### ISSUE TITLE
Crash on style transition

### ISSUE THREAD

**Issue by asalliou** [mapbox/mapbox-gl-native#11078] opened 2018-01-29 12:55 UTC
**Platform:** iOS
**Mapbox SDK version:** ios-v3.7.3

### Steps to trigger behavior

 1. Display a map style with extrusions (extrusions should be visible)
 2. Switch to another style without extrusions but with equivalent layers & sources (https://gist.github.com/asalliou/4058975f595a75274659370d4ebedaed)

### Actual behavior

App crashes

`
Assertion failed: (dynamic_cast<FillBucket*>(tile.tile.getBucket(*baseImpl))), function render, file /Users/asalliou/Documents/3rdParty/mapbox/mapbox-gl-native/src/mbgl/renderer/layers/render_fill_layer.cpp, line 64.
`

**Comment by jmkiley** [comment] 2018-01-29 16:27
Hey @asalliou -

Thank you for the sample code. It looks like you may be adding the sources and layers before the new style has finished loading. Could you check whether you are updating the sources and layers before [mapView:didFinishLoadingStyle](https://www.mapbox.com/ios-sdk/api/3.7.3/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didFinishLoadingStyle:) is called?

**Comment by asalliou** [comment] 2018-01-30 12:14
I made a quick sample to alternate styles only : https://github.com/asalliou/MapboxCycleStyleCrash/blob/master/MapboxCycleStyleCrash/ViewController.swift
The crash is still here

**Comment by EmperiorEric** [comment] 2018-02-12 05:53
Could this be related? We're seeing a crash when switching to specific styles as well.

<img width="446" alt="screen shot 2018-02-11 at 9 52 59 pm" src="https://user-images.githubusercontent.com/337916/36084853-f691ce9e-0f75-11e8-9326-c3d25c8ff5c8.png">

**Comment by asalliou** [comment] 2018-03-12 17:30
It seems to be similar.

![crash](https://user-images.githubusercontent.com/404209/37299391-7117284e-2623-11e8-8e84-1b6068e318c6.png)

**Comment by iDevid** [comment] 2018-07-24 12:21
Same here with extruded styles.

**Comment by friedbunny** [comment] 2018-07-24 14:46
We really appreciate this report and reproductions, @asalliou — we’ve recently started investigating this over at #12432 and I’m going to close this issue to consolidate, but please feel free to follow along and contribute there. 🙇 

/cc @jfirebaugh

**Closed by friedbunny** 2018-07-24 14:46 UTC
Labels: Core, crash

**Comment by asalliou** [comment] 2018-07-25 07:01
Thank you @friedbunny , I will test this fix as soon as a new version is available.
