### ISSUE TITLE
Missing labels in shields around Hiroshima

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#3487] opened 2016-01-08 23:15 UTC
![screen shot 2016-01-08 at 12 18 38 pm](https://cloud.githubusercontent.com/assets/1149913/12211977/3fbcc9dc-b633-11e5-8d1e-143586cea346.png)

Seeing this in both node-mbgl and mapbox-gl-js, so I suspect it may be a caused by a combination of the underlying data in the vector tiles ([Japanese half-width numerals perhaps?](http://jrgraphix.net/r/Unicode/FF00-FFEF)) and the fontstack used by this style - need to investigate further.

**Comment by friedbunny** [comment] 2016-01-09 05:54
The missing characters are kanji, such as `中国道`:

![screen shot 2016-01-09 at 12 48 54 am](https://cloud.githubusercontent.com/assets/1198851/12214641/dc0d61ca-b66a-11e5-84ed-ce1699b36158.png)

I'm not seeing this exact problem [in production](https://api.mapbox.com/styles/v1/mapbox/streets-v8.html?access_token=pk.eyJ1IjoiZnJpZWRidW5ueSIsImEiOiIyMTIxYTQ4NTFlNzRlNWE5NGRjZGQ0OTc1ZGRjYWRhMSJ9.0n-f9tEJdMayzhX_E5qZCg#8.53/34.3121/131.8261), but I suspect it's a symptom of the glyph corruption that I do still see regularly when Asian character sets are involved.

**Comment by mikemorris** [comment] 2016-01-11 16:39
Thanks for digging deeper @friedbunny - the reason I didn't initially suspect glyph corruption/atlas overflow is because of how few non-Latin glyphs had been loaded in the view.

**Comment by friedbunny** [comment] 2016-05-20 13:53
Duplicate of #1681.

**Closed by friedbunny** 2016-05-20 13:53 UTC
Labels: text rendering
