### ISSUE TITLE
[glfw] Test application doesn't run after replacing libuv with native implementations

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#4605] opened 2016-04-05 12:33 UTC
I am unable to launch `mapbox-gl` GLFW client in OSX (e.g. via `make run-linux`) - the application immediately returns after initialized. I've bisected the code and it points out to `879382f72405edd1840d2f37744bcba49131859a`, which replaces `libuv` with native implementations.

I am going to debug `platform/darwin/src/run_loop.cpp` and see if I can find the root cause, but it looks like the run loop is not being run.

👀 @jfirebaugh @tmpsantos @kkaefer

**Comment by 1ec5** [comment] 2016-04-05 14:21
Duplicate of #4578.

**Closed by 1ec5** 2016-04-05 14:21 UTC

**Comment by brunoabinader** [comment] 2016-04-05 14:26
Oh, thanks @1ec5 :)
