### ISSUE TITLE
GLMapView hides / fails to load annotations when I change map style 

### ISSUE THREAD

**Issue by ejdslayer** [mapbox/mapbox-gl-native#2235] opened 2015-09-02 17:24 UTC
I have just started using the latest released version of Mapbox for iOS, and have setup a map with annotations successfully. The annotations needed custom images based upon a priority value passed by the API. To do this I am using imageForAnnotation as follows:

    - (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(id <MGLAnnotation>)annotation
    {
        CustomAnnotation *custom = (CustomAnnotation *)annotation;
        
        NSString *name = nil;
        if (custom.priority == 1 || custom.priority == 2)
            name = @"dot_red";
        else if (custom.priority == 3)
            name = @"dot_orange";
        else if (custom.priority > 3)
            name = @"dot_yellow";
        else if (custom.priority == -11)
            name = @"dot_purple";
        
        MGLAnnotationImage *annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:name];
        
        if ( ! annotationImage)
        {
            UIImage *annoImage = [UIImage imageNamed:name];
            annotationImage = [MGLAnnotationImage annotationImageWithImage:annoImage reuseIdentifier:name];
        }
        
        return annotationImage;
    }

However, when I change the map style all of the annotations disappear, the map change code is below:

    [_mapView setStyleURL:kMapSatelliteStyleURL];
                [button setTitle:@"Regular" forState:UIControlStateNormal];
                button.tag = 1;

Now when I pan around the map, I notice that the following pops up in the debug window '{Worker}[Sprite]: Can't find sprite named'. This is apparently an issue caused by the asynchronous loading (Source: https://github.com/mapbox/mapbox-gl-native/issues/1877), however, the suggested workaround is to implement imageForAnnotation which I do anyway. 

I have attached 3 screenshots below of me toggling the map type:

![ios simulator screen shot 28 aug 2015 11 47 28](https://cloud.githubusercontent.com/assets/5479823/9638658/cc6d453a-519f-11e5-84a5-cab63269dd1a.png)
![ios simulator screen shot 28 aug 2015 11 47 35](https://cloud.githubusercontent.com/assets/5479823/9638663/cf5485ec-519f-11e5-9a1e-1c189df9be82.png)
![ios simulator screen shot 28 aug 2015 11 47 42](https://cloud.githubusercontent.com/assets/5479823/9638666/d32e61e2-519f-11e5-83a7-27ec22ffac10.png)

As you can see, even when toggling back to the original map again the images never re-appear. The annotations are definitely being added again (subsection of the broken in to imageForAnnotation po below):

    po mapView.annotations
    <__NSArrayI 0x7fc1b8dec650>(
    <CustomAnnotation: 0x7fc1b8b4b450>,
    <CustomAnnotation: 0x7fc1b3df6780>
    )

Has anyone else come across this issue and know how to fix it? I am wondering whether the changing of map style re-orders the map layers, therefore annotations are drawn below the map tiles?

**Comment by 1ec5** [comment] 2015-09-02 17:52
Duplicate of #1488.

**Closed by 1ec5** 2015-09-02 17:52 UTC
