### ISSUE TITLE
Paint properties should take effect immediately

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6435] opened 2016-09-22 21:58 UTC
With #6018, a developer could set a paint property and see it reflected on the map immediately. #6201 rolled back that change, so that only changes to layout properties and filters would take effect immediately. Now, when you set a circle layer’s color, for example, you have to explicitly set its visibility too. This is contrary to the developer’s expectation; paint properties should take effect immediately.

/cc @jfirebaugh @incanus

**Comment by incanus** [comment] 2016-09-22 21:59
Revealed by the demo beefing I'm doing over in https://github.com/mapbox/mapbox-gl-native/pull/6433.

**Comment by jfirebaugh** [comment] 2016-09-22 23:11
If this changed in #6201, it was unintentional. When a paint property is modified, the intended behavior is that `Style::onLayerPaintPropertyChanged` is called, triggering recalculation and repaint on the next turn of the event loop. Want to investigate where that's going awry?

**Comment by 1ec5** [comment] 2016-09-22 23:49
@incanus, is there really a bug here? I just went off the presence of redundant `visible` assignments in #6433.

**Comment by jfirebaugh** [comment] 2016-09-23 00:09
This turned out not to be reproducible.

**Comment by incanus** [comment] 2016-09-23 00:10
Not seeing a problem now that I'm using a new device sim. Probably style caching-related on my well-worn sim. Removed triggers in f6303e49e8fc68e7b6a3eeae8aadd1574db86597 in my current work & closing here.

**Closed by jfirebaugh** 2016-09-23 00:09 UTC
Labels: bug, iOS, macOS, release blocker, runtime styling
