### ISSUE TITLE
Area fill colors get corrupted upon scroll (Android).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1702] opened 2015-06-10 04:05 UTC
This is consistently reproducible on Samsung Nexus S. 
Just go to any area with fill colors and scroll.  I've attached two screenshots from Samsung Nexus S (one that shows expected fill colors and the other that shows corrupted fill colors).

![corrupted_fillcolor](https://cloud.githubusercontent.com/assets/8890269/8074764/258a51fa-0eeb-11e5-8f5e-11a0fbd78ec1.png)
![expected_fillcolor](https://cloud.githubusercontent.com/assets/8890269/8074763/258a1d84-0eeb-11e5-8fb2-cadf647a84f7.png)

**Comment by mb12** [comment] 2015-06-10 04:11
Here is another screenshot illustrating corruption.

![another_corruption](https://cloud.githubusercontent.com/assets/8890269/8074834/f40c3426-0eeb-11e5-8756-220ae285daac.png)

**Comment by ljbade** [comment] 2015-06-10 11:46
Hmm this is interesting.

Have you seen this before on iOS (or Android) @kkaefer @1ec5 ? I haven't

**Comment by ljbade** [comment] 2015-06-10 11:47
@mb12 Does this only happen on Nexus S? Have you been able to reproduce this on other phones?

**Comment by 1ec5** [comment] 2015-06-10 14:33
I haven't seen this issue on iOS. The closest thing I can think of is that fills are all screwed up after loading Pencil style.

**Comment by kkaefer** [comment] 2015-06-10 14:37
Never seen this issue on my Moto G 2 test device.

**Comment by mb12** [comment] 2015-06-10 16:36
@ljbade Consistently reproducible on Nexus S. Does not happen on Note 3.
@1ec5  What is the pencil style issue you are referring to? Is it consistently reproducible?

**Comment by mb12** [comment] 2015-06-10 16:40
The "Light" style shows red lines and smudges even without scrolling.

![light_style](https://cloud.githubusercontent.com/assets/8890269/8088197/71d87f5a-0f54-11e5-861e-366eaa7aa61c.png)

**Comment by 1ec5** [comment] 2015-06-10 16:42
> What is the pencil style issue you are referring to? Is it consistently reproducible?

See #636 and https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/pencil-v7.json.

**Comment by mb12** [comment] 2015-06-10 17:13
Sometimes lines disappear on scrolling as well. I've attached two screenshots (one with lines and one without lines).

![lines_as_expected](https://cloud.githubusercontent.com/assets/8890269/8088741/8171df84-0f58-11e5-938f-a6864ff97ef8.png)
![lines_disappear](https://cloud.githubusercontent.com/assets/8890269/8088740/8171c300-0f58-11e5-8582-95cc30ce592c.png)

**Comment by ljbade** [comment] 2015-06-11 00:04
@mb12 Can you get the GL info from your phone? It will be in the app logcat towards the start.

This is either an interaction with some specific set of GL extensions your phone has, or some sort of bug in the GPU driver for your phone.

**Comment by mb12** [comment] 2015-06-11 00:10
Is this what you are looking for?

https://gist.github.com/mb12/cf952c89c26137dcc3a4

**Comment by ljbade** [comment] 2015-06-11 13:03
@mb12 thanks

**Comment by erf** [comment] 2015-06-16 07:55
I have a similar problem on a Samsung S3 (Android version 4.4.4). Some tiles don't always load it seems or rendering is invalid.

**Comment by mb12** [comment] 2015-07-28 05:10
@ljbade and @bleege   Is it possible to analyze this for B1? There are at least two devices where this reproduces consistently (S3 and Nexus S). 

I would be more than happy to  mail you  one of my test devices to reproduce the issue.
I also checked that Nexus S is available for $30 or so on ebay (Buy now price).

**Comment by bleege** [comment] 2015-07-28 05:28
@mb12 Could you provide some more information on the S3?  Specifically, Android API number that your device is running.  It's an older phone that [looks like it originally came with Android 2.3](http://www.gsmarena.com/samsung_google_nexus_s-3620.php).

**Comment by mb12** [comment] 2015-07-28 05:51
It's 4.1.2
![screenshot_2015-07-27-22-45-15](https://cloud.githubusercontent.com/assets/8890269/8924375/f8036ab8-34b1-11e5-96e9-9c11fbc80c87.png)

**Comment by mb12** [comment] 2015-08-03 19:13
@ljbade The symptoms of this bug look very similar to z fighting. Is it possible to have this code reviewed (esp. the usage of glDepthRange, glDepthMask in translucent phase etc)?  z fighting may also explain why symbols/lines sometimes disappear upon panning or just do not show up on some Android devices.  I've verified that the Depth buffer size is 24 bits on the device where it reproduces (Its also 24 bits on where it does not reproduce). 

https://en.wikipedia.org/wiki/Z-fighting

**Comment by mb12** [comment] 2015-08-10 21:21
@kkaefer , @ansis , @jfirebaugh Is it possible to prioritize this bug since it  happens on a variety of Android devices (Similar symptoms have also been reported on S3, Lenovo Tab, Nexus 10 running Android 5.1). It looks like a combination of several bugs in the opengl client code. I've included some of the analysis below.

1. There is definitely a bug in antialiasing code for fill buckets.  Just commenting out the relevant code in Painter::renderFill gets rid of the reddish fringe line around fills.

2. Usage of  strata_epsilon can also cause issues. The strata_epsilon value is 2^-16. This will definitely have an issue with some android devices since we request EGL configurations with depth buffer >= 16 bits. There is no need to use strata_epsilon. It can be logically changed to use strataThickness/2 etc to improve precision issues.

3. Depth precision can also be improved by adding a zlevel to RenderItem and incrementing it on a per layer basis instead of per tile basis.

**Comment by kkaefer** [comment] 2015-08-11 13:55
@mb12: thanks for your observations, certainly looks like these are multiple bugs. Can you check whether https://github.com/mapbox/mapbox-gl-native/tree/fix-android-rendering-bugs fixes any of the above bugs for you?

**Comment by mb12** [comment] 2015-08-11 16:17
This still reproduces the issue.

1.)  For lines, very frequently the map goes to a state, where panning to one side causes the line to disappear and panning to the other makes them appear (similar to this issue https://github.com/mapbox/mapbox-gl-native/issues/1478). This happens on master repo as well. I've attached two screenshots showing the line disappearance issue.

2.) Red lines around fills still persists and they expand to fill the area upon pan.


![screenshot_2015-08-11-08-52-50](https://cloud.githubusercontent.com/assets/8890269/9202971/3412c35c-4009-11e5-9536-9e4679ca5f99.png)
![screenshot_2015-08-11-08-53-31](https://cloud.githubusercontent.com/assets/8890269/9202972/3413f24a-4009-11e5-9a7c-e109c1c4ab5d.png)

**Comment by mb12** [comment] 2015-08-11 18:16
Here is more information regarding the lines disappearing issue:

1.) Lines disappear/appear at a point a new tile enters/leaves the Viewport.  By this I mean, with renderDebugFrame turned on, move the red frame line into and out of the ViewPort.

2.) Whenever this happens, the list of RenderItems changes, resulting in new depth ranges being mapped to each RenderItem bucket. 

3.) The issue happens independently of fill buckets. Remove fill style layers from style.json or always return nullptr from TileWorker::createFillBucket.

**Comment by mb12** [comment] 2015-08-13 21:54
@kkaefer I have been able to narrow down the line disappearance issue to LineSdfShader. If I get rid of dashed lines from the style or make the equivalent change  in painter_line.cpp the disappearing line issue goes away. I am unable to figure out how panning can interact with LineSdfShader causing lines to disappear.  Please do let me know what else I can try to narrow down the issue further.

**Comment by erf** [comment] 2015-08-20 12:17
Map is really messed up now in commit d400fe0c91b66e066f50dbf3615db68af8895a10 on a samsung s3 device

**Comment by bleege** [comment] 2015-08-31 20:02
Bumped to `0.2.0` as both phones are on the older side and likely to have a smaller population.  [Nexus S](https://en.wikipedia.org/wiki/Nexus_S) is from 2010, while the [Samsung S3](https://en.wikipedia.org/wiki/Samsung_Galaxy_S_III) is from 2012.  Will treat as a Known Issue in the mean time.

**Comment by erf** [comment] 2015-08-31 22:03
The samsung s3 is the most popular android phone accourding to appbrain.com

http://www.appbrain.com/stats/top-android-phones

**Comment by ljbade** [comment] 2015-10-30 02:14
@erf Are you still seeing this issue?

**Comment by adam-mapbox** [comment] 2015-12-11 23:45
FYI I have a Galaxy S3, running 4.4.2, and I can't reproduce any of these issues with the latest master.  Not sure if we fixed it, or if it's the Android version, or what.

![device-2015-12-11-154422](https://cloud.githubusercontent.com/assets/14084862/11758301/28d1c52c-a01e-11e5-8a88-136db5ce5d22.png)

**Comment by adam-mapbox** [comment] 2015-12-11 23:55
It's been a while since we've heard much noise about this particular issue, and we haven't been able to reproduce it in-house.  Can we get a status check on this @mb12 @erf and see if things are still wonky?  A lot has changed in the meantime and it's possible that either we fixed this inadvertently or that it only shows up on very old Android versions.

**Comment by mb12** [comment] 2015-12-12 00:07
@adam-mapbox It consistently reproduces on Galaxy Nexus S. @ljbade also purchased one from ebay and confirmed that he was able to reproduce the issue. This issue no longer reproduces on S3.

**Comment by bleege** [comment] 2015-12-12 04:39
@mb12 Can you confirm what version of Android (API level would be ideal) that the Galaxy Nexus S is running?  According to [Wikipedia it's running 2.3.3](https://en.wikipedia.org/wiki/Nexus_S).

**Comment by tobrun** [comment] 2016-03-13 19:45
I haven't seen this issue on other devices, including the screenshots taken from 220 devices on AWS device farm and the Nexus S is a device from 2010 and is too old to keep supporting. Closing.

**Closed by tobrun** 2016-03-13 19:45 UTC
Labels: Android, bug, P1

**Comment by mb12** [comment] 2016-03-14 01:26
@tobrun Do you know if there is a way to mark a particular device as unsupported in AndroidManifest.xml?

**Comment by tobrun** [comment] 2016-03-14 02:20
Not in the AndroidManifest.xml but you can do this in `Google Play Developer Console`:
Here is for example a screenshot where you can disable the mentioned device:
<img width="801" alt="screen shot 2016-03-13 at 22 19 47" src="https://cloud.githubusercontent.com/assets/2151639/13733484/ce11f7ac-e969-11e5-97c2-b40e29e16640.png">
