### ISSUE TITLE
Sanity check access tokens

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1647] opened 2015-05-27 06:29 UTC
If the Mapbox access token scheme is known and stable, we should do some pre-validation to see if a developer's access token is sane when it is set, before using it for network requests. Basic length and character set checks would be good enough, probably.

Trying to initialize a map with variety of bad access tokens throws not always helpful errors:

**Case 1**

```objc
[MGLAccountManager setAccessToken:@"<mapbox-access-token-here>"];
```

>[ERROR] {0}{Map}[ResourceLoader]: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]: The operation couldn’t be completed. (NSURLErrorDomain error -1002.)

`NSURLErrorDomain -1002` is `NSURLErrorUnsupportedURL`.

**Case 2**

```objc
[MGLAccountManager setAccessToken:@"pk.asdlfkjasdflkjasdflkasjdflkasjflaksjfla"];
```

>  [ERROR] {0}{Map}[ResourceLoader]: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]: HTTP status code 401

**Case 3**

```objc
[MGLAccountManager setAccessToken:@"jason"];
```
> [ERROR] {0}{Map}[ResourceLoader]: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]: 

No error reason given, should be `HTTP status code 401`.

**Comment by jfirebaugh** [comment] 2015-05-27 16:25
Preflighting wouldn't catch a revoked access token or many kinds of typos (e.g. accidentally dropped the last character). I'd be satisfied if:

* All three were 401 errors
* It printed the requested URL, rather than the `mapbox://` URL

Can you investigate what it would take to do both of those?

**Comment by friedbunny** [comment] 2015-05-27 16:39
@jfirebaugh I'm on it.

**Comment by friedbunny** [comment] 2015-05-27 17:14
In Case 1, using `< >` brackets is the problem as those are illegal characters. Probably not a common case, but we could catch this by validating against URL-legal characters:

`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=`

Case 3 is a result of... request caching? It starts dropping the `401` error after the first run and it doesn't come back.

**Comment by friedbunny** [comment] 2015-05-27 17:57
And the answer to getting the actual request URL is: I can't find a way, but I'm sure there is one.

[Here's the fail block in `Source::load()`.](https://github.com/mapbox/mapbox-gl-native/blob/f4707f72e0ce7f1c40337c72ae5c0c0c8ef0efed/src/mbgl/map/source.cpp#L153-L158)

I'm going to have to leave it here, for now.

**Comment by 1ec5** [comment] 2015-05-27 18:05
You can transform a style URL to the actual URL using [`normalizeStyleURL()`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/mapbox.cpp#L35).

**Comment by friedbunny** [comment] 2015-05-27 18:19
Heh, I spent a while poking around the stack to see if it was already there, but just normalizing the URL again would be much easier. :wink: So that's settled.

Are we sure that we don't want to throw a friendlier error/warning if access tokens are obviously bad?

**Comment by 1ec5** [comment] 2015-05-28 00:21
One reason I pushed to have Info.plist be the usual place to put access tokens is so that we could avoid somewhat cheesy code samples like `accessToken:@"<insert real access token here and don't forget to remove the angle brackets but keep the double quotes>"`. But if we must continue to put placeholders in code, the best way to format the placeholders would be `accessToken:<#accessToken#>` (IIRC, can't check on my phone), which turns into a blue bubble in Xcode, just like the ones you get from code completion. Because it isn't a string literal or valid identifier, the code will fail to compile until the real access token is entered as a string literal.

**Comment by 1ec5** [comment] 2015-05-28 02:27
Yep: type “<#access token#>” into Xcode’s source code editor (any language) and it immediately turns into a bubble and a compiler error saying “Expected expression”:

![token](https://cloud.githubusercontent.com/assets/1231218/7851529/5d388544-04a6-11e5-983b-c794771aad3e.png)
![tokenerror](https://cloud.githubusercontent.com/assets/1231218/7851530/5d39643c-04a6-11e5-996d-145fdd03ccb3.png)

**Comment by kkaefer** [comment] 2015-05-28 12:06
> In Case 1, using < > brackets is the problem as those are illegal characters. Probably not a common case, but we could catch this by validating against URL-legal characters:

We should just urlencode the token.

**Comment by friedbunny** [comment] 2015-05-28 17:35
@kkaefer I don't believe we'll need to make allowances for illegal characters in the access token: Mapbox controls the scheme and doesn't(?) use them.

For me, the question here is whether or not we should explicitly add checks that throw console errors/warnings in the case of obviously wrong access tokens.

**Comment by ljbade** [comment] 2015-06-02 00:07
Perhaps it is possible to do a preflight http request with the access token during init. Then throw an assert or something if you get a access token error back with an easy to understand error pointing to the documentation on access tokens.

That way you handle all the cases including revoked tokens.

**Comment by jfirebaugh** [comment] 2016-06-01 17:35
@friedbunny @cammace Are typo'd or otherwise invalid tokens a frequent support topic?

**Comment by cammace** [comment] 2016-06-02 15:02
@jfirebaugh Not on my end. On the Android side of things we make it pretty clear when you are missing the access token or if the app fails to launch due to a wrong token. App will crash with the error:

    FATAL EXCEPTION: main
                                                                Process: mapbox.mapboxnav, PID: 8509
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{mapbox.mapboxnav/mapbox.mapboxnav.MainActivity}: com.mapbox.mapboxsdk.exceptions.InvalidAccessTokenException: 
                                                                Using MapView requires setting a valid access token. Use setAccessToken on Mapview to provide one. 
                                                                Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
                                                                More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2625)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2686)
                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5969)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
                                                                 Caused by: com.mapbox.mapboxsdk.exceptions.InvalidAccessTokenException: 
                                                                Using MapView requires setting a valid access token. Use setAccessToken on Mapview to provide one. 
                                                                Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
                                                                More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
                                                                    at com.mapbox.mapboxsdk.MapboxAccountManager.validateAccessToken(MapboxAccountManager.java:71)
                                                                    at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:360)
                                                                    at mapbox.mapboxnav.MainActivity.onCreate(MainActivity.java:69)
                                                                    at android.app.Activity.performCreate(Activity.java:6669)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2578)
                                                                    	... 9 more

The logcat links are clickable and take you directly to the information needed. With the `4.1.0` release we've made access tokens even easier with the `MapboxAccountManager` which centralizes the location of a users access token. Users will only need to provide the access token once in their app.

**Comment by friedbunny** [comment] 2016-06-02 15:41
Bad tokens were a common support question at one point—back when entering a bad token and running the app would poison the local cache—but now this rarely rises to the level where we’re contacted.

The 401s now show consistently, but I’d still love it if our errors were a bit more informative.

**Comment by kkaefer** [comment] 2016-06-09 09:06
We could validate that the token itself is valid by checking that it begins with `pk.` or `sk.` and checking that the first part before the dot can be parsed as JSON after base64 decoding and checking for required keys.

I don't think preflighting the access token is necessary; it'll just complicate and delay the process of getting the map loaded.

**Comment by jfirebaugh** [comment] 2016-06-09 18:03
I don't think we should enforce a `pk` or `sk` prefix or base64 decoding. These are implementation details we have changed in the past and may change again, and enforcing them as they are today would be a potential forward incompatibility.

If there are specific error messages that could be improved, let's open newly-framed tickets. Closing here.

**Closed by jfirebaugh** 2016-06-09 18:03 UTC
