### ISSUE TITLE
Error in the iOS SDK 3.3.7

### ISSUE THREAD

**Issue by evgzor** [mapbox/mapbox-gl-native#8344] opened 2017-03-10 13:25 UTC
I got strange logs from map box : 
"Failed to make complete framebuffer object 8cd6"
"<CAEAGLLayer: 0x600000226860> to GL_RENDERBUFFER 1"
**Platform: iOS
**Mapbox SDK version: 3.37

### Steps to trigger behavior

 1. load map with annotations
 2. Get result with empty map with blue background
 3.

### Expected behavior
<img width="368" alt="screenshot 2017-03-10 16 23 57" src="https://cloud.githubusercontent.com/assets/5227456/23796818/fd25f762-05ad-11e7-808d-51a2ee97013f.png">

### Actual behavior
<img width="341" alt="screenshot 2017-03-10 16 22 36" src="https://cloud.githubusercontent.com/assets/5227456/23796799/e489eccc-05ad-11e7-93b9-40f53da8e5ef.png">

**Comment by jfirebaugh** [comment] 2017-03-10 15:56
Hi @evgzor, thanks for using Mapbox! Please try upgrading to the latest version of the iOS SDK, v3.4.2. Let us know if this issue isn't fixed in that version.

**Comment by evgzor** [comment] 2017-03-10 17:20
I installed 3.4.2 Mapbox-iOS-SDK and got absolutely the same issue @jfirebaugh please reopen the issue.

**Comment by jfirebaugh** [comment] 2017-03-10 17:26
Thanks @evgzor. Does this occur on any device, or only on specific models? Can you provide more detailed information about what's needed to reproduce this issue, or what you did differently between the "expected" and "actual" images? Or, ideally, supply a minimal test project that demonstrates the issue?

**Comment by evgzor** [comment] 2017-03-10 17:30
tested ios 10.1.1/10.2 iphone 6s/6. Its happens with bad network connection. For test project require a time.

**Comment by evgzor** [comment] 2017-03-13 09:28
Just to avoid another questions:  MGLMapView(frame: CGRect(x: 0, y: 0, width: 1.0, height: 1.0))

**Comment by evgzor** [comment] 2017-03-13 12:11
also u may try public func mapView(_ mapView: MGLMapView, regionWillChangeAnimated animated: Bool) {
    guard let adjustBounds = mapView.superview?.bounds else {
      return
    }
    mapView.frame = adjustBounds
  }

**Comment by friedbunny** [comment] 2017-03-13 16:21
Duplicate of #1572.

**Comment by evgzor** [comment] 2017-03-13 16:59
@friedbunny  Why u closed the ticket? Its not duplicated actually. The Initialization was  MGLMapView(frame: CGRect(x: 0, y: 0, width: 1.0, height: 1.0)) The problem was exactly that size changed from (1,1) to zero -- its different use case.

**Comment by friedbunny** [comment] 2017-03-14 03:36
I’ll reopen. When you have the time, please provide a precise description of the issue and the exact code that can be used to reproduce it — thanks.

**Comment by jfirebaugh** [comment] 2017-04-11 17:11
This will have been fixed by #8562.

**Closed by jfirebaugh** 2017-04-11 17:11 UTC
Labels: iOS, needs information
