### ISSUE TITLE
MyLocationTracking.TRACKING_FOLLOW does not cope well with map.setPadding

### ISSUE THREAD

**Issue by eddieux** [mapbox/mapbox-gl-native#6768] opened 2016-10-20 10:27 UTC
Doing map.setPadding while on user tracking mode (MyLocationTracking.TRACKING_FOLLOW) pushed the user dot away from the correct location.

**Platform:**
Android

**Mapbox SDK version:**
4.2.0-beta3
### Steps to trigger behavior

Reproducible in the Mapbox Dev Preview app, try setting some map padding e.g. map.setPadding(0, 0, 0, 400) after the enableLocationTracking() method call.
### Expected behavior

User dot stays in the correct location.
### Actual behavior

User dot pushed away to map center, which IMO is wrong.

**Comment by tobrun** [comment] 2016-10-20 10:52
Would you be able to retest with latest snapshot? 
We have fixed some bugs related to MyLocationView since beta.3.

I tested MapPaddingActivity from master and added:

```java
MyLocationViewSettings myLocationViewSettings = mapboxMap.getMyLocationViewSettings();
myLocationViewSettings.setPadding(0,250,0,0);
```

![device-2016-10-20-124812](https://cloud.githubusercontent.com/assets/2151639/19556903/9ed1a480-96c3-11e6-85eb-50d4ef183212.png)

Closing as resolved, feel free to comment if there is still an issue with the snapshot.
Thank you for reaching out and reporting your issue!

**Comment by eddieux** [comment] 2016-10-20 11:19
Thx for the quick reply.  I just ran the demo app against the snapshot (com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-SNAPSHOT), issue is unfortunately still there.

**Comment by tobrun** [comment] 2017-01-24 16:36
Haven't been able to reproduce this issue locally. Feel free to add more information if still reproducible from your end. Closing.

**Closed by tobrun** 2017-01-24 16:36 UTC
Labels: Android
