### ISSUE TITLE
Add delegate method for manipulating user location

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#7791] opened 2017-01-19 17:46 UTC
**Platform: iOS**
**Mapbox SDK version: master**

For navigation applications, it's important to keep the user snapped to the current road they're traveling on and reduce as much GPS noise as possible. Not only does this make for a more pleasant user experience, it's easier for the user to interpret maneuvers and safer.

My proposal is to add a delegate method that allows developers to hook into the internal location manager, change location update values as needed and then return a new value that is reflected in any follow mode.

/cc @1ec5 @frederoni @boundsj @pveugen

**Comment by 1ec5** [comment] 2017-01-19 18:45
Duplicate of #6867.

**Closed by 1ec5** 2017-01-19 18:45 UTC
Labels: iOS
