### ISSUE TITLE
Application crashing on launch screen while initialising mapView 

### ISSUE THREAD

**Issue by pallavis-webonise** [mapbox/mapbox-gl-native#7223] opened 2016-11-29 13:49 UTC
Hi , we witnessed  a large number of crashes being reported since our latest release ,with MapBox SDK version: 3.3.4 . The crash reports are pointing at Mapbox. I am unable to reproduce the issue on my side. I have attached a crash log for reference. I was initialising  the Mapview with no frame , might this be the possible reason for the crash. Any help is appreciated
[2016-11-24_17-39-05.1228_-0600-8b753b955745192bbde3d6d0c72132d952f344fd.txt](https://github.com/mapbox/mapbox-gl-native/files/619062/2016-11-24_17-39-05.1228_-0600-8b753b955745192bbde3d6d0c72132d952f344fd.txt)

**Comment by frederoni** [comment] 2016-11-29 16:30
Initializing an MGLMapView with no frame is a known issue that unfortunately won't be fixed in 3.4.
May I ask why you're initializing a map view with no frame?

This is likely a duplicate of #1572

**Comment by pallavis-webonise** [comment] 2016-11-30 05:22
@frederoni :I was using this in default init of a class. But we are unable to reproduce this crash , this happens to be occurring for some users only. Can you give us some steps to reproduce this issue and the reasons why it might be happening for some users only. We had released our previous version with same mapbox and we saw no crashes.

**Comment by friedbunny** [comment] 2016-11-30 16:25
As the crash you posted is unsymbolicated, it’s very difficult to be sure what’s actually happening. Please update to the latest stable version of the Mapbox iOS SDK ([v3.3.7](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.7)) and use the accompanying dSYM to symbolicate any subsequent crashes.

**Closed** 2017-02-11 00:33 UTC
Labels: crash, iOS
