### ISSUE TITLE
[node] Bindings for Node v8

### ISSUE THREAD

**Issue by edpop** [mapbox/mapbox-gl-native#10356] opened 2017-11-02 01:22 UTC
Hello.
Here is a Node v8 LTS released. Are you going to add bindings for this version, any ETA?
Thanks.

**Comment by jfirebaugh** [comment] 2017-11-02 01:34
Duplicate of #10343.

**Closed by jfirebaugh** 2017-11-02 01:34 UTC

**Comment by edpop** [comment] 2017-11-02 01:41
Yep, sorry...
