### ISSUE TITLE
[Android] black road shields

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#12671] opened 2018-08-20 08:46 UTC
### Steps to reproduce

 1. Starts the "Press Map for Marker" sample
 2. Long press the map a marker to display

### Expected behavior
A marker is added and every thing goes right

### Actual behavior
A marker is added, but some road shields have become black

![black pannels](https://user-images.githubusercontent.com/6266608/44329965-23db6380-a466-11e8-9205-15f7353356e7.gif)

### Configuration

**Android versions:** 8.0.0 (API 26)
**Device models:** Nexys 6P (avd)
**Mapbox SDK versions:** 6.3.0

**Comment by mayardb** [comment] 2018-08-20 08:54
By the way, I am issuing the same behavior with the "Animated SymbolLayer" sample. It looks the same for animated markers.

![animated symbol layers](https://user-images.githubusercontent.com/6266608/44330396-28544c00-a467-11e8-8965-118ec9d31ecb.gif)

**Comment by LukasPaczos** [comment] 2018-08-20 12:11
Thanks for reporting this issues @mayardb!

Closing as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10829.

**Closed by LukasPaczos** 2018-08-20 12:11 UTC
