### ISSUE TITLE
[android] App crashed unexpectedly

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#10414] opened 2017-11-08 12:48 UTC
**Platform:** Android 6.0 Nexus 5
**Mapbox SDK version:** `release-agua` branch

Was testing test app activities and when I opened `Custom Dynamic InfoWindow` app crashed. I tried again later but couldn’t reproduce anymore.

```
                                           --------- beginning of crash
11-08 13:17:25.210 9066-14528/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 13856
                                                  Process: com.mapbox.mapboxsdk.testapp, PID: 9066
                                                  java.lang.Error: glDrawElements( static_cast<GLenum>(primitiveType), static_cast<GLsizei>(indexLength), GL_UNSIGNED_SHORT, reinterpret_cast<GLvoid*>(sizeof(uint16_t) * indexOffset)): Error GL_INVALID_OPERATION at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/gl/context.cpp:693
                                                      at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
                                                      at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:83)
                                                      at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:55)
                                                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
                                                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

cc @tobrun @ivovandongen

**Comment by Guardiola31337** [comment] 2017-11-17 13:12
I was able to reproduce OP with latest changes in `release-agua` 👀

![custom_dynamic_info_window_crash](https://user-images.githubusercontent.com/1668582/32948650-50f05c94-cba0-11e7-91d3-f044928d538f.gif)

```
11-17 14:08:01.666 17704-17704/com.mapbox.mapboxsdk.testapp E/TrackingSettings: Could not activate user location tracking: user did not accept the permission or permissions were not requested.
11-17 14:08:01.677 17704-17740/com.mapbox.mapboxsdk.testapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x99bfe790
11-17 14:08:01.683 17704-17740/com.mapbox.mapboxsdk.testapp D/OpenGLRenderer: endAllStagingAnimators on 0x9e76d400 (RippleDrawable) with handle 0x97f3e890
11-17 14:08:01.866 189-189/? W/SurfaceFlinger: couldn't log to binary event log: overflow.
11-17 14:08:01.949 17704-18228/com.mapbox.mapboxsdk.testapp W/Adreno-ES20: <gl_draw_error_checks:608>: GL_INVALID_OPERATION
11-17 14:08:01.967 17704-18228/com.mapbox.mapboxsdk.testapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x982252a0
11-17 14:08:01.977 17704-18228/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: GLThread 7724
                                                                              Process: com.mapbox.mapboxsdk.testapp, PID: 17704
                                                                              java.lang.Error: glDrawElements( static_cast<GLenum>(primitiveType), static_cast<GLsizei>(indexLength), GL_UNSIGNED_SHORT, reinterpret_cast<GLvoid*>(sizeof(uint16_t) * indexOffset)): Error GL_INVALID_OPERATION at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/gl/context.cpp:693
                                                                                  at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
                                                                                  at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:83)
                                                                                  at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:55)
                                                                                  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
                                                                                  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
11-17 14:08:01.978 774-3038/? W/ActivityManager:   Force finishing activity com.mapbox.mapboxsdk.testapp/.activity.infowindow.DynamicInfoWindowAdapterActivity
11-17 14:08:01.982 774-3038/? W/ActivityManager:   Force finishing activity com.mapbox.mapboxsdk.testapp/.activity.FeatureOverviewActivity
```

Device 👉 Nexus 5 (Android 6.0)

cc @tobrun @ivovandongen

**Comment by lilykaiser** [comment] 2017-12-01 17:53
@Guardiola31337 is this still consistently reproduceable?

**Comment by Guardiola31337** [comment] 2017-12-04 08:39
@lilykaiser yes, still it is.

Followed the same steps described in https://github.com/mapbox/mapbox-gl-native/issues/10414#issuecomment-345240128 (`release-agua` and Nexus 5) and got the same crash.

**Comment by lilykaiser** [comment] 2017-12-04 15:34
Thanks for confirming!

**Comment by amotzg** [comment] 2018-04-01 14:44
Seems related to (or a duplicate of) #11266

**Closed** 2018-12-07 05:31 UTC
Labels: Android, archived, crash
