### ISSUE TITLE
(Android) Map reloads map tiles on onResume

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14336] opened 2019-04-04 13:10 UTC
With the most recent MapBox version 7.3.0, the map started to fully reload when showing the mapview again. If I remember correctly, this has been fixed quite recently. Has something changed in this version to cause this behaviour?

### Configuration

**Android versions:** all
**Device models:**  all
**Mapbox SDK versions:** 7.3.0

**Comment by tobrun** [comment] 2019-04-04 13:33
this change happened as part of https://github.com/mapbox/mapbox-gl-native/pull/14127, For GLSurfaceView to support all possible use-case as recylerview and fragments this was a required change. You can avoid the reload by moving to a TextureView implementation instead.

**Closed by tobrun** 2019-04-04 13:33 UTC

**Comment by martinKindall** [comment] 2019-05-02 03:09
Hi, I'm having the same issue, I'm using Mapbox android sdk 7.3.2 on Android 6.0.1

-------------------------------------------------------------------------------------------
Action 1: on device rotation

Expected bevahiour: map doesn't reload

Result: Map reloads, and sometimes takes up to 5 seconds.
-------------------------------------------------------------------------------------------
Action 2: map Activity loses focus but is not destroyed (onStop)

Expected behaviour: map doesn't reload when returning to map Activity because it was not destroyed.

Result: Activity is not destroyed, but map reloads anyway, I have to wait some seconds to be able to use it again.
-------------------------------------------------------------------------------------------

"You can avoid the reload by moving to a TextureView implementation instead." 
Please explain how to do this, I don't know what does that mean nor did I found info on the official docs.

Thanks.

**Comment by tobrun** [comment] 2019-05-02 10:17
@martinKindall 

1. For not recreating your map when rotation changes:

```
<activity
  android:name=".MyActivity"
  android:configChanges="screenSize|smallestScreenSize
      |screenLayout|orientation"
/>
```

2. For enabling textureview:

```
MapboxMapOptions#textureMode(true)
```

or through xml with:

```
app:mapbox_renderTextureMode="true"
```

**Comment by martinKindall** [comment] 2019-05-03 18:25
@tobrun Thanks for the detailed and quick answer!! It's working.

**Comment by ChrisHelmsC** [comment] 2020-10-22 02:08
I'm seeing a similar issue. Note that I am not at all using ads. Possibly Mapbox related?
