### ISSUE TITLE
Opening InfoWindow after adding a marker causes the InfoWindow to get stuck

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#3016] opened 2015-11-12 23:25 UTC
This was found in Sirius.

![device-2015-11-11-202205](https://cloud.githubusercontent.com/assets/1215089/11087961/a9e2f542-88b2-11e5-9202-7a41b8f0810f.png)

/cc @tobrun

**Comment by ljbade** [comment] 2015-11-12 23:26
First change will be to make TestApp open InfoWindow on drop pin like Sirius.

**Comment by ljbade** [comment] 2015-11-12 23:28
Code from Sirius
```
    @Override
    public void onMapLongClick(@NonNull LatLng point) {
        MapView mapView = mMapView.get();
        if (mapView != null) {
            mapView.addMarker(new MarkerOptions()
                    .position(point)
                    .title("Dropped Pin")
                    .snippet("Tap for directions"))
                    .showInfoWindow();
        }
    }
```

**Comment by ljbade** [comment] 2015-11-12 23:34
Duh! `showInfoWindow()` is marked as internal use only!

I'm going to update JavaDoc to more clearly point to `MapView.selectMarker()`

**Comment by tobrun** [comment] 2015-11-13 07:39
I'm having issues with this when using setCoordinateBounds, I have documented this in #2719

**Comment by tobrun** [comment] 2016-01-12 08:47
Was not able to reproduce this anymore, closing

**Closed by tobrun** 2016-01-12 08:47 UTC
Labels: Android, bug, in progress
