### ISSUE TITLE
(Android) application becomes unresponsive to touch

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1941] opened 2015-07-28 01:53 UTC
I've seen this several times today. Here is the relevant info from logcat. 
(This is a regression since I started seeing this after I synced my repo. It doesn't happen with an older repo that I have).

I/InputDispatcher(  251): Application is not responding: Window{414f0940 com.mapbox.mapboxgl.testapp/com.mapbox.mapboxgl.testapp.MainActivity paused=false}.  It has been 5005.9ms since event, 5005.6ms since wait started.  Reason: Waiting because the touched window has not finished processing the input events that were previously delivered to it.
I/WindowManager(  251): Input event dispatching timed out sending to com.mapbox.mapboxgl.testapp/com.mapbox.mapboxgl.testapp.MainActivity
I/InputDispatcher(  251): Dropped event because it is stale.
I/InputDispatcher(  251): Dropped event because it is stale.
I/InputDispatcher(  251): Dropped event because it is stale.
I/InputDispatcher(  251): Dropped event because it is stale.

**Comment by ljbade** [comment] 2015-07-28 06:06
@bleege possibly related to recent `Activity` changes?

**Comment by mb12** [comment] 2015-07-28 06:11
I also see this sometimes in logcat  (something about no touchable window etc.).

I/InputDispatcher(  251): Application is not responding: AppWindowToken{42158df0 token=Token{41e1bc20 ActivityRecord{41a4ead8 com.mapbox.mapboxgl.testapp/.MainActivity}}}.  It has been 5003.9ms since event, 5002.8ms since wait started.  Reason: Waiting because there is no touchable window that can handle the event but there is focused application that may eventually add a new window when it finishes starting up.

**Comment by mb12** [comment] 2015-07-28 06:20
And after some time this shows in the logcat but the screen continue to stay dark/black.

W/ActivityManager(  251): Activity stop timeout for ActivityRecord{41922970 com.mapbox.mapboxgl.testapp/.MainActivity}
I/ActivityManager(  251): Activity reported stop, but no longer stopping: ActivityRecord{41922970 com.mapbox.mapboxgl.testapp/.MainActivity}

W/WindowManager(  251): App freeze timeout expired.
W/WindowManager(  251): Force clearing freeze: AppWindowToken{421cf8e8 token=Token{41c5d220 ActivityRecord{41922970 com.mapbox.mapboxgl.testapp/.MainActivity}}}

**Comment by bleege** [comment] 2015-07-28 16:28
@mb12 Can you describe what you're seeing this in / your setup?  Is this the TestGLApp running on simulator?  Are you using the new `0.0.1-SNAPSHOT` release in a standalone project?

**Comment by mb12** [comment] 2015-07-28 16:30
This is the testglapp running on Nexus S. I am building the mapboxgl sdk and then running the sample app.

**Comment by incanus** [comment] 2015-07-28 16:50
Are you seeing this with the same code on other devices @mb12?

**Comment by mb12** [comment] 2015-07-28 17:08
Yes, this happens even on higher end devices like Samsung Note 3. The log message is slightly different and less descriptive though (on Note 3).

I/InputDispatcher(  846): Dropping event because there is no touchable window at (562, 509).

I do not see this behavior with an older repo.  One Android specific change that I do not have in older repo is "Drive render from UI thread". I am not sure if that could cause this.

**Comment by ljbade** [comment] 2015-09-03 05:26
@mb12 Does this still happen with lastest `master`?

**Comment by ljbade** [comment] 2015-09-04 03:08
It is possible there are so many touch events coming in that the time it takes to process each event (which includes panning the map, recalculating labels, etc) is taking too long?

I have yet to notice any performance issues on my phones.

**Comment by mb12** [comment] 2015-09-04 03:16
Its most likely gone.  I will verify it the first thing tomorrow morning.

**Comment by incanus** [comment] 2015-09-08 17:27
Any update on this @mb12? I'm inclined to move to `0.2.0` if we can't easily replicate this widely.

**Comment by mb12** [comment] 2015-09-08 17:29
@incanus and @ljbade Sorry for the delay. I am testing it now. I will update within an hour or so.

**Comment by mb12** [comment] 2015-09-08 18:17
The behavior has changed now. It still crashes consistently.  It has something to do with rotation while animation is on. Here is how to reproduce it consistently. It happens even on modern devices like Note 3.

1.  Start pan animation
2.  Change device orientation while animation is on.
3.  The application crashes.

It looks like all objects are being purged (correctly) upon device rotation (since activity is destroyed). However HTTP requests are  not cancelled.

**Comment by mb12** [comment] 2015-09-08 18:32
@incanus and @ljbade We can prevent Activity from getting destroyed upon device orientation change by adding android:configChanges="keyboardHidden|orientation" in AndroidManifest.xml. 

However this still won't handle the common case of an android application with multiple acitvities.

**Comment by ljbade** [comment] 2015-09-08 21:42
@mb12 Yeah we should avoid that since there are other config changes that can trigger Activity tear down including possibly new ones in future OS releases.

I will have a look at this, might be related to the OkHTTP refactor.

**Comment by mb12** [comment] 2015-09-08 21:48
Under "Developer options", there is also a setting to "Destroy Activities Immediately".  This can be used to trigger such and other potential issues(esp  in save/restore instance state) more frequently. With this option set Activity will be destroyed immediately even for scenarios such as tapping on the "Home Button"

**Comment by ljbade** [comment] 2015-09-09 04:39
Yeah that makes it crash on my phone. Going to grab the log

**Comment by bleege** [comment] 2015-09-09 15:05
@ljbade Any update based on what you saw in the log?

**Comment by ljbade** [comment] 2015-09-10 00:29
@bleege created a new ticket since this seems to be a different bug then this touch issue: https://github.com/mapbox/mapbox-gl-native/issues/2295

**Comment by bleege** [comment] 2015-09-10 00:55
@ljbade Just to clarify you're talking about the Pan Animation vs the original Touch issue correct?

**Comment by ljbade** [comment] 2015-09-10 00:56
@bleege Yeah this is a crash vs not responding.

**Comment by ljbade** [comment] 2015-09-11 01:39
I think that this and https://github.com/mapbox/mapbox-gl-native/issues/1941 are related.

**Comment by kkaefer** [comment] 2015-09-15 15:13
I can reproduce this as well.

**Comment by bleege** [comment] 2015-09-15 15:54
@kkaefer Can you clarify?  Are you reproducing the 1) Unresponsive to touch portion or 2) Crash on Pan?

**Comment by bleege** [comment] 2015-09-15 16:02
I was able to reproduce Crash on Pan case by panning and then rotating the phone (see crash log).  This definitely seems to me like the recreating the Activity on rotation (natural Android process) is causing this.

My setup:
Running a3ea4acb7cb4d57ca2f5808b9b600d7c1b7b3cc7 from `master`
HTC M9

```
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Caveat: 12344
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Conformant: 69
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Color: 32
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Red: 8
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Green: 8
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Blue: 8
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Alpha: 8
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Alpha mask: 0
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Depth: 24
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Stencil: 8
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Sample buffers: 1
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: ...Samples: 4
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: Chosen config is 3
09-15 11:58:40.687  28551-28551/com.mapbox.mapboxgl.testapp I/mbgl﹕ {Main}[OpenGL]: Chosen window format is 2
09-15 11:58:40.697  28551-28781/com.mapbox.mapboxgl.testapp A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 28781 (b2G0RjI_gznrjtg)
09-15 11:58:40.697  28551-28781/com.mapbox.mapboxgl.testapp W/libc﹕ Security Level: (1), Debug inforamtion is controlled by the DUMPABLE flag.
```

**Comment by bleege** [comment] 2015-09-15 16:06
Since the original issue (unresponsive to touch) has been resolved based on @mb12 's [comment above](https://github.com/mapbox/mapbox-gl-native/issues/1941#issuecomment-138655147), I'm going to close this issue to prevent further confusion.  #2295 is where we'll track the Start Pan, Rotate Device, TestApp crashes issue.

**Comment by kkaefer** [comment] 2015-09-15 16:09
I couldn't get it to crash, but it was unresponsive.

**Comment by bleege** [comment] 2015-09-15 16:31
@kkaefer Ok.  Let's reopen this then.  Can you provide steps for reproducing the unresponsiveness?

**Comment by bleege** [comment] 2015-09-16 23:12
@kkaefer are you still seeing this as of #2345?

**Comment by bleege** [comment] 2015-09-17 14:45
@kkaefer is looking into this for us this morning.  should know more soon as to if this is still a problem or not.

**Comment by kkaefer** [comment] 2015-09-17 15:02
I'm still seeing this issue when violently rotation the device; the app locks up and shows a black screen only, and stops rendering actual maps.

**Comment by ljbade** [comment] 2015-09-22 01:08
@kkaefer @incanus @bleege I brought back the old curl HTTP implementation in https://github.com/mapbox/mapbox-gl-native/tree/android-curl

However that branch still has this freeze.

I think this means we can rule out OkHTTP implementation being the cause. This seems like a more general bug.

**Comment by ljbade** [comment] 2015-09-22 05:18
Been putting in some logging to try and figure this out.

So far I know the hang happens after `onResume`.

**Comment by ljbade** [comment] 2015-09-22 05:30
Enabled the JNI debug messages:
```
09-22 15:29:36.311    4269-4269/com.mapbox.mapboxgl.testapp V/MainActivity﹕ onResume begin
09-22 15:29:36.311    4269-4269/com.mapbox.mapboxgl.testapp D/mbgl﹕ {Main}[JNI]: nativeResume
09-22 15:29:36.311    4269-4269/com.mapbox.mapboxgl.testapp D/mbgl﹕ {Main}[Android]: NativeMapView::resume
09-22 15:29:36.311    4269-4269/com.mapbox.mapboxgl.testapp D/mbgl﹕ {Main}[Android]: Not resuming because we are not ready
09-22 15:29:36.311    4269-4269/com.mapbox.mapboxgl.testapp V/MainActivity﹕ onResume end
```

That not ready message is bad.

**Comment by ljbade** [comment] 2015-09-22 05:33
Aha `nativeCreateSurface` is never called for some reason after rotation.

I think this is related to the TextureView change.

**Comment by ljbade** [comment] 2015-09-22 05:53
Reason it never gets called is that main thread gets stuck in `nativeOnInvalidate`

**Comment by mb12** [comment] 2015-09-22 06:00
This matches with the following observation.

https://github.com/mapbox/mapbox-gl-native/issues/1941#issuecomment-125680998

**Comment by ljbade** [comment] 2015-09-22 06:07
I think I figured it out, normal flow for creating the activity when it doesn't feeze:
- `onCreate` (starts map paused)
- `onStart`
- `onResume` (calls `map->resume()`) - returns `Not resuming because we are not ready` as we don't yet have valid GL surface
- `onSurfaceTextureAvailable` - creates GL surface then calls `map->resume()`, this time it is successful and map starts running

When it freezes:
- `onCreate` (starts map paused)
- `onStart`
- `onResume` (calls `map->resume()`) - returns `Not resuming because we are not ready` as we don't yet have valid GL surface
- `onInvalidate`'s `Runnable()` - no idea where this comes from, perhaps from a latent `View.post()` on the old `Activity` just before it is destroyed (e.g. from the panning animation) which Android not so helpfully queues up after the new `Activity` is restored - this calls `map->renderSync()`

Since the map is still paused `map->renderSync()` never completes.

**Comment by ljbade** [comment] 2015-09-22 06:07
I think the check here is to check if the map is paused before we call `renderSync()`.

**Comment by ljbade** [comment] 2015-09-22 06:13
I'm going to add to `Map` an `isPaused()`

**Comment by ljbade** [comment] 2015-09-22 06:17
Sucess! :boom: 

That fixed it. Making a PR now.

**Comment by mb12** [comment] 2015-09-22 06:19
Awesome work @ljbade  !!!

**Comment by ljbade** [comment] 2015-09-22 06:25
PR done, waiting for Travis.

**Closed** 2015-09-22 06:39 UTC
Labels: Android, bug, in progress

**Comment by bleege** [comment] 2015-09-22 13:32
Great job troubleshooting this @ljbade!!!  I love the details about where and why things went off the rails.

:+1: :+1:

**Comment by bleege** [comment] 2015-09-22 15:34
SNAPSHOT 22 was just released with this fix in it (from `master`)
