### ISSUE TITLE
[iOS] Mapbox continuously asks for permission to access location on first launch.

### ISSUE THREAD

**Issue by rweindl** [mapbox/mapbox-gl-native#11225] opened 2018-02-16 20:58 UTC
Platform: iOS (only on Device not in Simulator)
Mapbox SDK version: 3.7.4

### Steps to trigger behavior
1. Configure the App to support MapBox and set `NSLocationWhenInUseUsageDescription` and `NSLocationAlwaysUsageDescription` in its `Info.plist`.
2. Instantiate a new `MGLMapView`.
3. Set `showsUserLocation` to `true`.

### Expected behavior
When a user opens the map the first time I want the popup `Allow "AppName" to access your location?` to appear exactly once.

### Actual behavior
When a user opens the map the first time the popup `Allow "AppName" to access your location?` appears in an infinite loop and I cannot tap any button like `Only While Using the App`, `Always Allows` or `Don't Allow`. The popup is visible for about 1 second and then reappears.

### Workaround
Downgrading to version 3.7.3 solves the issue on our devices.

### Screenshot
![2018-02-16 22 10 58](https://user-images.githubusercontent.com/2217226/36329464-4ff194f8-1366-11e8-9840-bae65d5c3034.gif)

**Comment by friedbunny** [comment] 2018-02-16 21:25
A few questions:

- Which iOS version(s) are you seeing this on?
- Which are you specifying: `NSLocationAlwaysUsageDescription` or `NSLocationAlwaysAndWhenInUseUsageDescription`? Both?
- Does the app a separate `CLLocationManager` that could be requesting permission?

**Comment by rweindl** [comment] 2018-02-16 21:29
Hi @friedbunny thanks for taking such a quick look on that issue. To your questions:
- iOS Version is 11.2.5
- Device is iPhone 7
- Both `NSLocationAlwaysUsageDescription` and `NSLocationAlwaysAndWhenInUseUsageDescription` are specified.
- App is not using another CLLocationManager.

**Comment by friedbunny** [comment] 2018-02-16 21:48
@rweindl Hrm, so I can’t reproduce this — neither by enabling `showsUserLocation` in `viewDidLoad` nor in a storyboard, with any combination of usage descriptions.

- Can you say more about how/where/when you instantiate the map view?
- Do you implement any of our [location delegate methods](https://www.mapbox.com/ios-sdk/api/3.7.4/Protocols/MGLMapViewDelegate.html#/Tracking%20User%20Location) or set any [user location properties](https://www.mapbox.com/ios-sdk/api/3.7.4/Classes/MGLMapView.html#/Displaying%20the%20User’s%20Location)?

**Comment by captainbarbosa** [comment] 2018-02-16 21:57
I can reproduce this with the [Mapbox Studio Preview app](https://itunes.apple.com/us/app/mapbox-studio-preview/id1208400007?mt=8).

**Comment by rweindl** [comment] 2018-02-16 22:09
Hi @friedbunny I created a small Test Environment illustrating this behavior. 
Just execute:
1. `pod install`
2. Set `MGLMapboxAccessToken` in the Info.plist
3. Select a Developer Team to deploy on device.
4. Build on Device.

### Zip File:
[MapBoxCrash.zip](https://github.com/mapbox/mapbox-gl-native/files/1732970/MapBoxCrash.zip)

### Screenshot:
![2018-02-16 23 06 14](https://user-images.githubusercontent.com/2217226/36331541-7d2183a4-136e-11e8-86a6-01411488b8c8.gif)

**Comment by friedbunny** [comment] 2018-02-16 23:16
Thanks for your help @rweindl and @captainbarbosa — this is happening because #11151 re-added a listener for `UIApplicationWillResignActiveNotification`. 

After a bit of preliminary digging, it looks like this is the sequence of events leading to the loop:

- The app gets `UIApplicationWillResignActiveNotification ` when the permission dialog appears.
- #11151 catches the notification and calls `sleepGL:`, which disables location services.
- The dialog disappears, because location services have been disabled and the permissions request effectively cancelled.
- With the dialog gone, the app gets `UIApplicationDidBecomeActiveNotification` and calls `wakeGL:`, which re-enables location services and asks for permission.

The quick fix would be to just remove the listener for `UIApplicationWillResignActiveNotification` (which we’ve evidently judged to be unnecessary in the past: https://github.com/mapbox/mapbox-gl-native/pull/2988), but perhaps we should also reevaluate `wakeGL:`/`sleepGL:`.

/cc @julianrex @1ec5

**Comment by rweindl** [comment] 2018-02-16 23:24
Thanks for identifying the issue that quickly and keeping us in the loop! We're using 3.7.3 in the meantime.

**Comment by friedbunny** [comment] 2018-02-17 02:35
Fixed by #11229, which is now available in Mapbox Maps SDK for iOS 3.7.5. Thanks again for reporting this issue and helping us fix it, @rweindl. 🙇

**Closed by friedbunny** 2018-02-17 02:35 UTC
Labels: bug, iOS
