### ISSUE TITLE
Qt SDK breaks on Broadcom Videocore IV

### ISSUE THREAD

**Issue by KK1423** [mapbox/mapbox-gl-native#9596] opened 2017-07-24 22:16 UTC
**Platform:** Qt 5.9 on Raspberry Pi 3
**Mapbox SDK version:** 3.4.4

### Steps to trigger behavior

 1. Build and deploy Qt from official repo (Using Linaro arm-linux-gnueabihf gcc version 5.3, and installing required runtime libraries)
 2. Build and deploy mapviewer example, with the menu bar ported to Quick Controls 2 or with mapboxgl hardcoded as default plugin
 3. Run and observe that roads and lines are missing

### Expected behavior
Roads and outlines are visible
### Actual behavior
Roads and outlines are not visible
![image](https://user-images.githubusercontent.com/10897532/28547396-a4af6424-709c-11e7-8623-f5b308526d99.png)

Issues #6454 and #4037 involve devices that, like the Raspberry Pi 3, use a Broadcom Videocore IV GPU, producing similar results. The fix in PR #9573 has no effect.

**Comment by jfirebaugh** [comment] 2017-07-24 22:24
cc @tmpsantos @brunoabinader

**Comment by jfirebaugh** [comment] 2017-07-25 04:26
Ah, VideoCore IV: duplicate of #7583.

**Closed by jfirebaugh** 2017-07-25 04:26 UTC
Labels: Qt

**Comment by timfrankentwf** [comment] 2017-11-22 16:26
Were you able to get mapboxGL running on RPi 3? 
If so, how?

**Comment by brunoabinader** [comment] 2017-11-24 13:07
> Were you able to get mapboxGL running on RPi 3?

We embed it as a plugin for QtLocation in Qt 5.9 - Qt provides a Yocto repository for that in the following link:

https://github.com/meta-qt5/meta-qt5

Documentation for the Mapbox GL plugin can be found on the link below:

https://doc.qt.io/qt-5/location-plugin-mapboxgl.html

**Comment by timfrankentwf** [comment] 2017-11-24 14:54
Thanks @brunoabinader !, I will look again into the Yocto-project. 
After few weeks, I was able to get Qt running with my own build from sources on Rasbian-Lite.
Everything works, except for MapboxGL (Mapbox itself works just fine).
I also couldn't find any good instructions on building a MapboxGL-supported Qt-build.
