### ISSUE TITLE
iOS: Tapping next to annotation triggers Annotation didSelect method

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#10523] opened 2017-11-21 18:03 UTC
**Platform:*iOS*
**Mapbox SDK version:*3.7.0*

### Steps to trigger behavior

 1. Add some MGLAnnotationImage annotations on map
 2. Implement mapView(_ mapView: MGLMapView, didSelect view: MGLAnnotation) function
 3. Tap next to an annotation

### Expected behavior

Nothing happens

### Actual behavior

annotation didSelect is called. See this screenshot:

![image-1](https://user-images.githubusercontent.com/10425157/33088638-750b10c8-ceee-11e7-9f3d-64f77a279bb7.jpg)

When tapping in the black marked zone between annotation 47 and 48, annotation 48 didSelect. I just upgraded from version 3.6, and this only happens in version 3.7.

**Comment by fabian-guerra** [comment] 2017-11-21 20:53
Hi, @nijs9. Is this the zoom level at what the issue is happening?

e.g. In this example I am tapping in the middle of this two annotations but since the zoom is far and we make a tappable area the annotation from the right get selected.
<img width="398" alt="fatfinger" src="https://user-images.githubusercontent.com/2745166/33096057-bedffcce-ced3-11e7-95df-728e433c7480.png">

If I increase the zoom and tap again the middle nothing gets selected.
<img width="395" alt="noselect" src="https://user-images.githubusercontent.com/2745166/33096153-0422dedc-ced4-11e7-90bb-81a7f3771566.png">

**Comment by nijs9** [comment] 2017-11-22 07:49
Hi @fabian-guerra. To simulate this case, you can add just one MGLannotionImage with:

`func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage?`

I disable callouts:

`func mapView(_ mapView: MGLMapView, annotationCanShowCallout annotation: MGLAnnotation) -> Bool {
        return false
    }`

And then I use the didSelect methode:

`func mapView(_ mapView: MGLMapView, didSelect view: MGLAnnotation)`

If I run the app and when I tab inside a certain radius around the Annotation, de didSelect method is triggered. Zoomlevel does not mather, but let's say you can test it on zoom level 17. In the screenshot below you can see my case.

<img width="159" alt="image-1" src="https://user-images.githubusercontent.com/10425157/33115561-baa243f4-cf61-11e7-9186-aa82371172cc.png">

You could say I have a transparent halo around my annotation image but that's not the case. If I tab in de black marked zone, the didSelect method for this annotation is triggered. I just downgraded to version 3.6.4, and there is no problem.

**Comment by fabian-guerra** [comment] 2017-11-30 19:31
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/10538

**Closed by fabian-guerra** 2017-11-30 19:31 UTC
Labels: annotations, iOS
