### ISSUE TITLE
Offline maps

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#584] opened 2014-11-10 20:33 UTC
It is a personal goal to have the ability to view maps without needing an Internet connection.

Very useful for activities such as bushwalking our mountain biking.

Plus we know there are others interested in this feature too.

**Comment by hallahan** [comment] 2015-03-16 20:52
Whatever happened with this issue? Is there now MBTiles support for Android? Is this done natively? This feature is a requirement for me to use this library as an Android app.

**Comment by incanus** [comment] 2015-03-16 20:53
There is not MBTiles support yet in this project. Offline support will be coming in a future release; pretty sure this will include MBTiles.

**Comment by hallahan** [comment] 2015-03-16 20:55
Darn, is there a branch this is being tried with? Is this going to be native C++ for all builds? For me, this is the most important feature I need. I'm interested in helping.

**Comment by incanus** [comment] 2015-03-16 21:00
There's no movement on it yet, AFAIK. Right now we are sprinting towards a series of iOS beta releases, after which we'll focus on Android and a broader feature set. I would expect it to be in C++, yes, with Java/ObjC bindings. 

Happy to take work in a branch, but it just likely won't get many eyeballs during March due to priorities elsewhere.

**Comment by kristfal** [comment] 2015-04-20 15:34
Hey,

I know this is a large feature that will be implemented later, but I'm very curious regd. the performance differences, so wondering:

Is there currently a more elegant way to load tiles bundled with an app besides doing [this](https://github.com/mapbox/mapbox-gl-native/blob/7827d4954cea5b4fcfce3f245aae2e8c66e0ccb2/test/fixtures/api/water.json) and then load individual .pbfs referenced through [a tilejson](https://github.com/mapbox/mapbox-gl-native/blob/7827d4954cea5b4fcfce3f245aae2e8c66e0ccb2/test/fixtures/tiles/streets.json)?

**Comment by xwz** [comment] 2015-05-15 09:11
I'm trying to have a go at providing a mbtiles source for offline use. There is some difference in what the sdk downloads from the tile server hosted by mapbox and that downloaded from the same url from the command line using curl. 

E.g. for the vector tile at `v4/mapbox.mapbox-streets-v6/14/15074/9831.vector.pbf` the sdk downloaded file 13405 bytes, the first few bytes are: (setting a break point some where in `http_request_nsurl.m`)

~~~
0000000: 1a83 080a 076c 616e 6475 7365 125f 0800  .....landuse._..
0000010: 1206 0000 0101 0202 1803 2251 0927 f615  .........."Q.'..
~~~

Where as download via the command line with curl it is 7842 bytes:
~~~
0000000: 1f8b 0800 0000 0000 0003 ad7b 797c 5445  ...........{y|TE
0000010: b67f 9fba 7bf5 9a9b 85ce 4d27 e974 1212  ....{.....M'.t..
~~~

Any idea what's going on? Next step is going to examine the data with mapnik-vector-tile tool.

**Comment by xwz** [comment] 2015-05-15 23:41
I've made some progress in adding mbtiles source. It is very basic at the moment, it simply loads tiles from the mbtiles file using sqlite.

**Comment by ljbade** [comment] 2015-05-18 02:55
@xwz Great, have you put your changes on GitHub?

**Comment by xwz** [comment] 2015-05-18 03:24
@ljbade See https://github.com/mapbox/mapbox-gl-native/compare/master...xwz:mbtiles-source

**Comment by frenos** [comment] 2015-05-20 09:04
Can we get a rough plan on where to sort this on the agenda? Beta2 will probably be too early, maybe Beta3?

**Comment by vespakoen** [comment] 2015-07-14 11:05
Great stuff, @xwz what is the reason that there is no pull request for your changes?

**Comment by nitrag** [comment] 2015-08-05 22:24
Bump/Vote! Want!

**Comment by erf** [comment] 2015-08-20 11:09
Same her! Please support this in Android.

**Comment by PaulEhrhardt** [comment] 2015-08-20 11:12
Yes, me too. Please add offline support.

**Comment by erf** [comment] 2015-08-20 11:31
What we need is to be able to point a style.json tiles source to a local file path for hosting .pbfs, fonts and sprites.

**Comment by frederik-jacques** [comment] 2015-08-20 11:54
This would be a great addon, we are developing citytour apps with Mapbox & local mbtile files.
It would be great to see a possibility to add local vector maps (smaller size then mbtile files), because our users don't need internet connectivity when they do a tour (most are on wifi only ipads)!

**Comment by chrisballinger** [comment] 2015-08-20 16:37
We use offline maps (mbtiles) in iBurn because there's no internet in the Black Rock Desert: https://github.com/burning-man-earth/iburn-ios

Super excited to add vector maps next year!

**Comment by incanus** [comment] 2015-08-20 16:58
I've started on some work to abstract a per-platform tile request hook over in [`platform-tile-hook`](https://github.com/mapbox/mapbox-gl-native/tree/platform-tile-hook), meaning iOS or Android could jump in with reads out of SQLite or what-have-you, eventually on a per-frame basis (for things like frames of video https://github.com/mapbox/mapbox-gl-native/issues/601 or weather rasters). I'm not in that work right now, but we should be picking it up again soon.

**Comment by mb12** [comment] 2015-08-20 17:07
@incanus Wouldn't this make it difficult for Mapbox to charge based on number of MapViews/metered usage etc? Also would this mean that metrics collection happen offline and periodically synced to mapbox?

**Comment by incanus** [comment] 2015-08-20 17:11
The business questions are further out, particularly because we promise no longer than 60s live time for metrics data on device before it's just discarded as part of our [TOS](https://www.mapbox.com/mobile-data-collection/). But this needs to happen on a technical level.

**Comment by chrisballinger** [comment] 2015-08-20 19:00
@incanus Oh hmm, would this mean we wouldn't be able to continue using the open source / free tier for offline vector maps in iBurn?

**Comment by incanus** [comment] 2015-08-20 19:01
I don’t think we’re sure yet. We will be digging into this more once we pick up the offline development again as a priority.

**Comment by chrisballinger** [comment] 2015-08-20 19:12
@incanus Please consider a free tier for verified open source projects! We operate on a $0 budget and really love what you guys are doing. Because you guys understand the value of open source tech, I've always recommended Mapbox to others, and have no problem with paying for commercial use. :)

**Comment by incanus** [comment] 2015-08-21 00:10
@chrisballinger Duly noted :-)

**Comment by ltressens** [comment] 2015-08-31 13:37
After reading all these comments, and my small knowledge of all distinct branches in this project, I have no clear idea if the Offline feature for Mapbox GL iOS is nearly ready, or if it has a public schedule.
So I welcome every answer to my comment :) Thanks

**Comment by tyjacobs** [comment] 2015-08-31 15:29
I too am actively working on an app for a client that needs offline maps.  The approach of having each user's device cache tiles while connected and then having them available offline is fine in our case.  That is, assuming we can programmatically cache on a background thread similar to what was mentioned above:

-beginDownloadingMapID:mapRegion:minimumZ:maximumZ:

For now, my project only needs to support iOS.  I am in the same boat as @ltressens, wondering if/when this capability will be available.

**Comment by nitrag** [comment] 2015-09-01 01:45
+1 Don't really care about the GL portion, need offline (mbtiles) file
capability!

**Comment by ltressens** [comment] 2015-09-01 08:11
Well, understand me well @nitrag. I *DO* care a lot about Mapbox GL.
I am already a user of Mapbox iOS SDK which allows caching for offline use (you should be happy).
My interest is in caching vector information for Mapbox GL.

**Comment by nitrag** [comment] 2015-09-01 13:36
Oops. I was speaking to needing offline support on the Android SDK. Maybe
that's a different Issue #.

**Comment by leimingdu** [comment] 2015-09-11 10:43
We are also developing an offline man using vector title, need cache all tiles for both iOS and android, any progress? whether it is possible to using sqlite DB? thanks

**Comment by incanus** [comment] 2015-09-11 16:30
No recent movement on this.

**Comment by ltressens** [comment] 2015-09-11 16:32
:(
Still on schedule or out of scope for a moment ?

**Comment by AlanPew** [comment] 2015-09-11 19:27
In addition to offline tiles, I've noticed that vector tiles cannot be used when setting the url similar to how the raster tiles can be set in the style.json file from an outside url.  Specifically, I've set the style.json source to use third party vector tiles similar to this Mapbox GL JS example using Mapzen vector tiles (https://www.mapbox.com/mapbox-gl-js/example/third-party/).  I've set up the source and style of the layer exactly like the third party source styling for Mapbox GL JS and the feature isn't available.   Are third party vector tiles going to be able to used as a GL layer, or are vector tiles only going to be allowed from a Mapbox url?  This might seem like a tangent from the original question, but I'm posting here because its of similar relevance to using vector mbtiles hosted on the iOS device (cannot use local mbtiles, only ones stored on Mapbox servers).  Is this going to be a feature similar to how raster tiles can use third party source, or is it not a priority right now?  Love how great the WebGL renders and looks and would love to see this availble.  Thanks for your hard work, @incanus .

**Comment by jfirebaugh** [comment] 2015-09-11 20:31
@AlanPew That should work. It's really a different issue -- can you open a separate ticket please?

**Comment by AlanPew** [comment] 2015-09-11 20:58
Will do @jfirebaugh.  Thanks for the heads up and sorry for straying from the original issue everybody.

**Comment by caBBAlainB** [comment] 2015-10-03 10:12
+1 to get offline MB for Android.

**Comment by erf** [comment] 2015-10-03 10:28
Supporting offline tiles in Android is fairly simple. Just run a local web server (https://github.com/NanoHttpd/nanohttpd) in a service, set your url to localhost and return the requested files from disk.

**Comment by kkaefer** [comment] 2015-10-03 14:26
@erf you can also just put them directly on disk and specify with `asset://tiles/{z}/{x}/{y}.pbf`

**Comment by erf** [comment] 2015-10-03 14:34
@kkaefer but that is just for the assets folder right? You can't point to files on a sdcard for example?

**Comment by erf** [comment] 2015-10-03 14:38
..that is saved during runtime

**Comment by ljbade** [comment] 2015-10-03 22:54
@erf Yeah has to be in assets folder. However it is possible to change that behaviour in C++.

**Comment by suraj-aahlaad** [comment] 2015-10-23 09:28
please any one tell me How to calculate the selected area of the map size before downloading the map.

**Comment by twbell** [comment] 2015-11-11 16:54
A quick heads-up here to note that we believe offline operation is critical to the future of mobile mapping, and we are therefore baking this capability at a low-level into both our iOS and Android clients. We intend our implementation to meet requirements for both performance (obviating bad network connections) and offline travel/planning ("download this area before I go there") . We will begin posting updates shortly to this ticket as we make progress.

**Comment by tikimcfee** [comment] 2015-12-16 16:23
Hey there!

I'd like to put in the similar +1 from @hallahan, @erf, @leimingdu, et al. MapBox is a proven and core asset in the production of our team's software solution. We cache tiles for offline use in iOS to great success, and have been pushing to implement the same feature set on Android. One of our biggest gating factors for this, though, is our clarity in what we can expect this GL push to mean for both mobile platforms in terms of overall client capability and release schedules. We would hate to spend parity-focused development time for an SDK right on the cusp of major changes!

Our critical scenarios and questions are, then, focused on:

1. Our mobile clients will move offline and online frequently - having map tiles available for users at all times is critical to our user experience around that scenario. 
To that end, we need to know if both Android and iOS will have the capability of caching tiles (raster or vector).

2. We are an agile team with limited development time, and rework being necessitated from staggered platform SDK releases are brutal for us. 
Will the SDKs be ready for both platforms at or around the same time? If not, is there an expected release schedule that we can keep in mind?

I think those listening in here would really appreciate a consolidated answer on this (I know my team will!). We also want to put out a hand for any sort of questions you might have for *us* on this, and another for any help we can lend in for testing or describing use cases in greater detail.

Thanks for the time on this, and again for picking up this feature with gusto!

**Comment by twbell** [comment] 2015-12-16 20:20
Copy that @tikimcfee.

1. Our approach here on the Mobile side is for broad feature parity between iOS and Android.  We expect this to be a stepping-stone approach where one platform leads and the other follows -- which leads first depends on te

**Comment by twbell** [comment] 2015-12-16 20:32
Copy that @tikimcfee.

Our approach on the Mobile side here is for broad feature parity between iOS and Android.  We expect this frequently to be a stepping-stone approach where one platform leads and the other follows in short order -- which leads first will vary depending on internal business priorities, but the goal is to minimize feature lag between the two platforms.

We want our mobile dev intentions to be lucid and reliable.  To this end we are keen to articulate our priorities and our concomitant release schedule wherever possible. The two caveats here are (1) we are starting very conservatively, and (2) we can expect to have internal business drivers that may divert resources on short notice.  

That being said, I would hope to continue to make our intentions more plain and our plans more specific as we continue to develop our mobile clients.

**Comment by tikimcfee** [comment] 2015-12-22 14:07
@twbell 

Just wanted to say thanks for the response to our questions. It's really a treat to hear back so quickly from the community! It's also great to see the strategy being adopted here, giving us an understanding of where we can place our goals and implementation strategies on our own roadmap.

**Comment by ryandury** [comment] 2015-12-31 21:34
Thank you for being in touch with us about this.. This is an exciting feature and would be an essential component in the region that my app will be utilized.

**Comment by zugaldia** [comment] 2016-01-04 23:36
Related: https://github.com/mapbox/mapbox-gl-native/pull/3424

**Comment by MarthzElena** [comment] 2016-01-05 21:21
Hi all! I'm really excited about this feature because is really necessary for the app I'm currently working on, and I'm already a user of mapbox so I really like how it works. I was wondering do you have any release dates (even for beta) for the offline maps feature on Android and/or iOS?

**Comment by twbell** [comment] 2016-01-05 21:25
Thanks @MarthzElena, @ryandury, @tikimcfee we're saying "Q1" now.  This feature is critical for our plans too.  Expect a more refined date on this thread when we can lock it in with unassuming confidence.

**Comment by Sh1mor1nka** [comment] 2016-01-11 20:23
Guys, i still don't understand does mapbox supports offline maps for iOS? On my device, iPod Touch 6 Gen, once i open maps, cached some location, reopen app, it's ok. Tomorrow i open maps and see black screen, what can it be? Thank you.

**Comment by friedbunny** [comment] 2016-01-11 21:26
The iOS SDK (`mbgl`, really) has passively cached requests for quite some time, but this cache is not guaranteed and is subject to expiration, etc. This is not what we call "offline support" and it is not directly configurable by the developer.

Offline support means that the developer will be able to explicitly download and store all the necessary assets for a defined area. This is not implemented yet and is what we're working on currently.

**Comment by Sh1mor1nka** [comment] 2016-01-11 21:46
@friedbunny Thank you for clear answer! I look forward to offline support :)

**Comment by gprokopchuk** [comment] 2016-01-12 15:27
Hi! How soon will you be able to show results with offline map in mapbox gl? And Will caching feature for custom areas on the map able in new builds?

**Comment by twbell** [comment] 2016-01-12 15:43
@gpsml we're talking about a Q1 release for this feature so you should see something in or before March.

**Comment by jmcazaux** [comment] 2016-01-15 07:32
Hi guys,
I am really looking forward to this feature as it would allow me switching to Mapbox & vector tiles which would really be a plus.

Just to make sure that this would be a fit, I have 2 questions though: 
- How would be defined the "download" area?
I need people to be able to download & cache map for a country. Some countries fit nicely in a rectangle, but not many.
It would be great if once could define the download area as a set of 1°x1° tiles for example.

- How "filtered" will be the vector data ?
In my maps, I am using the Mapbox Streets dataset, but (for example) I am not displaying residential streets, nor streams and ditches, and I do not need to go beyond zoom level 11.0.
Is the vector data going to filtered according to the styles and target zoom levels (or can that be specified at download time) in order to make the download as light as possible.

Many thanks for your reply.

JM

**Comment by jfirebaugh** [comment] 2016-01-15 16:22
In the first release of offline, an offline region will be specified by style URL, bounding box, and zoom range. We may add polygonal regions in a future release. We don't plan to support filtering individual vector tile features because the idea is that an offline map should work exactly the same as an online map, minus network traffic. Therefore if you want filtered vector tiles you will need to make your own tileset.

**Comment by jmcazaux** [comment] 2016-01-15 16:47
@jfirebaugh many thanks for you answer.

When you say "you need to make your own tileset" what do you mean?

Provided once could easily build a vector MBTiles file, could we "feed" it into the library for off mine use ?

Many thanks for any hint,
JM

**Comment by jfirebaugh** [comment] 2016-01-15 17:45
I mean construct vector tiles containing the data you want, and upload them to mapbox.com or host them yourself. That way the same tiles are used online and offline.

The initial release of offline will not support importing a preexisting offline database. We may add support for that in a future release.

**Comment by mb12** [comment] 2016-01-15 17:53
@jmcazaux You can use mapbox vector tiles and your own style to filter out anything you do not wish to render.  

https://www.mapbox.com/mapbox-gl-style-spec/#types-filter

**Comment by twbell** [comment] 2016-01-15 19:06
@jmcazaux note that the system will have limits on what can be downloaded for offline use, and it will be smaller than a country.  There will be size and performance constraints; guidance will follow.

**Comment by gmaclennan** [comment] 2016-01-15 19:08
Thank you for all the updates on this. One further question: will we be able to use local vector tiles, rather than downloading from a server? We will be building vector tiles dynamically in the app and want to render with mapbox-gl-native.

**Comment by jfirebaugh** [comment] 2016-01-15 19:18
Downloading is always via tile URL. If you want to generate tiles locally, run a local server and set the tile URL to a localhost URL.

**Comment by 2ndGAB** [comment] 2016-01-15 19:21
@twbell I don't really agree. Sure there are limitations but how do Sygic or TomTom do?

**Comment by twbell** [comment] 2016-01-15 21:34
@2ndGAB suggest we hold fire on debating this until I post more details on what the bounds on this feature will be.

**Comment by arifklk** [comment] 2016-01-19 21:29
Hello all, I am also very excited for offline support. Several weeks ago I sent an email to support team and they told me to planning to announce Offline Maps end of this month. Is it too early? Because as I see from messages Offline Usage is a work for Q1. 

It is kind of critical for us because we are building our project on offline maps and it would be great if it is possible to see a beta or something like that? Thanks.

**Comment by twbell** [comment] 2016-01-19 21:32
Q1; we'll announce here when we can put a stake in the ground publicly.

**Comment by twbell** [comment] 2016-02-03 17:15
Targeting release last two weeks of March; I will refine that window further, and give preliminary visibility, when I know more.

**Comment by nnhubbard** [comment] 2016-02-03 17:18
At any point are we able to beta test this?

**Comment by twbell** [comment] 2016-02-03 17:26
> give preliminary visibility, when I know more

Will release docs/capabilities as soon as I have them.  Do not intend to do a public beta; focus instead on a timely release.

**Comment by lucaswoj** [comment] 2016-02-03 22:10
@nnhubbard As always, you are welcome to test our code and track our progress in the `offline` branch. :smile:

**Comment by nzhuk** [comment] 2016-02-04 05:04
@twbell Thanks for the update!

**Comment by speechlogger** [comment] 2016-02-09 18:52
Will referring the map's source to local on-device raster-tiles through the [style json](https://www.mapbox.com/mapbox-gl-style-spec/#sources-raster) not work offline? 
Does the SDK need to verify the access-token before making the map work, even if it doesn't use Mapbox hosted maps?

**Comment by jfirebaugh** [comment] 2016-02-09 20:37
An access token will be required only when downloading resources from Mapbox APIs.

If by "local on-device raster-tiles" you're referring to the use of `asset://` URLs, no -- offline will not support `asset://` URLs (`asset://` URLs are already inherently "offline"). But if the tiles are served by a local server with localhost URLs, they will work with offline the same as other http URLs.

**Comment by jfirebaugh** [comment] 2016-02-11 01:07
⇢ #3715, #3891, #3892

**Closed by jfirebaugh** 2016-02-11 01:07 UTC
Labels: feature, in progress, offline

**Comment by nnhubbard** [comment] 2016-02-22 19:08
Since this was closed, do we have a release date?

**Comment by JonasVautherin** [comment] 2016-02-22 21:58
They said in March! ;-)

**Comment by twbell** [comment] 2016-03-03 01:23
Tracking progress and feedback on Offline here: https://github.com/mapbox/mapbox-gl-native/issues/4178

**Comment by rm3dbeckers** [comment] 2016-06-07 13:07
We've recently tested it and although it looks like the mapView itself accepts styleURLs looking like "asset://style.json" (they load and the tiles are being requested correctly), but the class OfflineTilePyramidRegionDefinition only seems to accept styleUrls of the form "mapbox://styles/mapbox/streets-v9". styleURLs pointing into the assets seem to later cause an error like getHost() called on null reference (or something along that line) and then result in a termination from within the mapbox-gl.so

**Comment by zugaldia** [comment] 2016-06-07 14:35
@rm3dbeckers could you open a separate ticket to track this issue? Thanks for the feedback.

**Comment by kkaefer** [comment] 2016-06-09 09:15
@rm3dbeckers `asset://` URLs are already offline, so they shouldn't be stored in the cache.

**Comment by rm3dbeckers** [comment] 2016-06-09 09:34
The problem is that I don't have any tiles in the assets but just the style.json which I want to use to download tiles. But using asset:// urls for the styleURL seems to only work for the mapview itself, not for the OfflineTilePyramidRegionDefinition.

**Comment by Stophface** [comment] 2017-09-29 15:19
Is there `mbtiles` for `ios` and/or `android`?

**Comment by nitrag** [comment] 2017-09-29 15:22
Chrckout openmaptiles. They have an extension for this. Here, no.

**Comment by Stophface** [comment] 2017-09-29 15:29
@nitrag  thanks for the fast reply. I am searching for *ready-to-use* `mbtiles` for `iOS` or `android`. Although for `android` a solution might be `osmdroid`.

**Comment by nitrag** [comment] 2017-09-29 15:30
Pretty sure it's ready to use. You just have to pay them for their module.

**Comment by songyuyang0918** [comment] 2019-03-25 08:56
Everybody is good! How does the latest IOS SDK load an offline map?
If there is a plug-in, please give me an address, thank you very much!

**Comment by tobrun** [comment] 2019-03-25 11:03
https://docs.mapbox.com/help/troubleshooting/mobile-offline/

**Comment by ssshake** [comment] 2021-12-01 16:40
Sorry to be posting on an old issue but I'm not finding a clear answer on the state of this in 2021. 

We have a react native app using mapbox-gl-js so I'm realizing now I'm in the wrong repo. We have a need to pre-cache tiles for offline use as we are producing an app to be used on ipad by workers out in remote areas. They need to cache their tiles then go out to the job site.

To complicate matters we also need this cache to be in an application group / shared storage. Which is an ios concept to allow 2 or more applications by the same vendor to access common data storage.

We have two applications, one using mapbox-gl-js and the other using the unity mapbox SDK. The react native application needs to download and cache the tiles in shared storage. The unity application need to be able to access the offline tiles from shared storage.

Any help indicating where to go would be very helpful as I'm finding the number of libraries/sdks for mapbox and the supported feature set between them to be quite unclear. Thanks!

**Comment by hjhimanshu01** [comment] 2023-05-16 11:38
@ssshake, were you able to render maps in offline mode?

**Comment by ssshake** [comment] 2023-05-16 19:57
With some hackery and trade offs yes. The two issues are 1) writing tiles DB to shared storage, 2) having the react-native and unity mapbox SDK use the same database and tiles.

I had to modify the SDK to handle that shared storage path. 

Unfortunately the database and tile file format between Unity and React Native are totally different. Both use SQL lite, but the table structures are not the same. Also it seems that React Native and Unity are opinionated about which type of tile image format they use. One uses JPGs and the other uses PNGs. 

I found no easy way to modify either SDK to make them use the same table structure or tile image format. So for now we are storing two completely different DBs and tiles for each SDK. It's unfortunate for obvious reasons, not disk or network efficient having to store two sets of data.

It's been a while since we did this so my memory isn't exact. If you wish to discuss further I can dig up the code and provide more specifics. Thanks!

p.s. I understand my use-case is atypical. Our product leverages Unity's 3D system to build 3d models, on the fly, of real world industrial assets that are installed across North America. 

We use React Native to present a map view which shows all of the work that an employee needs to do. When they perform the collection it links them into Unity, where instead of a birds eye view of many things, it focuses on the single asset to be modelled in the field. 

We use Mapbox in Unity to show a very localized, zoomed in map view of where the asset is. This allows the employee to make minor adjustment to the real world position of these assets if the supplied lat/long data is in error. 

This is why we use mapbox in both applications. And this is why we want to be able to share the offline data between the two applications/SDKs. The goal would be one database consisting of all the necessary tiles, which can be used by multiple applications belonging to an iOS Application Group. Grouped applications can access a common data path called Shared Storage. 

That was a mouth full but figured more info is better than less. Thanks again.

**Comment by hjhimanshu01** [comment] 2023-05-17 10:29
@ssshake, thanks for explaining, seems like quite an intricate solution you have got there. What I'm trying to achieve is related to 1), just to cache the tile data in a DB and read it later when offline, though I'm trying to achieve it in iOS using swift. Is it possible for you to just share some pointers on how did you cached those tiles and read it back in mapbox? 

Once again thanks for explaining it in so much detail, cheers!

**Comment by hjhimanshu01** [comment] 2023-05-18 11:46
Perfect, thanks for the info!
