### ISSUE TITLE
Various features render with wrong color on some Android GPUs

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#8385] opened 2017-03-14 06:05 UTC
![screenshot_20170314-013900](https://cloud.githubusercontent.com/assets/197010/23887821/7c3d0190-085a-11e7-95f8-3dd96010db63.png)
![screenshot_20170314-013934](https://cloud.githubusercontent.com/assets/197010/23887823/7ee44746-085a-11e7-8495-c43647404a8f.png)
![screenshot_20170314-014114](https://cloud.githubusercontent.com/assets/197010/23887825/80df19d6-085a-11e7-9e19-228afe821731.png)

**Platform:** Android
**Mapbox SDK version:** 5.0.0-SNAPSHOT

1. App uninstall/reinstall has no effect.
2. Works fine on other devices.

**Comment by tobrun** [comment] 2017-03-14 07:53
@nitrag thank you for letting us know that the [Samsung Galaxy J3 2016](http://www.gsmarena.com/samsung_galaxy_j3_(2016)-7760.php) has rendering issues. Do you know if older versions of the SDK rendered correctly on this device?

**Comment by nitrag** [comment] 2017-03-14 17:41
@tobrun I can confirm in a barebone app test project that the problem arose when moving to 5.0.0-beta3. Beta2 is working fine.

**Comment by tobrun** [comment] 2017-03-16 08:16
capturing from chat with @zugaldia that the issue only reproduces on one device and thus isn't a release blocker. Going to remove the label. This doesn't take away that this is a bug that should be looked into.

**Comment by tobrun** [comment] 2017-03-16 08:40
I was able to purchase the European equivalent of the mentioned A&T phone, though there isn't an Android 6.0.1 update for it yet:
![device-2017-03-16-093906](https://cloud.githubusercontent.com/assets/2151639/23987971/7d6f268c-0a2c-11e7-9a63-762d204e0bcc.png)

**Comment by tobrun** [comment] 2017-03-16 08:43
Not able reproducing the render issue on this device:

![ezgif com-video-to-gif 22](https://cloud.githubusercontent.com/assets/2151639/23988058/dfd7ee8a-0a2c-11e7-9ae7-3d886f548690.gif)

@nitrag any more information on this to move forward? Are you aware of any other devices with this issue?

**Comment by nitrag** [comment] 2017-03-16 13:29
Can you share this Simple Map project I want to be sure it's exact. Is
there some kind of advanced debugging I can enable in case there is a style
error? I will do some further testing today.

**Comment by tobrun** [comment] 2017-03-17 11:28
This produced with the Simple Map Activity found in this repo, you can test with latest snapshot by replacing:

```
    compile(project(':MapboxGLAndroidSDK')) {
        transitive = true
    }
```

with the [snapshot instructions](https://www.mapbox.com/android-sdk/) if you don't want to go through the trouble of building the C++ code. Feel free to share your style so we can try reproducing it with the style from OP.

**Comment by jfirebaugh** [comment] 2017-03-22 16:00
Given that the regression occurred between 5.0.0-beta2 and 5.0.0-beta3 and is GPU-specific, it was likely caused by 692f5e0a9f5321ee2932a976a8eb9e0a83fc3352.

**Comment by jfirebaugh** [comment] 2017-03-22 16:03
All color pragmas (e.g. [here](https://github.com/mapbox/mapbox-gl-js/blob/b9e10b939c6a3fe5d7ecac209f751b4871970ede/src/shaders/circle.fragment.glsl#L1) need to use `highp`.

cc @anandthakker

**Comment by jfirebaugh** [comment] 2017-03-22 20:27
A speculative fix has been merged to the `release-ios-v3.5.0-android-v5.0.0` branch. Next step is to confirm it resolves the issue by testing a build from this branch on an affected device.

**Comment by nitrag** [comment] 2017-03-22 20:37
I'm not too Android savvy and wasn't successful building the SDK from source last time I tried. Can someone build it from source for me? Happy to test.

**Comment by zugaldia** [comment] 2017-03-22 20:49
Thanks @nitrag. I ran the updated branch on one of the affected devices, a Galaxy S6 Edge API Level 22 (via Firebase). This is the current rendering:

![image](https://cloud.githubusercontent.com/assets/6964/24220023/35b3ecea-0f1f-11e7-86f0-9430f42893d9.png)

And this was the rendering, on the same device, before the fix:

![image](https://cloud.githubusercontent.com/assets/6964/24220034/41bd146c-0f1f-11e7-8a86-938839c74185.png)

This seems to confirm the fix is working. Next, we're releasing 5.0.1 including just this fix.

**Comment by nitrag** [comment] 2017-03-22 20:51
Ok great! I'll confirm once I see 5.0.1 published.

**Comment by zugaldia** [comment] 2017-03-22 22:26
@nitrag 5.0.1 has been published https://github.com/mapbox/mapbox-gl-native/issues/8501, could you check if you still see the rendering issue?

**Comment by snowpong** [comment] 2017-03-23 10:52
@zugaldia Fixes rendering issues for me. Attached screenshots https://github.com/mapbox/mapbox-gl-native/issues/8501#issuecomment-288682209 (sorry, probably should have attached them here)

**Comment by tobrun** [comment] 2017-03-23 12:03
Thank for confirming @snowpong, closing.

**Closed by tobrun** 2017-03-23 12:03 UTC
Labels: Android

**Comment by nitrag** [comment] 2017-03-23 12:23
Confirming as well. Thanks!

**Comment by zugaldia** [comment] 2017-03-23 12:57
@nitrag Thank you for checking!

**Comment by ragaisis** [comment] 2017-03-27 10:45
@zugaldia, I'm still having rendering problems on custom map style 😞 using 5.0.1 that I build from SHA 1479014a58199ac0b348dc88a10022aaa0ba155b  

![Uploading Screenshot_2017-03-27-13-01-16.png…]()
