### ISSUE TITLE
Content insets and edge padding should be additive, not mutually exclusive

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#15232] opened 2019-07-26 20:27 UTC
By design, a camera’s edge padding and the map’s content insets are supposed to be additive: every camera change operation is relative to the content insets, and the edge padding can further inset the camera.

In #12818, the `-[MGLMapView setCamera:withDuration:animationTimingFunction:edgePadding:completionHandler:]` method incorrectly treated the edge padding and content insets as mutually exclusive. If the developer left the edge padding unspecified when changing the camera, then MGLMapView would correctly consider just the content insets. But if the developer passes in an edge padding, MGLMapView would incorrectly ignore the content insets in favor of the edge padding alone. Clients (including the navigation SDK) worked around the bug by explicitly adding the content insets to the edge padding.

#14813 fixed this issue for v5.1.0, but in the same release, #14664 regressed it in mbgl and expanded the issue to flight animations as well:

https://github.com/mapbox/mapbox-gl-native/blob/b6dd995813625a89bba8937c512cdf1175827d66/src/mbgl/map/transform.cpp#L85 https://github.com/mapbox/mapbox-gl-native/blob/b6dd995813625a89bba8937c512cdf1175827d66/src/mbgl/map/transform.cpp#L165

/cc @astojilj @mapbox/maps-ios @mapbox/navigation-ios @d-prukop

**Comment by 1ec5** [comment] 2019-07-26 20:38
Additionally, if a padding is explicitly passed into either `easeTo()` and `flyTo()`, mbgl persists that padding as the content insets:

https://github.com/mapbox/mapbox-gl-native/blob/b6dd995813625a89bba8937c512cdf1175827d66/src/mbgl/map/transform.cpp#L146-L151 https://github.com/mapbox/mapbox-gl-native/blob/b6dd995813625a89bba8937c512cdf1175827d66/src/mbgl/map/transform.cpp#L310-L315

Because mbgl conflates the two properties, it isn’t possible even to work around the original issue by manually passing in the content inset plus a padding – now the developer has to reset the content inset in the camera change operation’s completion handler.

**Comment by astojilj** [comment] 2019-07-27 11:33
@1ec5 ,

We discussed this concern at https://github.com/mapbox/mapbox-gl-native/issues/12818#issuecomment-496836719 and I should continue work on this.

> By design, a camera’s edge padding and the map’s content insets are supposed to be additive: every camera change operation is relative to the content insets, and the edge padding can further inset the camera.

As mentioned there, didn't see it defined in documentation and thought it is intuitive to make it behave additive for case of automaticallyAdjustsScrollViewInsets, otherwise no.

This is related to discussion in https://github.com/mapbox/mapbox-gl-native/issues/15233 and we should clarify the behavior in documentation. I don't see it requires API changes.

**Comment by 1ec5** [comment] 2019-07-28 19:38
I don’t think _API_ changes are strictly required, but I do think we need to do more than clarify the documentation. If content insets and edge padding are redundant to each other and one affects the other, then there was no point in fixing #12818, and the situation is especially confusing for someone used to UIKit and MapKit controls.

The discussion in https://github.com/mapbox/mapbox-gl-native/issues/12818#issuecomment-496836719 was focused on whether we could get away with making the change without bumping the major version, as required by semantic versioning. A loophole in the documentation meant that we could do so, but it was still necessary to make the various methods consistent.

`automaticallyAdjustsScrollViewInsets` is only a convenience for the developer, but the developer can set the insets for exactly the same reason that it would be set automatically. In that case, they should get the same camera behavior as if the map view adjusted the insets automatically.

**Comment by astojilj** [comment] 2019-08-14 09:53
Offline agreement on this is that it is confusing to have both content insets and padding since they both use the same implementation to implement Android and iOS code and terms content insets, padding, edge insets are used interchangeably.

We will reconsider anchor design later.

@1ec5 

>By design, a camera’s edge padding and the map’s content insets are supposed to be additive: every camera change operation is relative to the content insets, and the edge padding can further inset the camera.

This is left to be covered. I don't see that out documentation covers this. Is the design implied by adopting similar functionality existing in other APIs?

**Comment by astojilj** [comment] 2019-08-14 10:41
@1ec5 , @fabian-guerra 

I'm going again through the discussion to split the issues list from the description and title (part of it is related to implementation detail of pre and after #14664.

The regression tag added here - is it related to #14813 fixing #12818?

> #14813 fixed this issue for v5.1.0, but in the same release, #14664 regressed it in mbgl and expanded the issue to flight animations as well.

My plan is to try to cover the desired functionality with tests. Given that the patches are committed almost at the same time, it is obvious that we could have prevented collision if there were tests.

**Comment by astojilj** [comment] 2019-08-14 11:26
Closing according to https://github.com/mapbox/mapbox-gl-native/issues/15232#issuecomment-521195215

**Closed by astojilj** 2019-08-14 11:26 UTC
Labels: Core, bug, high priority, navigation, needs discussion, regression
