### ISSUE TITLE
Crash after screen rotation in Android 4.1.1

### ISSUE THREAD

**Issue by salonkasoli** [mapbox/mapbox-gl-native#10078] opened 2017-09-27 08:02 UTC
```

public class MainActivity extends AppCompatActivity {

	private MapView mapView;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		Mapbox.getInstance(this, "token");
		setContentView(R.layout.activity_main);


		mapView = (MapView) findViewById(R.id.mapview);
		mapView.onCreate(savedInstanceState);

		mapView.getMapAsync(new OnMapReadyCallback() {
			@Override
			public void onMapReady(MapboxMap mapboxMap) {

			}
		});
	}

	@Override
	public void onStart() {
		super.onStart();
		mapView.onStart();
	}

	@Override
	public void onResume() {
		super.onResume();
		mapView.onResume();
	}

	@Override
	public void onPause() {
		super.onPause();
		mapView.onPause();
	}

	@Override
	protected void onStop() {
		super.onStop();
		mapView.onStop();
	}

	@Override
	public void onSaveInstanceState(Bundle outState) {
		super.onSaveInstanceState(outState);
		mapView.onSaveInstanceState(outState);
	}

	@Override
	public void onLowMemory() {
		super.onLowMemory();
		mapView.onLowMemory();
	}

	@Override
	protected void onDestroy() {
		super.onDestroy();
		Log.wtf("tag","before onDestroy");
		mapView.onDestroy();
		Log.wtf("tag","after onDestroy");
	}
}

```

I rotate screen, app crashes. Log:

```
09-27 14:59:25.458 31526-31526/com.example.pici.maptest A/tag: before onDestroy
09-27 14:59:25.488 31526-31526/com.example.pici.maptest A/libc: Fatal signal 11 (SIGSEGV) at 0x00000230 (code=1), thread 31526 (le.pici.maptest)
```

**Comment by tobrun** [comment] 2017-09-27 08:59
@salonkasoli 
Thank you for the report, I haven't been able to reproduce this on a JellyBean device or emulator. 
Would you be able to add more device details to [this](https://github.com/mapbox/mapbox-gl-native/issues/10030) ticket? Going to close this as a duplicate of that one, they seem related.

**Closed by tobrun** 2017-09-27 08:59 UTC
