### ISSUE TITLE
Offline map download crash

### ISSUE THREAD

**Issue by chenqingfeid** [mapbox/mapbox-gl-native#8903] opened 2017-05-05 09:15 UTC
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.Download offline map 
 2.Download completed ，launch mapActivity
 3.MapActivity will be crash

### Expected behavior
05-03 15:11:15.382 17849 17849 I AEE/AED : ABI: 'arm'
05-05 16:08:35.067 12641 12641 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20 in tid 12641 (com.speedx.s605)
05-05 16:08:35.127 20908 20908 I AEE/AED : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-05 16:08:35.127 20908 20908 I AEE/AED : Build fingerprint: 'Letv/Le1s_CN/X3:6.0/DBXCNOP5902303111S/1489169409:user/release-keys'
05-05 16:08:35.127 20908 20908 I AEE/AED : Revision: '0'
05-05 16:08:35.127 20908 20908 I AEE/AED : ABI: 'arm'
05-05 16:08:35.127 20908 20908 I AEE/AED : pid: 12641, tid: 12641, name: com.speedx.s605  >>> com.speedx.s605 <<<
05-05 16:08:35.127 20908 20908 I AEE/AED : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20
05-05 16:08:35.144 20908 20908 I AEE/AED :     r0 00000000  r1 00000001  r2 f7558ea4  r3 f7558de4
05-05 16:08:35.144 20908 20908 I AEE/AED :     r4 d716f570  r5 ffc1b768  r6 ffc1b768  r7 ffc1b730
05-05 16:08:35.144 20908 20908 I AEE/AED :     r8 40280000  r9 d7203ca0  sl d7203d84  fp 00000000
05-05 16:08:35.144 20908 20908 I AEE/AED :     ip f7558f04  sp ffc1b730  lr d5292819  pc d5292818  cpsr 400b0030
05-05 16:08:35.149 20908 20908 I AEE/AED : 
05-05 16:08:35.149 20908 20908 I AEE/AED : backtrace:
05-05 16:08:35.149 20908 20908 I AEE/AED :     #00 pc 00013818  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #01 pc 000cd203  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #02 pc 000cd1a9  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #03 pc 0006b501  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #04 pc 0006b3cb  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #05 pc 000457d1  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #06 pc 0005d6d3  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #07 pc 0004ddf1  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #08 pc 0004dd73  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #09 pc 0004de93  /data/app/com.speedx.s605-1/lib/arm/libmapbox-gl.so
05-05 16:08:35.150 20908 20908 I AEE/AED :     #10 pc 00dae599  /data/app/com.speedx.s605-1/oat/arm/base.odex (offset

**Comment by tobrun** [comment] 2017-05-05 09:42
cc @Guardiola31337

**Comment by jfirebaugh** [comment] 2017-05-05 17:47
Hi @chenqingfeid, thanks for using Mapbox. Since the stack trace does here does not include any debug symbols, and were unable to replicate a crash in our own test applications, it's unlikely that we'll be able to diagnose the issue here without a minimal code sample that replicates the issue. Are you able to provide that?

**Comment by chenqingfeid** [comment] 2017-05-08 02:25
Of course, I can repeat the above problems.

**Comment by tobrun** [comment] 2017-05-08 08:24
@chenqingfeid I'm not seeing how previous comment is actionable, could you add some more information for reproducing the issue (enable/disable internet connection? or any other specifics around your test setup? or a minimal code example to reproduce? Without having additional information, I'm unable to reproduce. Going to close this until more information is provided.

**Closed by tobrun** 2017-05-08 08:24 UTC
Labels: Android, crash, needs information, offline
