### ISSUE TITLE
Offline Download with asset hosted style

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14912] opened 2019-06-13 07:20 UTC
I'm unable to download an offline region when trying to create one using a local hosted asset style (eg. `assset://streets.json`). This style works correctly when loaded in a normal map.

#### Actual result:

```
E/Mbgl-HttpRequest: [HTTP] Unable to parse resourceUrl asset://streets.json
```

#### Expected result:

I'm able to use a local style for downloading an offline region

**Comment by tobrun** [comment] 2019-06-13 07:33
Looking at the c++ code `offline_download.cpp`, I'm seeing usage of [online_filesource](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/src/mbgl/storage/offline_download.cpp#L435). 
@tmpsantos should we replace this with our general filesource abstraction to also allow loading resources from `asset://` and `file://` or is this a work as designed?

**Comment by kkaefer** [comment] 2019-06-13 10:32
Duplicate of https://github.com/mapbox/mapbox-gl-native/issues/9960

**Closed** 2019-06-13 11:31 UTC
Labels: Core
