### ISSUE TITLE
Artefacts offline mode

### ISSUE THREAD

**Issue by Comanga** [mapbox/mapbox-gl-native#9493] opened 2017-07-13 07:42 UTC
**Platform: iOS 10**
**Mapbox SDK version: v3.6.0**

### Steps to trigger behavior

 1. Download Mapbox's sample project: https://github.com/mapbox/ios-sdk-examples
 2. Go to OfflinePackExample_Swift
 3. Fully download the map with an internet connection
 4. Kill the application
 5. Go back **in airplane mode** 6 ~ 24 hours later (that's where the bug is tricky to reproduce but when it happens the map will always be buggy)

### Expected behavior

No artefacts (version 3.5.4 works normal)

### Actual behavior

I don't know if the problem is related to this issue [https://github.com/mapbox/mapbox-gl-native/issues/9211](https://github.com/mapbox/mapbox-gl-native/issues/9211) but it occurs even in Mapbox's examples... 

Here is a video to demonstrate the glitch: https://youtu.be/i0tdzvjYEig (don't pay attention to the wifi logo, quicktime adds it).

**Comment by jfirebaugh** [comment] 2017-07-13 15:29
Duplicate of #8756.

**Closed by jfirebaugh** 2017-07-13 15:29 UTC
Labels: bug, iOS, offline

**Comment by zivlevy** [comment] 2017-07-17 17:32
I have the same issue using 3.6.0 with objective c.
Any progress ?
