### ISSUE TITLE
Query rendered features with icon-rotate

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#12909] opened 2018-09-18 11:49 UTC
Capturing from a downstream issue in https://github.com/mapbox/react-native-mapbox-gl/issues/1347 and validated upstream. Query rendered features doesn't take in account the icon-rotate property, see gif below as example. First we are offseting the icon and afterwards applying a rotation to it.

![ezgif com-video-to-gif 44](https://user-images.githubusercontent.com/2151639/45685367-6cf80380-bb49-11e8-90f5-9fabb5488c81.gif)

**Comment by mollymerp** [comment] 2018-10-15 19:56
this is a duplicate of #11872

**Closed** 2018-10-18 19:14 UTC
Labels: Core, querying
