### ISSUE TITLE
GeoJSON layers vanishing when rendering a map tile in zoom >= 15

### ISSUE THREAD

**Issue by trasch** [mapbox/mapbox-gl-native#4632] opened 2016-04-07 14:58 UTC
I am trying to render a map with some GeoJSON line on it (using the Node.js bindings), here is the example:

https://gist.github.com/trasch/2ad54fd13565da72e4ce9ae6662ca7db

The curious thing is that it works for any zoom level < 15, but the line vanishes in zoom levels >= 15.

### Steps to trigger behavior

Run the script above for zoom 14.9 and 15.

### Expected behavior

There should be a line on the rendered image for both zoom levels.

### Actual behavior

There is a line for zoom 14.9 but not for 15.

**Platform: Mac OS X**
**Mapbox SDK version: 3.0.2**

**Comment by mikemorris** [comment] 2016-04-07 22:36
Welp, I can confirm the behavior you're reporting in `node-v3.0.2`, but it looks to be fixed in `master` now. Not quite sure what originally caused this, but I'll tag a new release tomorrow.

**Closed by mikemorris** 2016-04-07 22:36 UTC
Labels: node

**Comment by mikemorris** [comment] 2016-04-07 23:18
Looks like this was fixed in 387f37d035d08a1832ad693e8d9401d7f29857bd
