### ISSUE TITLE
make android redownloads ndk on every build

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#2346] opened 2015-09-16 19:47 UTC
This makes testing any Android build system changes quite slow.

**Comment by incanus** [comment] 2015-09-16 22:32
Currently looking into this as part of https://github.com/mapbox/mapbox-gl-native/pull/2344.

**Comment by incanus** [comment] 2015-09-16 22:38
From what I can see, the various Mason scripts involved use `mason_download`, which does in fact check `mason_packages/.cache`. Digging further.

**Comment by incanus** [comment] 2015-09-16 22:52
Checking this list of NDK downloads and hashes — I have a hunch we have a bad hash and that is causing the re-download every time. 

https://gist.github.com/incanus/016ac1d43fdc4fae8978

**Comment by incanus** [comment] 2015-09-16 22:59
And the scripts are re-downloading `arm-9-r10e.tar.gz` which isn't mentioned in Mason...

**Comment by incanus** [comment] 2015-09-16 23:04
@mikemorris Are you on 10.10 or 10.11? I'm on 10.11.

**Comment by incanus** [comment] 2015-09-16 23:15
I think the problem is no `osx-10.11` cache: 

```
$ aws s3 ls s3://mason-binaries/ | grep osx
                           PRE osx-10.10/
                           PRE osx-10.9/
```

**Comment by incanus** [comment] 2015-09-16 23:23
Not necessarily the problem, as this version is based on: 

```
xcrun --sdk macosx --show-sdk-version
```

Which returns `10.10` even on `10.11`, depending Xcode version currently in use.

**Comment by incanus** [comment] 2015-09-16 23:32
This may however be a discrepancy between the SDK version and the host version, the latter of which is used for the cache path.

**Comment by incanus** [comment] 2015-09-16 23:35
Mason seems to be downloading nested binaries, for example trying to write the NDK to here: 

```
gl-native/mason_packages/.build/geojson-vt-cpp-1.1.0/mason_packages/.binaries/osx-10.10/android-ndk/arm-9-r10e.tar.gz
```

_Now_ this seems related to https://github.com/mapbox/mapbox-gl-native/issues/2348.

**Comment by incanus** [comment] 2015-09-16 23:38
I'm going to wait until the `npm`-related changes are reverted in `master` in https://github.com/mapbox/mapbox-gl-native/pull/2349 before pursuing this any further.

**Comment by incanus** [comment] 2015-09-17 00:02
Confirmed — once https://github.com/mapbox/mapbox-gl-native/pull/2349 landed, the NDK is only downloaded once.

**Comment by ljbade** [comment] 2015-09-17 00:02
On Linux the NDK is cached fine, so never noticed this issue.

**Comment by ljbade** [comment] 2015-09-17 00:04
Oh, @incanus actually yes I remember seeing NDK redownload yesterday and put it down to random network glitch (that was before I was aware of #2348)

**Comment by mikemorris** [comment] 2015-09-17 15:43
> I think the problem is no osx-10.11 cache

I was seeing this on OS X 10.10.5, `xcrun --sdk macosx --show-sdk-version` returns `10.11` though. That directory nesting does look wrong.

**Comment by incanus** [comment] 2015-09-17 15:47
Yeah, this was related to the now-reverted geojson-vt change using _it's own_ nested Mason and installing the NDK multiple times. That's gone now.

**Comment by mikemorris** [comment] 2015-09-17 18:39
So the initial bug is that there isn't a matching binary published yet...
```
* Building for Platform 'android/arm-v7-9'...
* Loading install script 'https://github.com/mapbox/mason/blob/android-ndk-arm-9-r10e/script.sh'...
* Downloading binary package osx-10.11/android-ndk/arm-9-r10e.tar.gz...
curl: (22) The requested URL returned error: 403 Forbidden
* Binary not available yet for osx-10.11/android-ndk/arm-9-r10e.tar.gz
* Downloading http://dl.google.com/android/ndk/android-ndk-r10e-darwin-x86_64.bin...
```
But after downloading the ndk source, everything gets moved into the `geojson-vt-cpp` directory for some reason???
```
* Building for Platform 'osx/10.11'...
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries (with libc++abi)...
Copying files to: /Users/mikemorris/Projects/mapbox-gl-native/mason_packages/.build/geojson-vt-cpp-1.1.0/mason_packages/osx-10.11/android-ndk/arm-9-r10e
```

**Comment by incanus** [comment] 2015-09-17 18:48
I think we are talking about two different things. 

1. What I was seeing was with a 10.10 SDK, so the `osx-10.10/android-ndk/arm-9-r10e.tar.gz` binary *did* exist, and was getting downloaded, but geojson-vt was nesting it one or more times, so it kept re-downloading it. 

1. What you are seeing @mikemorris is due to the `osx-10.11/android-ndk/arm-9-r10e.tar.gz` binary *not* existing, getting downloaded from `dl.google.com` instead of S3, but also having some problem relating to geojsonvt copying files.

**Comment by incanus** [comment] 2015-09-17 18:49
FWIW with a 10.10 SDK, I no longer see my problem as of https://github.com/mapbox/mapbox-gl-native/pull/2349.

**Comment by mikemorris** [comment] 2015-09-17 19:07
Looks like `geojsonvt-1.1.0` is overwriting the `MASON_BUILD_PATH` at https://github.com/mapbox/mason/blob/geojsonvt-1.1.0/script.sh#L16

**Comment by ljbade** [comment] 2015-10-30 02:16
Does this still happen?

**Comment by mikemorris** [comment] 2015-10-30 04:30
Think this was "fixed" by adding a mason binary.

**Comment by ljbade** [comment] 2015-10-30 06:26
Ah yeah that's the usual way to prevent recompiling.

**Closed by ljbade** 2015-10-30 06:26 UTC
Labels: Android, build
