### ISSUE TITLE
All animations broken

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2036] opened 2015-08-11 04:43 UTC
Tapping the compass no longer reliably resets the bearing — upon tapping, the compass will sometimes stutter towards north a few degrees and halt. Other times the compass will haltingly reset to north and disappear.

Not seeing any particular pattern right now.

/cc @mapbox/mobile

**Comment by ljbade** [comment] 2015-08-11 05:19
Happens on Android too, noticed in https://github.com/mapbox/mapbox-gl-native/issues/1856#issuecomment-129666707

**Comment by 1ec5** [comment] 2015-08-11 06:37
#1829 changed the iOS compass to rely on mbgl for frame updates, whereas it used to use view-based animation. So this is definitely a bug in mbgl’s update notifications.

**Comment by 1ec5** [comment] 2015-08-11 06:40
This is causing `-[MapViewTests testCompassTap]` to fail reliably.

**Comment by 1ec5** [comment] 2015-08-11 23:37
Regression from fa4636ffe4d2c00446292c229cd549cbaee9e20c.

**Comment by incanus** [comment] 2015-08-11 23:47
iOS tests should have caught this, yes? Why didn't they? 

https://travis-ci.org/mapbox/mapbox-gl-native/builds/74223611

**Comment by 1ec5** [comment] 2015-08-12 00:12
The tests have been catching the issue about 80% of the time. I had thought it was #1887, but those failures were just burying this one.

**Comment by 1ec5** [comment] 2015-08-12 00:37
Probably related: when tracking user location, the user dot often shuffles out of view.

**Comment by 1ec5** [comment] 2015-08-12 22:22
All animation is broken, and I’m having a difficult time untangling fa4636ffe4d2c00446292c229cd549cbaee9e20c. @brunoabinader, can you look into this?

**Comment by 1ec5** [comment] 2015-08-12 23:09
I may have confused the bisect by starting with release-0.5.0 as good, but when I start with two revisions on master, I get this commit instead: 0a527f623ed88ef46c104e97a86239b012141074. #2026 is interesting because perhaps this constant redrawing was only masking the underlying problem.

/cc @kkaefer

**Comment by brunoabinader** [comment] 2015-08-13 02:00
I am AFK this Thursday and Friday, will have a look on my way to US this weekend.
/cc @tmpsantos

**Comment by brunoabinader** [comment] 2015-08-13 07:35
Got lucky with wifi onboard, so I managed to find the root cause: `mbgl::Transform::{_moveBy,_setAngle}` were returning `Update::Nothing`, causing the render call to not repaint. Changing thost to `Update::Repaint` fixed all the aforementioned issues. Fixed in #2060.

**Comment by brunoabinader** [comment] 2015-08-13 07:57
Reopening issue for proper validation. I've tested on an iPad, iPhone 6 (via simulator), Android, GLFW and Qt-based ports in OSX, clicking on compass button now properly resets bearing to North, and all other animations are working as should. Please verify?

**Comment by ljbade** [comment] 2015-08-13 11:30
Works on Android

**Comment by 1ec5** [comment] 2015-08-13 19:04
Works great on iOS 8.4 on an iPhone 6 and on the iOS 9 Simulator.

**Closed by 1ec5** 2015-08-13 19:04 UTC
Labels: Android, bug, iOS

**Comment by friedbunny** [comment] 2015-08-13 21:46
Looks good on-device — iPhone 5, iOS 9. :+1:
