### ISSUE TITLE
Annotation returl nil in tapOnCalloutForAnnotation 

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#5824] opened 2016-07-29 09:05 UTC
*_Platform:_iOS*
*_Mapbox SDK version:_3.3.1*
### Steps to trigger behavior
1. Tap on callout of annotation
2. Annotation return nil

**Comment by 1ec5** [comment] 2016-07-29 15:39
Does this issue occur every time? Are you using the built-in callout views or a custom callout view? Can you provide some sample code to illustrate what your code does? Thanks!

**Comment by iBinh** [comment] 2016-07-29 20:06
It always return 0x00. I use custom callout view, like this example : 
[https://www.mapbox.com/ios-sdk/examples/custom-callout/
](url)
add selector for a button in calloutview by 
          `  [self.someButton addTarget:self action:@selector(calloutTapped) forControlEvents:UIControlEventTouchUpInside];
`
and when I touch the button, annotation in tapOnCalloutForAnnotation delegate method return 0x00. I also use custom annotation.

**Comment by 1ec5** [comment] 2016-07-29 22:08
In that example, the implementation of `-[CustomCalloutView calloutTapped]` calls the callout view’s delegate’s `-calloutViewTapped:` method, passing in `self` as the object. Does that match your implementation? The object passed into that method is what gets passed into the `-mapView:tapOnCalloutForAnnotation:` method’s `annotation` parameter.

**Comment by iBinh** [comment] 2016-07-30 04:52
That matches my implementation

**Comment by 1ec5** [comment] 2016-07-30 17:56
I’m unable to reproduce the issue using the exact code in that Objective-C example. To be clear, the example is using a UIButton to make the entire callout view tappable (including the “Hello world!” text). However, if you want the callout view to resemble the built-in callout, which has an accessory button on either side of the title and subtitle labels, then you’d add additional UIButtons and set the [`leftAccessoryView`](https://www.mapbox.com/ios-sdk/api/3.3.3/Protocols/MGLCalloutView.html#/c:objc(pl)MGLCalloutView(py)leftAccessoryView) and [`rightAccessoryView`](https://www.mapbox.com/ios-sdk/api/3.3.3/Protocols/MGLCalloutView.html#/c:objc(pl)MGLCalloutView(py)rightAccessoryView) properties to those buttons.

**Comment by sncvsrtoip** [comment] 2016-09-02 20:12
100% repro also in my implementation

**Comment by sncvsrtoip** [comment] 2016-09-02 21:01
In my case problem was with mapBox.userTrackingMode = .followWithHeading used before return view in calloutViewFor (I put there because calloutViewFor seems to reset tracking mode).

**Comment by friedbunny** [comment] 2017-03-10 03:09
Closing as unreproducible — please feel free to post more information/code and we can reinvestigate.

**Closed by friedbunny** 2017-03-10 03:09 UTC
Labels: annotations, iOS
