### ISSUE TITLE
Equivalent of MGLOfflineStorage.shared (). CountOfBytesCompleted in  Android

### ISSUE THREAD

**Issue by houariii** [mapbox/mapbox-gl-native#7721] opened 2017-01-13 21:40 UTC
Hi,
I know that for calculating the sum of oflline regions size, I use MGLOfflineStorage.shared (). CountOfBytesCompleted in iOS, But i don't find the equivalent in Android !!!
How to calculate the sum of all offline regions on my device, the real size because if I take  size(region 1)+......size(region N) give wrong size because there are shared regions.
Thanx

**Comment by 1ec5** [comment] 2017-01-14 17:37
Duplicate of #5580, which has been fixed for iOS and macOS but not Android.

**Closed by 1ec5** 2017-01-14 17:37 UTC
Labels: Android, offline

**Comment by houariii** [comment] 2017-01-15 15:23
Hi,
Can I get an approximate size value with this code 

private String mbglOffline = "/data/data/ca.qc.expweb.avalon/files/mbgl-offline.db";
 File file = new File(mbglOffline);
        if(file.exists()) {
            long sizeMb = (file.length()*100 / 1048576 );  // size in MB * 100
            float dispalyedSize = (float) sizeMb /100;   // with size devide by 100 we get 2 digit after point
            Log.i(TAG,"size = "+dispalyedSize);
	}

**Comment by 1ec5** [comment] 2017-01-15 18:14
We’re unable to provide estimates via GitHub tickets. You can use [this tile count estimator](https://www.mapbox.com/labs/offline-estimator/) to at least know how many tiles you’ll need to download. However, the size of each tile varies by how much detail is included in that tile. For example, a tile in the middle of the Atlantic Ocean will naturally be much smaller than a tile in Manhattan. So your best bet is to simply try downloading that region on your own device and check the size of mbgl-offline.db. There’s a lot more information along these lines in [our offline maps help document](https://www.mapbox.com/help/mobile-offline/).
