### ISSUE TITLE
shape_annotation_impl.cpp:109: undefined reference to `mapbox::util::geojsonvt::Convert::create

### ISSUE THREAD

**Issue by rvmirror** [mapbox/mapbox-gl-native#3205] opened 2015-12-07 12:01 UTC
$ make linux
make[1]: Entering directory '/disk/src/mapbox-gl-native'
build: linux/x86_64
host: linux/x86_64
libs: headless=glx  platform=linux  asset=fs  http=curl  cache=sqlite
* Recreating project...
* Building target linuxapp...
make[2]: Entering directory '/disk/src/mapbox-gl-native/build/linux-x86_64'
  LINK(target) Release/mapbox-gl
./Release/obj.target/gyp/libmbgl-core.a(shape_annotation_impl.o): In function `mbgl::ShapeAnnotationImpl::updateTile(mbgl::TileID const&, mbgl::AnnotationTile&)':
/disk/src/mapbox-gl-native/build/linux-x86_64/../../src/mbgl/annotation/shape_annotation_impl.cpp:109: undefined reference to `mapbox::util::geojsonvt::Convert::create(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, mapbox::util::geojsonvt::ProjectedFeatureType, mapbox::util::variant<mapbox::util::geojsonvt::ProjectedPoint, mapbox::util::geojsonvt::ProjectedGeometryContainer>)'
collect2: error: ld returned 1 exit status
gyp/linuxapp.target.mk:248: recipe for target 'Release/mapbox-gl' failed
make[2]: *** [Release/mapbox-gl] Error 1
make[2]: Leaving directory '/disk/src/mapbox-gl-native/build/linux-x86_64'
scripts/main.mk:124: recipe for target 'Makefile/linuxapp' failed
make[1]: *** [Makefile/linuxapp] Error 2
make[1]: Leaving directory '/disk/src/mapbox-gl-native'
Makefile:64: recipe for target 'linux' failed
make: *** [linux] Error 2

**Comment by mikemorris** [comment] 2015-12-07 17:43
Looks possibly related to https://github.com/mapbox/geojson-vt-cpp/pull/15 - are you building with a compiler that doesn't support `__attribute__ ((visibility ("default"))) ` by any chance?

**Comment by jfirebaugh** [comment] 2015-12-09 01:31
Duplicate of #3123.

**Closed by jfirebaugh** 2015-12-09 01:31 UTC
