### ISSUE TITLE
Offline Region updateMetadata

### ISSUE THREAD

**Issue by vidsag** [mapbox/mapbox-gl-native#10626] opened 2017-12-04 13:25 UTC
I am trying to store some information in the meta during the download.This information maybe altered during the course of the download and certain actions might be taken based on this. But in the sdk they mention that `After you call this method, you may not call any additional methods on this object`. Why is it that I cannot call any additional methods on this object?. They say the same for delete which I can understand. But why for `updateMetadata`?. It is just changing the meta as for me I don't find any implications that this might have.

**Comment by fabian-guerra** [comment] 2017-12-04 14:25
Hi, @vidsag. Thank you for using Mapbox. Could you please be more specific about the platform/version/class are you using?

**Comment by jfirebaugh** [comment] 2017-12-04 16:42
Duplicate of #4344 (assuming this is for iOS).

**Comment by vidsag** [comment] 2017-12-05 05:34
Hi @fabian-guerra This is for android and I am using the latest mapbox sdk `5.2.0`. This is a usecase in the offline maps section. The `updateMetaData` in the callback in the `OfflineRegion` used to update the meta data of the downloaded offline region.

Please reopen this issue.

**Comment by fabian-guerra** [comment] 2017-12-05 15:01
Hi, @vidsag. 
> used to update the meta data of the downloaded offline region.

Do you mean `updateMetaData` is not working?

**Comment by vidsag** [comment] 2017-12-07 04:55
No what I mean is the I don't clearly understand the description that is provided for the `updateMetaData` where it says. I don't understand the `After you call this method, you may not call any additional methods on this object` part and its implications.

**Comment by jfirebaugh** [comment] 2017-12-07 16:23
Looks like that sentence was copied-and-pasted from the `delete` method by mistake. There's no such restriction on `updateMetaData`.

**Comment by vidsag** [comment] 2017-12-07 18:48
Thanks for confirming that

**Comment by tobrun** [comment] 2017-12-13 15:58
Documentation was updated in #10694, thank you @vidsag for reporting this.

**Closed by tobrun** 2017-12-13 15:58 UTC
Labels: Android, documentation
