### ISSUE TITLE
Android Mapbox Markers - With custom styling, only first marker added in loop is clickable

### ISSUE THREAD

**Issue by dportology** [mapbox/mapbox-gl-native#11986] opened 2018-05-23 01:37 UTC
Platform: Android
Mapbox SDK version: 6.1.1

See related question here (https://stackoverflow.com/questions/50321368/android-mapbox-markers-only-first-marker-added-is-clickable)

When adding markers in a loop, and setting an on marker click listener, only the first added marker is clickable. The other markers do not become clickable unless the map is zoomed / rotated manually.

**Comment by ychescale9** [comment] 2018-05-24 02:31
I've been having a similar issue since migrating to 6.0.
Seems to be a regression introduced in one of the 6.X releases (caused by new version of the telemetry dependency?). I haven't investigated further as the MapboxGLAndroidSDKTestApp was broken. I can spend some time to get more info if required.

**Comment by tobrun** [comment] 2018-05-24 12:18
Thanks both for reaching out! Atm not able to reproduce with the test app from this repo:
![ezgif com-video-to-gif 15](https://user-images.githubusercontent.com/2151639/40484889-49a03bc0-5f5d-11e8-8598-6e080ac65652.gif)

Will try out some different scenario's any pointers/code are highly appreciated!

**Comment by dportology** [comment] 2018-05-24 22:12
Trying to recreate in an example app to pin point the issue, but so far no luck. I'll post more if I find anything out.

Some things particular to my use case which may give some hints:

- I'm loading these markers in from Firebase
- I'm setting a custom icon from a bitmap (Tried in example app and this didn't seem to matter)
- The map is in a fragment in an activity (Also tried in example app and it didn't matter)
- I am using a custom style from a styleUrl
- I have a transparent view covering the map which consumes certain touch events but uses dispatchTouchEvent to pass touchs through to the map. Touches always work on the first marker like stated though. Are the others possibly being added to a different layer?

**Comment by ychescale9** [comment] 2018-05-28 00:44
Some more info:

In my case the regression happens on Samsung device (S7 edge) and works on emulators and Google Pixel.

I have 2 GeoJsonSources (and layers) - 1 for the features being represented as markers, the other one for currently selected feature (marker).

After rendering the 2 GeoJsonSrouces for the first time, `queryRenderedFeatures` doesn't seem to be able to find the feature after tapping on the marker, but once a new marker has been added (the GeoJsonSources updated the second time), selection starts working.

Putting the app in the background and coming back (`onPause()` -> `onResume()`) also fixes the issue immediately.

Sorry that this is looking more like a different issue..

**Comment by dportology** [comment] 2018-05-31 00:10
Could this have to do with using Marker Options instead of adding markers to a symbol layer? I checked out the marker playground (https://www.mapbox.com/help/marker-playground/) and the example code uses a Symbol layer

`private void addMarkers() {
	List<Feature> features = new ArrayList<>();
    /* Source: A data source specifies the geographic coordinate where the image marker gets placed. */
	features.add(Feature.fromGeometry(Point.fromCoordinates(new double[] {-72.19226170680705,41.71499147931593})));
	FeatureCollection featureCollection = FeatureCollection.fromFeatures(features);
	GeoJsonSource source = new GeoJsonSource(MARKER_SOURCE, featureCollection);
	mapboxMap.addSource(source);
	/* Style layer: A style layer ties together the source and image and specifies how they are displayed on the map. */
	SymbolLayer markerStyleLayer = new SymbolLayer(MARKER_STYLE_LAYER, MARKER_SOURCE)
	  .withProperties(
		PropertyFactory.iconAllowOverlap(true),
		PropertyFactory.iconImage(MARKER_IMAGE)
	  );
	mapboxMap.addLayer(markerStyleLayer);
  }
`

Whereas I am having an issue with MarkerOptions. My markers are added in a loop with this code:

`Marker newMarker = mainMap.addMarker(new MarkerOptions()
                                            .position(new LatLng(lat, lng))
                                            .title(name)
                                            .icon(icon)
                                            .snippet("snip"));`

**Comment by dportology** [comment] 2018-05-31 00:55
I beleive the issue is with custom map styling.

I have created a simple example project in which I was able to isolate the issue: (https://github.com/dportology/MapboxTrialProject), You can use this example, although I tested this in my main project as well and was able to reproduce it there as well. 

Changing the mapbox:mapbox_styleUrl attribute between
`mapbox:mapbox_styleUrl="@string/mapbox_style_mapbox_streets"`
 and my custom style:
`mapbox:mapbox_styleUrl="mapbox://styles/dportology/cjgztq95s000h2rpfqoq3ideb"`
makes the issue come up and go away. All markers work all the time with the default style.

I'm not sure why this is, but I'm guessing it has something to do with how layers work in mapbox? I unfortunately don't know much about layers and haven't been able to confirm why yet. Please advise.

**Comment by LukasPaczos** [comment] 2018-06-01 09:11
This looks like a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/11795. Closing for the time being.
Feel free to let us know if fixes related to https://github.com/mapbox/mapbox-gl-native/issues/11795 (when available) don't help with your issue.

**Closed by LukasPaczos** 2018-06-01 09:11 UTC
Labels: Android
