### ISSUE TITLE
Unknown Native Exception when setting Filter on Layer

### ISSUE THREAD

**Issue by vanshg** [mapbox/mapbox-gl-native#11264] opened 2018-02-20 20:06 UTC
When setting a `Filter` on a `LineLayer`, I sometimes get `unknown native exception`. I haven't been able to reproduce myself, but I've got a couple crash logs that have this error.

Using Mapbox version 5.3.2
Occurs mostly on Android 7, but also on Android 5 and 6. I don't have any crash reports from Android 8.

```
Fatal Exception: java.lang.Error
unknown native exception
com.mapbox.mapboxsdk.style.layers.Layer.nativeSetFilter (Layer.java)
com.mapbox.mapboxsdk.style.layers.LineLayer.setFilter (LineLayer.java:77)
```

**Comment by tobrun** [comment] 2018-02-21 07:02
@vanshg do you have a bit more context on this exception? Could it be that your are invoking `Layer#setFilter` after the MapView has been destroyed? eg. after an AsyncTask has finished executing.

**Comment by vanshg** [comment] 2018-02-27 21:15
is there a simple way to check the destroy status? I see a `destroyed` variable in `MapView`, but it is private

**Comment by tobrun** [comment] 2018-02-28 06:07
@vanshg destroyed is set as part of MapView#onDestroy, the equivalent of something you are able to hook into is `Activity#isFinishing()`. Hardening calls around destroyed mapview and the underlying sources/layers is ticketed in #10947.

**Comment by vanshg** [comment] 2018-03-06 17:37
Normally, I would do something like that, but these operations are taking place as a part of an activity independent module. The ticket you mentioned might be what I'm running into, so I look forward to that getting resolved.

**Comment by jfirebaugh** [comment] 2018-05-18 19:54
Closing as presumptive duplicate of #10947.

**Closed by jfirebaugh** 2018-05-18 19:54 UTC
Labels: Android, needs information
