### ISSUE TITLE
Removing annotations doesn't work on Android. 

### ISSUE THREAD

**Issue by fcarello** [mapbox/mapbox-gl-native#2763] opened 2015-10-23 16:01 UTC
Tried out all of the following methods:
- mapView.removeAllAnnotations();
- mapView.removeAnnotation(polyline);

**Comment by ljbade** [comment] 2015-10-23 16:33
@tobrun Hmm this is working in Sirius is it not? With the clear annotations menu item?

**Comment by ljbade** [comment] 2015-10-23 22:03
We need to add a test for this to test app.

**Comment by tobrun** [comment] 2015-10-23 22:39
@ljbade 

We have an [example](https://github.com/mapbox/mapbox-gl-native/blob/2726-finish-add-markers-in-bulk/android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java#L500) in the test app itself. I also used it today while implementing markers without any issue.

**Comment by ljbade** [comment] 2015-10-23 22:43
@fcarello What version are you using?

**Comment by fcarello** [comment] 2015-10-24 14:10
@ljbade Hey, thanks for the quick response on that. I'm using version 2.1.0. I'm actually using polylines to draw 3 calculated routes alternatives on the mapview. When switching in the UI between the routes (polyline annotations) I need to change the color of the selected one to a defined highlight color. Thus I'm currently removing all routes and redrawing them again with respective colors. For some reason the old routes are not removed.

**Comment by ljbade** [comment] 2015-10-25 12:15
@fcarello Do you mind testing it with `master`?

**Comment by ljbade** [comment] 2015-10-25 13:50
@tobrun Can you add to the bulk marker test activity a remove button that tests both remove and remove all functions?

**Comment by tobrun** [comment] 2015-10-27 07:52
I'm adding a test setup for this in #2809

**Comment by tobrun** [comment] 2015-10-27 10:25
I have added a test feature activity in the sample app in  f3ffb45.

In that test activity:
 - mMapView.removeAnnotation(mPolyLines.get(0));
 - mMapView.removeAnnotations(mPolyLines);
 - mMapView.removeAllAnnotations();

For me this works as indented but I have changed some internals for #2809 and #2811.

@fcarello 
I will ping you here when a new snapshot becomes available, would you be able to retest this?

**Comment by fcarello** [comment] 2015-10-27 14:54
@tobrun Sure. Just let me know. Thanks for your great support guys!

**Comment by tobrun** [comment] 2015-10-27 19:04
@fcarello new SNAPSHOT was released. 

Install instructions can be found [here](https://www.mapbox.com/android-sdk/#gradle)
If that doesn't help, could you compare your code with this [Activity](https://github.com/mapbox/mapbox-gl-native/blob/f3ffb45cf6adbdca375217c645eb455ff47991ec/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PolylineActivity.java)?

**Comment by fcarello** [comment] 2015-10-28 17:27
@tobrun Hey there. I managed to integrate the snapshot. After some teste I realized two things: The polyline adding/removal issue was my fault :/ The good thing is that your example code led me to the solution. So great support on that! The second thing I noticed is that you refactored the way to use custom marker icons. Using a bitmap (which I need to create at runtime, as the color changes according some application state) as icon was one of the missing features in the release build. So glad to see that you are introducing that. What's still missing is a way to update the bitmap for a an existing and added marker without having to remove and re-add the marker again. Or did I overlook that method? Nevertheless, thanks again for your awesome support on that!

**Comment by tobrun** [comment] 2015-10-28 17:56
@fcarello Cool that you were able to resolve your issue!
I believe it is currently not possible to update the bitmap dynamically. 
I will need loop in @ljbade to verify this. 
If that is the case we should open a feature request for it. 

Closing the issue for now, hence the problem is resolved.

**Closed by tobrun** 2015-10-28 17:56 UTC
Labels: Android, bug

**Comment by ljbade** [comment] 2015-10-29 00:44
@fcarello Yes currently there is no way to modify annotations once they are added. We are currently working on refactoring bits of core GL to allow this, so keep an eye out.

A work around is to remove then re-add the annotations, but it can cause some flicker - https://github.com/mapbox/mapbox-gl-native/issues/1688). Hopefully this will be fixed soonish.

**Comment by fcarello** [comment] 2015-10-29 06:29
@ljbade Sounds promising. I actually use the same workaround you described. We at COBI will still have a close eye to the further development of mapbox. We really think you are doing a great job. Thanks again guys!
