### ISSUE TITLE
increase click area of of marker

### ISSUE THREAD

**Issue by basitsaleemmb** [mapbox/mapbox-gl-native#12996] opened 2018-10-01 14:35 UTC
how can i increase the clickable area of marker.
 this.mapboxMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
                @Override
                public boolean onMarkerClick(@NonNull Marker marker) {
       }
}

**Comment by tobrun** [comment] 2018-10-09 11:56
@basitsaleemmb
Would love to address the root cause of your issue:
 - Do you feel the marker click area is too small? 
 - Would you be able to provide some resources of your marker image or a video showcasing missed click events?

For now however you can workaround this issue by rolling your own click handling system:

```java
  private void addSymbolClickListener() {
    mapboxMap.addOnMapClickListener(point -> {
      PointF screenPoint = mapboxMap.getProjection().toScreenLocation(point);
      // RectF can increase the toucharea
      List<Feature> features = mapboxMap.queryRenderedFeatures(screenPoint, "com.mapbox.annotations.points");
      if (!features.isEmpty()) {
        Feature feature = features.get(0);
        Toast.makeText(
          context,
          "hello",
          Toast.LENGTH_LONG).show();
      }
    });
  }
```

In above code block you can alter the PointF querying by a RectF equivalent. You also need to implement mapping between the GeoJSON Feature and the Marker itself.

Closing for now but feel free to add more information to this ticket!

**Closed by tobrun** 2018-10-09 11:56 UTC
Labels: Android, question
