### ISSUE TITLE
Method to set visible rectangle would be useful

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1293] opened 2015-04-17 20:22 UTC
MKMapKit has a method to set the visible rectangle of a map. Very useful.
`- (void)setVisibleMapRect:(MKMapRect)mapRect animated:(BOOL)animate`

It would be a great addition to MapBox GL for iOS. And it looks like it's just exposing something that would call `- (void)zoomToSouthWestCoordinate:(CLLocationCoordinate2D)southWestCoordinate northEastCoordinate:(CLLocationCoordinate2D)northEastCoordinate animated:(BOOL)animated`

**Comment by incanus** [comment] 2015-04-21 23:35
Dupe of https://github.com/mapbox/mapbox-gl-native/issues/1092.

**Closed by incanus** 2015-04-21 23:35 UTC
