### ISSUE TITLE
Telemetry Crash at high zoom?

### ISSUE THREAD

**Issue by leelx78** [mapbox/mapbox-gl-native#11750] opened 2018-04-20 22:38 UTC
Hi I see an issue in 6.0.1 which I don't have in 5.5.2

If I zoom in a lot in some regions the map crashes and resets as soon as it gets to draw the buildings. Example: try to zoom into Addis Ababa in Ethiopia (south of the city), I get frequent crashes around that but I also see them in EU (random).

The stack trace is not helpful (below) but there is a mention of the Telemetry service..

Thanks

> --------- beginning of system
01-21 09:02:50.505 I/WindowState: WIN DEATH: Window{25806fbc u0 SurfaceView}
01-21 09:02:50.506 W/InputDispatcher: channel 'f58dede com.demo.app/com.demo.app.main (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-21 09:02:50.506 E/InputDispatcher: channel 'f58dede com.demo.app/com.demo.app.main (server)' ~ Channel is unrecoverably broken and will be disposed!
01-21 09:02:50.509 I/Zygote: Process 5944 exited due to signal (11)
01-21 09:02:50.510 D/WifiService: Client connection lost with reason: 4
01-21 09:02:50.514 I/ActivityManagerService: Process com.demo.app (pid 5944) has died
01-21 09:02:50.516 W/ActivityManagerService: Scheduling restart of crashed service com.demo.app/com.mapbox.android.telemetry.TelemetryService in 1000ms
01-21 09:02:50.516 I/WindowState: WIN DEATH: Window{f58dede u0 com.demo.app/com.demo.app.main}
01-21 09:02:50.516 W/InputDispatcher: Attempted to unregister already unregistered input channel 'f58dede com.demo.app/com.demo.app.main (server)'
01-21 09:02:50.518 W/ActivityManagerService: Force removing ActivityRecord{9f6872c u0 com.demo.app/.main t106}: app died, no saved state

**Comment by tobrun** [comment] 2018-04-23 12:51
@leelx78 thank you for reaching out, I having trouble reproducing this issue. On what kind of hardware reproducing this crash? Is there any other useful information in the logcat above the pasted block?

**Comment by leelx78** [comment] 2018-04-23 17:16
@tobrun hardware is RK3368. No other info available unfortunately. It just crashes and restarts the app. 
All I can say is that this only happens on 6.0.1 but not on 5.5.x. 

Tha main line that suggested a Telemetry issue was

`Scheduling restart of crashed service com.demo.app/com.mapbox.android.telemetry.TelemetryService in 1000ms`

What is Telemetry doing? Can that be turned off?

**Comment by tobrun** [comment] 2018-05-02 12:43
This isn't the actual crash, the crash log will be found above those lines. This is only a message indicating the restart since the app crashed and thus crashed the service. Closing, feel free to open a new ticket with the actual crash. Thank you for reaching out.

**Closed by tobrun** 2018-05-02 12:43 UTC
Labels: Android, telemetry
