### ISSUE TITLE
[iOS] onlineFileSource assertion failed: (ec=0)

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#4099] opened 2016-02-24 14:07 UTC
iOS 9.2 + simulator. Branch iOS 3.1.1.
Creating a simple mapView, got a crash du to an assertion failed in the OnlineFileSource thread:

Assertion failed: (ec == 0), function unlock, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/libcxx_Sim/libcxx-237.2/src/mutex.cpp, line 45.

Nothing more to help ... I don't see it on device for the moment.

**Comment by friedbunny** [comment] 2016-02-24 15:36
This is a dupe of #4025, which was fixed by #4033.

**Closed by friedbunny** 2016-02-24 15:36 UTC

**Comment by RomainQuidet** [comment] 2016-02-24 16:41
thanks again. Searched on opened bugs, not closed ones!
