### ISSUE TITLE
Marker clustering for mobile!

### ISSUE THREAD

**Issue by vns-cuong** [mapbox/mapbox-gl-native#3967] opened 2016-02-16 05:42 UTC
Can we do this for android and iOs?
https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/

I found that we can do this with mapbox-ios-sdk-legacy, but with current latest sdk, I don't know how to do this?

**Comment by 1ec5** [comment] 2016-02-16 05:50
Duplicate of #320. This was recently implemented in GL JS in mapbox/mapbox-gl-js#1931 and in mapbox/supercluster; that work now needs to be ported to C++.

**Closed by 1ec5** 2016-02-16 05:50 UTC
