### ISSUE TITLE
Icon has dark color on map initialization. After zoom in it becomes white

### ISSUE THREAD

**Issue by F0rc0sigan** [mapbox/mapbox-gl-native#15777] opened 2019-10-08 06:29 UTC
I am using mapbox android sdk in my projct for past 2 years. I am using custom icon for markers and use symbol layer. It was working fine. Now when i run map first it shows dark icons, after i zoom in they become white (like it should be). Could you advice if that is bug or i am missing something? I am not sure at which version problem appeared, i mentioned it at sdk > 8.

Update.
I figure out that problem happens only when clustering is turned on.

### Steps to reproduce

 1. Add custom icon via symbol layer. I use png image format.
 2. [Start map and it show dark markers](https://i.imgur.com/wiCtDuj.png)
 3. [After zoom in they become white like they should be](https://i.imgur.com/DYBJU6Z.png)
 4. [At certain zooms i can get this](https://i.imgur.com/6YFGNVP.png)

### Expected behavior
Marker should be white 

### Actual behavior
Markers are dark

### Configuration

API 26 - API 28
I use emulator for testing Nexus9 or pixel2
Mapbox version 8.4

**Comment by tobrun** [comment] 2019-10-08 14:00
duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10829 
thank you for reaching out

**Closed by tobrun** 2019-10-08 14:00 UTC
