### ISSUE TITLE
 GLEngine glFinish_Exec

### ISSUE THREAD

**Issue by minikin** [mapbox/mapbox-gl-native#1995] opened 2015-08-05 14:03 UTC
Hi guys,

While starting an app. The screen with mapbox map didn't load. 
[More details] (http://crashes.to/s/a4f49b75360)
```
Thread : Crashed: com.apple.main-thread
0  libGPUSupportMercury.dylib     0x2b248776 gpus_ReturnNotPermittedKillClient
1  libGPUSupportMercury.dylib     0x2b249251 gpusSubmitDataBuffers
2  IMGSGX543RC2GLDriver           0x2282214d 
3  GLEngine                       0x2697095b glFinish_Exec
4  GLKit                          0x24d6354d -[GLKView _display:] + 344
5  QuartzCore                     0x26f74617 CA::Layer::display() + 106
6  QuartzCore                     0x26f58729 CA::Layer::display_if_needed(CA::Transaction*) + 200
7  QuartzCore                     0x26f583ed CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
8  QuartzCore                     0x26f57d81 CA::Context::commit_transaction(CA::Transaction*) + 224
9  QuartzCore                     0x26f57b6f CA::Transaction::commit() + 434
10 UIKit                          0x275411eb _afterCACommitHandler + 126
11 CoreFoundation                 0x23e94fed __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
12 CoreFoundation                 0x23e926ab __CFRunLoopDoObservers + 278
13 CoreFoundation                 0x23e92ab3 __CFRunLoopRun + 914
14 CoreFoundation                 0x23ddf201 CFRunLoopRunSpecific + 476
15 CoreFoundation                 0x23ddf013 CFRunLoopRunInMode + 106
16 GraphicsServices               0x2b8b0201 GSEventRunModal + 136
17 UIKit                          0x275aba09 UIApplicationMain + 1440
18 Kebab                          0x00058b40 main (AppDelegate.swift:16)
19 libdyld.dylib                  0x32dc4aaf start + 2

```
```
Thread : com.apple.NSURLConnectionLoader
0  libcorecrypto.dylib            0x32d56c68 ccaes_arm_decrypt_cbc + 216
1  ???                            0x176d18c0 
2  libcorecrypto.dylib            0x32d5b129 cbc_wrapper + 60
3  libsystem_coretls.dylib        0x32e537cb CCSymmEncryptDecrypt + 166
4  libsystem_coretls.dylib        0x32e522c1 tls1DecryptRecord + 60
5  libsystem_coretls.dylib        0x32e52bdd tls_record_decrypt + 152
6  Security                       0x272f2751 SSLRecordReadInternal + 268
7  Security                       0x272f4c97 SSLReadRecord + 18
8  Security                       0x272f5009 SSLRead + 272
9  CFNetwork                      0x239289e1 SocketStream::securityRead_NoLock(unsigned char*, long, unsigned char*, unsigned char*) + 124
10 CFNetwork                      0x239288a1 SocketStream::securityBufferedRead_NoLock() + 132
11 CFNetwork                      0x2390715d SocketStream::socketCallbackReadLocked(SocketStreamSignalHolder*) + 68
12 CFNetwork                      0x239067c5 SocketStream::socketCallback(__CFSocket*, unsigned long, __CFData const*, void const*) + 104
13 CFNetwork                      0x23906727 SocketStream::_SocketCallBack_stream(__CFSocket*, unsigned long, __CFData const*, void const*, void*) + 58
14 CoreFoundation                 0x23e9789b __CFSocketPerformV0 + 554
15 CoreFoundation                 0x23e94faf __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
16 CoreFoundation                 0x23e94451 __CFRunLoopDoSources0 + 364
17 CoreFoundation                 0x23e92a25 __CFRunLoopRun + 772
18 CoreFoundation                 0x23ddf201 CFRunLoopRunSpecific + 476
19 CoreFoundation                 0x23ddf013 CFRunLoopRunInMode + 106
20 CFNetwork                      0x2397ba4f +[NSURLConnection(Loader) _resourceLoadLoop:] + 486
21 Foundation                     0x24c0e3bb __NSThread__main__ + 1118
22 libsystem_pthread.dylib        0x32f0ce23 _pthread_body + 138
23 libsystem_pthread.dylib        0x32f0cd97 _pthread_start + 118
24 libsystem_pthread.dylib        0x32f0ab20 thread_start + 8
```
```
Thread : my.ios.App.189703C2-E4E6-4CC6-83A8-7B03CD8C8D7B-1035-00000104C5C9ED18.events.serial
0  libsystem_kernel.dylib         0x32e7b4c4 semaphore_wait_trap + 8
1  libsystem_platform.dylib       0x32f07435 _os_semaphore_wait + 12
2  libdispatch.dylib              0x32daa7ff _dispatch_barrier_sync_f_slow + 362
3  MapboxGL                       0x0041befb -[MGLMapboxEvents contentSizeScale] + 330
4  MapboxGL                       0x0041b155 __44-[MGLMapboxEvents pushEvent:withAttributes:]_block_invoke + 1428
5  libdispatch.dylib              0x32da32e3 _dispatch_call_block_and_release + 10
6  libdispatch.dylib              0x32dab729 _dispatch_queue_drain + 1468
7  libdispatch.dylib              0x32da5aad _dispatch_queue_invoke + 84
8  libdispatch.dylib              0x32dacf9f _dispatch_root_queue_drain + 394
9  libdispatch.dylib              0x32dae3c3 _dispatch_worker_thread3 + 94
10 libsystem_pthread.dylib        0x32f0adc1 _pthread_wqthread + 668
11 libsystem_pthread.dylib        0x32f0ab14 start_wqthread + 8
```

```
Thread : SQLite Cache
0  libsystem_kernel.dylib         0x32e7e99c kevent + 24
1  MapboxGL                       0x0045690b uv__io_poll + 1050
2  MapboxGL                       0x00445df3 uv_run + 122
3  MapboxGL                       0x00441c53 void mbgl::util::Thread<mbgl::SQLiteCache::Impl>::run<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>, 0ul>(mbgl::util::ThreadContext, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>&&, std::__1::integer_sequence<unsigned long, 0ul>) + 206
4  MapboxGL                       0x00441b09 std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::SQLiteCache::Impl>::Thread<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(mbgl::util::ThreadContext const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&)::'lambda'()> >(void*, void*) + 236
5  libsystem_pthread.dylib        0x32f0ce23 _pthread_body + 138
6  libsystem_pthread.dylib        0x32f0cd97 _pthread_start + 118
7  libsystem_pthread.dylib        0x32f0ab20 thread_start + 8
```

**Comment by jfirebaugh** [comment] 2015-08-05 15:37
Thanks for the report. This looks like a duplicate of #1460. If you upgrade to version 0.5.1 or later it should be fixed.

**Closed by jfirebaugh** 2015-08-05 15:37 UTC
