### ISSUE TITLE
Thread Sanitizer: data race between RunLoop::push() and ~RunLoop()

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#10125] opened 2017-10-04 21:15 UTC
In https://circleci.com/gh/mapbox/mapbox-gl-native/27095, the Clang Thread sanitizer reported this issue.

/cc @jfirebaugh @ivovandongen

**Comment by jfirebaugh** [comment] 2017-10-04 21:29
Duplicate of #9620.

**Closed by jfirebaugh** 2017-10-04 21:29 UTC
Labels: bug, Core
