### ISSUE TITLE
use stale cache when network is not available

### ISSUE THREAD

**Issue by hanchao** [mapbox/mapbox-gl-native#1811] opened 2015-07-01 09:55 UTC
This would be useful when there is no network.

I try call `notify` and `startRealRequest` when cache expired.

```
void DefaultFileSource::Impl::startCacheRequest(const Resource& resource) {
...
         if(expired()){
            std::shared_ptr<const Response> res = std::move(response);
            // Notify all observers.
            for (auto req : request->observers) {
                req->notify(res);
            }
            // stale cache. Run the real request.
            startRealRequest(resource, res);
        } 
...
}
```
 But can't work, there are a lot of mistakes mistakes. 
`Request` could not handle the two `notify`, it will be deleted after the first `notify`

**Comment by kkaefer** [comment] 2015-07-01 09:56
Duplicate of #896

**Closed by kkaefer** 2015-07-01 09:56 UTC
