### ISSUE TITLE
MapBox Crash after a few minutes

### ISSUE THREAD

**Issue by dsuresh-ap** [mapbox/mapbox-gl-native#11949] opened 2018-05-18 17:13 UTC
**Platform: Android**
**Mapbox SDK version:6.1.1**

The app crashes after about 3 minutes on multiple phones.

```
05-18 13:06:02.526 14082-14153/com.gotenna.pro A/art: art/runtime/indirect_reference_table.cc:115]     51195: 0x131a39a0 java.lang.Thread
    art/runtime/indirect_reference_table.cc:115]     51194: 0x131a3940 java.lang.Thread
    art/runtime/indirect_reference_table.cc:115]     51193: 0x131a38e0 java.lang.Thread
    art/runtime/indirect_reference_table.cc:115]     51192: 0x133a6f40 java.lang.Thread
    art/runtime/indirect_reference_table.cc:115]     51191: 0x131a3880 java.lang.Thread
    art/runtime/indirect_reference_table.cc:115]     51190: 0x131a3820 java.lang.Thread
    art/runtime/indirect_reference_table.cc:115]   Summary:
    art/runtime/indirect_reference_table.cc:115]         1 of com.mapbox.mapboxsdk.maps.NativeMapView
    art/runtime/indirect_reference_table.cc:115]         1 of com.mapbox.mapboxsdk.maps.MapView$5
    art/runtime/indirect_reference_table.cc:115]         1 of android.opengl.GLSurfaceView$GLThread
    art/runtime/indirect_reference_table.cc:115]      5683 of java.lang.Class (5683 unique instances)
    art/runtime/indirect_reference_table.cc:115]         1 of java.lang.ThreadGroup
    art/runtime/indirect_reference_table.cc:115]         1 of byte[] (1 elements)
    art/runtime/indirect_reference_table.cc:115]         2 of byte[] (16 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:115]         2 of byte[] (100 elements) (2 unique instances)
    art/runtime/indirect_reference_table.cc:115]         3 of byte[] (392 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:115]         3 of byte[] (784 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:115]         4 of byte[] (1152 elements) (4 unique instances)
    art/runtime/indirect_reference_table.cc:115]         5 of byte[] (1764 elements) (5 unique instances)
    art/runtime/indirect_reference_table.cc:115]         6 of byte[] (1820 elements) (6 unique instances)
    art/runtime/indirect_reference_table.cc:115]         3 of byte[] (2016 elements) (3 unique instances)
    art/runtime/indirect_reference_table.cc:115]         8 of byte[] (2100 elements) (8 unique instances)
05-18 13:06:14.228 446-446/? A/DEBUG:     #15 pc 0025fffb  /system/lib/libart.so (_ZN3art14ObjectRegistry11InternalAddINS_6mirror6ObjectEEEyNS_6HandleIT_EE+794)
        #16 pc 00260183  /system/lib/libart.so (_ZN3art14ObjectRegistry3AddEPNS_6mirror6ObjectE+74)
        #17 pc 001476b1  /system/lib/libart.so (_ZN3art3Dbg11GetThreadIdEPNS_6ThreadE+252)
        #18 pc 00254033  /system/lib/libart.so (_ZN3art4JDWP9JdwpState16PostThreadChangeEPNS_6ThreadEb+450)
        #19 pc 0014b427  /system/lib/libart.so (_ZN3art3Dbg15PostThreadStartEPNS_6ThreadE+26)
        #20 pc 00341833  /system/lib/libart.so (_ZN3art6Thread6AttachEPKcbP8_jobjectb+562)
        #21 pc 0031dae9  /system/lib/libart.so (_ZN3art7Runtime19AttachCurrentThreadEPKcbP8_jobjectb+12)
        #22 pc 0024d30b  /system/lib/libart.so (_ZN3art3JII19AttachCurrentThreadEP7_JavaVMPP7_JNIEnvPv+142)
        #23 pc 000fe6c7  /system/lib/libart.so (_ZN3art8CheckJII19AttachCurrentThreadEP7_JavaVMPP7_JNIEnvPv+94)
        #24 pc 0007c6b7  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #25 pc 0007c5cd  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #26 pc 0005ed37  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #27 pc 001855e7  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #28 pc 0030c9a1  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #29 pc 0030bf61  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #30 pc 0030b9af  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #31 pc 002f9bbf  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #32 pc 001856e5  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #33 pc 0018580f  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #34 pc 00277fbb  /data/app/com.gotenna.pro-1/lib/arm/libmapbox-gl.so
        #35 pc 0003fd0b  /system/lib/libc.so (_ZL15__pthread_startPv+30)
        #36 pc 0001a145  /system/lib/libc.so (__start_thread+6)
```

The crash log doesn't seem to be consistent among each crash.

**Comment by jfirebaugh** [comment] 2018-05-18 20:20
Duplicate of #11556.

**Closed by jfirebaugh** 2018-05-18 20:20 UTC
Labels: Android
