### ISSUE TITLE
Ambient cache not work after downloading other style offline cache.

### ISSUE THREAD

**Issue by Dagzo** [mapbox/mapbox-gl-native#11252] opened 2018-02-20 03:09 UTC
**Platform:** Android
**Mapbox SDK version:** 5.4.1

### Steps to trigger behavior

 1. Open simple Outdoor style map view on activity.
 2. Download a region as Street style.
 3. Open Street style map activity from outdoor style activity.
 4. Back to Outdoor style activity.
 5. Ambient cache of outdoor map not work.

### Expected behavior
Ambient cache work well.

### Actual behavior
Ambient cache not work.
To fetch map resources, Internet connection starts every time, every scroll.

I use custom mapbox style that use Japanese fonts.
I think it's data size is big. Ambient caching is essential.

**Comment by jfirebaugh** [comment] 2018-07-20 20:08
Duplicate of #4411.

**Closed by jfirebaugh** 2018-07-20 20:08 UTC
Labels: Android, offline
