### ISSUE TITLE
Android: Road labels are not visible even after applying pull-9573

### ISSUE THREAD

**Issue by mdakram** [mapbox/mapbox-gl-native#9599] opened 2017-07-25 03:48 UTC
I was facing same road layer missing issue with samsung device i have. It seems its already there
even after i have applied [pull 9573](https://github.com/mapbox/mapbox-gl-native/pull/9573).

Chipset, GPU and CPU info

Chipset | Broadcom BCM23550Spreadtrum SC8830 - GT-I9060I
CPU | Quad-core 1.2 GHz Cortex-A7
GPU | Broadcom VideoCore IVMali-400MP2 - GT-I9060I

below is screenshot of mapview and processor's info.

![MapView](https://user-images.githubusercontent.com/1751271/28554919-0b94fa82-711a-11e7-8fed-5065e976fe7a.png)

![Phone info](https://user-images.githubusercontent.com/1751271/28554922-0bbea35a-711a-11e7-8941-072093132eef.png)

![Processor's info](https://user-images.githubusercontent.com/1751271/28554915-06266e1e-711a-11e7-96d9-cb6a99f309e8.png)

**Comment by jfirebaugh** [comment] 2017-07-25 04:03
Duplicate of #7583.

**Closed by jfirebaugh** 2017-07-25 04:03 UTC
