### ISSUE TITLE
iOS bug! When I change a MGLFillStyleLayer fillOpacity after style did loaded , the layers draw the order incorrectly

### ISSUE THREAD

**Issue by dgccom** [mapbox/mapbox-gl-native#9911] opened 2017-09-05 08:39 UTC
I add a MGLFillStyleLayer after style did loaded,then I change the MGLFillStyleLayer fillOpacity, the layers draw incorrectly.When fillOpacity equal 1.0,it is ok, but fillOpacity less than 0.99,the symbol layer and line layer draw under the MGLFillStyleLayer,it should be above the MGLFillStyleLayer
1.when set fillOpacity = 1.0,as the picture shows
![img_0355](https://user-images.githubusercontent.com/16534756/30052341-b1dc6eb2-9257-11e7-9e68-9a1e0ba688d8.PNG)

2.when set fillOpacity = 0.9f,as the picture shows
![img_0357](https://user-images.githubusercontent.com/16534756/30052368-c6950788-9257-11e7-89b3-00d9c386fc55.PNG)

3.when set fillOpacity = 0.7f,as the picture shows
![img_0356](https://user-images.githubusercontent.com/16534756/30052397-e4c5b1bc-9257-11e7-9193-445ebd35d106.PNG)

4.when set fillOpacity = 0.4f,as the picture shows
![img_0359](https://user-images.githubusercontent.com/16534756/30052421-f22a5b50-9257-11e7-8036-18f2f690bb8c.PNG)

**Comment by fabian-guerra** [comment] 2017-09-05 13:33
Hi @dgccom. Thank you for using Mapbox. I am sorry to hear you are having some issues. Is it possible you could help us providing a code snipet or test app to look into this issue?

**Comment by jmkiley** [comment] 2017-09-05 17:17
This looks like it may be a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/8699

**Closed** 2017-09-05 17:18 UTC
Labels: bug, iOS
