### ISSUE TITLE
Marker shows wrong position after zoom

### ISSUE THREAD

**Issue by TankJK** [mapbox/mapbox-gl-native#13992] opened 2019-02-26 13:02 UTC
Hi there,

We have requirement for showing the markers on Map. I have created a demo using information from https://docs.mapbox.com/android/maps/examples/marker-symbol-layer/. 

Markers shows correct position initially but when zoom map, marker position points to wrong location. Before zoom, it was at correct position but after zoom, marker pointer points out of country.

I have even given iconOffset(new Float[]{0f, -9f}) as suggested in above link.

### Steps to reproduce

 1. Add the markers using SymbolLayer
 2. Zoom the map
 3. Marker  will point to  wrong position

### Expected behavior
Marker  will point to  wrong position 

### Actual behavior
Marker  should show same position before and after zoom.

### Configuration

**Android versions:** 
Android 7.0
**Device models:** 
Moto G
**Mapbox SDK versions:** 
7.1.2
mapbox-android-sdk:7.1.2 .

Before zoom
![marker_before_zoom_2](https://user-images.githubusercontent.com/25880682/53415079-442c4200-39f6-11e9-9fdd-7fbb97df3c22.png)

After zoom
![marker_after_zoom_2](https://user-images.githubusercontent.com/25880682/53415083-468e9c00-39f6-11e9-97b6-20f543b5c8c5.png)

Thanking you in advance,

Regards,
Tank

**Comment by LukasPaczos** [comment] 2019-02-26 13:28
Hey @TankJK, thanks for using Mapbox!

As you can see in the style-spec, [the `icon-offset` property](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-offset) represents the **pixel offset** which doesn't take any real latitude-longitude values into account. If you'd like to scale this property, you can use the zoom-based interpolation like so:
```
style.addLayer(new SymbolLayer("marker-layer", "marker-source")
  .withProperties(PropertyFactory.iconImage("my-marker-image"),
    iconOffset(
      Expression.interpolate(
        Expression.linear(), Expression.zoom(),
        Expression.stop(1, new Float[] {0f, -9f}),
        Expression.stop(5, new Float[] {0f, -8f}),
        Expression.stop(10, new Float[] {0f, -5f}),
        Expression.stop(15, new Float[] {0f, -2f})
      )
    )
  )
);
```
You can also experiment with adding a padding to your icon image.

Closing as this is working as designed.

**Closed by LukasPaczos** 2019-02-26 13:28 UTC
Labels: Core, support

**Comment by TankJK** [comment] 2019-02-26 14:23
Dear LukaPaczos,

Thank you for replying.

I tried your suggested code but still have same issue. Can you please suggest how to rectify it?

Thanking you in advance,
Tank

**Comment by LukasPaczos** [comment] 2019-02-26 14:24
You will need to tweak the example I provided based on your bitmap's dimensions.

**Comment by TankJK** [comment] 2019-02-26 14:28
Thank you for the reply.
Is there any documentation available which will help me to understand the dimension and offset relationship.

Regards,
Tank

**Comment by LukasPaczos** [comment] 2019-02-26 14:55
Unfortunately, I don't think there's any documentation around the topic of offsetting the icon to keep its arbitrary point (other than center) at the constant latitude-longitude value pair as this isn't a truly supported use-case. I think your best bet is to define an offset that positions the icon in the most precise place on the maximum available zoom level. Afterward, you can scale that offset with the zoom-based interpolation when the zoom increases, but keep in mind, that the furthest away you go, the least precise you need to be because the pixel-per-meter value will start to dramatically decrease.

On the other hand, if the positioning is the most important factor, you can add a bottom padding to your icon, so that its center is precisely where the tip of the marker points. This way your icon should always be correctly placed, [take a look at this image for example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res/drawable-xxhdpi/mapbox_marker_icon_default.png). The downside of this approach is that you will have an extended click area by the invisible bottom padding.
