### ISSUE TITLE
setPadding & LatLngBounds are not working as expected.

### ISSUE THREAD

**Issue by khanyasirforu** [mapbox/mapbox-gl-native#15199] opened 2019-07-23 18:28 UTC
I am migrating my app from google maps to Mapbox maps

First of all LatLngBound is not considering if we have set map padding, like google does.

second when i setPadding and trying to use LatLngBound its not being fit in screen.

### Steps to reproduce

1. 

set padding 
left:0
top:0
right:0
bottom:800

2. Take 50 -60 vertically aligned points and draw a polyline with 
3. try to set LatLngBound on those points

### Expected behavior

Whole polyline should be visible when we call animate/move/ease on map.

### Actual behavior

polyline being pushed upside visible area

### Configuration

**Android versions:** 6,7,8,9
**Device models:** Moto G,Nokia 3, OnePlus 3T, MI A2
**Mapbox SDK versions:** 8.1.0

[Here is code](https://gist.github.com/khanyasirforu/d46e7723835b5ce21da6ee2542ded676)

**Comment by LukasPaczos** [comment] 2019-07-24 10:06
@brunoabinader @astojilj this is caused by https://github.com/mapbox/mapbox-gl-native/blob/cafecd3f6fedc16e7bf5dff699960978c3b5cb3d/src/mbgl/util/geo.cpp#L138-L139 and is expected, right?

**Comment by astojilj** [comment] 2019-07-24 10:47
@khanyasirforu 

> set padding
> left:0
> top:0
> right:0
> bottom:800

bottom:800 means that bottom padding is moved up 800px. What is the logical size of your view?

**Comment by khanyasirforu** [comment] 2019-07-24 11:07
Hi @astojilj actually i have a bottom sheet which has three states(You can relate it to google maps)
1. collapsed
2. anchored
3. expanded

in first two i am calculating height of bottomsheet view and setting padding accordingly. On one of my phone size is coming 800px, which i am setting as bottom padding and my polyline is being pushed up.

**Comment by astojilj** [comment] 2019-07-24 11:28
@khanyasirforu,
bottom padding equal to screen height causes that center of perspective (center of content area that is getting height 0) is pushed to the top edge, as expected.

**Comment by LukasPaczos** [comment] 2019-07-24 11:45
@khanyasirforu after setting the padding, you should reposition the camera to still have the line in your viewport. Could you compare your code to the implementation from  [this example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.kt) and https://github.com/mapbox/mapbox-gl-native/pull/14924? It works correctly for me locally.

Closing as answered, but please let us know if it didn't help to resolve your issue. If you're still hitting the issue, a contained reproducible example would be great. Thanks!

**Closed by LukasPaczos** 2019-07-24 11:45 UTC
Labels: Android

**Comment by khanyasirforu** [comment] 2019-07-24 12:01
@astojilj no bottom padding is not equal to screen height

screen height is 1920px
bottom padding i am setting is 800px

when i am setting padding 0,0,0,0 and passing 800 bottom padding in 
mapboxMap.moveCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds,0,0,0,800));
Its working as expected.

Hi @LukasPaczos i am preparing a demo app and will share.

**Comment by astojilj** [comment] 2019-07-24 12:15
@khanyasirforu 
API refers to [viewport size](https://docs.mapbox.com/android/api/map-sdk/8.1.0/com/mapbox/mapboxsdk/maps/MapboxMap.html#setPadding-int-int-int-int-), not to screen resolution.

Maybe [this](https://deviceatlas.com/blog/viewport-resolution-diagonal-screen-size-and-dpi-most-popular-smartphones#motorola) helps, too.

**Comment by mdakram** [comment] 2019-07-24 12:32
@astojilj thanks.

as i am coming from google maps, things were working as expected on google, can we make something like google?

**Comment by khanyasirforu** [comment] 2019-07-24 12:37
@astojilj Thanks,

As i was using same code with google and it was working as expected. I thought it would work with mapbox as well.

**Comment by khanyasirforu** [comment] 2019-07-31 11:41
Hi @LukasPaczos [i have created a sample app with same issue in it  please check](https://github.com/khanyasirforu/MapboxDemo)

**Comment by khanyasirforu** [comment] 2019-08-08 09:25
Hi @LukasPaczos please have a look into sample what i am trying to achieve.
