### ISSUE TITLE
Self-defined map style has conflicts with the fill-extrusion-color

### ISSUE THREAD

**Issue by YayinC** [mapbox/mapbox-gl-native#16113] opened 2020-01-13 15:50 UTC
My problem is weird.
When I use the **self-defined map style** in Mapbox GL JS, the circle-color works well but **fill-extrusion-color** doesn't work, which means no matter what color I assign, all fill extrusions will display the grey color. 
However, when I change the map style to mapbox template (light, dark), they work very well.  **fill-extrusion-color** perfectly display the assigned color.
Due to the data privacy, I can't post a screenshot. Does anyone have the similar problem or know the reason?

**Comment by astojilj** [comment] 2020-01-13 18:02
@YayinC ,
Which SDK are you using Mapbox GL JS (mentioned by you in issue description) your or Mapbox GL Native (this repository here is about mapbox-gl-native issues, not for mapbox-gl-js).

If you're using _self-defined map style in Mapbox GL JS_, please check the console for any style validation errors. It might help you debug the issue.

> Does anyone have the similar problem or know the reason?

I didn't see similar issue.

Otherwise, you'll need to help us to fix the issue by providing minimal example (style's JSON file or JS code you use) that is sufficient to reproduce the issue. Without JSON example it is not possible to debug the issue or know the reason. Thanks. Until then, closing this.

**Closed by astojilj** 2020-01-13 18:02 UTC

**Comment by jasondowalter** [comment] 2020-01-13 18:13
I’m sorry but I’m confused and don’t know what to do
