### ISSUE TITLE
[core] Raster tiles blurry

### ISSUE THREAD

**Issue by rinigus** [mapbox/mapbox-gl-native#10076] opened 2017-09-27 07:16 UTC
When using Mapbox GL Native with Qt through QML bindings on Linux desktop, I get blurry maps for raster sources/styles. This is very clear on maps that are rendered by Mapnik, for example. To reproduce, compare Leaflet presentation of the same map with the presentation by Mapbox GL and focus on labels.

I compared the images at full zoom levels (14 vs 14, ...). Its clear that 14.x would be interpolated by Mapbox GL, but I was expecting the same sharpness on the full zoom levels. This is not the case. It was tested with pixelRatio=1, tile sizes 512, 1024 (and specified as needed). 

When looking into logs of the map server, looks like the same level zoom is loaded as displayed by Mapbox GL when 512 tiles are used. For 1024, you get zoom level fetched from the map server that is one level smaller than displayed.

Maybe there is some smoothing filter applied while rendering the raster maps? Or some interpolation?

As it is, using Mapbox GL with the raster tiles leads to considerable regression in map quality. Which is not desired and would be great to fix.

I can upload images if needed later today.

Possibly related to https://github.com/mapbox/mapbox-gl-js/issues/1030 , which, according to the comments, seems not to be fully explained by `Math.floor` issue.

I am using my own QML bindings (https://github.com/rinigus/mapbox-gl-qml), but I presume that this did not cause such effect.

**Comment by jfirebaugh** [comment] 2017-09-27 15:38
What is the native size of your raster tiles? If 256px, did you set `tileSize: 256` on the raster source?

**Comment by rinigus** [comment] 2017-09-27 16:52
I have a server which can output many sizes. I tested 512x512 and specified tileSize: 512 as well as 1024x1024 with the tileSize: 1024:

For example:

```
{
    "version": 8,
    "name": "Raster",
    "sources": {
        "Raster": {
            "tiles": ["http://localhost:8553/v1/tile?scale=2&z={z}&x={x}&y={y}"],
            "type": "raster",
            "tileSize": 512
        }
    },
    "layers": [
        {
            "id": "raster",
            "type": "raster",
            "source": "Raster",
            "layout": {
                "visibility": "visible"
            },
            "paint": {
                "raster-opacity": 1
            }
        }
    ],
    "id": "test-raster"
}
```
I have repeated the test using provided Qt demo app (https://github.com/mapbox/mapbox-gl-native/tree/master/platform/qt/app) by replacing the used style with the style above and observed the same effect. Attached are the screenshots from Mapbox GL demo app (zoom level 14) and Leaflet (same zoom level). As you can see, Leaflet shows sharp image while Mapbox GL shows blurred tiles.  Finally, an original tile as served by the server is attached as well.
![leaflet](https://user-images.githubusercontent.com/15706605/30926295-517a22cc-a3bd-11e7-8d3d-8a6d5cd70624.png)
![mapboxgl](https://user-images.githubusercontent.com/15706605/30926294-517a158e-a3bd-11e7-810f-6a53aa5b10cb.png)
![tile](https://user-images.githubusercontent.com/15706605/30926321-65bb58e6-a3bd-11e7-9c83-d9c2412cf2b7.png)

**Comment by jfirebaugh** [comment] 2017-09-27 16:58
Thanks, just wanted to eliminate one common mistake. In that case, this is a duplicate of #4552.

**Comment by jfirebaugh** [comment] 2017-09-27 16:59
Ooops, that's a gl-js issue -- this is the native equivalent.

**Comment by SumeetMoray** [comment] 2017-09-29 13:29
Hi, i am also facing this issue when using a custom raster tile source. One of the TEMPORARY solution to this issue is to reduce the tilesize below 200 for example 150 : this would make the tiles appear more clear but the text size gets very much reduced and it gets difficult to read names of places. 

Anyway, does anyone know how to create custom vector tile server and set the style URL. I think this issue would not arise with vector tiles.

**Comment by rinigus** [comment] 2017-09-29 17:45
Just an additional note: its not specific to Qt, I have the same blurry map for glfw Linux bindings.

**Comment by kkaefer** [comment] 2018-05-09 15:16
This was fixed in https://github.com/mapbox/mapbox-gl-native/pull/10984

**Closed by kkaefer** 2018-05-09 15:16 UTC
Labels: Qt
