### ISSUE TITLE
Crash when downloading offline maps without enough free space on device

### ISSUE THREAD

**Issue by ioel** [mapbox/mapbox-gl-native#11346] opened 2018-03-01 05:40 UTC
**Platform:** Android
**Mapbox SDK version:** 5.4.0

### Steps to trigger behavior

 1. Use device with less than 100 MB free space
 2. Srart download any offline region which will take 100 MB or more
 3. Crash when free space is ended

Here's the log:

```
03-01 10:48:13.660: A/libc(4507): Fatal signal 6 (SIGABRT), code -6 in tid 4652 (DefaultFileSour)
03-01 10:48:13.764: A/DEBUG(4850): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-01 10:48:13.765: A/DEBUG(4850): Build fingerprint: 'samsung/a5y17ltexx/a5y17lte:7.0/NRD90M/A520FXXU3BQLA:user/release-keys'
03-01 10:48:13.765: A/DEBUG(4850): Revision: '8'
03-01 10:48:13.765: A/DEBUG(4850): ABI: 'arm64'
03-01 10:48:13.766: A/DEBUG(4850): pid: 4507, tid: 4652, name: DefaultFileSour  >>> com.shaka.guide <<<
03-01 10:48:13.766: A/DEBUG(4850): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-01 10:48:13.766: A/DEBUG(4850):     x0   0000000000000000  x1   000000000000122c  x2   0000000000000006  x3   0000000000000008
03-01 10:48:13.766: A/DEBUG(4850):     x4   ffffffffffffffff  x5   8000000000000000  x6   0000000000000080  x7   ff6b6b74651f7268
03-01 10:48:13.766: A/DEBUG(4850):     x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
03-01 10:48:13.767: A/DEBUG(4850):     x12  ffffffffffffffff  x13  0000000000000000  x14  0000000000000000  x15  001f02c85d64ef5e
03-01 10:48:13.768: A/DEBUG(4850):     x16  0000007ae96beee0  x17  0000007ae9668404  x18  00000000ffffffff  x19  0000007a9c4f84f8
03-01 10:48:13.769: A/DEBUG(4850):     x20  0000000000000006  x21  0000007a9c4f8450  x22  000000000000001c  x23  00000000ffffffc8
03-01 10:48:13.769: A/DEBUG(4850):     x24  0000007a9c4f76d0  x25  0000007a9c4f75a0  x26  0000007a9c4f75e0  x27  0000007a9c4f7da0
03-01 10:48:13.769: A/DEBUG(4850):     x28  0000000000000004  x29  0000007a9c4f74b0  x30  0000007ae9665898
03-01 10:48:13.769: A/DEBUG(4850):     sp   0000007a9c4f7490  pc   0000007ae966840c  pstate 0000000060000000
03-01 10:48:13.803: A/DEBUG(4850): backtrace:
03-01 10:48:13.803: A/DEBUG(4850):     #00 pc 000000000006c40c  /system/lib64/libc.so (tgkill+8)
03-01 10:48:13.803: A/DEBUG(4850):     #01 pc 0000000000069894  /system/lib64/libc.so (pthread_kill+64)
03-01 10:48:13.803: A/DEBUG(4850):     #02 pc 000000000002450c  /system/lib64/libc.so (raise+24)
03-01 10:48:13.803: A/DEBUG(4850):     #03 pc 000000000001c9ec  /system/lib64/libc.so (abort+52)
03-01 10:48:13.803: A/DEBUG(4850):     #04 pc 0000000000471794  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.803: A/DEBUG(4850):     #05 pc 00000000004718a4  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #06 pc 000000000046ef64  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #07 pc 000000000046e880  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #08 pc 000000000015ec18  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #09 pc 0000000000152550  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #10 pc 0000000000151df4  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #11 pc 0000000000153440  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #12 pc 0000000000159fa0  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #13 pc 0000000000146638  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #14 pc 0000000000147d20  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #15 pc 0000000000147ea8  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #16 pc 000000000015bba4  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #17 pc 0000000000337ce8  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #18 pc 00000000003382d0  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.804: A/DEBUG(4850):     #19 pc 0000000000140a10  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.805: A/DEBUG(4850):     #20 pc 00000000001408a0  /data/app/com.shaka.guide-1/lib/arm64/libmapbox-gl.so
03-01 10:48:13.805: A/DEBUG(4850):     #21 pc 000000000006909c  /system/lib64/libc.so (_ZL15__pthread_startPv+196)
03-01 10:48:13.805: A/DEBUG(4850):     #22 pc 000000000001ded4  /system/lib64/libc.so (__start_thread+16)
```

### Expected behavior

Catch the error and pass it to onError callback or shold be able to determine required maps size
in advance.

### Actual behavior

App crashes during the downloading if free space is ended.

**Comment by kkaefer** [comment] 2018-03-01 09:54
Thanks for using Mapbox and for reporting this crash! This is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/7164. Closing here since it's already tracked in that issue.

**Closed by kkaefer** 2018-03-01 09:54 UTC
