### ISSUE TITLE
Switching styles turns annotations invisible

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1488] opened 2015-05-09 00:45 UTC
Changing the style causes any annotations in view to become invisible. Any popover remains visible, and invisible annotations continue to respond to taps.

![pindrop](https://cloud.githubusercontent.com/assets/1231218/7552213/4831fb0a-f65d-11e4-9312-d618cb1bc83f.PNG)

**Comment by 1ec5** [comment] 2015-05-09 00:55
Zooming in and out causes the annotations to appear and disappear – with the old style's sprites.

@bsudekum, this is likely the issue you were seeing with your React Native project.

**Comment by incanus** [comment] 2015-05-09 01:12
This will go away when we lift annotation imagery of the sprite sheet. This might be an acceptable part of the b1 stopgap.

**Comment by incanus** [comment] 2015-06-15 21:24
I'm ok with this being a stopgap again in b2, meaning you need to set style and leave it before adding/managing annotations for now. b3's focus thus far is better annotations.

**Comment by ejdslayer** [comment] 2015-09-03 09:39
Hi, so is there a beta version available that will address this issue for now? I don't mind re-adding the annotations etc, I just need this ready for a project due to launch in 3 weeks. Thanks

**Comment by kristfal** [comment] 2015-09-17 07:37
Ref #2326, is there any known workarounds for this? 

This issue persists across app launches in ios-v2.1.2 (even closing the app from the task manager), making annotations unusable in any context where a style may be swapped. Let me know if you want any help debugging or testing.

**Comment by robipresotto** [comment] 2015-09-17 18:25
@incanus map caches the icon annotation anyway if we are setting it before setting the map style. Any suggestion?

**Comment by maciekish** [comment] 2015-09-28 14:31
cc @zakay

**Comment by maciekish** [comment] 2015-09-28 14:49
FWIW 3ec610c did not fix the issue.

**Comment by Zakay** [comment] 2015-10-01 09:20
+1 I'm really hoping this gets fixed asap, we are so close to launch our app with a reach of 1millions users, and this is a major blocking issue.

**Comment by ljbade** [comment] 2015-10-01 22:06
@1ec5 would this be a case of saving the markers at `setStyleURL` then loading them back after style loaded?

**Comment by 1ec5** [comment] 2015-10-01 22:19
@robipresotto, I think that might be #1628 complicating matters.

**Comment by 1ec5** [comment] 2015-10-01 22:21
@ljbade, not really; you might be able to fashion a workaround at the MGLMapView level by removing the annotations before setting the style and readding all the annotations after it’s done loading, but I think the issue is deeper than MGLMapView.

**Comment by jfirebaugh** [comment] 2015-10-01 22:26
To bring over knowledge from #2420: the bug here is with point annotations, which produce errors like "Can't find sprite named 'com.mapbox.sprites.51'" in the output. To support point annotations will require keeping a record of which sprite icons were added via `Map::setSprite` and then re-add them to the new style. Or, better, removing `Map::setSprite`, associating the icon directly with the annotation object, and re-adding it to the sprite after the style changes.

**Comment by ljbade** [comment] 2015-10-02 02:43
@jfirebaugh I vote associating it with annotation object, makes more sense. Like `setSpriteForAnnotation`

**Comment by incanus** [comment] 2015-11-13 18:47
@jfirebaugh Ok to pass this to @adam-mapbox? He's gonna dig a bit on possible solutions, and I think what you did in annotations recently lays the foundation / this doesn't intersect too much with the style API work?

**Comment by jfirebaugh** [comment] 2015-11-13 19:00
:+1: 

To expand on my previous comment: the issue is that sprite icons are owned by `Style` (via `SpriteStore`), so when you change the style, all annotation sprites added via `Map::setSprite` are gone.

Associating the icon directly with the annotation object seems like a decent solution (should be done by modifying `PointAnnotation` class, not by adding `setSpriteForAnnotation` though). However, this will require that `SpriteStore` deduplicates sprites based on their contents, so as not to blow up the store with multiple copies of the same sprite, when used by multiple annotations.

**Comment by ljbade** [comment] 2015-11-15 22:12
@jfirebaugh While someone is in here, fixing `removeSprite` will also be useful for when annotations are deleted. Currently if you add and delete enough unique sprite annotations, the sprite store will fill up.

Ref https://github.com/mapbox/mapbox-gl-native/issues/2560

**Comment by adam-mapbox** [comment] 2015-11-17 00:36
https://github.com/mapbox/mapbox-gl-native/pull/3049

**Comment by mb12** [comment] 2015-11-17 02:02
1.) SpriteAtlas is expensive (memory wise). Is it possible to delay creation of annotationSpriteAtlas until it is actually needed (first time a marker point is added to the map)?

2.) Also is it possible to expose and test a remove method in the SpriteAtlas/SpriteStore that can used to free up the memory allocated for a marker image when its no longer needed?

**Comment by adam-mapbox** [comment] 2015-11-17 21:19
#1 is complete

For #2: What is the right way to expose a method by which sprites can be removed?  Should there be a sister method to `-MGLAnnotationImage annotationImageWithImage:reuseIdentifier:` ? Maybe some kind of `deleteAnnotationImageWithReuseIdentifier:`?  There already is a way to remove sprites from a sprite store, I just have to expose it somehow.

**Comment by 1ec5** [comment] 2015-11-17 21:31
> What is the right way to expose a method by which sprites can be removed?

`-[MGLMapView didReceiveMemoryWarning]` would be a good place to perform this kind of work.

**Comment by incanus** [comment] 2015-11-17 23:08
> `-[MGLMapView didReceiveMemoryWarning]` would be a good place to perform this kind of work.

Not sure about that; if memory gets low, we could legitimately jettison cached tiles and the like, but getting rid of sprites would cause the map to not render annotations?

**Comment by incanus** [comment] 2015-11-17 23:09
Also, let's keep the discussion about @adam-mapbox's code in https://github.com/mapbox/mapbox-gl-native/pull/3049 over in that ticket, instead of here in the _problem_ side of things.

**Comment by adam-mapbox** [comment] 2015-11-17 23:10
I think @1ec5 's idea was that we only jettison those that aren't being used anymore?  But that's actually pretty tough to do if we're not informed of them.  It might also break the contract of the API.

**Closed** 2015-12-01 17:58 UTC
Labels: bug, P0

**Comment by incanus** [comment] 2015-12-01 18:10
:tada: 

This should land in iOS 3.1.0 (next feature release) so no need to cherry-pick the fix anywhere just yet, as that will be based off of `master`.

**Comment by kdgwill** [comment] 2016-02-09 07:01
Has their been any update on this issue?
