### ISSUE TITLE
getStyle().addImage() can halt the map from rendering

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10526] opened 2017-11-22 09:02 UTC
Capturing from https://github.com/mapbox/mapbox-gl-native/issues/10517 that getStyle().addImage() can result in momentary halting the map (while looping and adding 500 images). While it isn't noticeable during initialisation: 

![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/2151639/33076431-0152c0d4-cecd-11e7-92f6-b96ad68b8733.gif)

It's noticeable when delaying the addImage invocation:

![ezgif com-video-to-gif 8](https://user-images.githubusercontent.com/2151639/33077069-03d3806c-cecf-11e7-9c4e-2e1d61cc9220.gif)

**Comment by nikiizvorski** [comment] 2017-11-22 09:06
For me both addImages() and addImage() does that in a slightly difference matter. One is a bit bette than the other one which we already know why.

**Comment by nikiizvorski** [comment] 2017-11-22 09:17
@tobrun Hey Tobrun i am not trying to affect and i am trying to be constructive here. What i was speaking is that your solution doesn't solve the problem. We already know that thats possible i am doing it currently. And with yours i will give you the example you have you have loaded 500 but small bitmaps less than 1kb which are not coming from objects and they are created and staying in ObjectPool of the Bitmap. And after they are being reused so thats why you don't have the existing problem. Please get in depth with this one to create the same problem. But we try to rethink our strategy since you shouldn't load more than a couple projects with Lazy Load. I already did all whats possible with the API that you have i just want to check if other people did something that i didn't currently see.

**Comment by jfirebaugh** [comment] 2017-12-02 01:09
Duplicate of #10249?

**Closed** 2017-12-02 07:24 UTC
Labels: Android, Core
