### ISSUE TITLE
Move/Enlarge touch target Marker

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2454] opened 2015-09-29 15:31 UTC
While testing I noticed that the touch target of the marker is lower than the actual sprite. This resulted in not handled click events. Touch target of marker should be moved higher or/and enlarged.

**Comment by ljbade** [comment] 2015-09-30 04:31
@incanus are you scaling the target hit box with the DPI?

**Comment by tobrun** [comment] 2015-09-30 12:31
Missing the touch target occurs more on Emerald styled map than MapboxStreets 
 - Marker is larger on Emerald

**Comment by ljbade** [comment] 2015-09-30 22:25
Ah yeah.

@tobrun You think this is a quick fix?

**Comment by incanus** [comment] 2015-10-01 17:19
Dupe of #1504

**Closed by incanus** 2015-10-01 17:19 UTC
Labels: Android, bug
