### ISSUE TITLE
All annotations blink when changing position one of them

### ISSUE THREAD

**Issue by Gerz-inc** [mapbox/mapbox-gl-native#7918] opened 2017-02-01 12:58 UTC
**Platform:** iOS
**Mapbox SDK version:** 3.4.1

All annotations blink when changing position one of them. Used mapView:imageForAnnotation:. And  same story if I combine imageForAnnotation & viewForAnnotation, and when I moving annotations with view - imageAnnotations are blink

![-1](https://cloud.githubusercontent.com/assets/12774979/22507522/01b6d884-e897-11e6-8cef-416ad35e61b6.gif)

**Comment by 1ec5** [comment] 2017-02-01 15:37
Possibly a duplicate of #7615, fixed in #7616 for v3.5.0. Given all the refactoring that has occurred between v3.4.0 and v3.5.0, I don’t think it would be straightforward to backport the change to the release-ios-v3.4.0 branch for v3.4.2.

**Comment by jfirebaugh** [comment] 2017-03-06 00:27
Closing with the assumption that this was fixed per above. If this is reproducible in the v3.5.0 betas, please reopen the issue.

**Closed by jfirebaugh** 2017-03-06 00:27 UTC
Labels: iOS
