### ISSUE TITLE
MarkerViews onClick event doesn’t work as intended

### ISSUE THREAD

**Issue by chronos83** [mapbox/mapbox-gl-native#7071] opened 2016-11-15 15:59 UTC
A marker filter and search under the touch is triggered in MapView.onSingleTapConfirmed(MotionEvent motionEvent) that calls on AnnotationManager.getMarkersInRect(RectF rectangle). The rectangle parameters are based on size and position constants, independantely of MarkerViews size and anchor.

**Platform: Android**
**Mapbox SDK version: SNAPSHOT**

### Steps to trigger behavior

 1. Add big size (100dp) marker views
 2. mMapboxMap.getMarkerViewManager().setOnMarkerViewClickListener to log onMarkerClick 
 3. Touch the marker on the bottom right corner.

### Expected behavior
Receive onMarkerClick callback
### Actual behavior
No onMarkerClick callback

**Comment by cammace** [comment] 2016-11-15 16:09
Thanks for reporting, this is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/6761.

**Closed by cammace** 2016-11-15 16:09 UTC
