### ISSUE TITLE
flaky Android build

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3539] opened 2016-01-13 22:02 UTC
The Android build will sometimes fail with the following output:

```
make[2]: *** No rule to make target `Release/obj.target', needed by `/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/obj.target'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CXX(target) Release/obj.target/example-custom-layer-lib/platform/android/src/example_custom_layer.o
../../platform/android/src/http_request_android.cpp:191:59: warning: unused parameter 'message' [-Wunused-parameter]
void HTTPAndroidRequest::onResponse(int code, std::string message, std::string etag, std::string modified, std::string cacheControl, std::string expires, std::string body) {
                                                          ^
1 warning generated.
make[2]: Leaving directory `/bitrise/src/build/android-arm-v7'
make[1]: Leaving directory `/bitrise/src'
make[1]: *** [Makefile/androidapp] Error 2
make: *** [android-lib] Error 2
==> Script finished with exit code: 2
ERRO[21:59:51] Step (Build Android SDK For arm) failed, error: (exit status 2) 
```

I don't think the "warning: unused parameter" is relevant (although we should fix that). I have no idea what "No rule to make target `Release/obj.target'" means, but it seems to be the cause. There's nothing before that.

**Comment by jfirebaugh** [comment] 2016-01-13 22:03
Example: https://www.bitrise.io/build/07ceba5e8e8e66f3

**Comment by tobrun** [comment] 2016-01-14 10:09
@jfirebaugh 
I was able to reproduce this locally by building with same command as CI:
 > make android -j4

Other make commands seem to be unaffected

#### Current workaround:
I have hotfixed this for now by [silencing the message param](http://stackoverflow.com/questions/1486904/how-do-i-best-silence-a-warning-about-unused-variables):

```cpp
    // the message param is unused, this generates a warning at build time
    // this was breaking builds for `make android -j4`
    (void)message;
```
This is not a correct solution but will resolve the flakiness for now. 
l will leave this issue open so we can address the real issue later on.

**Comment by tobrun** [comment] 2016-01-14 13:34
Reopening because work around is not a valid solution.

**Comment by tobrun** [comment] 2016-01-14 13:36
I now have found that there is already an issue for that issue. Linking that one and closing this one. #3438

**Comment by jfirebaugh** [comment] 2016-01-14 17:53
As hinted in the description, I don't think the warning (#3438) is the cause of this. I assume that the warning appears 100% of the time, and the build does not fail 100% of the time.

**Comment by tobrun** [comment] 2016-01-15 07:12
@jfirebaugh:
I went over the builds from last night, the above error did not fail any builds anymore:

The reasons why a few builds failed:
 - git clone failed
 - forgot to commit file, file not found :trollface: 
 - out of date branch without build fixes from last days

**Comment by tobrun** [comment] 2016-01-15 12:21
@jfirebaugh 
I believe you are right, this fail of the build is unrelated to the contents of the PR:

> make[2]: *** No rule to make target `Release/obj.target', needed by `/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/obj.target'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CXX(target) Release/obj.target/example-custom-layer-lib/platform/android/src/example_custom_layer.o
make[2]: Leaving directory `/bitrise/src/build/android-arm-v7'
make[1]: Leaving directory `/bitrise/src'
make[1]: *** [Makefile/androidapp] Error 2
make: *** [android-lib] Error 2

**Comment by tobrun** [comment] 2016-01-18 09:39
Another example of flaky failed build is:

> make[2]: *** No rule to make target `Release/obj.target', needed by `/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/obj.target'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CXX(target) Release/obj.target/example-custom-layer-lib/platform/android/src/example_custom_layer.o
make[2]: Leaving directory `/bitrise/src/build/android-arm-v7'
make[1]: Leaving directory `/bitrise/src'
make[1]: *** [Makefile/androidapp] Error 2
make: *** [android-lib] Error 2

after researching this a bit, I have learned that `Error 2` indicates:
> tells me that there was an error of some sort in the submake.

We should add logging or some sort to identify where `Error 1` is thrown.

**Comment by jfirebaugh** [comment] 2016-03-23 17:33
This continues to be an issue.

**Closed** 2016-04-08 01:15 UTC
Labels: Android, build
