### ISSUE TITLE
Use TextureView

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2244] opened 2015-09-03 05:41 UTC
Now that we target API level 15 and above we should switch to [`TextureView`](http://developer.android.com/reference/android/view/TextureView.html)

The advantage is that we can treat a `MapView` the same as any other `View`. This will allow advanced layouts and may avoid bugs such as https://github.com/mapbox/mapbox-gl-native/issues/2018 and https://github.com/mapbox/mapbox-gl-native/issues/1894

@bleege Do we want to do this in 0.1.0 or 0.2.0?

**Comment by ljbade** [comment] 2015-09-03 06:13
Started work on this.

**Comment by tobrunvannuland** [comment] 2015-09-03 13:01
Nice, looking forward seeing this working!

Hopefully this will not be an issue:
> The main strike against TextureView is the performance of the composition step. With SurfaceView,  the content is written to a separate layer that SurfaceFlinger composites, ideally with an overlay. With TextureView, the View composition is always performed with GLES, and updates to its contents may cause other View elements to redraw as well (e.g. if they're positioned on top of the TextureView)

**Comment by bleege** [comment] 2015-09-03 13:40
> Do we want to do this in 0.1.0 or 0.2.0?

`0.2.0`.  @ljbade This sounds like a good thing, but it's too late for `0.1.0`.

**Comment by ljbade** [comment] 2015-09-03 23:44
@bleege Sure we might have to move those bugs to `0.2.0` then.

**Comment by bleege** [comment] 2015-09-08 15:41
Moving this to `0.1.0` as it solves Translucent Status bar issue in #1894 .  See https://github.com/mapbox/mapbox-gl-native/issues/1894#issuecomment-138603599 for more details.

Is there anything more to be done @ljbade or can we merge this one in as is?

**Comment by mb12** [comment] 2015-09-08 15:47
@ tobrun Were you able to reproduce the original issue without these changes?  My understanding is that this is a speculative fix for an issue which is not reproducible with latest master.

**Comment by tobrun** [comment] 2015-09-08 16:43
@mb12 will do a small test before it gets merged

**Comment by incanus** [comment] 2015-09-08 17:26
Per chat with @bleege, we are going to move this back to `0.2.0` since it's a bit of a refactor and is triggered only in an edge case. We can quickly wrap it into the next release cycle and go from there.

**Comment by tobrun** [comment] 2015-09-09 13:09
@mb12
Problem still exists on master so TextureView is a valid fix.

Nice job @ljbade :+1:

![device-2015-09-09-150700](https://cloud.githubusercontent.com/assets/2151639/9762543/96558b96-5704-11e5-91c0-1805955265c4.png)

**Comment by mb12** [comment] 2015-09-09 17:18
Great fix. This was a tough one.

**Comment by bleege** [comment] 2015-09-09 19:50
Thanks for the feedback and tire kicking @tobrun @mb12 and @ljbade for making this happen.  @incanus and I just discussed this and decided that we will make the time to include this now.  Hopefully this will also solve #1894 too.

**Closed** 2015-09-09 20:15 UTC
Labels: Android, refactor

**Comment by bleege** [comment] 2015-09-09 21:50
Merged.
