### ISSUE TITLE
[android] Zoom gesture not working

### ISSUE THREAD

**Issue by joaopedro1520** [mapbox/mapbox-gl-native#10173] opened 2017-10-10 15:39 UTC
I'm testing the map in several devices, and when using a galaxy s2 with api15 the zoom gesture doesnt work on map version 5.1.4 but it works on 5.1.3

**Platform:** Android
**Mapbox SDK version:** 5.1.4

**Comment by tobrun** [comment] 2017-10-10 19:06
Thank you for the report @joaopedro1520, closing as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10101. 
We are working on fixing this as part of a 5.1.5 release.

**Closed by tobrun** 2017-10-10 19:06 UTC
Labels: Android
