### ISSUE TITLE
Android mountain_peak_label elevation format incorrect

### ISSUE THREAD

**Issue by clydebarrow** [mapbox/mapbox-gl-native#5026] opened 2016-05-13 11:01 UTC
Platform: Android
Mapbox SDK Version: 4.10.-SNAPSHOT

Adding a layer in Mapbox Studio using source data from Mapbox Streets V7, mountain_peak_label.
The style text field is {name} {elevation_ft} and in Mapbox Studio it renders as expected:

![screen shot 2016-05-13 at 8 58 54 pm](https://cloud.githubusercontent.com/assets/2366188/15246056/9270c386-194d-11e6-8982-e0f216d82957.png)

However when viewed on Android the elevation includes numerous 0s after a decimal point:

![screen shot 2016-05-13 at 8 48 57 pm](https://cloud.githubusercontent.com/assets/2366188/15246079/ab2eda52-194d-11e6-8a2a-d2928ceee0b9.png)

It would appear the format being used on Android is not correct.

**Comment by tobrun** [comment] 2016-05-13 11:36
This is going to be resolved when https://github.com/mapbox/mapbox-gl-native/pull/4965 lands

cc @friedbunny

**Comment by 1ec5** [comment] 2016-05-13 14:59
Duplicate of #998.

**Closed by 1ec5** 2016-05-13 14:59 UTC
Labels: Android
