### ISSUE TITLE
Android Mapbox bearing issue in Landscape

### ISSUE THREAD

**Issue by mmaran** [mapbox/mapbox-gl-native#8238] opened 2017-03-01 13:40 UTC
**Platform: Android Lollipop API 23** (Mobile - ASUS Max)
**Mapbox SDK version:  4.2.2**

### Steps to trigger behavior
 1. My application is set only to Landscape mode
 2. Bearing tracking is set to Compass

![screenshot_20170301-184110](https://cloud.githubusercontent.com/assets/26115171/23461199/f86b82a6-feae-11e6-8d87-4bf1f32a03cb.jpg)

I have custom compass image to show the actual North from compass

                map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.COMPASS);
                map.getTrackingSettings().setDismissBearingTrackingOnGesture(false);
                map.getMyLocationViewSettings().setPadding(0, 0, 0, 0);
                map.getMyLocationViewSettings().setForegroundTintColor(Color.parseColor("#FF4081"));

### Expected behavior
Bearing should point correct heading even in landscape mode

### Actual behavior
Bearing pointing to West when I actually point North

I can see the same issue in the sample application(https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationTrackingActivity.java) The bearing is fine when in potrait but not in landscape.

Is there a way to set custom heading ?? or Am I missing anything ??

Please help out.

**Comment by tobrun** [comment] 2017-03-02 15:16
@mmaran thank you for reaching out and reporting this.
would you be able to retest with the `5.0.0.beta.2`?
I'm unable to reproduce this issue as shown in the OP With latest master:

![device-2017-03-02-101330](https://cloud.githubusercontent.com/assets/2151639/23513186/2a85260c-ff31-11e6-9538-02b64285531e.png)

![device-2017-03-02-101351](https://cloud.githubusercontent.com/assets/2151639/23513192/2cdf14bc-ff31-11e6-9594-59b07c03db28.png)

**Comment by mmaran** [comment] 2017-03-02 17:14
Hey @tobrun 

I tried rebuilding my app with the beta version, getting a lot of errors. Some of the Mapbox SDK classes seems to be missing.

Is there a page that lists the enhancements/changes in version 5, so that I can update my code according to that ?

**Comment by tobrun** [comment] 2017-03-02 17:27
@mmaran we are working on a documenting this in https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update.

**Comment by tobrun** [comment] 2017-03-03 16:48
Feel free to let us know if you are able to reproduce with newest version. 
Closing this for now as not reproducible. Thank you again for reaching out!

**Closed by tobrun** 2017-03-03 16:48 UTC
Labels: Android
