### ISSUE TITLE
Satellite style flickers with black tiles on emulator

### ISSUE THREAD

**Issue by invised** [mapbox/mapbox-gl-native#14604] opened 2019-05-07 15:47 UTC
This issue is there for quite a long time, but nobody seems to experience it, or trying to fix. This problem makes maps on emulator unusable most of the times. Also often whole computer lags while maps are shown in the emulator.

### Steps to reproduce

 1. Launch android emulator (Mac OS affected at least)
 2. Install and launch Mapbox Demo app
 3. Go to "Styles - Default styles", choose "Satellite" layer
 4. Move the map, zoom in and out

### Expected behavior
The map should properly display raster satellite tiles depending on the zoom level

### Actual behavior
Raster satellite tiles randomly flicker black or shown greyscaled
[Demonstration video](https://dump.video/C2ffIR)

### Configuration

**MacOS version:** 10.13.6 and older (seems independent of version)
**Android versions:** 28, 23, Q or older (seems independent of version)
**Device models:** Emulator
**Mapbox SDK versions:** 7.3.2, 7.0.1 and older

**Comment by tobrun** [comment] 2019-05-09 06:29
@invised some users that had similar issues with black flickering of labels fixed it with the following configuration of their emulator:

```
OpenGL ES renderer: SwiftShader
OpenGL ES API level: Render maximum (up to OpenGL ES 3.1)

```

**Comment by LukasPaczos** [comment] 2019-05-09 11:07
Let us know if the settings work for you @invised! Meanwhile closing as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10829.

**Closed by LukasPaczos** 2019-05-09 11:07 UTC
Labels: Android

**Comment by invised** [comment] 2019-05-10 15:26
> @invised some users that had similar issues with black flickering of labels fixed it with the following configuration of their emulator:
> 
> ```
> OpenGL ES renderer: SwiftShader
> OpenGL ES API level: Render maximum (up to OpenGL ES 3.1)
> ```

Unfortunately this configuration makes the emulator so slow, that it becomes totally unusable.
