### ISSUE TITLE
Troubles with rendering on Meizu

### ISSUE THREAD

**Issue by SanQri** [mapbox/mapbox-gl-native#8470] opened 2017-03-20 14:09 UTC
I have some troubles with rendering on Meizu since 5.0.0 beta 3. 5.0.0 also doesn't work properly. However, 5.0.0 beta 1 worked fine. 

I launched Mapbox dev preview from Play Market and made some builds with using of new Mapbox SDK on Meizu U20 (Android 6.0) and Meizu M3 Note (Android 5.1). All the road are white, some of the labels too. Then I launched same apps on Xiaomi (Android 6.0) and Samsung (Android 5.1) and it worked as usual.

**Platform:** 6.0 and 5.1

**Mapbox SDK version:** 5.0.0 and 5.0.0 beta 3

![s70320-15432581](https://cloud.githubusercontent.com/assets/15667737/24102509/e61495d6-0d84-11e7-97a7-95c39b8bcf92.jpg)

**Comment by ragaisis** [comment] 2017-03-21 08:03
I can add that I have custom map style rendering problems too.

![screenshot_20170309-154317 copy](https://cloud.githubusercontent.com/assets/2177892/24137628/5c97c690-0e1d-11e7-857a-7aa62e6edca6.png)
 

After trying to investigate my guess is that probably Mali GPU is causing those issues, because on my Galaxy S5 maps are rendering good (GPU Adreno 330), but it fails on various other test devices:

- Galaxy A5 (2016) GPU Adreno 405  **Mali-T720MP2**
- Huawei P9    GPU **Mali-T880 MP4**
- Samsung tab A    GPU	Adreno 306 **Mali-400MP2**
- Acer iconia one 7 GPU PowerVR SGX544MP2

**Comment by tobrun** [comment] 2017-03-22 06:33
Thank you for the report and investigating in more detail. Linking #8385 as possible duplicate.

**Comment by jfirebaugh** [comment] 2017-03-22 15:57
Closing as duplicate of #8385.

**Closed by jfirebaugh** 2017-03-22 15:57 UTC
Labels: Android
