### ISSUE TITLE
Tilt map 90º degrees

### ISSUE THREAD

**Issue by SudarshanMahesh** [mapbox/mapbox-gl-native#11670] opened 2018-04-12 11:03 UTC
The availability to tilt the map 90º. Useful form my live flight tracking app! This is what I mean:
https://sspinnovations.com/wp-content/uploads/assets/assets/Keystone_Resized.png

**Comment by jfirebaugh** [comment] 2018-04-12 15:51
Duplicate of #6908.

**Closed by jfirebaugh** 2018-04-12 15:51 UTC
