### ISSUE TITLE
Got "Unfortunately, App has stopped" dialog without App crashes with Mapbox version 5.0.2

### ISSUE THREAD

**Issue by 13kz** [mapbox/mapbox-gl-native#8848] opened 2017-04-28 14:39 UTC
**Platform:Android**
**Mapbox SDK version:5.0.2**

I'm working with Mapbox version 5.0.2 but I got a weird dialog with the message "Unfortunately, App has stopped" without the application crashes. 
And I don't have no specific message in Android Monitor that explain this one.

I already add mapboxMap.setMyLocationEnabled(true) in onMapReady to show user location drawable on the map.

```
@Override
    public void onMapReady(MapboxMap mapboxMap) {
        /** set Max Zoom Preference**/
        /** set Min Zoom Preference**/
        mapboxMap.setMyLocationEnabled(true);
    }

```

**Comment by tobrun** [comment] 2017-05-02 08:03
@13kz did you request any runtime location permissions? How do you mean no specififc messages in your android monitor? If the app crashed there should always be stacktrace. Sometimes it's hidden under your logcat filters. Without having any stacktrace this issue isn't actionable for us. The test activity we the same code works as expected on master.

**Comment by neonwarge04** [comment] 2017-05-05 05:28
@13kz, I can confirm your app will crash if you don't have the permission set properly. You can look at the demo sample for further reference.

**Comment by 13kz** [comment] 2017-05-05 15:44
@tobrun, u're right. The stack trace is visible when I change Debuggable process in Android Monitor. This issue is already created [**here (lost issue)**](https://github.com/mapzen/lost/issues/173). 
I'll use Release Android v5.1.0-beta1 version to check.

**Comment by tobrun** [comment] 2017-05-09 05:51
@13kz, beta1 will not resolve your issue yet. The PR in #8872 will fix this. Feel free to retest when that lands with a SNAPSHOT or when beta.2 is released (eta somewhere this week). Closing this as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/8639

**Closed by tobrun** 2017-05-09 05:51 UTC
Labels: Android, crash, needs information
