### ISSUE TITLE
Crash if marker icon width and height is to small About Android SDK

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4088] opened 2016-02-24 07:11 UTC
I have two images, like below:
1. ic_launcher.png, both size of height and widht are 96
![](https://github.com/Trinea/trinea-download/blob/master/temp/ic_launcher.png?raw=true)  
2. ic_launcher_small.png, both size of height and widht are 20
![](https://github.com/Trinea/trinea-download/blob/master/temp/ic_launcher_small.png?raw=true)  
Copy those two images to resource of Android.  
```
mv.addMarker(new MarkerOptions().title("Edinburgh").snippet("Scotland").icon(IconFactory.getInstance(context).fromResource(R.drawable.ic_launcher_small)).position(new LatLng(55.94629, -3.20777)))
```
use ic_launcher_small.png as Marker icon will cause app crash.  I have debuged to
```
NativeMapView.public void addAnnotationIcon(String symbol, int width, int height, float scale, byte[] pixels)
```
method, it's value is like
![](https://github.com/Trinea/trinea-download/blob/master/temp/map_box_annotation_icon.png?raw=true)
width is 6, height is 6, scale is 3.0

**Comment by tobrun** [comment] 2016-03-01 12:35
@ansis any idea why this is crashing?

**Comment by tobrun** [comment] 2016-03-08 14:43
I have added  the following icon to the testapp:
![ic_small](https://cloud.githubusercontent.com/assets/2151639/13604739/2b6dadbc-e512-11e5-9006-7156e0621e57.png)

Which has the same dimensions as mentioned above in the issue.

**Comment by tobrun** [comment] 2016-03-08 14:50
Here is a screenshot of the icon in `xxxhpdi`:

![device-2016-03-08-094758](https://cloud.githubusercontent.com/assets/2151639/13604876/ee311b36-e512-11e5-8ea5-b63bbec35e12.png)

**Comment by tobrun** [comment] 2016-03-08 14:51
I tested with an icon of the dimensions of 1px, still not able to reproduce, considering this was an issue with older SDK versions and no longer an issue with the `4.0.0` release. Closing.

**Closed by tobrun** 2016-03-08 14:51 UTC
Labels: Android, crash
