### ISSUE TITLE
Camera issues on armeabi only binaries

### ISSUE THREAD

**Issue by invised** [mapbox/mapbox-gl-native#11517] opened 2018-03-25 07:34 UTC
**Platform:** Android
**Mapbox SDK version:** 5.5.0

### Steps to trigger behavior

 1. Use only _armeabi_ binaries on _armeabi-v7a_ or _arm64-v8a_ device.
 2. Animate camera to some bounds.

### Expected behavior
No camera issues: smooth camera movement to the destination bounds
### Actual behavior
Camera freezes and jumps to random locations while moving to the destination bounds, as shown below
https://gph.is/2pELKzB

**Comment by tobrun** [comment] 2018-03-25 19:27
Thank you for reaching out and reporting this issue. Was able to reproduce though with the upcoming NDK 17 release (currently in beta) Google has removed support for armeabi and mips: 
https://github.com/android-ndk/ndk/wiki/Changelog-r17-beta1

> Support for ARMv5 (armeabi), MIPS, and MIPS64 has been removed. Attempting to build any of these ABIs will result in an error.

We are working to remove this from our codebase in https://github.com/mapbox/mapbox-gl-native/pull/11458. Since we are removing support, going to close this as non-actionable.

**Closed by tobrun** 2018-03-25 19:27 UTC
Labels: Android
