### ISSUE TITLE
Warning in Android logcat: Attempt to remove non-JNI local reference, dumping thread

### ISSUE THREAD

**Issue by guruduttstay** [mapbox/mapbox-gl-native#7325] opened 2016-12-07 12:47 UTC
**Platform: Android**
**Mapbox SDK version: mapbox-android-sdk:4.2.0-beta.5 **

### Steps to trigger behavior

While building my app with MapBoxMap LogCat continuously shows this warning several times 

W/art: Attempt to remove non-JNI local reference, dumping thread

Is this dangerous or can we ignore it ?

**Comment by tobrun** [comment] 2016-12-07 14:31
@guruduttstay 
Thanks for reaching out and reporting your issue. Could you give us a bit more information on the type of device you are using? I'm not seeing those warnings locally here.

**Comment by guruduttstay** [comment] 2016-12-08 07:45
We use several phones (for e.v. 4S , 6S , Nexus 4, Nexus 5, Nexus 7 etc) and always we see it :(

**Comment by jfirebaugh** [comment] 2017-01-04 00:06
Can you post the full log from when this occurs?

**Comment by guruduttstay** [comment] 2017-01-04 08:36
As soon MabBox starts logs looks like .... continuously 

```
01-04 09:33:01.560 32246-32396/com.stay I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-04 09:33:01.560 32246-32396/com.stay I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-04 09:33:01.560 3036-3825/? D/EnterpriseController: netId is 0
01-04 09:33:01.560 3036-3825/? D/Netd: getNetworkForDns: using netid 559 for uid 10333
01-04 09:33:01.570 3079-3079/? D/gpsd: CALL_SENTRY(main()): GlEngine::OnStart took 250 ms (from 419368000 to 419368250) (logOverhead=0,0,0,0,0,0), start: 00:09:33.001
01-04 09:33:01.610 3079-3079/? D/gpsd: CALL_SENTRY(main()): marshal_gps_start took 295 ms (from 419367986 to 419368281) (logOverhead=0,0,0,0,0,0), start: 00:09:33.001
01-04 09:33:01.610 3079-3079/? D/gpsd: CALL_SENTRY(main()): ProcessEvent took 295 ms (from 419367986 to 419368281) (logOverhead=0,0,0,0,0,0), start: 00:09:33.001
01-04 09:33:01.610 3429-4335/? D/libgps: OnGpsExtensionMessage: message_id(11), data(0x7f95883e44), size(4)
01-04 09:33:01.610 3429-4335/? D/libgps: [OnGpsExtensionMessage] Received: MSG_SET_LOG_LEVEL(2)
01-04 09:33:01.610 3429-4335/? D/libgps: OnGpsExtensionMessage: message_id(6), data(0x0), size(0)
01-04 09:33:01.610 32246-32729/com.stay D/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request with response code = 304: Not Modified
01-04 09:33:01.620 3429-4335/? D/libgps: OnGpsExtensionMessage: message_id(11), data(0x7f95883e44), size(4)
01-04 09:33:01.620 3429-4335/? D/libgps: [OnGpsExtensionMessage] Received: MSG_SET_LOG_LEVEL(2)
01-04 09:33:01.620 3429-4335/? D/libgps: OnGpsExtensionMessage: message_id(6), data(0x0), size(0)
01-04 09:33:01.630 3036-3825/? D/EnterpriseController: netId is 0
01-04 09:33:01.630 3036-3825/? D/Netd: getNetworkForDns: using netid 559 for uid 1021
01-04 09:33:01.640 32246-32722/com.stay V/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
01-04 09:33:01.660 3429-3958/? V/NetworkStats: performPollLocked(flags=0x1)
01-04 09:33:01.660 3429-3958/? D/NtpTrustedTime: currentTimeMillis() cache hit
01-04 09:33:01.680 32246-32730/com.stay D/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request with response code = 304: Not Modified
01-04 09:33:01.680 32246-32731/com.stay V/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
01-04 09:33:01.750 32246-32740/com.stay V/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
01-04 09:33:01.800 32246-32396/com.stay I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-04 09:33:01.800 32246-32396/com.stay I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-04 09:33:01.800 3429-4335/? D/libgps: OnGpsExtensionMessage: message_id(4), data(0x0), size(0)
01-04 09:33:01.800 3429-4335/? D/libgps: proxy__agps_ril_request_refloc_cb: refLocationSaved(0), time1(145201734), time2(144333709)
01-04 09:33:01.810 32246-32731/com.stay V/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).
01-04 09:33:01.820 3429-3958/? V/NetworkStats: performPollLocked() took 154ms
01-04 09:33:01.820 3429-3958/? D/NtpTrustedTime: currentTimeMillis() cache hit
01-04 09:33:01.820 3429-3960/? D/NtpTrustedTime: currentTimeMillis() cache hit
01-04 09:33:01.830 3429-4335/? D/libgps: proxy__agps_ril_set_ref_location: agps_reflocation->type(4), refLocationInfo.refLocationSaved(0)
01-04 09:33:01.830 3429-4335/? D/libgps: proxy__agps_ril_set_ref_location: type(4), mcc(242), mnc(1), cid(18140933), psc(281), lac(30901) 
01-04 09:33:01.830 3429-4335/? I/libgps: OnGpsExtensionMessage: MSG_REQUEST_LOCATION_ID
01-04 09:33:01.840 3429-3960/? D/NtpTrustedTime: currentTimeMillis() cache hit
01-04 09:33:01.850 32246-32396/com.stay I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-04 09:33:01.850 32246-32396/com.stay I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-04 09:33:01.920 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.920 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.920 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.920 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.920 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.920 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.920 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.920 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.930 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.930 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.930 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.930 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.930 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.930 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.960 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.960 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.960 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.960 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.960 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.960 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.970 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.970 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.970 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.970 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.970 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.970 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.970 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.970 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.970 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.970 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.970 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.970 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.980 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.990 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.990 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.990 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.990 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.990 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.990 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.990 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.990 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.990 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:01.990 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.990 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:01.990 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:02.000 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.000 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.000 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:02.000 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.000 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.000 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:02.000 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.000 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.000 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:02.000 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.000 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.000 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:02.010 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.010 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.010 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:02.010 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.010 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.010 32246-32246/com.stay D/mbgl: {com.stay}[JNI]: No source found
01-04 09:33:02.010 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.010 32246-32246/com.stay W/art: Attempt to remove non-JNI local reference, dumping thread
01-04 09:33:02.170 3079-3079/? D/wrapperGPS: wrapperisConnected_RILD
01-04 09:33:02.180 3079-3079/? D/wrapperGPS: wrapperInvokeOemRequestHookRaw
01-04 09:33:02.180 3079-3079/? D/wrapperGPS: SendOemRequestGpsFreqAiding, len(5), enable(1)
01-04 09:33:02.180 3079-3079/? D/wrapperGPS: wrapperSendInvokeOemRequestHookRaw, totalLen 13, ipcLen 8
01-04 09:33:02.180 3079-4350/? D/wrapperGPS: onRawReqComplete, 
01-04 09:33:02.190 3429-4335/? D/libgps: OnGpsExtensionMessage: message_id(1), data(0x7f95883e44), size(2432)
01-04 09:33:02.190 3429-4335/? D/libgps: GpsiHook: API: gpsSvStatusCb(GpsiHookStateGps: e,c,g)
01-04 09:33:02.190 3429-4335/? D/libgps: proxy__gps_sv_status_cb : called
01-04 09:33:02.190 3429-3522/? I/PassiveLocTracker: GPS Satllite Status
01-04 09:33:02.190 32246-32396/com.stay I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-04 09:33:02.190 32246-32396/com.stay I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-04 09:33:02.210 3079-4350/? D/wrapperGPS: onUnsol: sub_id(01)
01-04 09:33:02.210 3079-4350/? D/wrapperGPS: onUnsol: Undefined IPC sub id: 01
01-04 09:33:02.220 3079-4350/? D/wrapperGPS: onUnsol: sub_id(28)
01-04 09:33:02.220 3079-4350/? D/wrapperGPS: oem_unsol_gps_frequency_aiding, lock_status = 1
01-04 09:33:02.220 3079-4350/? D/wrapperGPS: GPS_onUnsolicitedResponse, sub_id(37)

```

**Comment by guruduttstay** [comment] 2017-01-10 09:14
@jfirebaugh 
Here are longer log [click to download](https://www.dropbox.com/s/10niie1iakgubq4/log.txt?dl=0) :)

Let me know if you need more info to reproduce it there, I can try my best.

**Comment by johanlunds** [comment] 2017-03-09 19:35
We also have this issue.

Mapbox Android SDK version: 5.0.0-beta.1

We use a `ValueAnimator` to continously update `iconImage` in a `SymbolLayer` to get a marker animation effect.

I re-created the issue in a new, empty Android Studio project: [MapboxIssue.zip](https://github.com/mapbox/mapbox-gl-native/files/832050/MapboxIssue.zip)

The zip also contains a compiled `app-debug.apk` and 3 commits in a `.git` repo.

It continuously logs:

`03-09 19:31:05.172 12460-12460/com.example.johan_lunds.mapboxissue W/art: Attempt to remove non-JNI local reference, dumping thread`

The relevant code is in `MainActivity`, [which I uploaded as a Gist](https://gist.github.com/johanlunds/a5acae6b44596fd91be3080c013cf280). Specifically the following code is what triggers the problem, the line with `mWaterPulseLayer.setProperties(iconImage(imageName))`:

```java
private void createWaterPulseAnimator() {
    ValueAnimator animator = new ValueAnimator();
    animator.setDuration(1500);
    animator.setStartDelay(0);
    animator.setIntValues(0, PULSE_DRAWABLES.length);
    animator.setRepeatCount(ValueAnimator.INFINITE);
    animator.setInterpolator(new LinearInterpolator());
    animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
        private int previousValue = -1;

        @Override
        public void onAnimationUpdate(ValueAnimator animator) {
            int i = (int) animator.getAnimatedValue();

            if (previousValue != i) {
                String imageName = String.format(Locale.US, "pulse-frame-%d", i);
                mWaterPulseLayer.setProperties(iconImage(imageName));
            }

            previousValue = i;
        }
    });

    animator.start();
}
```

Questions:

1. What does this error mean?
2. How serious is it?
3. Are you able to find the cause using the submitted info?

**Comment by johanlunds** [comment] 2017-03-09 20:28
I tried investigating if there's a memory leak but I was very confused by Android's memory profiling and monitoring tools.

**Comment by johanlunds** [comment] 2017-03-13 18:24
Ping @jfirebaugh

**Comment by jfirebaugh** [comment] 2017-07-12 21:19
Is this reproducible with version 5.1.0 of the Android SDK?

**Comment by tobrun** [comment] 2017-07-13 05:12
Haven't seen logs of this myself anymore, feel free to comment if otherwise. Closing for now.

**Closed by tobrun** 2017-07-13 05:12 UTC
Labels: Android, needs information

**Comment by uburoiubu** [comment] 2017-07-25 15:44
Android-sdk:5.1.0@aar

Got these logs.

**Comment by riyadfebrian** [comment] 2017-08-23 07:04
the same like me, i use Android-sdk:5.1.0@aar

**Comment by tobrun** [comment] 2017-08-23 07:12
We are looking into this as part of https://github.com/mapbox/mapbox-gl-native/issues/9688
