### ISSUE TITLE
Custom tiles do not load on an Mapbox Android native client

### ISSUE THREAD

**Issue by isimonescu** [mapbox/mapbox-gl-native#6307] opened 2016-09-12 11:48 UTC
Platform: Android
Mapbox SDK version: 4.1.1.
### Steps to trigger behavior

When using datasource "planet.mbtiles" (latest data) from osm2vectortiles, some tiles on mapbox-gl-native Android client do not load, while the same tiles load ok on mapbox-gl-js client. The logcat shows the following output:

09-12 11:20:24.660 9535-9535/com.test.me.app E/mbgl: [Style]: Failed to load tile 7/69/45=>7 for source mapbox: std::exception
09-12 11:20:35.592 9535-9535/com.test.me.app E/mbgl: [Style]: Failed to load tile 6/34/22=>6 for source mapbox: std::exception
09-12 11:21:40.835 9535-9535/com.test.me.app E/mbgl: [Style]: Failed to load tile 6/33/22=>6 for source mapbox: std::exception

The first tile (7/69/45) can also be accessed here:
http://filebin.ca/2uoelqWBv0zM
### Expected behavior

mapbox-gl-js client rendering:
![tile_load_error_web_ok](https://cloud.githubusercontent.com/assets/5670067/18434531/faecb7ee-78ed-11e6-9470-8a6d31068b4c.png)
### Actual behavior

mapbox-gl-native Android rendering:
![tile_load_error_android_bug](https://cloud.githubusercontent.com/assets/5670067/18434554/10648fb6-78ee-11e6-9f9c-eff2f24633a4.png)

**Comment by jfirebaugh** [comment] 2016-09-12 16:38
Can you provide the style you're using for rendering?

**Comment by isimonescu** [comment] 2016-09-13 06:17
The style is basically stock from osm2vectortiles (https://github.com/klokantech/osm2vectortiles-gl-styles/blob/gh-pages/styles/bright-v8.json) with a few color tunings and a custom raster tile background.

Is the style relevant to the tile not being loaded?

**Comment by cammace** [comment] 2016-09-14 14:00
@isimonescu using the bright style you linked to, i'm not able to produce on my end. 

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5652865/18514917/6b394c64-7a61-11e6-824e-fd6297935379.gif)

The issue might be caused by the custom raster tile background, could you try temporarily removing and test out again?

**Comment by isimonescu** [comment] 2016-09-15 12:18
I am sorry, the style was just for reference, not for preview.

I exposed our server live, here is the correct style with accessible data.
http://84.255.244.132:1335/style_broken.json <-- this style has newest 3rd party data from osm2vectortiles
http://84.255.244.132:1335/style_works.json <-- this style has old 3rd party data from osm2vectortiles, which DOES display the adriatic coast, but has faulty data elsewhere, not related to this issue

Also, I removed the custom raster tile background and it did not make any difference at all.

Please take a look.

**Comment by cammace** [comment] 2016-09-16 20:50
Has the style changed? I loaded it and it works fine (bugs not reproducible) except the hillshade isn't showing up. Note that i'm using the SNAPSHOT version of our SDK which is built nightly from source.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/18600762/4ba56f86-7c2d-11e6-8a3b-da06a0350a98.gif)

**Comment by isimonescu** [comment] 2016-09-29 08:00
The style you used is the correct one - I just cleaned it up so isolate the issue. We tested it with the 4.2.0-beta.3 version and it loaded OK - but it is A LOT slower than your stock maps. Here's the experience:
- if the whole world is shown, it is super fast
- as soon as you zoom in to the first roads being shown, it becomes almost unresponsive, although the amount of data shown does not increase significantly
- as you zoom in further, it becomes faster again

My question: why is it so slow? It probably isn't a load issue, because even if you pan the map around an already loaded area, rendering is slow. Is the dataset in the upper tile zooms too large? Is the style being applied on the fly at render time rather than at load time?

**Comment by cammace** [comment] 2016-10-18 18:36
you'll need to define "slow" better, typically, the more data being displayed on the map along with the hardware/software being used to display the map are causes for slow tile loading. You could also make sure you are on a solid internet connection. If the original issue in this ticket has been resolved I feel we are safe to close this issue.

**Closed** 2017-01-03 23:34 UTC
Labels: needs clarification
