### ISSUE TITLE
enforce TileJSON bounds

### ISSUE THREAD

**Issue by rm3dbeckers** [mapbox/mapbox-gl-native#5394] opened 2016-06-17 17:52 UTC
![multiple_layers_bounds_do_not_work](https://cloud.githubusercontent.com/assets/17709375/16159908/9b697788-34c5-11e6-9463-7134c92a7aae.gif)

According to https://github.com/mapbox/tilejson-spec/tree/master/2.1.0, there is parameter "bounds", which can be used to define east, south, west, north LatLon bounds on a source, unfortunately this parameter seems to have no effect in a style.json.

We are trying to use our own raster Tilesource (which basically works great), which unfortunately doesn't cover the whole world. So we use another tilesource behind it, and now would like to only request our tiles within given bounds and only request the other tiles outside of the bounds.

The main problem is that right now both sources are being queried inside of the bounds, which of course produces unnecessary traffic and creates an ugly visual effect as you are able to see the unwanted tiles for a short amount of time (or maybe even longer, depending on bandwidth).

**Comment by jfirebaugh** [comment] 2016-06-24 22:50
Duplicate of #2329.

**Comment by rm3dbeckers** [comment] 2016-06-27 08:49
There seems to be a misunderstanding.
We don't want to restrict the area, in which the camera can be moved (we want it to be the whole world). We want to restrict the area in which on of the sources, that is used by one of our layers, is being used, so we can achieve something like: In central europe the first source is being used, for the rest of the tiles the other source is being used.
Ideally the bounds could be inverted as well, so we wouldn't have to create 4 different sources to surround the central europe area :)

**Comment by jfirebaugh** [comment] 2016-06-27 15:47
Thank you for clarifying!

**Comment by jfirebaugh** [comment] 2017-04-12 21:27
GL-JS implementation happened in https://github.com/mapbox/mapbox-gl-js/pull/4556.

**Comment by femski** [comment] 2017-07-09 00:56
+1
very important for us. It impacts how to structure your application - as one big raster layer or multiple smaller layer. Its impossible to do multiple smaller raster layer without bounds checking upfront. Needlessly querying dozens of sources makes app very very slow.

**Closed** 2018-01-05 14:35 UTC
Labels: Core, GL JS parity
