### ISSUE TITLE
E/libEGL: call to OpenGL ES API with no current context (logged once per thread) and eglSwapBuffers() returned error 12301

### ISSUE THREAD

**Issue by riyadfebrian** [mapbox/mapbox-gl-native#9877] opened 2017-08-29 01:40 UTC
I implement an app that can remove the layer and add the layer dyamicaly triggered with button, it's work perfectly but when i test to remove and add layer 20+ times, it got an error

detail error : 

`08-29 08:36:00.461 15123-15123/com.sig.probolinggo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.sig.probolinggo, PID: 15123
                                                                     Theme: themes:{default=overlay:org.cyanogenmod.hexolibre, iconPack:system, fontPkg:com.kapp.cm.theme.custom_480820583, com.android.systemui=overlay:org.cyanogenmod.hexolibre, com.android.systemui.navbar=overlay:system}
                                                                     java.lang.Error: eglSwapBuffers() failed
                                                                         at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                                         at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:179)
                                                                         at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:407)
                                                                         at android.view.View.draw(View.java:16187)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15184)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.View.draw(View.java:15957)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                         at com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild(SlidingUpPanelLayout.java:1191)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                         at android.view.View.draw(View.java:16190)
                                                                         at com.sothree.slidinguppanel.SlidingUpPanelLayout.draw(SlidingUpPanelLayout.java:1244)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15184)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15144)
                                                                         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
                                                                         at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
                                                                         at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
                                                                         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                     	at android.os.Handl
`

anybody have a solution for this bug ?
i think this is about buffer in EGLS Mapbox

**Comment by tobrun** [comment] 2017-08-29 05:11
@riyadfebrian could you share some code helping us to reproduce this? 
Are you calling all methods on MapboxMap from the UI thread?

**Comment by riyadfebrian** [comment] 2017-08-29 09:09
Here's the code

First Initialization
```
@Override
    public void onMapReady(final MapboxMap mapboxMap) {
        this.mapboxMap = mapboxMap;
        try {
            loadAllGeoJson();
            // the default is Peta Administrasi
            makeFillLayer('0');
            makeLineLayer('0');
            makeSymbolLayer('0');
 } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```

it will calls this method


  ```
  private void loadAllGeoJson () throws InterruptedException {

        Thread addSourceGeoJson = new Thread() {
            public void run() {
                GeoJsonSource[] x = new GeoJsonSource[load_loop];

                try {

                    // added geojson to layer map
                    for (int i = 0; i < load_loop; i++) {
                        x[i] = new GeoJsonSource(("source-" + i), config.loadJsonFromAsset(getApplicationContext(), filename[i]));
                        mapboxMap.addSource(x[i]);
                    }

                } catch (Exception e) {
                    Log.d("Error", "Hasil : "+ e);
                }

                Log.d("Error", "Loaded GeoJSON Source");

            }
        };

        addSourceGeoJson.start();
        addSourceGeoJson.join();


    }

    private void makeFillLayer (final char args) throws InterruptedException {
        Thread fillthelayer = new Thread() {
            public void run() {

                if (args == '0') {
                    // peta administrasi
                    load_loop = 24;

                } else {
                    //peta bencana
                    load_loop = 4;
                    //  perulangan pertama untuk peta administrasi
                    //  perulangan selanjutnya untuk peta bencana
                }

                FillLayer[] warna = new FillLayer [load_loop];

                for (int i=0; i < load_loop; i++) {
                    if (load_loop == 24) {
                        warna[i] = new FillLayer(("source" + i + "-fill"), ("source-0"));
                        config.setPropertiesFill(warna[i], (short) 1, (short) i);
                    } else {
                        if  (i == 0 ) {
                            //perulangan pertama untuk peta administrasi
                            warna[i] = new FillLayer(("source" + i + "-fill"), ("source-0"));
                            config.setPropertiesFill(warna[i], (short) 1, (short) -1);
                        }  else {
                            warna[i] = new FillLayer(("source" + i + "-fill"), ("source-"+args));
                            Log.d("Error", "source to layer add = " + "source-"+args);
                            config.setPropertiesFill(warna[i], (short) (i+1), (short) -1);
                        }

                    }

                    if (i == 0) {
                        mapboxMap.addLayerBelow(warna[i], "airport-label");
                    } else {
                        mapboxMap.addLayerAbove(warna[i], ("source"+(i-1)+"-fill"));
                    }
                }
                Log.d("Error", "Fill Layer");

            }
        };

        fillthelayer.start();
        fillthelayer.join();


    }

    private void makeLineLayer (final char args) throws InterruptedException {

        Thread addlinetolayer = new Thread() {
          public void run () {
              String fill;

              if (args == '0') {
                  fill = "source23-fill";
              } else {
                  fill = "source3-fill";
              }

              LineLayer batas_administrasi = new LineLayer("administrasi-border", "source-0");
              config.setPropertiesLine(batas_administrasi, '0', 1f, "#000000");
              mapboxMap.addLayerAbove(batas_administrasi, fill);

              Log.d("Error", "Line Layer");

          }
        };

        addlinetolayer.start();
        addlinetolayer.join();


    }

    private void makeSymbolLayer (final char args) throws InterruptedException {
        final Thread addSymbolLayer = new Thread() {
          public void run () {

              Bitmap icon = BitmapFactory.decodeResource(getApplicationContext().getResources(), R.drawable.ic_centroid);
              mapboxMap.addImage("my-marker-image", icon);

              SymbolLayer centroid = new SymbolLayer("centroid-symbol", "source-8").withProperties(
                      iconSize(0.4f),
                      iconImage("my-marker-image")
              );

              if (args == '0') {
                  mapboxMap.addLayerAbove(centroid, "source23-fill");
                  Log.d("Error", "dieksekusi di source 23");
              } else {
                  mapboxMap.addLayerAbove(centroid, "source3-fill");
                  Log.d("Error", "dieksekusi di source 3");
              }
              Log.d("Error", "SymbolLayer");

            }

        };
        addSymbolLayer.start();


    }
```


and for the dynamic change of geojson layer, i use RxBus event

```
@Subscribe
    public void OnreceivedMessage (String msg) throws InterruptedException {
        Log.d("Error", "pesan RxBus : " + msg);
        now_State = msg;

        if (previous_State.equals("desa") && !now_State.equals("desa")) {

            for (int i=0; i < 24; i++) {
                mapboxMap.removeLayer("source" +  i +"-fill");
            }
            mapboxMap.removeLayer("centroid-symbol");

        } else {
            if (!previous_State.equals(now_State)) {
                for (int i=0; i < 4; i++) {
                    mapboxMap.removeLayer("source" +  i +"-fill");
                }
                mapboxMap.removeLayer("centroid-symbol");
            }

        }

        if (now_State.equals("abrasi") && (!previous_State.equals("abrasi")) ) {
            // abrasi
            changeLayout('1');
        } else if (msg.equals("banjir") && (!previous_State.equals("banjir")) ) {
            //banjir
            changeLayout('2');
            mTampilkan = new Tes_getData();
            mTampilkan.execute((Void) null);
        } else if (msg.equals("banjirbandang") && (!previous_State.equals("banjirbandang")) ) {
            //banjir bandang
            changeLayout('3');
        } else if (msg.equals("gempabumi") && (!previous_State.equals("gempa")) ) {
            //gempa
            changeLayout('4');
        } else if (msg.equals("gunungmeletus") && (!previous_State.equals("gunungmeletus")) ) {
            //gunung meletus
            changeLayout('5');
        } else if (msg.equals("kekeringan") && (!previous_State.equals("kekeringan")) ) {
            //kekeringan
            changeLayout('6');
        } else if (msg.equals("tanahlongsor") && (!previous_State.equals("tanahlongsor")) ) {
            //tanah longsor
            changeLayout('7');
        }

        previous_State = now_State;
        Log.d("Error", "Prsent State = " + now_State );

    }
```

and method changeLayout
```
 private void changeLayout(char params) throws InterruptedException {
        makeFillLayer(params);
        makeSymbolLayer('1');
    }
```

**Comment by riyadfebrian** [comment] 2017-08-29 09:11
the config.class

```
package com.sig.probolinggo.geojson;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.util.Log;

import com.mapbox.mapboxsdk.storage.Resource;
import com.mapbox.mapboxsdk.style.layers.FillLayer;
import com.mapbox.mapboxsdk.style.layers.LineLayer;
import com.mapbox.mapboxsdk.style.layers.Property;
import com.mapbox.mapboxsdk.style.layers.PropertyFactory;
import com.mapbox.mapboxsdk.style.layers.SymbolLayer;
import com.mapbox.mapboxsdk.style.sources.GeoJsonSource;
import com.sig.probolinggo.R;

import java.io.IOException;
import java.io.InputStream;

import static com.mapbox.mapboxsdk.Mapbox.getApplicationContext;
import static com.mapbox.mapboxsdk.style.layers.Filter.eq;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.fillColor;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.fillOpacity;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.iconImage;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.iconSize;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.lineWidth;

public class config {

    public static String loadJsonFromAsset(Context context, String filename) throws IOException {

        // loads in GeoJSON files from the assets folder.
        InputStream is = context.getAssets().open("geojson/" + filename + ".geojson");
        int size = is.available();
        byte[] buffer = new byte[size];
        is.read(buffer);
        is.close();
        return new String(buffer, "UTF-8");
    }

    public static void setPropertiesFill (FillLayer object, short TAG, short i) {
        // char TAG: 0 : none; 1 : zona 1; 2 : zona 2; 3 : zona 3
        String filter_x = "filter words";
        String color = "color code hex";

        if (TAG == 1) {

                if (i >= 0 ) {
                    switch (i) {
                        //filter untuk administrasi desa
                        case 0:
                            filter_x = "BANTARAN";
                            color = "#e370ff";
                            break;
                        case 1:
                            filter_x = "BANYUANYAR";
                            color = "#ff7d82";
                            break;
                        case 2:
                            filter_x = "BESUK";
                            color = "#6fb3fc";
                            break;
                        case 3:
                            filter_x = "DRINGU";
                            color = "#fed57b";
                            break;
                        case 4:
                            filter_x = "GADING";
                            color = "#73ffe4";
                            break;
                        case 5:
                            filter_x = "GENDING";
                            color = "#fffe6f";
                            break;
                        case 6:
                            filter_x = "KOTAANYAR";
                            color = "#a1ff72";
                            break;
                        case 7:
                            filter_x = "KRAKSAAN";
                            color = "#8d414d";
                            break;
                        case 8:
                            filter_x = "KREJENGAN";
                            color = "#754382";
                            break;
                        case 9:
                            filter_x = "KRUCIL";
                            color = "#d59da0";
                            break;
                        case 10:
                            filter_x = "KURIPAN";
                            color = "#9eabd7";
                            break;
                        case 11:
                            filter_x = "LECES";
                            color = "#c9d060";
                            break;
                        case 12:
                            filter_x = "LUMBANG";
                            color = "#78f5c9";
                            break;
                        case 13:
                            filter_x = "MARON";
                            color = "#6478cf";
                            break;
                        case 14:
                            filter_x = "PAITON";
                            color = "#ffbde8";
                            break;
                        case 15:
                            filter_x = "PAJARAKAN";
                            color = "#4d7201";
                            break;
                        case 16:
                            filter_x = "PAKUNIRAN";
                            color = "#97e400";
                            break;
                        case 17:
                            filter_x = "SUKAPURA";
                            color = "#cd8964";
                            break;
                        case 18:
                            filter_x = "SUMBER";
                            color = "#00e5ac";
                            break;
                        case 19:
                            filter_x = "SUMBERASIH";
                            color = "#e39a00";
                            break;
                        case 20:
                            filter_x = "TEGALSIWALAN";
                            color = "#a8f478";
                            break;
                        case 21:
                            filter_x = "TIRIS";
                            color = "#e2e0e5";
                            break;
                        case 22:
                            filter_x = "TONGAS";
                            color = "#f4cb79";
                            break;
                        case 23:
                            filter_x = "WONOMERTO";
                            color = "#cb679b";
                            break;
                    }

                    object.setFilter(eq("KECAMATAN", filter_x));
                } else {
                    // peta satu warna dasar
                    color = "#e4ffe2";
                }
            object.setProperties(
                    fillColor(Color.parseColor(color)),
                    fillOpacity(0.3f) );

        } else  {
            //filter untuk peta bencana
                 if (TAG == 2) {
                     filter_x = "Zona I";
                     object.setFilter(eq("Zona", filter_x));
                     color = "#38a700";
                } else if (TAG == 3) {
                     filter_x = "Zona II";
                    object.setFilter(eq("Zona", filter_x));
                     color = "#feff73";
                } else if (TAG == 4) {
                     filter_x = "Zona III";
                    object.setFilter(eq("Zona", filter_x));
                     color = "#fe0000";
                }

            object.setProperties(
                    fillColor(Color.parseColor(color)),
                    fillOpacity(0.6f)
            );

        }

    }

    public static void setPropertiesLine (LineLayer object, char filter, float thickness, String color) {
        // char filter: 0 : none; 1 : zona 1; 2 : zona 2; 3 : zona 3

        if (filter == '0') {
            object.setProperties(
                    PropertyFactory.lineColor(Color.parseColor(color)),
                    lineWidth(thickness),
                    PropertyFactory.lineCap(Property.LINE_CAP_ROUND),
                    PropertyFactory.lineJoin(Property.LINE_JOIN_ROUND)
            );
        } else if (filter >= '0') {
            if (filter == '1') {
                object.setFilter(eq("Zona", "Zona I"));
            } else if (filter == '2') {
                object.setFilter(eq("Zona", "Zona II"));
            } else if (filter == '3') {
                object.setFilter(eq("Zona", "Zona III"));
            }

            object.setProperties(
                    PropertyFactory.lineColor(Color.parseColor(color)),
                    lineWidth(thickness),
                    PropertyFactory.lineCap(Property.LINE_CAP_ROUND),
                    PropertyFactory.lineJoin(Property.LINE_JOIN_ROUND)
            );

        }

    }

}

```

**Comment by tobrun** [comment] 2017-08-29 09:42
@riyadfebrian  I'm seeing that you are creating separate threads and in those you are calling methods on MapboxMap. MapboxMap is annotated with `@UiThread` and its methods should only be called from the main thread. Optimizing your code to take this in account will remove the crash. Thank you for the report, closing as root cause has been identified.

**Closed by tobrun** 2017-08-29 09:42 UTC
Labels: Android, needs information

**Comment by riyadfebrian** [comment] 2017-08-29 12:27
Fixed. thanks... :)
i've  removed the separated threads...
and it works perfectly without bug...

tested 50+ times removing and adding a geojson layer
