### ISSUE TITLE
Incorrect colors at startup

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3259] opened 2015-12-11 07:31 UTC
As of bde07c8f0edcc890efd7fd6993f5309d6881c402, I’m seeing iosapp occasionally launch with a corrupted Streets style:

![img_0926](https://cloud.githubusercontent.com/assets/1231218/11738209/784b0372-9f95-11e5-8d63-660ffc4f4ea2.PNG)

![osxapp](https://cloud.githubusercontent.com/assets/1231218/11797763/36bbe146-a27a-11e5-9203-d131a1042ea6.png)

Everything goes back to normal upon the very next redraw. At z0, this redraw doesn’t happen until the user manually interacts with the map, but at higher zoom levels, this happens automatically when labels fade in. Still, the corrupted rendering is visible long enough that to the user it’s as though a negative of the map is flashing in.

/cc @jfirebaugh @kkaefer

**Comment by bleege** [comment] 2015-12-14 21:51
There are similar issues in the Android TestApp as well.

/cc @mapbox/mobile

**Comment by zugaldia** [comment] 2015-12-14 21:51
We're also seeing this on Android, including during transitions: https://www.dropbox.com/s/3c2qzlxftogmyld/weird.mp4?dl=0

**Comment by 1ec5** [comment] 2015-12-14 22:36
This regression was caused by 93c000dd18f5896b6d0c5b3f1670c999489c2f12 for #3066. The viewport isn’t being set on Android, iOS, or OS X anymore – only on GLFW and HeadlessView.

/cc @kkaefer

**Comment by jfirebaugh** [comment] 2015-12-14 22:37
As always, there may be multiple issues -- for me this bisected to 45c7b472adb78600ab9f9c8f82082d6b0af21ba2, which was also my guess beforehand.

**Comment by jfirebaugh** [comment] 2015-12-14 23:51
@zugaldia @1ec5 Can you check if 9b8f5d3be1d25a0eefe7f9f22544d439f54d92b1 fixes the issue?

**Comment by zugaldia** [comment] 2015-12-15 00:06
@jfirebaugh can't reproduce the issue on the Android test app anymore after applying https://github.com/mapbox/mapbox-gl-native/commit/9b8f5d3be1d25a0eefe7f9f22544d439f54d92b1

**Comment by jfirebaugh** [comment] 2015-12-15 00:38
Great, merged. @1ec5 please reopen if this doesn't also fix the issue on iOS.

**Closed by jfirebaugh** 2015-12-15 00:38 UTC
Labels: bug

**Comment by 1ec5** [comment] 2015-12-15 00:39
Looks good in iosapp. Thanks for taking care of this one.

**Comment by bleege** [comment] 2015-12-15 15:22
I rebased on my working branch for #3244 (Camera API) and retested.  The colors seem to be back on track, although there appears to still be an issue with `MapView.setCenterCoordinate()` not immediately drawing.  I'll keep working on it there though.

**Comment by bleege** [comment] 2015-12-15 15:22
Forgot to say... great job diagnosing and solving this yesterday @jfirebaugh @1ec5!
