### ISSUE TITLE
-pre.x suffix in CFBundleShortVersionString triggers App Store submission error

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#3911] opened 2016-02-11 22:59 UTC
![](https://cldup.com/TpaUm61b8f.png)

Going forward, `pre` versions should perhaps look like `3.1.1-pre1`.

/cc @1ec5

**Comment by 1ec5** [comment] 2016-02-11 23:03
The problem is that CFBundleShortVersionString must follow the format x.y.z, so it should say 3.1.1 in this case, not 3.1.1-pre.11. Under Apple Generic Versioning, the integer CFBundleVersion is used to distinguish between different builds with the same marketing version.

**Comment by 1ec5** [comment] 2016-02-11 23:04
To be clear, this affects only prerelease builds of the Mapbox iOS SDK. Stable releases are unaffected.

**Comment by 1ec5** [comment] 2016-02-11 23:26
One more thing: 3.1.1-pre1 would violate Semantic Versioning rules. The dot has to be in there, odd as it looks.

**Comment by 1ec5** [comment] 2016-02-13 18:26
Fixed in #3937, which will be in v3.1.1 shortly.

**Closed by 1ec5** 2016-02-13 18:26 UTC
Labels: build, in progress, iOS
