### ISSUE TITLE
Marker isn't repositioned to the front when calling selectMarker()

### ISSUE THREAD

**Issue by lyptt** [mapbox/mapbox-gl-native#5785] opened 2016-07-25 15:19 UTC
On the Android Mapbox SDK, calling `selectMarker()` doesn't bring the marker to the front, however manually clicking on the marker in the map view does do this.

Is there any other way of bringing a GL marker to the front?

**Comment by cammace** [comment] 2016-09-27 14:37
GL markers aren't moving to the front when `selectMarkers` called but MarkerViews seem to be working as intended. I'd recommend using them:

![ezgif com-video-to-gif 10](https://cloud.githubusercontent.com/assets/5652865/18878104/668f93c6-849d-11e6-916f-8f94052999dd.gif)

**Closed** 2016-10-12 11:49 UTC
Labels: Android
