### ISSUE TITLE
Style JSON String support

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14137] opened 2019-03-16 18:30 UTC
Feature request to support loading a style json from a string. After digging some through the documentation [here](https://docs.mapbox.com/ios/api/maps/4.9.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)style), I'm not seeing how I can load a string to be the rendered style. Am I missing something? I believe this is a very useful API to support.

cc @julianrex

**Comment by julianrex** [comment] 2019-03-19 12:14
@tobrun can you point me at the Android equivalent please?

**Comment by tobrun** [comment] 2019-03-19 12:41
Public API binding in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java#L798.
Which uses this builder https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java#L595
Which hooks into the core map api: https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/style.cpp#L17

**Comment by 1ec5** [comment] 2019-03-26 23:56
This is a duplicate of #6386, right?

**Comment by 1ec5** [comment] 2019-03-27 00:15
Closing in favor of #6386.

**Closed by 1ec5** 2019-03-27 00:15 UTC
Labels: iOS, needs discussion
