### ISSUE TITLE
Annotations disappear from some tiles until panned out of view or zoomed

### ISSUE THREAD

**Issue by JosephShering** [mapbox/mapbox-gl-native#2956] opened 2015-11-06 04:57 UTC
I'm using Swift with the Mapbox iOS SDK. Is there a way around this issue?

**Comment by petezendesk** [comment] 2015-11-06 10:06
Having the same problem when I use 'showAnnotations(..).

**Comment by BenjaminDigeon** [comment] 2015-11-06 11:28
Having the same problem too, with objective-c.

**Comment by 1ec5** [comment] 2015-11-06 16:11
Wonder if this could be fixed by #2951.

**Comment by picciano** [comment] 2015-11-06 17:30
Not to join the "me too" bandwagon, but we've started seeing this in the past few days. Possible regression of https://github.com/mapbox/mapbox-gl-native/issues/1675 ?

**Comment by 1ec5** [comment] 2015-11-06 17:38
@jfirebaugh, did you run into this problem while refactoring annotations at the core level?

**Comment by jfirebaugh** [comment] 2015-11-06 18:37
I'm not able to reproduce this in our annotation tests or in the test app. Can someone share example code?

**Comment by picciano** [comment] 2015-11-06 18:53
This test project demonstrates the issue.
https://github.com/tallygo/MissingMapMarkers

The map should display a map with a polyline and two annotations. Tapping the "redraw" button will instantiate a new map. The results are inconsistent, you will often see part of the line missing, one or both annotations missing.
![simulator screen shot nov 6 2015 11 52 59 am](https://cloud.githubusercontent.com/assets/417933/11005759/f5905dac-847c-11e5-87f1-b5668158bc00.png)
![simulator screen shot nov 6 2015 11 51 01 am](https://cloud.githubusercontent.com/assets/417933/11005760/f59f208a-847c-11e5-811f-0fe88ad3c1e2.png)
![simulator screen shot nov 6 2015 11 50 58 am](https://cloud.githubusercontent.com/assets/417933/11005761/f5a2f4bc-847c-11e5-8b5b-07d9094b30a9.png)

**Comment by picciano** [comment] 2015-11-19 22:36
This problem seems to come and go with different builds.

This started worked reliably in https://github.com/mapbox/mapbox-gl-native/tree/85ab48636c0f0cb5b1ec5c5b6b64a41dbd188e06

But has since regressed again. It's not working well in ios-v3.0.0-pre.9 at all. In fact, of the releases, I have to go back to ios-v3.0.0-pre.2 to find good working version.

**Comment by YBthebest** [comment] 2015-11-20 00:41
I can confirm this issue. I have exactly the same for the pre.9 build.

**Comment by 1ec5** [comment] 2015-12-11 19:04
I’m unable to reproduce the issue in the MissingMapMarkers sample application using Mapbox iOS SDK 3.0.1.

**Comment by picciano** [comment] 2015-12-11 19:34
I'll check that out, thanks for the update

**Comment by picciano** [comment] 2015-12-11 21:29
I agree, 3.0.1 is working great. No missing point or line annotations.
Do we know what caused this?

**Comment by jfirebaugh** [comment] 2015-12-14 22:30
This probably settled down with 7669e02062ccab9e3d908a9eab04f5d13a7b89c0.

**Closed by jfirebaugh** 2015-12-14 22:30 UTC
Labels: bug, iOS
