### ISSUE TITLE
Poor performance on macOS

### ISSUE THREAD

**Issue by mmase** [mapbox/mapbox-gl-native#10013] opened 2017-09-16 03:45 UTC
**Platform:** macOS
**Mapbox SDK version:** 3.6.3

### Steps to trigger behavior

 1. open demo app on recent retina macbook pro model (2015, 2016, 2017)
 2. make the app either full screen or full width/height
 3. pan, zoom, etc

### Expected behavior
the native app be more performant than web version

### Actual behavior
it is substantially slower. when the window is smaller, it improves. this is before adding any customization. seems to freeze up and just really struggle with rendering in a performant fashion.

**Comment by fabian-guerra** [comment] 2017-09-18 15:28
Hi @mmase thank you for using Mapbox. I am sorry to hear you have some issues. To clarify are you using our macOS sdk version [0.5.0](https://github.com/mapbox/mapbox-gl-native/releases/tag/macos-v0.5.0)?

We are already aware of the issue as noted here https://github.com/mapbox/mapbox-gl-native/issues/9912. There should be a new version soon.

**Comment by fabian-guerra** [comment] 2017-09-18 15:30
I'm closing this as is already fixed. I will let you know when the new version is released.

**Closed by fabian-guerra** 2017-09-18 15:30 UTC
Labels: macOS, performance

**Comment by mmase** [comment] 2017-09-18 15:36
Thanks, @fabian-guerra and sorry for the noise!

**Comment by 1ec5** [comment] 2017-09-18 17:23
#9912 was caused by #9676, which hasn’t made it into any macOS SDK release yet. But it sounds like @mmase was using a release, so this slowness is probably #7820, which is a long-running issue. Can you clarify which version you were running?

**Comment by mmase** [comment] 2017-09-18 17:30
apologies for confusion, I was using latest on master as of friday evening.

**Comment by 1ec5** [comment] 2017-09-19 16:23
No worries, glad this worked out!
