### ISSUE TITLE
(Android) Crash when back from activity contain MapView.

### ISSUE THREAD

**Issue by vfaSonnt** [mapbox/mapbox-gl-native#5021] opened 2016-05-13 07:25 UTC
**Platform: Android_ Sony LT26w __ OS 4.1.2**
**Mapbox SDK version: com.mapbox.mapboxsdk:mapbox-android-sdk:4.0.0@aar**

### Steps to trigger behavior

 1. Open any example from MapboxGL Android.
 2. Wait until map load success.
 3. Press back to go back Menu Screen.

### Expected behavior
Open the screen without any problem.

### Actual behavior
It is force close.

```
06-09 11:12:47.819 172-172/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 11:12:47.819 172-172/? I/DEBUG: Build fingerprint: 'SEMC/LT26w_1266-2032/LT26w:4.1.2/6.2.B.1.96/n7v_zg:user/release-keys'
06-09 11:12:47.819 172-172/? I/DEBUG: pid: 21410, tid: 21410, name: le.myapp.dev  >>> dev.myapp <<<
06-09 11:12:47.819 172-172/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000230
06-09 11:12:48.279 172-172/? I/DEBUG:     r0 6b480420  r1 63827ea0  r2 00000000  r3 6ddf36f8
06-09 11:12:48.279 172-172/? I/DEBUG:     r4 6b480420  r5 63827ea0  r6 63827300  r7 00000000
06-09 11:12:48.289 172-172/? I/DEBUG:     r8 6b480c6c  r9 6b480420  sl 00000014  fp 00000000
06-09 11:12:48.289 172-172/? I/DEBUG:     ip 00000000  sp bedd55c8  lr 5cb5d4ef  pc 5cb695bc  cpsr 20000030
06-09 11:12:48.289 172-172/? I/DEBUG:     d0  0000050044a01000  d1  0000000044a01000
06-09 11:12:48.289 172-172/? I/DEBUG:     d2  000000004211d530  d3  0000000056d75548
06-09 11:12:48.289 172-172/? I/DEBUG:     d4  0000000000000000  d5  0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d6  0000000000000000  d7  0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d8  3f8000003f800000  d9  4434000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d10 3ff00000441ec000  d11 0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d12 0000000000000000  d13 0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d14 0000000000000000  d15 0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d16 0000000000001a04  d17 0000000000000001
06-09 11:12:48.289 172-172/? I/DEBUG:     d18 0000000000000000  d19 0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d20 0000000000000000  d21 0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d22 0000000000000000  d23 0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     d24 0013375175a1abab  d25 0013385276a3abab
06-09 11:12:48.289 172-172/? I/DEBUG:     d26 0013395276a3abab  d27 002877b1f1fbffff
06-09 11:12:48.289 172-172/? I/DEBUG:     d28 0100010001000100  d29 0100010001000100
06-09 11:12:48.289 172-172/? I/DEBUG:     d30 0000000000000000  d31 0000000000000000
06-09 11:12:48.289 172-172/? I/DEBUG:     scr 28000013
06-09 11:12:48.289 172-172/? I/DEBUG:     #00  pc 000405bc  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_array_object+19)
06-09 11:12:48.289 172-172/? I/DEBUG:     #01  pc 000344ed  /system/lib/egl/libGLESv2_adreno200.so (nobj_destroy_table+42)
06-09 11:12:48.289 172-172/? I/DEBUG:     #02  pc 0002ae6f  /system/lib/egl/libGLESv2_adreno200.so (gl2_context_delete+1130)
06-09 11:12:48.289 172-172/? I/DEBUG:     #03  pc 00015ddc  /system/lib/egl/libEGL_adreno200.so (eglDestroyClientApiContext+60)
06-09 11:12:48.289 172-172/? I/DEBUG:     #04  pc 00015e60  /system/lib/egl/libEGL_adreno200.so (eglFreeContext+72)
06-09 11:12:48.289 172-172/? I/DEBUG:     #05  pc 00016a1c  /system/lib/egl/libEGL_adreno200.so (eglContextReleaseRef+336)
06-09 11:12:48.289 172-172/? I/DEBUG:     #06  pc 0000edf4  /system/lib/egl/libEGL_adreno200.so (qeglDrvAPI_eglDestroyContext+188)
06-09 11:12:48.289 172-172/? I/DEBUG:     #07  pc 00005f68  /system/lib/egl/libEGL_adreno200.so (eglDestroyContext+16)
06-09 11:12:48.289 172-172/? I/DEBUG:     #08  pc 0000c847  /system/lib/libEGL.so (eglDestroyContext+66)
06-09 11:12:48.289 172-172/? I/DEBUG:     #09  pc 000e41d0  /data/data/dev.myapp/lib/libmapbox-gl.so (mbgl::android::NativeMapView::terminateContext()+64)
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5588  00001000  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd558c  6b480420  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5590  6dedc2b8  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5594  6b4806dc  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5598  00001000  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd559c  6b480a6c  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55a0  5cb695a9  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_array_object)
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55a4  6b480a6c  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55a8  00000000  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55ac  402369b1  /system/lib/libc.so (dlfree+56)
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55b0  40236979  /system/lib/libc.so (dlfree)
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55b4  6b480a6c  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55b8  5cb695a9  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_array_object)
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55bc  6b480a6c  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55c0  df0027ad  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55c4  00000000  
06-09 11:12:48.289 172-172/? I/DEBUG:     #00  bedd55c8  6b480a6c  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55cc  5cb695a9  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_array_object)
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55d0  6b480a70  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55d4  5cb5d4ef  /system/lib/egl/libGLESv2_adreno200.so (nobj_destroy_table+44)
06-09 11:12:48.289 172-172/? I/DEBUG:     #01  bedd55d8  5c8a50a0  /system/lib/libgsl.so
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55dc  6b480420  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55e0  00000000  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55e4  00000004  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55e8  6b480430  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55ec  5cb68461  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_buffer_object)
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55f0  00000000  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55f4  5cb53e73  /system/lib/egl/libGLESv2_adreno200.so (gl2_context_delete+1134)
06-09 11:12:48.289 172-172/? I/DEBUG:     #02  bedd55f8  6b480420  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd55fc  00000000  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5600  00000001  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5604  6b474800  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5608  5c896044  /system/lib/egl/libEGL_adreno200.so
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd560c  00000000  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5610  5c865a38  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5614  5c896044  /system/lib/egl/libEGL_adreno200.so
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5618  4036aad0  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd561c  00000000  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5620  5c865a38  
06-09 11:12:48.289 172-172/? I/DEBUG:          bedd5624  5c88ade0  /system/lib/egl/libEGL_adreno200.so (eglDestroyClientApiContext+64)
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480400 00000000 00000280 000000a0 00000062  ............b...
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480410 00040006 00000000 00000038 00000f5b  ........8...[...
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480420 00000000 6b4746c8 6b481378 01010101  .....FGkx.Hk....
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480430 00000000 00000000 00000000 3f6dedef  ..............m?
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480440 3f69e9eb 3f59d9db 3f800000 3f800000  ..i?..Y?...?...?
06-09 11:12:48.299 172-172/? I/DEBUG:     63827e80 00000000 000003ec 00000000 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     63827e90 00000000 00000000 000006f8 0000009a  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     63827ea0 00000000 00000001 00000001 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     63827eb0 00000000 00000000 00000001 0000ffff  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     63827ec0 00000001 00000001 00000000 63827f80  ...............c
06-09 11:12:48.299 172-172/? I/DEBUG:     6ddf36d8 6ddf3258 6ddf3658 6ddf3260 6ddf3258  X2.mX6.m`2.mX2.m
06-09 11:12:48.299 172-172/? I/DEBUG:     6ddf36e8 6ddf3678 6037af88 6037b1e4 0000fe15  x6.m..7`..7`....
06-09 11:12:48.299 172-172/? I/DEBUG:     6ddf36f8 30203130 00000489 638272f8 638272f8  01 0.....r.c.r.c
06-09 11:12:48.299 172-172/? I/DEBUG:     6ddf3708 00000000 00000000 00000000 00000004  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     6ddf3718 00000000 00000000 00000000 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480400 00000000 00000280 000000a0 00000062  ............b...
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480410 00040006 00000000 00000038 00000f5b  ........8...[...
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480420 00000000 6b4746c8 6b481378 01010101  .....FGkx.Hk....
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480430 00000000 00000000 00000000 3f6dedef  ..............m?
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480440 3f69e9eb 3f59d9db 3f800000 3f800000  ..i?..Y?...?...?
06-09 11:12:48.299 172-172/? I/DEBUG:     63827e80 00000000 000003ec 00000000 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     63827e90 00000000 00000000 000006f8 0000009a  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     63827ea0 00000000 00000001 00000001 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     63827eb0 00000000 00000000 00000001 0000ffff  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     63827ec0 00000001 00000001 00000000 63827f80  ...............c
06-09 11:12:48.299 172-172/? I/DEBUG:     638272e0 638161a0 20303101 00000000 3f800000  .a.c.10 .......?
06-09 11:12:48.299 172-172/? I/DEBUG:     638272f0 63820cd0 63820cd8 63820cd8 00000489  ...c...c...c....
06-09 11:12:48.299 172-172/? I/DEBUG:     63827300 6ddf36f8 6ddf36f8 63d68690 6de12e48  .6.m.6.m...cH..m
06-09 11:12:48.299 172-172/? I/DEBUG:     63827310 5cf4c740 00000004 00000002 000088e4  @..\............
06-09 11:12:48.299 172-172/? I/DEBUG:     63827320 00000000 0000065a 00000000 00000000  ....Z...........
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480c4c 00000000 00000000 00000000 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480c5c 00000000 00000000 00000000 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480c6c 00000000 00000000 00000000 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480c7c 00000000 00000000 6b480c88 00000000  ..........Hk....
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480c8c 00000000 00000000 00000000 00000000  ................
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480400 00000000 00000280 000000a0 00000062  ............b...
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480410 00040006 00000000 00000038 00000f5b  ........8...[...
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480420 00000000 6b4746c8 6b481378 01010101  .....FGkx.Hk....
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480430 00000000 00000000 00000000 3f6dedef  ..............m?
06-09 11:12:48.299 172-172/? I/DEBUG:     6b480440 3f69e9eb 3f59d9db 3f800000 3f800000  ..i?..Y?...?...?
06-09 11:12:48.299 172-172/? I/DEBUG:     bedd55a8 00000000 402369b1 40236979 6b480a6c  .....i#@yi#@l.Hk
06-09 11:12:48.299 172-172/? I/DEBUG:     bedd55b8 5cb695a9 6b480a6c df0027ad 00000000  ...\l.Hk.'......
06-09 11:12:48.299 172-172/? I/DEBUG:     bedd55c8 6b480a6c 5cb695a9 6b480a70 5cb5d4ef  l.Hk...\p.Hk...\
06-09 11:12:48.299 172-172/? I/DEBUG:     bedd55d8 5c8a50a0 6b480420 00000000 00000004  .P.\ .Hk........
06-09 11:12:48.299 172-172/? I/DEBUG:     bedd55e8 6b480430 5cb68461 00000000 5cb53e73  0.Hka..\....s>.\
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb6959c 8ff0e8bd 00054a76 ffffeedd 4604b570  ....vJ......p..F
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb695ac 2900460d 6c8ed028 6833b1be 6802b1ab  .F.)(..l..3h...h
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb695bc 3230f8d2 f8d2b113 4798022c 46236821  ..02....,..G!h#F
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb695cc f5014a0e 46317008 6812447a ff3ef7f3  .J...p1FzD.h..>.
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb695dc f5006820 f7e97008 6ce9fd4f 68a0b111   h...p..O..l...h
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb5d4cc f5004606 27007800 6948e00e 688b61b0  .F...x.'..Hi.a.h
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb5d4dc 60cf600f b113614f 1e5a6863 46486062  .`.`Oa..chZ.b`HF
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb5d4ec 682047a8 60211e41 290069b1 3604d1ed  .G hA.!`.i.)...6
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb5d4fc d1f94546 f44f4620 e8bd7206 f05043f8  FE.. FO..r...CP.
06-09 11:12:48.299 172-172/? I/DEBUG:     5cb5d50c b570b8af 688b4605 b303460c 2a14f8d0  ..p..F.h.F.....*
```

**Comment by jfirebaugh** [comment] 2016-06-01 22:41
Possible duplicate of #5094.

**Comment by vfaSonnt** [comment] 2016-06-02 02:56
This bug only happen on this device, the others work OK.
I test on Galaxy S3,S4,S5, nexus3, nexus7, some HTC model...

**Comment by vzenrhen** [comment] 2016-06-09 08:43
Same happens on Samsung GT-I8262, Android 4.1.2

```
[ 06-09 12:35:30.426  8474: 8474 I/         ]
frmFromMap onStop
[ 06-09 12:35:30.426  8474: 8474 I/         ]
frmFromMap onDestroyView
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4d8  00001000  
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4dc  533d3608  
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4e0  531ede58  
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4e4  55377dc8  
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4e8  00001000  
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4ec  533d3c54  
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4f0  52ecc639  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_array_object)
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4f4  533d3c58  
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4f8  00000000  
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c4fc  402517b1  /system/lib/libc.so (dlfree+56)
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c500  40251779  /system/lib/libc.so (dlfree)
06-09 12:35:31.406 140-140/? I/DEBUG:          bea8c504  533d3c54  
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c508  52ecc639  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_array_object)
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c50c  533d3c58  
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c510  df0027ad  
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c514  00000000  
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c51c  52ecc639  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_array_object)
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c520  533d3c5c  
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c524  52ec0577  /system/lib/egl/libGLESv2_adreno200.so (nobj_destroy_table+44)
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c52c  533d3608  
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c530  00000000  
06-09 12:35:31.416 140-140/? I/DEBUG:          bea8c534  00000004  
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c538  533d3618  
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c53c  52ecb4f1  /system/lib/egl/libGLESv2_adreno200.so (delete_vertex_buffer_object)
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c540  00000000  
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c544  52eb6ecb  /system/lib/egl/libGLESv2_adreno200.so (gl2_context_delete+1134)
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c54c  00000000  
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c550  00000001  
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c554  5103c6d8  
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c558  504c7044  /system/lib/egl/libEGL_adreno200.so
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c55c  00000000  
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c560  50457a78  
06-09 12:35:31.426 140-140/? I/DEBUG:          bea8c564  504c7044  /system/lib/egl/libEGL_adreno200.so
06-09 12:35:31.436 140-140/? I/DEBUG:          bea8c568  400ecc54  
06-09 12:35:31.436 140-140/? I/DEBUG:          bea8c56c  00000000  
06-09 12:35:31.436 140-140/? I/DEBUG:          bea8c570  50457a78  
06-09 12:35:31.436 140-140/? I/DEBUG:          bea8c574  504bc1f8  /system/lib/egl/libEGL_adreno200.so (eglDestroyClientApiContext+64)
```

**Comment by tobrun** [comment] 2016-10-20 11:12
stale

**Closed by tobrun** 2016-10-20 11:12 UTC
Labels: Android, crash
