### ISSUE TITLE
Android DrawerLayout, MapView, button with top margin and translucent statusbar glitch.

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#1894] opened 2015-07-15 12:18 UTC
This is a pretty complex issue, but i think i have broken it down pretty well now.

I want to have a MapView with a DrawerLayout with a transparent StatusBar and with a settings button with top margin in a framelayout over the map.

What happens is when i open the drawer, an area at the top, equal to the top button margin is not grayed out until after the drawer is completely opened.

I have an activity with the following layout:

```xml

<!-- A DrawerLayout is intended to be used as the top-level content view using match_parent for both width and height to consume the full space available. -->
<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity"
    >

    <FrameLayout
        android:id="@+id/layout_map"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        >

        <com.mapbox.mapboxgl.views.MapView
            android:id="@+id/map_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />

        <!--
        <View
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#00f"
            />
            -->

        <ImageButton
            android:id="@+id/view_hamburger"
            android:layout_gravity="start|top"
            android:layout_width="48dp"
            android:layout_height="48dp"
            android:layout_marginTop="40dp"
            android:layout_marginStart="40dp"
            android:background="#f00"
            />

    </FrameLayout>

    <android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:headerLayout="@layout/drawer_header"
        app:menu="@menu/drawer"
        />

</android.support.v4.widget.DrawerLayout>

```

And with the theme:

```xml
    <style name="MyStyle parent="@style/Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowTranslucentStatus">true</item>
    </style>
```

**Comment by hallahan** [comment] 2015-07-15 18:20
Hi @erf! My suspicion is that the GL canvas is not aligned right or interacts in a strange way with the transparent status bar. I am aware that Mapbox is working on a Material Design sample app that should encounter this issue.

https://github.com/mapbox/mapbox-gl-native/issues/1856

Could you by any chance provide a screen shot of this problem on your phone?

**Comment by ljbade** [comment] 2015-07-28 06:17
@bleege This may be related to the `TextureView` vs `SurfaceView` issue I mentioned this morning about animated layouts. Will be interesting is `GLSurfaceView` also has the same problem.

**Comment by erf** [comment] 2015-08-06 14:47
![screenshot_2015-08-06-16-43-40](https://cloud.githubusercontent.com/assets/1562523/9114572/da978ddc-3c5a-11e5-8ef3-a77f62c3c785.png)

**Comment by erf** [comment] 2015-08-06 14:51
See example here: https://github.com/erf/mapbox-drawer-glitch

**Comment by bleege** [comment] 2015-08-06 14:59
Thanks for the screenshot and example @erf.  Super helpful!

We're going to be redoing the TestApp's UI to make it more compatible with Material Design / Navigation Drawers.  We'll keep this in mind as it get's built out soon.  The details on this and to follow along please see https://github.com/mapbox/mapbox-gl-native/issues/1856.

**Comment by ljbade** [comment] 2015-09-03 03:07
I have not seen this in our current TestApp which now uses a DrawerLayout.

@erf Do you mind seeing if you can modify the TestApp UI to reproduce this and stick a branch with it up on GitHub?

**Comment by ljbade** [comment] 2015-09-03 05:21
Hmm did some testing with transparent status and navigation bars and I can't find any issue with `MapView`.

It is posible this is a bug in Android or the support libs.

@erf What happens when you replace:
```
<com.mapbox.mapboxgl.views.MapView
            android:id="@+id/map_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />
```
with
```
<View
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#ff0000"
            />
```

Do you get the same no shading while the drawer is opening?

**Comment by ljbade** [comment] 2015-09-04 02:53
We are pushing `TextureView` to `0.2.0` so we should wait to fix this bug then?

@bleege ?

**Comment by bleege** [comment] 2015-09-04 14:23
> Hmm did some testing with transparent status and navigation bars and I can't find any issue with MapView.

@ljbade I'm confused here.  Can you help me better understand why implementing TextView in #2244 would solve an issue [that your testing didn't confirm](https://github.com/mapbox/mapbox-gl-native/issues/1894#issuecomment-137334764)?  We can certainly look to include TextView in `0.1.0` if there's a solid reason why there's a strong belief it'd solve this issue.

@erf Are you still experiencing this issue?

**Comment by ljbade** [comment] 2015-09-05 00:08
@bleege At this stage it is a hunch. Until @erf can provide us an example app that recreates this issue (I wasn't able to on my phone) there is no way to prove this bug is fixed.

Also this bug appears to be related to the Android layout system so I'm thinking it might be a bug in the Android platform, or the layout has just not been set up correctly.

I don't think it has much to do with `MapView` other than `SurfaceView` is a special case when it comes to Android layout as it directly draws to the screen instead of being composited like all other `View`. `TextureView` states it behaves just like a normal `View`.

**Comment by ljbade** [comment] 2015-09-05 00:24
@erf Do you mind recreating the bug against the `TextureView` implementation in https://github.com/mapbox/mapbox-gl-native/tree/2244-texture-view branch?

I would like to know if this is a solution.

**Comment by tobrun** [comment] 2015-09-06 07:32
@ljbade I'm happy to report that I was able to get the correct behaviour using your branch:

![device-2015-09-06-093018](https://cloud.githubusercontent.com/assets/2151639/9703144/f64252ba-5479-11e5-964d-555ef12865eb.png)
![device-2015-09-06-093027](https://cloud.githubusercontent.com/assets/2151639/9703145/f642ee00-5479-11e5-9ef1-f07612fe9061.png)
![device-2015-09-06-093033](https://cloud.githubusercontent.com/assets/2151639/9703146/f64388ce-5479-11e5-932e-4afc61b15921.png)

[Code in forked branch](https://github.com/tobrun/mapbox-gl-native/tree/2244-texture-view)

**Comment by ljbade** [comment] 2015-09-07 07:58
@tobrun Excellent!

Hopefully we can get this fix into `0.1.0`

/cc @bleege

**Comment by bleege** [comment] 2015-09-08 15:39
Very cool.  Thanks for running at this @ljbade @tobrun.  Yep this is important so let's bolt #2244 into `0.1.0` ASAP.  :+1:

**Comment by bleege** [comment] 2015-09-09 21:52
Hooked up TextureView via #2244 and #2293 this afternoon.

I'm going to close this issue for now as it looks like @tobrun @ljbade are confident that it fixes this issue.  That said @erf please feel free to try the latest code out and reopen if you're still seeing issues.

Great job everyone!

**Closed by bleege** 2015-09-09 21:52 UTC
Labels: Android, bug

**Comment by erf** [comment] 2015-09-10 08:43
Sorry for the late reply, I can confirm using mapbox-gl-native commit 532bbd5 
Test repo her: https://github.com/erf/mapbox-drawer-glitch
Great work!

**Comment by bleege** [comment] 2015-09-10 21:52
Awesome!  Thanks @erf!
