### ISSUE TITLE
Custom user location annotation lags when panning

### ISSUE THREAD

**Issue by antontupikov** [mapbox/mapbox-gl-native#6362] opened 2016-09-17 18:15 UTC
I try to customize userLocation view with MGLUserLocationAnnotationView, but it's flickering when panning on iPhone (some lag with tiles). On simulator it look's great.
I'm using iPhone 5 iOS 9.3.5. Anybody knows how to fix it and synchronize moving?

Here is my code:

```
func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView?
{
	if(annotation.isEqual(mapView.userLocation))
	{
		let userLocationView = MGLUserLocationAnnotationView();
		let dotLayer = CALayer();
			
		dotLayer.backgroundColor = UIColor.red.cgColor;
		dotLayer.bounds = CGRect(x: 0, y: 0, width: 14, height: 14);
		dotLayer.cornerRadius = 7;
		
		userLocationView.layer.sublayers = [dotLayer];
		
		return userLocationView;
	}
	
	return nil;
}
```

**Comment by 1ec5** [comment] 2016-09-17 19:19
Duplicate of #5489. If you look closely, it turns out the map actually lags behind the annotation views in most cases.

**Comment by 1ec5** [comment] 2016-09-17 19:19
(Note that, for this particular use case, you can avoid the performance issue by using MGLAnnotationImage with `MGLMapViewDelegate.mapView(_:imageFor:)` instead.)

**Closed by 1ec5** 2016-09-17 19:19 UTC

**Comment by galli-leo** [comment] 2018-04-17 14:59
@1ec5 I tried using that delegate method for the user annotation, unfortunately it doesn't get called. Did something change in the sdk?

**Comment by friedbunny** [comment] 2018-04-17 17:51
@galli-leo `MGLUserLocationAnnotationView` is an annotation _view_ and can’t be used with `MGLMapViewDelegate.mapView(_:imageFor:)`. It’s possible to use an annotation _image_ for anything you like, but you’d have to recreate everything related to user location tracking and updating yourself (which, if you want animation, isn’t something I’d particular recommend).

See [this example](https://www.mapbox.com/ios-sdk/examples/user-location-annotation/) for how to implement a custom user location annotation _view_.

**Comment by galli-leo** [comment] 2018-05-09 13:05
@friedbunny I don't want to use the annotation view, but rather use an image for the user annotation, since it should theoretically not lag (like @1ec5 explained). Unfortunately, I cannot get the delegate to be called for the user location.
