### ISSUE TITLE
New SDK Problems that I generated

### ISSUE THREAD

**Issue by naeemAkee** [mapbox/mapbox-gl-native#15681] opened 2019-09-19 17:37 UTC
Hello Sir,

I'm using Mapbox SDK, and when installing new pods, It's pod will be showing errors.

I change pods and it showing error again and again.

I was using these pods,
pod 'Mapbox-iOS-SDK', '> 5.1'
pod 'MapboxNavigation', '> 0.35.0'
pod 'MapboxGeocoder.swift', '~> 0.11'

I updated pods too
pod 'Mapbox-iOS-SDK', '> 5.3'
pod 'MapboxNavigation', '> 0.37.0'
pod 'MapboxGeocoder.swift', '~> 0.11'

It showing post again and again.

<img width="595" alt="Screenshot 2019-09-19 at 9 55 31 PM" src="https://user-images.githubusercontent.com/43524143/65267197-fe6bce00-db2d-11e9-81f0-da36d0717563.png">

<img width="297" alt="Screenshot 2019-09-19 at 9 55 49 PM" src="https://user-images.githubusercontent.com/43524143/65267201-ff9cfb00-db2d-11e9-9132-22d1b5185aea.png">

**Comment by friedbunny** [comment] 2019-09-19 18:16
Duplicate of https://github.com/mapbox/ios-sdk-examples/issues/357.

**Closed by friedbunny** 2019-09-19 18:16 UTC
