### ISSUE TITLE
Malformed userAgent in telemetry events

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-gl-native#4328] opened 2016-03-15 16:40 UTC
Seeing events come into staging that look like:
`{"event":"appUserTurnstile","created":"2016-03-14T20:46:23.676Z","userId":"{userId}","enabled.telemetry":true,"received":"2016-03-14T20:46:24.359Z","token":"{token}","owner":"bleege","authorization":"{auth}","userAgent":"Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 Mapbox GL/4.0.0/8 MapboxEventsAndroid/4.0.0-SNAPSHOT","version":2,"createdOffset":"+0100"}`

cc @bleege

**Comment by bleege** [comment] 2016-03-15 17:06
Good catch @camilleanne.  I'll fix this.

**Comment by bleege** [comment] 2016-03-18 20:37
Initial inspection seems to indicate a regression due to #4263 and specifically b372bb2d823a397fbfa98317d8c581de93063065.

**Comment by bleege** [comment] 2016-03-18 20:44
Also appears to be related to #2816 and 94c5c2e203efb906e86b8d4d4f416647736b2d76.  `initialise()` may be being called multiple times due to rotation that the [previous solo null check on savedInstanceState](https://github.com/mapbox/mapbox-gl-native/pull/3983/files#diff-886ea28eab2480af0b2b70f0b5c78898R312) was being used to avoid.

/cc @tobrun

**Comment by bleege** [comment] 2016-03-18 21:23
Added an explicit `if (savedInstanceState == null)` check before configuring MapboxEventManager to prevent the multiple initialization and subsequent repeated strings in the User Agent when the device is rotated.  Will merge to `master` and then cherry pick to the `release-ios-3.2.0-android-4.0.0` branch.

**Comment by bleege** [comment] 2016-03-18 21:28
Merged and cherry picked!

<img width="1148" alt="screen shot 2016-03-18 at 5 27 07 pm" src="https://cloud.githubusercontent.com/assets/989928/13892585/bfced250-ed2e-11e5-8978-c918e91105be.png">

/cc @jfirebaugh

**Comment by tobrun** [comment] 2016-03-21 08:10
@bleege 
Changes should be reviewed before going on to the release branch?

While the `savedInstanceState==null` hack solves it for most use-cases it will not for all, some examples:
 - Having multiple maps in multiple activities in one application 
 - User doesn't override onSaveInstanceState and thus not having a savedState when recreating.
 - User shows 2 Mapviews in one screen.

The fix in d33cee7 works around the issue, it doesn't solve the real issue of having a malformed user agent. When you cal initialise on a Singleton it should always produce the same outcome.

**Comment by bleege** [comment] 2016-03-21 17:35
Good catch @tobrun!  I've just added a state check to `userAgent` that will further ensure that it only gets set once.  Can you :eyes: to make sure that it addresses the concerns that you're thinking about?

**Comment by bleege** [comment] 2016-03-21 20:10
Merged to `master` via 16a58e8e499f7d28d43a22dff337edd6f4888744 and cherry picked to `release-ios3.2.0-android-4.0.0`.

![screen shot 2016-03-21 at 3 09 48 pm](https://cloud.githubusercontent.com/assets/989928/13932641/0707059e-ef77-11e5-8f9f-e7159cbff2cf.png)

/cc @jfirebaugh

**Closed by bleege** 2016-03-21 20:10 UTC
Labels: Android, bug, telemetry
