### ISSUE TITLE
Android emulator version 27.1.12 does not render Mapbox

### ISSUE THREAD

**Issue by indrek-koue** [mapbox/mapbox-gl-native#11394] opened 2018-03-06 10:42 UTC
**Platform:Android (emulator version 27.1.12)**
**Mapbox SDK version:5.4.1**

    compileSdkVersion 26
    buildToolsVersion '27.0.3'
    targetSdkVersion 25 
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.1@aar')
    
    Emulator settings: https://www.dropbox.com/s/6unfd14soducuhz/Screenshot%202018-03-06%2012.38.28.png?dl=0
    SDK tools versions: https://www.dropbox.com/s/pjpivrray1n0tvz/Screenshot%202018-03-06%2012.39.03.png?dl=0

### Steps to trigger behavior
 1. setup Mabox in android app
 2. run the app with emulator version 27.1.12
 3. Event log is full of errors and map is not rendered

### Expected behavior
Map is rendered

### Actual behavior
Map is not rendered and Android Studio event log is full of errors:

    Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glUniformMatrix4fv:3400 error 0x502
    Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glUniform1f:3268 error 0x502

**Comment by tobrun** [comment] 2018-03-06 11:10
duplicate of #11266

**Closed by tobrun** 2018-03-06 11:10 UTC
