### ISSUE TITLE
Crash while trying to render in background

### ISSUE THREAD

**Issue by js** [mapbox/mapbox-gl-native#14351] opened 2019-04-05 11:06 UTC
gpus_ReturnNotPermittedKillClient means that rendering is not allowed while in the background iirc, The Mapbox SDK is supposed to handle that, right? eg I'm not supposed to call anything to turn off mapbox rendering when entering the background, right?

Logged on iPhone 6, iPhone 5c, iPhone 5s devices logged so far, all with UIApplicationState == .background.

```
Crashed: com.apple.main-thread
0  libGPUSupportMercury.dylib     0x1caecaf28 gpus_ReturnNotPermittedKillClient
1  AGXGLDriver                    0x1cf6b08e0 (Missing)
2  libGPUSupportMercury.dylib     0x1caecbf04 gpusSubmitDataBuffers
3  AGXGLDriver                    0x1cf6b1e28 (Missing)
4  GLEngine                       0x1d09114e4 gliPresentViewES_Exec
5  OpenGLES                       0x1b1264a8c -[EAGLContext presentRenderbuffer:] + 80
6  GLKit                          0x1bb18f92c -[GLKView _display:] + 308
7  Mapbox                         0x1019e531c MBGLCustomGeometrySourceOptionsFromDictionary(NSDictionary<NSString*, objc_object*>*) + 38052
8  Mapbox                         0x1019e5cb0 MBGLCustomGeometrySourceOptionsFromDictionary(NSDictionary<NSString*, objc_object*>*) + 40504
9  UIKitCore                      0x1db58c9ac -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1620
10 UIKitCore                      0x1db58c5f8 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 672
11 UIKitCore                      0x1db58c5f8 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 672
12 UIKitCore                      0x1db58c5f8 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 672
13 UIKitCore                      0x1db58c5f8 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 672
14 UIKitCore                      0x1db58c5f8 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 672
15 UIKitCore                      0x1db57f7e4 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 156
16 Foundation                     0x1ae8ef30c -[NSISEngine withBehaviors:performModifications:] + 108
17 UIKitCore                      0x1db57f6c8 -[UIView(Hierarchy) _postMovedFromSuperview:] + 784
18 UIKitCore                      0x1db58f3f0 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1740
19 UIKitCore                      0x1db554e98 -[UITransitionView transition:fromView:toView:removeFromView:] + 1520
20 UIKitCore                      0x1dab4d08c -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 1620
21 UIKitCore                      0x1daa5115c __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 2704
22 UIKitCore                      0x1db0f887c _runAfterCACommitDeferredBlocks + 296
23 UIKitCore                      0x1db0e6878 _cleanUpAfterCAFlushAndRunDeferredBlocks + 384
24 UIKitCore                      0x1db115880 _afterCACommitHandler + 132
25 CoreFoundation                 0x1adedd6bc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
26 CoreFoundation                 0x1aded8350 __CFRunLoopDoObservers + 412
27 CoreFoundation                 0x1aded88f0 __CFRunLoopRun + 1264
28 CoreFoundation                 0x1aded80e0 CFRunLoopRunSpecific + 436
29 GraphicsServices               0x1b0151584 GSEventRunModal + 100
30 UIKitCore                      0x1db0ecc00 UIApplicationMain + 212
31 Bysykkel                       0x100cedc64 main (main.swift:15)
32 libdyld.dylib                  0x1ad996bb4 start + 4
```

**Comment by js** [comment] 2019-04-05 12:33
similar:

```
Crashed: com.apple.main-thread
0  libGPUSupportMercury.dylib     0x2ae063e4 gpus_ReturnNotPermittedKillClient
1  libGPUSupportMercury.dylib     0x2ae06ed1 gpusSubmitDataBuffers
2  IMGSGX543RC2GLDriver           0x2e8f13e1 (Missing)
3  GLEngine                       0x2f0530f9 glFinish_Exec
4  GLKit                          0x259add53 -[GLKView _display:] + 290
5  Mapbox                         0xc6a93f MBGLCustomGeometrySourceOptionsFromDictionary(NSDictionary<NSString*, objc_object*>*) + 41526
6  QuartzCore                     0x1f8349f1 CA::Display::DisplayLinkItem::dispatch(unsigned long long) + 112
7  QuartzCore                     0x1f834839 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 608
8  IOMobileFramebuffer            0x1ecd31bf IOMobileFramebufferVsyncNotifyFunc + 88
9  IOKit                          0x1cceca7f IODispatchCalloutFromCFMessage + 236
10 CoreFoundation                 0x1ca44c19 __CFMachPortPerform + 128
11 CoreFoundation                 0x1ca5865f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 34
12 CoreFoundation                 0x1ca57ebd __CFRunLoopDoSource1 + 338
13 CoreFoundation                 0x1ca55eab __CFRunLoopRun + 994
14 CoreFoundation                 0x1c9a91af CFRunLoopRunSpecific + 470
15 CoreFoundation                 0x1c9a8fd1 CFRunLoopRunInMode + 104
16 GraphicsServices               0x1e153b41 GSEventRunModal + 80
17 UIKit                          0x21d31a53 UIApplicationMain + 150
18 Bysykkel                       0xbd4ff main (main.swift:15)
19 libdyld.dylib                  0x1c1964eb start + 2
```

**Comment by julianrex** [comment] 2019-04-05 13:09
Thanks for the report @js - I'm going to mark this as a duplicate of a [known issue](https://github.com/mapbox/mapbox-gl-native/issues/13821) we're tracking.

Can you briefly explain what happens to your view controllers and views as they go into the background? FYI we believe we know what the cause is, but I'd love more test cases.

Thanks

**Closed by julianrex** 2019-04-05 13:09 UTC

**Comment by js** [comment] 2019-04-05 13:15
I haven't been able to reproduce it, only seen the crash reports.

There's nothing special about the view controllers in it self, but the map is embedded as a child view controller if that makes any difference. Looking at one of the traces above, it does look like it's being (re)moved.

**Comment by julianrex** [comment] 2019-04-08 18:26
Thanks for the info @js - this will definitely help.
