### ISSUE TITLE
All polylines flicker when adding adding/removing a polyline (iOS)

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#1797] opened 2015-06-27 15:43 UTC
I see an old issue (#1712) referencing flickering of annotations that's marked as closed for 0.4, but the issue still exists.

Steps to reproduce:
- Add a number of polylines to a map when it's first made
- Add a new polyline or remove an existing one triggered by a user action

http://f.cl.ly/items/0w1e2K2w3N2q3Y2K0V1x/Flicker.m4v

**Comment by kkaefer** [comment] 2015-06-29 10:42
Dupe of https://github.com/mapbox/mapbox-gl-native/issues/1688.

**Closed by kkaefer** 2015-06-29 10:42 UTC
Labels: bug, iOS, performance
