### ISSUE TITLE
Flickering labels when panning

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#7026] opened 2016-11-11 16:52 UTC
Seeing this at a panning operation. What's happening is this:
- Step 1: tiles are loaded and placed
- Step 2: an adjacent tile becomes visible in the viewport, some (but not all!) of the labels in the previously loaded tiles vanish
- Step 3: some of the new tiles complete loading, and some of the labels that disappeared are showing again (see lower left)
- Step 4: all new tiles completed loading, and all labels are back to normal

![untitled1](https://cloud.githubusercontent.com/assets/52399/20222855/38123158-a837-11e6-80fa-c7c8ca2c5bb6.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/52399/20222858/383cf640-a837-11e6-800b-b8c53b7908a8.jpg)
![untitled3](https://cloud.githubusercontent.com/assets/52399/20222856/3837141e-a837-11e6-85ca-1e95d030737f.jpg)
![untitled4](https://cloud.githubusercontent.com/assets/52399/20222857/383ce45c-a837-11e6-8b6a-bcc72b064964.jpg)

**Comment by boundsj** [comment] 2016-11-11 17:07
This seems like it might be related https://github.com/mapbox/mapbox-gl-native/issues/7003

**Comment by kkaefer** [comment] 2016-11-11 17:31
given https://github.com/mapbox/mapbox-gl-native/issues/7003#issuecomment-260009584, I don't think this is related

**Comment by 1ec5** [comment] 2017-01-04 23:59
I think this is the behavior @amyleew and I were seeing in #5946.

**Comment by jfirebaugh** [comment] 2017-01-05 01:31
This is reproducible on the iOS 3.4.0 release branch but not the 3.3.7 tag.

**Comment by jfirebaugh** [comment] 2017-01-05 18:23
From code comment linked above:

```
            // We're not clipping symbol layers, so when we have both parents and children of symbol
            // layers, we drop all children in favor of their parent to avoid duplicate labels.
            // See https://github.com/mapbox/mapbox-gl-native/issues/2482
```

I doubt that adjustments to eviction timing will make this strategy viable. Consider what happens, under the current algorithm, when slowly panning at zN across a region for which you have a parent tile at zN-1 cached, but tiles at zN are getting loaded on demand as you pan. Whenever a new tile a zN is needed, the algorithm notices that it's not immediately available, but that the zN-1 parent tile is. It loads in the parent tile. This causes labels on up to three other zN tiles to disappear, to be replaced with the labels from the parent tile, which might be completely different due to different data selection at zN-1. Then the fourth tile loads, and zN labels are rendered again. Pan a little bit further, and the process repeats.

To me this suggests that a "drop all children" approach isn't viable. If there are renderable symbol layers for the children, we should be preferring those to the symbol layer of the parent.

**Comment by jfirebaugh** [comment] 2017-01-05 22:32
> If there are renderable symbol layers for the children, we should be preferring those to the symbol layer of the parent.

After thinking about this for a while, this alone isn't a viable strategy either. There are at least three cases we need to consider:

* Panning at a fixed zoom level, as described in the previous comment. In this case, we do not want to render parent symbols if there is at least one child tile that was already rendering its labels:
  ```
  +-----------------+
  |                 |
  |                 |
  |                 |
  |--------+        |
  |    * OAK        |
  | * SF   |        |
  |        |        |
  +--------+--------+
  ```
* Zooming in. In this case, we should not render symbols for _any_ of the children covering a particular parent that was already rendering its symbols until _all_ necessary children are available. 
  ```
  +-----------------+
  |        |        |
  |    Sacramento * |
  |        |        |
  |--------+--------|
  |        |        |
  | * San Francisco |
  |        |        |
  +--------+--------+
  ```
  Otherwise, you would see flickering: as soon symbols were rendered for the first child at zN, symbols from the zN-1 parent which cover the remaining zN siblings would disappear, and then reappear when the ideal zN symbols became available.
* Zooming out. In this case, we should continue rendering all already-available child symbols until the ideal parent symbols are available. This likely already works as desired.

All these are based on the assumption that we are unable to relax the requirement that symbol layers cannot be clipped. If we can clip symbol layers, then other options may be feasible.

The general principle is: continue rendering previously-rendered symbol data for a tile until such time as the tile can be fully covered by ideal tiles with ready-to-render symbol data.

**Comment by jfirebaugh** [comment] 2017-01-10 18:17
Tile expiration-related flickering was fixed in #7616. This issue remains to track the flickering issue when panning, which is more difficult to fix.

**Comment by ChrisLoer** [comment] 2017-10-03 17:07
@ansis I think porting `CrossTileSymbolIndex` to gl-native (ongoing work at https://github.com/mapbox/mapbox-gl-native/pull/10103) will fix this problem, right? Or at least exchange this problem for new problems.

**Comment by ChrisLoer** [comment] 2017-10-20 22:42
We should fix this with #10103.

**Comment by ChrisLoer** [comment] 2017-11-02 00:10
> All these are based on the assumption that we are unable to relax the requirement that symbol layers cannot be clipped. If we can clip symbol layers, then other options may be feasible.

This is the assumption that the `CrossTileSymbolIndex` will change -- we won't actually clip symbols, but we'll detect duplicates between tiles and zero out the opacity of all but one version of the symbol.

The way I'm starting to think about this is that a `GeometryTile` can be "partially renderable" (everything but symbols loaded) or "fully renderable" (symbols also loaded). The general principle should be that `update_renderables` should never replace a "fully renderable" tile with a "partially renderable" one. The algorithm should be roughly:

 - If ideal tile is fully renderable, use it
 - If all children are fully renderable, use them
 - If any currently rendered parent is fully renderable, use it (but not a parent from the cache, because cached parents aren't currently displaying and we'd rather find something closer to the ideal zoom if possible)
 - If ideal tile is partially renderable, use it
 - Use as many children are renderable
 - If the tile is still not fully covered, use the nearest renderable parent, including cached parents

The idea here is that while loading "new" areas of the map (e.g. a pan operation), we'll still be able to start showing tiles before symbols load, but when we're zooming in and out on tiles where symbols are already displaying, we'll wait for tiles to fully loaded before we swap them out.

The non-symbol layers should all be clipped based on the set of tiles that are chosen, and the symbol layers should be un-clipped but with duplicate detection + cross-tile collision detection handling symbols from overlapping/mixed-zoom tiles.

I'm playing around with an implementation that does this, but I haven't gotten the tile clipping logic right yet.

**Comment by ChrisLoer** [comment] 2017-11-16 19:30
> I'm playing around with an implementation that does this, but I haven't gotten the tile clipping logic right yet.

As part of #10436, we decided to remove the "two-phase" logic that loads non-symbol buckets before symbol-buckets. This brings gl-native into line with gl-js, and significantly simplifies the tile-loading logic, at the cost of losing the "progressive load" effect when glyphs are taking longer to download than the rest of the map. Combined with the `CrossTileSymbolIndex`, I believe we've fixed this issue.

Rendering mixed-zoom tiles (i.e. a parent tile partially covered by children) is still a tricky case because the overlapping tiles are both fed into the collision index at the same time (meaning you can get cases where symbols from both a parent and a child tile are rendered next to each other for a short time, see https://github.com/mapbox/mapbox-gl-native/issues/10480). However, we now have fade animations for everything, so the worst case should be symbols starting to fade in/out and then reversing course.

**Closed by ChrisLoer** 2017-11-16 19:30 UTC
Labels: bug, Core, text rendering
