### ISSUE TITLE
MGLAnnotationView distorted when rotatesToMatchCamera is true

### ISSUE THREAD

**Issue by JanC** [mapbox/mapbox-gl-native#11756] opened 2018-04-22 19:58 UTC
Hi,
I noticed that when a `MGLAnnotationView` has its `rotatesToMatchCamera` set to `true`, it is quite often distorted when rotated. It's reproducible using the Mapbox example app

**Platform:**
iOS
**Mapbox SDK version:**
3.7.x, 4.0
### Steps to trigger behavior

 1. Clone the [SDK examples](https://github.com/mapbox/ios-sdk-examples)
 2. Set `rotatesToMatchCamera = true` of the `CustomAnnotationView` in the `AnnotationViewExample_Swift` class
 3. Bring the annotation view off screen
 3. Rotate the map while bringing the annotation view on screen

### Expected behavior
The annotation frame is preserved

### Actual behavior
The annotation is streched

Here is a video of the issue
https://www.dropbox.com/s/unjtl8ylkckgx5h/mapbox2.mov?dl=0

Here you can see that the frame size of the annotation view is `10x91` instead of `40x40`
<img width="1552" alt="screen shot 2018-04-22 at 22 00 49" src="https://user-images.githubusercontent.com/707703/39099295-bfbd3ac2-4678-11e8-8ae6-5d88d329f6aa.png">

**Comment by friedbunny** [comment] 2018-05-01 15:41
Thanks for the report — this issue appears to have always existed (since `ios-v3.6.0` and https://github.com/mapbox/mapbox-gl-native/pull/9147) and happens when an annotation is brought back on screen for reuse after the map has been rotated.

https://github.com/mapbox/mapbox-gl-native/pull/9147/files#r123204521 looked promising, but that doesn’t solve the issue, so I’m not sure yet what’s causing this.

Preliminary notes:
- Easiest to reproduce when you zoom into a group of annotations, rotate the map, and then zoom out.
- Happens with any rotate transform on the view annotation, not just our `mapView.direction` rotation.
- Also happens with a 2D rotate transform.
- Reproduction is unaffected by `scalesWithViewingDistance`.

**Comment by friedbunny** [comment] 2018-05-04 18:03
Fixed in #11817, which will be available in `ios-v4.0.1`.

**Closed by friedbunny** 2018-05-04 18:03 UTC
Labels: annotations, bug, iOS
