### ISSUE TITLE
Handling SQLITE_CORRUPT error

### ISSUE THREAD

**Issue by themics** [mapbox/mapbox-gl-native#11768] opened 2018-04-24 06:41 UTC
**Platform: Android**
**Mapbox SDK version: 5.1.0, 6.0.1**

### Steps to trigger behavior

 1. SQLite database file somehow corrupted
 2. Open an app

### Expected behavior

- Corrupted database being deleted(it's a cache, so flushing is fine, isn't it?)
- App runs normally

### Actual behavior

- App crashed at DefaultFileSource thread by uncaught c++ exception

---

Some of our users reported that our app crashes immediately at start, and again and again. Since the app terminated by crash catcher, we don't have stack trace, but `exception.what()` was "database disk image is malformed" at time. I can't say why database is corrupted but I think it should be handled in proper way. Here's our patch:

```diff
diff --git a/platform/default/mbgl/storage/offline_database.cpp b/platform/default/mbgl/storage/offline_database.cpp
index 65c209718..8fba018a4 100644
--- a/platform/default/mbgl/storage/offline_database.cpp
+++ b/platform/default/mbgl/storage/offline_database.cpp
@@ -57,13 +57,16 @@ void OfflineDatabase::ensureSchema() {
             removeExisting();
             connect(mapbox::sqlite::ReadWrite | mapbox::sqlite::Create);
         } catch (mapbox::sqlite::Exception& ex) {
-            if (ex.code != mapbox::sqlite::Exception::Code::CANTOPEN && ex.code != mapbox::sqlite::Exception::Code::NOTADB) {
+            if (ex.code != mapbox::sqlite::Exception::Code::CANTOPEN
+                && ex.code != mapbox::sqlite::Exception::Code::NOTADB
+                && ex.code != mapbox::sqlite::Exception::Code::CORRUPT) {
                 Log::Error(Event::Database, "Unexpected error connecting to database: %s", ex.what());
                 throw;
             }
 
             try {
-                if (ex.code == mapbox::sqlite::Exception::Code::NOTADB) {
+                if (ex.code == mapbox::sqlite::Exception::Code::NOTADB
+                    || ex.code == mapbox::sqlite::Exception::Code::CORRUPT) {
                     removeExisting();
                 }
                 connect(mapbox::sqlite::ReadWrite | mapbox::sqlite::Create);
diff --git a/platform/default/sqlite3.hpp b/platform/default/sqlite3.hpp
index 82e3ceff6..9278f7f03 100644
--- a/platform/default/sqlite3.hpp
+++ b/platform/default/sqlite3.hpp
@@ -22,6 +22,7 @@ enum OpenFlag : int {
 struct Exception : std::runtime_error {
     enum Code : int {
         OK = 0,
+        CORRUPT = 11,
         CANTOPEN = 14,
         NOTADB = 26
     };
```

**Comment by tobrun** [comment] 2018-04-24 07:56
cc @kkaefer

**Comment by jfirebaugh** [comment] 2018-04-24 08:48
Duplicate of #7920.

**Closed by jfirebaugh** 2018-04-24 08:48 UTC
Labels: Android
