### ISSUE TITLE
Marker is not visible sometimes.

### ISSUE THREAD

**Issue by jetadore** [mapbox/mapbox-gl-native#9656] opened 2017-08-01 01:10 UTC
**Platform:** android
**Mapbox SDK version:** ~5.1.1

### Steps to trigger behavior

 1. SDKTestApp -> AnimatedMarkerActivity ->
 2. zoom > THRESHOLD <-> -zoom < THRESHOLD
 3. repeat 2 fast( zoom in zoom out zoom in zoom out...),

### Expected behavior
wanna see marker Low/Hight anytime 

### Actual behavior
Low/High  marker is not visible sometimes

**Comment by jetadore** [comment] 2017-08-01 01:21
![mapbox-marker-issues](https://user-images.githubusercontent.com/20695541/28805184-cb882dc0-769a-11e7-8b59-e277b7079f7b.gif)

**Comment by tobrun** [comment] 2017-08-01 06:40
Thank you for the report, this is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/8799.

**Closed by tobrun** 2017-08-01 06:40 UTC
