### ISSUE TITLE
Annotations blink when adding additional annotations

### ISSUE THREAD

**Issue by fjolnir** [mapbox/mapbox-gl-native#1861] opened 2015-07-09 08:39 UTC
On iOS (9.0 Beta), when I add an annotation to a map, all existing annotations disappear and quickly reappear.

This is reproducible both in the sim & on device: http://d.asgeirsson.is/197YR (Video)

**Comment by kkaefer** [comment] 2015-07-09 13:22
Duplicate of https://github.com/mapbox/mapbox-gl-native/issues/1688

**Closed by kkaefer** 2015-07-09 13:22 UTC
