### ISSUE TITLE
Tiles parsing not working properly since mapbox 5

### ISSUE THREAD

**Issue by fauger** [mapbox/mapbox-gl-native#9411] opened 2017-07-03 14:40 UTC
**Platform:*Android *
**Mapbox SDK version:*5.0 et 5.1*
*Phone* : Motorola RAZR HD - 4.4.2 api19

Hello,

I check mapbox samples on my 'old'  Motorola RAZR HD - (4.4.2 api19).
Tiles parsing is glitching a lot and display only parcel of informations (city name only).
*Note : it works well with mapbox 4.2.2.* I'm wondering if the min opengl version needed is higher since mapbox 5.0 .

![device-2017-07-03-145652](https://user-images.githubusercontent.com/9048558/27797470-1e6f6eac-600e-11e7-8ce9-a4bd26bfb10f.gif)

Below some informations on device : 

`SurfaceFlinger global state:
EGL implementation : 1.4
EGL_QUALCOMM_shared_image EGL_KHR_image EGL_KHR_image_base EGL_QCOM_create_image EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_KHR_fence_sync EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_renderbuffer_image EGL_EXT_create_context_robustness EGL_NV_post_sub_buffer EGL_ANDROID_blob_cache EGL_ANDROID_framebuffer_target EGL_KHR_create_context EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_image_native_buffer EGL_KHR_gl_colorspace 
GLES: Qualcomm, Adreno (TM) 225, OpenGL ES 2.0 V@45.0 AU@  (CL@3869936)
GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_AMD_compressed_3DC_texture GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture `

**Comment by kkaefer** [comment] 2017-07-05 09:09
@fauger, thanks for reporting this issue. We've made a lot of changes for rendering compatibility for things that broke in 5.0 in the recently released version 5.1, which is available at https://www.mapbox.com/android-docs/map-sdk/overview/. Can you please check whether this fixes your issue on this particular device?

**Comment by jfirebaugh** [comment] 2017-07-06 21:04
Duplicate of #9164.

**Closed by jfirebaugh** 2017-07-06 21:04 UTC
Labels: Android
