### ISSUE TITLE
App crash on timeoutAllowedCheck startBackgroundTimeoutTime / setBackgroundLocationServiceTimeoutAllowedDate

### ISSUE THREAD

**Issue by shebtreq** [mapbox/mapbox-gl-native#12341] opened 2018-07-08 13:49 UTC
**Description**
The random crash appearing inside the SDK. It's not happening due to any specific steps. We get same crash but two slightly different crash logs.

- One reported in isssue [12325](https://github.com/mapbox/mapbox-gl-native/issues/12325). which crashes on setting  self.backgroundLocationServiceTimeoutAllowedDate.
- The other crash happens on unrecognised selector sent to timeoutAllowedCheck.

<img width="1248" alt="crashlog timeoutallowedcheck" src="https://user-images.githubusercontent.com/10112432/42420429-30279056-8309-11e8-96a1-58009b606056.png">

**Steps to reproduce**
Run the application on a device
Create a map using mapbox
Use it a little while, zooming in and zooming out
Expected behavior
The map works correctly

**Actual behavior**
The application crashes.

**Configuration**
Mapbox SDK versions: 4.0.2
iOS versions: 11.1.2 but  happen on any version
Device/simulator models: -
Xcode version: 9.2

**Comment by julianrex** [comment] 2018-07-08 18:36
Thanks @shebtreq for the report and adding additional information to https://github.com/mapbox/mapbox-gl-native/issues/12325.

/cc @rclee

**Comment by fabian-guerra** [comment] 2018-07-09 16:42
This is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/12325.

**Closed by fabian-guerra** 2018-07-09 16:42 UTC
Labels: crash, iOS
