### ISSUE TITLE
Map unable to display on activity

### ISSUE THREAD

**Issue by AshrafRah96** [mapbox/mapbox-gl-native#10157] opened 2017-10-07 14:06 UTC
Hi, ive implemented the Mapbox sdk for android and suggested however when i run the application the map is only displayed for a second before is disappears, same for when the user presses the back button to exit the activity.

The code on the activity i placed the map is:

    public class MapsActivity extends AppCompatActivity {

    private MapView mapView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Mapbox access token is configured here. This needs to be called either in your application
        // object or in the same activity which contains the mapview.
        Mapbox.getInstance(this, getString(R.string.access_token));

        // This contains the MapView in XML and needs to be called after the access token is configured.
        setContentView(R.layout.activity_maps);

        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {

                // Customize map with markers, polylines, etc.

            }
        });
    }

    // Add the mapView lifecycle to the activity's lifecycle methods
    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    protected void onStart() {
        super.onStart();
        mapView.onStart();
    }

    @Override
    protected void onStop() {
        super.onStop();
        mapView.onStop();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }
}

The build.gradel:

    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 26
        buildToolsVersion "26.0.0"
        defaultConfig {
            applicationId "com.name.test"
            minSdkVersion 21
            targetSdkVersion 26
            versionCode 1
            versionName "1.0"

            multiDexEnabled true

            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
            exclude group: 'com.android.support', module: 'support-annotations'
        })

        // Mapbox dependencies
        compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar') {
            transitive = true
        }

        // Mapbox Android UI
        compile 'com.mapbox.mapboxsdk:mapbox-android-ui:2.2.5'

        compile 'com.android.support:design:26.+'
        compile 'com.android.support:support-v4:26.+'
        compile 'com.android.support:appcompat-v7:26.+'

        compile 'com.android.support.constraint:constraint-layout:1.0.2'
        compile 'com.jakewharton:butterknife:8.8.1'
        compile 'com.google.android.gms:play-services:11.0.4'
        compile 'com.squareup.okhttp3:okhttp:3.8.1'
        compile 'com.google.android.gms:play-services-maps:11.0.4'
        compile 'com.google.maps.android:android-maps-utils:0.5'

        testCompile 'junit:junit:4.12'
        annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    }

The XML:

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:mapbox="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <com.mapbox.mapboxsdk.maps.MapView
            android:id="@+id/mapView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            mapbox:mapbox_cameraTargetLat="40.73581"
            mapbox:mapbox_cameraTargetLng="-73.99155"
            mapbox:mapbox_cameraZoom="11"
            mapbox:mapbox_styleUrl="mapbox://styles/ashrafrahman/cj8ew25mcafxz2rpnnbbyzl9d"/>

    </RelativeLayout>
![mapbox](https://user-images.githubusercontent.com/29957644/31308574-d943bff0-ab70-11e7-943c-1c4a7de1f37e.png)

### Steps to trigger behavior

 1. Clicking button to view to map activity
 2.
 3.

**Comment by tobrun** [comment] 2017-10-11 13:22
I haven't been able to reproduce this issue with the code shown above. 
Would you be able to add the logs from logcat?

**Comment by AshrafRah96** [comment] 2017-10-11 15:47
Hi @tobrun this is what it shows on my logcat, however i've noticed that i the map can be viewed for a split second when i press the back button to exit the activity.

    W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
    V/MapboxTelemetry: Initializing telemetry.
    V/MapboxTelemetry: Enabling telemetry.
    D/LocationManager: requestLocationUpdates listener=com.mapzen.android.lost.internal.FusionEngine@71aa534 packageName= com.name.test
    I/art: Thread[1,tid=23186,Native,Thread*=0x7f9df7ba00,peer=0x75b2abb0,"main"] recursive attempt to load library "/data/app/com.name.test-2/lib/arm64/libmapbox-gl.so"
    I/art: Thread[1,tid=23186,Native,Thread*=0x7f9df7ba00,peer=0x75b2abb0,"main"] recursive attempt to load library "/data/app/com.name.test-2/lib/arm64/libmapbox-gl.so"
    I/art: Thread[1,tid=23186,Native,Thread*=0x7f9df7ba00,peer=0x75b2abb0,"main"] recursive attempt to load library "/data/app/com.name.test-2/lib/arm64/libmapbox-gl.so"
    V/TelemetryService: Create event.
    V/TelemetryService: Start command event.
    I/Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
    D/ViewRootImpl: changeCanvasOpacity: opaque=true
    D/ViewRootImpl: changeCanvasOpacity: opaque=false

**Comment by zugaldia** [comment] 2017-10-11 17:51
@AshrafRah96 Is this happening in all devices, or under certain configurations?

**Comment by AshrafRah96** [comment] 2017-10-11 22:43
@zugaldia Its happening on all devices, i was testing from Api level 21 to 25

**Comment by AshrafRah96** [comment] 2017-10-19 09:41
@tobrun is there anything else you require from me? or is there a workaround i can use in the meantime whilst this is being fixed? e.g. using an older sdk version

**Comment by tobrun** [comment] 2017-10-19 13:44
I'm still not sure if this an actual issue with our SDK, a workaround that might work would be to use textureView as rendering surface. You can enable it with `mapbox:mapbox_textureMode="true"` or `MapboxMapOptions#setTextureMode(true)`.

**Comment by AshrafRah96** [comment] 2017-10-20 16:34
@tobrun Thanks! yes this has temporarily solved the issue for me to being development again, I look forward to the actual solution 👍

**Comment by tobrun** [comment] 2017-10-23 06:58
If this works, than this is an indication there is another surface blocking the MapView surface. Not sure where that surface is coming from tbh. In any case since we haven't had any other reports from this issue, I'm punting this on being an issue outside of this SDK. Closing, feel free to follow up with additional information.

**Closed by tobrun** 2017-10-23 06:58 UTC
Labels: Android, bug, needs information

**Comment by carlos-mg89** [comment] 2018-02-21 11:03
@tobrun I'm experiencing a similar issue on a Galaxy S6. However, I added the renderTextureMode but it didn't fix the error in my case.

This is my activity.xml file:

`<com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:mapbox_cameraTargetLat="40.4378693"
        mapbox:mapbox_cameraTargetLng="-3.8199625"
        mapbox:mapbox_styleUrl="mapbox://styles/mapbox/outdoors-v10"
        mapbox:mapbox_cameraZoom="4"
        mapbox:mapbox_renderTextureMode="true" />`

And this is my build.graddle:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "me.domain.mypackagedomain"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-cluster-utils:0.1.0'
    implementation "com.mapzen.android:lost:3.0.4"
    compile 'com.google.android.gms:play-services-location:11.8.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}
```

This occurred to me while following the hints to include the cluster marker support: https://github.com/mapbox/mapbox-plugins-android/pull/49

Any ideas?

Thanks in advance!

**Comment by tobrun** [comment] 2018-02-21 11:08
@carlos-mg89 that seems a different issue, please ticket out a separate issue for that.

**Comment by carlos-mg89** [comment] 2018-02-21 11:15
@tobrun you're right! Sorry :)
