### ISSUE TITLE
Crash on Android 4.4.4

### ISSUE THREAD

**Issue by MilkBiscuit** [mapbox/mapbox-gl-native#9878] opened 2017-08-29 03:36 UTC
**Platform:** Android 4.4.4  genymotion simulator
**Mapbox SDK version:** 5.1.2

### Steps to trigger behavior

1.Start Mapbox Demo app
2.Skip for now
3.Click "A simple map view" or "support map fragment" or "Dynamically build a map view"

### Actual behavior
3. Crash

**Comment by MilkBiscuit** [comment] 2017-08-29 03:37
`
08-28 23:33:24.413 6846-6846/com.mapbox.mapboxandroiddemo.debug W/dalvikvm: VFY: unable to resolve static method 28524: Lcom/google/common/collect/ImmutableMap;.copyOf (Ljava/util/Map;)Lcom/google/common/collect/ImmutableMap;
08-28 23:33:24.433 6846-7125/com.mapbox.mapboxandroiddemo.debug E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
08-28 23:33:24.641 6846-6846/com.mapbox.mapboxandroiddemo.debug E/mbgl: {droiddemo.debug}[OpenGL]: eglChooseConfig(NULL) returned error 12288
08-28 23:33:24.641 6846-6846/com.mapbox.mapboxandroiddemo.debug W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4cffb20)
08-28 23:33:24.641 6846-6846/com.mapbox.mapboxandroiddemo.debug E/UncaughtException: java.lang.Error: eglChooseConfig() failed
     at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
     at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:130)
     at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:199)
     at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:194)
     at com.mapbox.mapboxandroiddemo.examples.basics.SimpleMapViewActivity.onCreate(SimpleMapViewActivity.java:31)
     at android.app.Activity.performCreate(Activity.java:5231)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
     at android.app.ActivityThread.access$800(ActivityThread.java:135)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:136)
     at android.app.ActivityThread.main(ActivityThread.java:5001)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
     at dalvik.system.NativeStart.main(Native Method)
08-28 23:33:24.641 6846-6846/com.mapbox.mapboxandroiddemo.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.mapbox.mapboxandroiddemo.debug, PID: 6846
java.lang.Error: eglChooseConfig() failed
  at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
  at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:130)
  at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:199)
  at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:194)
  at com.mapbox.mapboxandroiddemo.examples.basics.SimpleMapViewActivity.onCreate(SimpleMapViewActivity.java:31)
  at android.app.Activity.performCreate(Activity.java:5231)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
  at android.app.ActivityThread.access$800(ActivityThread.java:135)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5001)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
  at dalvik.system.NativeStart.main(Native Method)`

**Comment by tobrun** [comment] 2017-08-29 05:48
Thank you for the report @MilkBiscuit and detailed reproduce instructions. Have you seen this issue only on Genymotion or also on a real device?  Going to close this issue as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/9120. Feel free to add any additional information you have to that issue.

**Closed by tobrun** 2017-08-29 05:48 UTC
