### ISSUE TITLE
Offline tiles are not being rendered if they don't include CJK glyphs

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14271] opened 2019-03-29 13:56 UTC
If the offline region definition excludes CJK glyphs, the downloaded tiles are not being rendered.
Example region:
- Bounds: `[LatLng(26.644858, 118.17), LatLng(26.63, 118.181632)]`
- MinZoom: `14`
- MaxZoom: `17`
- Style: `MAPBOX_STREETS`
- Include ideographs: `false`

The issue is present even if the client-site ideographs generation is enabled.
There are no warning/error logs emitted from core.

Full reproducible example:
```
public class SimpleMapActivity extends AppCompatActivity {

  private MapView mapView;
  private OfflineRegion offlineRegion;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_map_simple);
    mapView = findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);

    LatLngBounds bounds = new LatLngBounds.Builder()
      .include(new LatLng(26.644858, 118.17))
      .include(new LatLng(26.63, 118.181632))
      .build();
    double minZoom = 14;
    double maxZoom = 17;
    float pixelRatio = this.getResources().getDisplayMetrics().density;
    OfflineTilePyramidRegionDefinition definition = new OfflineTilePyramidRegionDefinition(
      Style.MAPBOX_STREETS, bounds, minZoom, maxZoom, pixelRatio, false);

    OfflineManager offlineManager = OfflineManager.getInstance(this);
    byte[] metadata = OfflineUtils.convertRegionName("test_region");
    offlineManager.createOfflineRegion(definition, metadata, new OfflineManager.CreateOfflineRegionCallback() {
      @Override
      public void onCreate(OfflineRegion offlineRegion) {
        SimpleMapActivity.this.offlineRegion = offlineRegion;
        launchDownload();
      }

      @Override
      public void onError(String error) {
      }
    });
  }

  private void launchDownload() {
    offlineRegion.setObserver(new OfflineRegion.OfflineRegionObserver() {
      @Override
      public void onStatusChanged(OfflineRegionStatus status) {
        if (status.isComplete()) {
          offlineRegion.setDownloadState(OfflineRegion.STATE_INACTIVE);
          offlineRegion.setObserver(null);
          Mapbox.setConnected(false);
          Toast.makeText(SimpleMapActivity.this, "Region downloaded", Toast.LENGTH_SHORT).show();
          mapView.getMapAsync(mapboxMap -> mapboxMap.setOfflineRegionDefinition(offlineRegion.getDefinition()));
        }
      }

      @Override
      public void onError(OfflineRegionError error) {
      }

      @Override
      public void mapboxTileCountLimitExceeded(long limit) {
      }
    });

    offlineRegion.setDownloadState(OfflineRegion.STATE_ACTIVE);
  }


  @Override
  protected void onStart() {
    super.onStart();
    mapView.onStart();
  }

  @Override
  protected void onResume() {
    super.onResume();
    mapView.onResume();
  }

  @Override
  protected void onPause() {
    super.onPause();
    mapView.onPause();
  }

  @Override
  protected void onStop() {
    super.onStop();
    mapView.onStop();
  }

  @Override
  public void onLowMemory() {
    super.onLowMemory();
    mapView.onLowMemory();
  }

  @Override
  protected void onDestroy() {
    super.onDestroy();
    mapView.onDestroy();
    Mapbox.setConnected(true);
  }

  @Override
  protected void onSaveInstanceState(Bundle outState) {
    super.onSaveInstanceState(outState);
    mapView.onSaveInstanceState(outState);
  }
}
```

**Comment by LukasPaczos** [comment] 2019-07-10 11:35
Looks like this is not an issue on iOS/macOS - https://github.com/mapbox/mapbox-gl-native/pull/14952, so I retested and here are the results.
#### Without CJK glyphs
```
OfflineTilePyramidRegionDefinition definition = new OfflineTilePyramidRegionDefinition(
  Style.MAPBOX_STREETS, bounds, minZoom, maxZoom, pixelRatio, false);
```
![ezgif com-video-to-gif (55)](https://user-images.githubusercontent.com/16925074/60965320-daae2f80-a315-11e9-8d91-36f0c0c4f8f3.gif)
Only the tiles that do not contain the glyphs seem to be downloaded and rendered correctly. The downloaded region weighs around **8 MB**, but it obviously misses a lot of stuff.

#### Including CJK glyphs
```
OfflineTilePyramidRegionDefinition definition = new OfflineTilePyramidRegionDefinition(
  Style.MAPBOX_STREETS, bounds, minZoom, maxZoom, pixelRatio, true);
```
![ezgif com-video-to-gif (56)](https://user-images.githubusercontent.com/16925074/60965192-82772d80-a315-11e9-85b6-d2c22fcff777.gif)

The download takes a whole lot longer and weighs **60 MB**.  

Our default font family for local CJK glyphs generation is `"sans-serif"`.

Updated example code:
```
public class SimpleMapActivity extends AppCompatActivity {

  private MapView mapView;
  private OfflineRegion offlineRegion;
  private TextView tv;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    Mapbox.setConnected(false);
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_map_simple);
    mapView = findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);

    tv = new TextView(this);
    ((RelativeLayout) mapView.getParent()).addView(tv);

    OfflineManager offlineManager = OfflineManager.getInstance(this);
    offlineManager.listOfflineRegions(new OfflineManager.ListOfflineRegionsCallback() {
      @Override
      public void onList(OfflineRegion[] offlineRegions) {
        if (offlineRegions.length > 0) {
          tv.setText("region present");
          Logger.d("OfflineTest", "region present");
          mapView.getMapAsync(mapboxMap -> mapboxMap.setOfflineRegionDefinition(offlineRegions[0].getDefinition()));
        } else {
          LatLngBounds bounds = new LatLngBounds.Builder()
            .include(new LatLng(26.644858, 118.17))
            .include(new LatLng(26.63, 118.181632))
            .build();
          double minZoom = 14;
          double maxZoom = 17;

          float pixelRatio = SimpleMapActivity.this.getResources().getDisplayMetrics().density;
          OfflineTilePyramidRegionDefinition definition = new OfflineTilePyramidRegionDefinition(
            Style.MAPBOX_STREETS, bounds, minZoom, maxZoom, pixelRatio, true);

          byte[] metadata = OfflineUtils.convertRegionName("test_region");
          offlineManager.createOfflineRegion(definition, metadata, new OfflineManager.CreateOfflineRegionCallback() {
            @Override
            public void onCreate(OfflineRegion offlineRegion) {
              Logger.d("OfflineTest", "starting download");
              SimpleMapActivity.this.offlineRegion = offlineRegion;
              Mapbox.setConnected(null);
              launchDownload();
            }

            @Override
            public void onError(String error) {
            }
          });
        }
      }

      @Override
      public void onError(String error) {
      }
    });
  }

  private void launchDownload() {
    offlineRegion.setObserver(new OfflineRegion.OfflineRegionObserver() {
      @Override
      public void onStatusChanged(OfflineRegionStatus status) {
        tv.setText(status.getCompletedResourceCount() + "/" + status.getRequiredResourceCount());
        Logger.d("OfflineTest", status.getCompletedResourceCount() + "/" + status.getRequiredResourceCount());
        if (status.isComplete()) {
          offlineRegion.setDownloadState(OfflineRegion.STATE_INACTIVE);
          offlineRegion.setObserver(null);
          Mapbox.setConnected(false);
          Toast.makeText(SimpleMapActivity.this, "Region downloaded", Toast.LENGTH_SHORT).show();
          mapView.getMapAsync(mapboxMap -> mapboxMap.setOfflineRegionDefinition(offlineRegion.getDefinition()));
        }
      }

      @Override
      public void onError(OfflineRegionError error) {

      }

      @Override
      public void mapboxTileCountLimitExceeded(long limit) {
      }
    });

    offlineRegion.setDownloadState(OfflineRegion.STATE_ACTIVE);
  }


  @Override
  protected void onStart() {
    super.onStart();
    mapView.onStart();
  }

  @Override
  protected void onResume() {
    super.onResume();
    mapView.onResume();
  }

  @Override
  protected void onPause() {
    super.onPause();
    mapView.onPause();
  }

  @Override
  protected void onStop() {
    super.onStop();
    mapView.onStop();
  }

  @Override
  public void onLowMemory() {
    super.onLowMemory();
    mapView.onLowMemory();
  }

  @Override
  protected void onDestroy() {
    super.onDestroy();
    mapView.onDestroy();
    Mapbox.setConnected(true);
  }

  @Override
  protected void onSaveInstanceState(Bundle outState) {
    super.onSaveInstanceState(outState);
    mapView.onSaveInstanceState(outState);
  }
}
```

/cc @chloekraw @tmpsantos

**Comment by tmpsantos** [comment] 2019-07-10 15:45
@LukasPaczos do we have system fonts enable don this test?

**Comment by LukasPaczos** [comment] 2019-07-10 16:12
> Our default font family for local CJK glyphs generation is "sans-serif".

@tmpsantos is this the answer you're looking for? Otherwise, I'm not sure how to verify that.

**Comment by pozdnyakov** [comment] 2019-07-30 10:36
This issue is caused by the fact that map renderer on Android is not given a non-empty local font family. [This branch](https://github.com/mapbox/mapbox-gl-native/tree/mikhail_offline_tiles_issue) contains the repro example and the naive fix on top.

**Comment by pozdnyakov** [comment] 2019-07-30 10:39
Assigning to @LukasPaczos for the appropriate fix in java.

**Comment by LukasPaczos** [comment] 2019-07-30 11:14
Great find, thanks for debugging this @pozdnyakov!

**Closed** 2019-07-30 11:53 UTC
Labels: Android, high priority
