### ISSUE TITLE
[iOS] MGLOfflinePack downloads do not continue in the background

### ISSUE THREAD

**Issue by felixLam** [mapbox/mapbox-gl-native#10039] opened 2017-09-21 16:45 UTC
Downloads of `MGLOfflinePack` do not continue while the app is in the background. It would be nice if there was a way to specify the url session to use for the download in order to use a backgroundSession which could continue in the background.

**Platform: iOS**
**Mapbox SDK version: 3.6.3**

### Steps to trigger behavior

 1. Create a new `MGLOfflinePack` or `resume` an incomplete one
 2. Leave the app while the pack is downloading
 3. Wait a while
 4. Open the app back up

### Expected behavior

While the app was in the background the downloads continue and the progress changed.

### Actual behavior

The downloads where paused while in the background and the progress is unchanged.

**Comment by jfirebaugh** [comment] 2017-09-21 17:00
Duplicate of #4291.

**Closed by jfirebaugh** 2017-09-21 17:00 UTC
