### ISSUE TITLE
TileJSON bounds render test failure

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#11008] opened 2018-01-24 01:30 UTC
Our map recycler found a failing test: https://61810-16286131-gh.circle-artifacts.com/0/render-tests

Shuffle seed: v0ZfOIRpA4

It looks like the TileJSON bounds aren't properly respected when reusing a map object.

**Comment by asheemmamoowala** [comment] 2018-01-24 02:17
Duplicate of #10880

**Closed by asheemmamoowala** 2018-01-24 02:17 UTC
