### ISSUE TITLE
Crashes on map destroy

### ISSUE THREAD

**Issue by waszqba** [mapbox/mapbox-gl-native#13417] opened 2018-11-20 13:40 UTC
Hi, I have this issue with application crashes on anything that resolves to closing the map view, be it navigating to other page or just minimizing the app and trying to reopen it. AFAIK this is not an issue on the nativescript wrapper side, as I've tried to juggle versions of both the wrapper and the sdk, and the latest version of the wrapper crashes while the second last works fine, with the only difference being sdk version. using trial and error I've come a point where the latest stable version of sdk and locationlayer are 6.3 and 0.7.0 respectively. I've tried using both newer sdk and older locationlayer and vice versa with no luck. Can anyone help me with this issue? I know nativescript is not your main concern as the market is small, but I'd like to make use of the latest fixes and enjoy the smoothness and stability of the mapBox.

### Steps to reproduce

 1. Create nativescript app with nativescript-mapbox
 2. set sdk ver to 6.4.0+ and locationlayer to 0.7.1+ in node_modules/nativescript-mapbox/platforms/android/include.gradle
 3. build app and try to run it on android
 4. go to another view or enter the task manager and reenter the app again
 5. ???
 6. profit?

### Expected behavior
The application should operate normally

### Actual behavior
Application crashes

### Configuration

**Android versions:** 7.1.2, 8.0.0, 9.0.0
**Device models:** nexus 5X, samsung galaxy s6, samsung galaxy note 9
**Mapbox SDK versions:** 6.4+

**Comment by LukasPaczos** [comment] 2018-11-21 10:37
I've no experience with NativeScript, but what you are describing, is often caused by not destroying the map properly. In Android terms, you need to call all lifecycles methods down to `MapView#onDestroy` when the view is destroyed, so when your map is in a fragment, that would be `Fragment#onDestroyView`, not `Fragment#onDestroy` which is pushed from activity, which still survives this change and is not going to be called.

Also, there is a factor of `LocationLayerPlugin`'s lifecycle management, are you calling all of the necessary lifecycle methods? I'd suggested testing out the most recent version, `6.7.1`, which includes the location APIs out of the box. Feel free to check out [the docs](https://www.mapbox.com/android-docs/maps/overview/location-component/).

Please let us know if any of the above is reproducible on the most recent version.

**Comment by waszqba** [comment] 2018-11-22 15:30
I would need to modify the NS plugin made by @EddyVerbruggen and check if it calls all the destruction steps. I will check it tomorrow and let you know if I find something

**Comment by waszqba** [comment] 2019-02-04 06:21
Not much luck, couldn't find anything suspicious

**Comment by tobrun** [comment] 2019-02-04 08:54
@waszqba would you be able to try moving the map configuration to use a TextureView instead of a GLSurfaceView? For other cross platforms projects I have found this setup to work more reliable. You can enable this feature with `MapboxMapOptions#textureMode(true)` or through MapView xml attribute `mapbox_renderTextureMode`

**Comment by tobrun** [comment] 2019-02-14 14:21
Noting here that the fragment freeze issue mentioned above has been fixed with https://github.com/mapbox/mapbox-gl-native/pull/13926

**Closed** 2019-02-23 07:42 UTC
Labels: Android
