### ISSUE TITLE
Mapbox memory leak crashes app when LeakCanary is enabled

### ISSUE THREAD

**Issue by cvance** [mapbox/mapbox-gl-native#8477] opened 2017-03-21 01:08 UTC
Not entirely sure if this is a Mapbox bug (or Mapzen or LeakCanary or a bug in my code) but I believe it is. Either way this seems to stem from a memory leak in Mapbox.

**Platform:** Android
**Mapbox SDK version:** 5.0.0

### Steps to trigger behavior

 1. Add and enable LeakCanary to a project using Mapbox 5.0.0
 2. Open an activity with a mapview, location engine and location engine listener
 3. Background the app

### Expected behavior
LeakCanary catches a memory leak from Mapbox

### Actual behavior
LeakCanary crashes the app. Disabling LeakCanary seems to resolve this crash.

 ```
java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.mapzen.android.lost.internal.FusedLocationProviderService$FusedLocationProviderBinder
                                                                                     at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:45)
                                                                                     at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:79)
                                                                                     at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:65)
                                                                                     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
                                                                                     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
                                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by tobrun** [comment] 2017-03-21 07:33
@cvance can you share the code of the related to mapview, location engine and location engine listener?

**Comment by cvance** [comment] 2017-03-21 18:27
I'm able to reproduce the crash using [this sample activity](https://gist.github.com/cvance/1921263ef51d979b8251cca7159e042a), LeakCanary 1.5 and Mapbox 5.0 on my Nexus 6P (7.1.2beta)

**Comment by Guardiola31337** [comment] 2017-03-24 19:36
[Same issue](https://github.com/mapbox/mapbox-java/issues/401) reported in MAS.

**Comment by Emeritus-DarranKelinske** [comment] 2017-03-28 16:57
I fixed this by removing all location permission from the manifest. There is a suggestion to use tools:remove in the manifest in the upstream bug, but I have not figured that out yet.

**Comment by tobrun** [comment] 2017-04-27 08:51
@cvance, would you be able to retest this with latest SNAPSHOT? I'm thinking that https://github.com/mapbox/mapbox-gl-native/pull/8825 might have resolved the issue (not able to reproduce with that code). 

Installation instructions for SNAPSHOT:

```java
repositories {
    mavenCentral()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0-SNAPSHOT@aar') {
        transitive=true
    }
}
```

**Comment by cvance** [comment] 2017-04-27 21:50
I'm able to reproduce still with 5.1.0-SNAPSHOT

**Comment by tobrun** [comment] 2017-05-04 11:52
In https://github.com/mapbox/mapbox-gl-native/pull/8872, I'm updating LOST to the latest 2.30-SNAPSHOT. This should include the fix that addresses this issue.

**Comment by tobrun** [comment] 2017-06-07 15:25
I'm going to close this issue, so we have more clarity on the milestone related to the LOST issue. I'm opting to track this in https://github.com/mapbox/mapbox-gl-native/pull/9141 as we have a PR tackling that in https://github.com/mapbox/mapbox-gl-native/pull/9142. In this PR we working on resolving the current outstanding upstream issues (https://github.com/mapzen/lost/issues/213). Thank you all for chipping in, continuing this issue in #9142.

**Closed by tobrun** 2017-06-07 15:25 UTC
Labels: Android
