### ISSUE TITLE
iOS Offline Pack limitations ignored

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#8285] opened 2017-03-05 20:09 UTC
While troubleshooting a silent error where the offline packs were downloaded but the map was still grey (can't reproduce after deleting app and starting from scratch), I found an issue with the limits of offline pack downloads.

**Platform:** iOS
**Mapbox SDK version:** 3.5.0-beta*

### Steps to trigger behavior

 1.Download multiple offline packs in different areas. For my test I download six offline packs ~2000 tiles each, double the limit. All were successful.
2. Exit App, Restart App
3. Attempt to download another offline pack in a new area and receive error:
`OfflineDownloadProgressView.offlinePackDidReceiveMaximumAllowedMapboxTiles reached limit of 6000 tiles.`

### Expected behavior

The tile limit should be reassessed after each offline pack completion.

### Actual behavior

Offline packs are only calculated on app start. This is confusing to user assumption of how much they can download without hitting limit, if they try to download more in future after deleting existing offline packs.

Again, I'll stress the need for the SDK to verify the tile count to-be-downloaded (subtracted from existing) is not over the overall limit. It is silly that I have to provide an error 20% of the way through a download: "Oh Sorry, in actuality you cannot download this pack because you have reached your device limit. Please delete this pack, and others to make room and try again."

@1ec5

**Comment by jfirebaugh** [comment] 2017-03-05 23:09
Can you provide a sample app that reproduces the issue?

**Comment by nitrag** [comment] 2017-03-06 01:06
Here's a quick version. Nothing special here, not sure how you aren't able to reproduce. You'll be blown away by the beautiful UI.

https://dl.dropboxusercontent.com/u/16045125/Mapbox%20BugTest_030517.zip

Each area I downloaded was < 6000 tiles. I downloaded five 1000-2000 tile areas, then got bored and went with two large tile counts. No errors. Rebooted app and immediately got a 6000 limit error when downloading an area that was approx. 20 new tiles. 

![save6](https://cloud.githubusercontent.com/assets/197010/23593557/6b14f7b0-01de-11e7-8c34-4d64c478d19a.jpeg)
![save7](https://cloud.githubusercontent.com/assets/197010/23593558/6b15f48a-01de-11e7-9497-6c96fcd78b4f.jpeg)

**Comment by jfirebaugh** [comment] 2017-03-14 00:52
@nitrag I wasn't able to reproduce any issue using your test app. When the limit was reached, "Offline pack “Optional("test")” reached limit of 6000 tiles." was printed to the debug console and the download stopped.

If you're downloading overlapping areas, then you won't necessarily download the sum of tiles shown by the [tile count estimator](https://www.mapbox.com/labs/offline-estimator/) because tiles are shared between regions. Also, the tile count estimates won't match what your test app downloads because the estimator assumes a source that uses a single vector tile source, and your test application creates a region using `satellite-streets-v9`, which uses both vector and raster tiles.

That said, since your test application doesn't download a fixed region, it's possible that there is a bug here which depends on the precise offline pack definitions that are used. If you are still seeing this issue, can you please provide the exact definitions you are using, including bounds, min, and max zoom?

**Comment by nitrag** [comment] 2017-03-14 17:45
Understood. It's going to take me some time to produce a test app for this, I need to release my app to production first. Please standby 1-2 weeks and I'll get back to you on this.

**Comment by jfirebaugh** [comment] 2017-04-18 23:50
Feel free to reopen if you get a chance to investigate further. Closing for now, as we haven't been able to replicate an issue in our tests.

**Closed by jfirebaugh** 2017-04-18 23:50 UTC
Labels: bug, needs information, offline
