### ISSUE TITLE
iOS Crash adding annotations (worker thread)

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1331] opened 2015-04-23 16:51 UTC
EXC_BAD_ACCESS line 70
`auto value = feature->getValue(key);`

```
Worker (27)
#0	0x00000001045212ed in mbgl::SymbolBucket::processFeatures(mbgl::GeometryTileLayer const&, mapbox::util::variant<mbgl::NullExpression, mbgl::EqualsExpression, mbgl::NotEqualsExpression, mbgl::LessThanExpression, mbgl::LessThanEqualsExpression, mbgl::GreaterThanExpression, mbgl::GreaterThanEqualsExpression, mbgl::InExpression, mbgl::NotInExpression, mbgl::AnyExpression, mbgl::AllExpression, mbgl::NoneExpression> const&, mbgl::GlyphStore&, mbgl::Sprite const&)::$_0::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const [inlined] at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/renderer/symbol_bucket.cpp:70
#1	0x00000001045212ed in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > mbgl::util::replaceTokens<mbgl::SymbolBucket::processFeatures(mbgl::GeometryTileLayer const&, mapbox::util::variant<mbgl::NullExpression, mbgl::EqualsExpression, mbgl::NotEqualsExpression, mbgl::LessThanExpression, mbgl::LessThanEqualsExpression, mbgl::GreaterThanExpression, mbgl::GreaterThanEqualsExpression, mbgl::InExpression, mbgl::NotInExpression, mbgl::AnyExpression, mbgl::AllExpression, mbgl::NoneExpression> const&, mbgl::GlyphStore&, mbgl::Sprite const&)::$_0>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mbgl::SymbolBucket::processFeatures(mbgl::GeometryTileLayer const&, mapbox::util::variant<mbgl::NullExpression, mbgl::EqualsExpression, mbgl::NotEqualsExpression, mbgl::LessThanExpression, mbgl::LessThanEqualsExpression, mbgl::GreaterThanExpression, mbgl::GreaterThanEqualsExpression, mbgl::InExpression, mbgl::NotInExpression, mbgl::AnyExpression, mbgl::AllExpression, mbgl::NoneExpression> const&, mbgl::GlyphStore&, mbgl::Sprite const&)::$_0 const&) at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/util/token.hpp:29
#2	0x0000000104520745 in mbgl::SymbolBucket::processFeatures(mbgl::GeometryTileLayer const&, mapbox::util::variant<mbgl::NullExpression, mbgl::EqualsExpression, mbgl::NotEqualsExpression, mbgl::LessThanExpression, mbgl::LessThanEqualsExpression, mbgl::GreaterThanExpression, mbgl::GreaterThanEqualsExpression, mbgl::InExpression, mbgl::NotInExpression, mbgl::AnyExpression, mbgl::AllExpression, mbgl::NoneExpression> const&, mbgl::GlyphStore&, mbgl::Sprite const&) at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/renderer/symbol_bucket.cpp:94
#3	0x00000001045214bb in mbgl::SymbolBucket::addFeatures(mbgl::GeometryTileLayer const&, mapbox::util::variant<mbgl::NullExpression, mbgl::EqualsExpression, mbgl::NotEqualsExpression, mbgl::LessThanExpression, mbgl::LessThanEqualsExpression, mbgl::GreaterThanExpression, mbgl::GreaterThanEqualsExpression, mbgl::InExpression, mbgl::NotInExpression, mbgl::AnyExpression, mbgl::AllExpression, mbgl::NoneExpression> const&, unsigned long, mbgl::SpriteAtlas&, mbgl::Sprite&, mbgl::GlyphAtlas&, mbgl::GlyphStore&) at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/renderer/symbol_bucket.cpp:130
#4	0x00000001045061f9 in mbgl::TileParser::createSymbolBucket(mbgl::GeometryTileLayer const&, mbgl::StyleBucket const&) at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/map/tile_parser.cpp:235
#5	0x0000000104505c58 in mbgl::TileParser::createBucket(mbgl::StyleBucket const&) at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/map/tile_parser.cpp:129
#6	0x0000000104505998 in mbgl::TileParser::parse() at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/map/tile_parser.cpp:71
#7	0x00000001044eea29 in mbgl::LiveTileData::parse() at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/map/live_tile_data.cpp:50
#8	0x00000001045046e5 in mbgl::TileData::reparse(mbgl::Worker&, std::__1::function<void ()>)::$_1::operator()() const [inlined] at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/map/tile_data.cpp:65
#9	0x0000000104504654 in decltype(std::__1::forward<mbgl::TileData::reparse(mbgl::Worker&, std::__1::function<void ()>)::$_1&>(fp)(std::__1::forward<>(fp0))) std::__1::__invoke<mbgl::TileData::reparse(mbgl::Worker&, std::__1::function<void ()>)::$_1&>(mbgl::TileData::reparse(mbgl::Worker&, std::__1::function<void ()>)::$_1&&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:413
#10	0x0000000104504654 in std::__1::__function::__func<mbgl::TileData::reparse(mbgl::Worker&, std::__1::function<void ()>)::$_1, std::__1::allocator<mbgl::TileData::reparse(mbgl::Worker&, std::__1::function<void ()>)::$_1>, void ()>::operator()() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1370
#11	0x0000000104579e4d in std::__1::function<void ()>::operator()() const [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1756
#12	0x0000000104579e44 in mbgl::Worker::workLoop() at /Users/picciano1/Documents/Apps/mapbox-gl-native/src/mbgl/util/worker.cpp:55
#13	0x000000010457cc91 in decltype(*(std::__1::forward<mbgl::Worker*>(fp0)).*fp(std::__1::forward<>(fp1))) std::__1::__invoke<void (mbgl::Worker::*)(), mbgl::Worker*, void>(void (mbgl::Worker::*&&)(), mbgl::Worker*&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:380
#14	0x000000010457cc78 in void std::__1::__thread_execute<void (mbgl::Worker::*)(), mbgl::Worker*, 1ul>(std::__1::tuple<void (mbgl::Worker::*)(), mbgl::Worker*>&, std::__1::__tuple_indices<1ul>) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread:332
#15	0x000000010457cc78 in void* std::__1::__thread_proxy<std::__1::tuple<void (mbgl::Worker::*)(), mbgl::Worker*> >(void*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/thread:342
#16	0x000000010947f268 in _pthread_body ()
#17	0x000000010947f1e5 in _pthread_start ()
#18	0x000000010947d41d in thread_start ()
```

**Comment by incanus** [comment] 2015-04-25 21:35
Dupe of https://github.com/mapbox/mapbox-gl-native/issues/1233.

**Closed by incanus** 2015-04-25 21:35 UTC
