### ISSUE TITLE
Black screen when turning on & off screen rapidly on Android 9.0(P)

### ISSUE THREAD

**Issue by themics** [mapbox/mapbox-gl-native#12561] opened 2018-08-07 11:13 UTC
### Steps to reproduce

 1. Open simple map activity
 2. Turn on & off screen via power button
 3. Repeat rapidly

### Expected behavior

1. No problem

### Actual behavior

1. Map goes black eventually
   - Screen record: [blackout.mp4.zip](https://github.com/mapbox/mapbox-gl-native/files/2266158/blackout.mp4.zip)
   - Screenshot:
      ![6](https://user-images.githubusercontent.com/1905052/43772729-08cb1b40-9a7e-11e8-8e6f-79bf781fe642.jpg)

### Configuration

**Android versions: 9.0.0** 
**Device models: Pixel 2** 
**Mapbox SDK versions: 6.3.0**

**Comment by themics** [comment] 2018-08-08 01:43
Might be a platform(Android) bug. When this happens, `GLSurfaceView.Renderer.onSurfaceChanged()` is not called.

**Comment by LukasPaczos** [comment] 2018-08-14 13:34
I'm seeing the same issue on the Pixel 2 XL running P. This seems to be related to the `GLSurfaceView` as switching to the `TextureView` resolves the issue.

**Comment by LukasPaczos** [comment] 2018-08-14 15:16
Enabling `GLSurfaceView` debug mode doesn't reveal any more clues besides the fact that the viewport is not invalidated which you already mentioned.

**Comment by tobrun** [comment] 2018-10-12 10:01
@LukasPaczos would you be able to retest this issue with the `   glSurfaceView.setPreserveEGLContextOnPause(true);` you recently added? 
Don't own a Android P device to retest

**Comment by LukasPaczos** [comment] 2018-10-22 13:36
@tobrun Unfortunately, https://github.com/mapbox/mapbox-gl-native/pull/12844 doesn't resolve the issue.

**Comment by LukasPaczos** [comment] 2019-04-23 10:18
I'm still able to reproduce on the Pixel 2 XL running Android Pie.

**Comment by tobrun** [comment] 2019-07-09 08:19
Tested on Pixel running Android Q, no able to reproduce. Either this was fixed with the refactor done in https://github.com/mapbox/mapbox-gl-native/pull/14841 or this was a platform bug fixed in Q. @LukasPaczos would you be able to quickly retest this on P?

**Comment by LukasPaczos** [comment] 2019-07-09 08:36
I can still reproduce on P, seems like it might've been fixed in Q.

**Closed** 2020-01-05 10:02 UTC
Labels: Android, archived
