### ISSUE TITLE
[Android][OS5.1.1] Icon Drifting when zoom in

### ISSUE THREAD

**Issue by peerapon01** [mapbox/mapbox-gl-native#9299] opened 2017-06-19 04:51 UTC
**Platform:Android (5.1.1)
**Mapbox SDK version:5.0.2 , 5.0.1

**It happen only on Galaxy S6 Edge (G925F) with OS 5.1.1**

_**I test on many Samsung Devices (6.0 , 7.0 ) and it can't reproduce this**_
### Steps to trigger behavior

 1. move the map 
 2. zoom into marker
 3. then the marker will drifting and can fly to anywhere

I just created an simple MapBoxActivity to reproduce this which is the same way to add Marker in my real application

  
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                mapboxMap.addMarker(new MarkerViewOptions()
                        .position(new LatLng(48.13863, 11.57603))
                        .title("Hello World!")
                        .snippet("Welcome to my marker."));

            }
        });

the video that explain the behavior:
<https://drive.google.com/file/d/0B24mp7L3D1cDMVF5VzRnakN3NFE/view?usp=sharing>
### Expected behavior
map should be move not the marker
### Actual behavior
marker icon drifting

**Comment by Guardiola31337** [comment] 2017-06-19 07:02
@peerapon01 thank you for reaching out and reporting your problem.

Could you add some more information for reproducing the issue? Are you able to provide any logs?
Thanks again!

**Comment by peerapon01** [comment] 2017-06-19 08:53
@Guardiola31337 I look into the #8728 issue. I can confirm that it is the same. 

It can reproduce by touch on the map and move around or zoom in Then, the map will be cannot move but marker can.

the log is here (there is no error):
[log-mapbox.txt](https://github.com/mapbox/mapbox-gl-native/files/1084362/log-mapbox.txt)

**Comment by Guardiola31337** [comment] 2017-06-19 12:59
@peerapon01 Thank you for the detailed info.

Just to confirm that the issue is still present in the latest version, would you mind retesting it using `5.1.0-beta.4` version?

It seems also the same issue as #9254

**Comment by peerapon01** [comment] 2017-06-20 04:12
@Guardiola31337  now I try that and it still happen in `5.1.0-beta.4`

**Comment by tobrun** [comment] 2017-06-20 10:23
closes this as a duplicate of #8728, feel free to report any follow up there. Thank you for the report.

**Closed by tobrun** 2017-06-20 10:23 UTC
Labels: Android
