### ISSUE TITLE
Android Offline Map: Request with response code = 401: Unauthorized

### ISSUE THREAD

**Issue by mrfaa** [mapbox/mapbox-gl-native#5781] opened 2016-07-25 06:19 UTC
Hello Mapbox Team,

i get an error since last week monday (07.18) when downloading an offline map:

Platform: Android
Mapbox SDK version: mapbox-android-sdk:4.1.1@aar

Error:
```
com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request with response code = 401: Unauthorized
com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request could not be executed: Canceled
```

I followd the [example code](https://www.mapbox.com/android-sdk/examples/offline-map/), tried to use a different token and style URLs. The MapboxMap View is working:

`com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).`

The error only occures when downloading an map. The download behavoir worked before that day.

Additional Info: It loads till 1% and then throws the 401 error:
`Percent 0 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx
Percent 0 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx
Percent 0 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx
Percent 0 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx
Percent 1 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx
Percent 1 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx
Percent 1 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx
Percent 1 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx
Percent 1 com.mapbox.mapboxsdk.offline.OfflineRegionStatus@xxxxxxx`

Do you know any advice? Thank you very much in advance!
Fabian

**Comment by tobrun** [comment] 2016-07-26 10:35
@mrfaa 
 - could you add some code how you are setting up the MapboxAccountManager? 
 - are you still using the `setAccessToken` method? 

A `401` indicates that the accesstoken wasn't available for the downloading the offline map.

**Comment by mrfaa** [comment] 2016-07-26 11:12
I initialized the MapboxAccountManager in the onCreate() Method of the MainActivity:

`MapboxAccountManager.start(this, AppConstants.MAPBOX_ACCESS_TOKEN);`

The MapView is working:
`com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request was successful (code = 200).`

The offline download was working before begining of last week.

**Comment by tobrun** [comment] 2016-07-26 12:35
could you try by moving the `MapboxAccountManager.start(this, AppConstants.MAPBOX_ACCESS_TOKEN);` to your application object and test if that resolves your issue?

**Comment by mrfaa** [comment] 2016-07-26 13:27
I did not have an Application Object in my project. The MapBoxAccountManager initialization is done in the applications launch activity:

>  If you are using a custom application object, you can place it in the onCreate() or it can go in your applications launch acitvity onCreate(). In either case you'll need to call the MapboxAccountManager and pass it context and your access token.

**Comment by mrfaa** [comment] 2016-07-26 15:05
Now I tried to use the method (although deprecated)

> offlineManager = OfflineManager.getInstance(this);
   offlineManager.setAccessToken(AppConstants.MAPBOX_ACCESS_TOKEN);

and now it works. That means I am setting the AccessToken twice now. The first time at the MapboxAccountManager and the second time at the offlineManager.

Is that a normal behavior?

Thanks tobrun and Cameron that you helped me with this issue!

**Comment by tobrun** [comment] 2016-07-26 15:27
@mrfaa no normally it shouldn't work like this. Thank you for doing the digging for us! We will need to find the source of the issue and patch this up for next release!

**Comment by cammace** [comment] 2016-07-27 14:43
Hey @mrfaa, glad to hear you got offline working. This is an unusual bug and I'm unable to reproduce using the [demo app offline map example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/offline/SimpleOfflineMapActivity.java) which is only using the `MapboxAccountManager` that's [set in the MainActivity](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java#L73). Could you either post your activities code here or through email (using our previous conversation) so we can better troubleshoot the issue, thanks!

cc: @zugaldia

**Comment by mrfaa** [comment] 2016-07-28 15:43
Hey,
i analysed the issue and got the error! My App hast he following construct:
I’m using an `public abstract class BaseActivity extends Activity `where all the basic code is. All other Activities are extending this abstract BaseActivity. In this BaseActivity i have the methods for downloading the offline map. They look exactly like in the [demo app offline map example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/offline/SimpleOfflineMapActivity.java).

These map download methods are called in the `public class MainActivity extends BaseActivity implements OnMapReadyCallback Activity`.

I initialized the MapBoxAccountManager in the MainActivity, and this was the issue. I had to use the `offlineManager.setAccessToken(AppConstants.MAPBOX_ACCESS_TOKEN)` method to make it run.

I now initialize the MapBoxAccountManager in the onCreate() method in the BaseActivity and now it works without the deprected method setAccessToken :)

**Comment by cammace** [comment] 2016-08-02 03:59
Glad to hear you got the issue resolved. Closing ticket now, feel free to reach out using [Mapbox's contact page](mapbox.com/contact) for future support questions.

**Closed by cammace** 2016-08-02 03:59 UTC
Labels: Android, bug, offline

**Comment by ANSB** [comment] 2016-10-03 19:12
@mrfaa I had also an app with MapboxAccountManager.start in my Activity. In fact, it's not a god idea as if you create an other activity using the map and so on, you'll init 2 or more time the lib and get crashes and HTTP401 error. Really the best is to init the lib at app level. Just create a class extending Application, like that:

```
public class App_Start extends Application
{
    @Override
    public void onCreate()
    {
        super.onCreate();
        String the_mapbox_token = this.getString(R.string.access_token);
        MapboxAccountManager.start(this,the_mapbox_token);
    }
    public void customAppMethod()
    {
        // Custom application method
    }
}
```

Then add it in your manifest at Application level:
```
    <application
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
         android:name="net.ansb_brasil.ansb_so41.App_Start">
```

It's far more easier and avoid a lot of trouble.
