### ISSUE TITLE
iOS API equivalents of -js APIs

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#1169] opened 2015-04-01 08:53 UTC
Hello,

probably more of a question rather than an issue, feel free to close it if it's in the wrong place. 

Been working with the -js client for a while (which is really awesome), and has just started looking at the native iOS client.

Do the native client support altering layers on the fly in a [similar fashion to the -js](https://github.com/mapbox/mapbox-gl-js/blob/617e590c833040407508606b9dbdae2abc3a305d/js/ui/map.js#L466-L567)?

Been looking through [this](https://github.com/mapbox/mapbox-gl-native/blob/2b6afe6a549284a862d0231653d2183d57a5b496/platform/ios/MGLMapView.mm), but can't find anything that seems to resemble the javascript API calls.

**Comment by martinnormark** [comment] 2015-04-01 10:02
I have successfully added layers using a recent version of master using the [style methods](https://github.com/mapbox/mapbox-gl-native/blob/2b6afe6a549284a862d0231653d2183d57a5b496/platform/ios/MGLMapView.mm#L928-L940).

You have to be familiar with the [style spec](https://www.mapbox.com/mapbox-gl-style-spec/) and first add your map ID to [`sources`](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/satellite-v7.json#L46) and then configure the rendering in [`layers`](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/satellite-v7.json#L63).

If you want to do it on the fly within the app, you have the manipulate the NSDictionary fetched using [`getRawStyle`](https://github.com/mapbox/mapbox-gl-native/blob/2b6afe6a549284a862d0231653d2183d57a5b496/platform/ios/MGLMapView.mm#L928) and then call [`setRawStyle`](https://github.com/mapbox/mapbox-gl-native/blob/2b6afe6a549284a862d0231653d2183d57a5b496/platform/ios/MGLMapView.mm#L935) which updates instantly.

That was very ugly, I'm not sure if [`setStyleOrderedLayerNames `](https://github.com/mapbox/mapbox-gl-native/blob/2b6afe6a549284a862d0231653d2183d57a5b496/platform/ios/MGLMapView.mm#L982) will add layers or just re-order? It doesn't seem to be in the header file, though...

You can also take one of the [current styles](https://github.com/mapbox/mapbox-gl-styles/tree/mb-pages/styles) bundled in the repo, change it and use that instead of the named one by calling [`setStyleJSON`](https://github.com/mapbox/mapbox-gl-native/blob/2b6afe6a549284a862d0231653d2183d57a5b496/platform/ios/MGLMapView.mm#L161) or [`setRawStyle`](https://github.com/mapbox/mapbox-gl-native/blob/2b6afe6a549284a862d0231653d2183d57a5b496/platform/ios/MGLMapView.mm#L935) if you load it into an `NSDictionary`.

**Comment by kkaefer** [comment] 2015-04-01 10:14
We'll add an explicit API for altering styles eventually. Duplicate of #837.

**Closed by kkaefer** 2015-04-01 10:14 UTC
