### ISSUE TITLE
stencil mask overflow.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#962] opened 2015-03-07 03:03 UTC
I've seen this message in Xcode debugger spew sometimes. Not sure if this is a real issue or not.

"stencil mask overflow"

**Comment by mb12** [comment] 2015-03-13 22:17
Can you please retag it as iOS? I see this message at times in xcode debugger log when testing with on iPhone 4S running 7.x.

**Comment by ljbade** [comment] 2015-03-17 03:45
@mb12 when creating an issue can you make sure you include info about exactly where/what platform you are seeing the problem on. This will make it easier for us to correctly tag the issue.

**Comment by friedbunny** [comment] 2015-03-22 19:04
I can get `[ERROR] {0}{Map}[OpenGL]: stencil mask overflow` on Hybrid style by zooming into hills (~z15-18) with significant contours.

**Comment by friedbunny** [comment] 2015-03-22 19:51
When this happens you'll see zoom levels stacking on top of each other like this:

[![ios-simulator-screen-shot-mar-22 -2015 -12 45 32-pm](https://cloud.githubusercontent.com/assets/1198851/6771089/a829393e-d091-11e4-9353-a459f96c8084.png)](https://cloud.githubusercontent.com/assets/1198851/6771083/943c0e38-d091-11e4-948e-2e057f592280.png)

And also sometimes long, straight contour-colored lines will flash or, rarely, stay on screen.

**Comment by jfirebaugh** [comment] 2015-03-23 18:45
The "zoom levels stacking" is expected behavior and not related to stencil mask overflow. It happens because both raster and vector tiles are being rendered and the VTs are twice as big.

**Comment by springmeyer** [comment] 2015-05-08 17:43
Seeing this loading satellite layers. The result I see is missing tiles:
![screen shot 2015-05-08 at 10 43 12 am](https://cloud.githubusercontent.com/assets/20300/7542095/16f0acce-f56f-11e4-81e1-92e3bd7a195f.png)

**Comment by friedbunny** [comment] 2015-05-08 18:30
@springmeyer I think that satellite issue is #1423, introduced in the last week or so. The stencil overflow may very well be the underlying cause, I don't know, but it has seemed fairly harmless so far.

**Comment by incanus** [comment] 2015-07-08 00:49
Well, the stencil mask (I believe) is only applicable for vector tiles anyway, since it's related to tessellated drawing. I think we could look higher up the chain and avoid calling into `ClipIDGenerator::update()` (where this log is found) for raster tiles at all.

**Comment by incanus** [comment] 2015-07-08 04:06
I'm curious if something this simple will solve it: 

```diff
diff --git a/src/mbgl/renderer/painter.cpp b/src/mbgl/renderer/painter.cpp
index 742572a..58377c7 100644
--- a/src/mbgl/renderer/painter.cpp
+++ b/src/mbgl/renderer/painter.cpp
@@ -211,7 +211,9 @@ void Painter::render(const Style& style, TransformState state_, TimePoint time)
         // Update all clipping IDs.
         ClipIDGenerator generator;
         for (const auto& source : sources) {
-            generator.update(source->getLoadedTiles());
+            if (source->info.type != SourceType::Raster && source->info.type != SourceType::Video) {
+                generator.update(source->getLoadedTiles());
+            }
             source->updateMatrices(projMatrix, state);
         }
 ```

But I'm worried their might be issues when raster is combined with vector. Need to investigate and understand this more.

**Comment by iceman201** [comment] 2015-12-01 00:01
I got this error as well in my swift coding 
[ERROR] {Map}[OpenGL]: stencil mask overflow

**Comment by RomainQuidet** [comment] 2016-01-13 15:27
I'm still seeing this message when adding 2 raster layers.

**Comment by nimrodgat** [comment] 2016-02-22 18:50
I'm seeing this error when setting a camera with `pitch:85°`, 45° seems to be fine.

**Comment by brewin** [comment] 2016-02-23 18:24
I'm seeing this a lot on Android as well. Vector and raster layers above the basemap flash when interacting with the map. At the same time, I see a flood of `stencil mask overflow` errors. I assume there's some correlation there.

**Comment by andrewcar** [comment] 2016-03-08 02:15
"[ERROR] {Map}[OpenGL]: stencil mask overflow"

I continually get these as I zoom in and out, regardless of whether I have any vector layers visible. I use Mapbox Studio, so I don't have any raster layers to my knowledge. For example, I will go to Europe and zoom in and out (where I have added nothing and removed several standard layers) and continually get the error logs.

**Comment by HeyLookItsBrandon** [comment] 2016-03-25 18:40
I too am seeing these errors flooding in on Android, like @brewin. However, I'm not seeing any of rendering issues mentioned in this issue. We are using 3.x, not the 4.0 snapshot.

**Comment by mikemorris** [comment] 2016-03-25 19:00
We've seen intermittent `stencil mask overflow` errors when rendering in `MapMode::Still` through the Node.js bindings as well, but haven't been able to directly associate them with any specific requests or rendering errors.

**Comment by brewin** [comment] 2016-04-07 17:26
I believe this was fixed with a recent commit (e7ac0f6, ea32ee7, or related). Using the latest 4.1.0-SNAPSHOT, I'm no longer seeing any `stencil mask overflow` errors.

**Comment by picciano** [comment] 2016-05-11 22:54
We've started seeing this error in our app using ios-v3.1.0.

It's pretty devastating to our navigation app, when it occurs, the route line (polyline) disappears. I could redraw the route line, but the app does not get any notification that this occurred.

**Comment by alinapaz** [comment] 2016-10-06 18:26
@tobrun + @kkaefer clarifying we're seeing this issue with some custom styles as well.

**Comment by mollymerp** [comment] 2016-10-12 14:44
May be related to https://github.com/mapbox/mapbox-gl-js/issues/3354

**Comment by andrewcar** [comment] 2016-12-23 14:06
Is there some way to silence these logs until 4.0 is released in Xcode's settings? Maybe in the scheme environment variables [like this?](http://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-8-logs)

**Closed** 2018-11-30 04:35 UTC
Labels: Core, Node.js, archived, bug, iOS, rendering
