### ISSUE TITLE
Android: setting MyLocationEnabled freezes the test app when returning from background

### ISSUE THREAD

**Issue by teroaij** [mapbox/mapbox-gl-native#2993] opened 2015-11-10 12:34 UTC
When receiving mock location updates, the test app freezes easily when pressing the locate me -button.
When MyLocation is not enabled, the app works fine in this case.

Using MapView in an own app with MyLocation disabled, and updating position using and Android location listener also works.

**Comment by tobrun** [comment] 2015-11-10 12:38
@teroaij 
How are you setting up these mock location updates? 
This would help to investigate the issue.

**Comment by teroaij** [comment] 2015-11-10 15:36
I was testing using this app: https://play.google.com/store/apps/details?id=ru.gavrikov.mocklocations. Allow mock locations enabled on Developer settings.

**Comment by tobrun** [comment] 2016-01-19 12:55
@teroaij 
I just retested with the mentioned app and I'm unable to reproduce this issue anymore ([video](https://www.dropbox.com/s/ujbny4t8vuvqct7/device-2016-01-19-134917.mp4?dl=0)).
Closing for now as non-reproducible, reopen if you are able to reproduce again.

**Closed by tobrun** 2016-01-19 12:55 UTC
Labels: Android, bug
