### ISSUE TITLE
app crashed when it updates symbols and changes Map style multiple times

### ISSUE THREAD

**Issue by trunglehuynh** [mapbox/mapbox-gl-native#13878] opened 2019-02-05 23:39 UTC
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG: Build fingerprint: 'motorola/perry_amz_f/perry_f:7.1.1/NPQS26.69-64-2/3:user/release-keys'
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG: Revision: 'p3b0'
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG: ABI: 'arm'
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG: pid: 24317, tid: 24317, name: test.dev  >>> co.test.test.test.dev <<<
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG:     r0 00000000  r1 00000000  r2 00430000  r3 aebb1472
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG:     r4 9589d004  r5 bea28000  r6 bea27da0  r7 bea27c88
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG:     r8 bea28000  r9 b04cf008  sl aec19230  fp aec04400
2019-02-05 15:25:20.106 24600-24600/? A/DEBUG:     ip aec19230  sp bea27c48  lr ae858fb5  pc 90681de4  cpsr 600f0030
2019-02-05 15:25:20.243 24600-24600/? A/DEBUG: backtrace:
2019-02-05 15:25:20.243 24600-24600/? A/DEBUG:     #00 pc 0004dde4  /data/app/co.airspace.ground.detectionapp.dev-2/lib/arm/libmapbox-gl.so
2019-02-05 15:25:20.243 24600-24600/? A/DEBUG:     #01 pc 000ae519  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
2019-02-05 15:25:20.243 24600-24600/? A/DEBUG:     #02 pc 000a9b41  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #03 pc 004065ad  /system/lib/libart.so (art_quick_invoke_stub+232)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #04 pc 000b0dd5  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+136)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #05 pc 001ee7e1  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+200)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #06 pc 001e8d91  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+492)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #07 pc 003fdfe3  /system/lib/libart.so (MterpInvokeVirtual+430)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #08 pc 0009c994  /system/lib/libart.so (ExecuteMterpImpl+14228)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #09 pc 001cc0bb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #10 pc 001d0c23  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #11 pc 001e8d77  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+466)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #12 pc 003fdfe3  /system/lib/libart.so (MterpInvokeVirtual+430)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #13 pc 0009c994  /system/lib/libart.so (ExecuteMterpImpl+14228)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #14 pc 001cc0bb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #15 pc 001d0c23  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #16 pc 001e8d77  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+466)
2019-02-05 15:25:20.244 24600-24600/? A/DEBUG:     #17 pc 003fdfe3  /system/lib/libart.so (MterpInvokeVirtual+430)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #18 pc 0009c994  /system/lib/libart.so (ExecuteMterpImpl+14228)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #19 pc 001cc0bb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #20 pc 001d0c23  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+114)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #21 pc 001e8d77  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+466)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #22 pc 003fdfe3  /system/lib/libart.so (MterpInvokeVirtual+430)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #23 pc 0009c994  /system/lib/libart.so (ExecuteMterpImpl+14228)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #24 pc 001cc0bb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+290)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #25 pc 001d0b8d  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+92)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #26 pc 003f59f7  /system/lib/libart.so (artQuickToInterpreterBridge+706)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #27 pc 000ae593  /system/lib/libart.so (art_quick_to_interpreter_bridge+34)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #28 pc 00532ae9  /system/framework/arm/boot-core-oj.oat (offset 0x51b000) (java.util.LinkedHashMap.addEntry+68)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #29 pc 00531cab  /system/framework/arm/boot-core-oj.oat (offset 0x51b000) (java.util.HashMap.put+310)
2019-02-05 15:25:20.247 24600-24600/? A/DEBUG:     #30 pc 0001d189  /dev/ashmem/dalvik-jit-code-cache (deleted)

### Steps to reproduce

 1. update  SymbolLayer, FillExtrusionLayer, LineLayer and change Map style at multiple times
 2. app just crashes

### Configuration

**Android versions:**  7.1
**Mapbox SDK versions:**  7.1.1

**Comment by tobrun** [comment] 2019-02-06 08:06
dupe of https://github.com/mapbox/mapbox-gl-native/issues/13879

**Closed by tobrun** 2019-02-06 08:06 UTC
