### ISSUE TITLE
[android] Crash when creating + adding a bunch of icons

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#9101] opened 2017-05-24 12:10 UTC
Trying to reproduce #9026 I got a crash when creating + adding a bunch of `Icon`s.

### Steps to trigger behavior

 1. [Sample code](https://github.com/mapbox/mapbox-gl-native/issues/9026#issue-229457645)
 2. After 7th iteration (which means 150 * 7 icons created and added to the map) 
 3. App crashes
 4. It seems there is an overflow somewhere. Spriteatlas?

### logcat

```
                                                                   --------- beginning of crash
05-24 13:44:06.101 17473-26706/com.mapbox.mapboxsdk.testapp A/libc: /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/text/collision_tile.cpp:158: Box mbgl::CollisionTile::getTreeBox(const Point<float> &, const mbgl::CollisionBox &, const float): assertion "box.x1 <= box.x2 && box.y1 <= box.y2" failed
05-24 13:44:06.102 17473-26706/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 26706 (Worker 1)
05-24 13:44:06.203 196-196/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-24 13:44:06.203 196-196/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0/MPA44I/2172151:user/release-keys'
05-24 13:44:06.203 196-196/? A/DEBUG: Revision: '0'
05-24 13:44:06.203 196-196/? A/DEBUG: ABI: 'arm'
05-24 13:44:06.203 196-196/? A/DEBUG: pid: 17473, tid: 26706, name: Worker 1  >>> com.mapbox.mapboxsdk.testapp <<<
05-24 13:44:06.203 196-196/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-24 13:44:06.242 196-196/? A/DEBUG: Abort message: '/Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/text/collision_tile.cpp:158: Box mbgl::CollisionTile::getTreeBox(const Point<float> &, const mbgl::CollisionBox &, const float): assertion "box.x1 <= box.x2 && box.y1 <= box.y2" failed'
05-24 13:44:06.243 196-196/? A/DEBUG:     r0 00000000  r1 00006852  r2 00000006  r3 9c2c0978
05-24 13:44:06.243 196-196/? A/DEBUG:     r4 9c2c0980  r5 9c2c0930  r6 00000000  r7 0000010c
05-24 13:44:06.243 196-196/? A/DEBUG:     r8 9aed0a3c  r9 9aed0a3d  sl 9c1c2000  fp 9fd5f4c9
05-24 13:44:06.243 196-196/? A/DEBUG:     ip 00000006  sp 9c2bef88  lr b6ca4af1  pc b6ca6e54  cpsr 40070010
05-24 13:44:06.262 196-196/? A/DEBUG: backtrace:
05-24 13:44:06.262 196-196/? A/DEBUG:     #00 pc 00041e54  /system/lib/libc.so (tgkill+12)
05-24 13:44:06.262 196-196/? A/DEBUG:     #01 pc 0003faed  /system/lib/libc.so (pthread_kill+32)
05-24 13:44:06.262 196-196/? A/DEBUG:     #02 pc 0001c30f  /system/lib/libc.so (raise+10)
05-24 13:44:06.262 196-196/? A/DEBUG:     #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
05-24 13:44:06.262 196-196/? A/DEBUG:     #04 pc 000174ac  /system/lib/libc.so (abort+4)
05-24 13:44:06.262 196-196/? A/DEBUG:     #05 pc 0001af23  /system/lib/libc.so (__libc_fatal+16)
05-24 13:44:06.262 196-196/? A/DEBUG:     #06 pc 00019549  /system/lib/libc.so (__assert2+20)
05-24 13:44:06.262 196-196/? A/DEBUG:     #07 pc 00410981  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.262 196-196/? A/DEBUG:     #08 pc 00410cf9  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #09 pc 0035471f  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #10 pc 0045f121  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #11 pc 0045fead  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #12 pc 0046051d  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #13 pc 0042aa43  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #14 pc 0042a9c9  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #15 pc 002f5721  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #16 pc 002f58dd  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #17 pc 002f3897  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #18 pc 002f355f  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
05-24 13:44:06.263 196-196/? A/DEBUG:     #19 pc 0003f3ef  /system/lib/libc.so (__pthread_start(void*)+30)
05-24 13:44:06.263 196-196/? A/DEBUG:     #20 pc 00019b43  /system/lib/libc.so (__start_thread+6)
05-24 13:44:07.182 775-27002/? W/ActivityManager:   Force finishing activity com.mapbox.mapboxsdk.testapp/.activity.maplayout.SimpleMapActivity
05-24 13:44:07.183 196-196/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_01
05-24 13:44:07.183 196-196/? E/DEBUG: AM write failed: Broken pipe
```

### Symbolicated Android crash

```
Crash dump is completed

********** Crash dump: **********
Build fingerprint: 'google/hammerhead/hammerhead:6.0/MPA44I/2172151:user/release-keys'
pid: 17473, tid: 26706, name: Worker 1  >>> com.mapbox.mapboxsdk.testapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Stack frame #00 pc 00041e54  /system/lib/libc.so (tgkill+12)
Stack frame #01 pc 0003faed  /system/lib/libc.so (pthread_kill+32)
Stack frame #02 pc 0001c30f  /system/lib/libc.so (raise+10)
Stack frame #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
Stack frame #04 pc 000174ac  /system/lib/libc.so (abort+4)
Stack frame #05 pc 0001af23  /system/lib/libc.so (__libc_fatal+16)
Stack frame #06 pc 00019549  /system/lib/libc.so (__assert2+20)
Stack frame #07 pc 00410981  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::CollisionTile::getTreeBox(mapbox::geometry::point<float> const&, mbgl::CollisionBox const&, float) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/text/collision_tile.cpp:158 (discriminator 3)
Stack frame #08 pc 00410cf9  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::CollisionTile::insertFeature(mbgl::CollisionFeature&, float, bool) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/text/collision_tile.cpp:129 (discriminator 1)
Stack frame #09 pc 0035471f  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::SymbolLayout::place(mbgl::CollisionTile&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/layout/symbol_layout.cpp:509 (discriminator 1)
Stack frame #10 pc 0045f121  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::GeometryTileWorker::attemptPlacement() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/tile/geometry_tile_worker.cpp:404 (discriminator 1)
Stack frame #11 pc 0045fead  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::GeometryTileWorker::symbolDependenciesChanged() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/tile/geometry_tile_worker.cpp:149
Stack frame #12 pc 0046051d  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::GeometryTileWorker::onIconsAvailable(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::SpriteAtlasElement, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, mbgl::SpriteAtlasElement> > >) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/tile/geometry_tile_worker.cpp:223
Stack frame #13 pc 0042aa43  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine void mbgl::MessageImpl<mbgl::GeometryTileWorker, void (mbgl::GeometryTileWorker::*)(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::SpriteAtlasElement, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, mbgl::SpriteAtlasElement> > >), std::__ndk1::tuple<std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::SpriteAtlasElement, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, mbgl::SpriteAtlasElement> > > > >::invoke<0u>(std::__ndk1::integer_sequence<unsigned int, 0u>) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/actor/message.hpp:31 (discriminator 3)
Stack frame #14 pc 0042a9c9  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::MessageImpl<mbgl::GeometryTileWorker, void (mbgl::GeometryTileWorker::*)(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::SpriteAtlasElement, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, mbgl::SpriteAtlasElement> > >), std::__ndk1::tuple<std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::SpriteAtlasElement, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, mbgl::SpriteAtlasElement> > > > >::operator()() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/actor/message.hpp:26
Stack frame #15 pc 002f5721  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::Mailbox::receive() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:48 (discriminator 1)
Stack frame #16 pc 002f58dd  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::Mailbox::maybeReceive(std::__ndk1::weak_ptr<mbgl::Mailbox>) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:57
Stack frame #17 pc 002f3897  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/default/mbgl/util/default_thread_pool.cpp:29
Stack frame #18 pc 002f355f  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine _ZNSt6__ndk18__invokeIZN4mbgl10ThreadPoolC1EjE3$_0JEEEDTclclsr3std6__ndk1E7forwardIT_Efp_Espclsr3std6__ndk1E7forwardIT0_Efp0_EEEOS4_DpOS5_ at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/type_traits:4287 (discriminator 1)
Stack frame #19 pc 0003f3ef  /system/lib/libc.so (__pthread_start(void*)+30)
Stack frame #20 pc 00019b43  /system/lib/libc.so (__start_thread+6)
```

cc @tobrun @ivovandongen

**Comment by jfirebaugh** [comment] 2017-05-24 15:58
Duplicate of #6988.

**Closed by jfirebaugh** 2017-05-24 15:58 UTC
Labels: Android, annotations, crash
