### ISSUE TITLE
SymbolLayer iconSize property not updating immediately

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6903] opened 2016-11-03 20:38 UTC
In the GIF when I click the map, the icon's suppose to change it's size but doesn't immediately change until I zoom in or out. 

![ezgif com-video-to-gif 18](https://cloud.githubusercontent.com/assets/5652865/19984245/dd4b67e8-a1e3-11e6-9ca3-24562fa3ff67.gif)

cc: @mapbox/android

**Comment by 1ec5** [comment] 2016-11-03 22:25
Given that `iconSize` is a layout property, I think this is a duplicate of #6820.

**Comment by jfirebaugh** [comment] 2016-11-03 23:37
Preliminary indications are that this is a separate bug from #6820.

**Closed** 2016-11-11 19:18 UTC
Labels: Android
