### ISSUE TITLE
Location move but MapView is frozen

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#6138] opened 2016-08-24 11:55 UTC
**Platform: Android**
**Mapbox SDK version: 4.2.0-beta.1**
### Steps to trigger behavior
1. Add mapview in a fragment
2. Add marker and zoom in, zoom out, drag the map...
3. Sometimes the map is frozen and not moved while markers are moved around.

![untitled-2](https://cloud.githubusercontent.com/assets/962484/17929673/2f7ff28a-6a2c-11e6-8749-3fc74331a17c.gif)

**Comment by tobrun** [comment] 2016-08-25 08:30
Possible fix with https://mapbox.slack.com/archives/twitter/p1472111378000919, but that is currently on hold for merging.

**Comment by mkv123** [comment] 2016-08-28 16:56
Looks very similar to #6031

**Comment by tobrun** [comment] 2017-01-20 14:29
Resolved with moving touch interaction of Marker to core in #5639 . Closing

**Closed by tobrun** 2017-01-20 14:29 UTC
Labels: Android, bug

**Comment by MrDazt** [comment] 2017-02-10 07:30
Still have this issue on One Plus Two android sdk 4.2.2

**Comment by kingfisherphuoc** [comment] 2017-07-20 09:12
@tobrun I got this issue again with 5.1.0 in SamSung edge device. Is there any problem the new sdk version?

**Comment by tobrun** [comment] 2017-07-20 11:17
we are looking into this issue as part of https://github.com/mapbox/mapbox-gl-native/issues/9441. We haven't been able to reproduce this issue ourselves.

**Comment by HappyDr0id** [comment] 2018-01-18 14:06
I got exactly the same issue : I have a map in a bottomsheet, which is in textureMode because of visual glitches when I drag the bottomsheet, and if I collapse the bottomsheet and expand it back, the map is totally frozen, not responding to user interaction, but MarkersViews are moving okay.
Finally the map is only working correctly on the first display.

I retrieved these logs when it happens :
```
01-18 14:49:19.297 15642-17390/fr.xpdigit.apptourism E/BufferQueueProducer: [SurfaceTexture-0-15642-2] dequeueBuffer: BufferQueue has no connected producer
                                                                            
                                                                            [ 01-18 14:49:19.297 15642:17390 D/         ]
                                                                            NULL == surf->write_back_color_buffer
01-18 14:49:19.300 15642-17390/fr.xpdigit.apptourism E/BufferQueueProducer: [SurfaceTexture-0-15642-2] dequeueBuffer: BufferQueue has no connected producer
                                                                            
                                                                            [ 01-18 14:49:19.301 15642:17390 D/         ]
```

I am using the last MapBox Android SDK Version (5.3.1) and I reproduced the issue on multiple devices : Samsung A3 (2016) SM-1310F on Android 7.0, Samsung S7 on Android 7.0, Moto E on Android 4.4.4, Nexus 5 on Android 6.0.1. But the issue is not reproduced on the Nexus 5X on Android 8.0.

I hope that it will help you to resolve this issue guys.
