### ISSUE TITLE
Seam at tile edge in outdoors

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#889] opened 2015-02-17 03:34 UTC
On my Nexus 7 there is a slight diagonal black seam at the tile boundary:
![device-2015-02-16-193349](https://cloud.githubusercontent.com/assets/1215089/6222972/dae69522-b612-11e4-8633-323940b88e5a.png)

![device-2015-02-16-193400](https://cloud.githubusercontent.com/assets/1215089/6222973/dd68c766-b612-11e4-87cf-c38a57bc2273.png)

/cc @ansis

**Comment by incanus** [comment] 2015-02-27 22:41
Not seeing this in your screenshot @ljbade — are you sure that's not a line in the style itself? Things are rotated the same but that lines that I think you are seeing don't match up to the red line actual tile borders?

**Comment by ljbade** [comment] 2015-03-02 21:15
@incanus you need to open the full resolution image as the downscaling hides it. Look for a dashed line just below the 1000m marker

**Comment by incanus** [comment] 2015-03-02 21:19
Got it, sorry about that. Posting an edited screenshot to be clearer about what the problem is. 

![dae69522-b612-11e4-8633-323940b88e5a](https://cloud.githubusercontent.com/assets/17722/6450739/c3ac2f6c-c0de-11e4-91a9-bab0984f06cd.png)

**Comment by ansis** [comment] 2015-03-26 19:36
I think https://github.com/mapbox/mapbox-gl-native/pull/381 might have fixed this. Can you check?

**Comment by bleege** [comment] 2015-08-19 22:56
@ljbade Is this still an issue or can we close this?

**Comment by ljbade** [comment] 2015-08-26 02:02
Outdoors hasn't been updated to v8?

**Comment by ljbade** [comment] 2015-08-26 02:02
Outdoors hasn't been updated to v8?

**Closed** 2015-08-26 02:02 UTC
Labels: Android, bug
