### ISSUE TITLE
Crash on DefaultFileSource

### ISSUE THREAD

**Issue by matthiaskmt** [mapbox/mapbox-gl-native#14996] opened 2019-06-25 08:16 UTC
### Steps to reproduce

We can't give a clear way how to reproduce. We just found the following crash report in Crashlytics.

### Configuration

**Mapbox SDK versions:** 5.0.0
**iOS/macOS versions:** 12.3.1
**Device/simulator models:** iPhone X

[de.komoot.berlinbikeapp_issue_crash_9a2869d272c04573b2c0eac43775a849_DNE_0_v2.txt](https://github.com/mapbox/mapbox-gl-native/files/3324236/de.komoot.berlinbikeapp_issue_crash_9a2869d272c04573b2c0eac43775a849_DNE_0_v2.txt)

```
# OS Version: 12.3.1 (16F203)
# Device: iPhone X
# RAM Free: 5.8%
# Disk Free: 66.9%

#5. Crashed: com.mapbox.mbgl.DefaultFileSource
0  libobjc.A.dylib                0x195e23530 objc_msgSend + 16
1  CoreFoundation                 0x196b1cf90 -[__NSDictionaryM objectForKey:] + 216
2  Mapbox                         0x105977b40 -[MGLNetworkConfiguration startDownloadEvent:type:] (MGLNetworkConfiguration.m:68)
3  Mapbox                         0x105b8db28 mbgl::HTTPFileSource::request(mbgl::Resource const&, std::__1::function<void (mbgl::Response)>) (http_file_source.mm:229)
4  Mapbox                         0x105ba7468 mbgl::OnlineFileSource::Impl::activateRequest(mbgl::OnlineFileRequest*) (memory:2638)
5  CoreFoundation                 0x196bc3650 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
6  CoreFoundation                 0x196bc3380 __CFRunLoopDoTimer + 864
7  CoreFoundation                 0x196bc2bb4 __CFRunLoopDoTimers + 248
8  CoreFoundation                 0x196bbdb04 __CFRunLoopRun + 1844
9  CoreFoundation                 0x196bbd0b0 CFRunLoopRunSpecific + 436
10 CoreFoundation                 0x196bbde0c CFRunLoopRun + 80
11 Mapbox                         0x105b93da4 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::Thread<std::__1::shared_ptr<mbgl::FileSource> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<mbgl::FileSource> const&&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, unsigned long long&&&)::'lambda'()> >(void*) (thread.hpp:69)
12 libsystem_pthread.dylib        0x1968502c0 _pthread_body + 128
13 libsystem_pthread.dylib        0x196850220 _pthread_start + 44
14 libsystem_pthread.dylib        0x196853cdc thread_start + 4
```

**Comment by friedbunny** [comment] 2019-06-27 00:44
Thanks for the report @matthiaskmt — this is a dupe of https://github.com/mapbox/mapbox-gl-native/issues/14982, so let’s track it there.

**Closed by friedbunny** 2019-06-27 00:44 UTC
Labels: iOS
