### ISSUE TITLE
[MGLMapView updateFromDisplayLink] crash

### ISSUE THREAD

**Issue by YBthebest** [mapbox/mapbox-gl-native#6275] opened 2016-09-07 14:26 UTC
I just got this new crash report on Crashlytics. Seems linked to Mapbox. 
Happened on iPhone 4S, 9.3.1.

```
Crashed: com.apple.main-thread
0  libGPUSupportMercury.dylib     0x30ed82fa gpus_ReturnGuiltyForHardwareRestart
1  libGPUSupportMercury.dylib     0x30ed8dc7 gpusSubmitDataBuffers
2  IMGSGX543GLDriver              0x33c45ebd glrFlushContextToken
3  GLEngine                       0x34254113 gliPresentViewES_Exec
4  GLEngine                       0x34254047 gliPresentViewES
5  OpenGLES                       0x26419ff9 -[EAGLContext presentRenderbuffer:] + 64
6  GLKit                          0x2bc1d55d -[GLKView _display:] + 336
7  infinight                      0x2ad149 -[MGLMapView updateFromDisplayLink] + 2515273
8  QuartzCore                     0x26cea9eb CA::Display::DisplayLinkItem::dispatch() + 106
9  QuartzCore                     0x26cea837 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 594
10 IOMobileFramebuffer            0x263d150b IOMobileFramebufferVsyncNotifyFunc + 86
11 IOKit                          0x248e0759 IODispatchCalloutFromCFMessage + 256
12 CoreFoundation                 0x2463e41d __CFMachPortPerform + 132
13 CoreFoundation                 0x24652623 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 34
14 CoreFoundation                 0x24651d37 __CFRunLoopDoSource1 + 342
15 CoreFoundation                 0x24650149 __CFRunLoopRun + 1688
16 CoreFoundation                 0x2459f2e9 CFRunLoopRunSpecific + 520
17 CoreFoundation                 0x2459f0d5 CFRunLoopRunInMode + 108
18 GraphicsServices               0x25b8fac9 GSEventRunModal + 160
19 UIKit                          0x28c640b9 UIApplicationMain + 144
20 infinight                      0x123321 main (main.m:16)
21 libdispatch.dylib              0x24247873 (Missing)
```

**Comment by 1ec5** [comment] 2016-09-07 19:45
Possibly related: #1509 #5731.

**Comment by jfirebaugh** [comment] 2016-09-21 23:21
Yeah, duplicate of #1509.

**Closed by jfirebaugh** 2016-09-21 23:21 UTC
Labels: crash, iOS
