### ISSUE TITLE
Color incorrect since 3.3.0 iOS

### ISSUE THREAD

**Issue by mrdavidrees** [mapbox/mapbox-gl-native#5793] opened 2016-07-26 00:19 UTC
**Platform:** IOS
**Mapbox SDK version:** 3.3.0

### Steps to trigger behavior

 1. Load up a style, add some sort of background layer that covers all items in the map with a color
 2. Open style in IOS, open style in Mapbox js
 3. Compare two maps

### Expected behavior

Overlay layer should apply to map

### Actual behavior

Overlay layer is not being drawn or has an incorrect draw order in mapbox iOS

Correct style
![screen shot 2016-07-26 at 10 14 19 am](https://cloud.githubusercontent.com/assets/811705/17121888/0f2bfcbe-531a-11e6-8fdc-296c877c5849.png)

iOS screenshot of exact same style
![fullsizerender](https://cloud.githubusercontent.com/assets/811705/17121897/21e5ccfe-531a-11e6-939a-12ffe3ee511a.jpg)

Turning off the overlay creates the same result as the iOS mapbox libary
![screen shot 2016-07-26 at 10 14 36 am](https://cloud.githubusercontent.com/assets/811705/17121912/47e24c7a-531a-11e6-9114-d9936a845a05.png)

**Comment by jfirebaugh** [comment] 2016-08-22 22:15
Duplicate of #5832.

**Closed by jfirebaugh** 2016-08-22 22:15 UTC
