### ISSUE TITLE
Awful Performance on iOS Simulator (Xcode 9)

### ISSUE THREAD

**Issue by jadar** [mapbox/mapbox-gl-native#10199] opened 2017-10-15 02:56 UTC
**Platform:** iOS / Xcode 9
**Mapbox SDK version:** 3.6

### Steps to trigger behavior

 1. Install Mapbox in an new app/project.
 2. Launch on any iOS Simulator. (I used iPhone X.)
 3. Observe impossibly slow scrolling, 100% CPU usage, and a laptop that sounds like a fighter jet.

### Expected behavior

Smooth map scrolling, zooming, interaction, etc.

### Actual behavior

Very slow map interaction.

<img width="1027" alt="screen shot 2017-10-14 at 8 56 54 pm" src="https://user-images.githubusercontent.com/3793928/31581189-6d5490d4-b12a-11e7-938a-50c8be353ede.png">

**Comment by jfirebaugh** [comment] 2017-10-15 04:52
Duplicate of #9959.

**Closed by jfirebaugh** 2017-10-15 04:52 UTC
