### ISSUE TITLE
Marker animation stops working on Android SDK version 5.x.x

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#8989] opened 2017-05-13 10:48 UTC
In version 4.x of the Android SDK, it was possible to animate a marker (rotating) in this way. Since 5.x, animation doesn't start anymore...

```
spawnmarker = map.addMarker(new MarkerViewOptions()
                        .position(new LatLng(result.Lat + 0.0003, result.Lon + 0.0003))
                        .title(result.Name)
                        .snippet("spawnitem")
                        .icon(icon), new MarkerViewManager.OnMarkerViewAddedListener() {
                            @Override
                            public void onViewAdded(@NonNull MarkerView markerView) {

                                Toast.makeText(getApplicationContext(), "nothing", Toast.LENGTH_SHORT).show();

                                if (markerView.getSnippet().equals("spawnitem")) {

                                    View view = map.getMarkerViewManager().getView(spawnmarker);

                                    ObjectAnimator markerAnimator = ObjectAnimator.ofFloat(view,
                                            "rotation", 0f, 360f);
                                    markerAnimator.setDuration(3000);
                                    markerAnimator.setRepeatCount(ValueAnimator.INFINITE);
                                    markerAnimator.start();

                                }

                            }
                        }
                    );
```

**Comment by tobrun** [comment] 2017-05-22 12:04
Thank for the report @nijs9, I debugged this to OnViewAdded not being invoked. Root cause will be https://github.com/mapbox/mapbox-gl-native/issues/8799. Closing as a duplicate, this issue was linked for visibility.

**Closed by tobrun** 2017-05-22 12:04 UTC
Labels: Android
