### ISSUE TITLE
MapView frozen when having two Fragments with a Map on top of each other

### ISSUE THREAD

**Issue by vanniktech** [mapbox/mapbox-gl-native#14980] opened 2019-06-21 11:47 UTC
### Steps to reproduce

 1. Fill in a mapbox api key and style into the sample application
 2. Run the application on a Samsung S6 or OnePlus 5 (those are the devices we have here that demonstrate the problem)
 3. Scroll around on the first map everything is working
 4. Push the button to display a new fragment

### Expected behavior

I'd expect to be able to scroll and change the map projection without any problems.

### Actual behavior

I can't scroll at all.

It seems like having two fragments on top of each other with each one having a map isn't really supported. This is a super minimal app demonstrating the problem. In our real application we have a fragment in between.

- Fragment A showing a map
- Fragment B being shown
- Fragment C being conditionally & partially included as part of Fragment B

Here's a video demonstrating the problem: [![Watch the video](http://cdn-b-east.streamable.com/image/1grmx.jpg?token=MtjVXFWAzJzXYwWYlmPEKw&expires=1561124400)](https://streamable.com/1grmx)

I've talked to @Guardiola31337 and he asked me to provide you with a sample app: [mapbox-fragment-glitch.zip](https://github.com/mapbox/mapbox-gl-native/files/3314282/mapbox-fragment-glitch.zip)

**Comment by LukasPaczos** [comment] 2019-06-21 13:20
Hey @vanniktech, I wasn't able to reproduce the issue using the provided project on neither Pixel 2 XL nor an emulator:
![ezgif com-video-to-gif (51)](https://user-images.githubusercontent.com/16925074/59924793-cd98d180-9436-11e9-83ea-71ebd5ad8b63.gif)

In general, our default `MapView` implementation uses a `GLSurfaceView` to render its content. Per docs, multiple surfaces cannot overlap because each of them "punctures a hole" in the view hierarchy. If they do overlap, it can generate all sorts of issues. You can use a `TextureView` implementation instead, which should cause no issues if stacked on top of each other:
```
<com.mapbox.mapboxsdk.maps.MapView
    android:id="@+id/mapView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:mapbox_renderTextureMode="true" />
``` 
or use [`MapboxMapOptions#textureMode`](https://docs.mapbox.com/android/api/map-sdk/8.0.1/com/mapbox/mapboxsdk/maps/MapboxMapOptions.html#textureMode-boolean-).

One additional note: `MapView#onDestroy` should be called from the fragment's `#onDestroyView` method, [see the documentation](https://docs.mapbox.com/android/api/map-sdk/8.0.1/com/mapbox/mapboxsdk/maps/MapView.html#onDestroy--).

Let us know if above helps.

**Comment by vanniktech** [comment] 2019-06-21 13:31
That's true. I wasn't able to reproduce it on a Pixel or emulator either. It's very specific to some devices.

Huh. So I changed the `#onDestroyView` thing and that didn't fix anything. However, when changing the texture mode it does work. 

Are there any drawbacks when using texture mode instead of `GLSurfaceView`?

**Comment by LukasPaczos** [comment] 2019-06-21 13:53
A tiny bit of overhead. In general, it shouldn't be too impactful and we recommend the switch if it unblocks a use-case. You can read up more about the differences [here](https://source.android.com/devices/graphics/architecture.html#high_level).

I'm going to close this one as not actionable from our perspective.

**Closed by LukasPaczos** 2019-06-21 13:53 UTC
Labels: Android, bug
