### ISSUE TITLE
Marker ID might change after a map reload

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3382] opened 2015-12-22 18:40 UTC
The default `OnMapChangedListener` reloads the markers after a `DID_FINISH_LOADING_MAP` change event. This reload can produce a change of IDs in the markers because they're effectively removed and re-added:

```
if (annotation instanceof Marker) {
    Marker marker = (Marker) annotation;
    mNativeMapView.removeAnnotation(annotation.getId());
    long newId = mNativeMapView.addMarker(marker);
    marker.setId(newId);
}
```

We shouldn't do this because the `hashCode` of a marker depends on its `id`, and this change of `id` can bring unintended consequences. For example, markers won't work well as keys in a `HashMap`. If this is necessary, this must be documented, or a different `hashCode` method unaffected by `id` changes could be implemented.

Possibly related: https://github.com/mapbox/mapbox-gl-native/issues/1488 which was fixed in https://github.com/mapbox/mapbox-gl-native/pull/3049.

**Comment by 1ec5** [comment] 2015-12-22 18:44
In the iOS SDK, MGLMapView originally mapped annotation model objects to their IDs, but we reversed it in #3261 so that IDs are mapped to the objects (along with some metadata). The primary reason is that mbgl considers the ID to be the unique identifier of an annotation, not the annotation model object (which mbgl never sees).

**Comment by tnightingale** [comment] 2016-01-21 01:53
As an example, I ran into this when implementing a MapView.OnInfoWindowClickListener for https://github.com/tnightingale/Mapbox/tree/geojson.

Markers were being added before the DID_FINISH_LOADING_MAP event. The marker ids were then used to index data associated with each marker (in this case GeoJSON Feature 'properties'). However when the InfoWindowClickListener fired none of the marker ids matched. I figured out that I needed to wait until DID_FINISH_LOADING_MAP before creating the markers but I assume that there are still other events that could trigger a reset of all marker ids?

**Comment by jiajiahan** [comment] 2016-02-03 20:41
I also ran into this problem recently and spent half a day to find out this issue here.

My use case is like this:
I have an object of data that is associated with each marker. When a marker is clicked, I show some info related to the marker on the bottom of the screen rather than the normal info window. So I kept a mapping between the marker ids and my object list. The list of objects is persisted during screen reloads (rotation, switch, etc). When the view is redrawn, I add new markers for each object during map initialization. So normally the info will be shown the first time when the data were fetched by some user interaction. However, after a screen rotation, the marker click will not find any data associated with that id.

After seeing this issue, I added a workaround to add a OnMapchangedListener in which I added the markers. It took a while to find the root cause and really confusing to debug. I think the marker id should be fixed after creation or this behavior should be well documented in all the addMarker{s} methods.

**Comment by tobrun** [comment] 2016-03-08 15:00
Doing some tests around this issue:

When creating the map and adding 3 markers:
```java
Adding marker with id : 0
Adding marker with id : 1
Adding marker with id : 2
```

After an orientation change:
```
Restoring marker with id : 0
Restoring marker with id : 1
Restoring marker with id : 2
```

**Comment by tobrun** [comment] 2016-03-08 15:07
Retested the use case from @tnightingale and this one is resolved for the same reason as above:

When creating the map and adding 3 markers:

```java
Adding marker with id : 0
Adding marker with id : 1
Adding marker with id : 2
```

Clicking them in the order as they were added:

```java
Click on marker with id : 0
Click on marker with id : 1
Click on marker with id : 2
```

**Comment by tobrun** [comment] 2016-03-08 15:11
@jiajiahan with the upcoming release for `4.0.0` you will be able to extend `MarkerOptions` and `Marker`. For an example see this [Activity](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/annotations) and the [child classes](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/annotations) of Marker and MarkerOptions.

**Comment by tobrun** [comment] 2016-03-08 15:11
The initial issue is resolved and nothing actionable left to do here. Closing

**Closed by tobrun** 2016-03-08 15:11 UTC
Labels: Android

**Comment by zugaldia** [comment] 2016-03-08 15:43
Yay!

**Comment by vcaen** [comment] 2016-04-16 15:52
@jiajiahan Indeed, Marker id us still changing whenever I move the map so I can't rely on it to map my data to it.

**Comment by tobrun** [comment] 2016-04-18 08:43
@vcaen I believe your issue is related to https://github.com/mapbox/mapbox-gl-native/issues/4553.
You can work around this issue for now using the [SNAPSHOT](https://www.mapbox.com/android-sdk/#gradle). Reach out if you have any other questions.

**Comment by vcaen** [comment] 2016-04-18 16:09
@tobrun Thanks, that's indeed the same issue. By the way, I found a workaround by using the Marker's LngLat (`marker.getPosition()`) since there is few chances that two markers have the same position.
