### ISSUE TITLE
Main thread blocked for several seconds when zooming out

### ISSUE THREAD

**Issue by harri121** [mapbox/mapbox-gl-native#4777] opened 2016-04-21 12:52 UTC
Hello,
can you tell me why the MGLMapView is blocking the main thread for at least 2-3 seconds when zooming out at level 4-6? This gives a really bad user experience. I use a custom map style and userTrackingMode = .Follow

**Comment by tobrun** [comment] 2016-04-21 13:03
Linking Android related ones: https://github.com/mapbox/mapbox-gl-native/issues/4652 and https://github.com/mapbox/mapbox-gl-native/issues/4692. 
I noticed this behaviour myself this morning.

**Comment by harri121** [comment] 2016-04-21 13:34
How can this bug be still in a production build? Why are the tiles not loaded/parsed entirely on a background thread? This seems to be such an obvious error.

**Comment by tobrun** [comment] 2016-04-21 13:39
The behaviour I noticed is on master not in a stable binary build.

**Comment by 1ec5** [comment] 2016-04-21 14:31
@harri121, what version of the iOS SDK are you running? Have you downloaded any offline packs?

**Comment by harri121** [comment] 2016-04-21 14:33
@1ec5 I tried it with v 3.2.0 and v 3.2.1 both showed the lagging when zooming out or panning to a new area. I didn't download any offline packs.

**Comment by 1ec5** [comment] 2016-04-21 14:48
I’m unable to reproduce the issue in a test application. Can you provide a sample of your application while it’s hanging (preferably in a gist)? Thanks!

**Comment by harri121** [comment] 2016-04-21 15:06
Sorry, I have no experience yet with gist. I attached a sample project. You have to enter an access token in the info.plist. To reproduce the bug quickly zoom out. [MapLag.zip](https://github.com/mapbox/mapbox-gl-native/files/230170/MapLag.zip)

**Comment by 1ec5** [comment] 2016-04-21 15:44
Thank you, I can reproduce the issue you describe. The problem definitely seems to be more pronounced in this part of Europe. Perhaps it’s due to the larger tile sizes from more mountainous terrain or scragglier borders. I see a lot of this on the background thread:

```
Thread 13#0	0x000000010b922de6 in __psynch_mutexwait ()
#1	0x000000010b8e7e4a in _pthread_mutex_lock_wait ()
#2	0x000000010b8e55f5 in _pthread_mutex_lock_slow ()
#3	0x000000010a235aef in std::__1::recursive_mutex::lock() ()
#4	0x0000000107745bf6 in _ZN4mbgl4util7RunLoop7InvokerIZNS0_6ThreadINS_6Worker4ImplEE4bindIMS5_FvPNS_10TileWorkerENSt3__16vectorINSA_10unique_ptrINS_10StyleLayerENSA_14default_deleteISD_EEEENSA_9allocatorISG_EEEENSC_INS_12GeometryTileENSE_ISK_EEEENS_15PlacementConfigENSA_8functionIFvN6mapbox4util7variantIJNS_22TileParseResultBucketsESt13exception_ptrEEEEEEEEEDaT_EUlDpOT_E_NSA_5tupleIJS9_SJ_SM_SN_ZNS1_18invokeWithCallbackIS14_RSW_JS9_SJ_SM_RSN_EEENSC_INS_11WorkRequestENSE_IS19_EEEEOS10_OT0_DpOT1_EUlS13_E_EEEE6cancelEv ()
#5	0x00000001077422b6 in mbgl::WorkRequest::~WorkRequest() ()
#6	0x000000010773206c in mbgl::VectorTileData::~VectorTileData() ()
#7	0x000000010a2356da in std::__1::__shared_weak_count::__release_shared() ()
#8	0x00000001076ea7d9 in mbgl::Source::update(mbgl::StyleUpdateParameters const&) ()
#9	0x000000010770d11b in mbgl::Style::update(mbgl::TransformState const&, mbgl::gl::TexturePool&) ()
#10	0x00000001076b74ec in mbgl::MapContext::update() ()
```

On master, we’ve recently moved this work to the main thread, so this is what it looks like:

```
Thread 1Queue : com.apple.main-thread (serial)
#0	0x000000010e042de6 in __psynch_mutexwait ()
#1	0x000000010e007e4a in _pthread_mutex_lock_wait ()
#2	0x000000010e0055f5 in _pthread_mutex_lock_slow ()
#3	0x000000010d7b1aef in std::__1::recursive_mutex::lock() ()
#4	0x0000000109e7a13f in std::__1::lock_guard<std::__1::recursive_mutex>::lock_guard(std::__1::recursive_mutex&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__mutex_base:83
#5	0x0000000109e7a130 in std::__1::lock_guard<std::__1::recursive_mutex>::lock_guard(std::__1::recursive_mutex&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__mutex_base:83
#6	0x0000000109e7a124 in _ZN4mbgl4util7RunLoop7InvokerIZNS0_6ThreadINS_6Worker4ImplEE4bindIMS5_FvPNS_10TileWorkerENSt3__16vectorINSA_10unique_ptrINS_10StyleLayerENSA_14default_deleteISD_EEEENSA_9allocatorISG_EEEENSC_INS_12GeometryTileENSE_ISK_EEEENS_15PlacementConfigENSA_8functionIFvN6mapbox4util7variantIJNS_22TileParseResultBucketsESt13exception_ptrEEEEEEEEEDaT_EUlDpOT_E_NSA_5tupleIJS9_SJ_SM_SN_ZNS1_18invokeWithCallbackIS14_RSW_JS9_SJ_SM_RSN_EEENSC_INS_12AsyncRequestENSE_IS19_EEEEOS10_OT0_DpOT1_EUlS13_E_EEEE6cancelEv at /path/to/mapbox-gl-native-3/platform/ios/../../include/mbgl/util/run_loop.hpp:141
#7	0x0000000109e6a0be in mbgl::WorkRequest::~WorkRequest() at /path/to/mapbox-gl-native-3/src/mbgl/util/work_request.cpp:14
#8	0x0000000109e6a153 in mbgl::WorkRequest::~WorkRequest() at /path/to/mapbox-gl-native-3/src/mbgl/util/work_request.cpp:13
#9	0x0000000109e6a1aa in mbgl::WorkRequest::~WorkRequest() at /path/to/mapbox-gl-native-3/src/mbgl/util/work_request.cpp:13
#10	0x0000000109e08f19 in std::__1::default_delete<mbgl::AsyncRequest>::operator()(mbgl::AsyncRequest*) const [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2516
#11	0x0000000109e08ef1 in std::__1::unique_ptr<mbgl::AsyncRequest, std::__1::default_delete<mbgl::AsyncRequest> >::reset(mbgl::AsyncRequest*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2715
#12	0x0000000109e08e70 in mbgl::VectorTileData::cancel() at /path/to/mapbox-gl-native-3/src/mbgl/tile/vector_tile_data.cpp:180
#13	0x0000000109e0759d in mbgl::VectorTileData::~VectorTileData() at /path/to/mapbox-gl-native-3/src/mbgl/tile/vector_tile_data.cpp:91
#14	0x0000000109e07c53 in mbgl::VectorTileData::~VectorTileData() at /path/to/mapbox-gl-native-3/src/mbgl/tile/vector_tile_data.cpp:90
#15	0x0000000109ccb392 in std::__1::__shared_ptr_emplace<mbgl::VectorTileData, std::__1::allocator<mbgl::VectorTileData> >::__on_zero_shared() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3829
#16	0x000000010d7b16da in std::__1::__shared_weak_count::__release_shared() ()
#17	0x0000000109cc538a in std::__1::shared_ptr<mbgl::TileData>::~shared_ptr() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4567
#18	0x0000000109cc5326 in mbgl::util::ptr<mbgl::TileData>::~ptr() at /path/to/mapbox-gl-native-3/platform/ios/../../include/mbgl/util/ptr.hpp:11
#19	0x0000000109cc27a3 in mbgl::util::ptr<mbgl::TileData>::~ptr() at /path/to/mapbox-gl-native-3/platform/ios/../../include/mbgl/util/ptr.hpp:11
#20	0x0000000109cc880c in mbgl::Tile::~Tile() at /path/to/mapbox-gl-native-3/platform/ios/../../src/mbgl/tile/tile.hpp:15
#21	0x0000000109cc87b3 in mbgl::Tile::~Tile() at /path/to/mapbox-gl-native-3/platform/ios/../../src/mbgl/tile/tile.hpp:15
#22	0x0000000109cc4a93 in std::__1::default_delete<mbgl::Tile>::operator()(mbgl::Tile*) const [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2516
#23	0x0000000109cc4a72 in std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> >::reset(mbgl::Tile*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2715
#24	0x0000000109cc4a15 in std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> >::~unique_ptr() [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2683
#25	0x0000000109cc4a05 in std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> >::~unique_ptr() [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2683
#26	0x0000000109cc49fd in std::__1::pair<mbgl::TileID const, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >::~pair() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:253
#27	0x0000000109cc49a3 in std::__1::pair<mbgl::TileID const, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >::~pair() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:253
#28	0x0000000109ccf5d3 in std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >::~__value_type() [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:653
#29	0x0000000109ccf5cb in std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >::~__value_type() [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:653
#30	0x0000000109ccf5bd in void std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*> > >::__destroy<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > > >(std::__1::integral_constant<bool, false>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*> >&, std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1664
#31	0x0000000109ccf5a8 in void std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*> > >::destroy<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > > >(std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*> >&, std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1527
#32	0x0000000109ccf58c in std::__1::__tree<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, std::__1::__map_value_compare<mbgl::TileID, std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, std::__1::less<mbgl::TileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > > > >::erase(std::__1::__tree_const_iterator<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*>*, long>) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:1974
#33	0x0000000109cbe41b in std::__1::map<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> >, std::__1::less<mbgl::TileID>, std::__1::allocator<std::__1::pair<mbgl::TileID const, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > > > >::erase(std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*>*, long> >) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:1232
#34	0x0000000109cbe3cb in void mbgl::util::erase_if<std::__1::map<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> >, std::__1::less<mbgl::TileID>, std::__1::allocator<std::__1::pair<mbgl::TileID const, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > > > >, std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*>*, long> >, mbgl::Source::update(mbgl::StyleUpdateParameters const&)::$_3>(std::__1::map<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> >, std::__1::less<mbgl::TileID>, std::__1::allocator<std::__1::pair<mbgl::TileID const, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > > > >&, std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*>*, long> >, std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, std::__1::__tree_node<std::__1::__value_type<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > >, void*>*, long> >, mbgl::Source::update(mbgl::StyleUpdateParameters const&)::$_3) at /path/to/mapbox-gl-native-3/platform/ios/../../include/mbgl/util/std.hpp:15
#35	0x0000000109cb92c0 in void mbgl::util::erase_if<std::__1::map<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> >, std::__1::less<mbgl::TileID>, std::__1::allocator<std::__1::pair<mbgl::TileID const, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > > > >, mbgl::Source::update(mbgl::StyleUpdateParameters const&)::$_3>(std::__1::map<mbgl::TileID, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> >, std::__1::less<mbgl::TileID>, std::__1::allocator<std::__1::pair<mbgl::TileID const, std::__1::unique_ptr<mbgl::Tile, std::__1::default_delete<mbgl::Tile> > > > >&, mbgl::Source::update(mbgl::StyleUpdateParameters const&)::$_3) at /path/to/mapbox-gl-native-3/platform/ios/../../include/mbgl/util/std.hpp:24
#36	0x0000000109cb8c43 in mbgl::Source::update(mbgl::StyleUpdateParameters const&) at /path/to/mapbox-gl-native-3/src/mbgl/source/source.cpp:427
#37	0x0000000109d41d02 in mbgl::Style::update(mbgl::StyleUpdateParameters const&) at /path/to/mapbox-gl-native-3/src/mbgl/style/style.cpp:152
#38	0x0000000109c159b7 in mbgl::Map::Impl::update() at /path/to/mapbox-gl-native-3/src/mbgl/map/map.cpp:229
#39	0x0000000109c20066 in mbgl::Map::Impl::Impl(mbgl::View&, mbgl::FileSource&, mbgl::MapMode, mbgl::GLContextMode, mbgl::ConstrainMode)::$_0::operator()() const at /path/to/mapbox-gl-native-3/src/mbgl/map/map.cpp:91
#40	0x0000000109c2001b in std::__1::__invoke<mbgl::Map::Impl::Impl(mbgl::View&, mbgl::FileSource&, mbgl::MapMode, mbgl::GLContextMode, mbgl::ConstrainMode)::$_0&>(decltype(std::__1::forward<mbgl::Map::Impl::Impl(mbgl::View&, mbgl::FileSource&, mbgl::MapMode, mbgl::GLContextMode, mbgl::ConstrainMode)::$_0&>(fp)(std::__1::forward<>(fp0))), mbgl::Map::Impl::Impl(mbgl::View&, mbgl::FileSource&, mbgl::MapMode, mbgl::GLContextMode, mbgl::ConstrainMode)::$_0&&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:416
#41	0x0000000109c2000a in _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZN4mbgl3Map4ImplC1ERNS3_4ViewERNS3_10FileSourceENS3_7MapModeENS3_13GLContextModeENS3_13ConstrainModeEE3$_0EEEvDpOT_ at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:468
#42	0x0000000109c1fe87 in std::__1::__function::__func<mbgl::Map::Impl::Impl(mbgl::View&, mbgl::FileSource&, mbgl::MapMode, mbgl::GLContextMode, mbgl::ConstrainMode)::$_0, std::__1::allocator<mbgl::Map::Impl::Impl(mbgl::View&, mbgl::FileSource&, mbgl::MapMode, mbgl::GLContextMode, mbgl::ConstrainMode)::$_0>, void ()>::operator()() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1437
#43	0x0000000109ea051c in std::__1::function<void ()>::operator()() const at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1817
#44	0x0000000109e9977c in mbgl::util::AsyncTask::Impl::runTask() at /path/to/mapbox-gl-native-3/platform/darwin/src/async_task.cpp:45
#45	0x0000000109e995d6 in mbgl::util::AsyncTask::Impl::perform(void*) at /path/to/mapbox-gl-native-3/platform/darwin/src/async_task.cpp:50
```

**Comment by 1ec5** [comment] 2016-04-21 15:47
I can reproduce this issue with any style that involves terrain, but not for instance Mapbox Satellite.

**Comment by harri121** [comment] 2016-04-21 15:53
When will there be a fix for this? Like this I cannot release the new version of my app?

**Comment by 1ec5** [comment] 2016-04-21 15:59
The issue hasn’t been fully diagnosed yet, so it’s unclear when a fix would arrive. In the meantime, is the issue mitigated if you remove the terrain layer from your custom style (if that’s an option for you)?

**Comment by mb12** [comment] 2016-04-21 16:05
@1ec5  From the stack trace it looks like a known issue with work task cancellation. Terrain tiles contain a lof polygons. Since tesselation is non cancellable, aborting such work requests is expensive. 
This will get worse once queryRenderedFeatures is checked into master since it adds an additional step of rtree construction for these polygons.

https://github.com/mapbox/mapbox-gl-native/issues/2644

**Comment by harri121** [comment] 2016-04-21 16:09
@1ec5 Hiding the terrain layer works. Thanks for the tip!

**Comment by harri121** [comment] 2016-04-21 16:30
@1ec5 @mb12  Why don't you delay the rendering of "work intensive" layers until you are sure the user wants display the designated tile?

**Comment by kkaefer** [comment] 2016-04-27 14:39
@mb12 in particular, https://github.com/mapbox/mapbox-gl-native/issues/2644#issuecomment-210258384 is the main culprit for this.

**Comment by friedbunny** [comment] 2016-05-10 16:47
There have been reports that the unperformant terrain layer is [`landcover`](https://www.mapbox.com/vector-tiles/mapbox-terrain/#landcover) — specifically the `wood` class.

**Comment by twbell** [comment] 2016-05-16 17:27
Confirming here that Axon Vibe (Sojo App) has experienced this; reported issue by email to me via @artemp.

**Comment by jfirebaugh** [comment] 2016-05-27 19:48
This issue should have been largely mitigated by a recent update to the Mapbox Streets vector tile source, which reduces the complexity of the unperformant layer. #2444 will also help.

Closing here in favor of the underlying issue, #2644.

**Closed by jfirebaugh** 2016-05-27 19:48 UTC
Labels: Core GL, performance
