### ISSUE TITLE
float text field with too many decimals

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#2125] opened 2015-08-19 12:08 UTC
Given a style like this:

```
{
      "id": "MYID",
      "type": "symbol",
      "source": "mysource",
      "source-layer": "MYLAYER",
      "minzoom": 12,
      "layout": {
        "text-field": "{MYKEY}"
      },
      "paint": {
        "text-color": "@contour_water",
        "text-halo-color": "@land",
        "text-halo-width": 1.5,
        "text-size": 12
      }
  }
```

The MYKEY attribute has a float value. In mapbox-gl-js a float value of 24.7 is displayed as 24.7. On mapbox-gl-native (iOS), it is written like 24.69999999.. This happens to some floats, but not all. I have never seen it happen on mapbox-gl-js, but lots of time on mapbox-gl-native.

I know float is float, but is there a way to fix this without switching the value type to a string?

![img_0160](https://cloud.githubusercontent.com/assets/445229/9355697/bf1e5a92-467b-11e5-8cd5-238446c782d7.png)

**Comment by mb12** [comment] 2015-08-19 15:44
@halset as you have mentioned the safest workaround is to add a string column for any feature property that needs to be rendered as text. You can add different columns  e.g. name_en, name_de etc and switch between them using style  classes. 

Is it possible to share if  this a public data set? I haven't seen one for anywhere other than US.

**Comment by halset** [comment] 2015-08-20 07:23
Thanks for the answer. I will add a text variant if it is the best way to handle this in -native. No problem.

I have added mapbox vector tile support to our ENC/S-57 service. Unfortunately, (almost) only US/NOAA data are freely available. The data for the rest of the world is available through PRIMAR (that I work for via ECC) and others, but the licensing is a bit too difficult.

**Comment by halset** [comment] 2015-09-07 14:18
Oups, this is a duplicate of #998

**Comment by ljbade** [comment] 2015-09-08 04:13
Closing as dupe of #998

**Closed by ljbade** 2015-09-08 04:13 UTC
