### ISSUE TITLE
[Android] Gesture Detector bug

### ISSUE THREAD

**Issue by mpuchala** [mapbox/mapbox-gl-native#5047] opened 2016-05-16 15:47 UTC
**Platform: Android**
**Mapbox SDK version: 4.1.0 Snapshot**
### Steps to trigger behavior
1. Start map
2. Fast zoom in/out gesture
### Expected behavior

Stable work
### Actual behavior

Crash
### Comment

I'm able to reproduce bug in way described above (don't know if there is other way to do it). We launched our app today and also get report from Fabric.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.view.MotionEvent.getEventTime()' on a null object reference
       at com.almeros.android.multitouch.gesturedetectors.BaseGestureDetector.handleInProgressEvent(BaseGestureDetector.java:112)
       at com.almeros.android.multitouch.gesturedetectors.MoveGestureDetector.updateStateByEvent(MoveGestureDetector.java:130)
       at com.almeros.android.multitouch.gesturedetectors.MoveGestureDetector.handleInProgressEvent(MoveGestureDetector.java:113)
       at com.almeros.android.multitouch.gesturedetectors.BaseGestureDetector.onTouchEvent(BaseGestureDetector.java:73)
       at …MapObserver.onTouchListener(MapObserver.java:166)
       at …MapObserver.initLocation(MapObserver.java)
       at …MapObserver$$Lambda$4.onTouch(Unknown Source)
       at android.view.View.dispatchTouchEvent(View.java:8383)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2425)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2747)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
       at android.view.View.dispatchPointerEvent(View.java:8579)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4028)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3894)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3509)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3475)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3585)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3483)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3642)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3509)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3475)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3483)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5708)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5682)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5653)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5798)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5769)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5821)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:548)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5238)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
```

I'm adding my own `MoveGestureDetector` but when I removed it app crashed as well.

**Comment by tobrun** [comment] 2016-05-17 06:53
@mpuchala thanks for reaching out and reporting this issue, will look into it

**Comment by tobrun** [comment] 2016-05-17 07:05
Looking into the stacktrace it looks like the source of the issue is found in `MoveGestureDetector` and within `handleInProgressEvent`:

```java
    @Override
    protected void handleInProgressEvent(int actionCode, MotionEvent event) {
        switch (actionCode) {
        case MotionEvent.ACTION_UP:
        case MotionEvent.ACTION_CANCEL:
            mListener.onMoveEnd(this);
            resetState();
            break;

        case MotionEvent.ACTION_MOVE:
            updateStateByEvent(event);

            // Only accept the event if our relative pressure is within
            // a certain limit. This can help filter shaky data as a
            // finger is lifted.
            if (mCurrPressure / mPrevPressure > PRESSURE_THRESHOLD) {
                final boolean updatePrevious = mListener.onMove(this);
                if (updatePrevious) {
                    mPrevEvent.recycle();
                    mPrevEvent = MotionEvent.obtain(event);
                }
            }
            break;
        }
    }
```

The actual issue seems to be in `updateStateByEvent` parents method in `BaseGestureDectector`:

```java
    protected void updateStateByEvent(MotionEvent curr) {
        final MotionEvent prev = mPrevEvent;

        // Reset mCurrEvent
        if (mCurrEvent != null) {
            mCurrEvent.recycle();
            mCurrEvent = null;
        }
        mCurrEvent = MotionEvent.obtain(curr);

        // Delta time
        mTimeDelta = curr.getEventTime() - prev.getEventTime();

        // Pressure
        mCurrPressure = curr.getPressure(curr.getActionIndex());
        mPrevPressure = prev.getPressure(prev.getActionIndex());
    }

```

More specifically in:

```
mTimeDelta = curr.getEventTime() - prev.getEventTime();
``` 

Since this is a bug in our gesture detector library and not in the SDK itself. I'm currently not seeing an easy fix for this. It's also a bit strange that we haven't seen any other reports on this issue since this code has been in the SDK since the start. 

@mpuchala what is the use case for adding an own move gesture detector?

**Comment by mpuchala** [comment] 2016-05-17 07:40
@tobrun 
Thanks for clarification. I'm adding my move gesture detector to find out gesture's delta. If it's longer than x observer is being notified (We're using it to hide custom view which can be shown on the to of map). I can implement it by my own (counting delta on ``MotionEvents``) but I think using ``MoveGestureDetector`` is more clear and simple.

Here is my implementation:

When MapboxMap object is ready I'm setting listener (``mapView.setOnTouchListener(this::onTouchListener);``).

Here is implementation of ``onTouchListener`` method:
```
    private boolean onTouchListener(View view, MotionEvent motionEvent) {
        switch (motionEvent.getAction()) {
            case MotionEvent.ACTION_DOWN:
                //(...)
                break;
            case MotionEvent.ACTION_CANCEL:
            case MotionEvent.ACTION_UP:
                //(...)
                break;
        }

        mMoveGestureDetector.onTouchEvent(motionEvent);

        return false;
    }
```

and ``MoveGestureDetector``

```
private MoveGestureDetector mMoveGestureDetector = new MoveGestureDetector(mContext, new MoveGestureDetector.SimpleOnMoveGestureListener() {
        @Override
        public void onMoveEnd(MoveGestureDetector detector) {
            if (detector.getFocusDelta().length() > Consts.Map.MIN_GESTURE_DELTA) {
                mMapObserverCallback.onLongMoveGesture();
            }
        }
    });
```

Fortunately it's not major bug and occurred only once since yesterday.

**Comment by mpuchala** [comment] 2016-06-10 11:47
@tobrun 
Update:
Nowadays it's one of our major bugs and occurred more than 20 times. Any progress in investigation or fixing issue?

Thanks

**Comment by mpuchala** [comment] 2016-09-27 15:27
@tobrun 
I'm using 4.1.0 stable version and actually it's the most common bug in our app...

Is there any progress with this issue?

**Comment by cammace** [comment] 2016-11-16 17:25
Hey @mpuchala, we haven't heard any more reporting on this issue and we currently don't support plugging in your own touch listener.

**Closed by cammace** 2016-11-16 17:25 UTC
Labels: Android, crash
