### ISSUE TITLE
bearing axis doesn't follow MyLocationView when padding is applied

### ISSUE THREAD

**Issue by Grsmto** [mapbox/mapbox-gl-native#8912] opened 2017-05-06 02:36 UTC
Hi Mapbox!

![xxklrp](https://cloud.githubusercontent.com/assets/527559/25769280/5c2f7936-31eb-11e7-813f-aa0263f44380.gif)

**Platform:** Android 7.1.2
**Mapbox SDK version:** android-v5.0.2

### Steps to trigger behavior
Simply use the example from the documentation https://www.mapbox.com/android-sdk/examples/customize-user-location/ or:

 1. Set bearing tracking mode `map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.COMPASS);`
 2. Set a padding on the Location View `map.getMyLocationViewSettings().setPadding(0, 1000, 0, 0);`
 3. Now, tilt the map with 2 fingers
 4. Rotate the map by moving your phone around

### Expected behavior
The map should rotate on the same axis as the MyLocationView.

### Actual behavior
The map rotates around a wrong axis.

**Comment by Grsmto** [comment] 2017-05-24 11:30
This may be a duplicate of #8415

**Comment by tobrun** [comment] 2017-06-02 08:36
Same root cause as #8415, closing as a duplicate. Thank you for the report @Grsmto!

**Closed by tobrun** 2017-06-02 08:36 UTC
Labels: Android
