### ISSUE TITLE
Black and "splitted" markers in Android

### ISSUE THREAD

**Issue by prudas** [mapbox/mapbox-gl-native#8943] opened 2017-05-10 08:44 UTC
**Platform: Android**
**Mapbox SDK version: 5.1.0**

Sometimes (not always, but more often when the map is opened for some time) after adding marker they become grey and somekind "splitted". See screenshot. Happens also with custom map source. The marker become correct sometimes after map changes zoom (randomly for each marker, around zoom levels 11,12,13).

![screenshot_2017-05-09-14-12-43](https://cloud.githubusercontent.com/assets/8956118/25890254/21480006-356d-11e7-8389-b02de8c968d0.png)
![screenshot_2017-05-09-14-12-57](https://cloud.githubusercontent.com/assets/8956118/25890255/214bf094-356d-11e7-9520-5c7b01a05a21.png)
![screenshot_2017-05-09-14-18-23](https://cloud.githubusercontent.com/assets/8956118/25890257/214e5e6a-356d-11e7-9443-35706f821ec4.png)
![screenshot_2017-05-09-14-18-45](https://cloud.githubusercontent.com/assets/8956118/25890258/21574548-356d-11e7-97da-aa8d11afc601.png)
<img width="113" alt="snimek obrazovky 2017-05-10 v 10 38 18" src="https://cloud.githubusercontent.com/assets/8956118/25890256/214d5466-356d-11e7-8c7b-76fecca64fbb.png">

### Testing devices
Acer A1 840FHD, Android 4.4.2
Samsung GT I9300, Android 4.3
Emulator Nexus 5, Android 7.0

**Comment by prudas** [comment] 2017-05-10 09:02
Change of orientation fixes markers.
"Split" problem appears also with not black markers, see screenshot below.
![screenshot_2017-05-10-11-19-55](https://cloud.githubusercontent.com/assets/8956118/25891126/305aebaa-3570-11e7-9ff1-58eaa07aa917.png)
![screenshot_2017-05-10-11-22-25](https://cloud.githubusercontent.com/assets/8956118/25891127/30601486-3570-11e7-9e06-15246b2695e1.png)

**Comment by Guardiola31337** [comment] 2017-05-25 09:57
@prudas thank you for reaching out and reporting your problem.

It seems you're experiencing the same issue described in #9026 

Could you add some more information for reproducing the issue? If there is any sample or pseudo code you can provide, that would also be helpful.

**Comment by danielprudek** [comment] 2017-05-25 10:24
Hello,

thank you for reaction. This was also me who created issue #9026, because I firstly thought It was not surely related to this one. (I was changing nickname that time and it somehow took effect later..).

Sample though would be the same as in #9026, I just can add one more information: **While adding and removing markers **(hundreds of markers, up to 100 different Bitmaps)**, it happened that some markers showed completely invisible and other were showed with different image.** Hope this helps.
 
I will try to implement suggested fix from #9026 with caching Icon objects (I was caching just Bitmap objects before and it had no effect).

I am sorry for duplicate and I believe you **can merge** these issues into one.

**Comment by Guardiola31337** [comment] 2017-05-25 10:43
@danielprudek no worries! Thanks 👍

Closing in favor of #9026

**Closed by Guardiola31337** 2017-05-25 10:43 UTC
Labels: Android, annotations

**Comment by zugaldia** [comment] 2017-09-06 15:52
Additionally, note that black and splitted marker rendering is tracked on https://github.com/mapbox/mapbox-gl-native/issues/9910.
