### ISSUE TITLE
Android Bug: the map rotates on enabling tracking

### ISSUE THREAD

**Issue by lgeromegnace** [mapbox/mapbox-gl-native#3450] opened 2016-01-06 16:38 UTC
Hi,
We are working on adding insets to the map (#2600) and we notice an unexpected behavior with the test app.

### How to:
After rotating the map, press the user location button several times.

### Observed:
The map rotates each time we press the user location.

### Expected:
The map should not rotate.

**Comment by tobrun** [comment] 2016-01-14 11:20
@lgeromegnace 
Could you add some code to test with?
Which version of the SDK are you using?

**Comment by lgeromegnace** [comment] 2016-01-14 13:55
@tobrun 
I observed the bug on version 3.1.0-SNAPSHOT of MapboxGLAndroidSDK.
You asked for code but I had the issue without any modification of mine.

**Comment by tobrun** [comment] 2016-01-14 14:57
@lgeromegnace 
I was able to reproduce it, looking..

**Comment by tobrun** [comment] 2016-01-14 15:25
When debugging I'm noticing that the `MyBearingTracking` value was equal to `MyBearingTracking.GPS`. I believe the problem is coming from not saving the `MyBearingTracking` state in `onSaveInstanceState`. With that in place I'm unable to reproduce it. Reopen if incorrect.

**Comment by tobrun** [comment] 2016-01-14 15:30
@lgeromegnace 
Note that this will be merged in release branch of 3.1.0 and will not be available in SNAPSHOT.

**Comment by lgeromegnace** [comment] 2016-01-14 15:38
Okay ! Thanks @tobrun

**Comment by tobrun** [comment] 2016-01-15 10:08
Landed in release branch with d764e9829eab48d2b6122ce2285f5ed95a366c6f

**Closed by tobrun** 2016-01-15 10:08 UTC
Labels: Android, in progress
