### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV) after changing to expressions

### ISSUE THREAD

**Issue by sarahthe** [mapbox/mapbox-gl-native#12541] opened 2018-08-03 11:07 UTC
I started updating to the new Android Maps SDK from 5.5.1 to 6.3.0.
Due to the upgrade, I had to switch to expressions.
While doing that, I encountered the SIGSEGV error and cannot find the reason for it.

When opening the map view, the app shows a white screen and crashes immediately.
The onMapReady function is called and runs through.

Below you can find a part of my code that creates the expressions and layers. Only after changing to expressions this error happened.

### Steps to reproduce
 1. Open map view

### Expected behavior
MapView is shown

### Actual behavior
App crashes with "A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7df1456e9c0fa8 in tid 22641 (oid.localee.dev)"

### Expression code
The expressions are created with a list of categories (that have a certain icon) and the features have a unique ID. Each unique category ID is supposed to be assigned its icon.

**EDIT: was able to fix the error due to wrong assignment of icons to icon-image expression.
Now I still get an error for the offset: Error setting property: icon-offset [3]: Expected array<number, 2> but found number instead.
I could't find any proper documentation how to create an array as it only takes one value.**

`List<Expression.Stop> categoryList = new LinkedList<>();
		List<Expression.Stop> offsetList = new LinkedList<>();

	for (CategoryDefaults category : CategoryDefaults.values()) {
			Icon icon = mapboxUtils.getIconFrom(markerIcons.getCategoryBitmap(category.getIdentifier(), false, false));

			view.getBaseMap().addImage(String.valueOf(category.getIdentifier()), icon.getBitmap());
			categoryList.add(Expression.stop(category.getIdentifier(), Expression.literal(String.valueOf(category.getIdentifier()))));
			offsetList.add(Expression.stop(category.getIdentifier(), Expression.literal(
					new Float[]{
							icon.getBitmap().getWidth() * 0.082f / icon.getScale(),
							icon.getBitmap().getHeight() * -0.419f / icon.getScale()
					})
			));
		}

		Expression.Stop[] categoryArray = new Expression.Stop[categoryList.size()];
		for (int i = 0; i < categoryList.size(); i++) {
			categoryArray[i] = categoryList.get(i);
		}

		Expression.Stop[] offsetArray = new Expression.Stop[offsetList.size()];
		for (int i = 0; i < offsetList.size(); i++) {
			offsetArray[i] = offsetList.get(i);
		}

		SymbolLayer marker = new SymbolLayer(MARKER, MARKER).withProperties(
				PropertyFactory.iconImage(Expression.match(
						Expression.get(CATEGORY),
						Expression.literal(mapboxUtils.getIconFrom(markerIcons.getCategoryBitmap(MarkerIcons.GENERIC_PLACE_ID, false, false))),
						categoryArray
				)),

				PropertyFactory.iconOffset(Expression.match(
						Expression.get(CATEGORY),
						Expression.literal(0),
						offsetArray
				)),

				PropertyFactory.iconAllowOverlap(Expression.literal(true))
		);

		view.getBaseMap().addLayer(marker);`

### Configuration
**Android versions:** 8.0.0
**Device models:** Nexus 5X
**Mapbox SDK versions:** Android Maps SDK 6.3.0, Services 2.2.10, LocationLayer 0.7.1, Navigation 0.12.0

**Comment by LukasPaczos** [comment] 2018-08-06 11:27
Hey @sarahthe, thanks for reaching out. It seems like the error is caused by the default value that you are passing, which should also be an array.

Instead of
```
PropertyFactory.iconOffset(Expression.match(
		Expression.get(CATEGORY),
		Expression.literal(0),
		offsetArray
)),
```
try using
```
PropertyFactory.iconOffset(Expression.match(
		Expression.get(CATEGORY),
		Expression.literal(new Float[]{0f, 0f}),
		offsetArray
)),
```

Closing as resolved but please feel free to reach back if that's not the case, thanks!

**Closed by LukasPaczos** 2018-08-06 11:27 UTC
Labels: Android, support
