### ISSUE TITLE
Annotation selection not working on Mapbox iOS SDK 5.1.0

### ISSUE THREAD

**Issue by anttifinnair** [mapbox/mapbox-gl-native#15088] opened 2019-07-10 09:29 UTC
`MGLAnnotationView` cannot be selected on map by tapping annotation and delegate `- (void)mapView:(MGLMapView *)mapView didSelectAnnotation:(id <MGLAnnotation>)annotation;` isn't called. Same code has worked with Mapbox 5.0.0 and earlier.

### Steps to reproduce

 1. Add `MGLAnnotationView` on map
 2. Tap it

### Expected behavior

`MGLAnnotation` gets selected and `didSelectAnnotation` delegate is called.

### Actual behavior

Nothing happens. Annotation isn't selected.

### Configuration

**Mapbox SDK versions:** 5.1.0
**iOS/macOS versions:** iOS 12.3.1
**Device/simulator models:** reprodusable on both simulator and device.
**Xcode version:** 10.2.1

**Comment by friedbunny** [comment] 2019-07-10 18:34
Thanks for the report, @anttifinnair — seems related to #15082.

**Comment by anttifinnair** [comment] 2019-07-11 07:42
Yes, that looks related. Selection randomly works on some zoom levels/rotation but mostly it doesn't.

**Comment by bDivergent** [comment] 2019-07-11 15:27
> Yes, that looks related. Selection randomly works on some zoom levels/rotation but mostly it doesn't.

That is what I have also experienced. When I zoom in too far then the annotation will not be visible. Nothing happens.

**Comment by julianrex** [comment] 2019-07-12 14:22
Noting I added #15106 which may be the cause, rather than #15082.

**Comment by azukinohiroki** [comment] 2019-08-22 03:21
Hi, I have the same problem.
When I zoom in/out by pinch and release both fingers at the same time, no problem happens.
Releasing fingers one by one, may cause the problem.
I hope it will help.

**Comment by friedbunny** [comment] 2019-08-22 15:23
This was fixed by #15097 in `ios-v5.2.0`. If anyone is still experiencing it after updating, definitely please let us know.

**Closed by friedbunny** 2019-08-22 15:23 UTC
Labels: Core, bug, iOS
