### ISSUE TITLE
Can't load the map

### ISSUE THREAD

**Issue by onion4** [mapbox/mapbox-gl-native#4955] opened 2016-05-06 04:26 UTC
can't display the mapview but show a blackscreen,please check the log,thanks
**Mapbox SDK version:4.0.0 stable

### 
java.lang.IllegalArgumentException: Unexpected char 0x91ce at 0 in User-Agent value: xxxx(AppName)/2.2.0-dev/131104 MapboxEventsAndroid/4.0.0
W/System.err:     at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:283)
W/System.err:     at okhttp3.Headers$Builder.set(Headers.java:263)
W/System.err:     at okhttp3.Request$Builder.header(Request.java:165)
W/System.err:     at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:637)
W/System.err:     at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:522)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by 1ec5** [comment] 2016-05-06 04:28
Duplicate of #4354, fixed in #4598, and slated for release in v4.1.0.

**Closed by 1ec5** 2016-05-06 04:28 UTC
Labels: Android
