### ISSUE TITLE
Some problem about Marker

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4048] opened 2016-02-20 05:04 UTC
I have some problem about marker.  

Marker can only be added by `MarkerOptions`  
```
mapView.addMarker(new MarkerOptions().title("aa"));
```  
#### 1. How can i change marker after added?  
There is no method like `marker.setTitle()` or `marker.setPosition()`.  

#### 2. How do i change zIndex of marker?  
If some marker on same position, I want to change the zIndex of marker, But there is no method like `marker.setZIndex()`.  

#### 3. There is some error if call some api just after mapView init.  

(1) setInfoWindowAdapter() is not work just after mapView init, for example It's not work just call it in OnCreateView() method, It's only work by delay some seconds.  

(2) animateCamera() will cause map is black total when call it just after mapView init.

**Comment by tobrun** [comment] 2016-02-20 20:31
>1. How can i change marker after added?
There is no method like marker.setTitle() or marker.setPosition().

this is not possible with `3.2.0` release, but will be with `4.0.0`

> 2. How do i change zIndex of marker?
If some marker on same position, I want to change the zIndex of marker, But there is no method like marker.setZIndex().

We currently do not support z indexes. Need to check if this will be added in the near future.

> (1) setInfoWindowAdapter() is not work just after mapView init, for example It's not work just call it in OnCreateView() method, It's only work by delay some seconds.

Will need to reproduce this, but I believe this will be automatically resolved with the `4.0.0` release.

> (2) animateCamera() will cause map is black total when call it just after mapView init.

Will need to reproduce this, but I believe this will be automatically resolved with the `4.0.0` release.

> 4. The infoWindow will be error when dragging marker if layout of infoWindow is complex.

Could you elaborate? we currently do not support draggable markers (yet).

> 5. How can i change my location picture after call

You can listen to Location changes, using `mMapView.setOnMyLocationChangeListener`:

```java
   /**
     * Interface definition for a callback to be invoked when the the My Location dot
     * (which signifies the user's location) changes location.
     *
     * @see MapboxMap#setOnMyLocationChangeListener(OnMyLocationChangeListener)
     */
    public interface OnMyLocationChangeListener {
        /**
         * Called when the location of the My Location dot has changed
         * (be it latitude/longitude, bearing or accuracy).
         *
         * @param location The current location of the My Location dot The type of map change event.
         */
        void onMyLocationChange(@Nullable Location location);
    }
```

**Comment by Trinea** [comment] 2016-02-22 01:34
Thank you for your reply.
1. When 4.0.0 will be realeased?

2. The infoWindow will be error when dragging map if layout of infoWindow is complex.

3. How can i change my location picture? the circle point of my location picture.

4. I will write a demo to show the bug of `setInfoWindowAdapter()` and `animateCamera()` bug when map inited.

**Comment by tobrun** [comment] 2016-02-22 09:11
> When 4.0.0 will be realeased?

We currently don't have an ETA on the release but if you like you can test out current SNAPSHOT:

![screen shot 2016-02-22 at 10 05 39](https://cloud.githubusercontent.com/assets/2151639/13213827/e612fe56-d94b-11e5-88da-b83acad4e5de.png)

> The infoWindow will be error when dragging map if layout of infoWindow is complex.

Could you show me some screenshot or code to reproduce?

> How can i change my location picture? the circle point of my location picture.

This is currently not available as an API (yet), you can use resource overloading to achieve this or if you can build the project from source and replace current images. We are thinking about adding this as an API in https://github.com/mapbox/mapbox-gl-native/issues/3231 (with added support for tinting).

> I will write a demo to show the bug of setInfoWindowAdapter() and animateCamera() bug when map inited.

That is super helpful, just a screenshot or a small video is also :+1:

@Trinea 
Reach out if you have any other questions!

**Closed by tobrun** 2016-02-22 09:11 UTC
Labels: Android, support

**Comment by Trinea** [comment] 2016-02-22 09:41
Thank you.

1. setInfoWindowAdapter() is not work just after mapView init.
```

    private MapView mv;

    private static final int PERMISSIONS_LOCATION = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        mv = (MapView) findViewById(R.id.mapview);
        mv.setStyle(Style.MAPBOX_STREETS);
        mv.setCenterCoordinate(new LatLng(0, 0));

        final Marker marker = mv.addMarker(new MarkerOptions().title("Edinburgh").snippet("Scotland").position(new LatLng(55.94629, -3.20777)));

        mv.onCreate(savedInstanceState);

        mv.setInfoWindowAdapter(new MapView.InfoWindowAdapter() {
            @Nullable
            @Override
            public View getInfoWindow(Marker marker) {
                View infowindow = LayoutInflater.from(MainActivity.this).inflate(R.layout.custom_info_window, null);
                render(marker, infowindow);
                return infowindow;
            }
        });
        marker.showInfoWindow();
	}
```

custom_info_window.xml is
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@drawable/marker_pop">

    <TextView
        android:id="@+id/title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:ellipsize="end"
        android:paddingBottom="15dp"
        android:paddingLeft="20dp"
        android:paddingRight="20dp"
        android:paddingTop="15dp"
        android:singleLine="true"
        android:text="Test"
        android:textColor="#707070"
        android:textSize="15dp"/>

</LinearLayout>
```
The infoWindow is not show, when start app, but if I change like below, The infoWindow can be showed.
```
marker.showInfoWindow();
``` 
to
```
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                marker.showInfoWindow();
            }
        }, 2000);
```

**Comment by Trinea** [comment] 2016-02-22 10:04
The infoWindow will be error when dragging marker if layout of infoWindow is complex.
![Uploading ezgif-1343719177.gif…]()
```
private MapView mv;

private static final int PERMISSIONS_LOCATION = 0;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    setContentView(R.layout.activity_main);

    mv = (MapView) findViewById(R.id.mapview);
    mv.setStyle(Style.MAPBOX_STREETS);
    mv.setCenterCoordinate(new LatLng(0, 0));

    final Marker marker = mv.addMarker(new MarkerOptions().title("Edinburgh").snippet("Scotland").position(new LatLng(55.94629, -3.20777)));

    mv.onCreate(savedInstanceState);

    mv.setInfoWindowAdapter(new MapView.InfoWindowAdapter() {
        @Nullable
        @Override
        public View getInfoWindow(Marker marker) {
            View infowindow = LayoutInflater.from(MainActivity.this).inflate(R.layout.custom_info_window, null);
            render(marker, infowindow);
            return infowindow;
        }
    });
    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            marker.showInfoWindow();
        }
    }, 2000);
}
```

custom_info_window.xml is
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@drawable/marker_pop">

    <TextView
        android:id="@+id/title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:ellipsize="end"
        android:paddingBottom="15dp"
        android:paddingLeft="20dp"
        android:paddingRight="20dp"
        android:paddingTop="15dp"
        android:singleLine="true"
        android:text="Test"
        android:textColor="#707070"
        android:textSize="15dp"/>

</LinearLayout>
```

**Comment by cammace** [comment] 2016-06-17 15:37
I've reviewed your code and it looks like you are using `marker.showInfoWindow();`. This is an internal library method which wont work properly for your use case. However, using `mapboxMap.selectMarker(marker);` in the new SDK will show the info window when executed.
