### ISSUE TITLE
Polygons on top of rasters have tile-border artifacts

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1857] opened 2015-07-09 03:07 UTC
Haven't quite tracked down the exact steps to replicate, but something like this:

1. Draw a filled polygon over the satellite layer
2. Zoom in until you see flickering lines in the polygon
3. Find a tile border and zoom in and out

![ezgif com-crop](https://cloud.githubusercontent.com/assets/1198851/8587131/eeed7f18-25c5-11e5-8b4a-8d2a56073a28.gif)

*Sorry for the heavy gif, rasters y'know...*

![raster-poly-bug](https://cloud.githubusercontent.com/assets/1198851/8587104/91a5c4be-25c5-11e5-903c-d59ad296a7a2.jpg)

/cc @incanus @1ec5 @kkaefer

**Comment by incanus** [comment] 2015-07-09 04:20
So the yellow stuff is the artifacts? 

Just spitballing here...

- Antialiasing problems related to the rounding change? 
- Something related to the tile clipping we are seeing log messages about in https://github.com/mapbox/mapbox-gl-native/issues/962?

**Comment by friedbunny** [comment] 2015-07-09 04:33
Poor word choice, sorry. The polygon is supposed to be solid — the straight yellow lines that appear on the tile boundaries are the "artifacts". Middle picture in the row is the best illustration.

**Comment by ansis** [comment] 2015-07-10 10:21
> Something related to the tile clipping we are seeing log messages about in #962?

That is my guess too.

The current approach to tile clipping can only support a limited number of tiles before it runs out of stencil buffer bits.

As a workaround we could disable clipping for raster sources since they don't really need it. Skipping this if the source is raster could help: https://github.com/mapbox/mapbox-gl-native/blob/efa7dad89c61fe0fcc01a492e8db8e36b8f27f53/src/mbgl/renderer/painter.cpp#L209-L223

**Comment by friedbunny** [comment] 2015-09-08 04:47
Haven't seen this since reporting — going to close.

**Comment by kkaefer** [comment] 2015-09-14 13:00
Tried to reproduce this, but failed.

**Comment by nicomgd** [comment] 2015-09-16 19:46
I got exactly the same artifact just today with our own styles & data, it turns out that it is related to stencil overflow : I quickly patched the code to remove the annotations virtual layers, thus gaining precious stencil bits, and the issue went away.

**Comment by kkaefer** [comment] 2015-09-17 13:47
@nicomgd can you please describe what sort of layers and sources your style has? What zoom levels are active at a given time?

**Comment by nicomgd** [comment] 2015-09-17 16:59
Sorry, gotta run a little, here is a brief description :

I got only vector tile layers (no raster).

![stencil-overflow-zooms](https://cloud.githubusercontent.com/assets/7020867/9939767/51843a12-5d6c-11e5-817d-83f43bb91e3a.jpg)

I manage to have the problem with 4 sources (there are more for real, but those removed have the same 'maxzoom') :

```
  "sources": {
    "world": {
      "type": "vector",
      "tiles": [
        "http:\/\/localhost:7878\/world\/{z}\/{x}\/{y}.pbf"
      ],
      "maxzoom": 5
    },
    "schematique": {
      "type": "vector",
      "tiles": [
        "http:\/\/localhost:7878\/schematique\/{z}\/{x}\/{y}.pbf"
      ],
      "maxzoom": 15
    },
    "mos-setec": {
      "type": "vector",
      "tiles": [
        "http:\/\/localhost:7878\/mos-setec\/{z}\/{x}\/{y}.pbf"
      ],
      "maxzoom": 14
    },
    "bdtopo-large": {
      "type": "vector",
      "tiles": [
        "http:\/\/localhost:7878\/bdtopo-large\/{z}\/{x}\/{y}.pbf"
      ],
      "maxzoom": 16
    }
  },
```

The debug view lets me think that all 4 zoom levels are active.

My quick & dirty instrumentation of mbgl code gives me this log (I put back the `annotations.points` layer) :

```
[INFO] {Map}[OpenGL]: ClipID for 'world'
[INFO] {Map}[OpenGL]: stencil bits: 1, total=1 - 1 tiles
[INFO] {Map}[OpenGL]: ClipID for 'schematique'
[INFO] {Map}[OpenGL]: stencil bits: 3, total=4 - 4 tiles
[INFO] {Map}[OpenGL]: ClipID for 'mos-setec'
[INFO] {Map}[OpenGL]: stencil bits: 3, total=7 - 4 tiles
[INFO] {Map}[OpenGL]: ClipID for 'bdtopo-large'
[INFO] {Map}[OpenGL]: stencil bits: 3, total=10 - 4 tiles
[ERROR] {Map}[OpenGL]: stencil mask overflow, bit_offset=10
[INFO] {Map}[OpenGL]: ClipID for 'com.mapbox.annotations.points'
[INFO] {Map}[OpenGL]: stencil bits: 5, total=15 - 16 tiles
[ERROR] {Map}[OpenGL]: stencil mask overflow, bit_offset=15
```

The patch for logging is :
```
diff --git a/src/mbgl/renderer/painter.cpp b/src/mbgl/renderer/painter.cpp
index e757d68..c11d183 100644
--- a/src/mbgl/renderer/painter.cpp
+++ b/src/mbgl/renderer/painter.cpp
@@ -208,6 +208,7 @@ void Painter::render(const Style& style, TransformState state_, const FrameData&
         // Update all clipping IDs.
         ClipIDGenerator generator;
         for (const auto& source : sources) {
+            Log::Info(Event::OpenGL, "ClipID for '%s'", source->info.source_id.c_str());
             generator.update(source->getLoadedTiles());
             source->updateMatrices(projMatrix, state);
         }
diff --git a/src/mbgl/util/clip_id.cpp b/src/mbgl/util/clip_id.cpp
index 901e978..cf9e34b 100644
--- a/src/mbgl/util/clip_id.cpp
+++ b/src/mbgl/util/clip_id.cpp
@@ -48,6 +48,7 @@ void ClipIDGenerator::update(std::forward_list<Tile *> tiles) {
         return a->id < b->id;
     });
 
+    int num_tiles = 0;
     const auto end = tiles.end();
     for (auto it = tiles.begin(); it != end; it++) {
         if (!*it) {
@@ -71,6 +72,8 @@ void ClipIDGenerator::update(std::forward_list<Tile *> tiles) {
             // We haven't found an existing clip ID
             pool.push_back(std::move(clip));
         }
+
+        num_tiles++;
     }
 
     if (!pool.empty()) {
@@ -87,10 +90,12 @@ void ClipIDGenerator::update(std::forward_list<Tile *> tiles) {
 
         bit_offset += bit_count;
         pools.push_front(std::move(pool));
+
+        Log::Info(Event::OpenGL, "stencil bits: %d, total=%d - %d tiles", bit_count, bit_offset, num_tiles);
     }
 
     if (bit_offset > 8) {
-        Log::Error(Event::OpenGL, "stencil mask overflow");
+        Log::Error(Event::OpenGL, "stencil mask overflow, bit_offset=%d", bit_offset);
     }
 }
 ```

**Comment by kkaefer** [comment] 2015-09-18 10:19
Thanks for posting this screenshot, this is very helpful. What's happening is that multiple vector tile sources with different max zooms require tiles of different zoom levels to be present at the same time. When adding more distinct tile sources, this increases as shown in the screenshot above  (there are tiles from four zoom levels present; disregard the leading `17`, it's wrong). Unfortunately, this eats up the available stencil bit pretty quickly.

The best solution for us is to change Mapbox GL so that clipping is no longer required on the GPU side. This means we'd have to clip all of our data on the CPU side to avoid duplicate rendering (such as seen in this ticket).

As a short term solution, we should implement a mechanism that avoids distributing clip IDs to tiles that don't render anything (such as many annotation tiles).

**Comment by kkaefer** [comment] 2015-09-18 10:22
@nicomgd for your particular problem, it'll also help to reduce the number of distinct tile sources, and in particular to reduce the number of distinct maxzooms. If all maxzooms are the same level, they'll eventually share ClipIDs once all tiles are loaded.

**Comment by nicomgd** [comment] 2015-09-18 11:18
Thanks for your feedback! 

For my particular current need, I think I'll be able change my tile sources to reduce the maxzooms 'set' - I'll see if I need to patch/remove the annotations to gain the 5 unused bits.

FWIW, we started working on the sources & style on mapbox-gl-js which has no limitation related to the stencil bits (which comes at a big performance cost it seems), so this is a bad surprise for us to have the rendering 'silently' corrupted.

I don't have a full picture of the underlying rendering architecture, but wouldn't it be possible to detect the stencil overflow, and in this case, go for rendering in multiple passes ? This would hurt performance, but allow to have correct rendering.

**Comment by kkaefer** [comment] 2015-09-18 11:21
Yeah, the "stencil overflow" message is generated by MBGL, so we know exactly when this happens. Doing multiple render passes is also a viable idea, but, as you rightly say, will hurt performance.

**Comment by jfirebaugh** [comment] 2016-02-12 01:42
Closing here since the original report isn't reproducible and we know the cause of stencil overflow and have issues tracking that, e.g. #962.

**Closed by jfirebaugh** 2016-02-12 01:42 UTC
Labels: bug, raster
