### ISSUE TITLE
Map crash (offline)

### ISSUE THREAD

**Issue by snodnipper** [mapbox/mapbox-gl-native#4717] opened 2016-04-15 18:18 UTC
Demo app crashes with after several hundred map movements using an offline map.

Device: Nexus 7 (2nd gen)
Map: custom style

Using a mixture of zooming and panning...after 3-5 minutes the app crashes.

Tested on (custom style*):
https://github.com/mapbox/mapbox-gl-native/commit/a70928c995504567e85d0b34c2e10c104a72634c
https://github.com/mapbox/mapbox-gl-native/commit/1ee0055710b31de4fa51a7cc58efe77973255114

[logcat.txt](https://github.com/mapbox/mapbox-gl-native/files/221480/logcat.txt)

\* I have yet to establish if the custom style has any significance.

**Comment by snodnipper** [comment] 2016-04-18 16:36
Update:

* I was able to crash the device without a downloaded region.
* Interestingly the streets dataset did not seem to crash - which makes me wonder if the custom style touches something different _or_ that the map data we are using is larger and therefore the problem is more apparent.  The map certainly uses overzoom if anyone thinks that might be relevant.

**Comment by cammace** [comment] 2016-10-31 18:44
Looks like this issue might have slipped through the cracks. There's been a memory issue reported for the Nexus 7: https://github.com/mapbox/mapbox-gl-native/issues/6429. If you are still running into issues, could you provide any additional information such as code and custom map URL.

**Comment by cammace** [comment] 2016-11-09 19:11
Unable to reproduce. Closing issue due to lack of information.

**Closed by cammace** 2016-11-09 19:11 UTC
Labels: Android, crash, offline
