### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by HovsepShhakaryan** [mapbox/mapbox-gl-native#16109] opened 2020-01-10 05:11 UTC
Good morning, I want to get location address from lat and long using mapbox

MapboxGeocoding reverseGeocode = MapboxGeocoding.builder()
.accessToken(Config.MAP_BOX_KEY)
.query(Point.fromLngLat(38.89770, -77.03655))
.geocodingTypes(GeocodingCriteria.TYPE_ADDRESS)
.build();

But it give me all think empty

2020-01-09 18:29:32.989 28832-28832/com.hovsep.bestfleet4u D/DSADSA: MapboxGeocoding{query=38.8977,-77.03655, mode=mapbox.places, accessToken=pk.eyJ1IjoiaG92c2VwIiwiYSI6ImNrNTZiaGUxbTAxaG0zbW9kcHp0d3Bud3AifQ.SYgSqmVIcfAkLQ1EugF6Vg, baseUrl=https://api.mapbox.com, country=null, proximity=null, geocodingTypes=address, autocomplete=null, bbox=null, limit=null, languages=null, reverseMode=null, fuzzyMatch=null, clientAppName=null}

how to fix it???

**Comment by LukasPaczos** [comment] 2020-01-10 11:29
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/16105.

**Closed by LukasPaczos** 2020-01-10 11:29 UTC
