### ISSUE TITLE
Downloading offline packs takes more size than expected. 

### ISSUE THREAD

**Issue by ivanmkc** [mapbox/mapbox-gl-native#10483] opened 2017-11-17 08:34 UTC
**Platform:** iOS 11
**Mapbox SDK version:** 3.6.4

### Steps to trigger behavior

 1. Download a small region (20m by 20m) around the Eiffel Tower at zoom level 15
 2. Track the download size through code and\or a HTTP monitor.

Sample repo here: https://github.com/ivanmkc/MapDownloadTest

### Expected behavior
The download should be relatively small. 

According to https://www.mapbox.com/help/mobile-offline/:
For the default Mapbox Streets style, some typical total sizes are:
City of Barcelona: 83 MB.
Greater London within the M25 at zoom levels 0–15: 120 MB.
Contiguous United States at zoom levels 0–9: 290 MB.
For Mapbox Satellite:

City of Barcelona: 45 MB.
Greater London within the M25 at zoom levels 0–15: 400 MB.
Contiguous United States at zoom levels 0–9: 315 MB.

### Actual behavior
The download of 2 tiles takes 70mb.

**Comment by jfirebaugh** [comment] 2017-11-17 15:31
Duplicate of #6292.

**Closed by jfirebaugh** 2017-11-17 15:31 UTC
Labels: iOS, offline
