### ISSUE TITLE
Polyline segments visibly overlap with alpha < 1

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#1771] opened 2015-06-22 20:19 UTC
If you draw a MGLPolyline with an alpha < 1, the colour multiplies where segments overlap and it looks a little strange.

![2015-06-22 at 21 17](https://cloud.githubusercontent.com/assets/565/8291929/623ef874-1924-11e5-9ff9-f4f37a25eaae.png)

**Comment by 1ec5** [comment] 2015-06-22 20:45
Compounding the effect, each line segment appears to have a round line cap and a square line cap.

**Comment by incanus** [comment] 2015-06-23 21:24
Ah, at first I thought this was a factor of line _joins_, which place a dot at the junction, but it does look like caps instead. 

Related: https://github.com/mapbox/mapbox-gl-native/issues/1734

**Comment by tomtaylor** [comment] 2015-07-01 05:14
@incanus: Does this look like a relatively easy fix? It's one of two outstanding bugs that are preventing me shipping an app on MapboxGL (modifying the logo and attribution buttons being the other), and it'd be amazing if they could get rolled into the next release. Even just an ETA would be helpful - thanks! Let me know if there's a better channel for this.

**Comment by incanus** [comment] 2015-07-01 05:24
@jfirebaugh @ansis Do you have a sense how tough this fix is?

**Comment by incanus** [comment] 2015-07-01 05:33
I think we can experiment with the line join here to fix this without adverse effects. I will check it out.

**Comment by ansis** [comment] 2015-07-01 09:24
@incanus see https://github.com/mapbox/mapbox-gl-js/issues/794#issuecomment-115646423

The quickest workaround is to use `"line-join": "miter"`, which is the default line join type.

**Comment by incanus** [comment] 2015-07-01 15:19
Test line is `0.5` alpha, `10.0` line width, `[UIColor blueColor]`. 

Line join for polyline annotations is set here: 

https://github.com/mapbox/mapbox-gl-native/blob/295ea0856becc35fe77ee7c207f533be3b7589ee/src/mbgl/map/map_context.cpp#L214-L217

Current (`round`): 

![ios simulator screen shot jul 1 2015 11 11 47 am](https://cloud.githubusercontent.com/assets/17722/8457963/58a1b7ce-1fe2-11e5-8643-c7d6853ff45e.png)

Reverting to the default of `miter` looks like this: 

![ios simulator screen shot jul 1 2015 11 13 52 am](https://cloud.githubusercontent.com/assets/17722/8457969/6d551b02-1fe2-11e5-856e-4b0f8a97fc54.png)

So, the join problems are fixed, but the line is jagged, especially at sharp turns. This was the main reason I used `round` in the first place. 

Just for completeness, here's `bevel`: 

![ios simulator screen shot jul 1 2015 11 17 08 am](https://cloud.githubusercontent.com/assets/17722/8458044/c931c5a6-1fe2-11e5-824e-398198b93688.png)

Looks better, but still problematic on sharp corners. 

Lastly, `flipbevel`, whatever that is: 

![ios simulator screen shot jul 1 2015 11 17 30 am](https://cloud.githubusercontent.com/assets/17722/8458058/dbe7bd40-1fe2-11e5-9f42-961e276b17f0.png)

**Comment by incanus** [comment] 2015-07-01 15:23
Experimenting with `line-miter-limit`.

**Comment by ansis** [comment] 2015-07-01 15:26
hmm, it looks like there are some tessellation bugs.

`flipbevel` is just for internal use. Bevels are drawn two different ways depending on the sharpness of the corner.

**Comment by incanus** [comment] 2015-07-01 15:37
@tomtaylor Based on this, it doesn't appear to be a trivial fix. Would it help if we work a bit on https://github.com/mapbox/mapbox-gl-native/issues/1734 and expose settings like the line join, so you can choose based on your data? Maybe you won't have sharp corners and a `miter` join would look ok?

**Comment by incanus** [comment] 2015-07-01 15:42
Here's a good patch for testing this by the way, using the default test shape of the hike up in northern Washington: 

```diff
diff --git a/ios/app/MBXViewController.mm b/ios/app/MBXViewController.mm
index 0024582..a19f8bd 100644
--- a/ios/app/MBXViewController.mm
+++ b/ios/app/MBXViewController.mm
@@ -347,12 +347,12 @@ mbgl::Settings_NSUserDefaults *settings = nullptr;
 
 - (CGFloat)mapView:(__unused MGLMapView *)mapView alphaForShapeAnnotation:(MGLShape *)annotation
 {
-    return ([annotation isKindOfClass:[MGLPolygon class]] ? 0.5 : 1.0);
+    return ([annotation isKindOfClass:[MGLPolygon class]] ? 0.5 : 0.5);
 }
 
 - (UIColor *)mapView:(__unused MGLMapView *)mapView strokeColorForShapeAnnotation:(MGLShape *)annotation
 {
-    return ([annotation isKindOfClass:[MGLPolyline class]] ? [UIColor purpleColor] : [UIColor blackColor]);
+    return ([annotation isKindOfClass:[MGLPolyline class]] ? [UIColor blueColor] : [UIColor blackColor]);
 }
 
 - (UIColor *)mapView:(__unused MGLMapView *)mapView fillColorForPolygonAnnotation:(__unused MGLPolygon *)annotation
@@ -360,6 +360,11 @@ mbgl::Settings_NSUserDefaults *settings = nullptr;
     return (annotation.pointCount > 3 ? [UIColor greenColor] : [UIColor redColor]);
 }
 
+- (CGFloat)mapView:(__unused MGLMapView * __nonnull)mapView lineWidthForPolylineAnnotation:(__unused MGLPolyline * __nonnull)annotation
+{
+    return 10;
+}
+
 - (void)mapView:(__unused MGLMapView *)mapView didChangeUserTrackingMode:(MGLUserTrackingMode)mode animated:(__unused BOOL)animated
 {
     UIImage *newButtonImage;
diff --git a/src/mbgl/map/map_context.cpp b/src/mbgl/map/map_context.cpp
index fa06a42..64d81a3 100644
--- a/src/mbgl/map/map_context.cpp
+++ b/src/mbgl/map/map_context.cpp
@@ -213,7 +213,8 @@ void MapContext::updateAnnotationTiles(const std::unordered_set<TileID, TileID::
 
             // apply line layout properties to bucket
             if (shapeStyle.is<LineProperties>()) {
-                shapeBucket->layout.set(PropertyKey::LineJoin, ConstantFunction<JoinType>(JoinType::Round));
+                shapeBucket->layout.set(PropertyKey::LineJoin, ConstantFunction<JoinType>(JoinType::Miter));
+                shapeBucket->layout.set(PropertyKey::LineMiterLimit, ConstantFunction<float>(10));
             }
 
             // connect layer to bucket
```

**Comment by mb12** [comment] 2015-07-01 15:45
@ansis and @incanus  Tesselation bug/line smudginess is very similar to what I've seen on  Android devices (consistently reproducible on Samsung Nexus S).  I am referring to the following issue.  Lines on some Android device show the kind of smudginess that is included in the screenshots above. Smudginess gets worse upon pan/scroll.

https://github.com/mapbox/mapbox-gl-native/issues/1702

**Comment by tomtaylor** [comment] 2015-07-01 15:50
Hi @incanus and co, thanks a lot for looking at this. Yeah, I think I'm unlikely to have sharp corners or overlaps, so exposing some more options would help enough that I could get this out the door. Much appreciated.

**Comment by incanus** [comment] 2015-07-06 16:49
@tomtaylor We are looking at this directly in #1839 and are hoping to roll it into the next dev build, ideally today, with the milestone build later this week.

**Comment by tomtaylor** [comment] 2015-07-06 19:23
@incanus great, thanks!

**Comment by incanus** [comment] 2015-07-07 23:57
@tomtaylor If I were to roll a custom build for you, would you be able to try it out? What are you using for install method? #1839 is looking pretty good in our testing.

**Comment by tomtaylor** [comment] 2015-07-08 06:30
@incanus sure thing. I'm using CocoaPods, currently pointing at the podspec on master. If you could provide me with a different podspec URL, I could try that?

**Comment by incanus** [comment] 2015-07-08 16:18
@tomtaylor Give this one a shot: 

    https://raw.githubusercontent.com/mapbox/mapbox-gl-native/1771-shape-tolerance/ios/MapboxGL.podspec

**Comment by tomtaylor** [comment] 2015-07-08 16:27
@incanus that looks identical to me - no changes from the original issue. Are you sure that's pointing to the correct build?

**Comment by incanus** [comment] 2015-07-08 16:28
Oh, shoot, I forget to combine the simplification changes (included) with https://github.com/mapbox/mapbox-gl-native/pull/1839 (not included). Sorry to waste your time — one sec.

**Comment by incanus** [comment] 2015-07-08 16:37
Ok @tomtaylor, trash your `Pods` and `pod update` with the same URL and it should grab a different build. This one has the line join improvements from #1839 and a tweak to the polygon simplification as well to make them less pronounced.

**Comment by tomtaylor** [comment] 2015-07-08 16:45
Thanks, that works. (I had to flush `~/Library/Caches/CocoaPods` too, just FYI.)

It's almost perfect, but there's a couple of little join glitches still. Much better than it was. They usually disappear when you zoom in 1 or 2 levels. Maybe increase the simplification a bit further?

![2015-07-08 at 17 42](https://cloud.githubusercontent.com/assets/565/8576290/cd539eaa-2598-11e5-93b8-26d1a95805fe.png)

![2015-07-08 at 17 44](https://cloud.githubusercontent.com/assets/565/8576306/f91ee440-2598-11e5-9f2f-a5249867c014.png)

**Comment by incanus** [comment] 2015-07-08 17:24
I'm wary to tweak the simplification for the specific case in light of affecting the general case. I also don't really want to expose simplification settings to the user as this gets complex. 

FWIW https://github.com/mapbox/mapbox-gl-native/commit/888ae5ebdc11703023ada9bc3dd1d113cfe52314 and https://github.com/mapbox/mapbox-gl-native/commit/03c4ed75a2684b9866a00eebf0392c96cceb8d34 just landed in master, so tonight's regular build will have the same effect as the custom build from https://github.com/mapbox/mapbox-gl-native/issues/1771#issuecomment-119652693.

**Comment by tomtaylor** [comment] 2015-07-08 18:10
Sure, understood. Thanks a lot - when the sprite customisation has landed I'll be able to ship this app.

**Comment by incanus** [comment] 2015-07-08 18:11
That just got merged — expect a build shortly.

**Comment by incanus** [comment] 2015-07-08 18:39
Going to move this off of the b3 milestone as we've made improvements here. We'll keep working on this — the end goal is zero overlap.

**Comment by picciano** [comment] 2015-09-29 17:16
This seems mostly resolved, but we are still seeing the occasional overlap, especially in angles < 90°.

![simulator screen shot sep 29 2015 11 12 33 am](https://cloud.githubusercontent.com/assets/417933/10172219/75b1a00e-669b-11e5-83a3-61f2e384e763.png)

**Closed** 2018-11-24 10:56 UTC
Labels: Core, archived, bug
