### ISSUE TITLE
[Android] NativeMapView crash

### ISSUE THREAD

**Issue by joaopedro1520** [mapbox/mapbox-gl-native#9007] opened 2017-05-15 21:23 UTC
**Platform:** Android
**Mapbox SDK version:** 4.2.0 - 5.1.0

I have been using the sdk since version 4.2.0 and I've been getting this crash on my logs.
Am I doing something wrong? 
Thanks

`Fatal Exception: java.lang.Error: program failed to link
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(SourceFile)
       at com.mapbox.mapboxsdk.maps.NativeMapView.render(SourceFile:178)
       at com.mapbox.mapboxsdk.maps.MapView.onDraw(SourceFile:420)
       at android.view.View.draw(View.java:14600)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.getDisplayList(View.java:13579)
       at android.view.View.draw(View.java:14313)`

Also this one 

`Fatal Exception: java.lang.Error: eglSwapInterval() failed
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(SourceFile)
       at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(SourceFile:157)
       at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceCreated(SourceFile:440)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:583)
       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2049)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)`

**Comment by jfirebaugh** [comment] 2017-05-15 22:37
Duplicate of #6112.

**Closed by jfirebaugh** 2017-05-15 22:37 UTC
