### ISSUE TITLE
[iOS] [Mason] duplicate symbols on static library

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#3366] opened 2015-12-21 10:30 UTC
From a clean master branch pull, I run "make ipackage".
It ends correctly (lib mapbox compiled and linked) but with warnings about duplicated symbols from geojsonvt.
When used, this library has duplicated symbols preventing our app to link.

Further more, Mason keeps old geojson libs / headers on our build machine, so it even more confused about duplicated symbols.

Mapbox lib error output: 
```
Building static library...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: armv7 same member name (tile.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(tile.o) and: gyp/build/Release-iphoneos/libmbgl-core.a(tile.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: armv7 same member name (transform.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(transform.o) and: gyp/build/Release-iphoneos/libmbgl-core.a(transform.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: armv7s same member name (tile.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(tile.o) and: gyp/build/Release-iphoneos/libmbgl-core.a(tile.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: armv7s same member name (transform.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(transform.o) and: gyp/build/Release-iphoneos/libmbgl-core.a(transform.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: i386 same member name (tile.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(tile.o) and: gyp/build/Release-iphonesimulator/libmbgl-core.a(tile.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: i386 same member name (transform.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(transform.o) and: gyp/build/Release-iphonesimulator/libmbgl-core.a(transform.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: x86_64 same member name (tile.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(tile.o) and: gyp/build/Release-iphonesimulator/libmbgl-core.a(tile.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: x86_64 same member name (transform.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(transform.o) and: gyp/build/Release-iphonesimulator/libmbgl-core.a(transform.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: arm64 same member name (tile.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(tile.o) and: gyp/build/Release-iphoneos/libmbgl-core.a(tile.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: arm64 same member name (transform.o) in output file used for input files: mason_packages/ios-9.2/geojsonvt/3.1.0/lib/libgeojsonvt.a(transform.o) and: gyp/build/Release-iphoneos/libmbgl-core.a(transform.o) due to use of basename, truncation and blank padding
Created build/ios/pkg/static/libMapbox.a
```

**Comment by 1ec5** [comment] 2015-12-21 10:33
If the issue is in Mason, please [report the bug in that repo](https://github.com/mapbox/mason/).

**Comment by RomainQuidet** [comment] 2015-12-21 10:42
@1ec5 I don't know yet, I'm trying to understand your project generation / compilation process, it's quite obscure for me. But the issue for me is on mapbox scripts, they include the libgeojsonvt.a in the final static lib, but it seems already included from libmbgl-core.a

**Comment by 1ec5** [comment] 2015-12-21 10:43
@mikemorris, I’m seeing these warnings too. Any idea what’s changed?

**Comment by RomainQuidet** [comment] 2015-12-21 10:44
@1ec5 you don't see the issue on the demo app as it is not using the final lib as third party developers do

**Comment by 1ec5** [comment] 2015-12-21 10:45
Regarding the old versions of the libraries, be sure to run `make clean && make distclean` (and possibly `rm -rf gyp/build/`) if you haven’t done so recently.

**Comment by RomainQuidet** [comment] 2015-12-21 10:46
@1ec5 we always do a make clean, I haven't see the distclean ! I'll try thanks

**Comment by RomainQuidet** [comment] 2015-12-21 13:07
Seems that core.gypi sets the core lib including geojsonvt static lib, and again in package.sh, the last step "building static library..." add again the geojsonvt static lib .a file...

**Comment by RomainQuidet** [comment] 2015-12-21 13:14
@1ec5 tested and validated: I removed the geojsonvt static lib include from the package.sh script, it works great now. Do you need a pull request or do you have somebody responsible for the build mechanism at MapBox?

**Comment by RomainQuidet** [comment] 2015-12-21 15:50
after several tests, it seems that the libmapbox.a is ok, but libtool has issues with fat lib... I don't see any duplicated symbols in libmapbox.a. 
Libtool had a bug like that back in 2010, maybe it's back again...

**Comment by mikemorris** [comment] 2015-12-21 18:45
Okay, so the double-linking of `geojsonvt.a` was implemented in https://github.com/mapbox/mapbox-gl-native/commit/79a5a960370a1bfcb8a90a628d85b8cd6d9b6a76, IIRC because the geojsonvt.a symbols linked in core.gypi are optimized of the core.a static library (the code paths are only used by platform implementations), so the symbols were missing unless explicitly linked in [`platform/ios/scripts/package.sh`](https://github.com/mapbox/mapbox-gl-native/blob/49bfdd662ff37ac77cd702c2cef92d2de8874be9/platform/ios/scripts/package.sh#L86) - I'm pretty sure this is an issue specific to our build system, not a general mason bug.

**Comment by mikemorris** [comment] 2015-12-21 18:46
> libtool has issues with fat lib

libtool as used in `package.sh` or as part of your implementation @RomainQuidet?

**Comment by RomainQuidet** [comment] 2015-12-22 10:17
@mikemorris Hi. Libtool is used by your package.sh as standard build mechanism (behind xcode-build). 
The build mechanism is loosing Xcode tools somewhere because of the double include. This prevent us to use the mapbox lib for the moment.

**Comment by mikemorris** [comment] 2015-12-22 19:56
I'm seeing this issue as far back as 79a5a960370a1bfcb8a90a628d85b8cd6d9b6a76, but I don't recall seeing this at all during earlier testing - I wonder if this could be related to the version of `libtool` packaged with a newer release of Xcode?

**Comment by 1ec5** [comment] 2015-12-22 22:26
Also reproduces in Xcode 7.1.

**Comment by 1ec5** [comment] 2015-12-22 23:15
This is related to the new Xcode version, but it isn’t libtool:

1. `sudo xcode-select -s /Applications/Xcode-72.app/`
1. `make clean && make distclean && rm -rf gyp/build && make ipackage-sim`
1. Link from an application in Xcode 7.2.
  * Linker errors
1. `sudo xcode-select -s /Applications/Xcode-71.app/`
1. `make ipackage-sim`
1. Link from an application in Xcode 7.2.
  * Linker errors
1. `sudo xcode-select -s /Applications/Xcode-71.app/`
1. `make clean && make distclean && rm -rf gyp/build && make ipackage-sim`
1. Link from an application in Xcode 7.2.
  * Success

Also, [geojsonvt-3.1.0](https://github.com/mapbox/mason/tree/geojsonvt-3.1.0) landed in Mason just within the last week. I wonder whether there are any relevant differences with [geojsonvt-3.0.1](https://github.com/mapbox/mason/tree/geojsonvt-3.0.1).

**Comment by 1ec5** [comment] 2015-12-23 02:02
The warnings themselves are slightly older than the linker errors: due to mapbox/geojson-vt-cpp@a55d31cdc6238ff556ef44cbdf377ba67978d228 and mapbox/geojson-vt-cpp@cc08ac50b069f78d9c7aaf70d8ee60c985c09a2f, libgeojsonvt and libmbgl-core have two compilation units with the same name (tile.cpp and transform.cpp). This collision has occurred since we started using v3.0.0 of libgeojsonvt in #3232.

**Comment by 1ec5** [comment] 2015-12-23 05:34
@RomainQuidet, after running `make clean && make distclean && rm -rf gyp/build/`, then either `make ipackage` or `make iframework`, I no longer see link errors when linking the static library into an application for the simulator. I believe `rm -rf gyp/build/` was the difference.

The warnings remain, so I’m leaving this ticket open to track them.

**Comment by mikemorris** [comment] 2015-12-23 16:37
@1ec5 We should probably add `rm -rf gyp/build/` to either `make clean` or `make distclean` tasks.

**Comment by 1ec5** [comment] 2016-04-18 04:04
No longer seeing this issue after #4641 landed.

**Closed by 1ec5** 2016-04-18 04:04 UTC
Labels: build, iOS
