### ISSUE TITLE
[iOS SDK] Build error: default property attribute assign not appropriate for non-GC object

### ISSUE THREAD

**Issue by Ra1nWarden** [mapbox/mapbox-gl-native#5923] opened 2016-08-10 05:33 UTC
**Platform: iOS**
**Mapbox SDK version: 3.3.4**

### Steps to trigger behavior

 1. Install using cocoapod
 2. Use `MGLMapView`
 3. Run

### Expected behavior

Compiles and runs

### Actual behavior

Got a build error: `default property attribute assign not appropriate for non-GC object` for these two properties. [1](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.h#L214) [2](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.h#L156)
Adding `strong` to them compile fine.
Is there something I am missing?
Thanks for any help!

**Comment by 1ec5** [comment] 2016-08-10 16:12
What version of Xcode are you using?

**Comment by Ra1nWarden** [comment] 2016-08-10 16:29
Hi @1ec5 I am using XCode 7.3.1

**Comment by Ra1nWarden** [comment] 2016-08-10 16:51
BTW, I am coding in Swift.

**Comment by 1ec5** [comment] 2016-08-10 17:07
Are you using the SDK in a manual retain-release (MRR) or garbage-collected (GC) target? The SDK requires ARC instead.

**Comment by Ra1nWarden** [comment] 2016-08-10 18:14
And yes! I do have ARC enabled. I am not sure why the default is `assign`. Is `assign` expected from the Mapbox's side? If not, could those two `strong` be added in the next release?  Thanks!

**Comment by 1ec5** [comment] 2016-08-10 18:59
This is very strange. This error is associated with ARC being disabled on the target or disabled on a particular file (in this case MGLMapView.h). I’ve never seen the error before in relation to the SDK and am unable to reproduce it with Mapbox iOS SDK v3.3.4 in Xcode 7.3.1 deploying back to iOS 8.0. Any unusual build settings or configurations that we should be aware of?

**Comment by boundsj** [comment] 2016-08-10 19:49
HI @Ra1nWarden. Using Xcode 7.3.1, Swift, deployment target of iOS 8, and Mapbox 3.3.4 via cocoapods, I created a new app with an MGLMapView set up in the app's storyboard (instructions for all of this are [here](https://www.mapbox.com/ios-sdk/) in the cocoapods tab). The application built and ran fine with no warnings or errors on both the simulator and device.

Also, the properties you've noted are objects (`NSArray` and `NSURL`). Object properties have a default of `strong` for memory management under ARC.

> And yes, I do have ARC enabled.

In my project, when I set `Objective-C Automatic Reference Counting` to NO **AND** I use an Objective-C file for my view controller code (and create and add the map view programmatically), I get the same warnings you've noted above. It seems like you may have turned on "warnings as errors"  and are **not** actually using ARC and may also be using both Objective-C and Swift in your project. In any case, that is the only way I can repro.

I think it may be helpful for you to start over and follow our [cocoapods instructions](https://www.mapbox.com/ios-sdk/) in the cocoapods tab) to create a simple project. Then, double check each of the variables above in your problematic project to make sure you are using ARC.

**Comment by boundsj** [comment] 2016-08-11 16:28
I'm going to close this issue since I'm not able to determine any additional actions we can take at the moment.

**Closed by boundsj** 2016-08-11 16:28 UTC
Labels: build, iOS

**Comment by Ra1nWarden** [comment] 2016-08-11 16:33
Thanks @boundsj for the help!
