### ISSUE TITLE
xml zoom not working in combination with location tracking

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#8538] opened 2017-03-27 19:06 UTC
when setting the camera zoom inside the activities XML layout, and then enabling user location tracking in the onMapReady callback, the zoom is ignored.

```java
mapboxMap.setMyLocationEnabled(true);
mapboxMap.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);
```

cc: @Guardiola31337 @tobrun

**Comment by tobrun** [comment] 2017-03-29 13:03
I'm unable to reproduce using [this](https://gist.github.com/tobrun/e810823a6e1023978d1dd78ecd216016) code. 

![ezgif com-video-to-gif 31](https://cloud.githubusercontent.com/assets/2151639/24455675/c7bffc02-1490-11e7-8c78-bb69f34d0866.gif)

**Comment by tobrun** [comment] 2017-03-30 06:56
reopen if you have more information. Closing as non reproducible.

**Closed by tobrun** 2017-03-30 06:56 UTC
Labels: Android, bug
