### ISSUE TITLE
[IOS] Load WMS to magnify derangement

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#14936] opened 2019-06-17 10:15 UTC
I used the mapbox-ios SDK, loaded a WMS service that geosever had been published, and began to zoom out.
My colleagues used openLayers imageWMS to load the whole thing, so how can mapbox be used in this way?

![热力图GIF](https://user-images.githubusercontent.com/15685672/59597149-c5395180-912b-11e9-92d0-11a0050f3006.gif)

<img width="1233" alt="屏幕快照 2019-06-17 下午6 10 08" src="https://user-images.githubusercontent.com/15685672/59597223-e306b680-912b-11e9-94e8-8e76470b9b44.png">

If possible, please do not close it, no one answers me in other places, thank you!

**Comment by tmpsantos** [comment] 2019-06-17 14:09
@songyuyang0918 can you provide a link to the style you are using?

**Comment by songyuyang0918** [comment] 2019-06-18 02:34
@tmpsantos  "MoreUrl" is my style link, which I put in a json file to test.

**Comment by halset** [comment] 2019-06-19 08:28
The last screen shot uses GetFeatureInfo instead of the normal GetMap.
Could you provide text instead of screen shots? That would be easier to work with.

**Comment by tmpsantos** [comment] 2019-06-25 19:07
The URL also points to a local network IP. :-( Closing this issue because we have no means to reproduce. Please feel free to reopen if there is a easy way to test/debug.

**Closed by tmpsantos** 2019-06-25 19:07 UTC

**Comment by songyuyang0918** [comment] 2019-07-02 09:42
Finally, I tried to get the elements using geosever's WFS service and use MGLHeatmapStyleLayer to generate it, but I needed to synchronize with the web side (using openlayers) display, and something went wrong.

Geoserver geoserver is a heatmap in this way:

<?xml version="1.0" encoding="UTF-8"?>
   <StyledLayerDescriptor version="1.0.0"
       xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd"
       xmlns="http://www.opengis.net/sld"
       xmlns:ogc="http://www.opengis.net/ogc"
       xmlns:xlink="http://www.w3.org/1999/xlink"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
     <NamedLayer>
       <Name>accMV03</Name>
       <UserStyle>
         <Title>accMV03</Title>
         <Abstract>A heatmap </Abstract>
         <FeatureTypeStyle>
           <Transformation>
             <ogc:Function name="gs:Heatmap">
               <ogc:Function name="parameter">
                 <ogc:Literal>data</ogc:Literal>
               </ogc:Function>
               <ogc:Function name="parameter">
                 <ogc:Literal>weightAttr</ogc:Literal>
                 <ogc:Literal>CLOUDCOVER</ogc:Literal>
               </ogc:Function>
               <ogc:Function name="parameter">
                 <ogc:Literal>radiusPixels</ogc:Literal>
                 <ogc:Function name="env">
                   <ogc:Literal>radius</ogc:Literal>
                   <ogc:Literal>35</ogc:Literal>
                 </ogc:Function>
               </ogc:Function>
               <ogc:Function name="parameter">
                 <ogc:Literal>pixelsPerCell</ogc:Literal>
                 <ogc:Literal>2</ogc:Literal>
               </ogc:Function>
               <ogc:Function name="parameter">
                 <ogc:Literal>outputBBOX</ogc:Literal>
                 <ogc:Function name="env">
                   <ogc:Literal>wms_bbox</ogc:Literal>
                 </ogc:Function>
               </ogc:Function>
               <ogc:Function name="parameter">
                 <ogc:Literal>outputWidth</ogc:Literal>
                 <ogc:Function name="env">
                   <ogc:Literal>wms_width</ogc:Literal>
                 </ogc:Function>
               </ogc:Function>
               <ogc:Function name="parameter">
                 <ogc:Literal>outputHeight</ogc:Literal>
                 <ogc:Function name="env">
                   <ogc:Literal>wms_height</ogc:Literal>
                 </ogc:Function>
               </ogc:Function>
             </ogc:Function>
           </Transformation>
          <Rule>
            <RasterSymbolizer>
            
              <Geometry>
                <ogc:PropertyName>geom</ogc:PropertyName>
              </Geometry>
              <Opacity>1</Opacity>
                <ColorMap type="ramp" >
                  <ColorMapEntry color="#FFFFFF" quantity="0" opacity="0" label="FFFFF" />
                  <ColorMapEntry color="#7F95E6" quantity="0.1" opacity="0.5" label="7F95E6" />
                  <ColorMapEntry color="#7DFC3F" quantity="0.3" opacity="0.5" label="7DFC3F" />
                  <ColorMapEntry color="#F6FD01" quantity="0.4" opacity="0.5" label="F6FD01" />
                  <ColorMapEntry color="#EF8C07" quantity="0.5" opacity="0.5" label="EF8C07" />
                  <ColorMapEntry color="#FE0409" quantity="0.7" opacity="0.5" label="FE0409" />
                  <ColorMapEntry color="#FE0409" quantity="1" opacity="0.5" label="FE0409" />
                  </ColorMap>
            </RasterSymbolizer>
           </Rule>
         </FeatureTypeStyle>
       </UserStyle>
     </NamedLayer>
    </StyledLayerDescriptor>

I made the same Settings in mapbox according to his Settings:

<img width="1812" alt="屏幕快照 2019-07-02 下午5 28 49" src="https://user-images.githubusercontent.com/15685672/60501853-50e7dc00-9cef-11e9-939d-cad51519baeb.png">

The json data I get (truncated because it's too big):
[热力数据.txt](https://github.com/mapbox/mapbox-gl-native/files/3349374/default.txt)

Effects:
<img width="1348" alt="屏幕快照 2019-07-02 下午5 41 01" src="https://user-images.githubusercontent.com/15685672/60502560-a2dd3180-9cf0-11e9-9143-040b32561445.png">

Results:
Can you help me find that the weights are completely different?

**Comment by songyuyang0918** [comment] 2019-07-04 10:21
@tmpsantos  @halset 
About the above questions, I found the answer in a reply (https://gis.stackexchange.com/questions/244789/geoserver-heatmap-wms-style-problem/290132), the result is bad, describe the geoserver heatmap is not support flat section, in IOS, I can't find any plug-in can solve this problem, so I follow his guidance, to image loading way.

I started testing how to load images:
But I found that when level:1-4 was loaded in the wrong place.
Level :5-max. All correct.
I do this by taking the bounds of the current screen and turning it to quad.

Effect:
![热力图GIF](https://user-images.githubusercontent.com/15685672/60659366-cab2cd80-9e87-11e9-8071-c2a8e141df00.gif)

Code:
<img width="1814" alt="屏幕快照 2019-07-04 下午6 16 58" src="https://user-images.githubusercontent.com/15685672/60659424-f59d2180-9e87-11e9-98c7-42afa98cdcf1.png">

I don't know what the problem is.

Next, I tried to load MGLHeatmapStyleLayer through WFS factor data.

Since my data is of type MultiPolygon, I found that mapbox only supports point to heatmap, so what should I do?
I've been beaten...
Please help me, thank you!

**Comment by halset** [comment] 2019-07-04 10:36
It looks like are trying to fit a non-projected EPSG:4326 WMS image on to a spherical mercator EPSG:3857 MGLMapView. That will not fit well when zoomed out, but will look pretty good when zoomed in.

Perhaps you can do a GetMap with EPSG:3857. Make sure that the BBOX then has coordinates in EPSG:3857 as well.

**Comment by songyuyang0918** [comment] 2019-07-04 10:45
Can mapbox get bounds of epsg:3857 directly? Or the method of transforming 3857 coordinates. I try a set of algorithms to convert, double to receive, but there is always a coordinate will appear "nan" situation!?

**Comment by halset** [comment] 2019-07-04 10:52
I do not know if mapbox has code for it. I do the following.
```objective-c
+(NSString *)bboxPart:(CLLocationCoordinate2D)ll
{
    double x = ll.longitude * 20037508.34 / 180;
    double y = log(tan((90 + ll.latitude) * M_PI / 360)) / (M_PI / 180);
    y = y * 20037508.34 / 180;
    return [NSString stringWithFormat:@"%f,%f", x, y];
}
```

**Comment by songyuyang0918** [comment] 2019-07-04 10:59
It's very coincidental that I also use this code to convert. The longitude and latitude conversion of a point is no problem. When I try to convert the four longitude and latitude coordinates of bounds, it will be out of order. There will always be a point named "nan".

**Comment by songyuyang0918** [comment] 2019-07-05 08:57
@halset  Hi!halset!
After today's discussion, I think it is the resolution of the picture.
Although you said that EPSG would cause different positions, we believe that there might be deviation at the large level, but the deviation at the small level should not exist. Now I am trying to find pictures with different resolutions on the Internet, and how do you think about the adjustment of coordinate size in the room presented on the IOS map?

**Comment by songyuyang0918** [comment] 2019-07-08 10:23
@halset  Hi! halset!
You are very professional. There is a big gap between EPSG3857 and 4326.
My previous understanding may be wrong. We release 4326 service, which can be displayed by mapbox3857. Now it seems that mapbox transforms 4326 coordinate system into 3857 coordinate system when it is loaded.

Next I tried mapbox to load the WFS element, and I wanted to ask: does it only support point computing? If yes, do you have any plugins to convert the surface or line into points?

If you are interested in ppi(resolution) of images, can imageView set the default ppi?
Thank you very much for your help!
