### ISSUE TITLE
MGLMapView fails to bind EAGLDrawable when initialised with CGRect with no width and height

### ISSUE THREAD

**Issue by duemunk** [mapbox/mapbox-gl-native#1572] opened 2015-05-16 14:57 UTC
Initialising a `MGLMapView` with CGRectZero:

``` swift
let map = MGLMapView(frame: CGRectZero, accessToken: "_")
```

Crashes:

``` console
2015-05-16 16:56:35.782 SomeApp[35232:1946290] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x17403a940> to GL_RENDERBUFFER 1
2015-05-16 16:56:35.783 SomeApp[35232:1946290] Failed to make complete framebuffer object 8cd6
2015-05-16 16:56:35.800 SomeApp[35232:1946361] [ERROR] {0}{Map}[Shader]: Program failed to validate: Validation Failed: Current draw framebuffer is invalid.
```

Current workaround

``` swift
let map = MGLMapView(frame: CGRect(x: 0, y: 0, width: 1, height: 1), accessToken: "_")
```

**Comment by 1ec5** [comment] 2015-05-27 20:13
Via #1654, `MGLMapView` should also support `CGRectNull`.

**Comment by 1ec5** [comment] 2016-01-26 16:12
`-[MGLMapView wakeGL:]` should guard on `CGRectIsEmpty()`, and probably `CGRectIsInfinite()` while we’re at it. `-setFrame:` and `-setBounds:` should trigger this check and cause binding to occur if the frame changes from being empty (or infinite) to a reasonable value.

**Comment by 1ec5** [comment] 2016-02-22 17:22
Per #4065, initializing the map view with an empty frame no longer crashes. It looks like the validation step that was failing was removed in #2147.

**Comment by 1ec5** [comment] 2016-06-28 23:48
Per #5457, the crash has returned.

**Comment by 1ec5** [comment] 2016-07-01 17:09
We’re still unable to reproduce the crash, yet we do get reports about it in the wild. The fix would likely involve changes to mbgl, which we aren’t willing to take this close to a release. Punting to 3.4.0.

**Comment by DsrMedia** [comment] 2016-07-04 13:41
@1ec5 completely unrelated to MGLMapView: we have an SDK that inits a WKWebView with CGRectMake(0, 0, 0, 0) and also rarely crashes in the wild (6S Plus - sample size of only 2). We've also had this issue in the past, the workaround was to init the UIWebView we had with 1px height and width, however that workaround is not an option for us anymore with the WKWebView and other changes we've made to the SDK. Now this issue has popped back up on the 27th and 28th of June. We can artificially "reproduce" the crash by putting NAN in the CGRectMake somewhere, which will crash the app and print the following error:

> CALayerInvalidGeometry', reason: 'CALayer position contains NaN:

However reproducing it artificially doesn't help as we have no clue why it is NAN in the first place when we literally use: CGRectMake(0, 0, 0, 0) (or CGRectZero) without any calculations.

Let me know if this helps you and if you find out anything

**Comment by incanus** [comment] 2016-11-04 17:16
Lots of debugging background yesterday in https://github.com/mapbox/mapbox-gl-native/issues/6883, which we've closed in favor of the core problem here.

**Comment by brunoabinader** [comment] 2017-04-04 17:30
As per #8562, using a zeroed `CGRect` will cause the core to throw a runtime exception.

**Comment by 1ec5** [comment] 2017-04-04 17:48
Reopening: it’s very common for a UIView or NSView to be initialized with zero size and given a size at some point before or after being added to the view hierarchy. This crash is a gotcha for many developers.

**Comment by 1ec5** [comment] 2017-04-04 18:54
@brunoabinader proposes that MGLMapView always create `mbgl::Map` with a minimum size of 64×64 points, even if MGLMapView and EAGLView themselves are smaller than 64×64 points. This might work, although it might also throw off any calculations that are dependent on the screen location of the center coordinate at initialization.

**Comment by 1ec5** [comment] 2017-04-10 16:35
#8562 ended up implementing the 64x64-point workaround described above, which should address this crash and console spew.

**Closed by 1ec5** 2017-04-10 16:35 UTC
Labels: crash, Google Maps parity, iOS, macOS, MapKit parity
