### ISSUE TITLE
-[MGLMapView showAnnotations:] should span the antimeridian

### ISSUE THREAD

**Issue by ab-rdarts** [mapbox/mapbox-gl-native#8708] opened 2017-04-11 12:02 UTC
**Platform:**
iOS
**Mapbox SDK version:**
3.5.2

### Steps to trigger behavior

 1. Add annotations like (latitude:0, longitude:179), (latitude:0, longitude:0), (latitude:0, longitude:-180)
 2. use showAnnotations method

### Expected behavior
MapView shows three annotations

### Actual behavior
MapView shows only two annotations and only after pan map a little bit (doesn't work at all if not pan)

[TestMap.zip](https://github.com/mapbox/mapbox-gl-native/files/913075/TestMap.zip)

**Comment by 1ec5** [comment] 2017-04-13 08:47
It isn’t possible to zoom all the way out to the point where the Prime Meridian, antimeridian, and 179° east are all visible at the same time. The map is constrained to avoid showing multiple “copies” of the world simultaneously and to avoid showing anything beyond 85.051129° north or south (due to [Web Mercator](https://en.wikipedia.org/wiki/Web_Mercator) projection). In the sample application provided above, the map view is 375 points wide and 563 points tall. At this aspect ratio, attempting to show all three annotations would require breaking both of those constraints.

**Comment by jfirebaugh** [comment] 2017-04-13 17:00
@1ec5 Should we close this as working as designed then?

**Comment by ab-rdarts** [comment] 2017-04-13 17:19
@1ec5 I understand that in this particular case it's not possible to fit all annotations, but the problem in another side. you can move annotation (0, 0) close to other annotations so that it can fit. And in this case it will not work also, it will show only two of them which close to 180 longitude. You should take into account span of longitude and latitude instead of calculating min/max of longitudes

**Comment by 1ec5** [comment] 2017-04-13 18:02
That’s a good point, @ab-rdarts! I’ve retitled this issue to reflect the fact that `-showAnnotations:` should be able to straddle the antimeridian if necessary. This would require `mbgl::Map::cameraForLatLngs()` to be able to straddle the antimeridian as well.

**Comment by 1ec5** [comment] 2017-04-14 20:22
Fixed in #8744.

**Closed by 1ec5** 2017-04-14 20:22 UTC
Labels: annotations, iOS
