### ISSUE TITLE
Crash when no network is available

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1375] opened 2015-04-30 09:10 UTC
When trying to load assets and no network is available, I'm seeing this crash:

![http_request_nsurl mm 2015-04-30 11-09-48](https://cloud.githubusercontent.com/assets/52399/7409757/7a106bb0-ef29-11e4-9b2d-049d7bbf4b95.png)

**Comment by jfirebaugh** [comment] 2015-04-30 14:08
Duplicate of #1368. "no network is available" is a good hint though.

**Closed** 2015-04-30 14:08 UTC
Labels: iOS
