### ISSUE TITLE
issue with MIPS API

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5126] opened 2016-05-24 21:46 UTC
Trying to build the SNAPSHOT on bitrise failed, with a little more investigating with @bleege we were able to determine that this issue is specific to MIPS ABI, all others seem to work fine. Running `make apackage` locally resulted in this output:

```
...
CXX(target) Debug/obj.target/core/src/mbgl/geometry/static_vertex_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/text_buffer.o
  CXX(target) Debug/obj.target/core/src/mbgl/geometry/vao.o
  CXX(target) Debug/obj.target/core/src/mbgl/gl/debugging.o
  CXX(target) Debug/obj.target/core/src/mbgl/gl/gl.o
  CXX(target) Debug/obj.target/core/src/mbgl/gl/gl_config.o
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/annotation_manager-84c2c5.s: Assembler messages:
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/annotation_manager-84c2c5.s:166400: Warning: no .cprestore pseudo-op used in PIC code
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/annotation_manager-84c2c5.s:166400: Warning: macro instruction expanded into multiple instructions
  CXX(target) Debug/obj.target/core/src/mbgl/gl/gl_object_store.o
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/annotation_manager-84c2c5.s:220949: Warning: no .cprestore pseudo-op used in PIC code
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/annotation_manager-84c2c5.s:220949: Warning: macro instruction expanded into multiple instructions
  CXX(target) Debug/obj.target/core/src/mbgl/gl/texture_pool.o
  CXX(target) Debug/obj.target/core/src/mbgl/layer/background_layer.o
clang36++: error: unable to execute command: Segmentation fault: 11
clang36++: error: assembler command failed due to signal (use -v to see invocation)
clang version 3.6 
Target: mipsel-none-linux-android
Thread model: posix
clang36++: note: diagnostic msg: PLEASE submit a bug report to http://source.android.com/source/report-bugs.html and include the crash backtrace, preprocessed source, and associated run script.
  CXX(target) Debug/obj.target/core/src/mbgl/layer/circle_layer.o
clang36++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang36++: note: diagnostic msg: /var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/annotation_manager-cd4044.cpp
clang36++: note: diagnostic msg: /var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/annotation_manager-cd4044.sh
clang36++: note: diagnostic msg: 

********************
make[1]: *** [Debug/obj.target/core/src/mbgl/annotation/annotation_manager.o] Error 254
make[1]: *** Waiting for unfinished jobs....
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/feature_index-bf683d.s: Assembler messages:
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/feature_index-bf683d.s:20314: Warning: no .cprestore pseudo-op used in PIC code
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/feature_index-bf683d.s:20314: Warning: macro instruction expanded into multiple instructions
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/feature_index-bf683d.s:23187: Warning: no .cprestore pseudo-op used in PIC code
/var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/feature_index-bf683d.s:23187: Warning: macro instruction expanded into multiple instructions
clang36++: error: unable to execute command: Segmentation fault: 11
clang36++: error: assembler command failed due to signal (use -v to see invocation)
clang version 3.6 
Target: mipsel-none-linux-android
Thread model: posix
clang36++: note: diagnostic msg: PLEASE submit a bug report to http://source.android.com/source/report-bugs.html and include the crash backtrace, preprocessed source, and associated run script.
clang36++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang36++: note: diagnostic msg: /var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/feature_index-7df367.cpp
clang36++: note: diagnostic msg: /var/folders/5r/8wwfkz3n4x11bcfpqjly7fjh0000gn/T/feature_index-7df367.sh
clang36++: note: diagnostic msg: 

********************
make[1]: *** [Debug/obj.target/core/src/mbgl/geometry/feature_index.o] Error 254
make: *** [android-lib-mips] Error 2
```

cc: @jfirebaugh @kkaefer @tmpsantos @brunoabinader @bleege

**Comment by jfirebaugh** [comment] 2016-05-24 21:58
Looks like a compiler bug. My first instinct would be to try upgrading to clang 3.7 or later.

**Comment by bleege** [comment] 2016-05-24 22:03
Noting that this can be duplicated quicker using `make android-lib-mips` instead of running the full ABI building `make apackage`.

**Comment by jfirebaugh** [comment] 2016-05-24 22:48
Does this still occur after the NDK revert in 6abd3d70beb9233262fbbb2de1f780cdfc29bb5c?

**Comment by bleege** [comment] 2016-05-24 22:49
Yep, that's actually how @cammace discovered it when he went to roll a new SNAPSHOT build from `master` after the NDK revert this afternoon.

**Comment by bleege** [comment] 2016-05-25 01:18
> My first instinct would be to try upgrading to clang 3.7 or later.

I'm looking into this, but so far haven't found were the compiler is configured.  So far I've looked in:

* `Makefile`
* `mbgl.gypi`
* `platform/android/scripts/configure.sh`
* `platform/android/scripts/debug.sh`
* `platform/android/scripts/toolchain.sh`

Will continue looking.

**Comment by bleege** [comment] 2016-05-25 01:38
Running `make android` produces the following output from the `Makefile`.  It looks like the Mason is actually setting the Clang version via the `CXX` and `CC` environment variables and that it's setting them to use the Clang that comes with the Android NDK.  I'll dig into the Android NDK docs to see how customizable this version is.

```sh
MASON_PLATFORM="android" MASON_ANDROID_ABI="arm-v7" CXX="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/arm-9-r10e/bin/arm-linux-androideabi-clang++" CC="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/arm-9-r10e/bin/arm-linux-androideabi-clang" LD="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/arm-9-r10e/bin/arm-linux-androideabi-ld" LINK="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/arm-9-r10e/bin/arm-linux-androideabi-clang++" AR="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/arm-9-r10e/bin/arm-linux-androideabi-ar" RANLIB="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/arm-9-r10e/bin/arm-linux-androideabi-ranlib" STRIP="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/arm-9-r10e/bin/arm-linux-androideabi-strip" LDFLAGS="-target armv7-none-linux-androideabi -march=armv7-a -Wl,--fix-cortex-a8 -fuse-ld=gold -no-canonical-prefixes -Wl,--warn-shared-textrel -Wl,--fatal-warnings ${LDFLAGS:-}" CFLAGS="-target armv7-none-linux-androideabi -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -D_LITTLE_ENDIAN -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -fomit-frame-pointer -fstrict-aliasing -Wno-invalid-command-line-argument -Wno-unused-command-line-argument ${CFLAGS:-}" CXXFLAGS="-target armv7-none-linux-androideabi -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -D_LITTLE_ENDIAN -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -fomit-frame-pointer -fstrict-aliasing -Wno-invalid-command-line-argument -Wno-unused-command-line-argument ${CXXFLAGS:-}" CPPFLAGS="-D__ANDROID__ ${CPPFLAGS:-}" JNIDIR="armeabi-v7a" ./configure platform/android/scripts/configure.sh build/android-arm-v7/config.gypi android arm-v7
```

**Comment by bleege** [comment] 2016-05-25 02:45
Android NDK Doc called "Working With Clang" --> 
https://developer.android.com/ndk/guides/standalone_toolchain.html#wwc

**Comment by bleege** [comment] 2016-05-25 03:02
Getting MIPS compiler name from Mason via `make android-lib-mips`, which is going to correspond to the following configs on Mason --> 

https://github.com/mapbox/mason/tree/master/scripts/android-ndk/mips-9-r10e

```sh
MASON_PLATFORM="android" MASON_ANDROID_ABI="mips" CXX="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang++" CC="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang" LD="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ld" LINK="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-clang++" AR="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ar" RANLIB="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-ranlib" STRIP="/Users/brad/development/mapbox-gl-android/mason_packages/osx-x86_64/android-ndk/mips-9-r10e/bin/mipsel-linux-android-strip" LDFLAGS="-target mipsel-none-linux-android -no-canonical-prefixes -Wl,--warn-shared-textrel -Wl,--fatal-warnings ${LDFLAGS:-}" CFLAGS="-target mipsel-none-linux-android -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -fomit-frame-pointer -fstrict-aliasing -Wno-invalid-command-line-argument -Wno-unused-command-line-argument ${CFLAGS:-}" CXXFLAGS="-target mipsel-none-linux-android -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -fomit-frame-pointer -fstrict-aliasing -Wno-invalid-command-line-argument -Wno-unused-command-line-argument ${CXXFLAGS:-}" CPPFLAGS="-D__ANDROID__ ${CPPFLAGS:-}" JNIDIR="mips" ./configure platform/android/scripts/configure.sh build/android-mips/config.gypi android mips
```

**Comment by bleege** [comment] 2016-05-25 03:34
So looking at the `script.sh` for the MIPS compiler on Mason, it looks like we need to alter [the LLVM version here](https://github.com/mapbox/mason/blob/f93259daa3dceb542f8e17c76707576b99e7a32d/scripts/android-ndk/mips-9-r10e/script.sh#L33) in order to change LLVM / Clang to Version 3.7.  I'm not quite sure how to make this change and test it without committing this change to `master` on Mason (aka, "how do I point my local Mason file at branch?").  I'll need some help on this one.

From another angle, every time I run the MIPS compiler it consistently errors on the same file called `background_layer.o` as it did in @cammace's original debug log.  I'm wondering if there's something that has recently changed (since Monday) in the source that MIPS isn't cool with?  The reason being is that the last good nightly 4.1.0-SNAPSHOT is from Monday morning ([Number 34 on the repo](https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/4.1.0-SNAPSHOT/)).  Per commit CI only compiles on the default arm7 ABI to save a ton of processing time, while the nightly one builds for the entire 6 ABI suite (arm-v5, arm-v7, arm-v8, x86, x86-64, mips) so that it can produce a SNAPSHOT release.

**Comment by bleege** [comment] 2016-05-25 14:03
Picking this up this morning, since I don't know much about the finer points of Mason I'm going to see if I can timebox when MIPS stopped compiling so that we can get some insight into what likely is causing this pain.  To do this I'm first going to get the last commit before @kkaefer's NDK update ( 7272d7c84cf6e874b417ecd165f46f26ae7729c9 ) and run `make android-lib-mips` on it.  If it compiles then we have a baseline for when things stopped and I can then try again with a commit a little further in the future to narrow in on it.

**Comment by bleege** [comment] 2016-05-25 14:17
Yep, we've found our baseline!  `make android-lib-mips` compiles at 7272d7c84cf6e874b417ecd165f46f26ae7729c9.  So something has changed since Monday morning that has caused MIPS to break.  I'm going to try building next with @jfirebaugh's commit from the end of Monday 1f8de2be5ce39d878d4fd9e3d77ea55c7dacd619.  This will use the new NDK stuff, but the issue there wasn't that it wouldn't compile but that it would crash at run time.  Depending on how this goes I'll try to revert the NDK build locally again at that commit and see if it still compiles.

<img width="1039" alt="screen shot 2016-05-25 at 9 08 01 am" src="https://cloud.githubusercontent.com/assets/989928/15543084/11a20098-2259-11e6-9326-677f037f74f7.png">

**Comment by bleege** [comment] 2016-05-25 14:33
I just ran `make android-lib-mips` on 1f8de2be5ce39d878d4fd9e3d77ea55c7dacd619 and it compiled.  I noticed that it was using Clang 3.8 which is likely related to the NDK bump.  I'm going to revert the NDK bump locally now and try compiling with the old NDK to see if things are still good.

**Comment by bleege** [comment] 2016-05-25 15:11
Progress.  `make android-lib-mips` compiled after I reverted the NDK at @jfirebaugh's last commit on Monday ( 1f8de2be5ce39d878d4fd9e3d77ea55c7dacd619 ), which I noticed was using Clang 3.6.  To further test things out I ran a `make android` to create the arm ABI and then successfully ran it via the TestApp on my Samsung S5 (API 21).  This means that MIPS was broken yesterday (24-May-2016) somewhere.  My hunch is that it's somewhere between the NDK reversal commit and the first commit of the day from @brunoabinader (see screenshot below).  It looks like there were five different commit groups yesterday ( @brunoabinader , @jfirebaugh , @brunoabinader , @brunoabinader , and @1ec5 chronologically ).  I'm going to start with the first one from @brunoabinader and work my way through until I find where things break.

<img width="901" alt="screen shot 2016-05-25 at 9 54 03 am" src="https://cloud.githubusercontent.com/assets/989928/15545175/06e99c9e-2261-11e6-848c-83d9b5400760.png">

**Comment by bleege** [comment] 2016-05-25 15:38
Just compiled MIPS for @brunoabinader's 6938970dcca56bceef2045b73c114cba8ceb37e0 using Clang 3.6.  Next up is @jfirebaugh's 9732f02422eb5cd5852d47e888b061aaf6ffe0bd.

**Comment by bleege** [comment] 2016-05-25 15:42
Boom!  Found the range.  9732f02422eb5cd5852d47e888b061aaf6ffe0bd doesn't compile using Clang 3.6.  Will try it with Clang 3.8 (aka new NDK) to see how it plays.  Depending on the results we may be forced to update the NDK as originally attempted and then power through all the regressions.  We'll see.

**Comment by bleege** [comment] 2016-05-25 15:51
Ok, the Clang 3.8 (aka new NDK) compiled just fine for 9732f02422eb5cd5852d47e888b061aaf6ffe0bd.  This means we have a compiled Native Library, but one that won't run in the SDK nor apps.

I think the next course of action is determine which is the bigger lift:  1) Updating the NDK and working through all the regressions or 2) Undo whatever is causing MIPS on Clang 3.6 to break.  In order to do that I'm going to try to compile the 6 possible breaking commits for MIPS to see where it goes off the rails.  From there we'll know how big of a lift it'd be to undo it and then can make a decision on Option 1 or Option 2.

**Comment by bleege** [comment] 2016-05-25 16:04
I checked out the first of the commits ( c02d837a337f04966e7ea6223ec72138bc42c1a6 ) and then reverted the NDK commit on top of it to get Clang 3.6 back.  From there I ran `make android-lib-mips` and it compiled as expected.  The next one to try is 35de561bb451e5d61ff7ba36e03b06d6fac1cf40.

**Comment by bleege** [comment] 2016-05-25 16:09
35de561bb451e5d61ff7ba36e03b06d6fac1cf40 compiles with Clang 3.6

**Comment by bleege** [comment] 2016-05-25 16:13
a6e0870a3a4c2fa441a8d28fd9a9134c0e2af783 compiles with Clang 3.6.

**Comment by bleege** [comment] 2016-05-25 16:23
eb03611943fc1c6a57d8981eff754f97ce99d4c7 compiles with Clang 3.6.

**Comment by bleege** [comment] 2016-05-25 16:29
fc1c21202ae866e9978dccbe9411d8704b7e1140 compiles with Clang 3.6.

**Comment by bleege** [comment] 2016-05-25 17:06
Found it!  9732f02422eb5cd5852d47e888b061aaf6ffe0bd is where things come off the rails.  It turns out the code that breaks is switching from `Release` build to `Debug` build (see screenshot).  I'm not sure the impact of this nor what it's goals are.  I'll touch base offline with @jfirebaugh to learn more about it.  Once that's known we can decide between Option 1 (New NDK) or Option 2 (Revert Build Mode).

![screen shot 2016-05-25 at 12 03 19 pm](https://cloud.githubusercontent.com/assets/989928/15549180/18b4ace2-2271-11e6-8c35-373167fc2978.png)
_Breaking Commit For MIPS ABI on Clang 3.6_

**Comment by jfirebaugh** [comment] 2016-05-25 17:29
OK, so the issue is that Debug builds fail on MIPS with clang 3.6 -- and probably always have failed, we just never tried them before 9732f02422eb5cd5852d47e888b061aaf6ffe0bd.

The simple solution is to add `export BUILDTYPE=Release` to Android's bitrise.yml to go back to the state of affairs on CI prior to 9732f02422eb5cd5852d47e888b061aaf6ffe0bd. The iOS and OSX bitrise.yml's already do that, and I had mistakenly assumed that the Android bitrise.yml did too.

This doesn't actually fix Debug builds on MIPS -- the long term solution for that is to upgrade the NDK.

**Comment by bleege** [comment] 2016-05-25 18:05
> OK, so the issue is that Debug builds fail on MIPS with clang 3.6 -- and probably always have failed, we just never tried them before 9732f02422eb5cd5852d47e888b061aaf6ffe0bd.

Agreed.

I'll update Android's `bitrise.yml` as suggested and get a new SNAPSHOT out the door that we can experiment with to make sure that things are 💯 again.  I'll then coordinate with @tobrun @cammace about next steps.

> the long term solution for that is to upgrade the NDK.

Yep.  I've already got this ticketed out at #5123 and we can put this on the TODO list for the next release after `4.1.0 FINAL` ships.

Thanks @jfirebaugh!

**Comment by bleege** [comment] 2016-05-25 18:41
CI Approved and I've now merged.  We should be good to go.  I'm going to fire off a new SNAPSHOT build now and see how it plays!

**Comment by bleege** [comment] 2016-05-25 19:55
4.1.0-SNAPSHOT Number 36 is now live on the Maven Central SNAPSHOT repo.  I loaded it into the [Mapbox Android Demo App](https://github.com/mapbox/mapbox-android-demo) and it worked as shown below...

![device-2016-05-25-145259](https://cloud.githubusercontent.com/assets/989928/15554175/6886d468-2288-11e6-9ecb-9b74c1072426.png)

**Comment by tobrun** [comment] 2016-05-31 08:27
SNAPSHOTS are failing on Bitrise (#5187) and logs seem to indicate it's the same issue. Reopening.

**Comment by bleege** [comment] 2016-05-31 14:55
Initial review shows that the per commit builds (aka `primary`) are continuing to work while the `scheduled` workflow is not.

**Comment by tobrun** [comment] 2016-05-31 14:58
@bleege `per commit` doesn't build mips

**Comment by bleege** [comment] 2016-05-31 14:59
@tobrun Right.  Just establishing a baseline here.  😉

**Comment by bleege** [comment] 2016-05-31 16:10
Looking at the `bitrise.yml` on the `release-android-v4.1.0` branch shows that it's building the `Release` Build type as it should.  I'm going to update my local repo and try to build there to see if I can get more details than what Bitrise is sharing.

https://github.com/mapbox/mapbox-gl-native/blob/release-android-v4.1.0/platform/android/bitrise.yml#L77

**Comment by bleege** [comment] 2016-05-31 16:27
When building locally for MIPS with the latest commit from `release-android-v4.1.0` c66cf0f73fc1fb08d5b8397941e5c3845c88ccaa it fails (as expected) but when I change the `/Makefile` back to `Release` from `Debug` it does compile as expected.  This makes me wonder if somehow the `bitrise.yml` is having trouble setting the `BUILDTYPE` environment variable in time (or at all) for the build process to run.

**Comment by tmpsantos** [comment] 2016-05-31 16:30
> When building locally for MIPS with the latest commit from release-android-v4.1.0 c66cf0f it fails (as expected) but when I change the /Makefile back to Release from Debug it does compile as expected.

Works locally for me on Release too.

**Comment by bleege** [comment] 2016-05-31 16:38
I just tried to recreate the Bitrise process locally by reverting `/Makefile` back to it's `Debug` state and setting the `BUILDTYPE` environment variable via the command line before firing off a `make android-lib-mips` build.  This worked and produced a MIPS .so file.  The issue has to be something with Bitrise.  To test it out I'm running a new `scheduled` workflow on Bitrise right now to produce a new SNAPSHOT.  This is the same process I originally used to verify that the reconfigured `bitrise.yml` was working.  If it works then we're back to square one (but with a new fresh SNAPSHOT for the first time since last Friday), and if it doesn't then at least things are consistently broken.  😉

**Comment by tmpsantos** [comment] 2016-05-31 16:53
It turns out that the issue is disabling optimization when building Debug. I managed to build Debug just fine with the change below. Definitely a compiler bug.

```
diff --git a/mbgl.gypi b/mbgl.gypi
index c25e53e..9855c6b 100644
--- a/mbgl.gypi
+++ b/mbgl.gypi
@@ -79,7 +79,7 @@
               ],
             },
           }, {
-            'cflags_cc': [ '-g', '-O0', '-fno-omit-frame-pointer','-fwrapv', '-fstack-protector-all', '-fno-common' ],
+            'cflags_cc': [ '-g', '-O1', '-fno-omit-frame-pointer','-fwrapv', '-fstack-protector-all', '-fno-common' ],
             'conditions': [
               ['coverage', { 'cflags_cc': [ '--coverage' ] }],
             ],
```

**Comment by bleege** [comment] 2016-05-31 17:40
The manually kicked off `scheduled` release in Bitrise just failed at the MIPS process again.  @tmpsantos and discussed this and it looks like it may actually be something with one of the arm ABIs but can't tell for sure as the Bitrise command is using compiled parallelization to do faster builds.  To help bring clarity to this I'm going to change this to back to use the sequential build process and kick off another `scheduled` build (all from the `release-android-v4.1.0` branch to minimize changes introduced to this debug effort).  @tmpsantos was also able to confirm that the Bitrise process IS being compiled in `Release` mode based off the logs shown.

```sh
// Parallelized Builds
make apackage -j4

// Sequential Builds
make apackage
```

**Comment by bleege** [comment] 2016-05-31 19:17
@tmpsantos was able to use the failure in the Serialized Build process to isolate the issue.  He's working on a solution now and will merge when complete.

**Comment by bleege** [comment] 2016-05-31 22:08
@tmpsantos was able to find a solution this afternoon (evening in Finland!) and we tested it out locally.  I'm going to merge the PR #5198 into `master` and the cherry pick to `release-android-v4.1.0`.  After that I'll kick off a new `scheduled` build to produce a new SNAPSHOT.

**Comment by bleege** [comment] 2016-05-31 23:01
The SNAPSHOT build worked!  It's build number 40 on SNAPSHOT server (see link below).  We should be good to go again, but I'm going to leave this ticket open until we can confirm that tonight's automated build process works as expected again and produces a new SNAPSHOT.  Will check tomorrow morning and hopefully close then.

https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/4.1.0-SNAPSHOT/

**Comment by bleege** [comment] 2016-06-01 14:17
Yep, last night's automated build ran on Bitrise and produced a brand new SNAPSHOT as expected from `release-android-v4.1.0`.  We're back on track here!

**Closed by bleege** 2016-06-01 14:17 UTC
Labels: Android, bug, Core GL
