### ISSUE TITLE
cameraThatFitsShape should accept target pitch as well

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#11387] opened 2018-03-05 19:10 UTC
https://github.com/mapbox/mapbox-gl-native/blob/6fa57b7d48b6f0505166b8d3a940eaaf1ab5a18f/platform/macos/src/MGLMapView.mm#L1275-L1296

Since the target pitch of the resulting camera is not exposed, internally we're looking at the pitch of the current map view when calculating the resulting camera.

The addition of another argument (pitch) would allow users to go from a pitched view to unpitched view in one fluid motion.

/cc @asheemmamoowala @frederoni @1ec5

**Comment by 1ec5** [comment] 2018-03-06 08:26
Duplicate of #10115.

**Closed by 1ec5** 2018-03-06 08:26 UTC
Labels: feature, iOS, macOS, navigation
