### ISSUE TITLE
iOS: Offline Pack size issue after deleting 2

### ISSUE THREAD

**Issue by CristianSerea** [mapbox/mapbox-gl-native#9245] opened 2017-06-12 14:37 UTC
#9206 

this is weird...cause user maybe want to delete the pack with 86 mb and then when he looks in settings storage would see that app still has 60 mb from deleted pack...

there is no solutions to delete entire pack with all resources? maybe i don't want to improve performance of the map with the remaining resources :) 

thanx

**Comment by jfirebaugh** [comment] 2017-06-12 16:33
Duplicate of #4376.

**Closed by jfirebaugh** 2017-06-12 16:33 UTC
