### ISSUE TITLE
Marker tap and info window offset problem

### ISSUE THREAD

**Issue by Jmaguerre** [mapbox/mapbox-gl-native#7873] opened 2017-01-26 13:55 UTC
**Platform: Android**
**Mapbox SDK version: 4.2.0-beta.5**

### Steps to trigger behavior

 1. Add a new marker to map.
 2. Tap marker

### Expected behavior

Info window appears always at the same distance from the marker

### Actual behavior

The first time I tap it appears correctly, following taps make the info window appear with an offset

This happens using the default icon and also the purple_marker custom example. There's also other thing I noticed, when using the default icon I have to tap above the icon in order to make the info window appear. I saw that the purple_marker.png file has more height than the actual marker. Is this on purpose for this tapping problem not to happen? I attach some screenshots to illustrate what I'm talking about.

**First tap**
<img width="310" alt="screen shot 2017-01-26 at 10 04 50" src="https://cloud.githubusercontent.com/assets/961227/22333067/da0944d6-e3b2-11e6-8db9-3564f6878e9f.png">

**Second tap**
<img width="310" alt="screen shot 2017-01-26 at 10 05 09" src="https://cloud.githubusercontent.com/assets/961227/22333080/ea541c08-e3b2-11e6-9732-e5f30f78806b.png">

**Default marker**
I need to tap on top of the marker for the info window to appear. 
This also is happening to me with other custom images different than purple_marker.png.

<img width="308" alt="screen_shot_2017-01-26_at_10_28_23" src="https://cloud.githubusercontent.com/assets/961227/22333126/1b4bfc7c-e3b3-11e6-8dec-a7b173ab707a.png">

Also in this last screenshot you can notice that while having the same position the default marker appears a little bit below regarding the image than the custom marker but I think this is due to the purple_marker.png file having the transparent space at the bottom

![purple_marker](https://cloud.githubusercontent.com/assets/961227/22333213/92d989c6-e3b3-11e6-97ce-da5660568b83.png)

**Custom image**
<img width="310" alt="screen shot 2017-01-26 at 10 53 44" src="https://cloud.githubusercontent.com/assets/961227/22333628/d7f99742-e3b5-11e6-8662-4d6f31d898fd.png">

Any idea on what's going on? Thanks

**Comment by tobrun** [comment] 2017-01-31 13:25
@Jmaguerre not sure what is going on without seeing the code but normally a secondary click will close the InfoWindow. I'm guessing you are overriding some interface and managing the infowindow yourself? I think that you are hitting this issue because of https://github.com/mapbox/mapbox-gl-native/issues/3176 and https://github.com/mapbox/mapbox-gl-native/issues/6099. Both these issues have been resolved for the  upcoming 5.0.0 release.

Re. touch surface of markers, see -> https://github.com/mapbox/mapbox-gl-native/issues/6761

Feel free to add some code to help look into this more, going to close this as I'm not able to reproduce this from our end. Thank you for reporting and feel free to reach out if you have any questions.

**Closed by tobrun** 2017-01-31 13:25 UTC
Labels: Android

**Comment by Jmaguerre** [comment] 2017-01-31 13:44
Hi @tobrun thanks for looking into this, maybe I was not clear enough, a secondary click does close the infowindow, what I was trying to say was that the second time the infowindow is shown after clicking on the marker is when the infowindow is rendered with an offset. 

I am not overriding any interface nor managing the infowindow myself. However, there is definitely something on my side that is causing this because I tried with a fresh project and it is not happening but I can't figure out why.

I'll continue to look into this and if I found anything I'll report it.

Thanks again.
