### ISSUE TITLE
RenderLineLayer::render() exception due to missing GeometryTile.iconAltas patterns

### ISSUE THREAD

**Issue by timbaker** [mapbox/mapbox-gl-native#13691] opened 2019-01-08 19:52 UTC
This bug is reproducible using commit 4a858eb381ab339ed6634ad05efe4a3d555a7f35.

This is the an example of a line-layer style causing the issue:
```
        {
            "type": "line",
            "paint": {
                "line-pattern": [
                    "step", ["zoom"],
                    "line_solid_6",
                    15, "line_double_14",
                    16, "line_double_16"
                ],
```

The exception occurs in RenderLineLayer::render() due to geometryTile.getPattern() returning empty results sometimes.  GeometryTile.iconAtlas does not include the required pattern images.
```
          optional<ImagePosition> posA = geometryTile.getPattern(linePatternValue.from);
          optional<ImagePosition> posB = geometryTile.getPattern(linePatternValue.to);
```
GeometryTileWorker::parse() calls RenderLineLayer::createLayout() which creates a new PatternLayout.
The PatternLayout constructor is returning patternDependencies for a certain zoom level (during the layout stage), but rendering may later be performed at a different zoom level requiring different patterns.

The solution seems to be either:
1) The PatternLayout constructor would need to return the patterns at every zoom level, or
2) RenderLineLayer::render() would need to evaluate() again at whatever zoom level GeometryTileWorker::parse() used when it created the PatternLayout.

Note: I'm seeing this using a VectorSource.  The TilePyramid appears to contain tiles between zoom levels 11-15 when rendering occurs at zoom=15.  So the results of a PatternLayout created for zoom=11 being rendered at zoom=15 results in this error.

**Comment by timbaker** [comment] 2019-01-11 04:19
Here is a style.json, xxx.geojson and sprites/ folder to demonstrate the bug.
I've tested it using mbgl-qt.exe from the Qt SDK.  The map data is near lat=-0.05 long=0.05.
There's a maki symbol there, if you zoom out you should see it.

Zooming in/out and scrolling around near zoom=15 should cause exceptions in RenderLineLayer::render().

[line-pattern-bug.zip](https://github.com/mapbox/mapbox-gl-native/files/2748042/line-pattern-bug.zip)

**Comment by brunoabinader** [comment] 2019-01-18 19:43
@timbaker I couldn't reproduce the issue using the latest master (b83030aa9bb1a8d9f14ae8160698c1ee4d5a4c72). Given the initial commit you've suggested, I suppose this has been fixed in https://github.com/mapbox/mapbox-gl-native/pull/13535 (/cc @ChrisLoer). Could you please verify using the latest master?

**Comment by kkaefer** [comment] 2019-03-27 10:21
Fixed in https://github.com/mapbox/mapbox-gl-native/issues/14230

**Closed by kkaefer** 2019-03-27 10:21 UTC
Labels: Core, bug
