### ISSUE TITLE
MGLMapView leaks in v3.0.0 of the iOS SDK

### ISSUE THREAD

**Issue by vyshane** [mapbox/mapbox-gl-native#3204] opened 2015-12-07 03:17 UTC
I've created a [minimal iOS project](https://github.com/vyshane/mapbox-leak) to observe the leak. The app uses a navigation controller to navigate between two view controllers. The root view controller has a button to push a view controller that contains an MGLMapView onto the navigation stack.

To observe the leak:

 1. Clone the project: `git clone https://github.com/vyshane/mapbox-leak.git`
 2. Edit [MapboxLeak/Info.plist](MapboxLeak/Info.plist) and update the value for the MGLMapboxAccessToken key with your Mapbox API token.
 3. Run `pod install` in the project root directory.
 4. Open the `MapboxLeak.xcworkspace` workspace in Xcode.
 5. Press ⌘i to start profiling.
 6. Once the app is running, tap on the `Show Map` button, then tap on `Back`.
 7. Do this a few times and observe that the number of `MBLMapView` instances keeps growing.

**Comment by syedhali** [comment] 2015-12-07 09:56
This is the same as #3130

**Comment by jfirebaugh** [comment] 2015-12-14 21:46
Closing as duplicate of #3130.

**Closed by jfirebaugh** 2015-12-14 21:46 UTC
Labels: iOS, performance

**Comment by syedhali** [comment] 2016-01-08 20:36
If this was fixed by #3448, any idea when the iOS cocoapod will be updated? We'd really love to update to v3.0

**Comment by friedbunny** [comment] 2016-01-09 05:46
We're nearing the homestretch on an iOS release, hopefully in the next couple weeks.

(@vyshane Thanks for the demo project, btw.)
