### ISSUE TITLE
[core] Allow paint transition update to be called with extraneous classes

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#5354] opened 2016-06-14 17:41 UTC
Port of https://github.com/mapbox/mapbox-gl-js/issues/2477 for GL native:
![download](https://cloud.githubusercontent.com/assets/76133/16053159/426c5c42-3270-11e6-8d0d-4d981cc0485b.png)

Part of https://github.com/mapbox/mapbox-gl-shaders/issues/1.

:eyes: @jfirebaugh @kkaefer @lucaswoj

**Comment by jfirebaugh** [comment] 2016-06-14 18:23
Closing here; "Unable to add a fill-pattern to a layer" was a bug in gl-js. It's not a bug in native. The test regression should be investigated as part of #5357.

**Closed by jfirebaugh** 2016-06-14 18:23 UTC
Labels: bug, Core GL, parity
