### ISSUE TITLE
-[MGLMapViewDelegate mapView:strokeColorForShapeAnnotation:] does not work properly for pattern collor

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#7712] opened 2017-01-13 10:33 UTC
**Platform:** iOS
**Mapbox SDK version:** ios-v3.4.0-beta.7

### Steps to trigger behavior

 1. Instantiate MGLMapView
 2. Set a delegate
 3. Add a multiline shape using MGLPolyline
 4. Implement ```- (UIColor *)mapView:(MGLMapView *)aMapView strokeColorForShapeAnnotation:(MGLShape *)anAnnotation```
 5. Return UIColor instantiated with a pattern image:
```
- (UIColor *)mapView:(MGLMapView *)aMapView strokeColorForShapeAnnotation:(MGLShape *)anAnnotation
{
     return [UIColor colorWithPatternImage:myImage];
}
```

Please review image attached
### Expected behavior
Stroke should be perfectly rendered

### Actual behavior
Stroke is not dispalyed

![out-of-bounds](https://cloud.githubusercontent.com/assets/13018567/21926898/1e1b6372-d984-11e6-92b7-05eeaf953ad3.png)

**Comment by friedbunny** [comment] 2017-01-13 18:48
Related: https://github.com/mapbox/mapbox-gl-native/issues/5033

**Comment by 1ec5** [comment] 2017-01-24 21:24
Duplicate of #5033.

**Closed by 1ec5** 2017-01-24 21:24 UTC
Labels: annotations, bug, iOS
