### ISSUE TITLE
java.lang.Error: std::bad_alloc when rotating map and zoom in/out at same time (many times)

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#8288] opened 2017-03-06 08:38 UTC
**Platform: Android **
**Mapbox SDK version: 5.0 Snapshot**

### Steps to trigger behavior

 1. Open `MapView`
 2. zoom in, out rotate app many times (fast as well)
 3. App crash with below logs:
```
java.lang.Error: std::bad_alloc
                                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(Native Method)
                                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(NativeMapView.java:591)
                                                                       at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerViewsInRect(AnnotationManager.java:398)
                                                                       at com.mapbox.mapboxsdk.maps.MapboxMap.getMarkerViewsInRect(MapboxMap.java:1049)
                                                                       at com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion(MarkerViewManager.java:463)
                                                                       at com.mapbox.mapboxsdk.annotations.MarkerViewManager.update(MarkerViewManager.java:449)
                                                                       at com.mapbox.mapboxsdk.maps.AnnotationManager.update(AnnotationManager.java:69)
                                                                       at com.mapbox.mapboxsdk.maps.MapboxMap.onUpdate(MapboxMap.java:162)
                                                                       at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:970)
                                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:943)
                                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeScaleBy(Native Method)
                                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.scaleBy(NativeMapView.java:349)
                                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.scaleBy(NativeMapView.java:342)
                                                                       at com.mapbox.mapboxsdk.maps.Transform.zoomBy(Transform.java:280)
                                                                       at com.mapbox.mapboxsdk.maps.MapGestureDetector$ScaleGestureListener.onScale(MapGestureDetector.java:478)
                                                                       at android.view.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector.java:437)
                                                                       at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:125)
                                                                       at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:290)
                                                                       at android.view.View.dispatchTouchEvent(View.java:8471)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SlidingUpPanelLayout.java:943)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                   	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.jav
```

### Expected behavior
Map should not crash when rotate, zoom in-out at same time
### Actual behavior
Map crashed when rotate, zoom in-out at same time

**Comment by tobrun** [comment] 2017-03-06 16:42
Some context around this crash: This only occurs when using ViewMarkers. This system relies on calling queryPointAnnotations every time the camera position changes.

**Comment by eimantas** [comment] 2017-03-07 13:53
Ditto crash for iOS 3.4.2 on `mbglMap->queryPointAnnotations()`. The context is the same - viewing annotations and there are a few of them (overlapping rects) under a tap area. 

Could be the same issue that is found in both SDKs because of the bug in mbgl-core?

**Comment by jfirebaugh** [comment] 2017-03-09 19:16
Duplicate of #8289.

**Closed by jfirebaugh** 2017-03-09 19:16 UTC
Labels: Android, crash, iOS
