### ISSUE TITLE
Mapbox.setConnected equivalent in iOS

### ISSUE THREAD

**Issue by alexrainman** [mapbox/mapbox-gl-native#14469] opened 2019-04-21 21:32 UTC
I need to fully block online map. I am using Mapbox.SetConnected(false) in Android.

How to do the same in iOS?

**Comment by fabian-guerra** [comment] 2019-04-22 16:41
Hi, @alexrainman. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

**Comment by fabian-guerra** [comment] 2019-09-17 18:13
In my original response I misread this ticket. I'm reopening as a feature request.

**Comment by friedbunny** [comment] 2019-09-23 23:40
This seems to be a duplicate of #7443.

**Closed by friedbunny** 2019-09-23 23:40 UTC
Labels: feature, iOS
