### ISSUE TITLE
Failed to build mapbox SDK from the current master branch

### ISSUE THREAD

**Issue by ragaisis** [mapbox/mapbox-gl-native#8310] opened 2017-03-08 12:21 UTC
**Platform:** Android
**Mapbox SDK version:** latest Mapbox master branch (2017-03-08 4:23 AM) SHA: f591421aaaf698c23ccff37a03d03c87eaa0d988

### Steps to trigger behavior

 1. checkout latest mapbox master branch
 2. try to build with "make android-lib-x86"
 3. error appears (error log attached as a file)

### Expected behavior
Master branch should be clean and builds should build

### Actual behavior
Now it's not building 

[mapbox_build_bug.txt](https://github.com/mapbox/mapbox-gl-native/files/827533/mapbox_build_bug.txt)

**Comment by jfirebaugh** [comment] 2017-03-08 15:35
Duplicate of #7702. For now you need to build with clang++ < 3.9.1.

**Closed by jfirebaugh** 2017-03-08 15:35 UTC
