### ISSUE TITLE
[iOS] Disable compass fade when facing north

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native#14942] opened 2019-06-17 18:02 UTC
The default behavior on the Maps SDK fades out the compass when it's facing north. On @mapbox/maps-android, there is a boolean method [`MapboxMap.getUiSettings().setCompassFadeFacingNorth(false)`](https://docs.mapbox.com/android/api/map-sdk/8.0.1/com/mapbox/mapboxsdk/maps/UiSettings.html#setCompassFadeFacingNorth-boolean-) to disable this fade. The same feature has been requested on iOS so that a developer can choose to always show the compass.

For other fade/animation customization options, we've faced a choice between whether to accept a boolean value or an integer, and the same question applies here. Accepting `int` is my preference -- it's more flexible because it supports the possibility of a future feature that enables the developer to customize the fade/animation duration, with `0` = disabled.

cc/ @mapbox/maps-ios

**Comment by friedbunny** [comment] 2019-06-17 19:00
Duplicate of #9562.

**Closed by friedbunny** 2019-06-17 19:00 UTC
Labels: iOS
