### ISSUE TITLE
Missing attribute: Visible and ZIndex in annotations/Polyline

### ISSUE THREAD

**Issue by tsenggordon** [mapbox/mapbox-gl-native#9623] opened 2017-07-26 18:47 UTC
**Platform:** Android
**Mapbox SDK version:** 5.1.0

In Google Map, visible and ZIndex are included in polyline, I wonder if mapbox has the parity of those or how can achieve the same behavior. 
https://developers.google.com/android/reference/com/google/android/gms/maps/model/Polyline

**Comment by jfirebaugh** [comment] 2017-07-26 19:14
Duplicate of #1728.

**Closed by jfirebaugh** 2017-07-26 19:14 UTC
