### ISSUE TITLE
Tracking mode first enters none when transition to a new view

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#6561] opened 2016-10-03 15:23 UTC
**Platform: iOS**
**Mapbox SDK version: `v3.4.0-alpha.4`**
### Steps to trigger behavior
1. Create navigation view controller
2. Navigate to a new view containing a map view. 
3. Set the `userTrackingMode` to `follow` within `viewDidLoad`
4. Add a listener for mapview tracking mode did change, print out `mode`
### Expected behavior

The map loads and the tracking mode directly enters `follow`.
### Actual behavior

The map loads and the `userTrackingMode` first enters `none` then `follow`.

/cc @1ec5 @boundsj

**Comment by friedbunny** [comment] 2016-10-03 19:39
To clarify: I think you’ve flipped the expected and actual behaviors. Expected behavior is that the tracking mode will always be what you set it to, right?

**Comment by bsudekum** [comment] 2016-10-03 21:10
@friedbunny 😅 ha yes, fixed.

**Comment by lilykaiser** [comment] 2017-11-17 23:35
Closing due to ticket age. If this is still a problem, please re-open

**Closed by lilykaiser** 2017-11-17 23:35 UTC
Labels: bug, iOS
