### ISSUE TITLE
Zoom dependent annotations

### ISSUE THREAD

**Issue by xwz** [mapbox/mapbox-gl-native#4793] opened 2016-04-22 02:42 UTC
Feature request:

Use case: when showing an overview of a city, show many little dots, as the user zooms in, the dots change to larger icons.

A possible solution is to allow annotations to appear and disappear (alpha levels?) depending on zoom level.

**Comment by 1ec5** [comment] 2016-04-22 03:45
Duplicate of #320.

**Closed by 1ec5** 2016-04-22 03:45 UTC
