### ISSUE TITLE
Cannot update MGLShapeSource shape property

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#9295] opened 2017-06-16 21:45 UTC
**Platform: iOS**
**Mapbox SDK version: master (tested on commit: afabd2795c95bd11273a370c8045b07296b7a346)**

### Steps to trigger behavior

 1. Add source and layer referencing that source to the map style
 2. Update the sources shape with a new source

### Expected behavior

Shape on map is updated to reflect new shape.

### Actual behavior

Initial shape remains on map.

Ref, example: https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/NavigationMapView.swift#L37-L38

/cc @1ec5 @boundsj @fabian-guerra

**Comment by asheemmamoowala** [comment] 2017-06-18 15:57
Should be fixed by #9110 . 
https://github.com/mapbox/mapbox-gl-native/pull/9110/commits/37fa8adc41126b4cdef5f7ba3916787209a55714#diff-12f94a363ba006ac75e7fba4eef3129cR36

**Comment by 1ec5** [comment] 2017-06-19 18:11
Duplicate of #9229.

**Closed by 1ec5** 2017-06-19 18:11 UTC
Labels: bug, iOS
