### ISSUE TITLE
Satellite style causes UI frozen

### ISSUE THREAD

**Issue by MilkBiscuit** [mapbox/mapbox-gl-native#6229] opened 2016-08-31 22:15 UTC
Using version mapbox-android-sdk-4.1.1 we tried to download offline region for some areas and then view the map.
 
When trying to use com.mapbox.mapboxsdk.R.string.style_satellite the app becomes unresponsive in NativeMapView.nativeSetReachability when we try to open map a second time.

We have tried the same thing with com.mapbox.mapboxsdk.R.string.style_light and it works properly and causes no problems.

See attached screenshot for the full stack trace.

It is 100% reproducible.

![stuck in nativeSetReachability](https://cloud.githubusercontent.com/assets/20746964/18148007/71c8c8ba-702b-11e6-9460-fbfbef12ea20.png)

**Platform:** Android 5.1.1
**Mapbox SDK version:** 4.1.1

**Comment by jfirebaugh** [comment] 2016-08-31 22:24
Duplicate of #4414.

**Closed by jfirebaugh** 2016-08-31 22:24 UTC
