### ISSUE TITLE
setInfoWindowAdapter sometime working and some time not

### ISSUE THREAD

**Issue by altaf2892** [mapbox/mapbox-gl-native#10172] opened 2017-10-10 12:52 UTC
**i have tried many of issues suggestions but i m facing  same issues**
**i m trying to implement this in fragment**
> i have tried to toast and log too but get nothing.....

`  @Override
    public void onMapReady(MapboxMap mapboxMap) {
        myMap = mapboxMap;
        myMap.setInfoWindowAdapter(new MapboxMap.InfoWindowAdapter() {

            @Nullable
            @Override
            public View getInfoWindow(@NonNull com.mapbox.mapboxsdk.annotations.Marker marker) {

                View v = getActivity().getLayoutInflater().inflate(R.layout.view_custom_marker, null);

                TextView title = (TextView) v.findViewById(R.id.t);
                TextView t1 = (TextView) v.findViewById(R.id.t1);
                TextView t2 = (TextView) v.findViewById(R.id.t2);
                ImageView imageView = (ImageView) v.findViewById(R.id.profile_image);
                Typeface font = Typeface.createFromAsset(getActivity().getAssets(), "font/AvenirLTStd_Medium.otf");
                t1.setTypeface(font);
                t2.setTypeface(font);

                String name = marker.getTitle();
                title.setText(name);
                String info = marker.getSnippet();
                t1.setText(info);
                driver_id = String.valueOf((Long) marker.getId());
                drivername = marker.getTitle();

                txt_info.setText(info);

/*

                if (CheckConnection.haveNetworkConnection(getActivity())) {

                    if (!progressDialog.isShowing()) {
                        progressDialog.show();
                    }
                    //LoadInfo(marker);
                } else {

                    Toast.makeText(getActivity(), NETWORK, Toast.LENGTH_LONG).show();

                }
*/

                Log.e("Clicked", "rres");

                return v;
            }

        });
      
    }`

**adding marker (this is for single but i have loop to add multiple markers)**
` com.mapbox.mapboxsdk.annotations.Marker marker = myMap.addMarker(new com.mapbox.mapboxsdk.annotations.MarkerOptions().position(new com.mapbox.mapboxsdk.geometry.LatLng(latitude, longitude)).setTitle(location.getName()).setSnippet(location.getVehicle_info()).icon(IconFactory.getInstance(getActivity()).defaultMarker()));
                `

**i have just tried to remove setInfoWindowAdapter and simple try to see default view but i faced same problem**

**Comment by tobrun** [comment] 2017-10-11 09:39
Validated with codebase that this is still working, not able to reproduce your issue.
In any case here are two examples
 -  [default InfoWindow example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowActivity.java)
 - [InfoWindowAdapter](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowAdapterActivity.java)

Let us know if those examples don't work on your device and provide some information on impacted device + OS version. Closing this now as unable to reproduce. Feel free to report any additional information you have on this issue.

**Closed by tobrun** 2017-10-11 09:39 UTC
Labels: Android, support

**Comment by altaf2892** [comment] 2017-10-11 11:24
i left to adding custom info window for now but i m adding three things to marker Title,snippet and id ..... here title,snippet and id i have as String  and i parse id and set id .....  and if i do so default info not showing on marker click but if i add title and snippet only it works.. whats problem with this  see like this ` marker.setId(Long.parseLong(location.getUser_id()));`

**Comment by tobrun** [comment] 2017-10-11 12:39
You aren't allowed to reset the id. If you want to add additional data to the marker you can extend the options class and the marker class.

**Comment by altaf2892** [comment] 2017-10-11 12:50
then you add settag method and allow to change it .....  googleMap has this setTag methosand allowed to change this ...... i was using googleMap but as i heard MapBox provide more feature and get easily implemented so i started to implement But disappointed ..like u ain't provide place picker like googleMap,  and i found [](`https://blog.mapbox.com/how-to-build-a-location-picker-for-your-app-8e61be7fc9cc`) for MapBox but it also unclearer to me as i m new to MapBox....  can u provide example for place picker ....    and also u mapBox dont have latest example ...more examples are for old versions..
