### ISSUE TITLE
Map error when animating using LatLngBounds

### ISSUE THREAD

**Issue by tan-tran-ea** [mapbox/mapbox-gl-native#11577] opened 2018-03-31 07:58 UTC
**Platform: Android + Kotlin**
**Mapbox SDK version: 5.5.1**

### Steps to trigger behavior

 1. Load map Async

 2. Create LatLngBounds with 2 locations:

```
    val startLatLng = LatLng(startingLocation.latitude,startingLocation.longitude)
    val endingLatLng = LatLng(endingLocation.latitude, endingLocation.longitude)
    mapboxMap.addMarker(MarkerOptions().position(startLatLng))
    mapboxMap.addMarker(MarkerOptions().position(endingLatLng))

    val latLngBounds = LatLngBounds.Builder()
        .include(startLatLng)
        .include(endingLatLng)
        .build()

    val cameraUpdate = CameraUpdateFactory.newLatLngBounds(latLngBounds,
        resources.getDimensionPixelSize(R.dimen.margin_padding_normal))
```

 3. Animate Camera

    `mapboxMap.animateCamera(cameraUpdate, 1000)`

### Expected behavior
Map will be animated and zoomed to LatLngBounds

### Actual behavior
Map error: 
`java.lang.NullPointerException: Attempt to read from field 'com.mapbox.mapboxsdk.geometry.LatLng com.mapbox.mapboxsdk.camera.CameraPosition.target' on a null object reference`

**Comment by LukasPaczos** [comment] 2018-04-03 17:45
Thanks for reporting the issue @tan-tran-ea. `CameraBoundsUpdate` is the only update that doesn't invalidate camera before executing which results in said `NPE`, that's caught, but will escape the rest of the code block regardless.

Closing as the issue is already fixed with the upcoming `6.0.0`, but I will add additional camera invalidation to the initialization process.

**Closed by LukasPaczos** 2018-04-03 17:45 UTC
Labels: Android
