### ISSUE TITLE
onMapReady() is not called in offline mode

### ISSUE THREAD

**Issue by zplesac** [mapbox/mapbox-gl-native#7045] opened 2016-11-14 14:51 UTC
Hi,

I'm using the latest Mapbox Android SDK version - 4.2.0-beta.4, and onMapReady() is still not called inside the activity or fragment when there is no active internet connection. Map area for that location was downloaded when app had an internet connection, and zoom level is inside min-max range defined in OfflineManager.

onMapChanged(@MapChange int change)  is called with following _change_ values when the activity is started:

5
0
3
3
11
8
9
8
9

Result screen:

![test](https://cloud.githubusercontent.com/assets/3542084/20269027/c9802bbc-aa81-11e6-816e-ab1e0c5567cd.png)

I've also tested the latest stable version, result remains the same. Both versions were tested on Android OS versions 7.0 and 5.1.1.

Map is visible with user location and all the markers when there is an active internet connection, so this eliminates the possibility that not all the lifecycle methods are propagated to MapView.

**Comment by cammace** [comment] 2016-12-12 22:06
Could you provide any logout while the region is being loaded in offline mode? Along with the snippet of code you are using to download the region.

**Comment by snowpong** [comment] 2017-01-18 14:44
I'm seeing a similar behavior here using 4.2.1 running both on Genymotion and on actual device. onMapReady(..) is never called when in Flight mode. I have offlined the region(s). Zoom level is inside min max and position is within the offlined region(s). The map is completely black except for the MapBox (i) text and icon.

Here is what onMapChanged spits out:
onMapChanged: 5
onMapChanged: 0
onMapChanged: 3
onMapChanged: 11
onMapChanged: 8
onMapChanged: 9
onMapChanged: 8
onMapChanged: 9
onMapChanged: 0
onMapChanged: 3
onMapChanged: 8
onMapChanged: 9
onMapChanged: 8
onMapChanged: 9
onMapChanged: 8
onMapChanged: 9
and then 8 9 8 9 ad nauseam.

So it seems to start loading the map, yet never fails nor finishes.
And it starts to render the map, and keeps rendering a frame over and over, yet never finishes rendering the map. Or at least, that is how I read those map changes.

**Comment by cammace** [comment] 2017-01-19 14:28
Can you confirm that the offline region is using the same style as the one set in your map view? This behavior has happened in the past but was fixed after insuring the styles matched. Also which device are you using (besides Genymotion)? You can also try changing the pixel ratio value or set it using `context.getResources().getDisplayMetrics().density`. 

Could you also provide the full logcat around when you attempt to load the style in.

cc: @mapbox/android

**Comment by snowpong** [comment] 2017-01-19 15:17
@cammace I filed a separate bugreport here which I feel reflects my issue a bit more clearly https://github.com/mapbox/mapbox-gl-native/issues/7783

I can confirm the offline region is using the same style as the map set on the view, the problem was I was not setting it early enough - so it's falling back to the default style (I believe) and thus failing when offline since the default style is not offlined, and there is no network.

This was happening on a Sony Z2 as well as Genymotion.

Don't have the logcat easily available. But see the other issue I link to - it has a diff in the end that shows what worked around the issue for me.

**Comment by cammace** [comment] 2017-01-19 15:28
Thanks for opening the ticket and making it clear what the issue is. Closing this ticket in favor of #7783

**Closed by cammace** 2017-01-19 15:28 UTC
Labels: Android
