### ISSUE TITLE
Manual iOS build instructions error out

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1502] opened 2015-05-11 17:04 UTC
I tried following the instructions in https://github.com/mapbox/mapbox-gl-native/blob/master/README.md#manually, but I ran into some issues:

```
$ brew install appledoc
Error: No available formula for appledoc 
Searching formulae...
appledoc20  appledoc21	appledoc22
Searching taps...
```

```
$ make ipackage
…
* Recording library version...
mapbox-gl-native d4fcb5bb98
* Creating build files...
git submodule update --init platform/ios/vendor/SMCalloutView
deps/run_gyp gyp/ios.gyp -Dhost=ios -Iconfig/ios.gypi -Dinstall_prefix=/usr/local -Dheadless_lib=none -Dplatform_lib=ios -Dasset_lib=fs -Dhttp_lib=nsurl -Dcache_lib=sqlite --depth=. -Goutput_dir=. --generator-output=./build/ios -f xcode
* Building iOS device targets...
./scripts/ios/package.sh: line 44: JOBS: unbound variable
./scripts/ios/package.sh: line 19: wait_for: No record of process 47919
make: *** [ipackage] Error 127
```

/cc @incanus

**Comment by 1ec5** [comment] 2015-05-11 18:08
Per chat with @mikemorris:

> It looks like `$JOBS` is unbound because it's [not being passed to the iOS packaging scripts in the Makefile](https://github.com/mapbox/mapbox-gl-native/blob/master/Makefile#L115-L147)?

**Comment by mikemorris** [comment] 2015-05-11 18:33
This was caused by dropping `source ./scripts/travis_helper.sh` from `scripts/ios/install.sh`

**Comment by incanus** [comment] 2015-05-11 18:40
Some of the appledoc background: https://github.com/Homebrew/homebrew/issues/33541

I'm working on testing my local setup **not with** the appledoc I have installed from source.

**Comment by 1ec5** [comment] 2015-05-11 19:07
ref tomaz/appledoc#526

**Comment by incanus** [comment] 2015-05-11 20:33
Fixed in `master`, cherry-picking over to b1 release.

**Closed by incanus** 2015-05-11 20:33 UTC
Labels: build, iOS
