### ISSUE TITLE
terminating with uncaught exception of type mapbox::sqlite::Exception: unable to open database file

### ISSUE THREAD

**Issue by emostar** [mapbox/mapbox-gl-native#6351] opened 2016-09-15 20:29 UTC
**Platform:** Android
**Mapbox SDK version:** 4.2.0-beta2

### Steps to trigger behavior

 1. Create a mapbox view

### Expected behavior

Show a map

### Actual behavior

It crashes with the following message. Deleting the application files and restarting the app causes it to work the next time, but something causes this error to trigger again in the future.

> Abort message: '/Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: unable to open database file" failed'

**Comment by jfirebaugh** [comment] 2016-09-15 20:30
Duplicate of #6193.

**Closed by jfirebaugh** 2016-09-15 20:30 UTC
