### ISSUE TITLE
Annotations disappear when moving map

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#8217] opened 2017-02-28 10:37 UTC
**Platform:** iOS
**Mapbox SDK version:** 3.4.2

### Steps to trigger behavior

 1. Add custom annotation with different reuseIdentifier
 2. Move mapView
 3. Annotation disappear

### Expected behavior
Annotations should not be removed. If I set all the annotation's reuseIdentifiers the same, they still attached to the map 
### Actual behavior
Annotations removed when mapView moving,

**Comment by boundsj** [comment] 2017-02-28 17:24
Thanks for the report @iBinh. I'm not able to reproduce the actual behavior you describe with those repro steps. Can you please post a code sample or sample project that reproduces the problem? Thank you.

**Comment by iBinh** [comment] 2017-03-03 11:42
when I set 
`@property (nonatomic, strong, nullable) NSString *reuseIdentifier;
`
then move map, annotation disapear and reappear
when set 
@property (nonatomic, copy, nullable) NSString *reuseIdentifier;
annotation not disappear but sometime, annotation A title is replaced by annotation B title, and for the other annotations.

**Comment by boundsj** [comment] 2017-03-03 20:10
Hi @iBinh. I'm not able to tell from those property definitions when you are setting / updating what appears to be a shared `reuseIdentifier` property in your application. You should define string values for the various categories of annotation views you intended to use and those string values should be consistent for an annotation and annotation view pairing.

I'm going to close this since I cannot reproduce the issues you are reporting when using the API in the intended way. Please have a look at the [Mapbox iOS SDK API documentation](https://www.mapbox.com/ios-sdk/api/3.4.2/) and [help resources](https://www.mapbox.com/help/) and [contact us through the form there](https://www.mapbox.com/contact/) if you cannot find a solution to your issue. 

Specifically, you may find [this example](https://www.mapbox.com/ios-sdk/examples/annotation-views/) useful.

**Closed by boundsj** 2017-03-03 20:10 UTC
Labels: annotations, iOS, needs clarification
