### ISSUE TITLE
Changing `image` property of `MGLAnnotationImage` doesn't update sprite

### ISSUE THREAD

**Issue by alexagat** [mapbox/mapbox-gl-native#4556] opened 2016-03-31 12:52 UTC
When I update the `image` property on a `MGLAnnotationImage`, for example in the `didSelectAnnotation` function:

```
func mapView(mapView: MGLMapView, didSelectAnnotation annotation: MGLAnnotation) {
    annotationsTitlesAndImages[annotation.title!!]!.image = UIImage(named: "map-pin-active")!
}
```

...I see the below block of code in mapbox-gl framework run, but the annotation image does not update:

```
- (void)setImage:(UIImage *)image {
    _image = image;
    [self.delegate annotationImageNeedsRedisplay:self];
}
```

I believe it should update the annotation's image on the fly without any type of manual refresh.

The issue is referenced:
https://github.com/mapbox/mapbox-gl-native/issues/2210
https://github.com/mapbox/mapbox-gl-native/pull/3146

**Comment by RomainQuidet** [comment] 2016-04-04 08:11
I tested it on objC, it's working for me.

**Comment by friedbunny** [comment] 2016-04-04 16:10
Replacing an annotation image is bit cumbersome — it’s currently not as simple as just changing the `image` property.

[Here’s an a WIP example of how to replace an annotation image in Swift.](https://gist.github.com/friedbunny/27ece538f288230a5905)

The key points:

- The annotation image should be an instance of `MGLAnnotationImage`.
- You should be checking reuse identifiers.
- Use the `annotation` object that comes with the `mapView:didSelectAnnotation:` delegate method.

**Comment by 1ec5** [comment] 2016-05-25 06:55
> Replacing an annotation image is bit cumbersome — it’s currently not necessarily as simple as just changing the `image` property.

This should work following #3835. Please let us know if setting the `image` property isn’t working in the v3.3.0 alphas.

**Comment by millenbop** [comment] 2016-11-23 09:57
This is still an issue with ios-v3.3.7, so please reopen. My code is below:

```
- (nullable MGLAnnotationImage *)mapView:(nonnull MGLMapView *)mapView imageForAnnotation:(nonnull id<MGLAnnotation>)annotation
{
    MapAnnotation* a = annotation;
    NSString* identifier = [NSString stringWithFormat:@"%f,%f", a.coordinate.latitude, a.coordinate.longitude];
    NSString* imageName = nil;
    
    if ([self.selected containsObject:a.userData])
    {
        imageName = @"marker-red.png";
    }
    else
    {
        imageName = @"marker-green.png";
    }
    
    MGLAnnotationImage* image = [mapView dequeueReusableAnnotationImageWithIdentifier:identifier];
    
    if (!image)
    {
        image = [MGLAnnotationImage annotationImageWithImage:[UIImage imageNamed:imageName] reuseIdentifier:identifier];
    }
    
    return image;
}

- (void)mapView:(MGLMapView *)mapView didSelectAnnotation:(id<MGLAnnotation>)annotation
{
    MapAnnotation* a = annotation;
    NSString* identifier = [NSString stringWithFormat:@"%f,%f", a.coordinate.latitude, a.coordinate.longitude];
    
    if (![self.selected containsObject:a.userData])
    {
        [self.selected addObject:a.userData];
        
        MGLAnnotationImage* annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:identifier];
        annotationImage.image = [UIImage imageNamed:@"marker-red.png"];
    }
   
}

- (void)mapView:(MGLMapView *)mapView didDeselectAnnotation:(id<MGLAnnotation>)annotation
{
    MapAnnotation* a = annotation;
    NSString* identifier = [NSString stringWithFormat:@"%f,%f", a.coordinate.latitude, a.coordinate.longitude];
    
    if ([self.selected containsObject:a.userData])
    {
        [self.selected removeObject:a.userData];
        
        MGLAnnotationImage* annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:identifier];
        annotationImage.image = [UIImage imageNamed:@"marker-green.png"];
    }
}
```

**Comment by Channel76** [comment] 2017-01-14 11:39
This is also true if you try to change the pin size for an annotation image that is already "drawn" on the map with the same ReuseId. Even if you remove and re-add the annotation, the size of the pin doesn't change. In order to see the pin with the new size, you have to restart the app...

**Comment by 1ec5** [comment] 2017-01-14 17:40
#7618 tracks this issue more generally for style images in the runtime styling API.

@millenbop, before I re-close this issue as a reverse duplicate of #7618, can you confirm whether the marker-red.png and marker-green.png images you were using had differing dimensions?

**Comment by millenbop** [comment] 2017-01-16 11:22
They have the same dimensions:

![marker-green](https://cloud.githubusercontent.com/assets/12835674/21981163/6e84ef9a-dbe6-11e6-9ba2-bc0556475de6.png)
![marker-red](https://cloud.githubusercontent.com/assets/12835674/21981164/6e8c11d0-dbe6-11e6-9935-2d163022fe46.png)
![marker-yellow](https://cloud.githubusercontent.com/assets/12835674/21981165/6e8edbb8-dbe6-11e6-9422-53f3a9af6fdd.png)

**Comment by nrubin999** [comment] 2017-08-28 22:23
What's the status of this? Trying to update `image` of `MGLAnnotationImage` with no success.

**Comment by 1ec5** [comment] 2017-08-30 17:39
I can reproduce this issue in iosapp in eedd90961168037954e534507f632fac7cb0a8ae (post-v3.6.2, pre-v3.6.3) with the following diff:

```diff
diff --git a/platform/ios/app/MBXViewController.m b/platform/ios/app/MBXViewController.m
index 992b7d587..adc6b7c44 100644
--- a/platform/ios/app/MBXViewController.m
+++ b/platform/ios/app/MBXViewController.m
@@ -1777,8 +1777,14 @@ typedef NS_ENUM(NSInteger, MBXSettingsMiscellaneousRows) {
         return;
     }
 
-    MGLPointAnnotation *point = (MGLPointAnnotation *)annotation;
-    point.coordinate = [self.mapView convertPoint:self.mapView.center toCoordinateFromView:self.mapView];
+//    MGLPointAnnotation *point = (MGLPointAnnotation *)annotation;
+//    point.coordinate = [self.mapView convertPoint:self.mapView.center toCoordinateFromView:self.mapView];
+    
+    NSString *title = [(MGLPointAnnotation *)annotation title];
+    if (!title.length) return;
+    NSString *lastTwoCharacters = [title substringFromIndex:title.length - 2];
+    MGLAnnotationImage *image = [mapView dequeueReusableAnnotationImageWithIdentifier:lastTwoCharacters];
+    image.image = [self imageWithText:lastTwoCharacters backgroundColor:[UIColor orangeColor]];
 }
 
 - (void)mapView:(MGLMapView *)mapView didFinishLoadingStyle:(MGLStyle *)style
```

Interestingly, if I uncomment the line that changes the annotation’s coordinate, the image does update – just for that particular annotation – by virtue of the call to `mbgl::Map::updateAnnotation()`.

Digging in further, it does appear that `-[MGLMapView annotationImageNeedsRedisplay:]` and `-installAnnotationImage:` are working as they always have, by calling `mbgl::Map::removeAnnotationImage()` followed by `addAnnotationImage()` with the same image ID. If I remove [this line](https://github.com/mapbox/mapbox-gl-native/blob/eedd90961168037954e534507f632fac7cb0a8ae/platform/ios/src/MGLMapView.mm#L4111), all the annotations associated with the annotation image update as expected.

Since the image replacement feature was originally implemented, a formal style image API was added with the expectation that a sprite image would never be removed while in use. I think removing the call to `removeAnnotationImage()` is an appropriate fix, but we’ll need to test some edge cases like setting `image` to `nil`.

**Comment by ohwhen** [comment] 2017-10-22 00:56
Also running into this issue, using build 3.6.4. The image doesn't refresh automatically..the only workaround I found that works is removing and adding the annotation again.

`
mapView.removeAnnotation(annotation)
mapView.addAnnotation(annotation)
`

**Comment by 1ec5** [comment] 2017-11-14 20:26
> we’ll need to figure out why the update only happens on deselection or camera changes

Pretty sure this was because I had merely moved the call to `removeAnnotationImage()` instead of deleting it outright.

**Comment by sassiwalid** [comment] 2018-11-28 12:39
my problem is when I select an annotation in the mapbox mapview the state changed to selected and the image of the annotation for this I wrote this delegate method

func mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation) {

        if let castAnnotation = annotation as? MyCustomPointAnnotation {
            if (!castAnnotation.willUseImage) {
                return
            }
            for mapAnn in mapView.annotations!
            {
                castAnnotation.selected = false
            if ((mapAnn.coordinate.longitude == annotation.coordinate.longitude) && (mapAnn.coordinate.latitude == annotation.coordinate.latitude))
            {
                castAnnotation.selected = true
                castAnnotation.willUseImage = true
                mapView.removeAnnotation(annotation)
                mapView.addAnnotation(castAnnotation)
            }

        }
        }

    } 
the addAnnotation method fire this imageForAnnotation method: func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage? {

    if let castAnnotation = annotation as? MyCustomPointAnnotation {
        if (!castAnnotation.willUseImage) {
            return nil;
        }
        if (!castAnnotation.selected == true) {

            var annotationImage = mapView.dequeueReusableAnnotationImage(withIdentifier: String(describing: annotation.coordinate))
            annotationImage = MGLAnnotationImage(image: UIImage(named: "pin_deselected")!, reuseIdentifier: String(describing: annotation.coordinate))
             annotationImage?.image = textToImage(drawText: castAnnotation.stepId, inImage: (annotationImage?.image)!, atPoint: CGPoint(x: 10, y: 5))
            return annotationImage!
        }else{
            var annotationImage = mapView.dequeueReusableAnnotationImage(withIdentifier: String(describing: annotation.title))
            if(annotationImage == nil) {
                annotationImage = MGLAnnotationImage(image: UIImage(named: "pin_selected")!, reuseIdentifier: String(describing: annotation.coordinate))
            }
            annotationImage?.image = textToImage(drawText: castAnnotation.stepId, inImage: (annotationImage?.image)!, atPoint: CGPoint(x: 10, y: 5))
            return annotationImage!
        }
    }
    return nil
}
It's fire correctly the second case but the pin image doesn't change!!!! I didn't know why??

**Comment by sfla** [comment] 2019-02-28 15:05
I have two different kinds of MGLAnnotation (using MGLAnnotationImage), all the instances of the first kind updates its image correctly, and the second kind never updates correctly.
I had to use mapView.remove then mapView.add for the first to work, but it doesn't work with the other.

**Closed** 2020-05-22 10:03 UTC
Labels: archived, bug, gl-ios, iOS
