### ISSUE TITLE
ANR when adding a polyline...

### ISSUE THREAD

**Issue by Lilyandlucy** [mapbox/mapbox-gl-native#12112] opened 2018-06-11 11:37 UTC
**Platform:** Android
**Mapbox SDK version:** 5.4.1

Hello, when I add a polyline , the statck trace is below....sometimes crash......
I'm stuck on this problem several days, any help would be massively appreciated.
Regards

```ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 23.  Wait queue head age: 5741.6ms.)
com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(Native Method)
com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(SourceFile:471)
com.mapbox.mapboxsdk.maps.MarkerContainer.obtainViewsIn(SourceFile:171)
com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerViewsInRect(SourceFile:208)
com.mapbox.mapboxsdk.maps.MapboxMap.getMarkerViewsInRect(SourceFile:1274)
com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion(SourceFile:485)
com.mapbox.mapboxsdk.annotations.MarkerViewManager.update(SourceFile:471)
com.mapbox.mapboxsdk.maps.AnnotationManager.update(SourceFile:90)
com.mapbox.mapboxsdk.maps.MapboxMap.onUpdateRegionChange(SourceFile:191)
com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(SourceFile:1064)
com.mapbox.mapboxsdk.maps.MapView.onMapChange(SourceFile:572)
com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(SourceFile:862)
com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddPolylines(Native Method)
com.mapbox.mapboxsdk.maps.NativeMapView.addPolyline(SourceFile:404)
com.mapbox.mapboxsdk.maps.PolylineContainer.addBy(SourceFile:31)
com.mapbox.mapboxsdk.maps.AnnotationManager.addPolyline(SourceFile:244)
com.mapbox.mapboxsdk.maps.MapboxMap.addPolyline(SourceFile:1312)

```

**Comment by LukasPaczos** [comment] 2018-06-11 14:19
Thanks for reaching out @Lilyandlucy. This looks like a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10207. Would you mind re-testing with `v6.1.3`?

**Comment by tobrun** [comment] 2018-06-11 21:03
@Lilyandlucy are you adding any Markers to the map as well? (more specifically any MarkerViews?)

**Comment by Lilyandlucy** [comment] 2018-06-12 02:18
@tobrun  Yes, I add marker to represent the position of my airplane, and add polyline to represent the flight path... Is there any problem?

**Comment by Lilyandlucy** [comment] 2018-06-12 03:07
@tobrun  emmm...I add MarkerView as the position of my airplane

**Comment by tobrun** [comment] 2018-06-12 09:51
@Lilyandlucy, yes, considering the stacktrace indicates the usage of a Polyline with MarkerView and it seems that this isn't working as expected. Since MarkerView has been deprecated for a while and we don't have plans patching this API up. There is not much else to do as to move your MarkerView implementatiion to either Marker or SymbolLayer. (fwiw these components have better performance). Closing as the source of the issue is MarkerView and this will be removed in an upcoming release.

**Closed by tobrun** 2018-06-12 09:51 UTC
Labels: Android, needs information
