### ISSUE TITLE
Polygon annotations flicker when zooming

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#12868] opened 2018-09-11 23:27 UTC
### Steps to reproduce

 1. Create a polygon annotation and add it to an MGLMapView.
 2. Return a color from `-mapView:fillColorForPolygonAnnotation:` to give the polygon annotation a color.
 3. Zoom in and out of the map and observe flickering.

This issue reproduces when running the companion ios-sdk-examples project: https://github.com/mapbox/ios-sdk-examples/blob/master/Examples/Swift/PolygonAnnotationExample.swift 

(Caught in https://github.com/mapbox/ios-sdk-examples/issues/225)

### Expected behavior
The polygon annotation should not flicker when zooming in/out.

### Actual behavior
The polygon annotation flickers, as shown here: https://gph.is/2x9hWPe
(I would embed here but GitHub compressed the gif too much to see the issue)

Could this possibly be related to https://github.com/mapbox/mapbox-gl-native/issues/12790?

### Configuration

**Mapbox SDK versions:** All recent versions up until v3.7.8.
**iOS/macOS versions:** iOS 11.4.1
**Device/simulator models:** iPhone X, physical device
**Xcode version:** 9.4.1

**Comment by mollymerp** [comment] 2018-09-25 17:40
good call @captainbarbosa – I can reproduce this in GL core 🙃 I think this is a combination of overdraw due to prefetching and the same clipping issue in #12790. The former  might be fixed by adding a similar condition as I did here #12529

**Comment by mollymerp** [comment] 2018-09-27 00:46
consolidating this issue with other related ones over at #12981

**Closed by mollymerp** 2018-09-27 00:46 UTC
Labels: Core, bug, iOS
