### ISSUE TITLE
Mapbox showing white screen with Mapbox logo in Fragment

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [mapbox/mapbox-gl-native#10041] opened 2017-09-22 07:40 UTC
Hi,

I am adding Mapbox programmatically in Fragment, but it's showing a white screen with Mapbox logo at the bottom. If I add Mapbox programmatically in Activity, it is working.

Here is the code for Fragment:

    import android.app.Fragment;
    import android.content.Context;
    import android.location.LocationManager;
    import android.os.Bundle;
    import android.support.annotation.Nullable;
    import android.util.Log;
    import android.view.LayoutInflater;
    import android.view.View;
    import android.view.ViewGroup;
    import android.widget.LinearLayout;

    import com.mapbox.mapboxsdk.Mapbox;
    import com.mapbox.mapboxsdk.camera.CameraPosition;
    import com.mapbox.mapboxsdk.geometry.LatLng;
    import com.mapbox.mapboxsdk.maps.MapFragment;
    import com.mapbox.mapboxsdk.maps.MapView;
    import com.mapbox.mapboxsdk.maps.MapboxMap;
    import com.mapbox.mapboxsdk.maps.MapboxMapOptions;
    import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;

    import java.util.ArrayList;

    public class MapboxFragment extends Fragment {

    private MapView _mapView;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
        Mapbox.getInstance(context, "<Mapbox Key>");
        LinearLayout layout = new LinearLayout(getActivity());
        MapboxMapOptions options = new MapboxMapOptions();
        CameraPosition position = new CameraPosition.Builder()
                .target(new LatLng(39.7637, -104.9401))
                .zoom(10)
                .tilt(20)
                .build();
        options.camera(position);
        _mapView = new MapView(getActivity(), options);
        _mapView.onCreate(savedInstanceState);
        _mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                Log.e("TAG", "Map is ready");
            }
        });
        layout.addView(_mapView);
        return layout;
    }
 
    @Override
    public void onStart() {
        super.onStart();
        _mapView.onStart();
    }

    @Override
    public void onPause() {
        super.onPause();
        _mapView.onPause();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        _mapView.onDestroy();
    }

    @Override
    public void onResume() {
        super.onResume();
        _mapView.onResume();
    }

    @Override
    public void onStop() {
        super.onStop();
        _mapView.onStop();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        _mapView.onLowMemory();
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        _mapView.onSaveInstanceState(outState);
    }
    }

This code is working if I put same in Activity.
Please provide me solution for this.

Thanks

**Comment by tobrun** [comment] 2017-09-26 13:47
@Dhvl-Golakiya 

Can you add a bit more code how you are adding this to your Activity?

This code is working for me:

```java
public class SimpleMapActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_map_simple);
    getSupportFragmentManager().beginTransaction().add(R.id.fragment_container, new MapboxFragment()).commit();
  }

  public static class MapboxFragment extends Fragment {

    private MapView _mapView;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
      LinearLayout layout = new LinearLayout(getActivity());
      MapboxMapOptions options = new MapboxMapOptions();
      CameraPosition position = new CameraPosition.Builder()
        .target(new LatLng(39.7637, -104.9401))
        .zoom(10)
        .tilt(20)
        .build();
      options.camera(position);
      _mapView = new MapView(getActivity(), options);
      _mapView.onCreate(savedInstanceState);
      _mapView.getMapAsync(new OnMapReadyCallback() {
        @Override
        public void onMapReady(MapboxMap mapboxMap) {
          Log.e("TAG", "Map is ready");
        }
      });
      layout.addView(_mapView);
      return layout;
    }

    @Override
    public void onStart() {
      super.onStart();
      _mapView.onStart();
    }

    @Override
    public void onPause() {
      super.onPause();
      _mapView.onPause();
    }

    @Override
    public void onDestroy() {
      super.onDestroy();
      _mapView.onDestroy();
    }

    @Override
    public void onResume() {
      super.onResume();
      _mapView.onResume();
    }

    @Override
    public void onStop() {
      super.onStop();
      _mapView.onStop();
    }

    @Override
    public void onLowMemory() {
      super.onLowMemory();
      _mapView.onLowMemory();
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
      super.onSaveInstanceState(outState);
      _mapView.onSaveInstanceState(outState);
    }
  }
}
```

**Comment by Dhvl-Golakiya** [comment] 2017-09-26 14:34
@tobrun 

I am using Mapbox in Fusetools. I need Mapbox view layout so I am creating one Framelayout and adding Fragment like this:

```
    LinearLayout layout = new LinearLayout(context);
    LinearLayout contentLayout = new LinearLayout(context);
    contentLayout.setId(12345);
    FragmentManager manager = com.fuse.Activity.getRootActivity().getSupportFragmentManager();
    FragmentTransaction fragTransaction = manager.beginTransaction();
    mapboxFragment = new MapboxFragment();
    fragTransaction.add(ll.getId(), mapboxFragment, TAG_MAP_FRAGMENT).commit();
    layout.addView(contentLayout);
    this.addView(layout);
```

**Comment by tobrun** [comment] 2017-09-27 10:47
@Dhvl-Golakiya would you be able to share a minimum reproducible project that I can open with Fusetools? I have no background using that, happy to help resolve this issue with some additional help from your end.

**Comment by Dhvl-Golakiya** [comment] 2017-09-28 05:17
@tobrun 

Please check this project.
https://www.dropbox.com/s/dmtqfm6s8abc70j/MapBoxSample.zip?dl=0

Let me know if you need any help from me with Fusetools.

**Comment by Dhvl-Golakiya** [comment] 2017-10-09 05:18
@tobrun 
Any updates on this?

**Comment by tobrun** [comment] 2017-10-09 09:43
@Dhvl-Golakiya found the root cause, this is a compatibility with Fuse as they also use a gl surface. This results in fighting over the z-index and in this the surface of fuse tools wins. There are a couple of workarounds but they have pitfalls:

 - use [zMediaOverlay](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java#L725-L732): this will show the SurfaceView of this library on top
but will also hide any Android SDK View (eg. CompassView). 

 - use [textureMode](https://github.com/mapbox/mapbox-gl-native/blob/release-ios-v3.6.0-android-v5.1.0/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java#L683-L697): this will use a TextureView instead of SurfaceView, which solves the issue of hiding the Android SDK Views from above but isn't as fast.

Going ahead and close this as I was able to reproduce and resolve.
Feel free to reach out if you have any more questions @Dhvl-Golakiya!

**Closed by tobrun** 2017-10-09 09:43 UTC
Labels: Android, needs information, support
