### ISSUE TITLE
Map Flickers with FillLayer

### ISSUE THREAD

**Issue by dsuresh-ap** [mapbox/mapbox-gl-native#12187] opened 2018-06-20 19:44 UTC
**Platform: Android**
**Mapbox SDK version:6.1.3**

This flicker happens in our app as referenced here https://github.com/mapbox/mapbox-gl-native/issues/11950. But I also see it happening in the MapBox Demo app that is on the app store. If any workarounds or solutions are available it would be appreciated. This is the only thing holding us back from upgrading the SDK.

[Recording](https://drive.google.com/file/d/1OaHCvkAyPF6tXCN4_eWlpHLSr2Cr8Vpb/view?usp=sharing)

### Steps to trigger behavior

1. Zooming in/out on any part of the map that is dense (NYC) and contains a layer causes flickering of the layer polygon and MapBox map.

### Expected behavior

Zooming in or out should be fluid and not flicker.

### Actual behavior

Layer and map flickers randomly.

**Comment by dsuresh-ap** [comment] 2018-06-20 19:48
Update: I think I figured out what causes the issue. In the demo app on a fresh load it is fine. But as soon as you background the app and foreground it the flickering happens as seen by the recording. I think it has something to do with `onResume()`.

[Flickering after onResume](https://drive.google.com/open?id=1tTBusVKEsOQi1jxHA9tODbqiJtlEqA4r)

**Comment by LukasPaczos** [comment] 2018-07-04 12:52
Thanks for reporting the issue, closing as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/11877.

**Closed by LukasPaczos** 2018-07-04 12:52 UTC
Labels: Android, Core
