### ISSUE TITLE
Offline raster tiles does not use correct zoom level

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#9563] opened 2017-07-20 10:51 UTC
**Platform:** iOS
**Mapbox SDK version:** master as of f19c36a4ba9adb6d1288a47252a0189aac5033ce

### Steps to trigger behavior

 1. Load raster tiles for offline use. Extra zoom levels for tiles intersecting certain interesting areas.
 2. Go offline.
 3. Zoom in on one of those interesting areas with extra zoom levels.

### Expected behavior

The best tiles available at any place are shown.

### Actual behavior

When zooming in, first the best tiles are shown. Then the map gets more and more blury as the view shifts to showing less and less detailed tiles.

In the console, lots of messages like this are shown:
```
[ERROR] {}[Style]: Failed to load tile 10/527/295=>10 for source 
```

![rasterzoom](https://user-images.githubusercontent.com/445229/28414009-fac1c100-6d49-11e7-9ff4-38fb9f0c8ee8.gif)

(The above gif show wifi and cell coverage dots, but those are turned on by QuickTime. This is really offline mode.)

**Comment by halset** [comment] 2017-07-20 11:02
This is not related to offline packs. I do not use offline packs. The tiles got into the database without using offline packs.

**Comment by halset** [comment] 2017-07-20 11:04
Looks like I have a similar, but less visible problem with vector tiles.

**Comment by halset** [comment] 2017-07-20 11:07
This might be a duplicate of #9493, but that one is closed as a duplicate of #8756 that discusses blocking based on offline pack operations that I do not use. So perhaps not after all.

**Comment by jfirebaugh** [comment] 2017-07-20 15:22
My guess is it's caused by #7741. cc @tmpsantos

**Comment by halset** [comment] 2017-07-20 15:25
I bisected this to 9a9408e8111bcdcd0fcb9a93112d61ab8fce0601

**Comment by jfirebaugh** [comment] 2017-07-20 15:28
Great, thanks for bisecting. That means this is a duplicate of #8678 and will be fixed by #9415 / #9468.

**Comment by halset** [comment] 2017-07-20 16:04
Tried now. The current state of #9468 does not fix this problem. Hopefully it will in the future.

**Comment by jfirebaugh** [comment] 2017-07-20 16:56
Ok, reopening so we can investigate.

**Comment by halset** [comment] 2017-07-20 19:37
In this case, it looks like my offline tiles are expired. So it first draw the old one, then tries to fetch a fresh tile and then when the network is down the download failes and it jumps to z-1. It should probably use the tile in the database in this case even when it has expired. Does this make sense?

**Comment by halset** [comment] 2017-07-20 20:42
I worked around this issue by making sure that the offline tiles that I insert into the database has a expire value in the future. That seem to prevent mapbox from attempting to refetch the expired tiles in offline mode and then failing resulting in jumping to z-1.

**Comment by tmpsantos** [comment] 2017-07-24 11:38
We had something like this before, but it was fixed by e962b79b0f434ab80556cede425bdc1daf7730b2

**Comment by namannik** [comment] 2017-08-14 04:24
I seem to be experiencing this issue also.  Here's a video of what I'm seeing:

https://www.dropbox.com/s/p89hb976d9qha5g/offline-raster-map-issue.mov?dl=0

This video shows the following:

| Timestamp | Description |
|------------|-----------|
| 0:00 - 0:19 | Normal behavior when internet connection is available |
| 0:35 - 1:04 | Unexpected behavior when internet connection is not available (The green rectangle seen at 0:35 indicates the area that has been downloaded for offline use.) |

As you can see in the video, it appears that the offline tiles load correctly for a brief moment, and then the map cycles through tiles from lower zoom levels until it just renders blank tiles.

I'm not sure if this matters, but I'm hosting raster tiles on my own server, with the following style.  (Note that the listing below omits the full tile URL.)

```
{
    "version": 8,
    "name": "Forest Maps",
    "sources": {
        "BaseMap": {
            "type": "raster",
            "tiles": [
                "https://------/tiles/{z}/{x}/{y}.png"
            ],
            "tileSize": 128
        }
    },
    "layers": [
        {
            "id": "BaseMap",
            "type": "raster",
            "source": "BaseMap",
            "minzoom": 3,
            "layout": {
                "visibility": "visible"
            }
        }
    ]
}
```

As mentioned by @halset, the log is outputting a lot of messages like this:

```
Failed to load tile 11/393/823=>11 for source BaseMap: The Internet connection appears to be offline.
```

**Comment by namannik** [comment] 2017-08-14 04:59
I tried previous versions of the iOS SDK and found that this issue does not occur when using v3.5.4, but does occur starting with v3.6.0-alpha.1.

**Comment by halset** [comment] 2017-08-14 12:42
@namannik Could it be that your tile provider does not have an Expires http header? And that the tiles are inserted in the tiles-table with null value in the expires column? Are you able to change the tile provider so that an Expires-header are included with the tiles?

**Comment by kkaefer** [comment] 2017-08-14 12:52
@namannik @halset I was able to reproduce this error; but the fix will take a little.

**Comment by namannik** [comment] 2017-08-14 16:51
Thanks, @kkaefer.  I've rolled back the SDK used in my app to v3.5.4, so I'll be good for now.

@halset The server hosting the tiles is one that I set up, and I didn't set it to provide an "Expires" http header.  (I wasn't aware this was necessary.)  I can give that a try.  As for how the tiles are inserted into the tiles table, I'm using Mapbox's built-in `MGLOfflineStorage`, so I don't know that I have direct visibility to the contents of the table.

**Comment by halset** [comment] 2017-08-14 18:28
Looking forward to the fix, @kkaefer 👍 Thanks! 

@namannik The Expires http header should not be required. During tile fetching, some of the http headers are stored with the tiles. When offline, the tile is first fetched from the database. As the tile has expired (Expires is missing), it is refetched in the background. And when that failes, it jump to the z-1 tile and so it goes. So setting the Expires header can be a workaround for this issue. This is at least how it looks for me.

**Comment by kkaefer** [comment] 2017-09-16 00:13
@halset fix is in  https://github.com/mapbox/mapbox-gl-native/pull/10011 / https://github.com/mapbox/mapbox-gl-native/pull/10012 (for the current release branch).

I verified that this fixes flickering raster tiles when tiles are expired in offline mode. Can you confirm that this fixes the issue for you as well?

**Closed** 2017-09-21 10:20 UTC
Labels: bug, iOS

**Comment by halset** [comment] 2017-09-25 13:06
@kkaefer It is working very well. Thank you!
