### ISSUE TITLE
MGLPolyline drawing issue

### ISSUE THREAD

**Issue by stefandric** [mapbox/mapbox-gl-native#8311] opened 2017-03-08 13:16 UTC
**Platform: iOS10**
**Mapbox SDK version: 3.4.2**

### Steps to trigger behavior

 1. Draw one polyline
 2. Draw another polyline in front of this
 3. Sometimes it draws, sometimes it doesn't

### Expected behavior
Both polylines are draw.
### Actual behavior
Sometimes polyline that is on top is drawn, sometimes is not.

I have tried few things and I located a problem when I removed polyline that is draw first. After that, this polyline that is sometimes draw and sometimes not is fine(always on map). This happened after I updated MapBox framework. Any thoughts?

**Comment by jfirebaugh** [comment] 2017-03-08 15:46
Hi @stefandric. Would you mind checking if this issue is still present in the [3.5.0-beta.2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.5.0-beta.2) release? If so, can you please provide a sample application that demonstrates the issue?

**Comment by ncryu2** [comment] 2017-03-09 00:59
Hi @stefandric.  
I don't know if this is the same problem, but the two polylines are the same coordinates(different colors, width), the second polyline is not displayed.
This is because the second polyline is skipped in addAnnotations method of MGLMapview.mm.

// adding the same annotation object twice is a no-op
if ([self.annotations containsObject:annotation])
        {
            continue;
        }

**Comment by jfirebaugh** [comment] 2017-03-09 16:51
This is likely a duplicate of #7811.

**Closed by jfirebaugh** 2017-03-09 16:51 UTC
Labels: annotations, bug, iOS, needs discussion
