### ISSUE TITLE
Duplicate data in tiles

### ISSUE THREAD

**Issue by m-sasha** [mapbox/mapbox-gl-native#10377] opened 2017-11-03 11:26 UTC
This is probably not the right place to report this, but I couldn't find where to file bugs against the tiles themselves.

The tiles served from https://a.tiles.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7/, at zoom 17 and greater, contain duplicate data. The geometries described by tiles at (x,y) ,(x+1,y),(x,y+1),(x+1,y+1) for even x and y, are the same geometries, offset by the extent of the tiles so that they exactly the same when drawn. In other words, each tile has all the data needed to render the other tiles as well.

In the attached screenshot, only the tiles marked by the green outline are rendered (with clipping disabled).

![device-2017-11-03-132133](https://user-images.githubusercontent.com/5230206/32371584-19c3f64c-c09a-11e7-9548-4df2f2b19e29.png)

**Comment by jfirebaugh** [comment] 2017-11-03 14:59
Thanks for the report @m-sasha -- we are aware of this issue and tracking it internally. Closing here since it's not a bug in Mapbox GL itself.

**Closed by jfirebaugh** 2017-11-03 14:59 UTC
