### ISSUE TITLE
Fatal Exception: std::runtime_error: in get<T>()

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#3681] opened 2016-01-24 20:11 UTC
I've seen this crash popping up in my log files. I haven't had any users contact me to reproduce yet, so I unfortunately don't have steps to guide towards how to reproduce. I've seen this crash ~100 times from ~30 users (reported from Fabric) since Jan 1 with a user-base of 15k MAU. So not huge % of the population, but still a crasher.

```
Crashed: Map
SIGABRT ABORT 0x0000000182e2c140

Thread : Crashed: Map
0  Slopes                         0x10028b2a0 CLSProcessRecordAllThreads + 4297683616
1  Slopes                         0x10028b2a0 CLSProcessRecordAllThreads + 4297683616
2  Slopes                         0x10028b6c0 CLSProcessRecordAllThreads + 4297684672
3  Slopes                         0x10027c61c CLSHandler + 4297623068
4  Slopes                         0x100289bf0 __CLSExceptionRecord_block_invoke + 4297677808
5  libdispatch.dylib              0x182cdd5f0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x182ce889c _dispatch_barrier_sync_f_invoke + 100
7  Slopes                         0x10028969c CLSExceptionRecord + 4297676444
8  Slopes                         0x100289220 CLSTerminateHandler() + 4297675296
9  libc++abi.dylib                0x1828eaf44 std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x1828ea85c __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
11 Slopes                         0x100511924 mapbox::util::geojsonvt::Convert::calcRingBBox(mapbox::util::geojsonvt::ProjectedPoint&, mapbox::util::geojsonvt::ProjectedPoint&, mapbox::util::geojsonvt::ProjectedGeometryContainer const&) + 50268
12 Slopes                         0x1005110c0 mapbox::util::geojsonvt::Convert::create(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, mapbox::util::geojsonvt::ProjectedFeatureType, mapbox::util::variant<mapbox::util::geojsonvt::ProjectedPoint, mapbox::util::geojsonvt::ProjectedGeometryContainer>) + 48120
13 Slopes                         0x10053b03c mbgl::ShapeAnnotationImpl::updateTile(mbgl::TileID const&, mbgl::AnnotationTile&) + 4764
14 Slopes                         0x100520a64 mbgl::AnnotationManager::getTile(mbgl::TileID const&) + 5084
15 Slopes                         0x100521248 mbgl::AnnotationManager::addTileMonitor(mbgl::AnnotationTileMonitor&) + 7104
16 Slopes                         0x10053831c mbgl::AnnotationTileMonitor::monitorTile(std::__1::function<void (std::exception_ptr, std::__1::unique_ptr<mbgl::GeometryTile, std::__1::default_delete<mbgl::GeometryTile> >)>) + 3304
17 Slopes                         0x1005704e4 mbgl::VectorTileData::VectorTileData(mbgl::TileID const&, std::__1::unique_ptr<mbgl::GeometryTileMonitor, std::__1::default_delete<mbgl::GeometryTileMonitor> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mbgl::Style&, std::__1::function<void ()> const&) + 1040
18 Slopes                         0x1005661d0 std::__1::shared_ptr<mbgl::VectorTileData> std::__1::shared_ptr<mbgl::VectorTileData>::make_shared<mbgl::TileID const&, std::__1::unique_ptr<mbgl::GeometryTileMonitor, std::__1::default_delete<mbgl::GeometryTileMonitor> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, mbgl::Style&, std::__1::__bind<void (mbgl::Source::*)(mbgl::TileID const&, mbgl::TransformState const&, bool), mbgl::Source*, mbgl::TileID const&, mbgl::TransformState const&, bool>&>(mbgl::TileID const&&&, std::__1::unique_ptr<mbgl::GeometryTileMonitor, std::__1::default_delete<mbgl::GeometryTileMonitor> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&, mbgl::Style&&&, std::__1::__bind<void (mbgl::Source::*)(mbgl::TileID const&, mbgl::TransformState const&, bool), mbgl::Source*, mbgl::TileID const&, mbgl::TransformState const&, bool>&&&) + 232
19 Slopes                         0x10056365c mbgl::Source::addTile(mbgl::MapData&, mbgl::TransformState const&, mbgl::Style&, mbgl::TexturePool&, mbgl::TileID const&) + 14388
20 Slopes                         0x100563f84 mbgl::Source::update(mbgl::MapData&, mbgl::TransformState const&, mbgl::Style&, mbgl::TexturePool&, bool) + 16732
21 Slopes                         0x1005aeb1c mbgl::Style::update(mbgl::TransformState const&, mbgl::TexturePool&) + 4132
22 Slopes                         0x10055e798 mbgl::MapContext::update() + 7168
23 Slopes                         0x1005065b4 uv_async_init + 4332
24 Slopes                         0x100506774 uv__async_init + 4780
25 Slopes                         0x10050a33c uv__io_poll + 20084
26 Slopes                         0x100506b24 uv_run + 5724
27 Slopes                         0x10055930c void mbgl::util::Thread<mbgl::MapContext>::run<std::__1::tuple<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>, 0ul, 1ul, 2ul>(mbgl::util::ThreadContext, std::__1::tuple<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul>) + 156
28 Slopes                         0x100559214 std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::MapContext>::Thread<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>(mbgl::util::ThreadContext const&, mbgl::View&&&, mbgl::FileSource&&&, mbgl::MapData&&&)::'lambda'()> >(void*, void*) + 176
29 libsystem_pthread.dylib        0x182ef3b28 _pthread_body + 156
30 libsystem_pthread.dylib        0x182ef3a8c _pthread_body + 154
31 libsystem_pthread.dylib        0x182ef1028 thread_start + 4
```

**Comment by jfirebaugh** [comment] 2016-01-24 20:49
Duplicate of #2926.

**Closed by jfirebaugh** 2016-01-24 20:49 UTC
