### ISSUE TITLE
File I/O Error when downloading on sleep mode.

### ISSUE THREAD

**Issue by carlosmellado** [mapbox/mapbox-gl-native#5592] opened 2016-07-06 16:32 UTC
Hello,
trying to enable downloads on background, when I put the iPhone on sleep mode, the app crashes and I receive "disk I/O error". As far as I know, you should disable data protection on SQLite (SQLITE_OPEN_FILEPROTECTION_NONE).

Platform: **iOS**
SDK Version: **~>3.2.3**

### Steps to trigger behavior

 1. Enable a UIBackgroundTaskIdentifier
 2. Start downloading a map
 3. Enter on sleep mode and wait a few seconds (less than 10).
 4. The app crashes.

![captura de pantalla 2016-07-06 a las 18 24 33](https://cloud.githubusercontent.com/assets/1913109/16626138/e5abed80-43a7-11e6-8898-e17e8ba8c1a5.png)

**Comment by jfirebaugh** [comment] 2016-07-06 17:20
Marking this as a duplicate of #4841, but thanks for the hint about `SQLITE_OPEN_FILEPROTECTION_NONE`, that's very helpful.

**Closed by jfirebaugh** 2016-07-06 17:20 UTC
