### ISSUE TITLE
Categorical styling crashes

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#11276] opened 2018-02-21 22:42 UTC
**Platform: iOS**
**Mapbox SDK version: v4.0.0-beta.2**

### Steps to trigger behavior

Consid the code:
 ```swift
line.lineColor = NSExpression(format: "%@.severe", [
    "unknown": UIColor.blue,
    "low": UIColor.green,
    "moderate": UIColor.yellow,
    "heavy": UIColor.red,
    "severe": UIColor.purple
])
```

### Expected behavior

The line would be colored purple.

### Actual behavior

Crash:

![image](https://user-images.githubusercontent.com/1058624/36509423-90702704-1714-11e8-99b6-e146683d6d45.png)

/cc @1ec5 @anandthakker

**Comment by anandthakker** [comment] 2018-02-22 01:47
Thanks @bsudekum  -- this is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10849.  Fix incoming shortly!

**Closed by anandthakker** 2018-02-22 01:47 UTC
Labels: bug, iOS
