### ISSUE TITLE
Android: setOnMarkerViewClickListener not working

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#9546] opened 2017-07-19 09:30 UTC
I add a markerview to my map in this way:

`map.addMarker(new MarkerViewOptions()
                                .position(new LatLng(result.Lat + 0.0003, result.Lon + 0.0003))
                                .title(result.Name)
                                .snippet("spawnitem")
                                .icon(icon)
                );`

Marker is added well, and the I implement a click listener in this way:

`map.getMarkerViewManager().setOnMarkerViewClickListener(new MapboxMap.OnMarkerViewClickListener() {

                    @Override
                    public boolean onMarkerClick(@NonNull Marker marker, @NonNull View view, @NonNull MapboxMap.MarkerViewAdapter adapter) {

                        return false;
                    }

                })`

When debugging and clicking on marker, infowindow is showed but code inside onmarkerClick is never called... Is this a bug?

**Comment by tobrun** [comment] 2017-07-19 13:17
Not able to reproduce this on master:

![ezgif com-video-to-gif 69](https://user-images.githubusercontent.com/2151639/28368636-5866c14e-6c95-11e7-9cb4-30ec0e1bec53.gif)

The toast shown above is shown as a result of OnMarkerViewClickListener.

@nijs9 Which version of the SDK are you using?

**Comment by Guardiola31337** [comment] 2017-07-20 16:17
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/9567

@nijs9 it'll be included in the next release [`5.1.1`](https://github.com/mapbox/mapbox-gl-native/issues/9564)
Thanks a lot for reporting it.

Closing.

**Closed by Guardiola31337** 2017-07-20 16:17 UTC
Labels: Android
