### ISSUE TITLE
EXC_BAD_ACCESS on iOS 3.0.0-pre.5

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#2971] opened 2015-11-07 14:25 UTC
I've just been having a go with 3.0.0-pre.5, and I seem to be able to trigger an `EXC_BAD_ACCESS` when I zoom the map in and out quickly. I'm not sure how to export the stack trace, so I've included a screenshot. This happens inside my CityCyclist app - happy to give you the latest source so you can try to reproduce.

![2015-11-07 at 14 23](https://cloud.githubusercontent.com/assets/565/11015558/3f0eab76-855b-11e5-8f41-fe93bca62806.png)

**Comment by 1ec5** [comment] 2015-11-07 18:26
Can you link against the “-symbols” build of the SDK and build in the Debug configuration (without optimization)? That may enable us to see more clearly what’s going on.

**Comment by 1ec5** [comment] 2015-11-07 18:27
You can export the stack trace by selecting the entire stack in the sidebar and copy-pasting it here or in a gist.

**Comment by tomtaylor** [comment] 2015-11-07 21:20
@1ec5 here's the stack trace, with the symbols build. It doesn't seem to give much more information I'm afraid. https://gist.github.com/tomtaylor/9c687af59100cbaf899a

**Comment by 1ec5** [comment] 2015-11-07 22:11
Most likely a duplicate of #2962.

**Closed by 1ec5** 2015-11-07 22:11 UTC
Labels: crash, iOS
