### ISSUE TITLE
Blacklist GL program binary caching Adreno GPUs

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9473] opened 2017-07-11 07:45 UTC
We are noticing some render artefacts on master:

![ezgif com-video-to-gif 66](https://user-images.githubusercontent.com/2151639/28056441-3947bd28-661d-11e7-88ca-cef43b02f24d.gif)

Since labels, borders etc aren't showing at the appropriate zoom levels, I'm hunching that this will be related

Was tested on a Nexus 5 running Android 4.4. also reproducible on a Moto X running 5.1

**Comment by tobrun** [comment] 2017-07-11 07:56
Got a reproducible scenario from a clean install:

![ezgif com-video-to-gif 68](https://user-images.githubusercontent.com/2151639/28057068-36008364-661f-11e7-92fb-5766ed38b2e1.gif)

First time the map renders correctly, second time the map doesn't anymore.

Going to `git bisect` this issue

**Comment by tobrun** [comment] 2017-07-11 08:40
Bisected it to commit b5fed1172d77bac0ba122c73a9d30739a51e5028 from https://github.com/mapbox/mapbox-gl-native/pull/9373. 
Reproducible on `attribute-location` from https://github.com/mapbox/mapbox-gl-native/pull/9433.

cc @lbud @jfirebaugh

**Comment by jfirebaugh** [comment] 2017-07-11 22:23
This likely is an issue with program binary caching. It doesn't reproduce on the S4 I've been testing #9433 with, although it does support program binaries. Do we have a Nexus 5 or Moto X in our SF inventory?

**Comment by tobrun** [comment] 2017-07-12 08:08
@danswick, I remember you having an Moto X? Would you be able to check the SF inventory?

**Comment by jfirebaugh** [comment] 2017-07-12 22:51
@tobrun Is this still reproducible after merging the speculative fixes for binary caching in #9433?

**Comment by tobrun** [comment] 2017-07-13 06:12
Still reproducible. @danswick were you able to find the Moto X?

**Comment by Guardiola31337** [comment] 2017-07-14 15:00
@jfirebaugh still reproducible in a Moto X (2nd gen) running Android 5.0 and in a Nexus 5 running Android 6.0
cc/ @tobrun @danswick

**Comment by jfirebaugh** [comment] 2017-07-17 22:04
Couldn't reproduce this on the Nexus 5 device in the SF office. We're going to order a dedicated Moto X test device for the SF office.

**Comment by edpop** [comment] 2017-07-18 05:26
Still artefacts on Mapbox Demo 5.1.0-6, ASUS_T001.

**Comment by jfirebaugh** [comment] 2017-07-19 15:04
While we're waiting for the device to be delivered -- @Guardiola31337, can you check if this happens on the release branch? b5fed1172d77bac0ba122c73a9d30739a51e5028 got cherry-picked to the release branch in eed89fcf9d099266aa793375ad63493e880f8a80 (as part of #9440), and the issue might have come with it.

**Comment by jfirebaugh** [comment] 2017-07-19 15:04
@edpop, I think you're experiencing a different issue. This issue was not in the 5.1.0 release.

**Comment by Guardiola31337** [comment] 2017-07-19 16:29
@jfirebaugh 
> can you check if this happens on the release branch?

I tried it on [`release-ios-v3.6.0-android-v5.1.0`](https://github.com/mapbox/mapbox-gl-native/tree/release-ios-v3.6.0-android-v5.1.0) branch and the same thing happens (both Nexus 5 and Moto X).

**Comment by edpop** [comment] 2017-07-19 23:19
@jfirebaugh 
> I think you're experiencing a different issue. This issue was not in the 5.1.0 release.

But the issue is closed https://github.com/mapbox/mapbox-gl-native/issues/9184 as duplicate of closed https://github.com/mapbox/mapbox-gl-native/issues/8658. Maybe we should to reopen it?

**Comment by jfirebaugh** [comment] 2017-07-19 23:23
#9184 is a duplicate of #8658. #8658 is _not_ a duplicate of this issue; the fix for #8658 caused this issue.

**Comment by jfirebaugh** [comment] 2017-07-19 23:25
#9184 is a duplicate of #8658. #8658 is not a duplicate of this issue; the fix for #8658 caused this issue.

[Adding to the confusion, Github is now going to _oh so helpfully_ report that I marked this as a duplicate of #8658 because I wrote "is a duplicate of #8658". THANKS GITHUB!]

**Comment by 1ec5** [comment] 2017-07-20 01:32
#9184 is a đüṕłīçåťə of #8658. 😉

**Comment by jfirebaugh** [comment] 2017-07-20 19:31
Both Nexus 5 and Moto X use Adreno 3xx GPUs, so this is very likely https://bugs.chromium.org/p/chromium/issues/detail?id=510637.

**Comment by jfirebaugh** [comment] 2017-07-20 19:35
Looks like we should blacklist program crashing for all Adreno GPUs: https://chromium.googlesource.com/chromium/src/gpu/+/master/config/gpu_driver_bug_list.json#2316

**Closed** 2017-07-21 16:31 UTC
Labels: Android, Core
