### ISSUE TITLE
Annotation view dont show custom icon, show default icon instead

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#7063] opened 2016-11-15 04:52 UTC
**Platform:**IOS
**Mapbox SDK version:**3.4.0-alpha.4

### Steps to trigger behavior

 1. Add annotation view with custom icon to the map (at this time, the annotation view shows as expected).
 2. move the map around
 3. Call:
`- (void)setCenterCoordinate:(CLLocationCoordinate2D)centerCoordinate zoomLevel:(double)zoomLevel direction:(CLLocationDirection)direction animated:(BOOL)animated completionHandler:(nullable void (^)(void))completion;`
Sometimes the custom icon is not showed, default icon is showed instead.
![img_0989](https://cloud.githubusercontent.com/assets/962484/20293522/d772342e-ab29-11e6-9f7f-dcbb8920fa5b.jpg)

**Comment by boundsj** [comment] 2016-11-15 17:18
@kingfisherphuoc are you referring to an instance of the `MGLUserLocationAnnotationView` not representing the user location as you would expect? It appears so from your description but I want to double check since `annotation view with custom icon` could mean any type of annotation.

Also note that we are now on [beta 2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.4.0-beta.2) with a 3rd beta expected a few hours from now. Can you please update to the latest beta(s) and test again?

**Comment by boundsj** [comment] 2016-12-14 05:36
@kingfisherphuoc I'm not able to reproduce the behavior you describe (insofar as I understand what you are trying to report). I'm closing this but please feel free to test on the latest beta and reopen with more detailed repro steps or an example project that reproduces the issue. Thanks.

**Closed by boundsj** 2016-12-14 05:36 UTC
Labels: annotations, iOS
