### ISSUE TITLE
Android runtime styling changes not updated when changing existing layer's filter

### ISSUE THREAD

**Issue by mkv123** [mapbox/mapbox-gl-native#6063] opened 2016-08-18 07:36 UTC
**Platform:** Android
**Mapbox SDK version:** Nightly

### Steps to trigger behavior

 1.  Load up a style url
 2.  Set a timer to change one of the existing layers' filter periodically.
(our case is highlighting different areas)
 
### Expected behavior
Styles update according to a specified filter

### Actual behavior
The initial render actually looks about right, but consecutive changes to the filter aren't visible on screen. Zooming in or out a full level seems to cause the current correct style to be rendered (and cached) on that zoom level, but again once all zoom levels are populated updates seem pretty erratic. Also sometimes it seems that things are only updated to a tile border.

I've tried invalidate() on MapView, MapboxMap, and individual layers, as workaround, but doesn't help. 

Apologies for the lack of code to demonstrate the issue, I just wanted to give you a heads up as quickly as possible about this issue.

**Comment by ivovandongen** [comment] 2016-08-18 10:45
@mkv123 Thanks for the report. I'll try to reproduce this myself. To be clear; have you tried the same on layers you added through the runtime style api?

**Comment by mkv123** [comment] 2016-08-18 10:47
No I have not. I've only tried it by modifying the filters of layers coming from through the style url.

**Comment by incanus** [comment] 2016-08-18 16:26
@mkv123 Would https://github.com/mapbox/mapbox-gl-native/issues/6040 properly capture the scope of your problem, i.e. is it a dupe? Seems like it is.

**Comment by incanus** [comment] 2016-08-18 19:56
Dupe of #6040, which is actually #5701 at the root.

**Comment by mkv123** [comment] 2016-08-18 20:53
Updating just to confirm: Initially was sceptical about being a dupe of #6040 as I was changing more than just integer params. Looking at the screen capture in #6040 it does look very similar to what I was seeing and #5701 explains what I was seeing and is not integer value specific.

**Comment by ivovandongen** [comment] 2016-08-23 10:41
Re-opened as we still need to track and test this for the 4.2.0 release.

**Closed** 2016-09-06 21:29 UTC
Labels: Android, bug, Core GL, runtime styling
