### ISSUE TITLE
Suggestion: assert if mapview.onDestroy() is wrongly called from a fragments onDestroy() method (or document this gotcha clearly)

### ISSUE THREAD

**Issue by thomanil** [mapbox/mapbox-gl-native#12994] opened 2018-10-01 10:47 UTC
### Actual behavior

I have the mapbox mapview inside a fragment in my project. I had the lifecycle methods hooked up, and upon exiting the activity with the fragment that encapsulated the mapview, after a few seconds I got a hard native crash/tombstone. 

It took me a long while to figure out that the issue was that since I am using a fragment to encapsulate mapview, I need to call mapview.onDestroy() from my fragments onDestroyView(), not from onDestroy().

### Suggested behavior

If possible: would be great if mapView.onDestroy() did an assert on whether or not the caller was a fragment or activity, and showed an obvious debug warn message or threw an runtime exception with a helpful hint.

Alternatively, just state this gotcha very explicitly in the setup documentation, eg. here: https://www.mapbox.com/android-docs/maps/overview/#5-lifecycle-methods

Would save others the same rabbit hunt I just went through. :)

**Comment by tobrun** [comment] 2018-10-09 12:03
Thank you for the report @thomanil , I feel your frustration on this issue. We are trying to address the root cause of this issue in https://github.com/mapbox/mapbox-gl-native/issues/11685. 

> If possible: would be great if mapView.onDestroy() did an assert on whether or not the caller was a fragment or activity, and showed an obvious debug warn message or threw an runtime exception with a helpful hint.

This would indeed be a better UX though I'm not sure if you can actually detect wether the caller was a fragment or activity? The context will in both cases be the hosting activity. How would you implement this? 

> Alternatively, just state this gotcha very explicitly in the setup documentation, eg. here: https://www.mapbox.com/android-docs/maps/overview/#5-lifecycle-methods

Yes, I ticketed out this issue in https://github.com/mapbox/android-docs/issues/660



Closing as we already have an issue covering the root cause and follow up ticket was created in our docs repo. That you for reaching out and using our products @thomanil !

**Closed by tobrun** 2018-10-09 12:03 UTC
Labels: Android

**Comment by thomanil** [comment] 2018-10-09 12:12
No idea how to detect if caller is fragment or activity now that I think about it, so doc adjustment is probably most straightforward. :) Thanks!
