### ISSUE TITLE
[Android] MarkerView anchor problem

### ISSUE THREAD

**Issue by Hugoo13** [mapbox/mapbox-gl-native#5604] opened 2016-07-07 08:09 UTC
In Android, with the previous version we used (4.1.0-beta3), the marker view anchor works fine. See :

![v4 1 0-beta 3](https://cloud.githubusercontent.com/assets/3592767/16646506/bb338f12-442a-11e6-8a80-b1de1f9f9688.gif)

With the version 4.1.0, markers view move when we rotate the map
![v4 1 0](https://cloud.githubusercontent.com/assets/3592767/16646413/4bfde854-442a-11e6-9c8c-a9b8f32504b3.gif)

**Comment by tobrun** [comment] 2016-07-07 08:34
thank you for reaching, duplicate of #5513, picking this up now there.

**Closed by tobrun** 2016-07-07 08:34 UTC
Labels: Android, annotations, bug

**Comment by tobrun** [comment] 2016-07-07 08:54
@Hugoo13 proposed solution in #5605
