### ISSUE TITLE
Random crash when scroll and zoom

### ISSUE THREAD

**Issue by Phanith-Fe** [mapbox/mapbox-gl-native#10891] opened 2018-01-10 17:30 UTC
**Platform:*iOS 11.2*
**Mapbox SDK version:*3.7.2*

### Steps to trigger behavior

 1. Run the code sample from Mapbox document
 2. Start scrolling
 3. Start zoom in and zoom out several time

### Actual behavior
Randomly crash, sometime crash on startup, sometime crash when scroll or zooming.
<img width="1440" alt="screen shot 2018-01-10 at 10 52 58 am" src="https://user-images.githubusercontent.com/22009512/34786360-8d2177ac-f666-11e7-9f64-8f8276290666.png">
<img width="1440" alt="screen shot 2018-01-10 at 10 53 15 am" src="https://user-images.githubusercontent.com/22009512/34786365-90b0f794-f666-11e7-80df-ea76554de719.png">
<img width="1440" alt="screen shot 2018-01-10 at 10 53 24 am" src="https://user-images.githubusercontent.com/22009512/34786370-961df6fa-f666-11e7-86f9-4344c744cc75.png">
<img width="1440" alt="screen shot 2018-01-10 at 10 53 24 am" src="https://user-images.githubusercontent.com/22009512/34786374-98b9bd0e-f666-11e7-991f-e5059e3b4b2d.png">

**Comment by akitchen** [comment] 2018-01-12 22:27
Hello - this isn't very clear, and we certainly haven't heard of cases of crashing on app startup. We're not able to reproduce any of this within any of our sample apps. Would you please post a sample project which demonstrates the issue you're having?

The logs of HTTP requests aren't relevant to the issue, and can be ignored.

**Comment by mdakram** [comment] 2018-01-13 07:30
may be related to [https://github.com/mapbox/mapbox-gl-native/pull/10791](issue) fixed in v3.7.3

**Comment by fabian-guerra** [comment] 2018-01-17 15:41
Hi, @mdakram. Did v3.7.3 fixed the problem?

**Comment by mdakram** [comment] 2018-01-18 06:40
@fabian-guerra using v3.7.3 and not getting these crashes.

**Comment by fabian-guerra** [comment] 2018-01-18 14:43
Hi, @mdakram. I am going to close this issue then. Feel free to reopen it if you get crashes again.

Thank you.

**Closed by fabian-guerra** 2018-01-18 14:43 UTC
Labels: iOS

**Comment by Phanith-Fe** [comment] 2018-01-18 17:01
The issue is not fixed in latest release. Here is my sample project @fabian-guerra 
https://github.com/Phanith-Fe/MapboxSample1

**Comment by Phanith-Fe** [comment] 2018-01-18 17:05
Here is video about that issue. @fabian-guerra @mdakram 
https://drive.google.com/open?id=14N4ERNi_4p5945gO2jmGm5rS7hueVZz-

**Comment by Phanith-Fe** [comment] 2018-01-18 17:08
Now I'm on v3.6.4 and everything is working fine.

**Comment by fabian-guerra** [comment] 2018-01-18 18:15
Hi, @Phanith-Fe. I am testing your sample project in my phone and simulator and I don't get a crash. I tried `v3.7.2` and `v3.7.3` using an iPhone 6+ and iOS 11.2.2. In your video as soon as you open the app and scroll you get the crash is it consistent?

**Comment by Phanith-Fe** [comment] 2018-01-19 03:12
Hi, @fabian-guerra 
It's not always crash, but most of the time, it crash.
Is it a phone or cpu model related? I'm on iPhone 5s, with iOS 11.2.2.
