### ISSUE TITLE
onMapReady not getting called when offline

### ISSUE THREAD

**Issue by tnightingale** [mapbox/mapbox-gl-native#4486] opened 2016-03-28 08:37 UTC
When running on my tablet (Nexus 9, Android 6) with WiFi disabled **before opening the application**. The map loads if there is an offline region available or ambient cache **but** the <code>onMapReady()</code> callback is not fired after <code>mapView.getMapAsync()</code> is called.

I'm seeing this in [my own application](https://github.com/tnightingale/Mapbox/blob/mapboxgl-android-4.x.x/src/android/MapboxManager.java#L98-L100) and in the [Android test application](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/OfflineActivity.java#L83-L85). On both the current gradle/maven SNAPSHOT release *and* the latest master branch built from source.

There seem to be some similar issues floating around:
 - https://github.com/mapbox/mapbox-gl-native/issues/4439
 - https://github.com/mapbox/mapbox-gl-native/issues/4393
 - https://github.com/mapbox/mapbox-gl-native/issues/4438

And maybe a fix here?
 - https://github.com/mapbox/mapbox-gl-native/pull/4462

Though I still encounter this on the SNAPSHOT build - would that not include the changes made in #4462?

**Comment by jfirebaugh** [comment] 2016-03-28 15:21
Is this different than #4393 in some way?

**Comment by tnightingale** [comment] 2016-03-28 17:08
@jfirebaugh only that it is happening using both the default streets and emerald styles and not a custom style. I see someone else has reported something similar over there too. Happy to close if it is duplicate.

**Comment by zugaldia** [comment] 2016-03-28 20:58
@tnightingale I just tried ambient caching and offline download for the default `mapbox://styles/mapbox/streets-v8` in the TestApp in branch `release-ios-3.2.0-android-4.0.0` and, in both cases, I'm seeing the `Map is ready` message show in the logs. Just to clarify, your experience is that you don't see this message (or any code inside the `OnMapReadyCallback`), is that right?

Could you check again making sure your cache is clean? You might be hitting an old SNAPSHOT that doesn't include the latest fixes.

**Comment by tnightingale** [comment] 2016-03-28 21:07
My test case is as follows:

Put breakpoints on the following two lines:
 1. [Call to mMapView.getMapAsync()](https://github.com/mapbox/mapbox-gl-native/blob/release-ios-3.2.0-android-4.0.0/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java#L82)
 2. [first line of onMapReady()](https://github.com/mapbox/mapbox-gl-native/blob/release-ios-3.2.0-android-4.0.0/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java#L85)

Ensure WiFi is disabled on the tablet (or Airplane mode is enabled).

Build and run testapp with the Android Studio debugger and load the OfflineActivity and observe: 
 1. Execution pauses on breakpoint 1.
 2. I press 'continue' expecting execution to eventually pause on breakpoint 2.
 3. Nothing.

I have just pulled the latest version of the release-ios-3.2-android-4.0.0 branch and will retry the above steps once it has finished building.

**Comment by tnightingale** [comment] 2016-03-28 21:18
I have just performed the above test with latest release-ios-3.2-android-4.0.0 built from source and execution is pausing on breakpoint 2 as expected *after* some tiles are in the cache.

My guess is that last night I was testing with a stale version of the SNAPSHOT release?

Just to clarify as I am not familiar with the inner-workings of maven repositories: How often is the SNAPSHOT release updated? Is it always building the latest version of whatever repository branch it is pointing at?

**Comment by zugaldia** [comment] 2016-03-28 21:36
@tnightingale thank you very much for your efforts testing this. If I understand you well, with the latest code from the `release-ios-3.2.0-android-4.0.0` branch you're no longer seeing this problem with stock styles. This seems to indicate that we might be seeing the same situation as in #4393.

No worries about the SNAPSHOT process, let me elaborate. We basically build those nightly out of `master`. Because we're now in the middle of a release process and we've already cut a release branch (the one mentioned above), we're now building those SNAPSHOTs nightly off of the release branch. That means a SNAPSHOT is very close to what the final release looks like and pretty safe to try. Once we release, we'll build again off of `master`. I hope this helps.

I'm closing this now as a duplicate of #4393 but please do reopen if you find this issue again.

**Closed by zugaldia** 2016-03-28 21:36 UTC
Labels: Android

**Comment by tnightingale** [comment] 2016-03-28 21:44
Yes things appear to be functioning as expected using stock styles and running both the SNAPSHOT release and the latest code from release-ios-3.2.0-android-4.0.0 branch.

Thanks for the help :)
