### ISSUE TITLE
Crash At Startup

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1466] opened 2015-05-07 21:21 UTC
The TestApp crashes at startup.  I'm running off the `master` branch at the latest commit dcbf4940daa35994e3d4f73a130af9476274e745.

```
05-07 16:12:52.960  14036-14036/? I/SELinux﹕ Function: selinux_android_load_priority [0], There is no sepolicy file.
05-07 16:12:52.970  14036-14036/? I/SELinux﹕ Function: selinux_android_load_priority , spota verifySig and checkHash pass. priority version is VE=SEPF_SAMSUNG-SM-G900A_4.4.2_0034
05-07 16:12:52.970  14036-14036/? I/SELinux﹕ selinux_android_seapp_context_reload: seapp_contexts file is loaded from /data/security/spota/seapp_contexts
05-07 16:12:52.970  14036-14036/? E/dalvikvm﹕ >>>>> Normal User
05-07 16:12:52.970  14036-14036/? E/dalvikvm﹕ >>>>> com.mapbox.mapboxgl.testapp [ userId:0 | appId:10249 ]
05-07 16:12:53.200  14036-14036/com.mapbox.mapboxgl.testapp I/PersonaManager﹕ getPersonaService() name persona_policy
05-07 16:12:53.220  14036-14036/com.mapbox.mapboxgl.testapp I/PersonaManager﹕ getPersonaService() name persona_policy
05-07 16:12:53.240  14036-14036/com.mapbox.mapboxgl.testapp I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
05-07 16:12:53.240  14036-14036/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 409: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
05-07 16:12:53.240  14036-14036/com.mapbox.mapboxgl.testapp I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
05-07 16:12:53.240  14036-14036/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 431: Landroid/content/res/TypedArray;.getType (I)I
05-07 16:12:53.270  14036-14057/com.mapbox.mapboxgl.testapp E/libEGL﹕ validate_display:255 error 3008 (EGL_BAD_DISPLAY)
05-07 16:12:53.270  14036-14057/com.mapbox.mapboxgl.testapp E/mbgl﹕ {0}{Map}[OpenGL]: eglMakeCurrent() returned error 12296
05-07 16:12:53.270  14036-14057/com.mapbox.mapboxgl.testapp A/libc﹕ Fatal signal 6 (SIGABRT) at 0x000036d4 (code=-6), thread 14057 (apboxgl.testapp)
```

/cc @ljbade

**Comment by bleege** [comment] 2015-05-07 21:37
Related to #1435 ?

**Comment by ljbade** [comment] 2015-05-07 22:25
@bleege yeah that this is a dupe of #1435, same crash. If you try the 1435 branch you will see I fixed the crash but now hang.

**Closed by ljbade** 2015-05-07 22:25 UTC
Labels: Android, crash

**Comment by bleege** [comment] 2015-05-07 22:31
Awesome!  Yep, I just did try the #1435 branch and got the "black screen of death".
