### ISSUE TITLE
[android] Remove MathUtils

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#11182] opened 2018-02-13 10:38 UTC
We should remove [MathUtils](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/MathUtils.java) once https://github.com/mapbox/mapbox-java/pull/719 lands and a new beta of MAS 3.0 is available.

Need to keep this in mind in future releases of Mapbox Maps SDK as MAS moves forward.

cc @tobrun @cammace @osana @electrostat

**Comment by tobrun** [comment] 2018-02-13 12:39
I'm only now noticing the impact what this would have, the issue is that MathUtils will be included in mas-services, while the SDK doesn't use that dependency (only telem + geojson).

**Comment by lilykaiser** [comment] 2018-02-13 15:12
Can this be closed?

**Closed** 2018-02-13 15:35 UTC
Labels: Android
