### ISSUE TITLE
Map is reused across screens

### ISSUE THREAD

**Issue by samiede** [mapbox/mapbox-gl-native#15479] opened 2019-08-26 09:10 UTC
### Steps to reproduce

 1. Instantiate screen with a map on it
 2. Instantiate second screen and fill map with data from completely different store
 3. Maps retain instance when switching screens

### Expected behavior

Both screens show different maps

### Actual behavior

Both screens show the same map

![mapbox](https://user-images.githubusercontent.com/6050746/63679507-bccb5a00-c7f1-11e9-9ffd-3818d06089ee.gif)

### Configuration

**Android versions:** 9
**Device models:** Pixel 3, OnePlus5, OnePlus 7
**Mapbox SDK versions:** 8.0.1

**Comment by tobrun** [comment] 2019-09-09 07:25
@samiede 
Wonder if you are using fragments? and if yes, how are you performing the fragment transactions? It seems you are overlapping the fragments instead of replacing them.

That said, the root cause of your issue here is the usage of GLSurfaceView. You seem to be adding a second on top of the first (see section above) and since surfaces aren't part of the view hierachy, they fight over the z index behind the window.

An easy fix is to use TextureView instead, while that would result in removing the visual artefact, it wouldn't really resolve the root cause. You can enable TextureView through xml attributes (`mapbox_renderTextureMode="true"`) or `MapboxMapOptions#textureMode(true)`.

Closing as answered

**Closed by tobrun** 2019-09-09 07:25 UTC
Labels: Android
