### ISSUE TITLE
API to allow the camera to point a bit above its target

### ISSUE THREAD

**Issue by BoD** [mapbox/mapbox-gl-native#10034] opened 2017-09-20 18:38 UTC
**Platform:** Android
**Mapbox SDK version:** 5.1.0

In an ongoing navigation scenario, it is usual to make the camera track the snapped device location, with a tilt, but with the location showing at the bottom of the map (so more of the rest of the route is visible).
Currently (correct me if I'm wrong) the center of the camera target will always be at the center of the map. 

So to do this, you need to make the camera actually point a bit "above" of the actual location - by calculating another location a few meters above - with the route's bearing taken into account. 

This is cumbersome, error prone, and not really satisfactory because the distance should actually depend on the zoom level. 

Instead, it would be great if there was an API to indicate the desired target location (either center, the current behavior, or bottom.)

**Comment by tobrun** [comment] 2017-09-21 06:46
We expose the concept of FocalPoint. This is the point were all gestures and camera interactions as zoom work around. You can provide your own FocalPoint through `UiSettings#setFocalPoint(PointF point)` and a reference to UiSettings is retrieved with `MapboxMap#getUisettings()`. Let us know if you have any issues with this setup, closing as we support this use-case through api mentioned above.

**Closed by tobrun** 2017-09-21 06:46 UTC

**Comment by palto-blubek** [comment] 2017-10-24 08:58
Sorry for the late reply - I only now had the chance to test the FocalPoint API.  I am confused because it doesn't seem to do what I thought it would.
  
I was expecting that, after setting a focal point, calling `setCameraPosition` would take it into account, and so the "target" of the camera should not be the center of the map, but the point that I have set. 
It did seem to change the 'pivot' for rotations gestures for instance.

**Comment by tobrun** [comment] 2017-10-24 14:12
You seem to be looking more for something as `MapboxMap#setPading(int left, int top, int right, int bottom)`. This allows to shift the viewport upwards. You are correct that focalpoint is only used for gesture interaction.

**Comment by palto-blubek** [comment] 2017-10-24 16:17
Thanks for your reply.  The problem is, doing that also has effects on the location of the mapbox logo, and the compass icon, right?

**Comment by tobrun** [comment] 2017-10-24 17:14
That is correct but if needed you can override those with the UiSettings class which you can reference with `MapboxMap#getUiSettings()`.

**Comment by palto-blubek** [comment] 2017-10-24 17:20
Ok thank you :) We will investigate this solution then.
