### ISSUE TITLE
Roads and Polylines not visible - SM-G350

### ISSUE THREAD

**Issue by tomlocks** [mapbox/mapbox-gl-native#6454] opened 2016-09-26 09:00 UTC
Hi,

I'm having problem on Samsung Galaxy Core Plus. The roads are not visible. Moreover this particular have problems with polylines that aren't drawing as well.

Platform: Android 4.2.2
Mapbox SDK version: 4.2.0-beta.3
1. Start Mapbox Dev Preview
2. Start simple map view.
### Expected behavior

  Visible roads.
### Actual behavior

 Roads aren't drawing.
![screenshot_2016-09-26-10-18-50 1](https://cloud.githubusercontent.com/assets/9156700/18828482/6abcd852-83d8-11e6-9200-5fbaee2c442b.png)

**Comment by ivovandongen** [comment] 2016-10-07 13:49
@tomlocks Thanks for the report. Is this issue occurring on other devices as well? And are you using a default or a custom style?

**Comment by tomlocks** [comment] 2016-10-10 07:35
I haven't seen that issue on other devices. It's deafult style shipped with Mapbox Dev Preview.

**Comment by VidMishra** [comment] 2017-02-03 05:40
I am facing the same issue with Mapbox SDK 4.2.2. However, this is not because of android OS version but the GLES version. It works fine if your device is having Open GLES version 3.0 or above but not with GLES version 2.0.

**Comment by mdakram** [comment] 2017-04-08 08:12
@tobrun Any update on this?

**Comment by jfirebaugh** [comment] 2017-07-21 00:01
Duplicate of #9164.

**Closed by jfirebaugh** 2017-07-21 00:01 UTC
Labels: Android

**Comment by KK1423** [comment] 2017-07-24 21:36
@jfirebaugh  I am having the same issue running the Qt mapbox gl plugin (cloned from the qt-staging branch) on a Raspberry Pi 3, which has the same Broadcom gpu as the Samsung devices in this thread. Applying the changes in PR #9573 to my source and rebuilding has no effect, and even you mentioned that the issue in this thread is probably different and unrelated to the Adreno 225 GPU issue with clipping. Maybe this issue should be reopened.

**Comment by jfirebaugh** [comment] 2017-07-24 21:48
@KK1423 Can you please open a new issue?

**Comment by KK1423** [comment] 2017-07-24 21:54
Okay, I'm on it.

**Comment by jfirebaugh** [comment] 2017-07-25 14:56
#7583 is now the tracking issue for line rendering on Broadcom Videocore IV.
