### ISSUE TITLE
Incorrect MyLocationView transformation

### ISSUE THREAD

**Issue by justasm** [mapbox/mapbox-gl-native#5438] opened 2016-06-22 15:46 UTC
**Platform:** Android
**Mapbox SDK version:** 4.1.0-beta.3

### Steps to trigger behavior

 1. Enable `MyBearingTracking.COMPASS` tracking mode.
 2. Tilt map around x axis (i.e. pitch) using two-finger shove gesture.
 3. Rotate map around z axis (i.e. bearing, aka direction) using two-finger rotate gesture.

### Expected behavior
![screenshot_20160622-182419](https://cloud.githubusercontent.com/assets/1081815/16272594/0215e932-38a7-11e6-96de-75254290f02a.png)

### Actual behavior
![screenshot_20160622-182544](https://cloud.githubusercontent.com/assets/1081815/16272598/0667dc84-38a7-11e6-950a-5af5fdb0d2d6.png)

### Discussion
The 3D transformation calculation for `MyLocationView` is

1. incorrect - the compass bearing / direction rotation is applied as `M' = R(degrees) * M` using [`Matrix#postRotate(float)`][mylocationview-postrotate-bearing], whereas it should be calculated as `M' = M * R(degrees)`, e.g. by using `Matrix#preRotate(float)`.
2. incomplete - map rotation around the z axis, i.e. map bearing / direction, is not taken into account. The compass bearing indicator is therefore incorrect when the map is not pointing north. Map rotation gestures should be propagated to `MyLocationView`, similar to [how tilt is][mylocationview-settilt], and accounted for when calculating the transformation.
3. needlessly complex - it uses both the `Camera` and `Matrix` classes, whereas the entire transformation could be calculated using just `Camera` and applied using `Camera#applyToCanvas(canvas)`.

[mylocationview-postrotate-bearing]: https://github.com/mapbox/mapbox-gl-native/blob/062c4ce773079fc6b408a50f64ab57c280dacdd9/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L272
[mylocationview-settilt]: https://github.com/mapbox/mapbox-gl-native/blob/062c4ce773079fc6b408a50f64ab57c280dacdd9/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L302

**Comment by tobrun** [comment] 2016-06-24 08:42
@justasm thank you for writing this up. I was able to reproduce the issue shown in the screenshot and patch it up by applying `Matrix#preRotate(float)` instead of `Matrix#postRotate(float)`. I'm now looking into your suggestions from 2) and 3).

**Comment by tobrun** [comment] 2016-06-24 08:58
Also noticing that when compass bearing is active and we don't have a tracking mode active. That the rotate gesture is disabled, while it should be enabled.

**Comment by tobrun** [comment] 2016-06-24 10:16
Noticing 2 JNI related items:
 -  `getMeterPerPixelAtLatitude` is called for each onDraw which is not good for performance.
  - I'm thinking about caching this value, a not 100% correct value will not have that much impact since the value is used for the accuracy circle.
 - The MyLocationView is sometimes stuck in an invalidation loop. Resulting in constantly invalidating through JNI. While the map is actually not changing and is stable.

**Comment by tobrun** [comment] 2016-06-24 11:09
`The MyLocationView is sometimes stuck in an invalidation loop.` 

> this occurred only when we receive a location update and were trying to animate the location update through an animator. For non-tracking behaviour we don't need to invalidate the map, we only need to invalidate the MyLocationView.

**Comment by tobrun** [comment] 2016-06-24 11:18
> I'm thinking about caching this value, a not 100% correct value will not have that much impact since the value is used for the accuracy circle.

I was wrong here because `getMetersPerPixelAtLatitude` uses current zoom level. I'm going try moving it to another place in the code than the `onDraw`.

**Comment by tobrun** [comment] 2016-06-24 12:18
I fixed the `getMetersPerPixelAtLatitude ` by calling this only when zoom levels changes. This is currently results in a jump in accuracy circle width but it's more performant now. I'm going to punt on this and revisit the whole system later on but not for the `4.1.0` release (this includes the removal of Matrix as mentioned in the OP).

**Comment by tobrun** [comment] 2016-06-24 12:28
Here you can see the less optimal UX but with improved performance since we are no longer calling a JNI method directly in onDraw.

![ezgif com-video-to-gif 41](https://cloud.githubusercontent.com/assets/2151639/16337708/c798136c-3a17-11e6-9880-dc40ee78eed0.gif)

**Comment by tobrun** [comment] 2016-06-25 07:49
Looking into this issue has resulted me going into the rabbit hole and finding/fixing multiple things. To limit impact/regressions for the release we are planning next week I'm going to patch up a few things and revisit this issue after release.

**Comment by tobrun** [comment] 2016-07-11 12:27
I'm running back at this issue, starting this off by cherry picking some ideas from #5468

**Comment by cammace** [comment] 2016-08-09 17:59
This ticket seems to be tracking multiple issues with the location view, If they haven't been fixed yet can we ticket them out separately and close this one @tobrun?

**Closed** 2016-08-16 15:22 UTC
Labels: Android
