### ISSUE TITLE
HTTP exception

### ISSUE THREAD

**Issue by peterneubauer** [mapbox/mapbox-gl-native#2979] opened 2015-11-09 11:03 UTC
I got this once:

    Fatal Exception: java.lang.NullPointerException: String cannot be null.
       at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.nativeOnFailure(HTTPContext.java)
       at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.onFailure(HTTPContext.java:92)
       at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.onResponse(HTTPContext.java:103)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by tobrun** [comment] 2015-11-13 08:14
@ljbade, @zugaldia:
Is this something that will be resolved with the `refactor for offline` or needs to investigated further?

**Comment by zugaldia** [comment] 2015-11-16 19:46
This definitely looks like something that will be addressed once https://github.com/mapbox/mapbox-gl-native/issues/2400 gets merged. Worth re-testing the code with those changes.

**Comment by ljbade** [comment] 2015-11-16 22:58
@zugaldia If I recall you found the same crash? We added a null check to JNI for that.

**Comment by zugaldia** [comment] 2015-11-17 02:44
@ljbade That's correct.

**Comment by tobrun** [comment] 2016-01-12 08:34
I was not able to reproduce this error and seeing the discussion above between @zugaldia and @ljbade. I'm calling this resolved for now. Reopen if this occurs again.

**Closed by tobrun** 2016-01-12 08:34 UTC
Labels: Android, crash

**Comment by zugaldia** [comment] 2016-01-13 16:35
Also, worth mentioning that we recently landed some better HTTP log messages to help debug these issues: https://github.com/mapbox/mapbox-gl-native/commit/d2b2336a9efc00978950cd3ee9d4d0af6ad7f1bf

**Comment by vfaSonnt** [comment] 2016-01-19 10:06
It occured after I upgrade to version 3.0.0. And it happened many time when network doesn't stable.
```
01-19 16:52:43.698 30050-30146/? D/com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest: onFailure: null
01-19 16:52:43.709 30050-30126/? E/mbgl: {Map}[Setup]: loading style failed: 
01-19 16:52:43.732 30050-30146/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                   Process: com.myapp, PID: 30050
                                                   java.lang.NullPointerException: String cannot be null.
                                                       at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.nativeOnFailure(Native Method)
                                                       at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.onFailure(HTTPContext.java:94)
                                                       at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.onResponse(HTTPContext.java:105)
                                                       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
                                                       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
```

**Comment by tobrun** [comment] 2016-01-20 12:13
@vfaSonnt thank you for reaching out and reporting your problem. 
This problem you are mentioning and the problem described here are a bit different.
We are going to test/patch/fix your problem in https://github.com/mapbox/mapbox-gl-native/issues/3465.

**Comment by vfaSonnt** [comment] 2016-02-17 10:56
@tobrun does this https://github.com/mapbox/mapbox-gl-native/issues/3692 is same with my problem?

**Comment by tobrun** [comment] 2016-02-17 15:29
@vfaSonnt: I believe it is the same

**Comment by vfaSonnt** [comment] 2016-02-18 02:58
Thank you very much.
