### ISSUE TITLE
Zooming on FillLayer and Polygon causes flickering

### ISSUE THREAD

**Issue by dsuresh-ap** [mapbox/mapbox-gl-native#11950] opened 2018-05-18 18:19 UTC
**Platform: Android**
**Mapbox SDK version:6.1.1**

### Steps to trigger behavior

 1. Create a circle (Polygon) or Polygon using a FillLayer or using `addPolygon()`
 2. Zoom in to shape and zoom out.

### Expected behavior

Shape's fill stays intact.

### Actual behavior

Shape's fill flickers and transparency flashes.
Attached recording: [Recording](https://drive.google.com/file/d/1GSfukB-_B0Z3PaHp6ifxBJek6AaH0fb_/view?usp=sharing)

**Comment by LukasPaczos** [comment] 2018-07-04 12:52
Thanks for reporting the issue, closing as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/11877.

**Closed by LukasPaczos** 2018-07-04 12:52 UTC
