### ISSUE TITLE
[iOS] crash when mapView is initialized with CGRectZero frame

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#3700] opened 2016-01-26 15:18 UTC
Initializing the map view with a zero frame crashes our test app:

2016-01-26 16:16:50.205 Mappy[346:51305] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x145e36d80> to GL_RENDERBUFFER 1
2016-01-26 16:16:50.206 Mappy[346:51305] Failed to make complete framebuffer object 8cd6
2016-01-26 16:16:50.316 Mappy[346:51305] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 23]'

**Comment by friedbunny** [comment] 2016-01-26 15:37
Dupe of #1572.

**Closed by friedbunny** 2016-01-26 15:37 UTC

**Comment by RomainQuidet** [comment] 2016-01-26 15:59
@friedbunny sorry, searched CGRectZero but did not find it ! Thanks

**Comment by friedbunny** [comment] 2016-01-26 16:38
@RomainQuidet No problem, thousands of issues are tough for us to keep track of, too — thanks for the report. 😄
