### ISSUE TITLE
Map crashes after requesting user position

### ISSUE THREAD

**Issue by Leminur** [mapbox/mapbox-gl-native#8819] opened 2017-04-25 22:59 UTC
**Platform: Android**
**Mapbox SDK version: 5.0.2**

I am having a big issue related to retrieve the user's position and use it to find a route. The crash mostly happens when the user immediately requires to find a route after they access the map. I have used the same methods from the examples given here in this repository. (Such as getRoute, drawRoute...). **I have tried 3 different cellphones and the AS's very emulator, all of them had the same error.**

### Steps to trigger behavior

 1. Access the map and immediately click on a marker
 2. Request the best route from that marker

### Expected behavior
The map should return the best route from the user's location to the very marker's position.

### Actual behavior
The app crashes as it tries to recover the user's position (`origin = Position.fromCoordinates(locationEngine.getLastLocation().getLongitude(), locationEngine.getLastLocation().getLatitude())`), 

### Error Log
```
516 28304-28304/afinal.projeto.unb.guiadoaluno E/AndroidRuntime: FATAL EXCEPTION: main
Process: afinal.projeto.unb.guiadoaluno, PID: 28304

java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLongitude()' on a null object reference

at afinal.projeto.unb.guiadoaluno.Mapa$1$2$1.onClick(Mapa.java:1667)
at android.view.View.performClick(View.java:5184)
at android.view.View$PerformClick.run(View.java:20893)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5940)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

### Code
```
  //...//
locationEngine = LocationSource.getLocationEngine(this);
        locationEngine.activate();
		
        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                map = mapboxMap;

                //.. //

                mapboxMap.setInfoWindowAdapter(new MapboxMap.InfoWindowAdapter() {
                    @Nullable
                    @Override
                    public View getInfoWindow(@NonNull Marker marker) {

                       // ... //
                        if (!marker.getTitle().equals("Origem") && !marker.getTitle().equals("Destino")) {
                            
                            botaoIr = (Button) v.findViewById(R.id.botaoIr);
                            botaoIr.setOnClickListener(new View.OnClickListener() {
                                
                                @Override
                                public void onClick(View view) {
                                    LocationManager manager = (LocationManager) getSystemService(Context.LOCATION_SERVICE);

                                    if (manager.isProviderEnabled(LocationManager.GPS_PROVIDER)) {

                                        if (map != null) {
                                            toggleGps(!map.isMyLocationEnabled());
                                        }

                                        LatLng ponto = marcador.getPosition();
                                        destination = Position.fromCoordinates(ponto.getLongitude(), ponto.getLatitude());

                                        if (ActivityCompat.checkSelfPermission(Mapa.this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(Mapa.this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
                                            ActivityCompat.requestPermissions(Mapa.this, new String[]{
                                                    Manifest.permission.ACCESS_COARSE_LOCATION,
                                                    Manifest.permission.ACCESS_FINE_LOCATION}, PERMISSIONS_LOCATION);
                                        }

                                        origin = Position.fromCoordinates(locationEngine.getLastLocation().getLongitude(), locationEngine.getLastLocation().getLatitude());

                                        origem = new MarkerOptions()
                                            .position(new LatLng(origin.getLatitude(), origin.getLongitude()))
                                            .title("Origem")
                                            .icon(iconeRota);

                                        destino = new MarkerOptions()
                                            .position(new LatLng(destination.getLatitude(), destination.getLongitude()))
                                            .title("Destino")
                                            .icon(iconeRota);

                                        try {
                                            getRoute(origin, destination);
                                            } catch (ServicesException servicesException) {
                                            servicesException.printStackTrace();
                                        }

                                    }
                                }
                            });
			//...//
                        }
                        return v;
                    }
                });
        });
    }
```

**Comment by tobrun** [comment] 2017-04-26 07:53
You are hitting an null pointer exception because `getLastLocation` returns a null location. You need to add a null check as the location provider isn't connected yet. What you need to do is wait for the onConnected callback and than you will be able to get the last known location. Closing as works as designed (due to using LOST as default location provider), let us know if you have any other questions.

**Closed by tobrun** 2017-04-26 07:53 UTC

**Comment by Leminur** [comment] 2017-04-26 20:29
@tobrun I have checked if the last location is null. ( locationEngine.getLastLocation() != null ), it seems to work on the first time, but then it crashes if the error happens on the second time. I have found the callback (locationEngineListener.onConnected()) but I am not sure how I can wait for such thing, as it is a void function. Do you have any examples or anything else that can help me with that? Thanks for the enlightenment!
