### ISSUE TITLE
MGLPointAnnotations with subtitle are not shown well on v3.7.1 

### ISSUE THREAD

**Issue by derjohng** [mapbox/mapbox-gl-native#10745] opened 2017-12-19 09:19 UTC
**Platform:iOS
**Mapbox SDK version:3.7.1

### Steps to trigger behavior

As attach file, v3.7.1 SDK will not show annotations (MGLPointAnnotations) properly. 
I roll back to v3.6.4 with the same code, and it works well.

<img width="982" alt="1219_001" src="https://user-images.githubusercontent.com/1803036/34149457-1f34ae22-e4e0-11e7-960b-078fa17c1e72.png">

**Comment by fabian-guerra** [comment] 2017-12-19 17:34
Hi, @derjohng. Thank you for using Mapbox. I am sorry to hear you are having some issues.

I used our test app to look at the issue you described. I am not able to reproduce the problem you are having.

Could you please add a code snipet or test app we could use to track the problem?

This is showing both title/subtitle. I am using `Mapbox Maps SDK for iOS v3.7.0`

![annotations](https://user-images.githubusercontent.com/2745166/34170384-4328cb18-e4b0-11e7-8724-29cfa8b09c57.png)

**Comment by derjohng** [comment] 2017-12-20 05:09
Hi, @fabian-guerra 
Today, I found the "1 or 2" annotations are the title of MGLPolylines. In old version (v3.6.4), the text of line will not be popup. So, I use that for attribute note. In v3.7.1, click the line, the title will be shown.

This is a new feature? Can I disable showing title of the MGLPolyline?

**Comment by fabian-guerra** [comment] 2017-12-20 16:20
Hi, @derjohng. 

Starting in https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.7.0 
> Added support selection of shape and polyline annotations.(#9984)

For `MGLPolyline` annotations remove the `title` and `subtitle` that will avoid showing the callout view.

I am going to close this issue due to is the intended behavior and is not a bug.

**Closed by fabian-guerra** 2017-12-20 16:20 UTC
Labels: annotations, iOS, needs information
