### ISSUE TITLE
[iOS] build fails with Xcode 8.1

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#6942] opened 2016-11-07 14:33 UTC
**Platform:*iOS*
**Mapbox SDK version: master branch**

### Steps to trigger behavior

 1. Compile SDK with command line make ipackage
 2. Or compile static or dynamic SDK with Xcode project after a make iproj

### Expected behavior
Compilation is ok

### Actual behavior
job fails with error on Settings.bundle:

CodeSign /Users/mappy/Documents/mapbox-gl-native/build/ios/Debug-iphonesimulator/Settings.bundle
    cd /Users/mappy/Documents/mapbox-gl-native/platform/ios
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/mappy/Documents/mapbox-gl-native/build/ios/Debug-iphonesimulator/Settings.bundle

/Users/mappy/Documents/mapbox-gl-native/build/ios/Debug-iphonesimulator/Settings.bundle: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1

**Comment by RomainQuidet** [comment] 2016-11-07 14:45
This happens only when the target device is iPhoneSimulator. The build on Xcode project succeed when set to iOS Generic Device

**Comment by RomainQuidet** [comment] 2016-11-08 15:43
according to this thread, a missing ressource or info.plist makes Xcode 8.1 failing building the bundle.
https://forums.developer.apple.com/thread/66538

**Comment by boundsj** [comment] 2016-11-08 15:54
This looks like a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/6947 that was fixed by https://github.com/mapbox/mapbox-gl-native/pull/6948. @RomainQuidet. Can you please test again with https://github.com/mapbox/mapbox-gl-native/pull/6948/commits/642ef0f76120b4a53bdf26df9146f7fee46c7f2c?

**Comment by RomainQuidet** [comment] 2016-11-09 09:21
You're right, it's the missing plist that makes Xcode 8.1 failing building mapbox

**Comment by frederoni** [comment] 2016-11-09 09:31
Fixed by #6948

**Closed by frederoni** 2016-11-09 09:31 UTC
Labels: iOS
