### ISSUE TITLE
Bug with MGLAnnotationView when constraining a subview to center and enabling `scalesWithDistance`

### ISSUE THREAD

**Issue by ollie-eman** [mapbox/mapbox-gl-native#5802] opened 2016-07-26 13:08 UTC
**Platform: iOS**
**Mapbox SDK version: 3.3.0**

I've created a custom annotation, a subclass of `MGLAnnotationView` to add to the map. Within the marker, I've added a `UIImageView` and added two constraints. One constraint for the image view's `centreX` attribute and another for the `centerY` attribute. Both of these are set as equal to the `self` - [the annotation].

With `scalesWithDistance` set to `true`, as per the default, when the viewing angle changes and the annotation scales the image view does not maintain it's position at the centre of the annotation view. 

At 0 degrees viewing angle, the image view is in the centre of the annotation.
![screen shot 2016-07-26 at 2 05 20 pm](https://cloud.githubusercontent.com/assets/20243749/17138856/1dc3e3e8-533a-11e6-9b48-d16256119e02.png)

As the viewing angle changes the image view constrained to centre moves further to the top left corner of the annotation view.
![screen shot 2016-07-26 at 2 05 45 pm](https://cloud.githubusercontent.com/assets/20243749/17138857/2148d244-533a-11e6-91d8-a190bda319bf.png)

At the highest viewing distance, the image view has moved quite significantly.
![screen shot 2016-07-26 at 2 05 56 pm](https://cloud.githubusercontent.com/assets/20243749/17138860/23ff7d94-533a-11e6-9bc9-5d80ac76a587.png)

### Code

The constraints are added within `layoutSubviews`
```
markerImageView.translatesAutoresizingMaskIntoConstraints = false
        
var centerX, centerY: NSLayoutConstraint
        
// marker image view
centerX = NSLayoutConstraint(item: markerImageView, attribute: .CenterX, relatedBy: .Equal, toItem: self, attribute: .CenterX, multiplier: 1.0, constant: 0)
centerY = NSLayoutConstraint(item: markerImageView, attribute: .CenterY, relatedBy: .Equal, toItem: self, attribute: .CenterY, multiplier: 1.0, constant: -20)
        
addConstraints([centerX, centerY])
```

The grey circle is being drawn using `CGContextAddEllipseInRect` within the `drawRect` function.
```
graphicsContext = UIGraphicsGetCurrentContext()
        
CGContextAddEllipseInRect(graphicsContext, rect)
        
CGContextSetFillColor(graphicsContext, CGColorGetComponents(UIColor.LightGreyColor(alpha: 0.5).CGColor))
CGContextFillPath(graphicsContext)
```

**Comment by 1ec5** [comment] 2016-07-26 17:46
Interesting, the constraints are unaffected by the 3D rotation transform we apply to the Core Animation layer. Any ideas @boundsj @frederoni?

**Comment by boundsj** [comment] 2016-07-27 23:25
Hi @ollie-eman. To achieve the scales with distance effect, the MGLAnnotationView base class performs a 3D scale transformation directly on the layer. Unfortunately, I think this will make using constraints to lay out application annotation views challenging if `scalesWithViewingDistance` is used. Here are some workarounds that I found:

### Option A: Override `layoutSubviews` to adjust the result of Auto Layout

As noted in [this objc.io post](https://www.objc.io/issues/3-views/advanced-auto-layout-toolbox/#animation), you can add some logic in `layoutSubviews` to opt out of or adjust Auto Layout behavior. For example, you could add this after your constraints are set:

##### Objective-C
```objective-c
static CGPoint center = {0,0};
if (CGPointEqualToPoint(center, CGPointZero)) {
    // grab the center view's center point after initial layout
    center = self. markerImageView.center;
} else {
    // apply the previous center to the vie
    self.markerImageView.center = center;
}
```
##### Swift
```swift

static var center = CGPoint(x:0, y: 0)

...

if CGPointEqualToPoint(AppAnnotationView.center, CGPointZero) {
    // grab the center view's center point after initial layout
    AppAnnotationView.center = self.markerImageView!.center;
} else {
    // apply the previous center to the view
    self.markerImageView!.center = AppAnnotationView.center;
}
```

This allowed me to successfully center a view (using Auto Layout) in the middle of an annotation view in a project where I reproduced the issue you described.

### Option B: Don't use Auto Layout

If you create a subview with a frame and center it in the containing annotation view it should work as expected.

### Option C: Disable `scalesWithViewingDistance`

If you turn off the `scalesWithViewingDistance` feature on your annotation view subclass, it avoids hitting the code path that applies the transform.

**Comment by boundsj** [comment] 2016-07-28 17:27
Closing since I think this is a limitation of UIKit that we must workaround using one of the above options.

**Closed by boundsj** 2016-07-28 17:27 UTC
Labels: annotations, iOS

**Comment by ollie-eman** [comment] 2016-07-28 17:30
Ok thanks for your help!

I ended up just turning off `scalesWithViewingDistance` and manually scaling. This enabled me to reset the image view's centre for each scaling operation.
