### ISSUE TITLE
Map becomes very laggy when navigate to the some areas in the world and try to zoom in/out

### ISSUE THREAD

**Issue by zikil** [mapbox/mapbox-gl-native#4652] opened 2016-04-08 13:13 UTC
**Platform: Android**
**Mapbox SDK version: 4.0.0**

### Steps to trigger behavior

If you navigate, for example, to the Netherlands and try to zoom in or our you will notice huge stuttering, for areas that do not have many details map works good. 
Video : https://www.dropbox.com/s/62oc4yk1r0w2ulc/device-2016-04-08-160809.mp4?dl=0

**Comment by tobrun** [comment] 2016-04-08 13:16
@zikil thank you for reaching out.
I tried opening your video but I'm seeing this error:
![screen shot 2016-04-08 at 15 14 47](https://cloud.githubusercontent.com/assets/2151639/14384695/b4930194-fd9c-11e5-88e4-0a5369d1927a.png)
Could you double check?

Thanks you for reporting this.

**Comment by zikil** [comment] 2016-04-08 13:19
@tobrun Oops, sorry. I updated link.

**Comment by Matthiasvt** [comment] 2016-05-10 10:25
Hi, I'm the PM of the project where @zikil is working on. 

It is a really annoying bug and we can't go into production with the bug still in it. I tried panning a lot in different parts of the world and it seems that the issue is mostly in zoomlevel 11 -> 5. 

It only happens in Europe, I've attached a video that shows the difference (http://sendvid.com/g3lozrvi).
As soon as I cross the Mediterranean Sea from Spain to Marroco everything is smooth.

I was wondering what we can do to make this stable for now so we can submit our Android app to production. It is waiting solely on this issue..

Have you already planned this issue / when do you think it will be solved? Or are we the only one with this issue?

**Comment by tobrun** [comment] 2016-05-10 11:12
@Matthiasvt 

More information about this issue, including a [workaround](https://github.com/mapbox/mapbox-gl-native/issues/4777#issuecomment-212986709), can be found in #4777. I can't give you an eta on the fix but we have 👀  on it. Would you be able to try out the workaround for now? 

Reach out if you have any other questions. Going the close this in favour of #4777.

**Closed by tobrun** 2016-05-10 11:12 UTC
Labels: Android, performance
