### ISSUE TITLE
Unclear Projection

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#8395] opened 2017-03-14 16:48 UTC
I am reading the following function in Mapbox:

```
// mapbox-gl-native/include/mbgl/util/projection.hpp
// ...
    static Point<double> project(const LatLng& latLng, double scale) {
        return Point<double> {
            util::LONGITUDE_MAX + latLng.longitude,
            util::LONGITUDE_MAX - util::RAD2DEG * std::log(std::tan(M_PI / 4 + latLng.latitude * M_PI / util::DEGREES_MAX))
        } * worldSize(scale) / util::DEGREES_MAX;
    }

```
I'm comparing this to the [Wolfram Mercator Projection](http://mathworld.wolfram.com/MercatorProjection.html)

I'm confused regarding this function. From what I can tell, it intends to create a mathematical mapping between a sphere and cartesian coordinates on a x-y plane. However, if this is true, then the following are unclear so far:

- Why convert the results from the ln (aka std::log) from radians to degrees? Wolfram shows the result should be plane units in the y dimension and not in radians to begin with. 

- Why subtract the resulting conversion from RAD2DEG from the maximum longitude? Wolfram shows the y values are only a function of the latitude and are NOT a function of longitude. Therefore it is unclear why the LONGITUDE_MAX should impact the y value result. 

There's a number of other confusing points but those may become clear if these are cleared.

**Comment by jfirebaugh** [comment] 2017-03-15 18:05
> Why convert the results from the ln (aka std::log) from radians to degrees? Wolfram shows the result should be plane units in the y dimension and not in radians to begin with.

The input is in degrees latitude, but it's converted to radians so that we can use standard `tan`, whose input is radians. It appears that Wolfram is assuming trigonometric functions that accept degrees.

> Why subtract the resulting conversion from RAD2DEG from the maximum longitude?

I believe it's a (confusing) use of `LONGITUDE_MAX` for its literal value of 180, rather than its semantic meaning. The purpose of the value 180 is not immediately clear to me however. Maybe another contributor knows.

I'm going to close this issue in the meantime, since it's not a bug report or feature request.

**Closed by jfirebaugh** 2017-03-15 18:05 UTC

**Comment by labermt** [comment] 2017-03-16 15:20
Hi @jfirebaugh, 

I think you misread the question. In the expression:

util::RAD2DEG * std::log(std::tan(M_PI / 4 + latLng.latitude * M_PI / util::DEGREES_MAX))

I'm referring to the "util::RAD2DEG" multiplication that is done on the result from std::log(). I am NOT referring to the input to std::tan(), which is being converted from degrees to radians through the multiplication by M_PI and divided by util:DEGREES_MAX. The result of the std::log() function is in y cartesian units and is not an angular measure, so why convert a linear value from radians to degrees when it isn't in radians (or any other angular measure) to begin with?

Hope that clarifies the question.

Meta-question. When I ask questions here, they are closed because they are not "bugs", but I'm encouraged to ask them here when I ask them elsewhere. A little clarity on the Q&A would be helpful. 

Thanks.
