### ISSUE TITLE
Missing token when calling Mapbox#getInstance after the layout inflation

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#13253] opened 2018-11-01 11:21 UTC
Refs https://github.com/mapbox/mapbox-gl-native/pull/13133.

If we are calling `Mapbox#getInstance` and passing the access token after the `MapView` inflation, we are going to run into a below crash, because the access token is not yet available during the renderer instantation, which now happens immediately on the layout inflation.

To fix the issue, we'd have to call `Mapbox#getInstance` before the layout inflation:
```
@Override
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  Mapbox.getInstance(this, token);
  setContentView(R.layout.activity_map_simple);

  mapView = (MapView) findViewById(R.id.mapView);
  mapView.onCreate(savedInstanceState);
}
```

instead of the previously valid approach of calling it before `MapView#onCreate`:
```
@Override
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  setContentView(R.layout.activity_map_simple);

  Mapbox.getInstance(this, token);

  mapView = (MapView) findViewById(R.id.mapView);
  mapView.onCreate(savedInstanceState);
}
```

The stack-trace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxsdk.testapp/com.mapbox.mapboxsdk.testapp.activity.maplayout.SimpleMapActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.mapbox.mapboxsdk.maps.MapView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
    at android.app.ActivityThread.access$800(ActivityThread.java:156)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5389)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
 Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.mapbox.mapboxsdk.maps.MapView
    at android.view.LayoutInflater.createView(LayoutInflater.java:633)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
    at com.mapbox.mapboxsdk.testapp.activity.maplayout.SimpleMapActivity.onCreate(SimpleMapActivity.java:21)
    at android.app.Activity.performCreate(Activity.java:5990)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442) 
    at android.app.ActivityThread.access$800(ActivityThread.java:156) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:211) 
    at android.app.ActivityThread.main(ActivityThread.java:5389) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
 Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
    at android.view.LayoutInflater.createView(LayoutInflater.java:607)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
    at com.mapbox.mapboxsdk.testapp.activity.maplayout.SimpleMapActivity.onCreate(SimpleMapActivity.java:21) 
    at android.app.Activity.performCreate(Activity.java:5990) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442) 
    at android.app.ActivityThread.access$800(ActivityThread.java:156) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:211) 
    at android.app.ActivityThread.main(ActivityThread.java:5389) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
 Caused by: com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException: 
Using MapView requires calling Mapbox.getInstance(Context context, String accessToken) before inflating or creating the view. The access token parameter is required when using a Mapbox service.
Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
    at com.mapbox.mapboxsdk.Mapbox.validateMapbox(Mapbox.java:164)
    at com.mapbox.mapboxsdk.Mapbox.getAccessToken(Mapbox.java:77)
    at com.mapbox.mapboxsdk.storage.FileSource.<init>(FileSource.java:231)
    at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:66)
    at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.<init>(MapRenderer.java:29)
    at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>(GLSurfaceViewMapRenderer.java:27)
    at com.mapbox.mapboxsdk.maps.MapView$5.<init>(MapView.java:293)
    at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:293)
    at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:134)
    at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:97)
    	... 24 more
```

**Comment by tobrun** [comment] 2018-11-01 11:49
That is a works as designed, the error message shows: `Using MapView requires calling Mapbox.getInstance(Context context, String accessToken) before inflating or creating the view.`. That this worked before was more a side effect of the async behaviour. Closing as not actionable, feel free to reopen if you feel this needs to be reconsidered.

**Closed by tobrun** 2018-11-01 11:49 UTC
Labels: Android, release blocker

**Comment by LukasPaczos** [comment] 2018-11-01 12:22
This is correct @tobrun. As this change might impact a large user base, even thought it's working as designed, I was looking for a way to force that change in the upcoming `7.0.0` instead of now by tweaking the initialization process, but couldn't find one that wouldn't significantly impact the current flow.

**Comment by geohacker** [comment] 2019-08-01 13:04
@tobrun @LukasPaczos We may be running into something like this while using [react-native-mapbox-gl](https://github.com/react-native-mapbox-gl/maps). 

We see this `accessToken is required` error when overriding the `OkHttpClient`. We're doing this because we need to store some cookies for authenticating tile requests. See code https://github.com/developmentseed/observe/blob/cc682e840abda9ea240698d709454c6d710ccd92/android/app/src/main/java/com/developmentseed/observe/MainActivity.java#L95

Do you perhaps have some recommendation or thoughts on what might be going wrong? Or suggestions what we should do to try and debug?

**Comment by tobrun** [comment] 2019-08-01 13:31
Hey @geohacker, great seeing you here! From current master, I'm not seeing how such a configuration should result in that error logging. My best guess is that the react-native package calling into Mapbox.java. I'm not really familiar with the react native setup. As workaround you can call into `Mapbox.getInstance(context, accesstoken)` before calling into the configuration. Let me know if you have any follow up questions!

**Comment by geohacker** [comment] 2019-08-01 13:49
@tobrun So great to hear from you! I'm not entirely sure what I should do here because this is all very new to me :) 

So I don't know when react-native is calling the configuration, but are you suggesting that we call Mapbox.getInstance before setting the http client? I'm currently also trying to reproduce this with the react-native example so I can also open a ticket there. Thank you so much for helping! 🙇
