### ISSUE TITLE
[android] new camera move listeners fire in wrong order

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#9177] opened 2017-06-02 12:45 UTC
**Platform:** Android
**Mapbox SDK version:** v5.1.0-beta.3

### Steps to trigger behavior

Move camera programmatically for ex.:
```
map.easeCamera(CameraUpdateFactory.newLatLng(new LatLng(location)), 0, false, null, true);
```
### Expected behavior
Callbacks are called in order: `onCameraMoveStarted() -> onCameraMove() -> onCameraIdle()`

### Actual behavior
Camera movement finishes with `onCameraMoveStarted()` or `onCameraMove()`, or fires infinitely with `onCameraMove()` callback sometimes mixed up with `onCameraMoveCanceled()`, or any other combination. It looks really inconsistent.

**Comment by tobrun** [comment] 2017-06-06 06:01
It seems that a `OnCameraMoveStarted` is called as a result of idle, this seems the source of the misplaced `OnCameraMoveCanceled`.

**Comment by tobrun** [comment] 2017-06-06 06:12
the OnCameraMoveStarted call was placed above the following codeblock:

```java
      if (velocityXY < MapboxConstants.VELOCITY_THRESHOLD_IGNORE_FLING) {
        // ignore short flings, these can occur when other gestures just have finished executing
        return false;
      }
```

While it only should be invoked when the fling isn't ignored.

**Comment by tobrun** [comment] 2017-06-06 06:23
Related to the OP with ease/animate camera. I'm only seeing expected behaviour:
 - started
 - multiple moves
 - idle

or

- started
- multiple moves
- cancel
- idle

**Comment by LukasPaczos** [comment] 2017-06-06 06:40
When camera is in an idle state and I use this code:
```
map.easeCamera(CameraUpdateFactory.newLatLng(new LatLng(39.489309, -0.360415)), 1000, true, null, true);
```

I'm getting such callbacks:
```
08:30:50.897 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - started
08:30:50.948 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:50.989 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.023 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.056 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.090 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.123 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.150 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.190 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.222 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.255 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.289 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.324 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.357 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.377 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.401 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.425 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.453 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.474 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.501 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.525 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.552 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.577 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.609 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.648 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.681 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.714 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.746 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.772 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.798 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.821 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.842 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.867 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.897 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
08:30:51.925 7746-7746/com.mapbox.mapboxandroiddemo.debug D/Map: camera - move
```

There is no call to `onCameraIdle()`. I'm able to reproduce it every time.

Callbacks being finished with `onCameraMoveStarted()` is resolved by #9192 :)

**Comment by tobrun** [comment] 2017-06-06 07:11
Thanks for adding the specific easeCamera definition, will try reproducing for #9192.

**Comment by LukasPaczos** [comment] 2017-06-06 07:12
When setting `TRACKING_FOLLOW` callbacks seemed to be infinite because when we are changing tracking mode to `TRACKING_FOLLOW` camera is beaing eased to current position and animation duration is being calculated like this `animationDuration = (int) ((locationUpdateTimestamp - previousUpdateTimeStamp) * 1.1f)` **but** `previousUpdateTimeStamp` and `locationUpdateTimestamp` are not being cleared when selecting `TRACKING_FOLLOW` again, therefore `animationDuration` is made extremely long which looked like infinite.

**Comment by tobrun** [comment] 2017-06-06 07:26
re. 

```map.easeCamera(CameraUpdateFactory.newLatLng(new LatLng(39.489309, -0.360415)), 1000, true, null, true);```

The source of this seems to be providing a null callback. Fixing up code to conform to this.

**Comment by tobrun** [comment] 2017-06-06 10:24
Both #9194 and #9192 were merged to the release branch. Closing.

**Closed by tobrun** 2017-06-06 10:24 UTC
Labels: Android

**Comment by Hassan-Fa** [comment] 2018-10-10 14:49
> i'm having the same issue 

with SDK 6.0.0-alpha.2 & 6.4.0 & 6.5.0 


`E/MapChangeListenerLogTAG:  MoveStarted && int : 3
E/MapChangeListenerLogTAG:    Move
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:    Move
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle
E/MapChangeListenerLogTAG:   MoveStarted && int : 1
E/MapChangeListenerLogTAG:   MoveCanceled 
E/MapChangeListenerLogTAG:   idle`

**Comment by LukasPaczos** [comment] 2018-10-11 08:46
Hey @Hassan-Fa, I've tested current implementation and I'm unable to reproduce a scenario when `canceled` isn't followed by `idle`, which I undestand is the issue. Could you provide a reproducible example (I'm aware this might be hard) or do some debugging on your side, especially the logic in the [`CameraChangeDispatcher`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java#L226-L246)?
