### ISSUE TITLE
[Android-iOS consistency] Zoom level vs ZoomLevel & Altitude mix

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#11676] opened 2018-04-13 07:37 UTC
Hi there,

I found some issue opened requesting a public api to convert Altitude to ZoomLevel and ZoomLevel to Altitude.

I know that's possible and already wrote the code myself to work with iOS but, for consistency between iOS and Android and to make developer's life easier both should have the same behaviour and value in Camera object.

Android never talk about altitude and works only with zoom level when iOS use both depends on something that I don't understand :)

There is some reason for this ?

There is some project on your side about this ?

Etienne

**Comment by 1ec5** [comment] 2018-06-21 20:43
> I found some issue opened requesting a public api to convert Altitude to ZoomLevel and ZoomLevel to Altitude.

Yes, #5583 would add that API to the iOS and macOS map SDKs.

> Android never talk about altitude and works only with zoom level when iOS use both depends on something that I don't understand :)

One of our design goals on iOS and macOS is to adhere to Cocoa conventions, often using MapKit as an example of how Cocoa conventions apply to maps. MapKit’s API is 100% about altitudes and as opposed to zoom levels, but we use a hybrid approach to better accommodate developers used to the Google Maps SDK, GL JS, or our Android map SDK.

Whether altitudes or zoom levels are better when working with a 3D map depends on your use case. Zoom levels are tied to tiles, but on a 3D map, tiles are different sizes as you look closer or farther from the camera. Increasing the zoom level doesn’t move the camera closer to the ground in a straightforward way; instead, it moves the camera closer to the focal point. If you want to move the camera closer to the ground, then altitude is the better option to adjust. MGLMapCamera has two initializers that let you express the camera in terms of a) which way the viewer is looking or b) what the viewer is looking at.

On the other hand, if you need to move the camera to a particular zoom level because that’s the zoom level at which your style changes in appearance, then zoom levels are more relevant to you. #5583 would make it easier to work with either, depending on your needs.

Instead of closing this issue as a duplicate of #5583, I’m leaving this issue open in case the Android team would be interested in adding altitude as an alternative to zoom level when working with cameras.

/cc @tobrun

**Closed** 2019-06-02 03:51 UTC
Labels: Android, archived
