### ISSUE TITLE
MapboxMap.removeAnnotations() doesn't remove markers

### ISSUE THREAD

**Issue by vfaSonnt** [mapbox/mapbox-gl-native#4553] opened 2016-03-31 07:56 UTC
I just upgrade to 4.0.0 and this bug happen.
Method removeAnnotations() doesn't work anymore. 
But removeMarker(Marker) still work.
I check on both android OS under 5.0 and above 5.0.
Both my project and Mapbox Example Source.

**Comment by tobrun** [comment] 2016-03-31 08:33
@vfaSonnt thank you for brining this to our attention.
I was able to reproduce this initial screen:
![device-2016-03-31-102921](https://cloud.githubusercontent.com/assets/2151639/14170021/88d8a17a-f72b-11e5-865a-fd21c17857c8.png)

`mapboxMap.removeAnnotations` is being called when I press the garbage bin in the options menu:

![device-2016-03-31-102946](https://cloud.githubusercontent.com/assets/2151639/14170043/a45cdd4e-f72b-11e5-85da-baffe15e078d.png)

Not all the markers were removed but some are. I'm guessing that the ids passed to core are not correct.

**Comment by tobrun** [comment] 2016-03-31 08:47
When adding marker, I'm seeing these ids:

```java
03-31 10:39:03.683 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: marker added with 6
03-31 10:39:06.421 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: marker added with 10
03-31 10:39:09.271 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: marker added with 11
```

When I inspect the first added marker with id `6`, I'm seeing it has a value of `9`.
When removing I'm seeing the following ids passed to core:

```
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 0
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 1
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 2
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 3
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 4
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 5
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 6
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 10
03-31 10:39:21.524 15756-15756/com.mapbox.mapboxsdk.testapp V/TAG: 11
```

This is a regression from the fix in https://github.com/mapbox/mapbox-gl-native/issues/4393.
Here you can see the issue in action, you should be able to see that the marker is multiple times added / removed because `DID_FINISH_RENDERING_MAP_FULLY_RENDERED` is called multiple times.

**Comment by tobrun** [comment] 2016-03-31 08:51
I found a fix for this by ensuring it's only called once without changing the event type

**Comment by vfaSonnt** [comment] 2016-03-31 09:20
Thank you very much! I checked, it is OK. Now I am waiting for next release. =)

**Closed** 2016-04-02 07:36 UTC
Labels: Android, bug
