### ISSUE TITLE
Android - Marker icons not respecting anchor values

### ISSUE THREAD

**Issue by chewbyte** [mapbox/mapbox-gl-native#5634] opened 2016-07-10 23:45 UTC
There seems to be an issue in the code for anchoring icons for markers. The icon will appear aligned at the top left of the icon, and will not respect anchor values set by `MarkerViewOptions.anchor`. Furthermore this is without even specifying custom marker icons, even the default marker suffers from the same problem, and this problem also appears in the MapBox Dev Preview app. The issue was raised [here](https://github.com/mapbox/mapbox-android-demo/issues/107) 2 days ago.

**Platform: Android**
**Mapbox SDK version: 4.1.0**

### Steps to trigger behavior

Set up a simple on click or on long press listener to add a marker in the position the map was clicked.

```
mapboxMap.setOnMapLongClickListener(new MapboxMap.OnMapLongClickListener(){

    @Override
    public void onMapLongClick(@NonNull LatLng point) {

        Marker marker = mapboxMap.addMarker(new MarkerViewOptions()
            .position(point)
            .title("Marker")
            .snippet("A marker!")
        );
    }
});
```

Then click anywhere and observe the location of the resultant marker icon.

### Expected behavior

The marker icon appears anchored at the location specified by the anchor.

### Actual behavior

The icon anchors via the top left of the icon regardless of the anchor configuration.

In the case of the image below, notice how the tree icon was clicked, but the marker icon anchors incorrectly.

![screenshot_20160711-003835](https://cloud.githubusercontent.com/assets/6507738/16716863/a279762a-4700-11e6-8c51-55c21509d832.png)

**Comment by cammace** [comment] 2016-07-11 00:37
Thanks @chewbyte for the feedback, I believe the issue you are describing was actually fixed in https://github.com/mapbox/mapbox-gl-native/issues/5513. Id like to recommend trying out the SNAPSHOT and seeing if the issue still presist. Heres how you [add it in your gradle file](https://www.mapbox.com/android-sdk/#gradle). The issue in the Mapbox Demo App is related to using the default marker which includes padding below the icon (due to it still being used for GL markers as well). Hope this helps!

**Closed by cammace** 2016-07-11 00:37 UTC

**Comment by chewbyte** [comment] 2016-07-11 03:14
Thanks @cammace. The anchor bug seems to be fixed, but I'm getting a few new issues now such as new markers not appearing until the map is zoomed or dragged.

**Comment by cammace** [comment] 2016-07-11 03:34
The SNAPSHOT, built typically every night from the master (sometimes release) branch, are the cutting edge of what we are working on for next release. The builds aren't nearly as tested as the stable SDK builds and will sometime have bugs like the one you mentioned above. The good news is that since the SNAPSHOTS built nightly, the bugs are cleared up much quicker.

**Comment by chewbyte** [comment] 2016-07-11 03:35
Excellent, thank you.

**Comment by yperess** [comment] 2016-12-10 18:40
I'm running 4.1.1 and this appears to still be an issue. I have 2 markers, one flat as a base @ (0.5, 0.5), one as a billboard @ (0.5, 1.0) and they both appear @ (0.5, 0.5), even setting one at 0, 0 and the other at 1,1 doesn't show anything different. Running on Nexus 5x Android 7.1

**Comment by cammace** [comment] 2016-12-10 23:59
@yperess try using the SNAPSHOT version of our SDK which shouldn't have this issue.

**Comment by yperess** [comment] 2016-12-11 01:33
@cammace I tried it just now and got an inflation error:

    Caused by: java.lang.NoSuchFieldError: No field textureView of type I in class Lcom/mapbox/mapboxsdk/R$id; or its superclasses (declaration of 'com.mapbox.mapboxsdk.R$id' appears in /data/app/com.app.test-1/base.apk)
                                                                          at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:199)
                                                                          at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:170)
