### ISSUE TITLE
The annotations cannot tap when maptiles is not loaded in Offline.

### ISSUE THREAD

**Issue by noramimiyuma** [mapbox/mapbox-gl-native#10586] opened 2017-11-29 00:36 UTC
**Platform:**
iPhone7 - iOS 11.1.1

**Mapbox SDK version:**
3.7.0

### Steps to trigger behavior

 1. trigger to Offline (ex. air plane mode)
 2. Launch app and load a view (that is MGLMapView or subclass of MGLMapView).
 3. Map tiles are never loaded and the annotations stands up on blank view.

### Expected behavior
We can tap an annotation standing on a blank view. 
(The annotations user Interaction still enable.)

### Actual behavior
I do not react even if I tap the annotations.

![img_5850_r](https://user-images.githubusercontent.com/15150828/33357856-53768a3a-d508-11e7-99c7-70048cbce91e.png)

**Comment by fabian-guerra** [comment] 2017-11-29 13:09
Hi, @noramimiyuma. Thank you for using Mapbox. I am sorry to hear you are having some issues. 
> trigger to Offline (ex. air plane mode)

Do you mean you previously downloaded a `MGLTilePyramidOfflineRegion`? 

You can take a look of how offline regions work at https://www.mapbox.com/ios-sdk/examples/offline-pack/

**Comment by noramimiyuma** [comment] 2017-11-29 13:22
Thank you for replying, @fabian-guerra !

I'm sorry I did not explain it clearly enough.

> Do you mean you previously downloaded a MGLTilePyramidOfflineRegion?

No, we assume that MGLMapView is used online on this screen (we do not use offline pack here).

However, we also need to assume that it will be used offline.
The problem is that user can not tap the annotation at that time.

**Comment by fabian-guerra** [comment] 2017-11-29 20:27
Hi, @noramimiyuma. Thank you for adding more context. The map will not render any annotations. This is the intended behavior if you have not downloaded the map's style.

I am closing this issue.

**Closed by fabian-guerra** 2017-11-29 20:27 UTC
Labels: iOS
