### ISSUE TITLE
[android] After scrolling maps lost interactive 

### ISSUE THREAD

**Issue by vacxe** [mapbox/mapbox-gl-native#9389] opened 2017-06-29 05:18 UTC
Case: Open map -> Just fast scroll map -> Interactive will be lost
Video: https://drive.google.com/open?id=0B8Sury_PDS4canRUbC1DazdYU1E

Android version: 7.0
Phone: Samsung SM-G925F
Mapbox ver: build master from git (28.06) -> Actual version 5.0.2

@tobrun u can help with this problem? (include fix in 5.1.0)

**Comment by tobrun** [comment] 2017-06-29 06:33
Haven't been able to reproduce on all the devices I have locally, seems a lot like #https://github.com/mapbox/mapbox-gl-native/issues/8728. Since you are building from source could u help logging/debugging this? Are methods in MapGestureDetector still reached at that point?

**Comment by vacxe** [comment] 2017-06-30 06:28
@tobrun I traced event till nativeMoveBy() and all works fine. "dx dy" is correct. But native map not move.

**Comment by vacxe** [comment] 2017-06-30 07:03
If i will just move map - all work fine. But if i want zooming i losing interactivity

**Comment by tobrun** [comment] 2017-06-30 09:40
Thank you for following up, I'm going to look into getting this device for testing.

**Comment by tobrun** [comment] 2017-07-07 08:08
Was able to get my hands on a device to do some testing. Initial test with Android 6.x does not show any issues. Updating device now to verify if it's related to Android version.

**Comment by tobrun** [comment] 2017-07-07 09:48
@vacxe 
Sadly wasn't able to reproduce with a Samsung Galaxy s6 edge. 
- Would you be able to retest with latest master? 
- Can you share more device details or compare them with the device I'm using?

![ezgif com-video-to-gif 64](https://user-images.githubusercontent.com/2151639/27952767-c204c320-6309-11e7-8ea0-eb0b5f99c61e.gif)

**Comment by vacxe** [comment] 2017-07-10 08:09
@tobrun 
- More devices details
![alt text](https://image.ibb.co/bMQ5Hv/device_2017_07_10_134625_Easy_Resize_com.jpg)
- I build latest master version. And problem to resolved yet [Video](https://drive.google.com/open?id=0B8Sury_PDS4cLWdES21QY3BXdzg)

**Comment by vacxe** [comment] 2017-07-10 08:15
@tobrun my mistake with version. Sorry.

**Comment by vacxe** [comment] 2017-07-18 09:48
@tobrun any info?

**Comment by tobrun** [comment] 2017-08-01 07:33
Still haven't been able to reproduce this issue once.. capturing from other issues related to this that they have resolved it by hooking into textureView instead. (this can be done through xml or MapboxMapOptions).

**Comment by tobrun** [comment] 2018-01-18 12:56
Closing this issue an non reproducible, please communicate back if you have more information on this issue. Reproducible code examples are highly appreciated! Thank you for reaching out!

**Closed by tobrun** 2018-01-18 12:56 UTC
Labels: Android, needs information
