### ISSUE TITLE
Could not find Settings.bundle

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#1095] opened 2015-03-25 09:08 UTC
The static build not find the settings.bundles

**Comment by picciano** [comment] 2015-03-25 15:05
Did you re-run git submodule update? There is a new style added to the styles submodule and it is set as the new default map style.

**Comment by robipresotto** [comment] 2015-03-25 15:10
yes, i did

**Comment by bleege** [comment] 2015-03-25 16:07
@robipresotto Can you tell us more about the Settings.bundle file not being found?  Are you seeing the `Could not find Settings.bundle` console message when the app is run?

**Comment by robipresotto** [comment] 2015-03-25 16:21
exactly

**Comment by bleege** [comment] 2015-03-25 16:49
Thanks for clarifying @robipresotto.  Did you do a `make clean` or `make iproj` after updating to the latest code from Github?

**Comment by robipresotto** [comment] 2015-03-25 17:34
after make clean, make iproj still the same problem... and nothing on app settings...
![ios simulator screen shot 25 mar 2015 18 33 54](https://cloud.githubusercontent.com/assets/3818948/6830936/87a67436-d31d-11e4-90eb-f6a1ba148252.png)

**Comment by bleege** [comment] 2015-03-25 17:34
I think I've found an answer.  While I was able to get `Settings.bundle` to work after creating a `make clean` and `make iproj` I did notice that `Settings.bundle` wasn't being included in the project generation process.  Once it passes the CI test i'll merge it in.

**Comment by bleege** [comment] 2015-03-25 17:35
Thanks for the screenshot @robipresotto.  How's that for timing though with the posts?  :-)

**Comment by robipresotto** [comment] 2015-03-25 17:47
hehe after the merging still the same :/

**Comment by bleege** [comment] 2015-03-25 19:01
Just merged it in to the `master` branch of the project.

As for the specific situation that you describe @robipresotto, did you run `make iproj` after you merged?

**Comment by robipresotto** [comment] 2015-03-25 19:19
i did make iproj after merged and still the same :/

**Comment by friedbunny** [comment] 2015-03-25 19:24
Xcode ⇧⌘K clean after a `make iproj` and merging worked for me.

**Comment by robipresotto** [comment] 2015-03-26 08:14
still the same

**Comment by incanus** [comment] 2015-03-26 17:00
@robipresotto Can you double-check your build product in Xcode (open the bundle) and see if the Setting.bundle is inside?

**Comment by robipresotto** [comment] 2015-03-26 17:05
![by robitto 2015-03-26 at 18 05 20](https://cloud.githubusercontent.com/assets/3818948/6852028/baed89a4-d3e2-11e4-9ae8-558aa83db765.png)

**Comment by bleege** [comment] 2015-03-26 17:24
Thanks for the screenshot @robipresotto.  It looks like the `MapboxGL.bundle` that's in the source is missing a `.plist`.  See below for example:

![screen shot 2015-03-26 at 12 22 59 pm](https://cloud.githubusercontent.com/assets/989928/6852506/05a458cc-d3b3-11e4-8d35-ea4a24649565.png)

**Comment by incanus** [comment] 2015-03-26 17:24
I mean like here @robipresotto: 

![screen shot 2015-03-26 at 10 24 16 am](https://cloud.githubusercontent.com/assets/17722/6852514/4ea493b8-d3a2-11e4-9785-a58ec37a17ad.png)

**Comment by robipresotto** [comment] 2015-03-26 17:42
![by robitto 2015-03-26 at 18 42 07](https://cloud.githubusercontent.com/assets/3818948/6852892/dbdd6d1e-d3e7-11e4-8d57-724529bd78a1.png)

**Comment by incanus** [comment] 2015-03-27 17:55
We just can't reproduce this @robipresotto. Can you try again and if you are able to, post here and I'll reach out to you by email for a sample project?

**Closed by incanus** 2015-03-27 17:55 UTC
Labels: iOS, metrics

**Comment by tgaul** [comment] 2015-04-16 20:02
I'm using the CocoaPod via the instructions at https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS. I get this message in my app, and the Settings.bundle is nowhere to be found in the Pods directory, nor the targets it creates.

**Comment by 1ec5** [comment] 2015-04-16 20:40
@tgaul This ticket was related to installing Mapbox GL by combining projects in a workspace manually. If you’re installing via CocoaPods, you still need to create a Settings.bundle yourself. You can copy the [example implementation from here](https://github.com/mapbox/mapbox-gl-native/tree/master/ios/app/Settings.bundle). The podspec doesn’t add it to your project automatically because you may already have a Settings.bundle or you may want to implement the opt-out a different way.

**Comment by incanus** [comment] 2015-04-16 20:43
_::waves::_ Hey, Troy! :smile:

**Comment by tgaul** [comment] 2015-04-16 20:45
Cool. Might be nice to mention that in the "Using CocoaPods (recommended)" section of that doc.

**Comment by 1ec5** [comment] 2015-04-16 20:59
[Done](https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS/_compare/e5414d813355f973df5b7157cd9bb19d5c4cc378...cbc4f2345a332b69d9f9a01130efffaec4ab87d4).
