### ISSUE TITLE
gcc compiler version support question

### ISSUE THREAD

**Issue by limingchina** [mapbox/mapbox-gl-native#15616] opened 2019-09-12 07:26 UTC
Compilation failed for std::move usage with gcc version 9.2.1.
One example is:

```
../platform/default/src/mbgl/storage/default_file_source.cpp:286:21: error: redundant move in return statement [-Werror=redundant-move]
  286 |     return std::move(req);
      |            ~~~~~~~~~^~~~~
../platform/default/src/mbgl/storage/default_file_source.cpp:286:21: note: remove ‘std::move’ call

```
So the general question is that if we want to drop gcc 4.9 compiler support. I noticed there is one comment in renderer_backend.cpp

```
     // Needs move to placate GCC 4.9
-    return std::move(result);
```

**Comment by andrewharvey** [comment] 2019-10-26 05:34
I think this is a duplicate of #15523

**Comment by tmpsantos** [comment] 2019-10-29 19:41
@limingchina Closing as duplicated, but answering your question, we are evaluating dropping GCC 4.9. The only reason why we still have it is because of customers using devices with old compilers.

**Closed by tmpsantos** 2019-10-29 19:41 UTC
