### ISSUE TITLE
MapChange loading notifications are never sent

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2263] opened 2015-09-04 21:15 UTC
These `MapChange` notifications are never sent and exist [only in the `enum` definition](https://github.com/mapbox/mapbox-gl-native/blob/322e1aa2c3c2570554a2fe2bbfa733ab7bbd4e81/include/mbgl/map/view.hpp#L20-L22):

```c++
MapChangeWillStartLoadingMap = 5,
MapChangeDidFinishLoadingMap = 6,
MapChangeDidFailLoadingMap = 7,
```

They need to be hooked up at the MBGL level. The delegate methods already exist on [iOS](https://github.com/mapbox/mapbox-gl-native/blob/2d6913da6d028dd76ca0ac049a9289636a1fcfc9/platform/ios/MGLMapView.mm#L2761-L2785) and [Android](https://github.com/mapbox/mapbox-gl-native/blob/e78eacefdb12e270ff990f31e22ee118b467d9b4/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java#L200-L205).

/cc @kkaefer @brunoabinader @tmpsantos @jfirebaugh

**Comment by ljbade** [comment] 2015-10-13 06:44
The obvious place to implement this is here: https://github.com/mapbox/mapbox-gl-native/blob/67f0108389cdd51f3c59ae7638ea2ecd1c4fa899/src/mbgl/map/map_context.cpp#L115-L119

@jfirebaugh For the map finish loading, should it be delayed until after the next successful `asyncUpdate`? I assume this is when we actually know things such as the marker top offset pixels value? (Needed in #2599)

**Comment by ljbade** [comment] 2015-10-13 09:45
@jfirebaugh in the commit ^ I tried triggering `MapChangeDidFinishLoadingMap` after the `update()`, but this is still too early. I need to wait for at least the sprite sheets to finish loading. Should we also wait for fonts to finish loading too?

I'm not familiar enough with the code to know how to wait for sprites/fonts to finish loading.

**Comment by jfirebaugh** [comment] 2015-10-13 16:30
Closing as a duplicate of #630; will comment there with implementation notes.

**Closed by jfirebaugh** 2015-10-13 16:30 UTC
Labels: bug
