### ISSUE TITLE
Snapshot Blocks the UI in Android

### ISSUE THREAD

**Issue by EzlyJohnnie** [mapbox/mapbox-gl-native#6587] opened 2016-10-05 09:47 UTC
MapBox 4.2.0-beta1
I Was trying to blur the map in background.
First I tried to convert the mapView to bitmap, but I got a black image with only makers.
So I tried to get snapshot from map, but it block the UI thread around 1.5 sec.
It will throw error if I don't run the map.snap() in main thread.
Is that a better way to blur the map?

**Comment by tobrun** [comment] 2016-10-05 12:49
Duplicate of #6238

**Closed** 2016-10-05 12:54 UTC
