### ISSUE TITLE
Something went wrong with styling. Need help.

### ISSUE THREAD

**Issue by adolgiy** [mapbox/mapbox-gl-native#10703] opened 2017-12-14 23:00 UTC
**Platform:** Android 8.1
**Mapbox SDK version:** 5.1.5 (Because 5.2.0 crashes on pre-Lollipop)

### Description
Some labels displayed with Android SDK still in English, but in my theme all labels are displayed properly in Russian, as I set up in theme.

The theme in `layout.xml` is `mapbox://styles/eskartaxi/cjb72mk3935dl2rqaeuiocjbd`. I mean... Themes are the same.

### Expected behavior
![image](https://user-images.githubusercontent.com/22356921/34018552-68a8a4f8-e13b-11e7-9fbb-f8784b837c94.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/22356921/34018530-478fe362-e13b-11e7-8613-18a6bca69436.png)

**Comment by Guardiola31337** [comment] 2017-12-15 11:25
Hey @adolgiy 👋
Thanks for reaching out and report your problem.

> **Mapbox SDK version:** 5.1.5 (Because 5.2.0 crashes on pre-Lollipop)

Wanted to warn you that https://github.com/mapbox/mapbox-gl-native/pull/10579 landed and it's available in the latest [release `5.2.1`](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v5.2.1).

Could you please retest this with the latest version and report back if it's still an issue?

**Comment by adolgiy** [comment] 2017-12-15 12:31
Hey @Guardiola31337! This issue is really solved. Just upgraded my version.

But the problem with locale is still there. 😞

**Comment by adolgiy** [comment] 2017-12-19 21:59
@Guardiola31337 Hi again! How can I up this issue?
On iOS platform all labels are ok, but on Android I should change all layers manually.

**Comment by danswick** [comment] 2018-01-04 21:26
Hi @adolgiy. It looks like your style has some unpublished changes. Can you try clicking the blue "Publish your style" button and let us know if the issue is resolved? Note that it may take a few minutes for the cached version of your style to clear.

**Comment by adolgiy** [comment] 2018-01-04 22:36
@danswick Hi! Cool. Sorry for wrong info. This button is so small for them who never read guides.

**Closed** 2018-01-04 22:36 UTC
Labels: Android

**Comment by danswick** [comment] 2018-01-05 00:41
no problem! glad you've got it working.
