### ISSUE TITLE
pencil-v7 style broken

### ISSUE THREAD

**Issue by H4wak** [mapbox/mapbox-gl-native#1340] opened 2015-04-24 10:02 UTC
When loading the pencil-v7 style, only the background image appears. (on OS X Yosemite)

**Comment by H4wak** [comment] 2015-04-24 12:43
I tried the "background-image" option with an other style and an other image, it's quite weird. All "line" and "fill" option in style disappear, only texts are present with a black background.

![capture d ecran 2015-04-24 a 14 39 17](https://cloud.githubusercontent.com/assets/8796622/7318775/bd514320-ea8f-11e4-87bf-6ef3dcb08136.png)
![capture d ecran 2015-04-24 a 14 38 33](https://cloud.githubusercontent.com/assets/8796622/7318784/d47b9d5c-ea8f-11e4-9eb5-28bbf1a050aa.png)

**Comment by H4wak** [comment] 2015-04-24 12:49
When zooming and dezooming we can see little parts of the map for a sec :

![capture d ecran 2015-04-24 a 14 48 01](https://cloud.githubusercontent.com/assets/8796622/7318925/010b820a-ea91-11e4-88ec-8c5e001a0f17.png)

**Comment by 1ec5** [comment] 2015-04-24 16:06
ref #1288

**Comment by 1ec5** [comment] 2015-05-11 04:30
Dupe of mapbox/mapbox-gl-native#636.

**Closed by 1ec5** 2015-05-11 04:30 UTC
Labels: bug
