### ISSUE TITLE
Layers flicker during zoom

### ISSUE THREAD

**Issue by cvance** [mapbox/mapbox-gl-native#14243] opened 2019-03-26 23:17 UTC
Fill Layers seem to flicker, artifact or get clipped when zooming in and out on a map with many layers. It does seem to stop after tiles have become cached. 

Demo video (best example at end):
https://imgur.com/a/wk51Qn1

Fork for reproducing:
https://github.com/cvance/mapbox-android-demo

### Steps to reproduce

 1. Clean install
 2. Open "Style circles categorically" under Data-driven styling
 3. Zoom in & out

### Configuration

**Android versions:** 8.0
**Device models:** Samsung Galaxy S8
**Mapbox SDK versions:** 7.2.0 and possibly older

**Comment by chloekraw** [comment] 2019-05-03 21:34
@cvance - we believe https://github.com/mapbox/mapbox-gl-native/pull/14438 has fixed this issue, which went out in the latest `alpha` on both mobile platforms. Please let us know if you are able to reproduce with the alpha or with this PR. The next beta and final release are slated for the end of the month.

**Comment by cvance** [comment] 2019-05-03 22:45
Initial impressions are looking very promising! Great news!

**Comment by pozdnyakov** [comment] 2019-05-13 11:19
@cvance could you confirm whether the issue is fixed for you?

**Comment by cvance** [comment] 2019-05-16 17:57
From everything I can see on the array of devices I've tested, yes. Fill layers seem much more stable now 😄 

I do see this error in my logs from when I use our style based on mapbox's satellite style but it appears to work just fine.

` E/Mbgl-NativeMapView: OnStyleImageMissing: `

**Comment by chloekraw** [comment] 2019-05-17 01:15
Thanks @cvance! Glad to hear it. Hmm, that's weird. Are you using the `onStyleImageMissing` callback (https://github.com/mapbox/mapbox-gl-native/pull/14253)?

**Comment by LukasPaczos** [comment] 2019-05-17 09:04
@cvance this means that there images that your style is looking for, but are not added to the map. You can listen to this event and react with the listener that @chloekraw linked (`OnStyleImageMissingListener`), but we've removed the log itself with https://github.com/mapbox/mapbox-gl-native/pull/14600 in the stable `7.4.0`.

**Comment by pozdnyakov** [comment] 2019-05-20 09:07
Closing this, @cvance please feel free to reopen if see fill layers flickering again. Thanks.

**Closed by pozdnyakov** 2019-05-20 09:07 UTC
Labels: Core
