### ISSUE TITLE
iOS: Follow With Heading tracking mode is being reset after next location update

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1183] opened 2015-04-02 17:29 UTC
I am setting the `userTackingMode` to `MGLUserTrackingModeFollowWithHeading`

After the first location update, the tracking mode is being reset to `MGLUserTrackingModeNone` and the map no longer tracks to the user's location.

**Comment by 1ec5** [comment] 2015-04-02 17:31
Dupe of #1145. The workaround is to set a valid coordinate before setting the user tracking mode.

**Comment by picciano** [comment] 2015-04-02 17:41
This might be little different. I am not doing this at startup and I am setting a center location for the map. I will reword the title to make more sense.

**Comment by friedbunny** [comment] 2015-04-04 18:26
@picciano In what order are you setting everything and at what base zoom level? There are a lot of landmines in the various `setZoomLevel` or `setCenterCoordinate` methods that will reset to `MGLUserTrackingModeNone`.

One bug that I consistently see is when any `MGLUserTrackingMode` is enabled and the user zooms beyond [`round(self.zoomLevel) >= 10`](https://github.com/mapbox/mapbox-gl-native/blob/e6e340afd17a29ee4d183540e716376cdb1ef88e/platform/ios/MGLMapView.mm#L1820-L1856), the eventual call to `[MGLMapView setCenterCoordinate:zoomLevel:animated:]` [resets the tracking mode](https://github.com/mapbox/mapbox-gl-native/blob/e6e340afd17a29ee4d183540e716376cdb1ef88e/platform/ios/MGLMapView.mm#L1184).

It seems to me that the forced zoom back to maximum (z18) when you were trying to zoom out is a somewhat annoying and unexpected behavior in the first place, but that's different topic.

**Comment by picciano** [comment] 2015-04-06 17:38
At startup:

    // Create the map view...
    self.mapView = [[MGLMapView alloc] initWithFrame:self.view.bounds accessToken:kMapboxPublicAccessToken];
    self.mapView.showsUserLocation = YES;
    self.mapView.userTrackingMode = MGLUserTrackingModeNone;
    self.mapView.rotateEnabled = NO;
    self.mapView.delegate = self;
    [self setTallyGoStyle];
    [self.view insertSubview:self.mapView atIndex:0];

User event triggers:

    self.mapView.userTrackingMode = MGLUserTrackingModeFollow;

Another user event triggers:

    self.mapView.userTrackingMode = MGLUserTrackingModeNone;
    self.mapView.rotateEnabled = !self.mapView.rotateEnabled;  // is YES now

Anther user event triggers:

    self.mapView.userTrackingMode = MGLUserTrackingModeFollowWithHeading;

The settings stays set for less than one second, then reverts back to MGLUserTrackingModeNone after the next location update.

**Comment by picciano** [comment] 2015-04-06 17:41
@friedbunny So, yes the zoom level is at 12 (set by code). MGLUserTrackingModeFollow works fine. MGLUserTrackingModeFollowWithHeading resets to MGLUserTrackingModeNone.

**Comment by friedbunny** [comment] 2015-04-07 18:45
Thanks for the walk-through @picciano, I'm going to take a look at this today.

**Comment by friedbunny** [comment] 2015-04-07 22:10
I can't reproduce this — I'm using actionsheet buttons to instigate the progression you outlined but the tracking mode stays properly set throughout.

**Comment by picciano** [comment] 2015-04-07 23:18
I am still seeing it, but I will see if I can isolate it better and provide a demo.

**Comment by picciano** [comment] 2015-04-08 15:08
Okay, I think I see what's going on. In my map delegate, I implement the `didUpdateUserLocation:` method. In that method, I call the `setDirection:` method of the map view, which turns off user tracking as a side effect.

If that's how it's supposed to work, then we're fine and this can be closed.

**Comment by picciano** [comment] 2015-04-08 15:09
But I guess that leaves me with the question, how can I keep the map oriented to the heading of the user?

**Closed** 2015-04-08 15:16 UTC
Labels: bug, iOS

**Comment by 1ec5** [comment] 2015-04-08 17:33
@picciano If you set `userTrackingMode` to `MGLUserTrackingModeFollowWithHeading`, `-[MGLMapView locationManager:didUpdateHeading:]` [already takes care of rotating the map for you](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLMapView.mm#L1917).

**Comment by rupendrag-ios** [comment] 2020-01-21 06:28
Hello Guys, 
My application getting crashes most of the time while we using self.mapView.userTrackingMode  
![Screen Shot 2020-01-21 at 11 56 52 AM](https://user-images.githubusercontent.com/36614663/72780580-2a669f80-3c45-11ea-85dc-333ed2898e53.png)

Please let me know How can i resolve the crash issue.
