### ISSUE TITLE
Android logcat: Attempt to remove non-JNI local reference, dumping thread

### ISSUE THREAD

**Issue by uburoiubu** [mapbox/mapbox-gl-native#9628] opened 2017-07-27 08:05 UTC
Have this warning every time I create a GeoJsonSource:

```
     Gson gson = Utils.createGsonWithTypeString();
        FeaturesPointObj featuresObj = new FeaturesPointObj();
        featuresObj.setFeatures(points);
        jsonPoints = gson.toJson(featuresObj);
        sourcePoints = new GeoJsonSource("track_points_source", jsonPoints); 
```

What could be the cause of this warning? 

P.S. I use Nexus 5x.

**Comment by tobrun** [comment] 2017-07-27 11:52
@uburoiubu 

The cause of the warning is the usage of `DeleteLocalRef` in combination with having CheckJNI turned on. 

Capturing some more detailed information from the chromium tracker [here](https://bugs.chromium.org/p/chromium/issues/detail?id=506850).

> Whenever the parameters passed from Java to a JNI method (i.e. the incoming jobject parameters) are wrapped in a ScopedLocalJavaRef, this causes them to be deleted once they go out of scope with JNIEnv::DeleteLocalRef. On recent versions of ART with CheckJNI turned on, this causes a spammy warning to be printed to logcat stating "Attempt to remove non-JNI local reference, dumping thread" with a thread dump, as apparently parameters are not supposed to be deleted, only objects returned as local references from native->java JNI calls. This is not actually a problem since the runtime just does nothing in this case (other than printing the warning)

Normally you should only see these warnings using an emulator as checkJNI is on by default. Could you verify if checkJNI is enabled on your device? More information in the extended checking section [here](https://developer.android.com/training/articles/perf-jni.html).

This issue is non actionable, shouldn't occur in normal circumstances, closing.

**Closed by tobrun** 2017-07-27 11:52 UTC
Labels: Android

**Comment by uburoiubu** [comment] 2017-07-27 16:14
Hi, have the same issue while trying to hide a layer that is already on the mapboxmap:

```
public void hideLayersById(ArrayList<String> args) {
        Log.e("LayerGroup: ", "hideLayersById");
        for (String id : args) {
            Layer layer = mapboxMap.getLayer(id);
            if (layer != null) {
                layer.setProperties(visibility(VISIBLE));
            }
        }
    }
```
