### ISSUE TITLE
- mapView: imageForAnnotation: not showing multiple images

### ISSUE THREAD

**Issue by Mamonaku** [mapbox/mapbox-gl-native#4054] opened 2016-02-21 10:07 UTC
Hello,
I'm using the latest 3.1 SDK. 

It seems that the delegate mapView: imageForAnnotation:] isn't showing multiple custom markers, i.e., the last image assigned is applied to all annotations.

Looking into the delegate, this happens 100% of the time when multiple annotations are visible at the same time. In particular, in the code below, dequeueReusableAnnotationImageWithIdentifier: returns an MGLAnnotationImage object even if it's in use for another visible marker. This manifest itself by having +annotationImageWithImage:reuseIdentifier: only called once, while several different markers are visible in the viewport.

Can you help?

thanks!

```
- (nullable MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(id <MGLAnnotation>)annotation{

    MGLAnnotationImage *annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:@"pin"];
    NSString *s = [NSString stringWithFormat:@"pin%@.png",[(MyAnnotation*)annotation foobar]];
    UIImage *image = [UIImage imageNamed:s];
    if (!image) {
        image = [UIImage imageNamed:@"foobar.png"];
    }

    if (!annotationImage) {
        annotationImage = [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:@"pin"];
        DLog(@"---> alloc'ing new annotation s = %@",s);

    }else{
        annotationImage.image = image;
    }
    
    return annotationImage;
}
```

**Comment by 1ec5** [comment] 2016-02-21 10:15
Duplicate of #3147.

**Closed by 1ec5** 2016-02-21 10:15 UTC
Labels: bug, iOS
