### ISSUE TITLE
[ios] Crash in ios sdk 3.4.2

### ISSUE THREAD

**Issue by iseeicando** [mapbox/mapbox-gl-native#8791] opened 2017-04-21 08:34 UTC
crash log ：

name = NSInvalidArgumentException
reason = *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
callstack =
0 CoreFoundation  ___exceptionPreprocess
1 libobjc.A.dylib  objc_exception_throw + 56
2 CoreFoundation  CFStringConvertNSStringEncodingToEncoding + 0
3 xxxxxx  -[MGLMapView visibleAnnotationsInRect:] MGLMapView.mm:188
4 xxxxxx  -[MGLMapView updateAnnotationViews] MGLMapView.mm:4761
5 xxxxxx  -[MGLMapView notifyMapChange:] MGLMapView.mm:4714
6 xxxxxx  __ZN8MBGLView15notifyMapChangeEN4mbgl9MapChangeE MGLMapView.mm:5206
7 xxxxxx  __ZN4mbgl3Map6renderERNS_4ViewE
8 xxxxxx  -[MGLMapView glkView:drawInRect:] MGLMapView.mm:872
9 GLKit  -[GLKView _display:]
10 xxxxxx  -[MGLMapView updateFromDisplayLink] MGLMapView.mm:1000
11 QuartzCore  __ZN2CA7Display15DisplayLinkItem8dispatchEy
12 QuartzCore  __ZN2CA7Display11DisplayLink14dispatch_itemsEyyy
13 IOKit  IODispatchCalloutFromCFMessage + 372
14 CoreFoundation  ___CFMachPortPerform
15 CoreFoundation  ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
16 CoreFoundation  ___CFRunLoopDoSource1
17 CoreFoundation  ___CFRunLoopRun
18 CoreFoundation  CFRunLoopRunSpecific + 444
19 GraphicsServices  GSEventRunModal + 180
20 UIKit  -[UIApplication _run]
21 UIKit  UIApplicationMain + 208
22 mxtrip  _main main.m:13
23 libdyld.dylib  _start

**Comment by boundsj** [comment] 2017-04-21 17:39
Thanks for the report @iseeicando.

This is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/8163 that was fixed by https://github.com/mapbox/mapbox-gl-native/pull/8513 that was first available in [Mapbox iOS Map SDK v3.5.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.5.1). Please update to the [latest Mapbox iOS Map SDK release](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.5.2).

**Closed by boundsj** 2017-04-21 17:39 UTC
