### ISSUE TITLE
Add Android event listeners

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1942] opened 2015-07-28 02:27 UTC
We should add support for listening to the various Map events such as map position changes etc.

I see Google Maps has a variety of different listeners listed [here](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap)

@bleege What sort of listeners does the raster SDK have?

What should we implement?

**Comment by incanus** [comment] 2015-07-28 05:09
@ljbade Are https://www.mapbox.com/mapbox-android-sdk/api/0.7.4/com/mapbox/mapboxsdk/events/MapListener.html and https://www.mapbox.com/mapbox-android-sdk/api/0.7.4/com/mapbox/mapboxsdk/views/MapViewGestureDetectorListener.html helpful?

**Comment by ljbade** [comment] 2015-07-28 06:01
@incanus Yeah. I think there are also some other listeners we could add from `notifyMapChange`

Depends what is useful to apps vs what is just usefully internally.

**Comment by ljbade** [comment] 2015-08-06 06:10
List of touch events from @erf:
- click
- long click
- drag

**Comment by erf** [comment] 2015-08-13 10:22
I belive adding the following to MapView will solve the first two:
<pre>
        @Override
        public boolean onSingleTapUp(MotionEvent e) {
            // Cancel any animation
            mNativeMapView.cancelTransitions();

            performClick();

            return true;
        }

        // Called for single taps after a delay
        @Override
        public boolean onSingleTapConfirmed(MotionEvent e) {
            return false;
        }

        // Called for a long press
        @Override
        public void onLongPress(MotionEvent e) {
            // TODO
            performLongClick();
        }
</pre>

**Comment by erf** [comment] 2015-08-13 10:34
Now onMapChangedListener, get's a lot of events. Google maps only receives these events after map has stopped moving (after a drag).

**Comment by erf** [comment] 2015-08-13 10:42
Instead of drag - we could perhaps add an "OnFlingListener", since it's already an gesture for that?

**Comment by erf** [comment] 2015-08-13 10:59
Just add somthing like
<pre>
    public interface OnFlingListener {
        void onFling();
    }

    public interface OnScrollListener {
        void onScroll();
    }

    private OnFlingListener onFlingListener;
    private OnScrollListener onScrollListener;

    public void setOnScrollListener(OnScrollListener onScrollListener) {
        this.onScrollListener = onScrollListener;
    }

    public void setOnFlingListener(OnFlingListener onFlingListener) {
        this.onFlingListener = onFlingListener;
    }
</pre>
And then call those inside
<pre>
        public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
</pre>
and 
<pre>
        public boolean onFling(MotionEvent e1, MotionEvent e2, float velocityX,
</pre>

**Comment by erf** [comment] 2015-08-13 11:34
created a pull request for this #2063

**Comment by bleege** [comment] 2015-08-31 22:07
Merged #2063 .  Thanks again @erf!

**Closed by bleege** 2015-08-31 22:07 UTC
Labels: Android, feature

**Comment by erf** [comment] 2015-08-31 22:09
No problem:)
