### ISSUE TITLE
Modifying annotation should not require removing it and adding it again (iOS)

### ISSUE THREAD

**Issue by futureshape** [mapbox/mapbox-gl-native#2517] opened 2015-10-03 18:19 UTC
Currently, the only way to get the map to show changes in an annotation (especially its image) is is to remove it and add it again i.e. 

```
[self.mapView removeAnnotation:annotation];
[self.mapView addAnnotation:annotation];
```

This causes flickering (see #1688) but also has the side effect of de-selecting an annotation that was previously selected by the user. There is a workaround for this:

```
BOOL annotationWasSelected = [self.mapView.selectedAnnotations containsObject:annotation];
[self.mapView removeAnnotation:annotation];
[self.mapView addAnnotation:annotation];
if(annotationWasSelected) [self.mapView selectAnnotation:annotation animated:false];
```

But ideally it should be possible to modify an annotation is a simpler way.

**Comment by 1ec5** [comment] 2015-10-03 18:25
Related to #1980, which is about moving the annotation.

**Comment by RomainQuidet** [comment] 2015-11-30 16:03
related to #2210 
Solved by pull request #3146 
Waiting for code review.
annotation will be updated by modifying its annotationImage.image property which is no more read only (based on native MapKit interface)

**Comment by 1ec5** [comment] 2016-01-08 07:00
This was fixed in #3146 and will be in the next release.

**Comment by t-yoshii** [comment] 2016-02-02 02:01
Does #3146 also fix to allow annotation coordinate to be updated?

**Comment by 1ec5** [comment] 2016-02-02 02:32
Oh you're right, that hasn't been addressed yet.

**Comment by jfirebaugh** [comment] 2016-02-15 18:33
#1980 is related / could be considered a duplicate.

**Comment by 1ec5** [comment] 2016-02-15 19:15
OK, duplicate of #1980.

**Closed by 1ec5** 2016-02-15 19:15 UTC
Labels: iOS
