### ISSUE TITLE
Fill layers with opacity flicker when adjusting pitch

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#9833] opened 2017-08-22 15:52 UTC
**Platform:** iOS
**Mapbox SDK version:** 3.6.2

### Steps to trigger behavior

 1. Create a new vector source with a corresponding `MGLFillStyleLayer`
 2. Set the `MGLFillStyleLayer`'s opacity to less than 1
 3. Run application and adjust the pitch of the map
 4. Observe flickering behavior within the `MGLFillStyleLayer` when adjusting pitch

### Expected behavior
The `MGLFillStyleLayer` should not flicker when adjusting pitch.

### Actual behavior
`MGLFillStyleLayer` displays flickering while adjusting pitch:

![bug](https://user-images.githubusercontent.com/10850812/29498592-c0e56ae4-85cd-11e7-9174-01c5d6fdae9c.gif)

I was also able to replicate this in [mapbox/ios-sdk-examples](https://github.com/mapbox/ios-sdk-examples):

![image uploaded from ios 2](https://user-images.githubusercontent.com/10850812/29574648-39ec69d4-8730-11e7-8e4b-bcb519921a05.jpg)

**Comment by jfirebaugh** [comment] 2017-08-22 16:06
Duplicate of #6604.

**Closed by jfirebaugh** 2017-08-22 16:06 UTC
