### ISSUE TITLE
UserHeadingIndicator is small and hard to look.

### ISSUE THREAD

**Issue by noramimiyuma** [mapbox/mapbox-gl-native#10587] opened 2017-11-29 04:17 UTC
**Platform:**
iPhone7 - iOS 11.1.1

**Mapbox SDK version:**
3.7.0

### Description

As this issue title shows, enable the `showsUserHeadingIndicator` on the user location in MGLMapView, that beaklike indicator is too small.

Please make more larger style ( or new parameter for indicator sizes selectable ) .

![img_2670_r](https://user-images.githubusercontent.com/15150828/33357749-8c2f4552-d507-11e7-82eb-750410108c06.png)

**Comment by friedbunny** [comment] 2017-11-29 15:47
Dupe of #10028, but thanks for the report.

**Closed by friedbunny** 2017-11-29 15:47 UTC
Labels: feature, iOS
