### ISSUE TITLE
Add ability to add layer via JSON

### ISSUE THREAD

**Issue by samfader** [mapbox/mapbox-gl-native#14652] opened 2019-05-13 22:49 UTC
Relaying from a customer:

Currently, the way to add a new layer at runtime is to add a source, add a layer, and change the properties of that layer (if needed) programmatically. It would be nice to be able to create a layer by passing in JSON as defined in the style spec: https://docs.mapbox.com/mapbox-gl-js/style-spec/#root-layers

The idea would be to build an API into the SDKs that would mimic the **Update a style API**: https://docs.mapbox.com/api/maps/#update-a-style

**Comment by tobrun** [comment] 2019-05-14 07:07
I believe this is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/13467, closing but feel free to reopen if not a duplicate.

**Closed by tobrun** 2019-05-14 07:07 UTC
Labels: Android, feature, iOS, needs discussion
