### ISSUE TITLE
Tile cache size should be larger on Retina displays

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7093] opened 2016-11-16 16:47 UTC
The tile cache size on iOS and macOS is based on MGLMapView's width and height in points, which means that (all things considered) it doesn't differ between HiDPI and LoDPI displays. However, raster images for HiDPI displays (whether 2× or 3×) are twice as large as on LoDPI displays. The tile cache size calculation should be based on the backing pixel size rather than the point bounds.

/cc @kkaefer @pveugen

**Comment by eimantas** [comment] 2016-11-17 11:29
It's 4 to 9 times as large.

**Comment by mb12** [comment] 2016-11-17 15:33
@1ec5 Has anything changed recently in how set of tiles covering viewport is computed? The behavior seems correct. The number of tiles used to cover the viewport is a function of viewport dims in points. Same number of tiles cover the viewport on both low res and hi res displays so long they have the same dim in points.

**Comment by kkaefer** [comment] 2016-11-17 16:04
@mb12 in #7091, we added caching for raster tiles. Since these are actually dependent on the pixel ratio, we may (or may not!) need to account for that.

**Comment by jfirebaugh** [comment] 2017-02-09 00:44
The unit of cache size is the tile. On 2× displays, we load `@2x` raster tiles, which cover the same physical size on screen as normal tiles on 1× displays. (And of course, vector tiles are agnostic to display pixel ratio by design.) So I'm not clear on why we would need to modify the number of tiles cached based on the display pixel ratio.

**Comment by 1ec5** [comment] 2017-02-09 01:12
I was under the impression that this API determines the maximum size in bytes (or similar):

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm

If it's actually a tile count, then I agree that the device pixel density is irrelevant.

**Comment by jfirebaugh** [comment] 2017-02-13 17:54
Yes, the API is in terms of tile count. Closing in favor of #8039.

**Closed by jfirebaugh** 2017-02-13 17:54 UTC
Labels: iOS, macOS, performance
