### ISSUE TITLE
MapboxMap.addSource does not display layer immediately

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-gl-native#6869] opened 2016-11-01 05:36 UTC
Android
android-v4.2.0-beta.4

We have map application based on Mapbox  (android-v4.2.0-beta.4), and have layer with road traffic

 1. Run Android  mapbox map with custom style - "http://vt.map.vl.ru/styles/primorye.json"

 2. Add source "traffic"  :
Source traffic = new VectorSource("traffic", "http://vt.map.vl.ru/sources/traffic.json");
getMapboxMap().addSource(traffic);

 3. FIll traffic layer with data:  ex:  
LineLayer lineLayer = (LineLayer) getMapboxMap().getLayer("free");
                    Filter.Statement statement = null;
                        statement = Filter.notIn("id",
                        getTakenSegmentsIds().toArray() );
### Expected behavior
Map should diaply traffic layer immediately

### Actual behavior
Video -  https://drive.google.com/file/d/0B-ynsfkrsF6ycDF3T3AwSjhheFU/view?usp=drivesdk 
Map displays traffic layer after changing zoom on mapview, or adding markers. 

Seems to me on beta3 version  update source work well. 

May be i should update mapview?  I've try call invalidate() mapview and layer after adding it and filling filters - but still no update.

**Comment by ivovandongen** [comment] 2016-11-02 12:24
@AlexeyIke Thanks for the report. A couple of things:

- Your style cannot be parsed as the GeoJsonSource "points_traffic" is missing a data attribute
- With this style fixed, you don't need to add the "traffic" VectorSource as it is already defined in the style. Getting the layer and setting the Filter should be sufficient.

If I add the vector source and a line layer on top of the default streets style manually, it seems to work as intended (ignoring the filters in this example):

```
        Source traffic = new VectorSource("traffic", "http://vt.map.vl.ru/sources/traffic.json");
        mapboxMap.addSource(traffic);

        LineLayer lineLayer = new LineLayer("traffic-free", "traffic")
                .withSourceLayer("traffic")
                .withProperties(
                        lineOffset(zoom(1, stop(8f, lineOffset(1f)), stop(12f, lineOffset(1f)), stop(22f, lineOffset(9f)))),
                        lineWidth(zoom(1, stop(8f, lineWidth(1f)), stop(12f, lineWidth(1f)), stop(22f, lineWidth(9f)))),
                        lineColor("#1fb306"),
                        lineOpacity(.6f)
                );
        mapboxMap.addLayer(lineLayer);
```

Here is a screencast of the above code in one of our test activities. The new layer shows up immediately as intended.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/64527/19928652/06b3ef4c-a108-11e6-8e8b-ddef594afbde.gif)

Tested this on our current master btw.

**Comment by AlexeyIke** [comment] 2016-11-02 13:24
Thanks for answer, i'll check it. I've forget to add details, firstly i remove source "traffic" to prevent road traffic tiles load. My point of view - we need  traffic display - i've add source "traffic" (if it absent),  then get LineLayer for  road states and  set filters.  Is that correct or i should add new layers if i remove souse before?

**Comment by AlexeyIke** [comment] 2016-11-02 14:23
I've check with removing and adding Layers for displaying traffic - layer displayed immediately. Thanks.

**Comment by ivovandongen** [comment] 2016-11-02 14:42
@AlexeyIke Great. Closing for now then.

**Closed by ivovandongen** 2016-11-02 14:42 UTC
Labels: Android

**Comment by AlexeyIke** [comment] 2016-11-03 06:53
Looks like new Layer (after creating and adding ) draws on top of all layers - even markers. It is some way to control z-order for new added layer?

**Comment by ivovandongen** [comment] 2016-11-03 13:48
@AlexeyIke There is an overloaded method that takes a String to identify where to place the new layer when adding. See the javadocs [here](https://www.mapbox.com/android-sdk/api/4.2.0-beta.4/com/mapbox/mapboxsdk/maps/MapboxMap.html#addLayer-com.mapbox.mapboxsdk.style.layers.Layer-java.lang.String-)
