### ISSUE TITLE
Fatal Exception: java.lang.Error eglChooseConfig() failed

### ISSUE THREAD

**Issue by MateusCarvalho** [mapbox/mapbox-gl-native#9237] opened 2017-06-10 14:41 UTC
I was received the follow bug in Android with versions 4 and 5.
`Fatal Exception: java.lang.Error: eglChooseConfig() failed
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(SourceFile)
       at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(SourceFile:127)
       at com.mapbox.mapboxsdk.maps.MapView.onCreate(SourceFile:213)
       at com.motaxis.MainActivity.onCreate(SourceFile:157)
       at android.app.Activity.performCreate(Activity.java:5231)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
       at android.app.ActivityThread.-wrap10(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5021)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by tobrun** [comment] 2017-06-12 08:23
Do you have more information on this crash?  Does this stacktrace come from a crash reporting tool? Do you have a use-case to reproduce this? is this crash affecting all 4.x/5.x devices or just a subset?

**Comment by MateusCarvalho** [comment] 2017-06-12 10:29
Yes, this information comes from a bug reporting tool.
The affected versions are as follows:
5.1
4.3.1
4.1.1
4.4.2

Trendmicro Smartphones; Batmobile; Samsung

**Comment by jfirebaugh** [comment] 2017-06-12 22:02
Duplicate of #9120.

**Closed by jfirebaugh** 2017-06-12 22:02 UTC
Labels: Android, crash, needs information
