### ISSUE TITLE
Poly line is missing in some specific zoom level.

### ISSUE THREAD

**Issue by sunzhec2702** [mapbox/mapbox-gl-native#4566] opened 2016-04-01 08:28 UTC
**Platform:** Android
**Mapbox SDK version:** 4.0

### Steps to trigger behavior

 1. Run the MapboxGLSDKTestApp.
 2. enter the polylines activity.
 3. zoom in and make sure that one of the polyline is at center of the screen.
 4. The poly line is missing at zoom level (seem to be 17)

Also, some time the marker is missing as well at my project with new Version 4.0.

### Expected behavior
The poly line should not be missing.
### Actual behavior
The poly line is missing at one zoom level.

**Comment by mastrgamr** [comment] 2016-04-05 17:23
I get the same issue when loading from my custom MapBox styles from the studio (tested on Android, not sure about other platforms).
My style contains data that draws polylines and on some zoomed levels massive parts of the lines get cut off or disappear.

**Comment by sunzhec2702** [comment] 2016-06-04 04:20
Hi @tobrun 
I can still repro this issue? Is this possible that it is only my environment issue?

**Comment by tobrun** [comment] 2016-06-04 06:34
@sunzhec2702 Thank you for the gentle ping on this issue. We are able to reproduce this as well. We are investigating it in https://github.com/mapbox/mapbox-gl-native/issues/5138. Since that issue has a bit more activity and background information. I'm going to close this issue as a duplicate.

**Closed by tobrun** 2016-06-04 06:34 UTC
Labels: bug
