### ISSUE TITLE
Build failed on Debian Stretch

### ISSUE THREAD

**Issue by mlundblad** [mapbox/mapbox-gl-native#9281] opened 2017-06-15 20:55 UTC
**Platform:** Debian GNU/Linux Stretch
**Mapbox SDK version:** git master

### Steps to trigger behavior

Building fails

../../../mason_packages/headers/boost/1.62.0/include/boost/numeric/ublas/matrix_expression.hpp: In member function ‘void boost::numeric::ublas::matrix_binary<E1, E2, F>::const_iterator1::increment(boost::numeric::ublas::sparse_bidirectional_iterator_tag)’:
../../../mason_packages/headers/boost/1.62.0/include/boost/numeric/ublas/matrix_expression.hpp:2224:17: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
                 if (it2_ != it2_end_)
                 ^~
../../../mason_packages/headers/boost/1.62.0/include/boost/numeric/ublas/matrix_expression.hpp:2227:21: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
                     if (it2_ != it2_end_) {
                     ^~

**Comment by jfirebaugh** [comment] 2017-06-15 21:28
Duplicate of #9268.

**Closed by jfirebaugh** 2017-06-15 21:28 UTC
