### ISSUE TITLE
The value for for CFBundleShortVersionString "3.1.1-pre.1" invalid

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#3931] opened 2016-02-13 00:05 UTC
Attempting to upload our app to TestFlight using the dynamic framework version 3.1.1-pre.1 produces an error.

![screen shot 2016-02-12 at 5 02 48 pm](https://cloud.githubusercontent.com/assets/417933/13023889/c82dee12-d1aa-11e5-9394-a4befa74381f.png)

**Comment by 1ec5** [comment] 2016-02-13 00:07
Duplicate of #3911.

**Closed by 1ec5** 2016-02-13 00:07 UTC
