### ISSUE TITLE
LocationComponent black dot

### ISSUE THREAD

**Issue by TomTasche** [mapbox/mapbox-gl-native#15534] opened 2019-09-01 10:36 UTC
Initializing the LocationComponent with default settings makes it show up as a black dot. While zooming in, the "real" drawable (blue dot with white surrounding) flashes up for less than a second.

### Steps to reproduce

Sample project attached.

### Expected behavior

LocationComponent using the default drawable (blue dot with white surrounding).

### Actual behavior

LocationComponent uses black solid dot.

### Configuration

**Android versions:** 26
**Device models:** Nexus 5X Emulator
**Mapbox SDK versions:** 8.3.0

[FlightDashboard.zip](https://github.com/mapbox/mapbox-gl-native/files/3563370/FlightDashboard.zip)
<img width="477" alt="Screenshot 2019-09-01 at 12 30 06" src="https://user-images.githubusercontent.com/128734/64075175-31503e00-ccb5-11e9-922e-3b38d563daa4.png">

**Comment by tobrun** [comment] 2019-09-02 07:03
This seems to be a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10829. Note that this is only reproducible on emulators. Closing as duplicate.

**Closed by tobrun** 2019-09-02 07:03 UTC
