### ISSUE TITLE
Backgroud/relaunch ios app causes crash

### ISSUE THREAD

**Issue by jonathanduty** [mapbox/mapbox-gl-native#1119] opened 2015-03-26 18:40 UTC
On a ios device, run the app.  Move the app around or zoom in.   Then background it, the relaunch.  May have to do this a few times.  Eventually the app will crash.

```
Assertion failed: (*this), function operator*, file include/mbgl/util/ptr.hpp, line 22.

#0	0x33467dfc in __pthread_kill ()
#1	0x334e5d36 in pthread_kill ()
#2	0x33407908 in abort ()
#3	0x333e7368 in __assert_rtn ()
#4	0x000ae288 in mbgl::util::ptr<mbgl::Style>::operator*() const at /Users/jonathanduty/Development/mapbox/mapbox-gl-native/include/mbgl/util/ptr.hpp:22
#5	0x000a1880 in mbgl::Map::render() at /Users/jonathanduty/Development/mapbox/mapbox-gl-native/src/mbgl/map/map.cpp:814
#6	0x000a9196 in mbgl::Map::start(bool)::$_3::operator()() const at /Users/jonathanduty/Development/mapbox/mapbox-gl-native/src/mbgl/map/map.cpp:151
#7	0x000a9068 in decltype(std::__1::forward<mbgl::Map::start(bool)::$_3&>(fp)(std::__1::forward<>(fp0))) std::__1::__invoke<mbgl::Map::start(bool)::$_3&>(mbgl::Map::start(bool)::$_3&&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_base:413
#8	0x000a905e in std::__1::__function::__func<mbgl::Map::start(bool)::$_3, std::__1::allocator<mbgl::Map::start(bool)::$_3>, void ()>::operator()() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1370
#9	0x000ac8fe in std::__1::function<void ()>::operator()() const at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1755
#10	0x000b1834 in uv::async::async_cb(uv_async_s*, int) at /Users/jonathanduty/Development/mapbox/mapbox-gl-native/src/mbgl/util/uv_detail.hpp:82
#11	0x00286faa in uv__async_event at /Users/kkaefer/Code/mason/libuv-0.10.28/mason_packages/.build/libuv-0.10.28/src/unix/async.c:80
#12	0x00287252 in uv__async_io at /Users/kkaefer/Code/mason/libuv-0.10.28/mason_packages/.build/libuv-0.10.28/src/unix/async.c:156
#13	0x0029a03c in uv__io_poll at /Users/kkaefer/Code/mason/libuv-0.10.28/mason_packages/.build/libuv-0.10.28/src/unix/kqueue.c:233
#14	0x00287712 in uv_run at /Users/kkaefer/Code/mason/libuv-0.10.28/mason_packages/.build/libuv-0.10.28/src/unix/core.c:317
#15	0x000a0de8 in mbgl::Map::run() at /Users/jonathanduty/Development/mapbox/mapbox-gl-native/src/mbgl/map/map.cpp:272
#16	0x000a86c2 in mbgl::Map::start(bool)::$_4::operator()() const at /Users/jonathanduty/Development/mapbox/mapbox-gl-native/src/mbgl/map/map.cpp:171
#17	0x000a8542 in void* std::__1::__thread_proxy<std::__1::tuple<mbgl::Map::start(bool)::$_4> >(void*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2602
#18	0x334e4e92 in _pthread_body ()
#19	0x334e4e06 in _pthread_start ()
#20	0x334e2b90 in thread_start ()
```

**Comment by incanus** [comment] 2015-03-26 18:41
I believe @kkaefer is working on a fix for this.

**Comment by kkaefer** [comment] 2015-03-26 18:42
Dupe of #1096, which is already in master.

**Comment by incanus** [comment] 2015-03-26 18:43
P.S. @jonathanduty We'll typically hit tags, but for inline code or stack traces, mind wrapping in \`\`\` lines? See https://guides.github.com/features/mastering-markdown/ for more info. I've been updating some of your tickets.

**Closed by kkaefer** 2015-03-26 18:42 UTC
Labels: crash, iOS

**Comment by jonathanduty** [comment] 2015-03-26 18:44
@incanus Ahh, looks much better.  Will do from now on.  Thank!
