### ISSUE TITLE
Major bug with annotation views

### ISSUE THREAD

**Issue by abushnaq-work** [mapbox/mapbox-gl-native#6864] opened 2016-10-31 20:25 UTC
Platform: iOS
Mapbox SDK version: 3.3.4 or 3.4.0-beta

I have a test app to try out the annotations/overlays feature of Mapbox with our mapping solution that is currently in progress. I am mapping about 20 or 30(maybe more) annotations and constructing their views in the call to viewForAnnotation. If I start the radar playing(it's playing in a custom layer in Mapbox) and I pan away from some of my annotations, viewForAnnotation is getting called for every frame update for every annotation that is not currently on the screen.

The expected behavior would be for the annotations to update when the user moves the map rather than 30 times per second per annotation view. This problem doesn't occur if I use imageForAnnotation instead.

I dug into your code on github and tracked this down to where it thinks the map is being updated which is why it's re-requesting all annotation views. 

I can provide a sample project that demonstrates the issue but I don't see how to add an attachment here.

**Comment by boundsj** [comment] 2016-10-31 20:52
Thanks for the report @abushnaq-work. This looks like a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/6173 that'll be fixed by https://github.com/mapbox/mapbox-gl-native/pull/5987.

**Comment by abushnaq-work** [comment] 2016-11-01 12:58
Thanks @boundsj . Is that scheduled for 3.4.0 ?

**Comment by friedbunny** [comment] 2016-11-01 14:37
Yup!

**Closed by friedbunny** 2016-11-01 14:37 UTC
Labels: bug, iOS, performance

**Comment by boundsj** [comment] 2016-11-01 18:56
https://github.com/mapbox/mapbox-gl-native/pull/5987 was merged to the release branch and will be in the next release (beta 2).
