### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by margge** [mapbox/mapbox-gl-native#5491] opened 2016-06-27 13:10 UTC
Hello, I integrated MapBox 4.0.1 and I am having this report. 
It happens when I try to set an icon to an existing marker.  
Example ```mMarker.setIcon(mIcon)```

Platform: Android
Android version: 4, 5, 6
Mapbox SDK version: 4.0.1@aar

Stacktrace
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
com.mapbox.mapboxsdk.annotations.Icon.equals (Icon.java:35)
java.util.ArrayList.contains (ArrayList.java:339)
com.mapbox.mapboxsdk.maps.MapView.ensureIconLoaded (MapView.java:970)
com.mapbox.mapboxsdk.maps.MapView.updateMarker (MapView.java:960)
com.mapbox.mapboxsdk.maps.MapboxMap.updateMarker (MapboxMap.java:656)
com.mapbox.mapboxsdk.annotations.Marker.setIcon (Marker.java:96)
```
Thanks in advance for your help.

**Comment by mastrgamr** [comment] 2016-06-27 13:31
Looks like the Icon is null. Perhaps it's not [initialized](https://www.mapbox.com/android-sdk/examples/custom-marker-icon/) correctly?

**Comment by bleege** [comment] 2016-06-27 19:35
@margge Can you provide more code that describes the app's setup?  This will help us better diagnose what the issue is.  Thanks!

/cc @mapbox/support

**Comment by tobrun** [comment] 2016-07-04 14:36
I believe @mastrgamr observation is correct and that you are trying to add a null value as an Icon. Feel free to reach out if you have any other issues. Closing as not actionable.

**Closed by tobrun** 2016-07-04 14:36 UTC
Labels: Android, support
