### ISSUE TITLE
MarkerView disappears during animation

### ISSUE THREAD

**Issue by zakgof** [mapbox/mapbox-gl-native#9363] opened 2017-06-25 08:02 UTC
**Platform:** Android
**Mapbox SDK version:** 5.1.0-beta.5

Add 100+ markers and polylines, then animate a MarkerView across screen.
During animation MarkerView blinks (not rendered on some frames), sometimes it's even not displayed on its final position.

![anim](https://user-images.githubusercontent.com/8456072/27514515-8e79d22a-5995-11e7-8617-01a170766136.gif)

### Code to reproduce

(a fragment from `com.mapbox.mapboxandroiddemo.examples.annotations.AnimatedMarkerActivity` 
with some background markers and lines added)

```
mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(MapboxMap mapboxMap) {

        final Icon icon1 = IconFactory.getInstance(AnimatedMarkerActivity.this).fromResource(R.drawable.purple_marker);
        final Icon icon2 = IconFactory.getInstance(AnimatedMarkerActivity.this).fromResource(R.drawable.blue_marker);

        Random random = new Random();
        for (int i = 0; i < 200; i++) {
          LatLng ll = new LatLng(64.900932 + random.nextFloat() * 10.0 - 5.0, -18.167040 + random.nextFloat() * 10.0 - 5.0);
          mapboxMap.addMarker(new MarkerOptions().position(ll).icon(icon1));
          mapboxMap.addPolyline(new PolylineOptions().width(3).alpha(0.5f).color(0xff808080).add(new LatLng(64.900932, -18.167040)).add(ll));
        }

        final MarkerView marker = mapboxMap.addMarker(new MarkerViewOptions().position(new LatLng(64.900932, -18.167040)).icon(icon2));

        mapboxMap.setOnMapClickListener(new MapboxMap.OnMapClickListener() {
          @Override
          public void onMapClick(@NonNull final LatLng point) {
            ValueAnimator markerAnimator = ObjectAnimator.ofObject(marker, "position", new LatLngEvaluator(), marker.getPosition(), point);
            markerAnimator.setDuration(1000);
            markerAnimator.start();
          }
        });

      }
    });
```

**Comment by tobrun** [comment] 2017-06-29 08:07
duplicate of https://github.com/mapbox/mapbox-gl-native/issues/8799

**Closed by tobrun** 2017-06-29 08:07 UTC
Labels: Android
