### ISSUE TITLE
_OBJC_CLASS_$_MGLMapView

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#1862] opened 2015-07-09 10:40 UTC
Just started a new swift project in Xcode 7 beta 3 and followed the steps on https://www.mapbox.com/guides/first-steps-gl-ios/

The build fail with the following error
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MGLMapView", referenced from:
      type metadata accessor for ObjectiveC.MGLMapView in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is how my Podfile looks. Is this how is should be?

```
use_frameworks!
pod 'MapboxGL'

target 'MyApp' do

end

target 'MyAppTests' do

end

target 'MyAppUITests' do

end
```

**Comment by friedbunny** [comment] 2015-07-09 14:18
@halset Which version of CocoaPods are you using?

This could be CocoaPods weirdness, or it may be related to #1859.

**Comment by friedbunny** [comment] 2015-07-09 14:20
Or it could be that we just don't support Xcode 7 or Swift 2 yet — @1ec5?

**Comment by friedbunny** [comment] 2015-07-09 14:25
Actually, this looks like a dupe of #1847/#1849 — @halset could you follow the instructions in https://github.com/mapbox/mapbox-gl-native/issues/1847#issuecomment-119641595 and report back?

**Comment by halset** [comment] 2015-07-09 14:39
Thank you very much. It is working now. And sorry for not finding the duplicate.

I am on CocoaPods 0.38.0.beta.2.

In fact, I only had to add "-ObjC" in one place. On Pods->Targets->MapboxGL->Other Linker Flags. Perhaps "-ObjC" could be added to ${MAPBOXGL_OTHER_LDFLAGS}?

![screen shot 2015-07-09 at 16 36 28](https://cloud.githubusercontent.com/assets/445229/8598044/0946b1a2-2659-11e5-9cae-b91781517cf7.png)

**Comment by friedbunny** [comment] 2015-07-09 14:50
Glad you got this to work! We'll work on fixing this in #1849.

**Closed by friedbunny** 2015-07-09 14:50 UTC
