### ISSUE TITLE
Wrong attribution positioning after resizing MGLMapView via constraints

### ISSUE THREAD

**Issue by u10int** [mapbox/mapbox-gl-native#6568] opened 2016-10-04 02:28 UTC
There seems to be an issue when resizing an MGLMapView via AutoLayout constraints during a custom view controller transition animation that breaks the layout of the attribution views that are normally at the bottom corners. My view controller transition consists of expanding the map view full screen from a smaller frame in the presenting profile/detail controller.

During the transition, the MGLMapView instance from the detail/profile controller is added as a subview of the destination/target view controller after which the necessary AutoLayout constraints are setup and then animated from the starting frame to the destination (full screen) frame. It appears that perhaps changing the map view's parent in this process may be breaking the position of the logo and attribution views at the bottom of the map. 

When working with Mapbox support a few months ago on the issue, it was believed the cause was related to [this issue](https://github.com/mapbox/mapbox-gl-native/issues/3697). But the latest SDK versions still have the issue.

Here's a screen capture of the issue:

![mapbox-logo-position](https://cloud.githubusercontent.com/assets/7958/19060710/4d4ffa02-899f-11e6-8866-f10dd6741aca.gif)

Platform: iOS 8.0+
Mapbox SDK: 3.3.4

Here's condensed version of the code that performs this presentation transition animation via the UIViewControllerAnimatedTransitioning protocol:

``` swift
let toViewController = toViewControllerInContext(transitionContext)
let targetViewController = targetViewControllerForKey(UITransitionContextToViewControllerKey, inContext: transitionContext)

transitionContext.containerView().addSubview(toViewController!.view)

if let mapController = targetViewController as? MapViewController, mapView = mapController.mapView {
    mapController.view.layoutIfNeeded()

    let originalMapSuperview = mapView.superview
    let targetMapFrame = mapController.mapContainerView.convertRect(originalMapSuperview!.frame, fromView: originalMapSuperview!.superview!)
    mapController.mapContainerView.addSubview(mapView)

    var mapHeightConstraint: NSLayoutConstraint?
    var mapTopConstraint: NSLayoutConstraint?

    constrain(mapView) { view in
        view.left == view.superview!.left
        view.right == view.superview!.right
        mapHeightConstraint = (view.height == CGRectGetHeight(targetMapFrame))
        mapTopConstraint = (view.top == view.superview!.top + CGRectGetMinY(targetMapFrame))
    }

    mapHeightConstraint?.constant = CGRectGetHeight(mapController.mapContainerView.frame)
    mapTopConstraint?.constant = 0
    UIView.animateWithDuration(transitionDuration(transitionContext), delay: 0, options: UIViewAnimationOptions.CurveEaseInOut, animations: { () -> Void in
        mapController.view.layoutIfNeeded()
        }, completion: { (finished) -> Void in
            transitionContext.completeTransition(true)
    })
}
```
### Expected behavior

The map view's attribution views should remain pinned to the bottom corners of the map when animating its layout constraints.
### Actual behavior

The map view's attribution views break their layout when animating the map view's layout constraints.

**Comment by 1ec5** [comment] 2016-10-07 06:39
This may be related to the ambiguous constraint warnings we’re seeing for the ℹ️ button, compass view, etc.: #5549.

**Comment by ketz** [comment] 2016-11-16 08:55
@u10int - did you ever find a way to improve that animation?
Having the exact same problem, and it makes it look really bad when animating.

**Comment by 1ec5** [comment] 2016-11-16 16:38
#6776 fixes some issues with the map view's internal constraints, but some known problems remain: #6954.

One workaround for your issue may be to hide the compass, logo view, and attribution button during the animation and show them again afterwards.

**Comment by ketz** [comment] 2016-11-16 19:00
@1ec5 - sadly, hiding those (even permanently to test properly), didn't work.
Here's a quick video to show it happening (with a red background on the map view to highlight the issue):
https://dl.dropboxusercontent.com/u/1977230/MapboxBug.mp4

**Comment by friedbunny** [comment] 2016-12-12 19:10
@frederoni Any sense if #7084 (or other related changes) address this issue?

**Comment by frederoni** [comment] 2016-12-12 19:47
#7084 most likely resolved this issue but there's a lot going on https://github.com/mapbox/mapbox-gl-native/issues/6568#issue-180792165 here with custom transitions so another test using the latest beta version of the SDK would be great. Though it's not only the attribution that's misaligned/missing but the speed of the animation when resizing the map view's frame if I'm not mistaken? (https://github.com/mapbox/mapbox-gl-native/issues/6568#issuecomment-261038898)

**Comment by ketz** [comment] 2016-12-13 09:52
Yes, the issue is the discrepancy between frame animations, which makes the map reveal the background.
I'll give it a go with the Beta SDK as soon as I get a chance

**Comment by lilykaiser** [comment] 2017-11-17 23:38
Closing due to ticket age. If this is still a problem, please re-open

**Closed by lilykaiser** 2017-11-17 23:38 UTC
Labels: bug, iOS
