### ISSUE TITLE
[Android] MyLocationView ForegroundDrawable not showing

### ISSUE THREAD

**Issue by Kahtaf** [mapbox/mapbox-gl-native#9183] opened 2017-06-04 23:57 UTC
Hi there, 

In Android, since 5.1.0-beta.2, the following no longer shows my custom MyLocationView drawable. 

`map.getMyLocationViewSettings().setForegroundDrawable(myCustomDrawable, null);`

The same code above worked fine in 5.1.0-beta.1. I could see my custom location marker as expected.

Thanks.

**Comment by Guardiola31337** [comment] 2017-06-05 12:43
@Kahtaf thank you for reaching out and reporting your problem.

Would you be able to retest this with the latest version `5.1.0-beta.3`? I wasn't able to reproduce the issue described in OP. Do you have a minimal example to reproduce it? If there is any sample or pseudo code you can provide, that would also be helpful.

**Comment by Kahtaf** [comment] 2017-06-05 23:33
Here's a sample Activity that I can see the issue in (taken more or less from the Android samples), using the latest `5.1.0-beta.3`. I was using the SupportMapFragment, which is a requirement for me. 

```
import android.graphics.drawable.Drawable;
import android.location.Location;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v4.app.FragmentManager;
import android.support.v7.app.AppCompatActivity;
import android.widget.Toast;

import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.constants.MyBearingTracking;
import com.mapbox.mapboxsdk.constants.MyLocationTracking;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.location.LocationSource;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import com.mapbox.mapboxsdk.maps.SupportMapFragment;
import com.mapbox.services.android.telemetry.location.LocationEngine;
import com.mapbox.services.android.telemetry.location.LocationEngineListener;
import com.mapbox.services.android.telemetry.permissions.PermissionsListener;
import com.mapbox.services.android.telemetry.permissions.PermissionsManager;

import java.util.List;

public class MainActivity extends AppCompatActivity implements PermissionsListener {
    private PermissionsManager permissionsManager;
    private MapboxMap map;
    private LocationEngine locationEngine;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Mapbox.getInstance(this, "...");
        final SupportMapFragment supportMapFragment = getMapFragment();
        supportMapFragment.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                map = mapboxMap;

                permissionsManager = new PermissionsManager(MainActivity.this);
                if (!PermissionsManager.areLocationPermissionsGranted(MainActivity.this)) {
                    permissionsManager.requestLocationPermissions(MainActivity.this);
                } else {
                    enableLocation();
                }

                map.setMyLocationEnabled(true);
                map.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);
                map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.GPS);
                map.getTrackingSettings().setDismissAllTrackingOnGesture(false);
                map.getTrackingSettings().setDismissAllTrackingOnGesture(false);
                Drawable customLocationView = getResources().getDrawable(R.drawable.mapbox_logo_icon);
                map.getMyLocationViewSettings().setForegroundDrawable(customLocationView, null);
            }
        });

    }

    private SupportMapFragment getMapFragment() {
        FragmentManager fragmentManager = getSupportFragmentManager();
        SupportMapFragment supportMapFragment = (SupportMapFragment) fragmentManager.findFragmentByTag(SupportMapFragment.class.getCanonicalName());
        if (supportMapFragment == null) {
            supportMapFragment = SupportMapFragment.newInstance();
            fragmentManager.beginTransaction().replace(R.id.map_container, supportMapFragment, SupportMapFragment.class.getCanonicalName()).commit();
        }

        return supportMapFragment;
    }

    private void enableLocation() {
        locationEngine = LocationSource.getLocationEngine(this);
        locationEngine.activate();
        locationEngine.requestLocationUpdates();

        // If we have the last location of the user, we can move the camera to that position.
        Location lastLocation = locationEngine.getLastLocation();
        if (lastLocation != null) {
            map.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(lastLocation), 16));
        }

        LocationEngineListener locationEngineListener = new LocationEngineListener() {
            @Override
            public void onConnected() {
                // No action needed here.
            }

            @Override
            public void onLocationChanged(Location location) {
                if (location != null) {
                    // Move the map camera to where the user location is and then remove the
                    // listener so the camera isn't constantly updating when the user location
                    // changes. When the user disables and then enables the location again, this
                    // listener is registered again and will adjust the camera once again.
                    map.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(location), 16));
                    //locationEngine.removeLocationEngineListener(this);
                }
            }
        };

        locationEngine.addLocationEngineListener(locationEngineListener);
        map.setLocationSource(locationEngine);
        map.setMyLocationEnabled(true);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    public void onExplanationNeeded(List<String> permissionsToExplain) {

    }

    @Override
    public void onPermissionResult(boolean granted) {
        if (granted) {
            enableLocation();
        } else {
            Toast.makeText(this, "Location permission not granted", Toast.LENGTH_LONG).show();
            finish();
        }
    }
}
```

**Comment by Guardiola31337** [comment] 2017-06-06 07:48
@Kahtaf using the code you provided I wasn't able to reproduce the issue either.

![issue_9183](https://cloud.githubusercontent.com/assets/1668582/26818894/cdf65a16-4a9c-11e7-9a32-45f6ee096305.png)

```java
public class SupportMapFragmentActivity extends AppCompatActivity implements OnMapReadyCallback, PermissionsListener {

  private PermissionsManager permissionsManager;
  private MapboxMap map;
  private LocationEngine locationEngine;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_map_fragment);

    SupportMapFragment mapFragment;
    if (savedInstanceState == null) {
      final FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();

      mapFragment = SupportMapFragment.newInstance();

      transaction.add(R.id.fragment_container, mapFragment, "com.mapbox.map");
      transaction.commit();
    } else {
      mapFragment = (SupportMapFragment) getSupportFragmentManager().findFragmentByTag("com.mapbox.map");
    }

    mapFragment.getMapAsync(this);
  }

  @Override
  public void onMapReady(MapboxMap map) {
    this.map = map;
    permissionsManager = new PermissionsManager(SupportMapFragmentActivity.this);
    if (!PermissionsManager.areLocationPermissionsGranted(SupportMapFragmentActivity.this)) {
      permissionsManager.requestLocationPermissions(SupportMapFragmentActivity.this);
    } else {
      enableLocation();
    }

    map.setMyLocationEnabled(true);
    map.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);
    map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.GPS);
    map.getTrackingSettings().setDismissAllTrackingOnGesture(false);
    map.getTrackingSettings().setDismissAllTrackingOnGesture(false);
    Drawable customLocationView = getResources().getDrawable(R.drawable.mapbox_logo_icon);
    map.getMyLocationViewSettings().setForegroundDrawable(customLocationView, null);
  }

  private void enableLocation() {
    locationEngine = LocationSource.getLocationEngine(this);
    locationEngine.activate();
    locationEngine.requestLocationUpdates();

    // If we have the last location of the user, we can move the camera to that position.
    Location lastLocation = locationEngine.getLastLocation();
    if (lastLocation != null) {
      map.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(lastLocation), 16));
    }

    LocationEngineListener locationEngineListener = new LocationEngineListener() {
      @Override
      public void onConnected() {
        // No action needed here.
      }

      @Override
      public void onLocationChanged(Location location) {
        if (location != null) {
          // Move the map camera to where the user location is and then remove the
          // listener so the camera isn't constantly updating when the user location
          // changes. When the user disables and then enables the location again, this
          // listener is registered again and will adjust the camera once again.
          map.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(location), 16));
          //locationEngine.removeLocationEngineListener(this);
        }
      }
    };

    locationEngine.addLocationEngineListener(locationEngineListener);
    map.setLocationSource(locationEngine);
    map.setMyLocationEnabled(true);
  }

  @Override
  public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
    permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
  }

  @Override
  public void onExplanationNeeded(List<String> permissionsToExplain) {

  }

  @Override
  public void onPermissionResult(boolean granted) {
    if (granted) {
      enableLocation();
    } else {
      Toast.makeText(this, "Location permission not granted", Toast.LENGTH_LONG).show();
      finish();
    }
  }
}
```

How does your custom location marker look like? Is it even showed in the map?

**Comment by Kahtaf** [comment] 2017-06-06 17:37
I'm experiencing an issue trying the code you posted above (it happened with my code sample too). I'm unable to move the map around. The only gesture that works is pinch to zoom, I'm unable to pan or rotate. The current location marker still doesn't show up. 

[Here's a recording](https://goo.gl/photos/FaoLogWquLVSfX7R7) of what I'm seeing. 

Nexus 6P, Android 7.1.2

**build.gradle**
```
    compile 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0-beta.3@aar'
    compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.1.1'
```
[Here's a link](https://www.dropbox.com/s/kq43jfmv66sie77/MapboxLocationTest.zip?dl=0) to my sample project. I removed the API key which I specified in my MainActivity. 

Happy to provide more information, or open up a new issue if it's unrelated to the current one.

**Comment by Guardiola31337** [comment] 2017-06-06 19:10
@Kahtaf Thanks for using Mapbox.
> I'm unable to move the map around. The only gesture that works is pinch to zoom, I'm unable to pan or rotate.

This is because how you're defining tracking settings.

[`map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.GPS);`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java#L127-L128)
[`map.getTrackingSettings().setDismissAllTrackingOnGesture(false);`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java#L167-L169)
☝️ Both `dismissLocationTrackingOnGesture` and `dismissBearingTrackingOnGesture` are `true` by default.

See [`TrackingSettings.java`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java) for more info.

> The current location marker still doesn't show up.

Are you getting your current location using a different location provider?

Can't reproduce. Closing here, but feel free to reopen if you have any other questions.

**Closed by Guardiola31337** 2017-06-06 19:10 UTC
Labels: Android, bug, needs information

**Comment by Kahtaf** [comment] 2017-06-07 03:22
Thanks for the tip about the tracking settings. Regarding the location marker, I think it was an issue with instant run. I uninstalled the app and redeployed and it magically started working? Sorry for the trouble, and thanks for the assistance.

**Comment by developergirl53** [comment] 2021-02-10 01:31
Hi team
I want to create custom circle for waypoibt or stops which we are betwwwn source and destination 
I have 10 waypoint but not able to get the claas were i can change waypoint default cirlce with my custom triangle image but not a marker!

Kindly guide plz
