### ISSUE TITLE
LineLayer not working after setStyleUrl

### ISSUE THREAD

**Issue by kjetila** [mapbox/mapbox-gl-native#13093] opened 2018-10-12 10:39 UTC
In my application I try to use the LineLayer to display a line between points. I have been using Polyline, but for several reasons I wanted to change to using a LineLayer to display it. 

However, in my application I use a custom mapbox style, and also I want to be able to switch between different custom styles at runtime. Everytime I use the setStyleUrl, the LineLayer will disappear and I am not able to draw a new one. 

I decided to try and make just a small application to check if I could reproduce there error there, and I could. LineLayer will work until setStyleUrl is called. 

I also used the mapboxMap.getLayers to see if I could find the LineLayer there, and it is still there and visibility is set to visible. Tried to remove layer and then add it again, but still with no luck.

Here is a little piece of my code: 

```
public void onMapReady(MapboxMap mapboxMap) {
                // Create the LineString from the list of coordinates and then make a GeoJSON
                // FeatureCollection so we can add the line to our map as a layer.
                LineLayer lineLayer = getLineLayer(mapboxMap);

                mapboxMap.addLayer(lineLayer);
                mMap = mapboxMap;
            }
        });
```
And just a button to trigger the setStyleUrl:

```
testButton.setOnClickListener(new` View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.d("TEST", "onMapReady: setting style url..");
                mMap.setStyleUrl("https://www.mapbox.com/android-docs/files/mapbox-raster-v8.json");
                for (Layer layer : mMap.getLayers()) {
                    Log.i("Layer", layer.getId() + " " + layer.getVisibility().toString());
                }
            }
        });
```

And the getLineLayer:

```
LineString lineString = LineString.fromLngLats(routeCoordinates);

        FeatureCollection featureCollection =
                FeatureCollection.fromFeatures(new Feature[]{Feature.fromGeometry(lineString)});
        GeoJsonSource source = mapboxMap.getSourceAs("line-source");
        if (source != null) {
            source.setGeoJson(featureCollection);
        } else {
            source = new GeoJsonSource("line-source", featureCollection);
            mapboxMap.addSource(source);
        }
        LineLayer lineLayer = new LineLayer("linelayer", "line-source");

        // The layer properties for our line. This is where we make the line dotted, set the
        // color, etc.
        lineLayer.setProperties(
                PropertyFactory.lineCap(Property.LINE_CAP_ROUND),
                PropertyFactory.lineJoin(Property.LINE_JOIN_ROUND),
                PropertyFactory.lineWidth(8f),
                PropertyFactory.lineColor(Color.parseColor("#e55e5e"))
        );
        return lineLayer;
```

I have also made this example application available in my github repository. https://github.com/kjetila/LineLayerExample

Without running the setStyleUrl:
![image](https://user-images.githubusercontent.com/1674294/46864474-d0104980-ce1a-11e8-8f6a-c3bd7b5c3ce0.png)

After clicking test button and change style url:

![image](https://user-images.githubusercontent.com/1674294/46864517-ed451800-ce1a-11e8-9914-6034a00c85f9.png)

### Steps to reproduce

 1. Create a LineLayer
 2. Use the setStyleUrl

### Expected behavior
I expect to see LineLayer also after setStyleUrl. Also atleast would expect that if adding new LineLayer it would be displayed.

### Actual behavior
LineLayer will not be drawn after calling setStyleUrl.

### Configuration

**Android versions:** 7.0, 8.1.0
**Device models:** Samsung SM-T815, Pixel XL 
**Mapbox SDK versions:** 6.6.0

**Comment by tobrun** [comment] 2018-10-12 10:52
@kjetila thanks for reporting your issue. This is expected behaviour, all layers and sources are child elements of a style object. Calling setStyleUrl will clear the style object (and the underlying sources and layers). The annotation API as Polygon is optimised to be able to persist across these style changes, so that is the reason why you weren't able to see that issue with this API.

Downstream in our plugins repo, we work around this issue by initialising the source and layer again if a style has finished loading. A code example for that can be found [here](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-building/src/main/java/com/mapbox/mapboxsdk/plugins/building/BuildingPlugin.java#L76).

We are aware that current setup doesn't feel very natural for a developer and we are thinking of ways to improve the developer experience. Current thinking is that #9338 will resolve this as you would need to add sources and layers to the style object instead of MapboxMap.

Closing this issue as works as designed, please let us know if you have any additional questions!

**Closed** 2018-10-12 10:52 UTC
Labels: Android

**Comment by kjetila** [comment] 2018-10-12 10:57
@tobrun ok, thanks for letting me know, and also for the great work at this sdk. 

I will look into your example and keep an eye on the potential change :)
