### ISSUE TITLE
[iOS] maker image rendered incorrectly

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#4300] opened 2016-03-14 10:59 UTC
on iOS, master branch. Sometime a marker image is rendered totally incorrectly.
See image below.
![simulator screen shot 14 mars 2016 12 04 05](https://cloud.githubusercontent.com/assets/8179069/13742463/3256b4ce-e9dc-11e5-8fc2-396f17c2e58a.png)

**Comment by 1ec5** [comment] 2016-03-14 16:11
Duplicate of #4185.

**Closed by 1ec5** 2016-03-14 16:11 UTC
