### ISSUE TITLE
MGLCalloutView Drops when map is moved.

### ISSUE THREAD

**Issue by Neilfau** [mapbox/mapbox-gl-native#9780] opened 2017-08-16 09:03 UTC
Platfrom: iOS (Swift)
Mapbox SDK version: 3.6

Hi, I have a custom MGLCalloutView, when I tap on a MGLAnnotationView the callout appears as expected just above the annotation, but if I move the map slightly the callout moves slight and drops down covering the annotation. One the callout has dropped it does stay anchored to that point as you move the map.

 Ive implemented **isAnchoredToAnnotation**, I'm not sure if this a bug or Ive implemented something wrong. I noticed in the docs it says implement setCentre, so Ive set the centre in presentCallout

`self.center = CGPoint(x: frameWidth / 2, y: frameHeight / 2)`     
`self.isAnchoredToAnnotation = true`

**Comment by friedbunny** [comment] 2017-08-16 19:36
Thanks for the report — this looks like a duplicate of #9228.

**Closed by friedbunny** 2017-08-16 19:36 UTC
Labels: iOS, support
