### ISSUE TITLE
[Android] Polygon annotation alpha issue

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#8824] opened 2017-04-26 09:54 UTC
**Platform: Android**
**Mapbox SDK version: 5.0.2**

Using polygon annotation for display areas on a map, i found a strange behavior

### Steps to trigger behavior

 1. Add a symbol layer with an associated source
 2. Draw a polygon with alpha = 1 (or without setting the option)

![opacity1](https://cloud.githubusercontent.com/assets/8739777/25428525/6c5f5d66-2a76-11e7-95a3-62e68fef9d42.png)

The symbol appears above the polygon

3. Set the alpha to 0.9 (or anything not 1)

![opacity0_9](https://cloud.githubusercontent.com/assets/8739777/25428636/af94daac-2a76-11e7-928a-9b89b13f7463.png)

The symbol appears below the polygon

### Expected behavior

The order should be the same regardless the opacity.

### Actual behavior

Order different with different opacity.

**Comment by jfirebaugh** [comment] 2017-04-26 14:55
Duplicate of #8699.

**Closed by jfirebaugh** 2017-04-26 14:55 UTC
