### ISSUE TITLE
handlePartialTile

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#1679] opened 2015-06-03 08:18 UTC
````ruby
Thread : Crashed: Map
0  Embark                         0x00000001004b9018 std::__1::__function::__func<mbgl::Source::handlePartialTile(mbgl::TileID const&, mbgl::Worker&)::$_1, std::__1::allocator<mbgl::Source::handlePartialTile(mbgl::TileID const&, mbgl::Worker&)::$_1>, void ()>::operator()() (source.cpp:576)
1  Embark                         0x000000010051ad3c mbgl::util::RunLoop::process() (__split_buffer:76)
2  Embark                         0x000000010054d674 uv__async_event (async.c:80)
3  Embark                         0x000000010054da2c uv__async_io (async.c:156)
4  Embark                         0x0000000100557b84 uv__io_poll (kqueue.c:233)
5  Embark                         0x000000010054e00c uv_run (core.c:317)
6  Embark                         0x00000001004b1744 void mbgl::util::Thread<mbgl::MapContext>::run<std::__1::tuple<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>, 0ul, 1ul, 2ul>(std::__1::tuple<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul>) (thread.hpp:135)
7  Embark                         0x00000001004b166c std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::MapContext>::Thread<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mbgl::util::ThreadPriority, mbgl::View&&&, mbgl::FileSource&&&, mbgl::MapData&&&)::'lambda'()> >(void*, void*) (thread.hpp:113)
8  libsystem_pthread.dylib        0x00000001972b3dc8 _pthread_body + 164
9  libsystem_pthread.dylib        0x00000001972b3d24 _pthread_body + 158
10 libsystem_pthread.dylib        0x00000001972b0ef8 thread_start + 4
````

**Comment by tmpsantos** [comment] 2015-06-04 07:30
Hi @robipresotto, thanks for reporting the crash.

It seems to be on iOS, right? Do you have more information about how to reproduce it and what version of Mapbox GL was in use?

**Comment by robipresotto** [comment] 2015-06-04 08:47
Hello @tmpsantos :)
the version is: https://github.com/mapbox/mapbox-gl-native/commit/6e0c14e0f3
it is an live app, i will try catch more info for you soon...

**Comment by jfirebaugh** [comment] 2015-10-29 23:03
This is likely fixed in master.

**Closed by jfirebaugh** 2015-10-29 23:03 UTC
Labels: crash, iOS
