### ISSUE TITLE
Move compass view [iOS]

### ISSUE THREAD

**Issue by afomich** [mapbox/mapbox-gl-native#8005] opened 2017-02-09 14:08 UTC
Hello, is there possible to move compass view to another place?

**Comment by frederoni** [comment] 2017-02-09 14:19
This seems to be a duplicate of #8003 
The first option in https://github.com/mapbox/mapbox-gl-native/issues/8003#issuecomment-278644190 is not a possible fix for this issue, however, the second option would work.

Closing in favor of #8003

**Closed by frederoni** 2017-02-09 14:19 UTC

**Comment by mqln** [comment] 2017-06-14 19:10
I've actually found a nifty solution to adjust the top constraint in Swift 3.0.

```
    // var get set so that compass doesn't get change upon re-layout
    private var compassOriginY: CGFloat = 44

    override func updateConstraints() {
        super.updateConstraints()

        // Get constrait for the top edge
        for constraint in self.constraints where constraint.firstItem as? NSObject == self.compassView {

            constraint.constant = compassOriginY
        }
    }
```

Amazingly, you can access the trailing constraint (x axis) by changing constraint.firstItem to .secondItem too!

**Comment by tubipham** [comment] 2017-07-21 05:50
i should override viewDidLayoutSubviews() method and reset frame for compassView
ex:
`    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        var rect = self.mapView.compassView.frame
        rect.origin.y += 100
        self.mapView.compassView.frame = rect
    }`

**Comment by SantoshDhirwani** [comment] 2019-05-29 09:26
How can I move the compass in Android?

**Comment by gregoireLem** [comment] 2020-10-14 15:29
Howcan I change compassView bounds ?

**Comment by Tapestes** [comment] 2021-03-03 21:08
Is it just me, or did this stop working?  Fine for a long time for me, but now it wants to move the compass back to the default position.

**Comment by gregoireLem** [comment] 2021-03-19 15:25
@Tapestes same for me
