### ISSUE TITLE
[Android] app crashes with android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by amir169** [mapbox/mapbox-gl-native#13099] opened 2018-10-14 12:52 UTC
### Description

I simply use mapbox sdk as an android library and it crashes with Resource$NotFoundException.

The strange thing is that this appears only on certain devices. 
For example: Samsung GT-N7100

### Steps to reproduce
 1. Add `'com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.0'` to your gradle dependencies.
 2. Run a simple app with a simple map view.
 
Here's the full stack trace:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.company.myapplication.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
                      at android.app.ActivityThread.access$900(ActivityThread.java:175)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:146)
                      at android.app.ActivityThread.main(ActivityThread.java:5602)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                      at android.view.LayoutInflater.createView(LayoutInflater.java:626)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at com.company.myapplication.MainActivity.onCreate(MainActivity.java:31)
                      at android.app.Activity.performCreate(Activity.java:5451)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:146) 
                      at android.app.ActivityThread.main(ActivityThread.java:5602) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.constructNative(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:600)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                      at com.company.myapplication.MainActivity.onCreate(MainActivity.java:31) 
                      at android.app.Activity.performCreate(Activity.java:5451) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:146) 
                      at android.app.ActivityThread.main(ActivityThread.java:5602) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class ImageView
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:463)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
                      at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:138)
                      at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:108)
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                      at com.company.myapplication.MainActivity.onCreate(MainActivity.java:31) 
                      at android.app.Activity.performCreate(Activity.java:5451) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:146) 
                      at android.app.ActivityThread.main(ActivityThread.java:5602) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/mapbox_info_bg_selector.xml from drawable resource ID #0x7f060058
                      at android.content.res.Resources.loadDrawable(Resources.java:3422)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                      at android.widget.ImageView.<init>(ImageView.java:133)
                      at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:71)
                      at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:67)
                      at android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:181)
                      at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:105)
                      at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
                      at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:463) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                      at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:138) 
                      at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:108) 
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                      at com.company.myapplication.MainActivity.onCreate(MainActivity.java:31) 
                      at android.app.Activity.performCreate(Activity.java:5451) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:146) 
                      at android.app.ActivityThread.main(ActivityThread.java:5602) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/mapbox_info_icon_selected.xml from drawable resource ID #0x7f06005a
                  	at android
`
### Configuration

**Android versions:** 4.4.2
**Device models:** GT-N7100
**Mapbox SDK versions:** mapbox-android-sdk:6.6.0

Note that version 6.5.0 was OK.

**Comment by tobrun** [comment] 2018-10-15 09:57
@amir169 thank you for the report, will look into reproducing

**Comment by tobrun** [comment] 2018-10-17 05:08
This was fixed with #13144, I'm aiming doing a 6.6.1 patch release to address this sometime this week.
Thank you for the report @amir169

**Comment by vladzbuker** [comment] 2018-10-18 12:27
Nothing changed after updating mapbox SDK to 6.6.1. Why did you close the issue if it wasn't fixed?

**Comment by tobrun** [comment] 2018-10-18 12:39
Capturing from user who tested out this fix with the SNASPHOT and confirmed it was fixed with v6.6.1 and using AppCompatActivity with the following:

```groovy
    defaultConfig {
        vectorDrawables {
            useSupportLibrary true
        }
    }
```

**Comment by DonTomika** [comment] 2018-10-22 07:52
After some further testing it seems that both MapboxGLAndroidSDKTestApp and the Mapbox Android demo app are affected by this issue. Both of those apps crash on Android 4.x (tested on Android 4.1 – API level 16), despite having vectorDrawables.useSupportLibrary set to true in their app module's build.gradle file. Same results with both 6.6.0 and 6.6.1. Adding AppCompatDelegate.setCompatVectorFromResourcesEnabled(true) to their Application class fixes these crashes, but it might have unintended side effects as mentioned above.

I believe the simplest way of solving this would be to unset vectorDrawables.useSupportLibrary for MapboxGLAndroidSDK (as it was before #12786), so PNGs would be generated during build for older platforms. This would increase the size of the AAR by up to 50 kB, but would restore compatibility with Android 4.x without side effect.

I've opened a PR which does exactly this: #13144.

**Comment by DonTomika** [comment] 2018-10-22 08:45
After some further testing it seems that both MapboxGLAndroidSDKTestApp and the Mapbox Android demo app are affected by this issue. Both of those apps crash on Android 4.x (tested on Android 4.1 – API level 16), despite having vectorDrawables.useSupportLibrary set to true in their app module's build.gradle file. Same results with both 6.6.0 and 6.6.1. Adding AppCompatDelegate.setCompatVectorFromResourcesEnabled(true) to their Application class fixes these crashes, but it might have unintended side effects as mentioned above.

I believe the simplest way of solving this would be to unset vectorDrawables.useSupportLibrary for MapboxGLAndroidSDK (as it was before #12786), so PNGs would be generated during build for older platforms. This would increase the size of the AAR by up to 50 kB, but would restore compatibility with Android 4.x without side effect.

I've opened a PR which does exactly this: #13144.

**Comment by LukasPaczos** [comment] 2018-10-24 12:11
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/13168.

**Closed by LukasPaczos** 2018-10-24 12:11 UTC
Labels: Android
