### ISSUE TITLE
Tiles freeze when open app from background

### ISSUE THREAD

**Issue by PaulBoston** [mapbox/mapbox-gl-native#9254] opened 2017-06-13 15:50 UTC
Hello i use latest stable version of mapbox (5.0.2@aar) and have some bug.
when i open app from background my tiles freeze but markers moved by map move and perfectly work zoom. what is wrong?
 I initialized map like here https://www.mapbox.com/android-sdk/examples/ (A simple map view)
all life cycle include
Example of bug on gif - 

![ezgif-3-4c5ad9f181](https://user-images.githubusercontent.com/3361446/27091534-0f9f78a4-5069-11e7-9b8b-38814df1f897.gif)

**Comment by PaulBoston** [comment] 2017-06-14 07:49
If after that continue to use and try to press something that will drop with an error about a lack of memory

java.lang.OutOfMemoryError: Failed to allocate a 158412 byte allocation with 28592 free bytes and 27KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:728)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:653)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:633)
	at ru.mgp.map.google.GMapUtils.getViewBitmap(Unknown Source)
	at ru.mgp.map.data.Loader.getTSBitmapWithRotation(Unknown Source)
	at ru.mgp.map.data.Loader.AddTelemetryMarker(Unknown Source)
	at ru.mgp.map.data.Loader.-wrap1(Unknown Source)
	at ru.mgp.map.data.Loader$6.onResponse(Unknown Source)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5933)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:819)

**Comment by Guardiola31337** [comment] 2017-06-19 07:10
@PaulBoston thanks for reaching out and report your problem.

Do you have some more information on used Android OS or device?

**Comment by PaulBoston** [comment] 2017-06-19 11:44
@Guardiola31337  Hello it's reproduce on many devices.
We tested on devices, not younger than sdk 22, and on that list : 
-meizu m3 note
-meizu m5 note
- xiaomi redmi s3
- samsung s5
- lenovo a 1510
- nexus 5
- nexus 5x
- meizu mx4 pro
- htc desire 816
- samsung galaxy s6
and others...

It's bug Is associated with a lack of memory, as I suppose, because it happens when you exit from the background, according to the android logs there is not anything similar

**Comment by Guardiola31337** [comment] 2017-06-19 13:14
@PaulBoston thanks a lot for the detailed info.

> Hello it's reproduce on many devices

What about different versions of the OS? Is this happening using different Android SDK versions?

I'm asking because OP issue seems really similar to #9299 and it only happens on Galaxy S6 Edge (G925F) with OS 5.1.1
Could you confirm? Thanks again!

**Comment by PaulBoston** [comment] 2017-06-19 13:18
@Guardiola31337 This is not related to the version of the android, it is also reproduced on the 5th, 6th and 7th versions

**Comment by Guardiola31337** [comment] 2017-06-19 13:57
@PaulBoston in that case, would you be able to retest this with the latest version `5.1.0-beta.4`? I wasn't able to reproduce the issue described in OP. 

Do you have a minimal example to reproduce it? If there is any sample or pseudo code you can provide, that would also be really helpful.

Thanks.

**Comment by PaulBoston** [comment] 2017-06-19 16:14
@Guardiola31337 Unfortunately, I can not give an example.
Using the 4 beta version, I started to fall with an error on the location manager, removing it from the project, continued to patch with a fatal error
A / libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 6860 (en.mosgorpass)

**Comment by Guardiola31337** [comment] 2017-06-19 16:56
@PaulBoston 
> Using the 4 beta version, I started to fall with an error on the location manager, removing it from the project, continued to patch with a fatal error
> A / libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 6860 (ru.mosgorpass)

I'm not following, what do you mean? Do you still experience OP issue?
Could you please supply more information, such as an extended crash log with the backtrace?

**Comment by PaulBoston** [comment] 2017-06-20 08:31
Sorry for my English.
When i change version to beta 4 , app started to fall with error instead OP issue.


`06-20 11:30:35.938 30348-30348/ru.mosgorpass E/RoutesManager: BuildOnWayMarkersAndPolylines
06-20 11:30:35.938 30348-30348/ru.mosgorpass E/RoutesManager: BuildOnWayMarkersAndPolylines: removePolylines
06-20 11:30:35.938 30348-30348/ru.mosgorpass E/RoutesManager: removePolylines: 
06-20 11:30:35.940 30348-30348/ru.mosgorpass E/RoutesManager: BuildOnWayMarkersAndPolylines: RemoveRouteMarkers
06-20 11:30:35.940 30348-30348/ru.mosgorpass W/RoutesManager: BuildFootPolylines-1
06-20 11:30:35.940 30348-30348/ru.mosgorpass W/RoutesManager: BuildFootPolylines
06-20 11:30:35.941 30348-30348/ru.mosgorpass A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 30348 (ru.mosgorpass)
06-20 11:30:38.714 30383-30391/ru.mosgorpass:Metrica I/System: FinalizerDaemon: finalize objects = 52
06-20 11:30:42.501 30479-30489/ru.mosgorpass:lost I/System: FinalizerDaemon: finalize objects = 56`

**Comment by Guardiola31337** [comment] 2017-06-20 09:11
@PaulBoston that seems a different issue. Could you open a new ticket, please?

I'm not seeing how the OP issue is actionable. Without having additional information, I'm unable to reproduce. Going to close this until more information is provided.

**Closed by Guardiola31337** 2017-06-20 09:11 UTC
Labels: Android, needs information

**Comment by Agisight** [comment] 2019-09-06 09:04
I have got same issue in iOS. All tiles sometimes become freezed after showing UIView above the map. Does anybody solved it?
