### ISSUE TITLE
Crash on open close different MapView

### ISSUE THREAD

**Issue by evgzor** [mapbox/mapbox-gl-native#9096] opened 2017-05-24 06:15 UTC
**iOS 10.3.2**
**v3.6.0-beta.1**

### Steps to trigger behavior

 1. Open MGLMapview with multiple annotations
 2. Close MapView with multiple annotations
 3. Open  another MGLMapview with multiple annotations

### Expected behavior
No crash observed
### Actual behavior
Crash observed like: 
<img width="1399" alt="screenshot 2017-05-24 09 06 47" src="https://cloud.githubusercontent.com/assets/5227456/26389136/0084feec-4061-11e7-8d74-a9f14c3bbecb.png">
and: 
<img width="1397" alt="screenshot 2017-05-24 10 48 48" src="https://cloud.githubusercontent.com/assets/5227456/26392338/eb01326c-406e-11e7-90db-b71243748a31.png">

and crash log: [crash.crash.zip](https://github.com/mapbox/mapbox-gl-native/files/1024548/crash.crash.zip)

In previous version 3.5.4 - no crash observed with same scenario

**Comment by boundsj** [comment] 2017-05-24 15:06
@evgzor from what I can tell, the crash report you attached to not implicate the Mapbox SDK. Can you please provide a sample project or code in a gist that would allow us to reproduce this?

**Comment by evgzor** [comment] 2017-05-24 18:42
Dear @boundsj this behavior is easily reproducible on yours ios-sdk examples. If u want I can attach video.

**Comment by jmkiley** [comment] 2017-05-24 23:29
Hi @evgzor,

I was able to repro this issue in `ios-sdk-examples` using `v3.6.0-beta.1`. The issue seems to have been introduced in that version, as I am not seeing it with previous versions. 

Looks like it may have been introduced with #7716 Will look more into this!

**Comment by incanus** [comment] 2017-05-25 17:53
@jmkiley and I found that the unregistering of `bounds` observation happening in `-[MGLMapView dealloc]` as part of #7716 is too late in the lifecycle—as is `-removeFromSuperview`. Both occasions are too late in the breakdown cycle to have properly unregistered the observation.

**Comment by incanus** [comment] 2017-05-25 17:56
@frederoni It also seems to be the case that if we (the `MGLMapView`) were moved between view controllers, we don't pay attention to that view controller's lifecycle to know to unregister observing its layout guides (say, during a `UIViewAnimationTransition` between view controllers). So we'd be in a new view controller but still paying attention to the layout guides from the first one.

**Comment by incanus** [comment] 2017-05-25 18:00
> properly unregistered the observation

To be clear, the crash is an unhandled exception related to the view controller layout guides going away before we unregister observing the layout guides' `bounds`.

**Comment by jmkiley** [comment] 2017-05-25 18:02
Noting that this crash seems to happen regardless of whether or not there are annotations or a nav bar. @incanus was able to reproduce with a clean `MGLMapView` in `iosapp`. 

My next steps are to look more into the `UIView` lifecycle to identify where the crash is happening.

Including the message from `ios-sdk-examples` for searchability:
```
2017-05-25 10:35:34.033 Examples[26372:856825] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x6000001b5d20 of class _UILayoutSpacer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x600000430880> (
<NSKeyValueObservance 0x600000254d30: Observer: 0x7fb107857c00, Key path: bounds, Options: <New: NO, Old: NO, Prior: NO> Context: 0x10879ac90, Property: 0x600000254d60>
```

**Comment by incanus** [comment] 2017-05-25 18:06
>  a clean `MGLMapView` in `iosapp`

https://github.com/mapbox/mapbox-gl-native/commit/537355e16da43f38c3678b72d4bc265cf2883753

**Comment by frederoni** [comment] 2017-05-25 19:14
> To be clear, the crash is an unhandled exception related to the view controller layout guides going away before we unregister observing the layout guides' bounds.

This seems to be correct. _UILayoutSpacer is deallocated before MGLMapView is. I think we can solve this by overriding `-[MGLMapView willMoveToWindow:]` and remove observers when window is nil.

> we don't pay attention to that view controller's lifecycle to know to unregister observing its layout guides (say, during a UIViewAnimationTransition between view controllers).

Good point. This should work with the willMoveToWindow fix mentioned aboved.

**Comment by boundsj** [comment] 2017-05-30 20:49
This was fixed by https://github.com/mapbox/mapbox-gl-native/pull/9109 on the `release-ios-v3.6.0-android-v5.1.0` branch.

**Closed by boundsj** 2017-05-30 20:49 UTC
Labels: annotations, beta blocker, crash, iOS, needs information

**Comment by evgzor** [comment] 2017-05-31 06:00
It's ios issue. How it's can be close as Android issue?

**Comment by frederoni** [comment] 2017-05-31 09:41
@evgzor if you are referring to the branch name, iOS and Android share a release branch. However, this issue only affects iOS.

**Comment by evgzor** [comment] 2017-05-31 09:47
when 3.6.0 would be released for checking fix?

**Comment by frederoni** [comment] 2017-05-31 09:50
3.6.0-beta.2 is just around the corner. Perhaps at the end of this week.

**Comment by boundsj** [comment] 2017-05-31 15:31
@evgzor 3.6.0-beta.2 should be published a few hours from now.
