### ISSUE TITLE
IOS : Offline maps do not display correctly

### ISSUE THREAD

**Issue by yueno12** [mapbox/mapbox-gl-native#9741] opened 2017-08-09 23:42 UTC
**Platform:iOS**
**Mapbox SDK version:3.6.1**

### Steps to trigger behavior

 1. Download the map.
Map style uses this
`{
    "layers": [
        {
            "id": "baseLayer", 
            "paint": {
                "raster-fade-duration": 0
            }, 
            "source": "baseLayer", 
            "type": "raster"
        }, 
        {
            "id": "colorLayer", 
            "paint": {
                "raster-fade-duration": 0, 
                "raster-opacity": 0.2
            }, 
            "source": "colorLayer", 
            "type": "raster"
        }
    ], 
    "name": "Raster Tiles", 
    "sources": {
        "baseLayer": {
            "tileSize": 256, 
            "tiles": [
                "https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png"
            ], 
            "type": "raster"
        }, 
        "colorLayer": {
            "tileSize": 256, 
            "tiles": [
                "http://cyberjapandata.gsi.go.jp/xyz/relief/{z}/{x}/{y}.png"
            ], 
            "type": "raster"
        }
    }, 
    "version": 8
}`

 2. Turn on iphone's airplane mode.
 3. Then Offline maps do not display correctly.

### Expected behavior

I have checked the same scenario using the older SDK v3.5.4, it's working there.

Offline Map by Mapbox iOS SDK v3.5.4 
https://youtu.be/6Xlk_-pMiYU 

### Actual behavior

Offline Map by Mapbox iOS SDK v3.6.1 
https://youtu.be/imZFB_vEl6Q

**Comment by kkaefer** [comment] 2017-08-10 14:05
Thank you for reporting this issue. I It looks like this is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/9563. Please follow issue resolution on that ticket.

**Closed by kkaefer** 2017-08-10 14:05 UTC
Labels: bug, Core, offline
