### ISSUE TITLE
Visual artifact of Marker still rendered on map when removed for a 2nd time (Android)

### ISSUE THREAD

**Issue by damianflannery** [mapbox/mapbox-gl-native#6208] opened 2016-08-30 14:37 UTC
I have a toggle feature to show/hide groups of markers on a map (iterating each list and making add/remove calls to MapboxMap). I have noticed that I can add and remove markers once without issue however after adding markers the 2nd time then the artifact of the marker is rendered on the map forevermore (even though you cannot click on the marker to get an infowindow etc).

**Platform:**
Android 6.0.1 (Nexus 5X) 

**Mapbox SDK version:**
4.2.0 beta2

### Steps to trigger behavior

```
Marker marker = mMapboxMap.addMarker(getMarkerOpt());
mMapboxMap.removeMarker(marker);
Marker marker2 = mMapboxMap.addMarker(getMarkerOpt());
mMapboxMap.removeMarker(marker2);
```

```
private MarkerOptions getMarkerOpt() {
return new MarkerOptions()
                                    .position(latLng)
                                    .title(name)
                                    .snippet(type + " " + subcat)
                                    .icon(poi.icon);
}
```

### Expected behavior
I would expect the marker icon to be removed from the map each time I call remove marker

### Actual behavior
Only first call to remove marker actually removes the rendered marker from the map. 
N.B. The act of adding / removing the marker technically works i.e. if I call remove for a 2nd time then I can no longer click on the marker to show the info window

**Comment by sddamico** [comment] 2016-08-30 15:15
Possible dupe of https://github.com/mapbox/mapbox-gl-native/issues/5915

**Comment by tobrun** [comment] 2016-09-12 20:34
Been trying to reproduce this issue with code shown in this [gist](https://gist.github.com/tobrun/ed2a77cc973a54b15e16d268b93958c8) but unable to reproduce. Going to look at @sddamico reported issue and see if that reproduces the issue.

**Comment by tobrun** [comment] 2016-09-12 23:04
I migrated the code from #5915 and this resulted in:

![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/2151639/18455907/d68bf0f4-7901-11e6-8ca0-ebc77d28552b.gif)

I added some debug loggings to `AnnotationManager` and could see this:

```java
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAndAdd: 0 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 0 
{pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 0 
{pboxsdk.testapp}[JNI]: DEBUGLOG Marker has been added in core with 0
{pboxsdk.testapp}[JNI]: DEBUGLOG Going to remove Marker in 0
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 0 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAndAdd: 1 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 1 
{pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 1 
{pboxsdk.testapp}[JNI]: DEBUGLOG Marker has been added in core with 1
{pboxsdk.testapp}[JNI]: DEBUGLOG Going to remove Marker in 1
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 1 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAndAdd: 0 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 0 
{pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 0 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAndAdd: 2 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 2 
{pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 2 
{pboxsdk.testapp}[JNI]: DEBUGLOG Marker has been added in core with 2
{pboxsdk.testapp}[JNI]: DEBUGLOG Going to remove Marker in 2
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 2 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAndAdd: 1 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 1 
{pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 1 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAndAdd: 3 
{pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 3 
{pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 3 
{pboxsdk.testapp}[JNI]: DEBUGLOG Marker has been added in core with 3
```

We should only be able to see 1 removeAndAdd call but we are seeing 2.

**Comment by tobrun** [comment] 2016-09-12 23:49
I added logging on the size of symbolAnnotations and it seems it only grows in size while it should remain one. @jfirebaugh can you think of any reason why `erase`  is not actually removing the annotation? or is something else not correct?

**Comment by jfirebaugh** [comment] 2016-09-12 23:58
Can you post the code?

**Comment by tobrun** [comment] 2016-09-13 00:11
Pushed the branch [here](https://github.com/mapbox/mapbox-gl-native/tree/6208-add-remove-annotations)

**Comment by jfirebaugh** [comment] 2016-09-13 00:39
Why is `AnnotationManager::removeAndAdd` getting called? Something must be calling `AnnotationManager::updateAnnotation`.

**Comment by tobrun** [comment] 2016-09-13 01:15
The updateAnnotation was definitely wrong but still seeing the same behaviour:

```java
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 0 
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG Size symbolAnnotations: 1 
D/mbgl: {pboxsdk.testapp}[JNI]: DEBUGLOG Marker has been added in core with 0
D/mbgl: {pboxsdk.testapp}[JNI]: DEBUGLOG Going to remove Marker in 0
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 0 
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 1 
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG Size symbolAnnotations: 1 
D/mbgl: {pboxsdk.testapp}[JNI]: DEBUGLOG Marker has been added in core with 1
D/mbgl: {pboxsdk.testapp}[JNI]: DEBUGLOG Going to remove Marker in 1
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 1 
**I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 0 **
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG Size symbolAnnotations: 1 
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 2 
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG Size symbolAnnotations: 2 
D/mbgl: {pboxsdk.testapp}[JNI]: DEBUGLOG Marker has been added in core with 2
D/mbgl: {pboxsdk.testapp}[JNI]: DEBUGLOG Going to remove Marker in 2
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG RemoveAnnotation: 2 
**I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 1 **
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG Size symbolAnnotations: 2 
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG addAnnotation: 3 
I/mbgl: {pboxsdk.testapp}[General]: DEBUGLOG Size symbolAnnotations: 3 
D/mbgl: {pboxsdk.testapp}[JNI]: DEBUGLOG Marker has been added in core with 3
```

**Comment by tobrun** [comment] 2016-09-13 01:25
I was able to pinpoint it, Going to clean it up and PR it.

**Closed** 2016-09-20 01:03 UTC
Labels: Android, gl-school
