### ISSUE TITLE
Wrong cached tiles on some zoomlevels

### ISSUE THREAD

**Issue by ohlsont** [mapbox/mapbox-gl-native#4798] opened 2016-04-22 13:03 UTC
*_Platform: iOS
*_Mapbox SDK version: 3.2
### Steps to trigger behavior

Can't reproduce consistently, happens 1/50 times or something.
1. Change style (deinit the mapview and make a new mapview)
2. Zoom in
### Expected behavior

The new style with new tiles is applied at all zoom levels
### Actual behavior

The new tiles is visible at lower zoomlevels, probably because no cached tiles exists there
![image](https://cloud.githubusercontent.com/assets/3426061/14742164/fc961ff4-089a-11e6-9ff5-0fe4ed80c638.png)

![image](https://cloud.githubusercontent.com/assets/3426061/14742146/f334af20-089a-11e6-9c36-daf7ae990e3e.png)

![image](https://cloud.githubusercontent.com/assets/3426061/14742139/eb4d42ae-089a-11e6-89b5-9e8616703ae1.png)

**Comment by 1ec5** [comment] 2016-04-22 14:57
This looks like the Android SDK v4.0.0, is that correct?

**Comment by hinken** [comment] 2016-04-25 09:27
nope iOS

**Comment by 1ec5** [comment] 2016-04-25 14:36
Ah, thanks for clarifying. When you say "change style", does that mean you're using a different style URL at this point, or that you've modified the style itself, for instance by editing it in Studio?

**Comment by hinken** [comment] 2016-04-25 15:11
Yep both, basically using the same style (different url) but with a different tileset coded into the style.

**Comment by 1ec5** [comment] 2016-04-25 15:18
Can you provide the style URLs you're using, as well as the tile IDs? (You can turn on tile IDs by setting the map view's debugMask.)

**Comment by hinken** [comment] 2016-05-16 07:28
Sorry for slow response:
Style id: cimvsumnn00go9wnj7rpam9t4
tileset: trueflow.venue-5-context-23648-floor-1 and trueflow.venue-5-context-23648-floor-2

**Comment by friedbunny** [comment] 2017-03-10 03:12
Closing as unreproducible — please feel free to post more information and we’ll reinvestigate.

**Closed by friedbunny** 2017-03-10 03:12 UTC
