### ISSUE TITLE
Crash MapBox on selecting multiple annotations.

### ISSUE THREAD

**Issue by evgzor** [mapbox/mapbox-gl-native#9066] opened 2017-05-22 08:17 UTC
**Platform: iOS**
**Mapbox SDK version: 3.5.4**

### Steps to trigger behavior

 1. Load map with multiple annotations
 2. call asynchronous remove and add Annotation in race conditions
 3. Observe the result

### Expected behavior
No crash delegate method was called susesfully
### Actual behavior
Crash with: 
<img width="1399" alt="screenshot 2017-05-22 11 10 04" src="https://cloud.githubusercontent.com/assets/5227456/26298249/3fe0c7b6-3edf-11e7-8f7b-b7c5864d2b10.png">
As was mention in https://github.com/mapbox/mapbox-gl-native/issues/8163
if disable all removeAnnotations functions the crash does not happend anymore.

**Comment by boundsj** [comment] 2017-05-24 01:23
Hi @evgzor. The problem you are describing sounds a lot like the issue caused by https://github.com/mapbox/mapbox-gl-native/issues/8754. That was fixed by https://github.com/mapbox/mapbox-gl-native/pull/9025 and that fix was just published in https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.0-beta.1.

Can you please test using `ios-v3.6.0-beta.1` and see if it fixes the issue you see?

I'm going to close this issue now but please reopen it if you can reproduce with that latest beta. If you do reopen this, please attach an actual crash report / trace file instead of the assembly view screenshot from Xcode. Also, if you have a gist or sample project that can reproduce the issue please feel free to attach it.

**Closed by boundsj** 2017-05-24 01:23 UTC
Labels: annotations, crash, iOS

**Comment by evgzor** [comment] 2017-05-24 06:21
Hi @boundsj it's true that current issue is not reproducible anymore on https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.0-beta.1. But I got another crash on 3.6.0-beta1 version: https://github.com/mapbox/mapbox-gl-native/issues/9096. Also, u changed API and now for draggable annotation in swift it requires implementing "init(annotation: MGLAnnotation?, reuseIdentifier: String?)" which is a bit strange.

**Comment by boundsj** [comment] 2017-05-25 04:09
> Also, u changed API and now for draggable annotation in swift it requires implementing "init(annotation: MGLAnnotation?, reuseIdentifier: String?)" which is a bit strange.

Thanks for noting this issue! It is fixed by https://github.com/mapbox/mapbox-gl-native/pull/9104 on the `release-ios-v3.6.0-android-v5.1.0` branch and the fix will be in the next pre-release of v3.6.0.

**Comment by evgzor** [comment] 2017-05-25 10:15
For the people who still in use 3.5 version u may temporarily fix it by 
**self.view(for: annotation)?.frame = CGRect(x: 0, y: 0, width: 0, height: 0)
        self.removeAnnotation(annotation)**
