### ISSUE TITLE
Flickers marker, when other MarkerView animated

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#6422] opened 2016-09-22 04:42 UTC
**Platform:** Android (Nexus 4, Android 5.1)
**Mapbox SDK version:** 4.2.0-beta3

Marker added through MarkerOptions flickers, when other MarkerView animated. 
### Steps to trigger behavior
1. https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/OffRouteActivity.java
2. 

change: `destinationMarker = map.addMarker(new MarkerViewOptions().position(point));`

to: `destinationMarker = map.addMarker(new MarkerOptions().position(point));`

4.2.0-beta2 does not have this problem.

**Comment by cammace** [comment] 2016-09-22 19:21
![ezgif com-video-to-gif 6](https://cloud.githubusercontent.com/assets/5652865/18762687/dd1868b6-80d7-11e6-9ea0-0ffd3f13aee3.gif)

Was able to reproduce on a Nexus 5x and will look more into this. Is there a paticuiliar reason for switching the `detinationMarker`? I recommend using Marker Views in almost all cases now unless you have an abundant amount of markers on your map and don't need the additional customization that comes with marker views.

cc: @tobrun @zugaldia

**Comment by klblk** [comment] 2016-09-23 02:23
I add over 1000 static markers through MapboxMap.addMarkers() in my project. MapboxMap.addMarkerViews() slowly and map freezin (with 1000 MarkerView).

**Comment by tobrun** [comment] 2016-09-23 05:55
Going to do some debugging to see what the cause is of this issue.

**Comment by tobrun** [comment] 2016-09-23 12:04
I have tried bisecting this 3 times but always ending up on a different commit 😅

**Comment by cammace** [comment] 2016-11-16 14:05
Not seeing this issue anymore in the Android SDK. 

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/5652865/20350163/0bd50eb4-ac0e-11e6-847f-007266d8bb4d.gif)

Closing

**Closed by cammace** 2016-11-16 14:05 UTC
Labels: Android

**Comment by klblk** [comment] 2016-11-17 07:11
Reproduce on 4.2.0-beta.5
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
passengerMarker created from MarkerViewOptions (not MarkerOptions)
