### ISSUE TITLE
[macos] Moving map to a screen with a different pixel density crashes

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/mapbox-gl-native#7857] opened 2017-01-25 16:42 UTC
**Platform:** MacOS
**Mapbox SDK version:** Master @ 164d156ccd67b14977431fb4919d9a8584765b2a
**Hardware:** iMac (Retina 5K, 27-inch, Late 2014), with 2 additional non-retina screens

### Steps to trigger behavior

 1. Run macosapp target on a retina screen
 2. Move window to a non-retina screen

### Expected behavior
Map stays functional

### Actual behavior
Application crashes with error. `libc++abi.dylib: terminating with uncaught exception of type mbgl::gl::Error: glUseProgram(value): Error GL_INVALID_VALUE at /Users/jesse/projects/mapbox-gl-native/src/mbgl/gl/value.cpp:223`

**Comment by jfirebaugh** [comment] 2017-01-25 17:28
Duplicate of #6654.

**Closed by jfirebaugh** 2017-01-25 17:28 UTC
