### ISSUE TITLE
Unable to cache tiles after offline region merge

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#13509] opened 2018-12-05 11:39 UTC
After a successful sideload of a database created with the `mbgl-offline` we are unable to cache any more tiles. The data is correctly downloaded and displayed, but hits:
```
V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
I/Mbgl: {DefaultFileSour}[Database]: Unable to make space for entry
V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
I/Mbgl: {DefaultFileSour}[Database]: Unable to make space for entry
I/Mbgl: {DefaultFileSour}[Database]: Unable to make space for entry
V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
I/Mbgl: {DefaultFileSour}[Database]: Unable to make space for entry
I/Mbgl: {DefaultFileSour}[Database]: Unable to make space for entry
V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
I/Mbgl: {DefaultFileSour}[Database]: Unable to make space for entry
I/Mbgl: {DefaultFileSour}[Database]: Unable to make space for entry
D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
I/Mbgl: {DefaultFileSour}[Database]: Unable to make space for entry
```

![ezgif com-video-to-gif 24](https://user-images.githubusercontent.com/16925074/49510505-b6bed300-f888-11e8-8dba-989cc2514314.gif)

Notes:
 - Sideloaded region is still displayed correctly. 
 - The issue is not caused by the [test database](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/assets/offline.db), only by the ones created with the `mbgl-offline`.
 - The issue can be reproduced on [the test branch](https://github.com/mapbox/mapbox-gl-native/compare/lp-sideload-cache).

/cc @asheemmamoowala

**Comment by asheemmamoowala** [comment] 2018-12-07 22:48
Duplicate of #4411

**Closed by asheemmamoowala** 2018-12-07 22:48 UTC
Labels: Core, offline
