### ISSUE TITLE
reposition map on iOS to properly show callouts

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#5769] opened 2016-07-22 22:12 UTC
Lost from the raster version is `SMCalloutView`'s ability to reposition the map slightly between annotation selection time and callout presentation time. Without this, tapping or selection an annotation near the map edge could cut off the callout. 

<img width="578" alt="screen shot 2016-07-22 at 3 10 33 pm" src="https://cloud.githubusercontent.com/assets/17722/17072600/740f56c0-501e-11e6-9cc5-bcacd177e854.png">

What should happen is the map should pan slightly automatically, then present the callout. 

The relevant API in the old SDK's callout is [here](https://github.com/nfarina/calloutview/blob/2ee6b8110eb738e88a0c38b0cc2507ee2205d67a/SMCalloutView.h#L185). 

Related: https://github.com/mapbox/mapbox-gl-native/pull/2412 https://github.com/mapbox/mapbox-gl-native/issues/3154

**Comment by 1ec5** [comment] 2016-07-22 23:53
Duplicate of #3249.

**Closed by 1ec5** 2016-07-22 23:53 UTC
Labels: feature, iOS, parity
