### ISSUE TITLE
Allow iOS developers to clear all tile and style caches

### ISSUE THREAD

**Issue by hastiranjkesh** [mapbox/mapbox-gl-native#13979] opened 2019-02-23 10:40 UTC
I use Mapbox SDK for my iOS app to display map and road traffic. When map style and tiles change on the server side, my app still displays cached data. I'm finding that when a tileset is updated, my iOS client is still holding onto the previous tiles. Previously cached tiles still show the old data. Is it possible to clear Mapbox cached data?

**Mapbox SDK versions: 4.7.1** 
**Mapbox Naviagtion SDK version: 0.28.0**
**Xcode version: 10.1**

**Comment by jmkiley** [comment] 2019-02-27 20:05
Hello @hastiranjkesh -

Thank you for using Mapbox! It looks like this is a duplicate of #4376.

**Closed by jmkiley** 2019-02-27 20:05 UTC
