### ISSUE TITLE
User location annotation callout crash in v3.5.1

### ISSUE THREAD

**Issue by lopemac** [mapbox/mapbox-gl-native#8674] opened 2017-04-07 05:01 UTC
I'm experiencing an immediate crash when displaying the current location circle label. If the map moves automatically or is moved or tapped in any way while the "You Are Here" default label is showing, the app immediately crashes. My app is using the latest Xcode and Mapbox SDK. I did not experience this behavior with SDK v3.5. When I downgrade back to v3.5, no crash occurs and the map can be moved as normal. I'm displaying the map in a rounded square view and am using these settings in the code under viewDidLoad:

```
mapinView.tintColor = .darkGray
mapinView.delegate = self
view.addSubview(mapinView)
self.view.addSubview(resetShadow) //used to show location button on top of map
mapinView.layer.cornerRadius = 20
```

I'm using "mapbox://styles/mapbox/light-v9" in the Style URL settings box. I'm also using the clustering code from the mapbox example page which shows labels without any issues or crashing.

Platform: iOS Swift 3.1 Xcode 8.3.1 running on iPhone 6 10.3.1 and iPhone 5 10.3
Mapbox SDK version: v3.5.1

Error Code from Xcode: 
```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found
(lldb)
```

### Steps to trigger behavior

 1. Zoom into current location or scroll to show current location
 2. Press on my location circle to get default pop up label that says "You Are Here"
 3. Move map around or tap anywhere while label is still showing

### Expected behavior
It should let you scroll map or tap anywhere without any abnormal behavior

### Actual behavior
It immediately crashes following the steps above.

![simulator screen shot apr 6 2017 6 50 01 pm](https://cloud.githubusercontent.com/assets/18113616/24786203/41438f38-1afb-11e7-8c42-542e4c3fb12e.png)

**Comment by friedbunny** [comment] 2017-04-07 05:40
Thanks for the report and clear reproduction steps, @lopemac. Here’s the error message associated with this crash:

```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found
```

This would seem to implicate https://github.com/mapbox/mapbox-gl-native/pull/8637, but there were a few other annotation-related changes in v3.5.1.

/cc @1ec5 @boundsj @fabian-guerra

**Comment by friedbunny** [comment] 2017-04-07 06:11
@1ec5 This crash did bisect to https://github.com/mapbox/mapbox-gl-native/pull/8637 for me.

**Comment by 1ec5** [comment] 2017-04-07 14:37
Looks like #8637 caught a real bug that was inserting bogus values into `_annotationContextsByAnnotationTag`.

**Comment by boundsj** [comment] 2017-04-07 22:24
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/8686 on the `release-ios-v3.5.0-android-v5.0.0` branch

**Closed by boundsj** 2017-04-07 22:24 UTC
Labels: crash, iOS
