### ISSUE TITLE
MGLMapCamera(lookingAtCenter:, fromDistance:, pitch:, heading:) is not respecting content insets properly. 

### ISSUE THREAD

**Issue by Gerungofulus** [mapbox/mapbox-gl-native#12728] opened 2018-08-23 18:21 UTC
### Steps to reproduce

 1. Set the content insets with a high (but not invalid) right inset. I tested it with a right inset of 370 in landscape mode.
 2. Use MGLMapCamera(lookingAtCenter:, fromDistance:, pitch:, heading:) to create a new camera looking at some coordinate. I used distance 1840, pitch 60, heading 184. 
 3. Call `fly(to: newCamera, withDuration: 1.25, completionHandler: nil)` with the new camera

### Expected behavior

- [x] The center coordinate is located in the center of the area of the view minus the insets
- [x] The pitch is set correctly
- [x] The distance is set correctly
- [ ] A marker oriented into a special direction put right at the center coordinate should point up. In other words: The vanishing point should be located right above the new center coordinate, but it is still located in the center of the view, even though the content insets are set properly. (please see the image below. I also added text to the two crosses)

### Configuration

**Mapbox SDK versions:** 
4.2.0
**iOS/macOS versions:** 
11.4.1 (15G77)
**Device/simulator models:**
iPhone 6s+ in Landscape
**Xcode version:** 
9.4.1 (9F2000)
![img_02c88c9455d2-1](https://user-images.githubusercontent.com/9848525/44544264-fe728200-a711-11e8-8220-7b5c938744d7.jpeg)

**Comment by 1ec5** [comment] 2018-09-13 06:34
`fly(to:withDuration:completionHandler:)` does seem to apply the content insets:

https://github.com/mapbox/mapbox-gl-native/blob/f1aa8696f6064923b01d34068176505847fa3157/platform/macos/src/MGLMapView.mm#L1205 https://github.com/mapbox/mapbox-gl-native/blob/f1aa8696f6064923b01d34068176505847fa3157/platform/macos/src/MGLMapView.mm#L1215-L1215 https://github.com/mapbox/mapbox-gl-native/blob/f1aa8696f6064923b01d34068176505847fa3157/src/mbgl/map/transform.cpp#L182-L183

However, I think the problem you’ve identified is that the vanishing point is always located at the center-top of the view. Core GL doesn’t offer any way to move the vanishing point; ultimately, edge insets are implemented by changing the frame of reference for a center coordinate.

/cc @ansis @brunoabinader

**Comment by 1ec5** [comment] 2018-09-13 06:50
A rather unsatisfying workaround would be to extend the map view further to the left, beyond the left edge of the containing view, until the vanishing point shifts sufficiently to the left.

**Comment by 1ec5** [comment] 2019-03-22 17:55
> In cases where the panel is translucent or doesn’t extend to the top and bottom edges of the window, a rather unsatisfying workaround would be to extend the map view further to the left, beyond the left edge of the containing view, until the vanishing point shifts sufficiently to the left.

This is the rather unsatisfying workaround we’ve settled on in the navigation SDK’s CarPlay integration.

> However, I think the problem you’ve identified is that the vanishing point is always located at the center-top of the view. Core GL doesn’t offer any way to move the vanishing point; ultimately, edge insets are implemented by changing the frame of reference for a center coordinate.

Configuring the vanishing point is an important feature for navigation use cases. It’s common for landscape layouts to overlay a large sidebar that doesn’t completely obscure the map but does shift the horizontal center visually.

**Comment by astojilj** [comment] 2019-05-23 06:32
> > In cases where the panel is translucent or doesn’t extend to the top and bottom edges of the window, a rather unsatisfying workaround would be to extend the map view further to the left, beyond the left edge of the containing view, until the vanishing point shifts sufficiently to the left.
> 
> This is the rather unsatisfying workaround we’ve settled on in the navigation SDK’s CarPlay integration: [mapbox/mapbox-navigation-ios#1845](https://github.com/mapbox/mapbox-navigation-ios/pull/1845).
> 

This is fixed in #14664.
It's waiting for review.
Note that current "workaround" should keep functioning as intended after the PR #14664 lands - if navigation-ios is just enlarging the view and offsetting it. 
If [MGLMapView.contentInset](https://docs.mapbox.com/ios/api/maps/5.0.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)contentInset) is specified, center of perspective, and the user puck, will always be centered in the center of content area specified by contentInset; vanishing point would be above it.

**Closed** 2019-05-28 11:38 UTC
Labels: Core, bug, navigation
