### ISSUE TITLE
Thread 1 BAD ACCESS Crash when run on device iOS 9.1

### ISSUE THREAD

**Issue by foffer** [mapbox/mapbox-gl-native#3167] opened 2015-12-02 13:32 UTC
I get a pretty nonsensical crash when I run my app on my device (no crash in the simulator). I'm using the latest SDK version and running iOS 9.1.

Below screenshot shows the error I get, although it doesn't tell you much. I'd be happy to provide more info if instructed how to do so

<img width="2250" alt="screen shot 2015-12-02 at 13 30 28" src="https://cloud.githubusercontent.com/assets/1674650/11532039/ff80ad4a-98f8-11e5-98a9-a25118a7fe29.png">

**Comment by foffer** [comment] 2015-12-02 14:08
Adding the framework manually seems to work fine. Would this have something to do with not adding the frameworks listed under https://www.mapbox.com/ios-sdk/#binary when installing via cocoapods?

**Comment by jfirebaugh** [comment] 2015-12-02 15:43
Duplicate of #3112.

**Closed by jfirebaugh** 2015-12-02 15:43 UTC
