### ISSUE TITLE
Missing labels at tile borders

### ISSUE THREAD

**Issue by pbnsilva** [mapbox/mapbox-gl-native#12763] opened 2018-08-29 07:31 UTC
Hello, I'm using `node-mapbox-gl-native` to request tiles using a custom style. However, in some tiles, labels are not drawn at the borders.
  
I'm running `node-mapbox-gl-native` version `4.0.0-pre.14`.
  
The [style](https://drive.google.com/open?id=1qt9SR3vmc_pqPOaJGuaSUmStvA23ySZX) I'm using.

Rendering with the code:  
```
var tile1 = {
  ratio: 1.556650390625,
  zoom: 8,
  width: 1024,
  height:  1024,
  center: [8.420257, 50.854598],
  pxWidth: 1594,
  pxHeight: 1594,
}

var tile2 = {
  ratio: 1.556650390625,
  zoom: 8,
  width: 1024,
  height:  1024,
  center: [11.232842, 50.854598],
  pxWidth: 1594,
  pxHeight: 1594,
}

renderTile('tile1', t1);
renderTile('tile2', t2);

function renderTile(name, tile) {
  var options = {
    request: function(req, callback) {
       // ...
    },
    ratio: tile.ratio,
  };

  var map = new mbgl.Map(options);

  map.load(require(stylePath));

  map.render({
    zoom: tile.zoom,
    width: tile.width,
    height:  tile.height,
    center: tile.center,
    bearing: 0,
    pitch: 0,
  }, function(err, buffer) {
      console.log(err);
      if (err) throw err;

      map.release();

      var image = sharp(buffer, {
          raw: {
              width: tile.pxWidth,
              height: tile.pxHeight,
              channels: 4
          }
      });

      // Convert raw image buffer to PNG
      image.toFile(name + '.png', function(err) {
          if (err) throw err;
      });
  });
}
```

### Expected behavior
I'd expect labels that cross multiple tiles to not be cut-off, like it happens in most situations.

### Actual behavior
I've aligned the two tiles here; notice how `Göttingen` is clipped:
![image](https://user-images.githubusercontent.com/2334434/44772476-43614300-ab6e-11e8-88cc-fc7e673b78a2.png)

Thanks

**Comment by asheemmamoowala** [comment] 2018-08-29 18:10
Duplicate of #8587. Per [#8587(comment)](https://github.com/mapbox/mapbox-gl-native/issues/8587#issuecomment-415227728), you can try using `symbol-avoid-edges` to improve this.

**Closed by asheemmamoowala** 2018-08-29 18:10 UTC

**Comment by pbnsilva** [comment] 2018-08-30 11:58
Unfortunately, setting `symbol-avoig-edges` to true makes no difference.

**Comment by ChrisLoer** [comment] 2018-09-11 16:40
`node-v4.0.0-pre.15` contains https://github.com/mapbox/mapbox-gl-native/pull/12520, which re-enables the `symbol-avoid-edges` behavior and also makes a change to make line labels _always_ avoid tile boundaries.

**Comment by ChrisLoer** [comment] 2018-10-11 16:15
Oof, that's a really dramatic one! The change to line label tile boundary handling won't make any difference in this case because both "Slovenia" and "Ljubljana" look like they're point labels. Are you sure that both layers that those two labels are part of have `symbol-avoid-edges: true`? I don't see `symbol-avoid-edges` anywhere in the style.json you linked (by the way, it looks beautiful!).

**Comment by pbnsilva** [comment] 2018-10-29 17:33
Thanks, [here it is](https://drive.google.com/file/d/1r_2n3ZKrZ8WapnvEjqQjrsnQe8YILfoc/view?usp=sharing).

**Comment by ChrisLoer** [comment] 2018-10-29 19:00
By the way, I hope this isn't rude, but when I loaded up your style, I thought "this would look really cool with dynamic hillshading added". Have you experimented with that?

<img width="831" alt="screenshot 2018-10-29 11 57 30" src="https://user-images.githubusercontent.com/375121/47673500-0e736b80-db72-11e8-8b2d-6a9af33d4ab7.png">

**Comment by pbnsilva** [comment] 2018-10-29 21:09
Completely missed that. Adding `mode: "tile"` fixed my problems. Thanks for your help Chris!

And not rude at all, it does look cool! Will share with the team.
