### ISSUE TITLE
No annotations at initial zoom level

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1675] opened 2015-06-02 16:58 UTC
If you follow the “[First steps with Mapbox GL for iOS](https://www.mapbox.com/guides/first-steps-gl-ios/#adding-a-marker)” guide, you wind up initializing an `MGLMapView`, centering it on the U.S. President’s front yard, and placing an annotation there, all within `-[ViewController viewDidLoad]`. But if you do all that in `-viewDidLoad`, the annotations fail to display at the initial zoom level. They appear when you zoom in or out to a different zoom level and disappear when you reenter the initial zoom level.

At launch, the map view happens to show z15 tiles:

![initial](https://cloud.githubusercontent.com/assets/1231218/7941610/5a10cbf4-090d-11e5-8b85-a22145f533e5.png)

Then zoom in, right to the cusp of z16:

![in](https://cloud.githubusercontent.com/assets/1231218/7941621/6933daea-090d-11e5-9ebe-a7502cdbfbbe.png)

And zoom in just a little farther to z17:

![inner](https://cloud.githubusercontent.com/assets/1231218/7941642/8a2f3ff0-090d-11e5-8d61-57756c62f705.png)

Or zoom out, right to the cusp of z14:

![out](https://cloud.githubusercontent.com/assets/1231218/7941654/9e321590-090d-11e5-8f63-b398b3b5b4de.png)

And a little further out to 14:

![outer](https://cloud.githubusercontent.com/assets/1231218/7941668/b0eaf8f0-090d-11e5-8691-bd00177e5172.png)

The upshot is that our guide does not work as designed. We didn’t catch this issue in development because the iOS demo app only adds annotations in response to an action sheet button, not within `-viewDidLoad`.

Reproduces in ios-v0.3.1 as well as master, regardless of style.

/cc @incanus

**Comment by incanus** [comment] 2015-06-02 16:59
Likely the same issue as https://github.com/mapbox/mapbox-gl-native/issues/1279.

**Comment by 1ec5** [comment] 2015-06-03 05:34
Because of this issue, bsudekum/react-native-mapbox-gl’s `-[RCTMapboxGL setAnnotations:]` has to [defer the call to `-addAnnotations:` or `-removeAnnotation:`](https://github.com/bsudekum/react-native-mapbox-gl/blob/openAnnotation/RCTMapboxGL/RCTMapboxGL.m#L98).

/cc @bsudekum

**Comment by incanus** [comment] 2015-06-15 19:47
Let's hit this as part of our focus on annotation solidification in b3.

**Comment by friedbunny** [comment] 2015-06-18 07:53
Trying to draw a shape annotation in `viewDidLoad` immediately after map initialization fails to render the shape on the map, too.

[Here's a GeoJSON polyline demo for iOS](https://gist.github.com/friedbunny/80e5010a8ea7bedb3e40) using the same delay technique as `react-native-mapbox-gl`.

**Comment by ansis** [comment] 2015-07-01 16:43
@1ec5 I think this should be fixed by the `fix-1675` branch. Can you check?

@tmpsantos do these partial parsing changes look right? https://github.com/mapbox/mapbox-gl-native/commit/5f90c60638de7260a66dda08208b6814b11bfc95

**Comment by 1ec5** [comment] 2015-07-01 17:08
@ansis, yes, that fixes it. Thanks!

**Comment by ansis** [comment] 2015-07-02 09:35
This was also fixed by @jfirebaugh's work that merged yesterday

**Comment by tmpsantos** [comment] 2015-07-02 10:30
> @tmpsantos do these partial parsing changes look right? 5f90c60

Perfect.

**Comment by friedbunny** [comment] 2015-07-17 17:53
Still seeing this issue.

Annotations don't load at the initial zoom, but load (**and stay**) after zooming in/out to the next level.

**Comment by 1ec5** [comment] 2015-07-18 02:41
So was @ansis' patch needed then?

**Comment by tmpsantos** [comment] 2015-07-18 11:24
> Annotations don't load at the initial zoom, but load (and stay) after zooming in/out to the next level.

I have theory why this is happening: could be that we add the layer so fast that we emit the `update()` request while the tiles are still being parsed for the first time and after that we think that parsing is done, not aware of a new layer that was added. I can have a look at this monday morning.

**Comment by incanus** [comment] 2015-07-27 23:21
@tmpsantos Any more movement on this? Is this something you can look into?

**Comment by tmpsantos** [comment] 2015-07-30 21:11
> @tmpsantos Any more movement on this? Is this something you can look into?

Yes, I managed to reproduce this early today. But I'll have to get back to this one later. :-/

**Comment by tmpsantos** [comment] 2015-07-31 12:05
Working on this one today.

It is indeed related to adding the annotation before the style gets parsed. I can reproduce adding the annotation after calling `map.setStyleURL` but not after `map.setStyleJSON`. The former will issue a network request that sometimes can be answered before we add the annotations (so it works) but most of the time will be late (so we don't see the marker) and the latter is guaranteed that the style gets parsed before we add the marker because there is no network request involved.

**Comment by mikemorris** [comment] 2015-07-31 15:54
Possibly relevant @tmpsantos: https://github.com/mapbox/tilelive-gl/issues/11#issuecomment-91659111

**Comment by incanus** [comment] 2015-09-04 21:46
Taking a look at this.

**Comment by incanus** [comment] 2015-09-04 22:08
> It is indeed related to adding the annotation before the style gets parsed. 

I am seeing missing markers before adjusting zoom both before and after parsing the style. For example, doing something like this in `viewDidLoad`: 

```objc
NSLog(@"adding first point");
MGLPointAnnotation *point = [MGLPointAnnotation new];
point.coordinate = CLLocationCoordinate2DMake(45, -123);
[self.mapView addAnnotation:point];
[self.mapView setCenterCoordinate:point.coordinate zoomLevel:15 animated:NO];

dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    NSLog(@"adding second point");
    MGLPointAnnotation *point2 = [MGLPointAnnotation new];
    point.coordinate = CLLocationCoordinate2DMake(45, -123);
    [self.mapView addAnnotation:point2];
});
```

Plus adding a lot line in `StyleParser:parse()` yields: 

```
2015-09-04 15:05:31.145 Mapbox GL[17153:4238217] adding first point
2015-09-04 15:05:31.145 Mapbox GL[17153:4238217] getting annotation image
2015-09-04 15:05:31.152 Mapbox GL[17153:4238420] [DEBUG] {Map}[ParseStyle]: recreating annotation styling
2015-09-04 15:05:33.337 Mapbox GL[17153:4238217] adding second point
2015-09-04 15:05:33.337 Mapbox GL[17153:4238217] getting annotation image
```

With neither marker showing at launch.

**Comment by incanus** [comment] 2015-09-04 22:11
This is regardless of returning `nil` in the delegate to use default imagery or returning an actual `MGLAnnotationImage` there.

**Comment by incanus** [comment] 2015-09-04 22:28
Current hunch is that the sprite imagery doesn't exist or isn't referenced properly at first, as the annotation tiles and style look ok around the points the annotations aren't rendering.

**Comment by incanus** [comment] 2015-09-04 22:35
This is not limited to zooming — panning away from the initial viewport, then back is enough to cause sprites to render. Which makes sense, if this is indeed a render timing bug.

**Comment by incanus** [comment] 2015-09-04 23:08
I've confirmed that merely moving the area off screen isn't enough to re-trigger, but moving the tile in question is. So it seems to be an initial viewable tile staleness issue.

**Comment by incanus** [comment] 2015-09-05 01:14
Getting closer. I've confirmed that annotation tile structures get updated/invalidated properly, but that's not necessarily re-rendering them once either the style's `sprite` (main sprite) or `spriteStore` (runtime sprites) are available.

**Comment by incanus** [comment] 2015-09-05 01:36
Seems to be related to https://github.com/mapbox/mapbox-gl-native/issues/1688. Annotation tiles rely on being expired and then re-rendered, but we don't have a way to say "re-render `x` tiles on screen now"; we typically do an `Update::Repaint` and have set `style.shouldReparsePartialTiles`.

**Comment by incanus** [comment] 2015-09-09 00:27
https://github.com/mapbox/mapbox-gl-native/pull/2289 has a proposed fix for this. In the long run, we should be allowing re-parse of annotation live tiles in the style of regular vector tiles, but that will be solved by the solution to https://github.com/mapbox/mapbox-gl-native/issues/1688.

**Comment by friedbunny** [comment] 2015-09-09 15:39
Works well, polylines and markers both show up immediately when drawn in `viewDidLoad:`. :100:

**Comment by picciano** [comment] 2015-09-11 16:30
This fix only seems to work about 90% of the time. Definitely an improvement, but does not appear to be solved completely.

We have a particular view where we instantiate a new instance of map view, add 3 annotations, (2 point annotations and 1 polyline). We do this within the `viewDidLoad` method. The polyline is always displayed, but the point annotations are only displayed some of the time, where either one or both are missing. Manually zooming in or out does cause the markers to display.

I have tried adding a delay in adding the annotations, but with only some benefit. The only console messages are `[INFO] {Map}[Sprite]: Can't find sprite named 'marsh-16'`, but not sure if those are related. We are using the latest source code from master.

Desired:
![screen shot 2015-09-11 at 10 26 36 am](https://cloud.githubusercontent.com/assets/417933/9820206/a8a0b53e-586f-11e5-8cba-66a0821ee533.png)

Missing 1 annotation:
![screen shot 2015-09-11 at 10 26 48 am](https://cloud.githubusercontent.com/assets/417933/9820207/a8a1c816-586f-11e5-8524-9dd2f8215362.png)

Missing 2 annotations:
![screen shot 2015-09-11 at 10 26 54 am](https://cloud.githubusercontent.com/assets/417933/9820205/a88eaccc-586f-11e5-9ce4-417e14714b9b.png)

**Comment by incanus** [comment] 2015-09-11 16:32
@picciano Is there anyway you could share the exact annotation data and `viewDidLoad` code? Would be easier to reproduce/test/fix.

**Comment by picciano** [comment] 2015-09-11 16:57
Sure. The lat/lng data is being extracted from a JSON results. This URL will return a typical route.
http://api.tallygo.com/v3/route?requestType=DepartureTime&startLat=33.987760&startLon=-118.470784&endLat=33.993995&endLon=-117.892209&time=2015-09-11T16:51:17&speed=-1.000000&course=-1.000000

The "origin" marker is set to the coordinates of the first point, the "destination" is set to the coordinates of the last point. The polyline is (not surprisingly) the coordinates of each point.

In `viewDidLoad` we have a wrapper class around the map view and do this:

```
.
.
.
    // Customize views
    self.mapOverview.layer.cornerRadius = 5.0f;
    self.mapOverview.layer.borderWidth = 1.0f;
    self.mapOverview.layer.borderColor = [UIColor lightGrayColor].CGColor;

    // Configure the map view...
    self.mapUtility = [TGMapUtility newInstance];
    self.mapUtility.mapView.userInteractionEnabled = YES;
    [self.mapOverview insertSubview:self.mapUtility.mapView atIndex:0];
    self.mapUtility.mapView.delegate = self;
    [self drawRoute];
.
.
.
```

TGMapUtility sets some defaults for us by running:
```
- (instancetype)initStandard {
    self = [super init];
    if (self) {
        _mapView = [[MGLMapView alloc] initWithFrame:[[UIApplication sharedApplication] keyWindow].frame styleURL:[[self class] tallyGoStyle]];
        self.mapView.userTrackingMode = MGLUserTrackingModeNone;
        self.mapView.rotateEnabled = NO;
        self.mapView.showsUserLocation = NO;
        self.mapView.userInteractionEnabled = NO;
        self.mapView.tintColor = [TGStyleKit tGGreen];
        [self removeLogoAndDisclosureButton];
        [self.mapView setCenterCoordinate:MIDDLE_OF_LA zoomLevel:DEFAULT_ZOOM animated:NO];
    }
    return self;
}
```

The style used is an embedded style, essentially Mapbox streets with a couple tweaks to hide the contour labels.

```
+ (NSURL *)tallyGoStyle {
    NSString *jsonFile = [[NSBundle mainBundle] pathForResource:@"tallygo-v8" ofType:@"json"];
    NSURL *styleURL = [NSURL URLWithString:[NSString stringWithFormat:@"asset://%@", jsonFile]];
    
    return styleURL;
}
```

Then in `drawRoute`, we do this:

```
- (void)drawRoute {
    TGRoute *route = self.options.route;
    if (route) {
        [self.mapUtility.mapView removeAnnotations:self.mapUtility.mapView.annotations];
        
        NSMutableArray *annotations = [NSMutableArray arrayWithCapacity:route.points.count];
        
        CLLocationCoordinate2D coordinates[route.points.count];
        for (int i = 0; i < route.points.count; i++) {
            CLLocationCoordinate2D coordinate = ((TGPoint *)route.points[i]).coordinate;
            coordinates[i] = coordinate;
        }
        
        MGLPolyline *polyline = [MGLPolyline polylineWithCoordinates:coordinates count:route.points.count];
        [annotations addObject:polyline];
        
        //add origin
        CLLocationCoordinate2D coordinate = ((TGPoint *)route.points[0]).coordinate;
        TGAnnotation *annotation = [TGAnnotation annotationWithLocation:coordinate title:kOrigin subtitle:kEmptyString];
        [annotations addObject:annotation];
        
        //add destination
        coordinate = ((TGPoint *)route.points[route.points.count - 1]).coordinate;
        annotation = [TGAnnotation annotationWithLocation:coordinate title:kDestination subtitle:kEmptyString];
        [annotations addObject:annotation];
        
        [self.mapUtility.mapView addAnnotations:annotations];
    }
}
```

Then, from `viewDidLayoutSubviews` we call:
```
- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    self.mapUtility.mapView.frame = self.mapOverview.bounds;
    [self zoomMap];
}
```

```
- (void)zoomMap {
    TGRoute *route = self.options.route;
    
    CLLocationCoordinate2D coordinates[route.points.count];
    for (int i = 0; i < route.points.count; i++) {
        CLLocationCoordinate2D coordinate = ((TGPoint *)route.points[i]).coordinate;
        coordinates[i] = coordinate;
    }
    
    [self.mapUtility.mapView setVisibleCoordinates:coordinates count:route.points.count edgePadding:UIEdgeInsetsMake(25, 10, 45, 10) animated:NO];
    
    self.tallyGoButton.enabled = YES;
}
```

**Comment by picciano** [comment] 2015-09-15 23:30
I put together a small app that reproduces this issue.
https://github.com/tallygo/MissingMapMarkers

Tapping the "Redraw" button re-creates the MapView and sometimes give a different manifestation of the problem. This project uses the latest published pod, but this is also seen from latest source in Master.

![ios simulator screen shot sep 15 2015 5 27 24 pm](https://cloud.githubusercontent.com/assets/417933/9892769/45cc250c-5bcf-11e5-9d9f-8482e998b1c5.png)
![ios simulator screen shot sep 15 2015 5 27 36 pm](https://cloud.githubusercontent.com/assets/417933/9892770/45df9aec-5bcf-11e5-83bc-043cdbabfc02.png)

**Comment by incanus** [comment] 2015-09-16 00:31
Thanks @picciano — reopening.

**Comment by jfirebaugh** [comment] 2015-09-21 22:56
It looks like the cases where shape annotations render at all is entirely by accident. There is no guarantee that `MapContext::updateAnnotationTiles` invalidates any of the necessary tiles for shape annotations after it creates the style layers and style buckets for shape annotations:

* `MapContext::updateAnnotationTiles` invalidates only the passed in `ids`, not any of the "stale tiles" accumulated by `annotationManager->markStaleTiles()`.
* But even if it did invalidate the union of `ids` and `staleTiles`, it still wouldn't guarantee to invalidate all or even any of the necessary tiles because for shape annotations, `MapContext::updateAnnotationTiles` is passed an empty `unordered_set` -- `AnnotationManager::addShapeFeature` [does not calculate the affected tiles](https://github.com/mapbox/mapbox-gl-native/blob/2141d95196cbdf63fd4bd8b34824660bf774bb08/src/mbgl/map/annotation.cpp#L106-L107).

I'm not sure how this was intended to work. @incanus?

**Comment by incanus** [comment] 2015-09-21 23:02
Keep in mind that this was perhaps significantly changed recently in https://github.com/mapbox/mapbox-gl-native/commit/2141d95196cbdf63fd4bd8b34824660bf774bb08 and I'm unfamiliar with that work. Do things look the same on the iOS release branch or `master` before that date @jfirebaugh?

**Comment by jfirebaugh** [comment] 2015-09-21 23:11
That commit didn't change this aspect of annotation behavior (or to my knowledge any aspects: it was a pure refactor).

**Comment by incanus** [comment] 2015-09-21 23:22
OTOH, I think shape tiles behave differently from point tiles, since shape tiles are actually generated by geojson-vt so that it can simplify shapes as well as trivially create tiles which are wholly inside filled polygons. 

I can get back into this shortly and try to provide more details after reviewing the code a bit.

**Closed** 2015-09-28 21:39 UTC
Labels: bug, in progress, iOS
