### ISSUE TITLE
Icons are off

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#5742] opened 2016-07-21 09:12 UTC
Just saw this:

![img_1321](https://cloud.githubusercontent.com/assets/52399/17017533/fd1095ec-4f33-11e6-9ea6-155212d8061e.PNG)

**Comment by jfirebaugh** [comment] 2016-07-21 15:48
Probably #4117.

**Comment by 1ec5** [comment] 2016-07-21 20:11
Yes, duplicate of #4117.

**Closed by 1ec5** 2016-07-21 20:11 UTC
