### ISSUE TITLE
[Android] Artifacts on v5.0.1

### ISSUE THREAD

**Issue by edpop** [mapbox/mapbox-gl-native#9184] opened 2017-06-05 01:52 UTC
Hello.
Artifacts appears on different styles.

### Steps to trigger behavior

View a map on Mapbox Dev Preview 5.0.1 https://drive.google.com/file/d/0B3U64R1No4k8SUJndmlHNnRwekk/view

### Expected behavior
In mapboxgl v4.2.0 it was OK.

### ENV
ASUS_T001
Android 4.4.2

Just to let you know.
If you want, I can provide more debug info.

**Comment by Guardiola31337** [comment] 2017-06-05 13:05
@edpop thank you for reaching out and reporting your problem.

> If you want, I can provide more debug info.

That'd be really helpful. Are you able to provide any logs?

**Comment by edpop** [comment] 2017-06-06 00:18
We did not see any logs when the artifacts appeared.
[mapbox-demo-release5.0.1_log.txt](https://github.com/mapbox/mapbox-gl-native/files/1053493/mapbox-demo-release5.0.1_log.txt)
[mapbox-demo-master_log.txt](https://github.com/mapbox/mapbox-gl-native/files/1053492/mapbox-demo-master_log.txt)

**Comment by nevzorovsergey** [comment] 2017-06-11 12:34
I have the same problem. Android 4.2.2 (Huawei U9508) OpenGL ES 2.0. But I didn't find any logs. Where can I find mapbox logs?

**Comment by edpop** [comment] 2017-06-11 13:14
The only way is to run it throw android studio.

**Comment by jfirebaugh** [comment] 2017-07-06 21:09
> ASUS_T001

This model has the PowerVR SGX544 GPU, so this is a duplicate of #8658.

**Closed by jfirebaugh** 2017-07-06 21:09 UTC
Labels: Android, bug, needs information
