### ISSUE TITLE
NPM install failed

### ISSUE THREAD

**Issue by zds05** [mapbox/mapbox-gl-native#15307] opened 2019-08-04 13:21 UTC
I compile on ubantu 16.04
node -v :  v12.7.0
npm -v : 6.10.0
root@zds-K45VD:/home/zds/mapbox/gitdown/mapbox-gl-native# make offline
mkdir -p build/linux-x86_64/Debug
(cd build/linux-x86_64/Debug && cmake -G Ninja ../../.. \
	-DCMAKE_BUILD_TYPE=Debug \
	-DWITH_CXX11ABI=ON \
	-DWITH_COVERAGE= \
	-DWITH_OSMESA= \
	-DWITH_EGL=)
-- Updating submodules...

-- Running 'npm install' for mapbox-gl-native...
-- Finished 'npm install' for mapbox-gl-native...
CMake Error at cmake/mbgl.cmake:54 (message):
  NPM install failed:

  /usr/local/lib/node_modules/npm/bin/npm-cli.js:84

        let notifier = require('update-notifier')({pkg})
        ^^^

  

  SyntaxError: Block-scoped declarations (let, const, function, class) not
  yet supported outside strict mode

      at exports.runInThisContext (vm.js:53:16)
      at Module._compile (module.js:374:25)
      at Object.Module._extensions..js (module.js:417:10)
      at Module.load (module.js:344:32)
      at Function.Module._load (module.js:301:12)
      at Function.Module.runMain (module.js:442:10)
      at startup (node.js:136:18)
      at node.js:966:3

Call Stack (most recent call first):
  cmake/mbgl.cmake:99 (_npm_install)
  CMakeLists.txt:37 (include)

-- Configuring incomplete, errors occurred!
See also "/home/zds/mapbox/gitdown/mapbox-gl-native/build/linux-x86_64/Debug/CMakeFiles/CMakeOutput.log".
Makefile:376: recipe for target 'build/linux-x86_64/Debug/build.ninja' failed

**Comment by LukasPaczos** [comment] 2019-08-05 11:51
Hey @zds05, this looks like a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/15150, please check out the workaround in https://github.com/mapbox/mapbox-gl-native/issues/15150#issuecomment-512782607.

**Closed by LukasPaczos** 2019-08-05 11:51 UTC
Labels: Core, build

**Comment by zds05** [comment] 2019-08-06 00:23
I find the reason ,it abort node version ,when I use node4.3,it can compile success
