### ISSUE TITLE
setVisibleCoordinates does not work for less than full-viewport-sized views

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#4476] opened 2016-03-25 20:58 UTC
On iOS, `setVisibleCoordinates:` and friends do not work correctly if the map view occupies less than the full viewport. For instance, `showAnnotations:` on a half-viewport-height view will still recenter the view as if it were full-height.

Going to tag this “iOS” for now, but it may reach down into `Map::cameraForLatLngs` (and affect other platforms).

![](https://cloud.githubusercontent.com/assets/1198851/14053422/83c5e4fa-f2a7-11e5-869d-6c3a1e17ab17.gif)

/cc @1ec5

**Comment by 1ec5** [comment] 2016-03-25 21:04
Duplicate of #4440.

**Closed by 1ec5** 2016-03-25 21:04 UTC
Labels: bug, iOS
