### ISSUE TITLE
Markers flickering in/out

### ISSUE THREAD

**Issue by yperess** [mapbox/mapbox-gl-native#8367] opened 2017-03-12 23:26 UTC
**Platform: Android**
**Mapbox SDK version:5.0.0. beta 2**

Demo: [video](https://goo.gl/photos/T1e9LLnvcxjprqCbA)

### Steps to trigger behavior

 1. Add several markers via addMarker(MarkerViewOptions)
 2. Override map rotation/zooming to manually alter the camera
 3. Move the camera around until markers begin clipping

### Expected behavior
Markers that are in the visible region should remain visible

### Actual behavior
Markers appear to be randomly being removed.

I traced this down to a specific region: [invalidateMarkersInVisibleRegion](https://github.com/mapbox/mapbox-gl-native/blob/ef82095a21b46916cc5a69e0c6996e599e550a80/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java#L463)

In here, getMarkerViewsInRect returns an incorrect list of marker views. I verified this by attaching a OnGlobalLayoutListener to the view and noticing that some times when I run:

```
boolean visible = mMapboxMap.getProjection()
        .getVisibleRegion()
        .latLngBounds
        .contains(markerView);
PointF screenPoint = mMapboxMap.getProjection()
        .toScreenLocation(markerView.getPosition());
boolean screenVisible = viewRectF.contains(screenPoint.x, screenPoint.y)
// visible != screenVisible
```

Unfortunately, even if I then override the view's visibility according to screenVisible (which seems to be more accurate) the marker still flickers out.

**Comment by tobrun** [comment] 2017-03-13 15:58
@yperess do you have some code to reproduce this with? Tried reproducing this with the test app MarkerView setup without any luck. Are you using anchoring/offset? Large icons?

**Comment by yperess** [comment] 2017-03-13 19:50
@tobrun I'll try to get you a sample. Unfortunately our code is in a private repo right now and I can't just share it. I'll try to extract a sample tonight and post a link to it here. For now here's a very rough sample of what we're doing. The images coming in from the network are capped at around 100x100 px (depending on screen density)

```
final MarkerView marker = mMap.addMarker(new MarkerViewOptions()
        .flat(false)
        .position(new LatLng(pin.latitude, pin.longitude));
Picasso.with(getContext())
        .load(url)
        .into(new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                // Here I add some code that manipulates the bitmap by using a canvas and
                // adding multiple extra bits to it (such as a base that lays flat on the
                // map).
                marker.setIcon(IconFactory.getInstance(getContext()).fromBitmap(bitmap));
                marker.setAnchor(0.5f, baseOffsetRatio);
            }
            @Override
            public void onBitmapFailed(Drawable errorDrawable) {
            }
            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable) {
            }
        });
```

**Comment by tobrun** [comment] 2017-03-14 11:09
Haven't been able to reproduce the issue, would you be able to retest with the latest SNAPSHOT? 
Since beta.2 the underlying code has changed a bit.

![ezgif com-video-to-gif 14](https://cloud.githubusercontent.com/assets/2151639/23897857/0c74e5d0-08af-11e7-81ab-0b58aafcc45e.gif)

![ezgif com-video-to-gif 12](https://cloud.githubusercontent.com/assets/2151639/23897823/ecf6a8ba-08ae-11e7-936b-4e85235e0cb1.gif)

**Comment by yperess** [comment] 2017-03-14 11:46
I'll give it a try. I've been trying to reproduce with an MVP with no luck
so far. I'm just trying to keep the sample as small as possible.

**Comment by yperess** [comment] 2017-03-15 07:05
https://github.com/yperess/MapboxClippingDemo

Notice that it takes me about 60+ seconds to find the right combination of zoom/orientation where the views get clipped

[Video](https://goo.gl/photos/ySkSm1zZvmph3FT16)

**Comment by neonwarge04** [comment] 2017-03-16 04:25
@tobrun, where is this add markers in bulk sample? How are you able to add multiple marker views (1000) on the map? I have markerviews a custom one and I just have 180+ markers and it was very slow.

**Comment by tobrun** [comment] 2017-04-19 10:42
@neonwarge04 the system will keep inflating views if it needs to display a MarkerView. The key is to not show them all at once ( this will make the system recycle the views instead of inflating new ones).

Related to the issue, haven't seen any reports and underlying logic has changed. 
Feel free to reach out if this is still an issue. Closing for now.

**Closed by tobrun** 2017-04-19 10:42 UTC
Labels: Android, annotations, bug

**Comment by yperess** [comment] 2017-04-19 17:04
It's a blocking issue which has left us with migrating off your product and over to Google Maps until this can be resolved. Did you have no luck with the sample app I provided?

**Comment by tobrun** [comment] 2017-04-24 07:36
Thank you for the additional ping, been looking a bit more in this issue and believe the source will be related to #8799. Thank again for reaching out and reporting your issue.
