### ISSUE TITLE
Crashing when dropping pins and single tapping on annotations

### ISSUE THREAD

**Issue by Zakay** [mapbox/mapbox-gl-native#3878] opened 2016-02-10 13:35 UTC
*** Assertion failure in -[MGLMapView handleSingleTapGesture:], mapbox-gl-native/platform/ios/src/MGLMapView.mm:1299

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot select nonexistent annotation with tag 368992152'

```
Steps to reproduce:

1. Drop pin 1 anywhere
2. Drop pin 2 anywhere
3. Tap on pin 1
4. Drop pin 3 anywhere
5. Tap on pin 1
```

**Comment by maciekish** [comment] 2016-02-10 14:10
+1

**Comment by 1ec5** [comment] 2016-02-10 15:54
Duplicate of #3284.

**Closed by 1ec5** 2016-02-10 15:54 UTC
Labels: crash, iOS
