### ISSUE TITLE
App crashes after shader compilation failure 

### ISSUE THREAD

**Issue by ChristopherUNIS** [mapbox/mapbox-gl-native#7143] opened 2016-11-22 12:53 UTC
**Platform: Linux**
**Mapbox SDK version: f92439d1807d743bddf48675df2414c7d0cd71d2**

### Steps to trigger behavior

 1. Compile qt platform with command "make  run-qt-qml-app" 
 
### Expected behavior

App runs

### Actual behavior

App crashes with following error : 

"[ERROR] {mbgl-qt}[Shader]: Shader failed to compile: 0:94(20): error: could not implicitly convert operands to arithmetic operator"

### Findings

Git bisect shows that this bug starts with commit 3380f0803a62525a6884ee4d05e103e072c36117

**Comment by eek001c** [comment] 2016-11-29 17:04
I've tested fix from issue #7197.
mbgl-qt works fine.

**Comment by tmpsantos** [comment] 2016-11-29 17:39
I get the same, the issue is that depending on your computer local, you get a

`#define DEVICE_PIXEL_RATIO 1,000000` instead of `#define DEVICE_PIXEL_RATIO 1.000000`

This is only reproducible if your locale uses `,` for decimal points instead of `.`, which is not the case for the US and the UK but it is for Brazil, France, Russia and pretty much the rest of the planet.

**Comment by tmpsantos** [comment] 2016-11-29 18:55
Fixed by https://github.com/mapbox/mapbox-gl-native/issues/7226

**Closed by tmpsantos** 2016-11-29 18:55 UTC
Labels: Core GL
