### ISSUE TITLE
[iOS] [feature request] New API to define z-index of annotations

### ISSUE THREAD

**Issue by floydaddict** [mapbox/mapbox-gl-native#3971] opened 2016-02-16 10:58 UTC
In the Mappy app we need to : 
 - bring a POI annotation to the front when it is selected by the user
 - some kind of annotations need to always be above the other ones
 - ensure the start and arrival annotations are always visible when displaying a route with a polyline and step annotations 

The goal of this feature is to provide a way to the user to decide which annotation(s) appear(s) above the others.

**Comment by floydaddict** [comment] 2016-02-16 11:00
I can work on it.
i could add a property on annotations. zIndex or weight ?

**Comment by jfirebaugh** [comment] 2016-02-16 16:57
Duplicate of #991 / #1728. We're holding off from making further changes to the annotation API while we work on a more flexible [Style API](https://github.com/mapbox/mapbox-gl-native/issues/837).

**Closed by jfirebaugh** 2016-02-16 16:57 UTC

**Comment by floydaddict** [comment] 2016-02-16 17:05
Do you have any even approximative idea when the refactoring on styles will be ready ? 
We need this feature to go prod and we need to plan our release date a few month ahead, thx.

**Comment by jfirebaugh** [comment] 2016-02-16 19:08
cc @twbell
