### ISSUE TITLE
[android] perspective change gesture calculates user location wrong

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#9161] opened 2017-06-01 13:24 UTC
**Platform:** Android
**Mapbox SDK version:** v5.1.0-beta.3

Issue is present when `TRACKING_FOLLOW` mode is selected, and **map padding** is applied.
I checked on version v4.2.0 and it was working fine.

![tilt_issue](https://cloud.githubusercontent.com/assets/16925074/26681612/0495ba20-46de-11e7-920d-1882ac3884ad.gif)

**Comment by tobrun** [comment] 2017-06-02 08:36
Thanks for the report @LukasPaczos, same issue as in https://github.com/mapbox/mapbox-gl-native/issues/8415. Closing as a duplicate.

just an FYI, we are working on MyLocationView implementation using runtime styling. This would remove issues as in OP as we can rely on the Map transformation instead of an estimated transformation.

**Closed by tobrun** 2017-06-02 08:36 UTC
Labels: Android

**Comment by LukasPaczos** [comment] 2017-06-02 08:44
@tobrun got it! Are #9163 and #9172 also related to this?

**Comment by tobrun** [comment] 2017-06-02 08:51
This issue is related to the projected location of MyLocationView. #9163 is related to how the MyLocationView is updated about camera changes while animating. #9172 is also unrelated but need to look more into to find the root cause. Thanks again for posting all these issues and making the SDK better!
