### ISSUE TITLE
Remove hard-coded CA filename

### ISSUE THREAD

**Issue by j-omega** [mapbox/mapbox-gl-native#15804] opened 2019-10-11 16:40 UTC
https://github.com/mapbox/mapbox-gl-native/blob/2fb1e47b75c038f226397df7b790ba699b6e2dc8/platform/default/src/mbgl/storage/http_file_source.cpp#L250

The name of this file can vary across linux platforms. A default value is often compiled into the curl package provided with the Linux distro (config option --with-ca-bundle). This file name decision should be left to curl.

**Comment by tobrun** [comment] 2019-11-08 11:03
duplicate of https://github.com/mapbox/mapbox-gl-native/issues/13850, will be resolved with https://github.com/mapbox/mapbox-gl-native/pull/15878

**Closed by tobrun** 2019-11-08 11:03 UTC
