### ISSUE TITLE
[Android] Markers blink on zoom change

### ISSUE THREAD

**Issue by mpuchala** [mapbox/mapbox-gl-native#6762] opened 2016-10-19 17:10 UTC
**Platform: Android**
**Mapbox SDK version: 4.2.0 Snapshot**
### Steps to trigger behavior
1. Create Map
2. Zoom in/out
### Actual behavior

It is also about the map. When I'm zooming in/out map and markers sometimes blink. It wasn't a problem on 4.1.0 now it occurs even on simple map. I've noticed similar behavior when I'm updating icon (in only one marker).

Here is a video:
https://www.dropbox.com/s/ok27ba09nty0sha/map_blink.mp4?dl=0

**Comment by mpuchala** [comment] 2016-11-08 11:09
@tobrun 

Hey,

Is there any progress with this issue?

I've just used 4.2.0-beta4 and it still appears. With few Markers UX is really bad (when I'm showing 10-20 almost everything on the screen is blinking). Are you able to reproduce it easily?

**Comment by cammace** [comment] 2016-11-10 22:54
Hey @mpuchala, could you clarify whether you are using GL Markers or view based markers? Also does this issue occur when you are using just the default markers found in the SDK?

**Comment by mpuchala** [comment] 2016-11-12 10:35
Hey,

Here is an example from Dev Preview:

https://www.dropbox.com/s/ptckispqoc077np/map_blink_2.mp4?dl=0
https://www.dropbox.com/s/ko0u1wkd3qfpgl3/map_blink_3.mp4?dl=0

I'm using GL Markers, there is a default icon and it's easy to find out same problem. It seems to blink when other elements like labels, icons, etc. are changing. As I mentioned before it also occurs when I'm changing an icon (all markers are disappearing for a moment) - it isn't an issue on 4.1.0 SDK version.

**Comment by cammace** [comment] 2016-11-16 15:51
You can try switching to marker views which shouldn't have any flickering issue. I've been able to reproduce in the test app with many markers: 

![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/5652865/20353962/e1e5e47a-ac1c-11e6-8d7a-9c164052c1e1.gif)

Any idea what is happening here @ivovandongen?

**Comment by mpuchala** [comment] 2016-11-16 16:10
Hey,

Thanks for reply.

My problem with MarkerViews is performance. I tried to use ~200 of them and app almost haven't responded.

IMHO it's not only about amount (GL Markers) but for sure it's easier to notice this behaviour then - in example I've attached there is only one icon.

Markers seem to disappear for a while when other map components like labels are being changed (and also only one marker icon I mentioned above).

We're using at least 1000-2000 markers so probably MarkerViews aren't suitable in our case - I've tested them with only one icon and result wasn't promising. I use them (MV) when I have few points and it works like a charm in that cases.

**Comment by tobrun** [comment] 2016-12-13 07:45
Have seen multiple reports on this, going to try pinpointing the cause of this.

**Comment by tobrun** [comment] 2016-12-14 10:36
a git bisects indicates this is coming from 41bbd4e4f7d66465433e370ca024ab0239fcace3. I'm thinking it will be related to the geometry_tile_worker? Any tips on how to proceed on this @jfirebaugh?

**Comment by jfirebaugh** [comment] 2016-12-14 18:06
Do you have a test case?

**Comment by tobrun** [comment] 2016-12-14 22:04
It's reproducible with the `Bulk Marker Activity` from the testapp as shown by @cammace  in https://github.com/mapbox/mapbox-gl-native/issues/6762#issuecomment-260982043. I think it's hard to write a test for this since it happens as part of gesture.

**Comment by dylan-chong** [comment] 2017-03-08 00:46
Has any progress been made on this issue in the last 3 months? This is a pretty problematic bug in terms of user experience, so I can't actually use any 4.2.x version on my app.

**Comment by tobrun** [comment] 2017-04-20 09:46
Going to add this to next milestone to look into more.

**Comment by mpuchala** [comment] 2017-05-17 13:13
@tobrun 
Have no idea if this feedback would be helpful or not, but on 5.0.2 it seems to work fine and stable on my app (~200 Markers - no MarkerViews), unfortunately it's an issue again on 5.1.0 beta...

**Comment by PhanVanLinh** [comment] 2017-05-18 08:56
@mpuchala  Do you know what is different between Marker and MarkerView?

**Comment by mpuchala** [comment] 2017-05-18 09:14
@PhanVanLinh If you would like to find differences please take a look on examples and API:
https://www.mapbox.com/android-sdk/api/5.0.2/

MarkerViews are much more flexible, however you have to prepare adapter for them (there is no need like that for Markers). According to my experience Markers are much more faster than MarkerViews (at least there were when I was compering them some time ago - maybe sth has changed).

I'm not a MapBox team member so maybe sth has changed, but I think it's not the best place to discuss about them - it's off topic and this issue is about something else.

**Comment by PhanVanLinh** [comment] 2017-05-18 09:20
@mpuchala Thank you so much for your explain. I will read the API. if you don't mind. can you share me your email then we can discuss in another place. my email is: phanvanlinh.94vn@gmail.com. I will remove this comment after your response

**Comment by paulVulog** [comment] 2017-09-28 08:06
Just in addition, I am able to see some flickering by just playing with the zoom in the MapBox demo app (v5.1.3) in the Annotations/Draw a marker Activity. 
It happens at very specific zoom level (e.g : at map labels woo; changes)

**Comment by VGordejevs** [comment] 2017-10-21 18:45
Yeah, weird story :x (5.2.0-SNAPSHOT)

**Comment by fdermishin-radargeo** [comment] 2017-12-05 08:19
5.2.0 still has this issue. This happens when layers change while zooming. For some reason there is a frame, on which new layers are already drawn, but layer with markers is not visible. The markers appear only on the next frame.

**Comment by tobrun** [comment] 2017-12-05 08:20
This behaviour is fixed on master and is planned to be released as part of the upcoming 6.0.0 release.

**Closed by tobrun** 2017-12-05 08:20 UTC
Labels: Android
