### ISSUE TITLE
Mapbox 5.1.x not working well on old Androids like Jelly Bean?

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#10145] opened 2017-10-06 15:46 UTC
_Originally ticketed in https://github.com/mapbox/mapbox-java/issues/589 by @leocarona_

After upgrading Mapbox from 5.0.x to 5.1.x, I began having a few issues on Android 4.1.2, and my project (as well as Mapbox as long as I know) sets minSdkVersion to API 15.

I've been using custom markers (as suggested here #3756) and it works just fine with Mapbox 5.0.x. Though, after upgrading to Mapbox 5.1.x I began having issues with zoom (double tap does zoom in as excepted, but pinching doesn't work at all), and when a Marker in clicked, rarely a infoWindow opens (I couldn't find a standard of when it usually opens, but most often nothing is happening when a marker is clicked).

**Comment by leocarona** [comment] 2017-10-07 16:51
** I've been using custom markers as suggested [**here by tobrun**](https://github.com/mapbox/mapbox-gl-native/issues/3756#issuecomment-181285795).

**Comment by leocarona** [comment] 2017-10-09 23:53
Looks like same issue as #10026 and the others referenced in it.

**Comment by tobrun** [comment] 2017-10-11 13:36
@leocarona are you setting  custom id on Marker in relation with not opening an infowindow? (this is not allowed and will break info windows). I just verified that InfoWindows still work correctly on master and the release branch.

related to the touch issue, as you indicated this is a duplicate for https://github.com/mapbox/mapbox-gl-native/issues/10101. 

Going to close this issue as both non reproducible as a duplicate.

Let us know if you have any more questions or bugs!

**Closed by tobrun** 2017-10-11 13:36 UTC
Labels: Android

**Comment by leocarona** [comment] 2017-10-11 14:25
No, I don't set Marker's id. I've extended BaseMarkerViewOptions [here](https://github.com/Hitchwiki/MyHitchhikingSpots-for-Android/blob/master/app/src/main/java/com/myhitchhikingspots/utilities/ExtendedMarkerViewOptions.java) to add my own tag attribute. And I've added these custom markers to the maps as you can see [here](https://github.com/Hitchwiki/MyHitchhikingSpots-for-Android/blob/master/app/src/main/java/com/myhitchhikingspots/HitchwikiMapViewActivity.java). 

Can you see something unusual on the way how I'm adding my custom markers or the MarkerViewAdapter?

I've tried to comment out addMarkerViewAdapter and to add regular markers with MarkerViewOptions but still when I click them on the map no infoWindow appears (API 15).
