### ISSUE TITLE
[iOS] Wrong map insets behavior while tracking user location

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#3778] opened 2016-02-01 15:13 UTC
Bug visible on current master (3.1.0 pre 3)
Show a map, set the map contentInset. The map moves accordingly. This is correct.
Then set the user tracking to follow. The map then "moves back" to its original position and only the user location is inset. This makes a double error : the map is not correctly inset and the user location is incorrect.

**Comment by 1ec5** [comment] 2016-02-01 15:33
Does this bug reproduce in pre.2 or pre.1?

**Comment by 1ec5** [comment] 2016-02-02 05:17
There are a number of possible reasons why the content inset might appear to be reverted. I’m unable to reproduce this issue by setting the content inset then setting the user tracking mode. Are you using the plain property setters or the `animated:` methods? Does the view controller have a top or bottom bar that might be overriding the content inset? Is the user tracking mode set immediately (synchronously) after setting the content inset, or is there some delay?

**Comment by RomainQuidet** [comment] 2016-02-02 09:38
Hi. I'm trying to inset on the right and bottom.
The view controller managing the map is part of a navigation controller so there's a navigation bar.
I did some tests, it always behave the same : I'm setting the inset to the map. I tried both with animation api or directly with the setter. Then I set userTrackingMode to follow. Even if I set it after 2s, there is a map shift which leads to an incorrect position of the marker vs the map. The user marker is correctly centered in the inset area, but the map suffers from an extra offset. 
I also just tried to set the user mode to follow on map appearance, then switch on/off the insets. Here are some screenshots to show the behavior.

![simulator screen shot 2 fevr 2016 10 39 54](https://cloud.githubusercontent.com/assets/8179069/12745265/ba7467f2-c998-11e5-96f9-6f76129333ba.png)
![simulator screen shot 2 fevr 2016 10 40 00](https://cloud.githubusercontent.com/assets/8179069/12745264/ba7261c8-c998-11e5-82c9-039bb1822bc6.png)
![simulator screen shot 2 fevr 2016 10 40 38](https://cloud.githubusercontent.com/assets/8179069/12745263/ba724e5e-c998-11e5-9176-d2f6463d679e.png)
![simulator screen shot 2 fevr 2016 10 40 42](https://cloud.githubusercontent.com/assets/8179069/12745262/ba70afae-c998-11e5-83dc-0ef092d5b82a.png)

**Comment by RomainQuidet** [comment] 2016-02-02 10:00
In case I just set the map region or center coordinate before setting / unsetting the insets, it works correctly.

![simulator screen shot 2 fevr 2016 11 04 40](https://cloud.githubusercontent.com/assets/8179069/12745906/2369914e-c99c-11e5-9452-ccb3dab7470b.png)
![simulator screen shot 2 fevr 2016 11 04 44](https://cloud.githubusercontent.com/assets/8179069/12745905/23657a3c-c99c-11e5-81fc-94de52a53a6f.png)

**Comment by RomainQuidet** [comment] 2016-02-02 14:51
Seems to be animation timing issue in MGLMapView.mm
in method - (void)locationManager:(__unused CLLocationManager *)manager didUpdateLocations:(NSArray *)locations animated:(BOOL)animated

the map view is updated, then the user view is updated ... under debug.

**Comment by RomainQuidet** [comment] 2016-02-03 10:43
@1ec5 On device the bug is not visible. I suspect the simulator to inject position too often and then an animation collision occur.

**Comment by RomainQuidet** [comment] 2016-02-18 10:54
@1ec5 I tested again on device, the bug is still there. 
In my view controller viewDidAppear I set the userTrackingMode to follow.
On a switch controller I set the map inset to inset.

**Comment by RomainQuidet** [comment] 2016-02-22 16:30
Seems that - (UIEdgeInsets)edgePaddingForFollowing is no more useful. 
All methods - (void)setCenterCoordinate:xxxxxx are using now self.contentInset as the edgePadding except one. Changing it make the user location + map centered correctly on the inset view.

Pull request ongoing.

**Comment by RomainQuidet** [comment] 2016-02-22 16:32
created #4067

**Comment by boundsj** [comment] 2016-08-30 23:48
Subsumed by https://github.com/mapbox/mapbox-gl-native/pull/6216

**Comment by boundsj** [comment] 2016-08-30 23:52
Thanks for your contribution @RomainQuidet! I think you are correct that passing `contentInset` as the edgePadding parameter to `_setCenterCoordinate` is correct. Your change to do that is now in https://github.com/mapbox/mapbox-gl-native/pull/6216 and should be merged soon.

**Closed** 2016-08-31 00:31 UTC
Labels: bug, iOS

**Comment by cdstamper** [comment] 2017-04-28 17:55
@boundsj has this fix been merged as of 3.4.2? 

I'm still seeing that setCenter() does not respect the map view's contentInset on simulator.
