### ISSUE TITLE
Make ReLinker the default library loader of SDK

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#13928] opened 2019-02-14 14:32 UTC
We have heard from multiple reports that the with the introduction of app bundles, users have seen more `UnsatisfiedLinkError` errors. A solution, which is also adviced by Google in the NDK 19 release notes is to use ReLinker for SO loading. 

With https://github.com/mapbox/mapbox-gl-native/pull/13768, we made ReLinker the default library loader for the testapp. I feel we should move the default library loader to this as well.  TBI: can we introduce this without breaking semver?

cc @mapbox/maps-android

**Comment by Jukurrpa** [comment] 2019-02-18 20:03
Hi @tobrun , our app crashes repeatedly for some of our users because of this issue (UnsatisfiedLinkError). Until this is investigated and fixed on your end, is using ReLinker the way you do in the test app a proper workaround to avoid these crashes? We can't reproduce these issues on our end as it happens on very specific devices.

**Comment by tobrun** [comment] 2019-02-19 08:12
> Until this is investigated and fixed on your end

afiak, nothing on our end can be fixed as the issue stems from  Android itself. Caputuring from Relinker Github: `The Android PackageManager's native library loading is unreliable` and to me it seems to have become more unreliable with the introduction of app bundles. 

> is using ReLinker the way you do in the test app a proper workaround to avoid these crashes?

Yes, as stated on their github [here](https://github.com/KeepSafe/ReLinker#overview) but it's now  also advised by Google [here](https://developer.android.com/ndk/downloads/revision_history): ` We believe that ReLinker is a better solution to native library loading issues on old Android versions.`.

**Comment by Jukurrpa** [comment] 2019-02-19 18:33
Got it, I thought you were going to include ReLinker in Mapbox and make it the default loader. Thanks for your help!

**Closed** 2019-02-25 15:58 UTC
Labels: Android
