### ISSUE TITLE
android.view.WindowManager$BadTokenException at com.mapbox.mapboxsdk.maps.AttributionDialogManager.showAttributionDialog(AttributionDialogManager.java:60)

### ISSUE THREAD

**Issue by ThaddeusMak** [mapbox/mapbox-gl-native#13698] opened 2019-01-10 04:50 UTC
I reopen this issue because the crash is still happened on the new version of SDK.

### Steps to trigger behavior
Unfortunately I did never (re)produce this error myself, but it showed up more than 15 crashes from the Crashlytics Report of my last apk.

**The stack trace always looks like this:**
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:982)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:384)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:101)
       at android.app.Dialog.show(Dialog.java:430)
       at android.app.AlertDialog$Builder.show(AlertDialog.java:1135)
       at com.mapbox.mapboxsdk.maps.AttributionDialogManager.showAttributionDialog(AttributionDialogManager.java:73)
       at com.mapbox.mapboxsdk.maps.AttributionDialogManager.onClick(AttributionDialogManager.java:65)
       at com.mapbox.mapboxsdk.maps.MapView$AttributionClickListener.onClick(MapView.java:1273)
       at android.view.View.performClick(View.java:6916)
       at android.view.View$PerformClick.run(View.java:26197)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7002)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

### Expected behavior
Don't crash or ignore this report because that scenario is not realistic.

### Actual behavior
Crashes.

### Configuration

**Android versions: Any** 
**Device models: Any ** 
**Mapbox SDK versions: 6.5.1**

**Comment by tobrun** [comment] 2019-01-10 07:58
Thank you for reaching out and using our products. We noticed this as well and are patching this up in https://github.com/mapbox/mapbox-gl-native/pull/13673. This issue is reproducible with opening an activity, clicking the `i` icon and rotating your device.  Note that this is a silent warning and won't crash the application of your users. 

Closing this as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/13208

**Closed** 2019-01-10 08:11 UTC
