### ISSUE TITLE
Changing styles causes annotation images to fail

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#3225] opened 2015-12-08 21:36 UTC
I've been prototyping a map that can switch between a terrain map style and a satellite style. On that map I draw a bunch of overlays, and then annotations which are backed by UIImages. The initial draw works perfectly fine. However, once I change the styleURL on the map view the backing tiles change OK, but all of the annotations are now not visible. 

My log does fill up with messages like `Can't find sprite named 'com.mapbox.sprites.End'` after the url switch.

Steps to reproduce:
- Create a custom map that can toggle between two styles
- Add annotations using Asset Catalog images as the custom views (not sure if limited to this case)
- Switch styles

**Comment by 1ec5** [comment] 2015-12-08 21:37
Dupe of #1488.

**Closed by 1ec5** 2015-12-08 21:37 UTC
