### ISSUE TITLE
Sprites not rendering on iPhone 6 Plus

### ISSUE THREAD

**Issue by gregzo** [mapbox/mapbox-gl-native#940] opened 2015-03-03 08:21 UTC
The iPhone 6 Plus's UIScreen nativeScale of 2.6 isn't supported - all sprites are rendered black. 

Related: support for @3x sprite sheets would be great.

Amazing project, btw!

**Comment by kkaefer** [comment] 2015-03-03 09:25
Duplicate of #843.

**Closed by kkaefer** 2015-03-03 09:25 UTC
