### ISSUE TITLE
[iOS] std::runtime_error in get<T>() (mapbox::util::geojsonvt::Convert::calcRingBBox)

### ISSUE THREAD

**Issue by DanielTomlinson** [mapbox/mapbox-gl-native#3975] opened 2016-02-16 13:43 UTC
Hey,

We've had a new crash pop up since recently switching to MapBox 3.1.0.

It's similar to https://github.com/mapbox/mapbox-gl-native/issues/3926 and https://github.com/mapbox/mapbox-gl-native/issues/2926.

Unfortunately I don't currently have a reproducible test case for this.

```
Application Specific Information:
*** Terminating app due to uncaught exception 'std::runtime_error', reason: 'in get<T>()'

Last Exception Backtrace:
0   [Redacted]                     0x00000001004579f8 mapbox::util::geojsonvt::Convert::calcRingBBox(mapbox::util::geojsonvt::ProjectedPoint&, mapbox::util::geojsonvt::ProjectedPoint&, mapbox::util::geojsonvt::ProjectedGeometryContainer const&) + 212
1   [Redacted]                     0x0000000100457194 mapbox::util::geojsonvt::Convert::create(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, mapbox::util::geojsonvt::ProjectedFeatureType, mapbox::util::variant<mapbox::util::geojsonvt::ProjectedPoint, mapbox::util::geojsonvt::ProjectedGeometryContainer>) + 368
2   [Redacted]                     0x00000001004813b4 mbgl::ShapeAnnotationImpl::updateTile(mbgl::TileID const&, mbgl::AnnotationTile&) + 944
3   [Redacted]                     0x0000000100466b38 mbgl::AnnotationManager::getTile(mbgl::TileID const&) + 1892
4   [Redacted]                     0x000000010046731c mbgl::AnnotationManager::addTileMonitor(mbgl::AnnotationTileMonitor&) + 224
5   [Redacted]                     0x000000010047e694 mbgl::AnnotationTileMonitor::monitorTile(std::__1::function<void (std::exception_ptr, std::__1::unique_ptr<mbgl::GeometryTile, std::__1::default_delete<mbgl::GeometryTile> >)>) + 216
6   [Redacted]                     0x00000001004b6aa8 mbgl::VectorTileData::VectorTileData(mbgl::TileID const&, std::__1::unique_ptr<mbgl::GeometryTileMonitor, std::__1::default_delete<mbgl::GeometryTileMonitor> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mbgl::Style&, std::__1::function<void ()> const&) + 452
7   [Redacted]                     0x00000001004ac62c std::__1::shared_ptr<mbgl::VectorTileData> std::__1::shared_ptr<mbgl::VectorTileData>::make_shared<mbgl::TileID const&, std::__1::unique_ptr<mbgl::GeometryTileMonitor, std::__1::default_delete<mbgl::GeometryTileMonitor> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, mbgl::Style&, std::__1::__bind<void (mbgl::Source::*)(mbgl::TileID const&, mbgl::TransformState const&, bool), mbgl::Source*, mbgl::TileID const&, mbgl::TransformState const&, bool>&>(mbgl::TileID const&&&, std::__1::unique_ptr<mbgl::GeometryTileMonitor, std::__1::default_delete<mbgl::GeometryTileMonitor> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&, mbgl::Style&&&, std::__1::__bind<void (mbgl::Source::*)(mbgl::TileID const&, mbgl::TransformState const&, bool), mbgl::Source*, mbgl::TileID const&, mbgl::TransformState const&, bool>&&&) + 228
8   [Redacted]                     0x00000001004a9928 mbgl::Source::addTile(mbgl::MapData&, mbgl::TransformState const&, mbgl::Style&, mbgl::TexturePool&, mbgl::TileID const&) + 1076
9   [Redacted]                     0x00000001004aa250 mbgl::Source::update(mbgl::MapData&, mbgl::TransformState const&, mbgl::Style&, mbgl::TexturePool&, bool) + 416
10  [Redacted]                     0x00000001004f56b4 mbgl::Style::update(mbgl::TransformState const&, mbgl::TexturePool&) + 72
11  [Redacted]                     0x00000001004a4b5c mbgl::MapContext::update() + 252
12  [Redacted]                     0x000000010044c688 uv_async_init + 364
13  [Redacted]                     0x000000010044c848 uv__async_init + 180
14  [Redacted]                     0x0000000100450410 uv__io_poll + 1268
15  [Redacted]                     0x000000010044cbf8 uv_run + 424
16  [Redacted]                     0x000000010049f6d0 void mbgl::util::Thread<mbgl::MapContext>::run<std::__1::tuple<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>, 0ul, 1ul, 2ul>(mbgl::util::ThreadContext, std::__1::tuple<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul>) + 152
17  [Redacted]                     0x000000010049f5d8 std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::MapContext>::Thread<mbgl::View&, mbgl::FileSource&, mbgl::MapData&>(mbgl::util::ThreadContext const&, mbgl::View&&&, mbgl::FileSource&&&, mbgl::MapData&&&)::'lambda'()> >(void*, void*) + 172
18  libsystem_pthread.dylib              0x000000018268bb28 _pthread_body + 152
19  libsystem_pthread.dylib              0x000000018268ba8c _pthread_start + 152
20  libsystem_pthread.dylib              0x0000000182689028 thread_start + 0
```

**Comment by 1ec5** [comment] 2016-02-16 16:34
Indeed, this is a duplicate of #2926.

**Closed by 1ec5** 2016-02-16 16:34 UTC
