### ISSUE TITLE
 test OfflineDatabase.ConcurrentUse Exited with code 134

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9436] opened 2017-07-06 18:45 UTC
I noticed that the `linux-gcc5-release-qt5` build is often failing with:

```java
[ RUN      ] OfflineDatabase.ConcurrentUse
[WARNING] {memcheck-amd64-}[Database]: Removing existing incompatible offline database
terminate called after throwing an instance of 'mapbox::sqlite::Exception'
  what():  database is locked Unable to fetch row
==2831== 
==2831== Process terminating with default action of signal 6 (SIGABRT)
==2831==    at 0x79B1428: raise (raise.c:54)
==2831==    by 0x79B3029: abort (abort.c:89)
==2831==    by 0x747384C: __gnu_cxx::__verbose_terminate_handler() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==2831==    by 0x74716B5: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==2831==    by 0x7471700: std::terminate() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==2831==    by 0x749CD37: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==2831==    by 0x524B6B9: start_thread (pthread_create.c:333)
==2831==    by 0x7A8282C: clone (clone.S:109)
==2831== 
==2831== HEAP SUMMARY:
==2831==     in use at exit: 6,349,261 bytes in 49,081 blocks
==2831==   total heap usage: 17,178,816 allocs, 17,129,735 frees, 4,973,723,173 bytes allocated
==2831== 
==2831== LEAK SUMMARY:
==2831==    definitely lost: 0 bytes in 0 blocks
==2831==    indirectly lost: 0 bytes in 0 blocks
==2831==      possibly lost: 0 bytes in 0 blocks
==2831==    still reachable: 440,648 bytes in 3,269 blocks
==2831==                       of which reachable via heuristic:
==2831==                         stdstring          : 135 bytes in 3 blocks
==2831==                         length64           : 1,060,608 bytes in 403 blocks
==2831==         suppressed: 5,908,613 bytes in 45,812 blocks
==2831== Reachable blocks (those to which a pointer was found) are not shown.
==2831== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2831== 
==2831== For counts of detected and suppressed errors, rerun with: -v
==2831== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 17383913 from 199)
scripts/valgrind.sh: line 18:  2831 Aborted                 ${VALGRIND_PREFIX}/bin/valgrind $PARAMS $@
Exited with code 134
```

Hit above twice in the same amount of days. 
Example build is [here](https://circleci.com/gh/mapbox/mapbox-gl-native/8385?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

cc @brunoabinader @tmpsantos

**Comment by brunoabinader** [comment] 2017-07-07 12:09
Duplicate of https://github.com/mapbox/mapbox-gl-native/issues/9108.

**Closed by brunoabinader** 2017-07-07 12:09 UTC
Labels: Qt
