### ISSUE TITLE
Pitch depends on the viewport height

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#3056] opened 2015-11-17 18:17 UTC
Pitch currently depends on the viewport height; we claim that it's an angle, but it's really not:

![out](https://cloud.githubusercontent.com/assets/52399/11220330/bff62514-8d5f-11e5-8f18-a447062972ec.gif)

**Comment by incanus** [comment] 2015-11-17 19:38
Refs https://github.com/mapbox/mapbox-gl-native/issues/2139

**Comment by tobrun** [comment] 2016-03-06 23:17
The solution for this will help resolving #3947

**Comment by 1ec5** [comment] 2016-05-14 05:38
From the perspective (hah!) of the iOS SDK, this is correct behavior inasmuch as we want to mimic the behavior of MapKit, which uses a vertical angular field of view of 30°. If I understand correctly, a vertical field of view means the skew is dependent on the height; that explains why Maps.app shows the same behavior depicted above.

**Comment by 1ec5** [comment] 2016-07-29 22:51
Labeling “Android”, because the fix would constitute a regression on iOS and macOS.

**Closed** 2018-11-30 22:49 UTC
Labels: Android, archived, bug
