### ISSUE TITLE
 .styleUrl(url) not available in Mapbox SDK version: 7.0.1

### ISSUE THREAD

**Issue by topinvestor** [mapbox/mapbox-gl-native#13805] opened 2019-01-27 01:52 UTC
### Steps to reproduce

 1.dependencies { implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.0.1'
 2.  MapboxMapOptions options = new MapboxMapOptions()
                .styleUrl(url)
       
 3.

### Expected behavior
 .styleUrl(url) is available and working

Mapbox SDK: 6.8.1 is working fine

### Actual behavior

error: cannot find symbol method styleUrl(String)

### Configuration

**Android versions:** 28
**Device models:** Google Pixel 2
**Mapbox SDK versions:** 7.0.1

**Comment by tobrun** [comment] 2019-01-28 08:17
StyleUrl was removed with 7.0.0, the way you setup your map and how the underlying style is loaded was decoupled from each other. To achieve a similar setup as before use code as:

```java
public class SimpleMapActivity extends AppCompatActivity {

  private MapView mapView;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_map_simple);
    mapView = findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);
    mapView.getMapAsync(mapboxMap -> mapboxMap.setStyle(
      new Style.Builder().fromUrl(Style.MAPBOX_STREETS)
    ));
  }

  @Override
  protected void onStart() {
    super.onStart();
    mapView.onStart();
  }

  @Override
  protected void onResume() {
    super.onResume();
    mapView.onResume();
  }

  @Override
  protected void onPause() {
    super.onPause();
    mapView.onPause();
  }

  @Override
  protected void onStop() {
    super.onStop();
    mapView.onStop();
  }

  @Override
  public void onLowMemory() {
    super.onLowMemory();
    mapView.onLowMemory();
  }

  @Override
  protected void onDestroy() {
    super.onDestroy();
    mapView.onDestroy();
  }

  @Override
  protected void onSaveInstanceState(Bundle outState) {
    super.onSaveInstanceState(outState);
    mapView.onSaveInstanceState(outState);
  }
}

```

Closing this issue as a works as designed.

**Closed by tobrun** 2019-01-28 08:17 UTC

**Comment by topinvestor** [comment] 2019-01-29 16:42
I have my own map style in MapBox Studio.

I see this:
setContentView(R.layout.activity_map_simple);
    mapView = findViewById(R.id.mapView);

How can I load my map style directly rather cling first to load
R.layout.activity_map_simple?

**Comment by tobrun** [comment] 2019-01-30 11:52
> How can I load my map style directly rather going first to load
"R.layout.activity_map_simple"?

You can't but you shouldn't worry about this specific case, we refactored our setup code so it loads faster as before with the whole xml / style config on MapView. OnMapReady now returns when the render surface has been created vs when the style has fully loaded.

**Comment by topinvestor** [comment] 2019-01-30 17:19
I have my own style in MapBox Studio, which I used before like this:

url = "mapbox://styles/mapbox/..."

  MapboxMapOptions options = new MapboxMapOptions()
                .styleUrl(url)
                .camera(new CameraPosition.Builder()
                        .zoom(8)
                        .build());
   mapView = new MapView(this, options);
  MainActivity.this.mapboxMap = mapboxMap;
  setContentView(mapView);
  mapView.onCreate(savedInstanceState);
  mapView.getMapAsync(MainActivity.this);

How to use my style with the new version in build.gradle:
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.0.1'

is my question.

**Comment by tobrun** [comment] 2019-01-30 17:46
```java
myUrl = "mapbox://styles/mapbox/..."

MapboxMapOptions options = new MapboxMapOptions()
//*.styleUrl(url)*//
.camera(new CameraPosition.Builder()
.zoom(8)
.build());
mapView = new MapView(this, options);
MainActivity.this.mapboxMap = mapboxMap;
setContentView(mapView);
mapView.onCreate(savedInstanceState);
mapView.getMapAsync(MainActivity.this);
```

above code block remains the same except for the styleUrl part. Since you have `mapView.getMapAsync(MainActivity.this);` you need to update that method as follows:

```java
  @Override
  public void onMapReady(@NonNull MapboxMap mapboxMap) {
      mapboxMap.setStyle(new Style.Builder().fromUrl(myUrl)));
  }

```

**Comment by topinvestor** [comment] 2019-01-30 17:53
When I execute build, I get an error:
"error: method does not override or implement a method from a supertype"

On 
-> @Override
  public void onMapReady(@NonNull MapboxMap mapboxMap) {

**Comment by tobrun** [comment] 2019-01-30 17:56
One simple project with all files would help a lot.
https://github.com/mapbox/mapbox-android-demo
https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp

**Comment by topinvestor** [comment] 2019-01-30 18:41
I added OnMapReadyCallback which eliminated the compile error: 

public class MainActivity extends AppCompatActivity implements OnMapReadyCallback, PermissionsListener {

---
This is now compiling:
---
  @Override
    public void onMapReady(@NonNull MapboxMap mapboxMap) {
        mapboxMap.setStyle(new Style.Builder().fromUrl(uniqueStyleUrl));
   }
--
But when I run it on the device there is not a map.

I see you updated the examples to 7.0, I would look at them but it is a bit of overwhelming
with all possible cases. I need first to recreate what already worked to be with v. 6

Also because I use my own styles there is nothing in the examples covering my own style.
Could you please help me recreate what I had working in v. 6?

**Comment by tobrun** [comment] 2019-01-31 13:08
> in real life I cannot hard encode Lat/Lng. I don't want my users to see predetermined location.
It should by dynamic as I used before. The real case is that my App gets the Users' location,
then the Lat/Lng, centers the map at this location, puts a Marker on the map to show some info.
This is the minimum functionality in real case scenarios.

There is no requirement adding the following to your xml:

```xml
mapbox:mapbox_cameraTargetLat="50.84749"
mapbox:mapbox_cameraTargetLng="4.35137"
mapbox:mapbox_cameraZoom="12"
``` 

you can later on once you have an instance of mapboxMap change your camera position dynamically. 

>  I use my own styles there is nothing in the examples covering using my own style.

There is no real difference between the default styles or your custom ones. In mapbox studio, you can generate a unique style url, you can pass this style Url to `new Style.Builder().fromUrl("yourcustomurl")`

**Comment by topinvestor** [comment] 2019-01-31 16:56
I followed the instructions but the screen comes black - there is no map.

**Comment by topinvestor** [comment] 2019-01-31 23:57
I tried to look at:
https://github.com/mapbox/mapbox-android-demo

Compiled (need to upgrade to Kotlin 1.3.0), installed on device (Pixel 2)

Then selected Styles examples from menu.

Clicking on any example crashes the App. 

Are these demos even tested?

**Comment by langsmith** [comment] 2019-02-01 00:22
As @tobrun said, please continue the conversation via https://www.mapbox.com/contact/support/#products/android and other Mapbox folks will help you get all set up!  Thanks

**Comment by topinvestor** [comment] 2019-02-01 00:22
> > Are these demos even tested?
> 
> Yes, they are.

The Demo App crashes when I choose any selection from the menu.

**Comment by topinvestor** [comment] 2019-02-01 00:32
> As @tobrun said, please continue the conversation via https://www.mapbox.com/contact/support/#products/android and other Mapbox folks will help you get all set up! Thanks

I already did. 

Please understand that I am in communication with the help channel since August 2018 and things are moving very slow. 

Also understand we need to support iOS and Android and usually do that in parallel.
There are nice examples on your web site but:
1) There is no match between iOS and Android versions.
For example selecting and highlighting a feature - there is an example in iOS, but not for Android.
I managed to make something working for Android but this cost me 3 months back and forth - nothing really helped but I needed to spend 1 week to do it myself.
2) The Android examples on your web site are not updated to latest version.
3) The Android Demos are crashing on physical device.
4) Demos can be nice but there are 1,000 files we need to inspect to stick together
something working for our needs. The web site examples with just one function
are better approach.

Please understand: I like MapBox functionality and would like to use it  but
these are showstoppers. We need to move this project close to live version -
it is 6 months since we first began communication with the help channel.

So I filled out this issue report - seems there is no change of the outcome.

**Comment by topinvestor** [comment] 2019-02-01 01:05
> > Are we supposed to look at examples with which you are targeting China? I am located in USA.
> 
> You can change the demo's BuildVariant to `globalDebug`
> 
> <img alt="screen shot 2019-01-31 at 4 19 34 pm" width="422" src="https://user-images.githubusercontent.com/4394910/52094427-06153d00-2574-11e9-935f-cb8e2b239ef8.png">
> 
> > Clicking on any example crashes the App.
> 
> This is probably happening because you haven't set [your own access token](https://www.mapbox.com/help/how-mapbox-works/access-tokens/) if you're trying to compile the app on your own. More instructions about this are here: https://github.com/mapbox/mapbox-android-demo#running-locally
> 
> You can download and run the app via https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo&hl=en as well
> 
> > Are these demos even tested?
> 
> Yes, they are.

Followed the selecting Global Debug. Compiled, installed on Pixel 2.
A screen to login: entered my data. 

"Loading..." staying, nothing happens.
