### ISSUE TITLE
Crash with Mapbox's MapView on API 17 and API 19

### ISSUE THREAD

**Issue by adolgiy** [mapbox/mapbox-gl-native#10602] opened 2017-11-30 14:59 UTC
**Platform:** 17, 19
**Mapbox SDK version:** 5.2.0

### Steps to trigger behavior
No steps, just try to run the activtity

### Actual behavior
Crashes on startup

### Layout
```
<android.support.design.widget.CoordinatorLayout
    android:id="@+id/container_main"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include layout="@layout/map"/>

</android.support.design.widget.CoordinatorLayout>
```
```
<?xml version="1.0" encoding="utf-8"?>
<merge
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mv_mapbox"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:mapbox_cameraZoom="11"
        app:mapbox_styleUrl="mapbox://styles/mapbox/streets-v10"
        app:mapbox_uiAttribution="false"
        app:mapbox_uiLogo="false"
        app:mapbox_uiRotateGestures="false"
        app:mapbox_uiTiltGestures="false"/>

</merge>
```
###

### Crashlog
```
E: FATAL EXCEPTION: main
   java.lang.RuntimeException: Unable to start activity ComponentInfo{taxi.eskar.eskartaxi/taxi.eskar.eskartaxi.ui.root.RootActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class com.mapbox.mapboxsdk.maps.MapView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
       at android.app.ActivityThread.access$600(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5391)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(Native Method)
    Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.mapbox.mapboxsdk.maps.MapView
       at android.view.LayoutInflater.createView(LayoutInflater.java:613)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:805)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at taxi.eskar.eskartaxi.ui.root.RootActivity.onCreate(RootActivity.kt:65)
       at android.app.Activity.performCreate(Activity.java:5122)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
       at android.app.ActivityThread.access$600(ActivityThread.java:165) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
       at android.os.Handler.dispatchMessage(Handler.java:107) 
       at android.os.Looper.loop(Looper.java:194) 
       at android.app.ActivityThread.main(ActivityThread.java:5391) 
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:525) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
       at dalvik.system.NativeStart.main(Native Method) 
    Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Native Method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:805) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:736) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
       at taxi.eskar.eskartaxi.ui.root.RootActivity.onCreate(RootActivity.kt:65) 
       at android.app.Activity.performCreate(Activity.java:5122) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
       at android.app.ActivityThread.access$600(ActivityThread.java:165) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
       at android.os.Handler.dispatchMessage(Handler.java:107) 
       at android.os.Looper.loop(Looper.java:194) 
       at android.app.ActivityThread.main(ActivityThread.java:5391) 
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:525) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
       at dalvik.system.NativeStart.main(Native Method) 
    Caused by: java.lang.VerifyError: com/mapbox/mapboxsdk/maps/widgets/MyLocationView
       at java.lang.reflect.Constructor.constructNative(Native Method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:459)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at com.mapbox.mapboxsdk.maps.MapView.initialise(MapView.java:125)
       at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:102)
       at java.lang.reflect.Constructor.constructNative(Native Method) 
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
       at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:805) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:736) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
       at taxi.eskar.eskartaxi.ui.root.RootActivity.onCreate(RootActivity.kt:65) 
       at android.app.Activity.performCreate(Activity.java:5122) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
       at android.app.ActivityThread.access$600(ActivityThread.java:165) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
       at android.os.Handler.dispatchMessage(Handler.java:107) 
       at android.os.Looper.loop(Looper.java:194) 
       at android.app.ActivityThread.main(ActivityThread.java:5391) 
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:525) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
       at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by DejanRistic** [comment] 2017-11-30 16:32
Might the duplicate of this guy:
https://github.com/mapbox/mapbox-gl-native/issues/10527

**Comment by adolgiy** [comment] 2017-11-30 17:20
@DejanRistic yes. looks like duplicate. but I still can't get 5.2.1 update.

**Comment by lilykaiser** [comment] 2017-11-30 19:17
Closing as duplicate - we are developing 5.2.1 now! Thanks for the report @adolgiy

**Closed by lilykaiser** 2017-11-30 19:17 UTC
Labels: Android
