### ISSUE TITLE
User location dot dances around during zooming

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2230] opened 2015-09-01 21:34 UTC
With the merge of `perspective` (#2116) the user dot jitters around during zooming — especially at higher zoom levels. Likely not confined to iOS, but we haven't tested this on Android.

@ansis is working on a fix in [`perspective-improved-gestures`](https://github.com/mapbox/mapbox-gl-native/tree/perspective-improved-gestures).

From https://github.com/mapbox/mapbox-gl-native/pull/2207#issuecomment-136864425:
![](https://cloud.githubusercontent.com/assets/17722/9616639/2e8dc362-50b4-11e5-9f94-13edd191bf75.gif)

/cc @incanus @1ec5 @brunoabinader

**Comment by incanus** [comment] 2015-09-01 21:48
Per @1ec5, seems to be a regression from https://github.com/mapbox/mapbox-gl-native/commit/51c93867aeeb34fd423bd0fb85d2cc06f074b88b. 

/cc @ansis

**Comment by incanus** [comment] 2015-09-01 21:49
>  Likely not confined to iOS, but we haven't tested this on Android.

We don't sync any views on Android right now, but do on iOS every frame draw.

**Comment by 1ec5** [comment] 2015-09-01 22:23
@incanus, @ansis has a fix in 3f79c39b7ebf7d04b6f51e47da8f4bb77c635601.

**Comment by incanus** [comment] 2015-09-01 22:26
Ah, thanks for closing the loop @1ec5. Sounding good.

**Comment by 1ec5** [comment] 2015-09-03 18:03
3f79c39b7ebf7d04b6f51e47da8f4bb77c635601 helps, but it doesn’t quite fix the issue. I still see the user dot jiggle while zooming in or out with two-finger tap and slightly while panning around at the lowest zoom levels.

**Comment by 1ec5** [comment] 2015-09-09 21:53
ref #1827

**Comment by 1ec5** [comment] 2015-09-10 21:08
→ #2301

**Closed by 1ec5** 2015-09-10 21:08 UTC
Labels: bug, iOS
