### ISSUE TITLE
Crash on main thread iOS, Swift

### ISSUE THREAD

**Issue by hsavit1** [mapbox/mapbox-gl-native#3186] opened 2015-12-04 04:41 UTC
I've been able to replicate this on multiple projects.

I'm just trying to create a new project with swift. Installed with cocoapods

CoreFoundation`CFStringCompare:
    0x182c9e5a0 <+0>:   stp    x22, x21, [sp, #-48]!
    0x182c9e5a4 <+4>:   stp    x20, x19, [sp, #16]
    0x182c9e5a8 <+8>:   stp    x29, x30, [sp, #32]
    0x182c9e5ac <+12>:  add    x29, sp, #32
    0x182c9e5b0 <+16>:  mov    x19, x2
    0x182c9e5b4 <+20>:  mov    x20, x1
    0x182c9e5b8 <+24>:  mov    x21, x0
    0x182c9e5bc <+28>:  tbnz   x21, #63, 0x182c9e64c     ; <+172>
->  0x182c9e5c0 <+32>:  ldr    x8, [x21]
    0x182c9e5c4 <+36>:  cbz    x8, 0x182c9e61c           ; <+124>
    0x182c9e5c8 <+40>:  adrp   x9, 117069
    0x182c9e5cc <+44>:  add    x9, x9, #8
    0x182c9e5d0 <+48>:  ldr    x9, [x9]
    0x182c9e5d4 <+52>:  cmp    x8, x9
    0x182c9e5d8 <+56>:  b.eq   0x182c9e61c               ; <+124>
    0x182c9e5dc <+60>:  adrp   x9, 117064
    0x182c9e5e0 <+64>:  ldr    x9, [x9, #2296]
    0x182c9e5e4 <+68>:  cmp    x9, #1023
    0x182c9e5e8 <+72>:  b.hi   0x182c9e5fc               ; <+92>
    0x182c9e5ec <+76>:  adrp   x10, 117067
    0x182c9e5f0 <+80>:  add    x10, x10, #0
    0x182c9e5f4 <+84>:  ldr    x22, [x10, x9, lsl #3]
    0x182c9e5f8 <+88>:  b      0x182c9e600               ; <+96>
    0x182c9e5fc <+92>:  movz   x22, #0
    0x182c9e600 <+96>:  cmp    x8, x22
    0x182c9e604 <+100>: b.eq   0x182c9e61c               ; <+124>
    0x182c9e608 <+104>: tbz    w8, #0, 0x182c9e64c       ; <+172>
    0x182c9e60c <+108>: mov    x0, x21
    0x182c9e610 <+112>: bl     0x18831a53c
    0x182c9e614 <+116>: cmp    x0, x22
    0x182c9e618 <+120>: b.ne   0x182c9e64c               ; <+172>
    0x182c9e61c <+124>: ldrb   w8, [x21, #8]
    0x182c9e620 <+128>: movz   w9, #0x5
    0x182c9e624 <+132>: and    w9, w8, w9
    0x182c9e628 <+136>: and    w8, w8, #0x60
    0x182c9e62c <+140>: cmp    w9, #4
    0x182c9e630 <+144>: b.ne   0x182c9e664               ; <+196>
    0x182c9e634 <+148>: and    w9, w8, #0xff
    0x182c9e638 <+152>: add    x8, x21, #16
    0x182c9e63c <+156>: cbz    w9, 0x182c9e644           ; <+164>
    0x182c9e640 <+160>: ldr    x8, [x8]
    0x182c9e644 <+164>: ldrb   w3, [x8]
    0x182c9e648 <+168>: b      0x182c9e678               ; <+216>
    0x182c9e64c <+172>: adrp   x8, 113081
    0x182c9e650 <+176>: ldr    x1, [x8, #808]
    0x182c9e654 <+180>: mov    x0, x21
    0x182c9e658 <+184>: bl     0x18831a29c
    0x182c9e65c <+188>: mov    x3, x0
    0x182c9e660 <+192>: b      0x182c9e678               ; <+216>
    0x182c9e664 <+196>: and    w8, w8, #0xff
    0x182c9e668 <+200>: cbz    w8, 0x182c9e674           ; <+212>
    0x182c9e66c <+204>: ldr    x3, [x21, #24]
    0x182c9e670 <+208>: b      0x182c9e678               ; <+216>
    0x182c9e674 <+212>: ldr    x3, [x21, #16]
    0x182c9e678 <+216>: movz   x2, #0
    0x182c9e67c <+220>: movz   x5, #0
    0x182c9e680 <+224>: mov    x0, x21
    0x182c9e684 <+228>: mov    x1, x20
    0x182c9e688 <+232>: mov    x4, x19
    0x182c9e68c <+236>: ldp    x29, x30, [sp, #32]
    0x182c9e690 <+240>: ldp    x20, x19, [sp, #16]
    0x182c9e694 <+244>: ldp    x22, x21, [sp], #48
    0x182c9e698 <+248>: b      0x182c9e69c               ; CFStringCompareWithOptionsAndLocale

**Comment by friedbunny** [comment] 2015-12-04 07:24
This is a dupe of #3112 — until v3.0.1 is released, make sure CoreTelephony.framework is not linked in your project.

**Comment by hsavit1** [comment] 2015-12-04 15:30
It has nothing to do with the core telephony framework. that framework isnt
linked at all.

The only thing i have done is added the settings bundle and installed
MapBox via Cocoapods. _That's it_

**Comment by 1ec5** [comment] 2015-12-04 15:59
Can you provide the full crash log (in a gist if it's too long)? Also, which devices/simulators are you seeing this on?

**Comment by benmarte** [comment] 2015-12-13 03:06
I'm having the same issue with SDK 3.0.1 I'm following [this](https://www.mapbox.com/help/first-steps-ios-sdk/) tutorial and when I click on build on the Adding A Map section the app crashes on an ipad pro.

What's weird is that it works in the simulator but when I try to test it in the actual device it crashes here is a screenshot so you can see what I encounter when testing on the ipad pro.

Any info is greatly appreciated, thanks.

<img width="1074" alt="screen shot 2015-12-12 at 10 04 08 pm" src="https://cloud.githubusercontent.com/assets/693275/11765235/78602e7c-a11c-11e5-9e69-28046fafc3ac.png">

**Comment by mikemorris** [comment] 2016-02-16 23:18
Reproducing this consistently while attempting to re-add conditional CoreTelephony support, dupe of #3112

**Closed by mikemorris** 2016-02-16 23:18 UTC
Labels: crash
