### ISSUE TITLE
linux-gcc5-release-qt5 on circleci flapping

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#9450] opened 2017-07-07 14:56 UTC
On several occasions the `OfflineDatabase.ConcurrentUse` failed for me, but only on this specific build. No related changes in these branches.

```
[ RUN      ] OfflineDatabase.ConcurrentUse
[WARNING] {memcheck-amd64-}[Database]: Removing existing incompatible offline database
terminate called after throwing an instance of 'mapbox::sqlite::Exception'
  what():  database is locked Unable to fetch row
==2843== 
==2843== Process terminating with default action of signal 6 (SIGABRT)
==2843==    at 0x79B3428: raise (raise.c:54)
==2843==    by 0x79B5029: abort (abort.c:89)
==2843==    by 0x747584C: __gnu_cxx::__verbose_terminate_handler() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==2843==    by 0x74736B5: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==2843==    by 0x7473700: std::terminate() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==2843==    by 0x749ED37: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==2843==    by 0x524B6B9: start_thread (pthread_create.c:333)
==2843==    by 0x7A8482C: clone (clone.S:109)
==2843== 
==2843== HEAP SUMMARY:
==2843==     in use at exit: 6,368,848 bytes in 49,230 blocks
==2843==   total heap usage: 17,425,457 allocs, 17,376,227 frees, 5,124,317,585 bytes allocated
==2843== 
==2843== LEAK SUMMARY:
==2843==    definitely lost: 0 bytes in 0 blocks
==2843==    indirectly lost: 0 bytes in 0 blocks
==2843==      possibly lost: 0 bytes in 0 blocks
==2843==    still reachable: 442,525 bytes in 3,306 blocks
==2843==                       of which reachable via heuristic:
==2843==                         stdstring          : 135 bytes in 3 blocks
==2843==                         length64           : 1,067,208 bytes in 410 blocks
==2843==         suppressed: 5,926,323 bytes in 45,924 blocks
==2843== Reachable blocks (those to which a pointer was found) are not shown.
==2843== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2843== 
==2843== For counts of detected and suppressed errors, rerun with: -v
==2843== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 17393280 from 197)
scripts/valgrind.sh: line 18:  2843 Aborted                 ${VALGRIND_PREFIX}/bin/valgrind $PARAMS $@
Exited with code 134
```

**Comment by tmpsantos** [comment] 2017-07-07 15:04
Duplicate of #9108.

**Closed by tmpsantos** 2017-07-07 15:04 UTC
Labels: build
