### ISSUE TITLE
Add setUserTrackingMode with completionHandler

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#6663] opened 2016-10-11 23:36 UTC
**Platform: iOS**
**Mapbox SDK version: N/A**

Currently, it's not possible to know when the map is done animating after setting the user tracking mode. This makes it impossible to know when you can modify the map state without interrupting setting the tracking mode type.

I propose we had a new method- `-setUserTrackingMode:animated:completionHandler:` which returns a callback after the tracking mode has been set and animation has completed.

/cc @incanus @1ec5

**Comment by incanus** [comment] 2016-10-12 00:06
Per chat, I'm generally 👍 on this, but we should be prepared for complexities like possibly canceling the callback if:

- the map gets moved or zoomed before animation completion
- the user location moves before animation completion
- user tracking mode changes or is disabled before animation completion

This differs from normal animation callbacks since there is a implicit contract here that upon completion firing, the user will be in the center of the map view.

**Comment by 1ec5** [comment] 2016-10-18 21:12
Duplicate of #5840.

**Closed by 1ec5** 2016-10-18 21:12 UTC
Labels: feature, iOS
