### ISSUE TITLE
Supporting User Tracking on macOS

### ISSUE THREAD

**Issue by hyerra** [mapbox/mapbox-gl-native#12942] opened 2018-09-21 23:15 UTC
### Feature Request
The iOS counterpart of the SDK has functionality to track a user's current location. It would be really beneficial if this could also be ported onto the macOS SDK as it is a vital feature when showing a map.
### Configuration

**iOS/macOS versions: Version 10.13.6 (17G65)** 
**Device/simulator models: MacBook Pro (Retina, 13-inch, Early 2015)**
**Xcode version: Xcode 10**

**Comment by 1ec5** [comment] 2018-09-22 04:40
Agreed; duplicate of #4983.

**Closed by 1ec5** 2018-09-22 04:40 UTC
