### ISSUE TITLE
unexpected color for undefined zoom levels in zoom-and-property functions for color and opacity properties

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-native#8838] opened 2017-04-27 19:28 UTC
**Platform:** iOS
**Mapbox SDK version:** v3.5.2

### Steps to trigger behavior

 1. Create a zoom-and-property function for a supported color or opacity property, where the first stop is higher than the minzoom for the layer, and last stop is lower than the maxzoom for that layer.

### Expected behavior

At undefined zoom levels (zoom levels lower than the first stop, and higher than the last stop), style property value will inherit the value from the first or last stop, or the default value if no stops are defined for that data property value.

### Actual behavior

Color: features turn white
Opacity: features are fully opaque

It doesn't look like these are getting assigned `#fff` and `1.0` values respectively – it looks like there's a rendering bug (in shader?), because the features also look thicker and aliased:

![img_9329](https://cloud.githubusercontent.com/assets/5607844/25500344/b10b9dd0-2b5c-11e7-8f6a-2d8682095ae8.PNG)

[Here's a stylesheet](https://gist.github.com/nickidlugash/34807c3e7e3c05d293b17653efd2331a) that has minimal tests for `text-color`, `fill-color`, `line-color` and `line-opacity`.

/cc @mapbox/ios @mapbox/gl

**Comment by jfirebaugh** [comment] 2017-04-27 19:31
I suspect this is a duplicate of #8613, and has been fixed for the next release.

**Comment by nickidlugash** [comment] 2017-04-27 19:57
@jfirebaugh Awesome 👍  When is the next release?

**Closed** 2017-05-23 23:06 UTC
Labels: bug
