### ISSUE TITLE
Map pans in opposite direction of swipe when pitched (upon fast swipe) (iOS)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#9053] opened 2017-05-19 15:46 UTC
**Platform:**
iOS
**Mapbox SDK version:**
3.5.4 (Version used to build latest version of Studio Preview application).
### Steps to trigger behavior

This consistently reproduces with Studio preview application available on iTunes.
 1. Pitch the map.
 2. Swipe down fast. (To reproduce you must swipe down fast.  Hold and drag does not reproduce it).

### Expected behavior
Map should pan in direction of swipe.

### Actual behavior
It pans in opposite direction.

**Comment by boundsj** [comment] 2017-05-19 19:34
This looks like a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/5292. Let's continue to track it there.

**Closed by boundsj** 2017-05-19 19:34 UTC
Labels: iOS
