### ISSUE TITLE
Style rendering strangely in gl-native (tested with macOS SDK and api-gl)

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-native#6620] opened 2016-10-07 00:56 UTC
**Platform:** Mac OSX
**Mapbox SDK version:** 0.1.0
### Steps to trigger behavior
1. Upload Natural Earth 4000m bathymetry data as a tileset
2. Add to a style and publish the style with only the layer styling this tileset
3. View using api-gl or mapbox-gl-native

See the style here: https://gist.github.com/lyzidiamond/673fd0f093a09c7c0be333ef8e837a3d
### Expected behavior

Style is rendered as in Mapbox GL JS
### Actual behavior

At certain zoom levels, the layer covers more area than it should. This is not a tileset simplifcation issue, but a rendering issue. See example in this gif -- first api-gl, then mapbox gl js, then api-gl again.

![fallback](https://cloud.githubusercontent.com/assets/2523165/19175719/1f4df8ba-8bee-11e6-8998-3bf910b66050.gif)

**Comment by danswick** [comment] 2016-10-12 01:24
May be related to https://github.com/mapbox/mapbox-gl-native/issues/962

**Comment by mollymerp** [comment] 2016-10-12 14:43
May be related to https://github.com/mapbox/mapbox-gl-js/issues/3354 as well

**Comment by danswick** [comment] 2016-10-12 16:22
Noting that we're seeing a similar issue in Mapbox Streets when viewing [this area](https://api.mapbox.com/styles/v1/mapbox/streets-v9.html?&fallback=false&title=true&access_token=pk.eyJ1IjoiZGFuc3dpY2siLCJhIjoieUZiWmwtVSJ9.0cPQywdbPVmvHiHJ6NwdXA#8.72/60.3439/21.7235) of islands near Finland. The issue is not present when viewing with Mapbox GL JS, but does appear when requesting [raster tiles](https://api.mapbox.com/styles/v1/mapbox/streets-v9.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZGFuc3dpY2siLCJhIjoieUZiWmwtVSJ9.0cPQywdbPVmvHiHJ6NwdXA&fallback=true#9/60.3613/21.5710) and when viewing on iOS and the macOS SDK (see screenshots below). 

![image](https://cloud.githubusercontent.com/assets/2365503/19318155/5e44e44e-905c-11e6-9c27-4cf6de811e23.png)
_iOS_

![image](https://cloud.githubusercontent.com/assets/2365503/19318134/3c47b100-905c-11e6-9f1c-b5b99851dc44.png)
_macOS_

**Comment by vhaze** [comment] 2016-10-18 11:42
Any news on this?
Is this someting we can work-around as for the time being?

**Comment by springmeyer** [comment] 2017-01-07 02:57
Proposed fix for this problem is at #7621.

**Comment by jfirebaugh** [comment] 2017-02-09 16:41
Merged #7621.

**Closed by jfirebaugh** 2017-02-09 16:41 UTC
Labels: Core GL
