### ISSUE TITLE
[iOS] Concurrent downloading of several offline packs

### ISSUE THREAD

**Issue by Gurbo** [mapbox/mapbox-gl-native#5842] opened 2016-08-02 12:51 UTC
Hi guys! I have an array of location points 
(something like 53.889599, 27.556780, 53.889778, 27.557421, 53.889320, 27.559839 and so on). I want to download MGLOfflineRegion for every of this point simultaneousy so I create NSOperation for every of points from array and in main-method of this operation wrote the code which addPackForRegion. But it works bad - every resource of offline pack downloads many times. I think that the problem is that we use [MGLOfflineStorage sharedOfflineStorage] singletone, not unique MGLOfflineStorage for each operation. How can I resolve this issue? Thanks!

**Comment by halset** [comment] 2016-08-02 22:37
I am doing something similar, but just add all the (~1000) packs from the same thread. It works pretty well except for the map view not beeing able to download tiles when the user zooms or pans. This is described in #4414.

**Comment by 1ec5** [comment] 2016-08-03 01:49
> every resource of offline pack downloads many times

I assume you're referring to the fact that progress updates are coming in for these packs that start at 0% and continue upwards from there. Rest assured, all that's happening is that the SDK is going through its "bill of materials" (so to speak), checking whether each resource is already downloaded or not. Multiple overlapping packs definitely should not be redownloading resources. If you find evidence of redundant network requests by sniffing your application, please let us know.

There is no way to create an MGLOfflineStorage for each pack you want to download. MGLOfflineStorage is the in-memory representation of the on-disk cache, which holds all offline resources as well as resources cached in the course of using an MGLMapView normally. There can only be one cache file on disk, so creating multiple instances of MGLOfflineStorage would lead to contention for that one database file.

**Comment by Gurbo** [comment] 2016-08-03 06:53
@halset so, did you download this 1000 packs concurrently or one-by-one?  I need to download them as fast as the MapBox can. Can you show a piece of code? @1ec5 so does any variant to simultaneously download a lot of packs exist? Thanks

**Comment by halset** [comment] 2016-08-03 21:37
@Gurbo I add the pack one by one and then OfflineDownload look in the database for existing resources and create lots of request objects that are then handled. Only a few http(s) requests are handled concurrently. It works pretty well except for #4414.

**Comment by jfirebaugh** [comment] 2016-09-12 17:55
Closing; I believe the concurrent download behavior is working as intended.

**Closed by jfirebaugh** 2016-09-12 17:55 UTC
