### ISSUE TITLE
Flicker and artifacting on FillLayer after returning from background

### ISSUE THREAD

**Issue by cvance** [mapbox/mapbox-gl-native#11877] opened 2018-05-10 18:44 UTC
**Platform:** Android
**Mapbox SDK version:** 6.1.1

### Steps to trigger behavior

 1. Add new geojsonsource to map
 2. Add new FillLayer using geojsonsource to map
 3. Zoom in and out (to verify no flickering/artifacts)
 3. Home out
 4. Re-open app
 5. Zoom in and out, see flickering/artifacts

Sample code:
https://gist.github.com/cvance/1a46db588025076f8d82431b26195291

Demonstration Video:
https://imgur.com/QR9kUCn

**Comment by cvance** [comment] 2018-05-17 18:29
Bump?

**Comment by vanshg** [comment] 2018-05-24 20:44
@tobrun Any ideas?

**Comment by femski** [comment] 2018-06-05 15:11
I am also seeing significant amount of flicker and artifacts since I updated my code to latest Mapbox master sometime in the few weeks. 

Same style works fine in GL JS but has significant amount of flicker and artifacts in Native. 

I thought it was bad geometry but I have now done considerable amount of topological clearing and simplification via GRASS and PostGIS but flickers continue.

I can upload my style to mapbox if necessary.

**Comment by LukasPaczos** [comment] 2018-07-04 13:56
The issue also arises for the `CircleLayer` as seen below, no need for reopening the app mentioned in the OP:
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/16925074/42280705-cadf40f0-7fa1-11e8-8694-e7c19b26dff9.gif)

Bisecting points to https://github.com/mapbox/mapbox-gl-native/commit/ed5438fc21672e838947c06669dd44051ce24c81 (https://github.com/mapbox/mapbox-gl-native/pull/10548).

/cc @brunoabinader @kkaefer

**Comment by kkaefer** [comment] 2018-07-04 14:09
Same underlying issue as https://github.com/mapbox/mapbox-gl-js/issues/6768: We're not clipping circle layers, and we aren't deduplicating features from overlapping tiles that are rendered into the same position (e.g. one parent child and one child tile containing the same point).

**Comment by kkaefer** [comment] 2018-07-04 14:10
https://github.com/mapbox/mapbox-gl-native/pull/10548 likely didn't introduce this bug but exacerbates it due to parent tiles being available earlier so that they can collide with child tiles.

**Comment by dsuresh-ap** [comment] 2018-07-13 13:57
Is there any planned fix for this issue? It is the only thing holding us from our Layer API changes.

**Comment by cvance** [comment] 2018-07-13 16:55
This has blocked our apps from upgrading to 6.x.x

**Comment by mollymerp** [comment] 2018-07-31 23:54
I can't reproduce the fill-layer flicker using just the glfw view, so there might be something else going on there on the android side.

I can reproduce the circle layer flicker. I can get rid of 90% of flickering by limiting parent tile retention for geojson sources to 1 ZL below the camera zoom. I will test that solution in with the android location plugin tomorrow. I think complete fix will require manual vertex clipping for tiles with an overlapping parent loaded which may have performance implications.

**Comment by cvance** [comment] 2018-08-01 00:01
I believe you are right about it being on the android side. I dont know that we saw it on iOS. However I do not think its limited to geojson sources. We see it with vector sources, if not worse.

**Comment by dsuresh-ap** [comment] 2018-08-17 15:55
@mollymerp did the last PR fix the issue or are there other issues involved. I just updated to 6.4.0 and I still see some issues.

[Recording](https://drive.google.com/file/d/1jrSV-B3wOR9tjmQpJG2_pDDXAGuelKVF/view?usp=sharing)

**Comment by cvance** [comment] 2018-08-17 16:33
I'm experiencing the same. I'm continuing to investigate but I cannot track down the source of this issue as it happens with our app using vector tiles. 

However on the initial example I posted, I have discovered more information. In that example, the flickering & artifacting only occurs after I background the app then re-open it. It appears the problem stems from MapView's onStop() method, when it calls mapRenderer.onStop(). If I disable this call I do not see any rendering issues when the app returns to the foreground.

**Comment by julianrex** [comment] 2018-08-17 17:29
@kkaefer @mollymerp Wondering if the root cause of this could also be the explanation for https://github.com/mapbox/mapbox-gl-native/issues/12452

**Comment by kkaefer** [comment] 2018-08-20 09:49
@julianrex no, I think that's unlikely. This issue is about circle layers that appear twice, while the other is about line layers that don't seem to be tiled correctly.

**Comment by dsuresh-ap** [comment] 2018-08-28 14:42
@tobrun We are still seeing the issue on 6.5.0-alpha.1. No backgrounding needed to trigger it. While zooming there is flickering until the loading of the tile under stops.

I thought it might have been the opacity that we added but as you can see in the recording below we removed it from the rectangle and there is still artifacts.

[Recording](https://drive.google.com/file/d/1OFtm2OqH4GVpBrPi6st8jzGp3t8WcGkK/view?usp=sharing)

**Comment by tobrun** [comment] 2018-08-28 15:25
Confirming that I'm indeed able to replicate it with code from OP, not same issue as with https://github.com/mapbox/mapbox-gl-native/issues/12586.

**Comment by LukasPaczos** [comment] 2018-09-04 08:28
I'm able to reproduce with the [`LatLngBoundsForCameraActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/LatLngBoundsForCameraActivity.java).

![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/16925074/45019671-355b6880-b02d-11e8-843d-f07986eada7d.gif)

**Comment by mollymerp** [comment] 2018-09-27 00:50
consolidating this issue with other related ones over at #12981

**Closed by mollymerp** 2018-09-27 00:50 UTC
Labels: Android, Core, bug
