### ISSUE TITLE
Lag in Map Render

### ISSUE THREAD

**Issue by skydeveloper9** [mapbox/mapbox-gl-native#13953] opened 2019-02-20 11:49 UTC
hi
i use mapbox sdk version 6.2 
it's Great Version and it work very smoothly.

when update to latest version 7.1.2 and fast zoom (zoom in / zoom out) (with two finger) in city place, make tick and Lagging

Older Version ( 6.2.0 ) It works smoothly
I also tested version 7.2.0. lag exist 

how can i Fix this ? or You Fix this :-)

My Device is Samsung Galaxy S8

**Comment by tobrun** [comment] 2019-02-22 09:00
Thank you for reaching out and using our products @skydeveloper9. Questions about why is this slow aren't really actionable to us. Do you have data backing up these claims? a video clearly showing the issue? 

For now I'm closing this issue as not actionable, we continuously try to make our products better and faster. if you have some data to help us determine the root cause, I'm happy to reopen this. Thanks again for using Mapbox.

**Closed by tobrun** 2019-02-22 09:00 UTC
Labels: Android, needs information

**Comment by skydeveloper9** [comment] 2019-02-24 15:24
hi again.
i record video with 2 device first video recorded on samsung j7
and second video recorded in Galaxy S8

i install mapbox demo app from play store map smoothly working but when i compile mapbox sdk lag exist
[Uploading videos.zip…]()

whats the problem

mapbox demo version 7.1.2
compiled version 7.1.2


video attached
-------------------
[video_2.zip](https://github.com/mapbox/mapbox-gl-native/files/2898030/video_2.zip)
[video_1.zip](https://github.com/mapbox/mapbox-gl-native/files/2898037/video_1.zip)
