### ISSUE TITLE
Crash when mapView.selectAnnotation is called.

### ISSUE THREAD

**Issue by agugel** [mapbox/mapbox-gl-native#11616] opened 2018-04-06 07:05 UTC
I get some crash reports for my iOS apps using MapBox 3.7.6 in production. 

These are the lines of code:

` DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(500)) {
                        if let parkAnnotation = self.parkId2parkAnnotation[park.parkId] {
                            self.mapView.selectAnnotation(parkAnnotation, animated: true)
                        }
                    }
`
This is the stack trace shown by XCode

![image](https://user-images.githubusercontent.com/1220641/38407282-253e3bb0-3979-11e8-9bfb-5c02061923d6.png)

**Platform:**
iOS

**Mapbox SDK version:**
3.7.6

### Steps to trigger behavior

I can only provide the data shown by XCode's crash reporting.

### Expected behavior

No crash. The crashes did not occur with Map Box 3.7.5

### Actual behavior

crash when using MapBox 3.7.6 (iOS)

**Comment by fabian-guerra** [comment] 2018-04-30 19:31
Hi, @agugel. Thank you for using Mapbox. I am sorry to hear you are having some issues. I am not able to reproduce this issue following the steps you mentioned. Could you please try using our latest [version](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.0.0) or provide a test app?

**Comment by fabian-guerra** [comment] 2018-05-03 13:55
Hi, @agugel. I'm going to close this issue. Please feel free to reopen it and add more information.

**Closed by fabian-guerra** 2018-05-03 13:55 UTC
Labels: annotations, crash, iOS, needs information
