### ISSUE TITLE
Constants in filter expressions no longer work.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#758] opened 2015-01-15 23:10 UTC
This is a regression bug. It used to work prior to the changes in filter expression syntax.
For e.g. the following no longer works.

 "filter": [ "<=", "real0",  "@my_constant_depth"],

The reason it no longer works because replaceConstant is no longer being called for all values in the filter array. I've verified in my local sandbox that changing parseBinaryFilter to call replaceConstant addresses the issue.

**Comment by jfirebaugh** [comment] 2015-01-15 23:26
This is by design; constants were not intended to be resolved in filters and the previous behavior was a bug.

**Closed by jfirebaugh** 2015-01-15 23:26 UTC
