### ISSUE TITLE
[android] JNI ERROR (app bug): weak global reference table overflow (max=51200)

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-gl-native#10583] opened 2017-11-28 20:17 UTC
**Android**: 7.1.1, API 25
**Maps SDK Version**: `5.2.0`

Using the navigation UI, I've experienced this crash at startup / after rotation.  The UI locks up for ~5 seconds before crashing:

```
11-28 15:10:36.957 8225-8225/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-28 15:10:36.958 8225-8225/? A/DEBUG: Build fingerprint: 'OnePlus/OnePlus3/OnePlus3T:7.1.1/NMF26F/10122113:user/release-keys'
11-28 15:10:36.958 8225-8225/? A/DEBUG: Revision: '0'
11-28 15:10:36.958 8225-8225/? A/DEBUG: ABI: 'arm64'
11-28 15:10:36.958 8225-8225/? A/DEBUG: pid: 8067, tid: 8125, name: Thread-44690  >>> com.mapbox.services.android.navigation.testapp <<<
11-28 15:10:36.958 8225-8225/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-28 15:10:36.963 8225-8225/? A/DEBUG: Abort message: 'art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): weak global reference table overflow (max=51200)'
11-28 15:10:36.963 8225-8225/? A/DEBUG:     x0   0000000000000000  x1   0000000000001fbd  x2   0000000000000006  x3   0000000000000008
11-28 15:10:36.963 8225-8225/? A/DEBUG:     x4   0000000000000177  x5   8080000000000000  x6   0000000000008080  x7   feff666e6b61686b
11-28 15:10:36.963 8225-8225/? A/DEBUG:     x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
11-28 15:10:36.963 8225-8225/? A/DEBUG:     x12  ffffffffffffffff  x13  ffffffffffffffff  x14  ffffffffff000000  x15  ffffffffffffffff
11-28 15:10:36.963 8225-8225/? A/DEBUG:     x16  0000007fa0851ee0  x17  0000007fa07fb984  x18  0000000000000000  x19  0000007f79bf44f8
11-28 15:10:36.963 8225-8225/? A/DEBUG:     x20  0000000000000006  x21  0000007f79bf4450  x22  000000000000000b  x23  0000007f9d785928
11-28 15:10:36.963 8225-8225/? A/DEBUG:     x24  000000000000000a  x25  ffffffffffffffff  x26  0000000000000abd  x27  0000007f79bf3571
11-28 15:10:36.963 8225-8225/? A/DEBUG:     x28  0000007f9d7fc760  x29  0000007f79bf3470  x30  0000007fa07f8e14
11-28 15:10:36.963 8225-8225/? A/DEBUG:     sp   0000007f79bf3450  pc   0000007fa07fb98c  pstate 0000000060000000
11-28 15:10:36.978 8225-8225/? A/DEBUG: backtrace:
11-28 15:10:36.978 8225-8225/? A/DEBUG:     #00 pc 000000000006b98c  /system/lib64/libc.so (tgkill+8)
11-28 15:10:36.978 8225-8225/? A/DEBUG:     #01 pc 0000000000068e10  /system/lib64/libc.so (pthread_kill+64)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #02 pc 00000000000242e8  /system/lib64/libc.so (raise+24)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #03 pc 000000000001cd54  /system/lib64/libc.so (abort+52)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #04 pc 0000000000433f10  /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+456)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #05 pc 00000000000e5918  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1576)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #06 pc 000000000024faac  /system/lib64/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+308)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #07 pc 00000000002f2db8  /system/lib64/libart.so (_ZN3art9JavaVMExt16AddWeakGlobalRefEPNS_6ThreadEPNS_6mirror6ObjectE+80)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #08 pc 0000000000352780  /system/lib64/libart.so (_ZN3art3JNI16NewWeakGlobalRefEP7_JNIEnvP8_jobject+600)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #09 pc 000000000010382c  /system/lib64/libart.so (_ZN3art8CheckJNI6NewRefEPKcP7_JNIEnvP8_jobjectNS_15IndirectRefKindE+708)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #10 pc 000000000030c200  /system/lib64/libart.so (_ZN3art14ObjectRegistry11InternalAddINS_6mirror6ObjectEEEmNS_6HandleIT_EE+1104)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #11 pc 000000000030caf4  /system/lib64/libart.so (_ZN3art14ObjectRegistry3AddEPNS_6mirror6ObjectE+152)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #12 pc 000000000016ab88  /system/lib64/libart.so (_ZN3art3Dbg11GetThreadIdEPNS_6ThreadE+632)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #13 pc 00000000002fd318  /system/lib64/libart.so (_ZN3art4JDWP9JdwpState16PostThreadChangeEPNS_6ThreadEb+872)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #14 pc 00000000001796dc  /system/lib64/libart.so (_ZN3art3Dbg15PostThreadStartEPNS_6ThreadE+48)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #15 pc 0000000000450d20  /system/lib64/libart.so (_ZN3art6Thread6AttachEPKcbP8_jobjectb+2560)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #16 pc 000000000043370c  /system/lib64/libart.so (_ZN3art7Runtime19AttachCurrentThreadEPKcbP8_jobjectb+112)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #17 pc 00000000002f6f50  /system/lib64/libart.so (_ZN3art3JII27AttachCurrentThreadInternalEP7_JavaVMPP7_JNIEnvPvb+296)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #18 pc 000000000010b374  /system/lib64/libart.so (_ZN3art8CheckJII19AttachCurrentThreadEP7_JavaVMPP7_JNIEnvPv+132)
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #19 pc 00000000000d1ae4  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #20 pc 00000000000d19d4  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #21 pc 00000000000b23cc  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #22 pc 000000000026c810  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #23 pc 00000000003e1988  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.979 8225-8225/? A/DEBUG:     #24 pc 00000000003e0a90  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.980 8225-8225/? A/DEBUG:     #25 pc 00000000003e03a0  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.980 8225-8225/? A/DEBUG:     #26 pc 00000000003c4e70  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.980 8225-8225/? A/DEBUG:     #27 pc 000000000026c940  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.980 8225-8225/? A/DEBUG:     #28 pc 000000000026ca74  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.980 8225-8225/? A/DEBUG:     #29 pc 000000000033b8e0  /data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so
11-28 15:10:36.980 8225-8225/? A/DEBUG:     #30 pc 0000000000068618  /system/lib64/libc.so (_ZL15__pthread_startPv+196)
11-28 15:10:36.980 8225-8225/? A/DEBUG:     #31 pc 000000000001df68  /system/lib64/libc.so (__start_thread+16)
```

cc @ivovandongen @tobrun

**Comment by tobrun** [comment] 2017-11-29 06:38
Thank you for the report @danesfeder, seems like the speculative fix in #10415 didn't resolve it.

**Comment by ivovandongen** [comment] 2017-11-29 11:46
@danesfeder Is the one plus 3 the only device you see this on?

Also, could explain in a bit more detail how to reproduce?

**Comment by danesfeder** [comment] 2017-11-29 18:03
@ivovandongen Unfortunately, I haven't been able to consistently reproduce - even when rotating / or starting & closing rapidly.  I've definitely seen it on more than the one plus 3.  Sorry, I know that doesn't help much at all.  

One thing I did notice is that the trace I posted above was only a small snippet from what looked like a much bigger stacktrace from the native code.  I can post the whole thing but thought this was the only thing valuable to you.

**Comment by danesfeder** [comment] 2017-11-29 19:19
[crash.txt](https://github.com/mapbox/mapbox-gl-native/files/1515194/crash.txt)

^ @ivovandongen this is the part I didn't copy - but always shows before the part I pasted above.  No idea if this helps or not.

**Comment by Alamgir** [comment] 2017-12-08 22:57
currently having this issue on a Pixel C tablet:

```
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492] Runtime aborting...
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492] Aborting thread:
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492] "Thread-43586" prio=10 tid=30 Runnable
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   | group="" sCount=0 dsCount=0 flags=0 obj=0x13040000 self=0x7da5124400
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   | sysTid=5751 nice=-10 cgrp=default sched=0/0 handle=0x7da76034f0
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   | state=R schedstat=( 7731868814 1826021529 42592 ) utm=596 stm=176 core=1 HZ=100
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   | stack=0x7da7509000-0x7da750b000 stackSize=1005KB
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   | held mutexes= "abort lock" "JNI weak global reference table lock" "ObjectRegistry lock" "mutator lock"(shared held)
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #00 pc 000000000039d278  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+212)
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #01 pc 00000000004645d0  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+348)
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #02 pc 000000000044bc24  /system/lib64/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+52)
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #03 pc 000000000044ba40  /system/lib64/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+456)
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #04 pc 000000000043d810  /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+172)
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #05 pc 000000000043e0c0  /system/lib64/libart.so (_ZN3art7Runtime7AborterEPKc+24)
12-08 14:53:17.560 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #06 pc 000000000052919c  /system/lib64/libart.so (_ZN7android4base10LogMessageD1Ev+912)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #07 pc 000000000024ded8  /system/lib64/libart.so (_ZN3art22IndirectReferenceTable3AddENS_15IRTSegmentStateENS_6ObjPtrINS_6mirror6ObjectEEE+780)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #08 pc 00000000002d9654  /system/lib64/libart.so (_ZN3art9JavaVMExt16AddWeakGlobalRefEPNS_6ThreadENS_6ObjPtrINS_6mirror6ObjectEEE+68)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #09 pc 0000000000359784  /system/lib64/libart.so (_ZN3art3JNI16NewWeakGlobalRefEP7_JNIEnvP8_jobject+576)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #10 pc 0000000000109ef8  /system/lib64/libart.so (_ZN3art8CheckJNI6NewRefEPKcP7_JNIEnvP8_jobjectNS_15IndirectRefKindE+712)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #11 pc 00000000002f1dec  /system/lib64/libart.so (_ZN3art14ObjectRegistry11InternalAddINS_6mirror6ObjectEEEmNS_6HandleIT_EE+1028)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #12 pc 00000000002f2abc  /system/lib64/libart.so (_ZN3art14ObjectRegistry3AddENS_6ObjPtrINS_6mirror6ObjectEEE+108)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #13 pc 0000000000171d2c  /system/lib64/libart.so (_ZN3art3Dbg11GetThreadIdEPNS_6ThreadE+604)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #14 pc 00000000002e3798  /system/lib64/libart.so (_ZN3art4JDWP9JdwpState16PostThreadChangeEPNS_6ThreadEb+520)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #15 pc 0000000000183b1c  /system/lib64/libart.so (_ZN3art3Dbg26DbgThreadLifecycleCallback11ThreadStartEPNS_6ThreadE+48)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #16 pc 000000000044c61c  /system/lib64/libart.so (_ZN3art16RuntimeCallbacks11ThreadStartEPNS_6ThreadE+48)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #17 pc 0000000000460f2c  /system/lib64/libart.so (_ZN3art6Thread6AttachEPKcbP8_jobjectb+1672)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #18 pc 000000000043d15c  /system/lib64/libart.so (_ZN3art7Runtime19AttachCurrentThreadEPKcbP8_jobjectb+84)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #19 pc 00000000002de068  /system/lib64/libart.so (_ZN3art3JII27AttachCurrentThreadInternalEP7_JavaVMPP7_JNIEnvPvb+268)
12-08 14:53:17.561 5631-5751/com.chariot.driver.debug A/zygote64: runtime.cc:492]   native: #20 pc 0000000000114fdc  /system/lib64/libart.so (_ZN3art8CheckJII19AttachCurrentThreadEP7_JavaVMPP7_JNIEnvPv+124)
```

**Comment by tobrun** [comment] 2018-01-18 12:45
closing as duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10528

**Closed by tobrun** 2018-01-18 12:45 UTC
Labels: Android, crash
