### ISSUE TITLE
Crash with Stops Dictionaries

### ISSUE THREAD

**Issue by iDevid** [mapbox/mapbox-gl-native#11569] opened 2018-03-30 14:53 UTC
**Platform:** iOS
**Mapbox SDK version:** Last

### Steps to trigger behavior

 1. Create an empty stops dictionary
 2. Create a MGLStyleFunction with that stop dictionary
 3. Add a default value in the options

### Expected behavior
I mighty expect that if a dictionary (that can be filled at runtime) is empty will be passed to a MGLStyleFunction, it will not cause a crash but will load the default Value

### Actual behavior
Crash

**Comment by jfirebaugh** [comment] 2018-03-30 14:55
Duplicate of #9539.

**Closed by jfirebaugh** 2018-03-30 14:55 UTC
