### ISSUE TITLE
iOS: wrong openGL rendering if another layer also uses openGL

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#11946] opened 2018-05-18 13:36 UTC
**Platform: iOS**
**Mapbox SDK version: 3.7.6**

### Steps to trigger behavior

 1. Launch our app showing a mapbox map
 2. Open an view controller showing 360 view (with openGL)
 3. Close the view controller

### Expected behavior
The map is showing correctly

### Actual behavior
The map shows strange behaviors (labels not correctly rendered as shown in the screenshot).

More info.
We use a view controller, which view is from class CAEAGLLayer, to show a 360° immersive view.
Once we close this view controller, we see now some issues in the mapbox map layer drawing. It was not the case with sdk v3.5.x, but not sure if this issue is new.

Is there something special to do on Mapbox SDK to be able to use openGL in parallel with Mapbox ?
I'm not an expert in openGL, but we also saw this issue with another sdk we integrate which also uses openGL.

Thanks
![image uploaded from ios](https://user-images.githubusercontent.com/8179069/40237556-196b67a0-5ab1-11e8-9536-a2921bdd0473.png)

**Comment by julianrex** [comment] 2018-05-18 13:59
Thanks for reporting this issue @RomainQuidet - do you have a sample project you can provide that illustrates this problem?

**Comment by RomainQuidet** [comment] 2018-05-18 14:15
Hi, for the moment it will not be easy as I can't share my customer 360° lib. 
I'll try to make a simple demo app to see if it can show the issue too.

**Comment by julianrex** [comment] 2018-05-18 15:03
That would be great - thanks so much!

**Comment by RomainQuidet** [comment] 2018-06-01 12:08
Hi,
I've create a test app based on https://www.raywenderlich.com/3664/opengl-tutorial-for-ios-opengl-es-2-0 example code.
You can find an already available port in Swift here: https://github.com/webfrogs/OpenGL-es-iOS-swift4-Demo

When showing the view controller with the openGL view, after 2 / 3 times, the map starts to show a strange rendering (see screenshot).

I added the source code I modified here if you want to replay it. Just add at root directory the Mapbox.framework. I used 3.7.8 as it's the one we use.

**Comment by RomainQuidet** [comment] 2018-06-01 12:08
![img_0938](https://user-images.githubusercontent.com/8179069/40840028-46521cf6-65a5-11e8-8b45-c44dd3c8dcb2.PNG)

**Comment by RomainQuidet** [comment] 2018-06-01 12:09
[OpenGL-es-iOS-swift4-Demo.zip](https://github.com/mapbox/mapbox-gl-native/files/2062611/OpenGL-es-iOS-swift4-Demo.zip)
The code I used to show the map turning green !

**Comment by julianrex** [comment] 2018-06-01 16:39
Great! Thanks so much @RomainQuidet

**Comment by ChrisLoer** [comment] 2018-06-05 17:53
Hi @RomainQuidet, I loaded up your test app and I don't actually see the artifacts from your screen shots, but I do get periodic crashes in our gl code. Both behaviors look consistent with a GL context accidentally being shared between `MGLMapView` and your `OpenGLView`. I haven't really done much debugging of your example code, but with a quick glance it looks like you're setting the EAGLContext (`EAGLContext.setCurrent(_context)`) at init but maybe not on subsequent render calls? The equivalent context-setting code in our iOS SDK is:

https://github.com/mapbox/mapbox-gl-native/blob/6eee8729554ed778491c52bda46cdcbec61b9c95/platform/ios/src/MGLMapView.mm#L6163-L6181

Activation/deactivation calls wrap all of our render calls, so that we can be sure we're rendering to our own context.

**Comment by ChrisLoer** [comment] 2018-06-06 16:40
> I added breakpoints in those activate() and deactivate() methods in mapbox demo app, whatever I do those methods are never called.

Ah good point, I forgot about:

https://github.com/mapbox/mapbox-gl-native/blob/2da57bd1576c99ff4305cab7b6ad8c1a39ac2fa7/platform/darwin/src/MGLRendererFrontend.h#L47-L53

and:

https://github.com/mapbox/mapbox-gl-native/blob/2da57bd1576c99ff4305cab7b6ad8c1a39ac2fa7/src/mbgl/renderer/backend_scope.cpp#L41-L50

The `MGLRenderFrontEnd` uses an "implicit" backend scope. The comments say:

> Creating an "Implicit" scope tells Mapbox GL that the supporting windowing system has already activated the GL Backend and that no further actions are required.

Here's a good point for me to confess that I don't know much about the iOS GL backend implementations. @kkaefer might be able to chime in with more detail here. I'm not sure exactly how your explicit `EAGLContext.setCurrent` calls interact with the implicit activation we're relying on, but my first guess would be that if you set the context before a render call you should be unsetting it when you're done in order to co-exist well on the same thread as an MGLMapView.

... and although I wouldn't consider it authoritative, I did a quick test in your app of adding an explicit `EAGLContext.setCurrent(nil)` at the end of initialization, and then wrapped the `render` call in set/release context calls, and I no longer see any crashes or rendering artifacts in your app.

As far as I can tell, there's not a bug here preventing `MGLMapView` from co-existing with other uses of OpenGL, so I'm going to close this issue, but feel free to re-open if I'm missing something.

**Closed by ChrisLoer** 2018-06-06 16:40 UTC
Labels: Core, bug, iOS, needs information

**Comment by RomainQuidet** [comment] 2018-06-07 07:10
Thanks for helping us on this issue.
Can you explain a little more the meaning of 

> then wrapped the render call in set/release context 

Even if there is no bug in MGLMapView, there is maybe some documentation to write on how we can make MGLMapView coexist with other openGL views (for no openGL experts!).
Thanks !

**Comment by kkaefer** [comment] 2018-06-07 09:57
@RomainQuidet The code in https://www.raywenderlich.com/3664/opengl-tutorial-for-ios-opengl-es-2-0 is broken because it assumes that it's the only OpenGL-based view that is active in the application and it doesn't ensure that it activates its own EAGLContext before issuing OpenGL commands. That means OpenGL commands in that view accidentally mangle state in Mapbox GL's context, and there's nothing that we can do to prevent it (other than intentionally setting the current EAGLContext to nil every time we're done drawing).

Instead of hand-crafting your OpenGL view, I recommend basing your View on [`GLKView`](https://developer.apple.com/documentation/glkit/glkview) and [`GLKViewController`](https://developer.apple.com/documentation/glkit/glkviewcontroller), which handles all of the setup automatically, including managing the state of the active OpenGL context. You can then implement [`GLKViewDelegate`](https://developer.apple.com/documentation/glkit/glkviewdelegate), and specifically `- (void)glkView:(GLKView *)view drawInRect:(CGRect)rect` to issue your OpenGL drawing commands.
