### ISSUE TITLE
custom http request headers

### ISSUE THREAD

**Issue by farfromrefug** [mapbox/mapbox-gl-native#11283] opened 2018-02-22 08:04 UTC
For some online sources it might be necessary to set custom headers like a custom userAgent.
An example is IGN in France.
Would be nice to see this in Mapbox.

Thanks

**Comment by asheemmamoowala** [comment] 2018-02-22 19:58
Duplicate of #11199. 

You may want to try the swizzling solution posted in [#11199(comment)](https://github.com/mapbox/mapbox-gl-native/issues/11199#issuecomment-365929142)

**Closed by asheemmamoowala** 2018-02-22 19:58 UTC

**Comment by farfromrefug** [comment] 2018-02-23 09:44
sorry @asheemmamoowala did not see that issue!
