### ISSUE TITLE
Symbol layer icons and text on different Z-indices

### ISSUE THREAD

**Issue by afischer** [mapbox/mapbox-gl-native#9752] opened 2017-08-10 15:56 UTC
Map symbol layers with both `icon-image`s and `text-field`s will correctly place the text on a higher z-index than the icon, but overlapping icons may interfere with one another as the text of icons "below" another can overlap with the icon "above." Here's an example:

![screen shot 2017-08-10 at 11 42 32 am](https://user-images.githubusercontent.com/5422397/29179503-9f426148-7dc2-11e7-9313-0dd5101e852a.png)
![screen shot 2017-08-10 at 11 55 39 am](https://user-images.githubusercontent.com/5422397/29179591-e6e8f124-7dc2-11e7-973b-e940ee6c7799.png)

**Platform:** iOS, Web (Others not tested)
**Mapbox SDK version:** `GL-JS 0.39.1`

### Steps to trigger behavior

 1. Create a map with a `symbol` layer that also has text.
 2. Allow overlap on these layers, and scroll out.

### Expected behavior
The symbols act if they were a single element, with the text "one" z-index above the icon.

### Actual behavior
Unpredictable behavior of text.

**Comment by jfirebaugh** [comment] 2017-08-10 16:04
I think you meant to open this issue in the Mapbox GL JS repository -- but in any case, it's a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/4064.

**Closed by jfirebaugh** 2017-08-10 16:04 UTC
