### ISSUE TITLE
Support for runtime style property functions

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#6090] opened 2016-08-19 13:28 UTC
Spec: https://www.mapbox.com/mapbox-gl-style-spec/#types-function-zoom-property

Parity with: https://github.com/mapbox/mapbox-gl-js/pull/2938.
Related test: https://github.com/mapbox/mapbox-gl-test-suite/pull/135.

# line-color/property-function
| Actual | Expected |
| --- | --- |
| ![actual](https://cloud.githubusercontent.com/assets/76133/17811137/c7fbdd28-6629-11e6-886f-1b57bb028029.png) | ![expected](https://cloud.githubusercontent.com/assets/76133/17811138/cd7a1fa8-6629-11e6-91cc-a873f938b7cf.png) |

**Comment by 1ec5** [comment] 2016-08-19 15:05
Duplicate of #4860.

**Closed by 1ec5** 2016-08-19 15:05 UTC
Labels: feature, GL JS parity
