### ISSUE TITLE
Compass/logo/attribution control views’ constraints are ambiguous on iOS 10

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#6260] opened 2016-09-06 20:36 UTC
**Platform:** iOS 10 (beta 8)
**Mapbox SDK version:** v3.3.0 — v3.4.0-alpha.4

On iOS 10, our UI elements are not respecting content insets:

![img_3584](https://cloud.githubusercontent.com/assets/1198851/18289486/924b7062-744d-11e6-9b9f-8dab89a53ba0.png)

- The compass can be overlapped by the status bar.
- Toolbars hide the Mapbox logo and attribution button. 

Navigation bar insets continue to work as expected, pushing the compass down.

Xcode’s View Hierarchy debugger flags these views with **“Vertical position is ambiguous.”**

![screen shot 2016-09-06 at 4 34 52 pm](https://cloud.githubusercontent.com/assets/1198851/18290039/e992fadc-744f-11e6-8689-b26862f3eaba.png)

/cc @boundsj @1ec5

**Comment by friedbunny** [comment] 2016-09-06 20:44
As I dig into this, it may just be a problem with Treble’s storyboard setup, which IB says has a misplaced view:

![screen shot 2016-09-06 at 4 44 17 pm](https://cloud.githubusercontent.com/assets/1198851/18290379/37e8d08e-7451-11e6-93d2-4b842884cdf9.png)

**Comment by friedbunny** [comment] 2016-09-06 21:04
Except that fixing the “misplaced view” doesn’t fix the inset problems. (And this view was never 600x600, as IB claims.)

![screen shot 2016-09-06 at 5 01 35 pm](https://cloud.githubusercontent.com/assets/1198851/18290994/cc4017cc-7453-11e6-8252-1532fba48bf0.png)

Making the Mapbox view the base view does solve this problem, however.

**Comment by 1ec5** [comment] 2016-09-06 21:35
> And this view was never 600x600, as IB claims.

Perhaps there was an issue migrating the storyboard to the Xcode 8 format, which no longer has a 600×600 default simulated size.

> Making the Mapbox view the base view does solve this problem, however.

It isn’t recommended to make the MGLMapView the root view unless you intend for it to be the only view in the scene.

In any case, I’m unable to reproduce the visual issue in Xcode 8.0 beta 6 (8S201h) with a test project that uses an MGLMapView as a direct child of the root view, with zero-point constraints on all sides and top and bottom bars. However, Xcode is reporting runtime Auto Layout warnings regarding the logo view, ℹ️ button, and compass container view, as you reported:

```
Layout Issues Group
x-xcode-debug-views://7ffd35f23cb0: runtime: Layout Issues: Vertical position is ambiguous for UIImageView.

x-xcode-debug-views://7ffd35f23cb0: runtime: Layout Issues: Vertical position is ambiguous for UIButton.

x-xcode-debug-views://7ffd35f23cb0: runtime: Layout Issues: Vertical position is ambiguous for UIView.
```

**Comment by 1ec5** [comment] 2016-10-07 06:38
Duplicate of #5549.

**Closed by 1ec5** 2016-10-07 06:38 UTC
Labels: bug, iOS
