### ISSUE TITLE
[iOS] Wrong annotation type provided when target is near the user location

### ISSUE THREAD

**Issue by whiskey** [mapbox/mapbox-gl-native#5743] opened 2016-07-21 09:43 UTC
**Platform:**
iOS 9.3

**Mapbox SDK version:**
Mapbox-iOS-SDK 3.3.1

### Steps to trigger behavior

Then I tap on annotations that are within the 'accuracy circle' of the user annotation all delegate calls like `mapView(mapView: MGLMapView, annotationCanShowCallout annotation: MGLAnnotation) -> Bool` provide me the user annotation instead of the custom annotation of the tapped entity.

![screen shot 2016-07-21 at 11 38 15](https://cloud.githubusercontent.com/assets/149976/17018383/c8f48526-4f37-11e6-8f3e-3bf54b7d340e.png)

### Expected behavior

`annotation` parameter in delegate method is not kind of `MGLUserLocation` when one of the orange annotations is tapped

### Actual behavior

`annotation` parameter  is kind of `MGLUserLocation`

**Comment by fabioknoedtbcgdv** [comment] 2016-07-21 15:19
Exactly the same for me. Was this bug introduced in 3.3.0 or 3.3.1? In 3.2.3 works fine.

**Comment by boundsj** [comment] 2016-07-21 16:34
Noting that this appears to be a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/5571

**Comment by 1ec5** [comment] 2016-07-21 20:14
Yes, duplicate of #5571.

**Closed by 1ec5** 2016-07-21 20:14 UTC
Labels: annotations, iOS
