### ISSUE TITLE
[Android] Marker disappears upon switch from zoom levels 15 to 16

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#8405] opened 2017-03-14 21:31 UTC
**Platform:** Android
**Mapbox SDK version:** 5.0.0-beta.2

### Steps to trigger behavior

 1.  Open simple map activity and place marker
 2. Zoom in and out to show flickering marker
 3.

### Expected behavior

Marker stays pinned to location

### Actual behavior

Marker disappears when the map's zoomed in enough

![giphy](https://cloud.githubusercontent.com/assets/4394910/23923167/d649dbfa-08c2-11e7-891b-9912a61edfdc.gif)

cc: @cammace @Guardiola31337 @tobrun

**Comment by tobrun** [comment] 2017-03-15 10:49
@langsmith can you retest with beta.3 or SNAPSHOT?

Not able to reproduce this with the release branch:

![ezgif com-video-to-gif 19](https://cloud.githubusercontent.com/assets/2151639/23945075/61a195d2-0975-11e7-89c5-2c010ab8e4f7.gif)

**Comment by yperess** [comment] 2017-03-15 20:29
I think this is the same issue I'm seeing on https://github.com/mapbox/mapbox-gl-native/issues/8367

**Comment by tobrun** [comment] 2017-03-16 08:01
I guess you are right @yperess, closing this as a duplicate, @langsmith could you try reproducing this with latest beta/snapshot?

**Closed by tobrun** 2017-03-16 08:01 UTC
Labels: Android, bug
