### ISSUE TITLE
Maps blink

### ISSUE THREAD

**Issue by senatorov** [mapbox/mapbox-gl-native#3988] opened 2016-02-17 14:43 UTC
Hi! after add/remove merker for my location ( android sdk ver 3.1.0 ) on emulator by google

```
private void mapInteraction(Location location, final Context context, final MapView mapView) {
        final LatLng latLng = new LatLng(location.getLatitude(), location.getLongitude());
        CameraPosition cameraPosition = new CameraPosition.Builder().target(latLng) .bearing(0).tilt(5) .zoom(13) .build(); 
        if (marker != null) {
            mapView.removeMarker(marker);
        }
        mapView.animateCamera(
                CameraUpdateFactory.newCameraPosition(cameraPosition), 100, new MapView.CancelableCallback() {
                    @Override
                    public void onCancel() {
                        drawMyPosIcon(context, latLng, mapView);
                    }

                    @Override
                    public void onFinish() {
                        drawMyPosIcon(context, latLng, mapView);
                    }
                });
    }

    private void drawMyPosIcon(Context context, LatLng latLng, MapView mapView) {
        IconFactory mIconFactory = IconFactory.getInstance(context);
        Drawable mIconDrawable = ContextCompat.getDrawable(context, R.drawable.my_location);
        Icon icon = mIconFactory.fromDrawable(mIconDrawable);

        marker = mapView.addMarker(new MarkerOptions()
                .position(latLng)
                .icon(icon));
    }
```

part of map blinks for example street names, buildings. 
Pls help

**Comment by tobrun** [comment] 2016-03-01 12:44
I'm not able to reproduce this on an actual device or genymotion. I believe the source of this problem originates from emulating a device on another chipset. As far as I can tell there is no direct fix for this and I believe this is not really an issue in real world situations. Closing for now..

**Closed by tobrun** 2016-03-01 12:44 UTC
Labels: Android, support
