### ISSUE TITLE
iOS Crash on start after updating to Mapbox-iOS-SDK 3.0.0

### ISSUE THREAD

**Issue by adamszeptycki** [mapbox/mapbox-gl-native#3187] opened 2015-12-04 11:33 UTC
After updating project to Mapbox-iOS-SDK app keeps crashing in `CoreFoundation`CFStringCompare:`
Crash is before `application:didFinishLaunchingWithOptions` is called. Project is in Swift.

Do you have any ideas how to solve that problem?

**Comment by adamszeptycki** [comment] 2015-12-04 11:55
I used cocoapods and your tutorial to integrate map box.

**Comment by 1ec5** [comment] 2015-12-04 16:01
Dupe of #3186. Would you mind providing a full crash log for this issue? Thanks.

**Closed by 1ec5** 2015-12-04 16:01 UTC

**Comment by adamszeptycki** [comment] 2015-12-04 16:25
It looks exactly the same as here:
http://stackoverflow.com/questions/34083200/mapbox-and-parse-ios-api-compatibility/34087004#34087004

**Comment by 1ec5** [comment] 2015-12-04 18:14
Are you linking Core Telephony in any way (for example, by linking some other package that requires Core Telephony)? If so, you’re actually seeing #3112, which is fixed and will make it into 3.0.1. In the meantime, the workaround is unfortunately to ensure that you aren’t using Core Telephony. Sorry for the inconvenience.

**Comment by adamszeptycki** [comment] 2015-12-04 21:09
I don't use core CoreTelephony. This is what I'm getting:

```
CoreFoundation`CFStringCompare:
    0x11074a590 <+0>:   pushq  %rbp
    0x11074a591 <+1>:   movq   %rsp, %rbp
    0x11074a594 <+4>:   pushq  %r15
    0x11074a596 <+6>:   pushq  %r14
    0x11074a598 <+8>:   pushq  %r12
    0x11074a59a <+10>:  pushq  %rbx
    0x11074a59b <+11>:  movq   %rdx, %r14
    0x11074a59e <+14>:  movq   %rsi, %r15
    0x11074a5a1 <+17>:  movq   %rdi, %rbx
    0x11074a5a4 <+20>:  testq  %rbx, %rbx
    0x11074a5a7 <+23>:  js     0x11074a613               ; <+131>
->  0x11074a5a9 <+25>:  movq   (%rbx), %rax
    0x11074a5ac <+28>:  testq  %rax, %rax
    0x11074a5af <+31>:  je     0x11074a5f1               ; <+97>
    0x11074a5b1 <+33>:  leaq   0x3551b8(%rip), %rcx      ; __CFConstantStringClassReferencePtr
    0x11074a5b8 <+40>:  cmpq   (%rcx), %rax
    0x11074a5bb <+43>:  je     0x11074a5f1               ; <+97>
    0x11074a5bd <+45>:  movq   0x34e3c4(%rip), %rcx      ; __kCFStringTypeID
    0x11074a5c4 <+52>:  xorl   %r12d, %r12d
    0x11074a5c7 <+55>:  cmpq   $0x3ff, %rcx
    0x11074a5ce <+62>:  ja     0x11074a5db               ; <+75>
    0x11074a5d0 <+64>:  leaq   0x353199(%rip), %rdx      ; __CFRuntimeObjCClassTable
    0x11074a5d7 <+71>:  movq   (%rdx,%rcx,8), %r12
    0x11074a5db <+75>:  cmpq   %r12, %rax
    0x11074a5de <+78>:  je     0x11074a5f1               ; <+97>
    0x11074a5e0 <+80>:  testb  $0x1, %al
    0x11074a5e2 <+82>:  je     0x11074a613               ; <+131>
    0x11074a5e4 <+84>:  movq   %rbx, %rdi
    0x11074a5e7 <+87>:  callq  0x1108cb8a8               ; symbol stub for: object_getClass
    0x11074a5ec <+92>:  cmpq   %r12, %rax
    0x11074a5ef <+95>:  jne    0x11074a613               ; <+131>
    0x11074a5f1 <+97>:  movb   0x8(%rbx), %cl
    0x11074a5f4 <+100>: movb   %cl, %al
    0x11074a5f6 <+102>: andb   $0x5, %al
    0x11074a5f8 <+104>: movzbl %al, %eax
    0x11074a5fb <+107>: andb   $0x60, %cl
    0x11074a5fe <+110>: cmpl   $0x4, %eax
    0x11074a601 <+113>: jne    0x11074a628               ; <+152>
    0x11074a603 <+115>: leaq   0x10(%rbx), %rax
    0x11074a607 <+119>: testb  %cl, %cl
    0x11074a609 <+121>: je     0x11074a60e               ; <+126>
    0x11074a60b <+123>: movq   (%rax), %rax
    0x11074a60e <+126>: movzbl (%rax), %ecx
    0x11074a611 <+129>: jmp    0x11074a636               ; <+166>
    0x11074a613 <+131>: movq   0x342b1e(%rip), %rsi      ; "length"
    0x11074a61a <+138>: movq   %rbx, %rdi
    0x11074a61d <+141>: callq  *0x355bd5(%rip)           ; (void *)0x00000001115ed800: objc_msgSend
    0x11074a623 <+147>: movq   %rax, %rcx
    0x11074a626 <+150>: jmp    0x11074a636               ; <+166>
    0x11074a628 <+152>: testb  %cl, %cl
    0x11074a62a <+154>: je     0x11074a632               ; <+162>
    0x11074a62c <+156>: movq   0x18(%rbx), %rcx
    0x11074a630 <+160>: jmp    0x11074a636               ; <+166>
    0x11074a632 <+162>: movq   0x10(%rbx), %rcx
    0x11074a636 <+166>: xorl   %edx, %edx
    0x11074a638 <+168>: xorl   %r9d, %r9d
    0x11074a63b <+171>: movq   %rbx, %rdi
    0x11074a63e <+174>: movq   %r15, %rsi
    0x11074a641 <+177>: movq   %r14, %r8
    0x11074a644 <+180>: popq   %rbx
    0x11074a645 <+181>: popq   %r12
    0x11074a647 <+183>: popq   %r14
    0x11074a649 <+185>: popq   %r15
    0x11074a64b <+187>: popq   %rbp
    0x11074a64c <+188>: jmp    0x110746310               ; CFStringCompareWithOptionsAndLocale
    0x11074a651 <+193>: nopw   %cs:(%rax,%rax)
```
I think it is the same thing as #3186.

**Comment by friedbunny** [comment] 2015-12-04 21:48
Try using `v3.0.1-pre.1` in your `Podfile`:

```ruby
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.0.1-pre.1/ios/Mapbox-iOS-SDK.podspec'
```

**Comment by adamszeptycki** [comment] 2015-12-05 11:51
@friedbunny It's working ;)

When version 3.0.1 will be released? Will it be this year?

**Comment by friedbunny** [comment] 2015-12-05 16:26
Should be coming officially early next week.
