### ISSUE TITLE
User location halo becomes solid while navigating

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#6146] opened 2016-08-24 21:41 UTC
**Platform:  iOS**
**Mapbox SDK version: master**
### Steps to trigger behavior
1. Create a simple app with navigation controller
2. Enable user location
3. Navigate away from map page deeper into the navigation controller
4. Navigate back to the map by dragging the left part of the screen
### Expected behavior

The user location halo remains transparent
### Actual behavior

The user location halo turns solid

![simulator screen shot aug 23 2016 1 40 10 pm](https://cloud.githubusercontent.com/assets/1058624/17949074/a5edde6a-6a08-11e6-82b2-570162696fd8.png)

/cc @1ec5 @friedbunny

**Comment by 1ec5** [comment] 2016-08-24 21:46
In MapKit, the accuracy halo behaves a bit differently while segueing: the pulsing does pause while you perform the gesture, but the size of the halo varies by how far you slide the view controller. So while the animation is paused this way, you can “rewind” and “fast forward” by scrubbing back and forth. I’m not sure what determines the animation behavior in this scenario.

**Comment by lilykaiser** [comment] 2017-11-17 23:34
Closing due to ticket age. If this is still a problem, please re-open

**Closed** 2018-12-03 16:50 UTC
Labels: MapKit parity, archived, bug, iOS

**Comment by friedbunny** [comment] 2018-12-03 19:16
I can no longer reproduce this on-device:
<img src=https://user-images.githubusercontent.com/1198851/49395955-e09bbc80-f705-11e8-93a2-5060ae77b6ba.PNG width=300px>
