### ISSUE TITLE
SymbolLayer click not always working (queryRenderedFeatures returns empty list)

### ISSUE THREAD

**Issue by Oyashirox** [mapbox/mapbox-gl-native#12129] opened 2018-06-12 08:18 UTC
**Platform:** Android
**Mapbox SDK version:** 6.1.3 - 6.2.0-beta.2

I followed [this tutorial](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c) to learn how to add custom symbols (I need simple markers, but with Anchors). I faced a problem where tapping the marker was not working (`queryRenderedFeatures` returns an empty list). After multiple interactions with the map (zooming mainly), it starts working/breaking again.

I tried "Mapbox Demo" from which the tutorial come from, and the same behavior is happening as you can see in [this video](https://nextcloud.florianchappa.fr/index.php/s/q8Dt5ZeNt3d8aCC/download)

### Steps to trigger behavior

 1. Create a source and a SymbolLayer, and add it to the map
 2. Add a click listener that calls queryRenderedFeatures

### Expected behavior
When tapping the symbol, queryRenderedFeatures should return the feature

### Actual behavior
Sometimes (most of the time) it returns an empty list. Zooming/dezooming may make it work/break it again.

**Comment by fabian-guerra** [comment] 2018-06-12 14:08
It may be related to https://github.com/mapbox/mapbox-gl-native/issues/11795. I think the fix is going to get included in 6.2.0 according to https://github.com/mapbox/mapbox-gl-native/issues/11795#issuecomment-396236500

Tagging @ChrisLoer and @ansis to double check.

**Comment by ChrisLoer** [comment] 2018-06-12 17:05
Yup, this looks like a duplicate of #11795. Thanks for the report @Oyashirox, we should have a fix out really soon! 🙂

**Closed by ChrisLoer** 2018-06-12 17:05 UTC
Labels: Core
