### ISSUE TITLE
Not loading default camera from style

### ISSUE THREAD

**Issue by fleuverouge** [mapbox/mapbox-gl-native#9511] opened 2017-07-14 08:26 UTC
**Platform: Android**
**Mapbox SDK version: 5.1.0**

Hi, I need to move the map to the center of the current style, and reload the style on demand. So I would like to know if there's any way for Android to archive the same result to resetPostion & reloadStyle functions in iOS SDK?

**Comment by tobrun** [comment] 2017-07-14 11:10
@fleuverouge thank for reaching out, we do not expose reloadStyle though you can use setStyle with the same url to achieve the same result. For resetPosition, get the camera position when the style has finished loading and keep that in memory until you want to reset to that position (you can use CameraUpdateFactory#moveCamera for that). Going ahead and close this as the question is answered.

**Comment by fleuverouge** [comment] 2017-07-21 02:59
Hi @tobrun , thanks very much for your support!

About ResetPosition, My problem is that, after loading a style, I want to move the map to its center. 
In iOS, I set map's style url -> style did finish rendering -> ResetPosition()
It works perfectly.
However in Android, when I load style, I got a whole world map. I tried to use AnimateCamera to zoom into the preferred level, however, since the center of the world map is not the style's center, the map zoomed into the ocean :(

**Comment by tobrun** [comment] 2017-07-21 05:56
@fleuverouge reopening as setting a default style should move the camera to that position.

**Comment by Guardiola31337** [comment] 2017-08-02 12:49
Hey @fleuverouge 👋

The way it works right now in Android is that if you don't specify any style via xml (`app:mapbox_styleUrl`) the default style is loaded behind the scenes (which sets `cameraMutated` to `true`) so the next time that a style is loaded `cameraMutated` is still `true` so [this](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/map.cpp#L729-L735) is not called.

This is the expected behavior so I suggest you to set up your custom style using the `app:mapbox_styleUrl` attribute because that way style properties (`center`, `zoom`, etc.) are respected.

Going ahead and closing here as workaround suggested.
Thanks for using Mapbox and feel free to open new tickets if you have any other questions 😉

**Closed by Guardiola31337** 2017-08-02 12:49 UTC
Labels: Android, bug, starter-task
