### ISSUE TITLE
[iOS] cameraThatFitsShape: direction: edgePadding: should also work with pitch

### ISSUE THREAD

**Issue by d-prukop** [mapbox/mapbox-gl-native#13005] opened 2018-10-02 21:48 UTC
A new method should be added to return a camera that fits a shape while the map is pitched.

**Comment by 1ec5** [comment] 2018-10-03 04:10
Duplicate of #10115.

**Comment by d-prukop** [comment] 2018-10-03 17:43
This is not a duplicate of #10115. That ticket is about the `cameraForLatLngs` method in core. This one is for exposing that capability in the iOS SDK.

**Closed** 2019-04-01 19:38 UTC
Labels: archived, feature, iOS, macOS
