### ISSUE TITLE
visibleFeaturesAtPoint/InRect does not work for all Polygons (esp with holes or non-convex geometries) / Feature Index is broken for Polygon geometries with holes.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#10086] opened 2017-09-28 21:35 UTC
**Platform:**
iOS and Android
**Mapbox SDK version:**
3.5.2 and Master
### Steps to trigger behavior

Experimenting with the mapbox test app visibleFeaturesAtPoint for polygons with holes and "C" shaped polygons. It fails for all such testcases. 

1. FeatureIndex only contains bounding box / extent of geometries.
2. For polygons with holes, consider a point in the hole part. It would be inside the bounding box of the geometry in the feature index. But its actually outside the polygon. The same bug would reproduce for non-convex geometries (e.g. geometry representing the english letter C).

### Expected behavior
visibleFeaturesAtPoint should work for polygons with holes and non-convex polygons. For a point in the hole part it should return zero results.

### Actual behavior
It actually returns two results. (See the explanation above for why it returns 2 results. FeatureIndex contains two entries, one for the exterior ring and the other for interior one).

**Comment by mb12** [comment] 2017-09-28 23:32
After  overlap test on the bbox index, it does do an actual intersection to remove false positives. I changed FillLayer::Impl::queryIntersectsGeometry to use the following modified version and that seems to work for all cases.

```
    bool polygonIntersectsMultiPolygon_Testing(const GeometryCoordinates& polygon, const GeometryCollection& multiPolygon) {
        size_t polysize = multiPolygon.size();
        if(polysize) {
            bool inside_outer_ring = polygonIntersectsPolygon(polygon, multiPolygon[0]);
            if(inside_outer_ring) {
                //point should be inside_outer_ring and outside all inner rings
                for(size_t holeIndex=1; holeIndex<polysize; ++holeIndex) {
                    bool inside_hole = polygonIntersectsPolygon(polygon, multiPolygon[holeIndex]);
                    if(inside_hole) {
                        return false;
                    }
                }
                return true;
            }
            // outside outer poly
            return false;
        }
```

**Comment by fabian-guerra** [comment] 2017-09-29 13:17
Hi @mb12. Thank you for using Mapbox. I am sorry to hear you are having some issues. Could you please help me answer this questions:

1. Did you tried our latest [version](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.4)?
2. Are you using the simulator?
3. Are you trying at a zoom out level?

**Comment by mb12** [comment] 2017-10-02 17:27
@fabian-guerra  The current code does not correctly handle Multipolygons and polygons with holes to remove false positives from GridIndex query. Vector tiles polygon geometries encode multipolygons and polygons similarly, the only difference between them being the winding order. This needs to be taken into account in polygonIntersectsMultiPolygon.

The following would fix it for both Multipolygons as well as regular polygons. 

```
    bool polygonIntersectsMultiPolygon(const GeometryCoordinates& polygon, const GeometryCollection& multiPolygon) {
        std::vector<GeometryCollection> actualPolygonArray = classifyRings(multiPolygon);
        for (const GeometryCollection& actualPolygon : actualPolygonArray) {
            size_t polysize = actualPolygon.size();
            if(polysize) {
                bool inside_outer_ring = polygonIntersectsPolygon(polygon, actualPolygon[0]);
                if(inside_outer_ring) {
                    //point should be inside_outer_ring and outside all inner rings
                    for(size_t holeIndex=1; holeIndex<polysize; ++holeIndex) {
                        bool inside_hole = polygonIntersectsPolygon(polygon, actualPolygon[holeIndex]);
                        if(inside_hole) {
                            return false;
                        }
                    }
                    return true;
                }
            }
        }
        return false;
    }

```

**Comment by fabian-guerra** [comment] 2017-10-03 17:26
Tagging @kkaefer for prioritization.

**Comment by kkaefer** [comment] 2017-10-06 10:30
Likely a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/9686

**Closed by kkaefer** 2017-10-06 10:30 UTC
Labels: Android, annotations, bug, Core, iOS
