### ISSUE TITLE
Floating points are not honored when evaluating the symbolSortKey

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#16114] opened 2020-01-13 21:27 UTC
When `iconAllowsOverlap` is `false` and the values for the `symbolSortKey` evaluate to doubles, the ordering of those values doesn't change the z-level of where the icons are drawn in a style layer. The same feature will always appear on top of the other whether you reverse the values for the sort (by multiplying by -1) or leave them as-is.

Somewhat similar to https://github.com/mapbox/mapbox-gl-native/issues/15964.

### Steps to reproduce

 1. Add a symbol style layer to the map with 2 overlapping features
 2. Set `textAllowsOverlap` and `iconAllowsOverlap` to `false`
 3. Set `textOptional` to `true`
 4. Ensure both features have values for the `symbolSortKey`
      - Make sure these values are doubles. I used `0.99999896` and `0.99999898`

### Expected behavior

I'm trying to get the feature with the higher sort of `0.99999898` to appear on top.

### Actual behavior

With the floating points above, the feature with the sort value of `0.99999896` will always be on top. This is also true if you reverse the order by multiplying the sort values by `-1`.

If I set `iconAllowsOverlap` to `true`, the sort order appears to be honored and the feature with the larger sort of `0.99999898` is drawn on top. 

This gist replicates the issue: https://gist.github.com/johnnewman/d69b5c28c9f8d0895f9bb5e36eb1baeb.

Here is a working project with the code from the gist. Just supply an API key in AppDelegate.swift.
[IconOrderingProject.zip](https://github.com/mapbox/mapbox-gl-native-ios/files/4055818/IconOrderingProject.zip)

### Configuration

**Mapbox SDK versions: 5.6.1** 
**iOS/macOS versions: iOS 13.3** 
**Device/simulator models: iPhone 7**
**Xcode version: 11.3**

**Comment by chloekraw** [comment] 2020-01-14 05:46
Whether the sort keys are integers or floats doesn't affect the cause of the behavior you're seeing, which is that symbols are not sorted by their sort keys during placement when overlap is disabled. It should also be fixed by https://github.com/mapbox/mapbox-gl-native/pull/16023 just like the other ticket you opened and linked, which we're working towards getting into the next release.

cc @ansis

**Comment by johnnewman** [comment] 2020-01-14 15:06
Thank you for checking this out! I will keep my eyes on that PR.

The odd thing I noticed about this issue was that if I switch the floats to integers like `1` and `2`, then the symbols do appear to be influenced by the sort key, I just have to multiply by -1 and the lowest value will draw on top. This same approach does not work with the floats.

| red = -0.99999898, blue = -0.99999896 | red = -2, blue = -1 |
| ---- | ---- |
| <img src="https://user-images.githubusercontent.com/1591735/72354748-494cbb00-36b4-11ea-8b1c-053851e2df8f.jpeg" width=200 /> | <img src="https://user-images.githubusercontent.com/1591735/72354838-608ba880-36b4-11ea-8d28-5f34553efc49.jpeg" width=200 /> |

**Comment by chloekraw** [comment] 2020-01-16 08:35
@johnnewman can you reproduce that reliably for sets of points at different locations in tiles? Based on previous testing we've done, I think this is just coincidence. There is some kind of deterministic order for which icons win in collision detection within a tile.

**Comment by johnnewman** [comment] 2020-01-16 20:01
@chloekraw So far I've only seen the feature with `-2` take priority and draw on top of the `-1`. I've randomly generated about 60 lat/lon values to confirm.

Hopefully this was a valid test: I was updating the `coordinate` property of the two `MGLPointFeature` objects, reassigning the shape of the `MGLShapeSource`, and taking note of the new display order when the features redrew.

**Comment by chloekraw** [comment] 2020-01-16 20:54
Okay, thanks! We’ll take a look then @johnnewman. Appreciate the time you took to test.

**Comment by ansis** [comment] 2020-02-11 16:55
Yep, it looks like we should probably switch these from `float`s to `double`s internally. In the meantime can you work around this by reducing the precision necessary for your sort keys?

**Comment by johnnewman** [comment] 2020-02-12 16:35
This makes sense and we can definitely work around it 👍. For context: we have millions of potential sort values and I was normalizing them to all be between 0 and 1 before passing them into the style layer. Oops! Thank you @ansis.

**Closed** 2020-08-16 20:26 UTC
Labels: archived
